### ISSUE TITLE
Selecting a deleted thesauri on a template and saving it, should return a server error saying the thesauri no longer exists (5 pts)

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazi#1003]
- Right now it can happen that you select a thesauri that has been just deleted and the server saves it no problem, comming back to the template results in an error when trying to edit the property with the unexistent thesauri.
- Make sure the async validation happens on the "model" and not in the route.

**Comment by konzz** [comment]
This can be easily replicated using 2 tabs
