### ISSUE TITLE
Add sub-items inside the menu

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1019]
We have a request to allow adding sub-items inside the menu. This will disengage the navigation through the menu instead of force users to research through the filters, for example:

- Home
- Reports
- Assembly
-- Agenda
-- Declarations
-- Decisions
-- Resolutions
-- Motions

Where:
- Assembly is a link to the library with all 5 document types activated.
- Each sub-item is a link to the library with that document type activated.

However is not as straigtforward as it seems because adding nested menu to the app normally worsen the navigation and deteriorate the user experience.

**Comment by kjantin** [comment]
Related to #1070

**Comment by danicatalan** [comment]
Up an increasing priority because another request from a project.

**Comment by txau** [comment]
@danicatalan @kjantin I think we should develop this, it will help a lot in certain instances with many links in the menu.

**Comment by simonfossom** [comment]
[Design](https://www.figma.com/file/xjsz7r65epN4B0b96zilac/uwazi-designs?node-id=133%3A0)

**Comment by konzz** [comment]
Closed in favour of #3826
