### ISSUE TITLE
Timeline items doesn't show the title of the item when cursor is hover

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1020]
On timelines, all the item should show the browser native tooltip with the title when the user hovers the item:

![screen shot 2017-05-22 at 16 24 31](https://cloud.githubusercontent.com/assets/6364153/26313558/85dd8c82-3f0b-11e7-8a78-ec3694856325.png)

Some item spheres doesn't have a `title` attribute, so if the user hovers the item, **the tooltip doesn't appears**.

- - - - - -

**How to reproduce it**

https://cejil.uwazi.io/es/entity/9r9kmpgnt3ygmn29

- Items that are dates (blank spheres) are working as expected.
- Items that are documents (the colorful spheres) doesn't show the tooltip. They must have a title to show it when hovered.

**Comment by danicatalan** [comment]
Not priority, moving to next.

**Comment by danicatalan** [comment]
@RafaPolit Can we check if this is deployed on CEJIL? Still not working on production.

**Comment by txau** [comment]
- [ ] Also timelines should show dates in both causas y medidas provisionales regardless of the label of the field.

**Comment by danicatalan** [comment]
@RafaPolit we can check together this.

**Comment by danicatalan** [comment]
I created a new issue to fix @txau's comment.

@RafaPolit please check why the titles are not working on production and close this issue when it's fixed. Thanks!

**Comment by RafaPolit** [comment]
This fix has not yet been deployed, but it is implemented and merged, hence why this was closed.

I'm closing this issue again.  For further requests, please create new issues.
