### ISSUE TITLE
Create document/entity templates without drag&drop interface

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1023]
This will fix:

- [x] Better UI on Desktop.
- [x] Allow template creation on Mobile.
- [x] Fix E2E tests.

**Comment by danicatalan** [comment]
This is the concept for adding properties with clicks. We keep the _cursor: move_ to allow drag and drop but also let users add with click on both Desktop and Mobile.

![screen shot 2017-05-30 at 18 09 03](https://cloud.githubusercontent.com/assets/6364153/26593078/2187daea-4563-11e7-9f59-eed3a6a37a93.png)

@daneryl do you think it's enough to also implement proper E2E tests to this section?

**Comment by kjantin** [comment]
Maybe we should consider editing the "Drag Properties Here" text so that mobile users don't assume that's the only way to add a property?

**Comment by danicatalan** [comment]
Waiting to implement #1059 before PR this issue.

**Comment by danicatalan** [comment]
Will be implemented in 1077.
