### ISSUE TITLE
User friendly format for date introduction

### ISSUE THREAD

**Issue by tuxpiper** [huridocs/uwazi#1024]
In the case of Japiqay, we are finding that the textual input date enforces a format that is not comfortable for these specific users : i.e. : "Jan 01, 1999" , which is pretty much alien to Peru .

For this specific user we would like to use the format they are used to: dd/mm/yyyy (i..e 01/01/1999)

**Comment by danicatalan** [comment]
Hi @tuxpiper, I'm going to review options to allow admins configure the date introduction. Thanks for the feedback.

**Comment by tuxpiper** [comment]
Thank you Dani!

**Comment by danicatalan** [comment]
Hi @tuxpiper, we've been discussing about this issue and possibly the best solution is:

- Allow you to select which one of the three standard formats do you want to use:
´YYYY-MM-DD´
´DD-MM-YYYY´
´MM-DD-YYYY´
- Allow you to select which one of the three standard separators do you want to use:
´-´
´/´
´.´

That way we cover almost every numeric format in the world (based on our [time parser library](https://momentjs.com/)) and also is easy for you to select which one of all the combos do you want to use. We will keep the human-readable format on the cards.

You can read more information in the issue mentioned above (979).

I would like to listen your thoughts about the solution before the implementation to be sure that this meets the requirements and solves your issue. Thanks!

**Comment by tuxpiper** [comment]
That sounds pretty good to me @danicatalan ! Would the parser be lenient with single digits as well? i.e. "1/1/1999" instead of "01/01/1999" .

**Comment by danicatalan** [comment]
@tuxpiper I hope is not complicated :)

**Comment by danicatalan** [comment]
@tuxpiper not going to develop the single digits parser right now, so dates need to be fully completed "01/01/1999". Thanks for your feedback!

Closing this, will be implemented as described in [1053](https://github.com/huridocs/uwazi/issues/1053).

**Comment by tuxpiper** [comment]
alright thanks!
