### ISSUE TITLE
Attachments in other languages dont sync with original language

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1026]
### UPDATE 1

We decided to prompt users asking if they want to upload the attachment in just this language or in all languages.

- - - - -

When a document has a fallback in other languages, the PDF, table of contents and references are sync in the other language. This is not happening with attachments.

**Current behaviour (BUG)**

- When user uploads a document (pdf), this is synced in all languages until he goes to another language and replace the original document with a new pdf.
- When user adds another file as an attachment, it **only appears in the language** you have uploaded the file.

The bug is causing the same document in three languages, but different attachments ([example](https://cejil.uwazi.io/es/document/ijqs96e354i5p14i)).

**Expected behaviour**
- When user adds a file as an attachment to a document, it **appears in all languages** where the document is synced.

The expected behaviour is the same document in three languages with the same attachments,
or different documents in each language with different attachments ([example](https://cejil.uwazi.io/es/document/ijqs96e354i5p14i)).

**Comment by danicatalan** [comment]
This was working on our current fixtures, as you can see Artavia Murillo was uploaded once -the PDF and the DOC attached- and both are available on all languages.

![image](https://cloud.githubusercontent.com/assets/6364153/26727233/4cc76668-47a6-11e7-8a9f-110bf253287c.png)

![image](https://cloud.githubusercontent.com/assets/6364153/26727256/67b12a72-47a6-11e7-9f2b-52d60505b278.png)

Now I uploaded an attachment in Spanish but is not synced in English.

**Comment by kjantin** [comment]
Would the next part of the *Expected behavior* be that the user can replace the fallback attachment with a different file if they wanted to? (for example, if that attachment was available in another language, they would want to attach the translation and not the fallback version of it)

**Comment by danicatalan** [comment]
Right now the expected behaviour is just synced uploads between languages that had the same base document.

**Comment by kjantin** [comment]
Would it be possible to provide an option to the user to select whether or not they want this attachment displayed in all languages? That way, it doesn't matter whether or not they have edited the metadata in another language (breaking the fallback system) - they can still sync those attachments if they want.

**Comment by danicatalan** [comment]
- [ ] Prompt users asking if they want to upload the attachment in just this language or in all languages.

**Comment by danicatalan** [comment]
As we talk on our last call, once a user uploads an attachment we will ask if they want to upload it on once language or in all of them.

The expect action in most of cases is to upload the attachments to all languages (the same when uploading the document on _My files_), so I decided to just use the green button on **"Upload to all languages"**.

Do you think this will be enough to solve the problem?

![prompt](https://user-images.githubusercontent.com/6364153/28453423-a13267b2-6df7-11e7-8be7-58c34e1b8450.png)

- - - - -

![n5djkqsgjx2](https://user-images.githubusercontent.com/6364153/28453343-37231902-6df7-11e7-835d-b2cfa7f447bb.gif)
