### ISSUE TITLE
Error processing certain documents

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#1031]
There are certain PDFs reported to fail conversion, and the system remains in 'processing' forever on client until reload.

Attached are some of the files reported as failing.

On local, GM gives the following error:
```
gm convert: Unable to sync cache (check temporary file disk space) (/tmp/d20170523-5594-1vulpvt/gmfAzw5d) [No space left on device].
```
[INF-F-BAGUA_MINORIA_FALLA_LA_MADRID.pdf](https://github.com/huridocs/uwazi/files/1036210/INF-F-BAGUA_MINORIA_FALLA_LA_MADRID.pdf)
[Ambrosiano-Andino84.pdf](https://github.com/huridocs/uwazi/files/1036211/Ambrosiano-Andino84.pdf)
[narcotrafico.pdf](https://github.com/huridocs/uwazi/files/1036212/narcotrafico.pdf)

@tuxpiper

**Comment by tuxpiper** [comment]
We were expecting this to be fixed last week, but it still seems to be happening.

Any ETA for fix?

**Comment by tuxpiper** [comment]
Attaching fresh screenshots from today:

![screen shot 2017-06-06 at 14 08 16](https://cloud.githubusercontent.com/assets/467393/26828912/b7bd336a-4ac3-11e7-8c03-364896506b1c.png)
![screen shot 2017-06-06 at 14 04 04](https://cloud.githubusercontent.com/assets/467393/26828913/b7c7773a-4ac3-11e7-9f79-80fa41752c1f.png)

**Comment by konzz** [comment]
@tuxpiper We detected some problems and we are working on it, we expect to have this finish for the next deploy.

Could you please share here some of the documents that gave you errors so we can check them and see if we detect other issues.

Thanks

**Comment by tuxpiper** [comment]
Thank you @konzz ! You will find sample documents linked up there in the issue description. We provided those.

**Comment by daneryl** [comment]
@tuxpiper this issue is solved, you should not have more problems with this kind of documents, this will be available on the next deploy. normally this is on Mondays, im going to do an early deploy, you will be able to process this files in a couple of hours.

**Comment by txau** [comment]
@daneryl what was the problem, how was it solved?

**Comment by tuxpiper** [comment]
Thank you @daneryl ! Confirmed on our side that, files that were previously failing to process, are smoothly working now.
