### ISSUE TITLE
Implement date range field type

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#1032]
Japiquay has, as Cejil, requested multi date range fields.

It would be interesting if we could extend those type of properties that are universally useful to all instances.

@tuxpiper

**Comment by txau** [comment]
Lets discuss in our next team call.

**Comment by tuxpiper** [comment]
@RafaPolit @txau  A key question for us here regarding this:

Once the extension has been applied to our instance, would that keep compatibility with any present documents & metadata? Or would we be looking at starting from scratch with the data?

**Comment by kjantin** [comment]
I think including a date range would be really useful for groups who want to use Uwazi to investigate human rights abuses, so that users can search and filter for cases that are within a date range.

**Comment by txau** [comment]
@kjantin Actually date range search is already implemented in Uwazi.

What we are talking about here is to have fields that support multiple dates (ie. date start - date end). I'm not so sure about wanting that functionality for everyone. Every new field type we commit to create, is a new field type we have to maintain.

**Comment by kjantin** [comment]
Sorry if I wasn't clear. I mean that having a date range field (not just the ability to search for dates within a certain range) with a start and end date would be helpful to many. There are many events that have a start and end date, not just one date, and I can imagine that capture these ranges in one field would be really helpful, and would allow someone to filter/search on "tell me all the events that were active on June 6, 2015" and it could find any event whose date range includes that date. 
As far as I understand it, that feature is not available in Uwazi now.

**Comment by konzz** [comment]
We have these current fields regarding to dates:
- Date
- Multi Date (only shows in cejil)
- Multi Date range (only shows in cejil)

We want to create a Date Range field, and make the Multi Date and Multi Date Range appear in all instances?

@kjantin I would say that we close issues that are for discussing, and create issues with clear objectives referencing the discussion issue.

**Comment by kjantin** [comment]
I know that a Date Range (single) field has been requested (by Japiqay) so yes let's have that appear in all instances. But I don't know about the Multi Date and Multi Date Range use cases or requests - since @RafaPolit created this issue, maybe he can provide more information/clarification?

Yes sounds good that we can close issues that are for discussing and create issues with clear objectives. I think this particular issue turned into a discussion because the description of it wasn't clear so we discussed what we thought it meant.
