### ISSUE TITLE
Some keys are missing in Settings > Translations

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1036]
Some keys are missing in translation section, on Settings. In this case, "Entity" is missing inside the label:

![screen shot 2017-05-30 at 10 12 49](https://cloud.githubusercontent.com/assets/6364153/26574173/aa14b920-4520-11e7-94ba-1cfe9ae5ffa8.png)

**Comment by kjantin** [comment]
Fixed!
