### ISSUE TITLE
Keep sidepanel open if changing language

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1041]
We need to think about keeping sidepanels opened if an admin changes from one language to other.

This is not critical while navigating as a user, because normally you change once the language, but as admins it's very painful to manage languages with this workflow.

**Current behaviour**

- Search a document in Spanish.
- Open sidepanel.
- Edit metadata.
- Change to English -> _Sidepanel is closed_.
- Search again the document in English.
- Open sidepanel.
- Edit metadata.

**Expected behaviour**
- Search a document in Spanish.
- Open sidepanel, edit metadata.
- Change to English -> _Sidepanel remains opened_.
- Edit metadata.

**Comment by txau** [comment]
This is not going to be implemented.
