### ISSUE TITLE
Ideas for improvements to the Uwazi translation system

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1042]
Some users' feelings about our current translation system:

- [x] Our current workflow to uploading documents in different languages (upload in English > enter inside the document > change the language > go to attachments > reupload the document) is too much complicated.
- [ ] Adding a text field in different languages is also complicated because admins need to change the language too.
- [ ] Text tools are sync if the same document is spread in diff languages. It's difficult to review which documents have the same doc for every language and which ones have different documents for each language.
- [x] Review attachments. Now attachments are not sync between languages, but they need to be sync too.
- [ ] Review the translate status on the whole collection, for UI and for documents / entities. We have tools to translate everything but it's not easy to now each translation status. - issue #931 
- [ ] Think about other approaches without fallback method:
    - Documents just in English > UI in English, French and Arab.
    - Documents in English, French and Arab > UI just in English.

**Comment by kjantin** [comment]
For my own clarification, if a user has document in English, and the same document also in French, they need to upload/publish the document to Uwazi while in the English interface, and then switch to the French interface and upload/publish the document in the French interface? When they do this, users will see the English document when on the English interface (and not the French version), and the French document on the French interface (and not the English)?

**Comment by txau** [comment]
@kjantin that is correct.

**Comment by txau** [comment]
Uwazi's language paradigm has changed and this assessment needs revision.
