### ISSUE TITLE
Visual feedback while using the filters is not obvious

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1044]
Priority sorting is working great, but now there are tweaks we need to fix.

One example is using filters. When using filters we expect the document list change, but if the sorting is too strong, those documents can be at the end of the list.

Users wait until the list is updated, but if those documents are not displayed we don't show any feedback to the users (just change the total documents displayed on the list). It feels confusing.

We need to improve the visual feedback after performing a search with the filters. Some ideas:

- Add some visual feedback on total documents displayed.
- Trigger a global loader every time a user performs a search.

**Comment by kjantin** [comment]
Global loader is implemented!

**Comment by danicatalan** [comment]
Reopen this issue.
