### ISSUE TITLE
Allow admins to change input[type="date"] format

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1053]
Implements #979 + #1024. HTML ready on `1053-date-format` branch.

- [ ] Allow admin to choose 3 different styles to write dates on inputs:
`YYYY-MM-DD`
`DD-MM-YYYY`
`MM-DD-YYYY`

- [ ] Allow admin to choose 2 different styles of separators:
`/`
`-`

![screen shot 2017-06-01 at 16 45 55](https://cloud.githubusercontent.com/assets/6364153/26685254/d807889c-46e9-11e7-919f-57ec5dfe90c4.png)

**Comment by RafaPolit** [comment]
Perhaps label it: Date Input Format to avoid confusion as to what exactly this format will encompass?

**Comment by danicatalan** [comment]
Agree. Also like "Date input".
