### ISSUE TITLE
When creating connections, improve the way users find the target document/entity

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1064]
While creating a connection, the search box is not useful because the search results are sorted too randomly. In this case, I needed to scroll to find my entity. Also you can notice there are documents above and below the entity with no reference to the keyword on the title.

![improve-connections-search](https://user-images.githubusercontent.com/6364153/26930589-26ef2fe0-4c5e-11e7-8658-e061a936a2ac.png)

Users want to create connections with a well known entity (they aren't discovering, they are searching for something specific and they know the target's title). I don't know if we need to remain cards without the keyword on the title, I think it's adding noise to the results list, but I'm absolutely convinced users want to find by title in this specific case.

- - - -

**To implement**
- [x] Modifiy the search logic to give priority to documents and entities with the keywords in the title.

**Comment by kjantin** [comment]
Related to #878

**Comment by danicatalan** [comment]
More info to reproduce it:

![image](https://user-images.githubusercontent.com/6364153/27548039-032e6650-5a98-11e7-9c51-34c3aead5884.png)

Want to connect with **Penal Castro Castro** entity. Doesn't appear.

**Comment by txau** [comment]
Countries don't appear either?

**Comment by danicatalan** [comment]
@txau entities will appear if the keyword is not using inside documents. This is a test with a very specific entity name:

![image](https://user-images.githubusercontent.com/6364153/27650821-73e11bbe-5c36-11e7-98c4-026cb8304569.png)

In your specific case, there are country names in every document, so those documents have priority and Countries will never appear on that list.

**Comment by txau** [comment]
Ok. I think we should reduce the size of the results. Maybe place the type after the title in a similar way to entities' titles.

**Comment by konzz** [comment]
@danicatalan we need to wait until [ ] #965 is finished, @daneryl is changing the code related to search and better wait until it's done.

**Comment by danicatalan** [comment]
In addition to the code related to the search, I move this issue to UX to improve the connection interface this sprint.

**Comment by danicatalan** [comment]
UI updated with styles to be more coherent with our current filters.

There also some extra changes that need to be implemented by a developer:

- [ ] The multiselect for connection type is mocked up on HTML (was previously a Select element).
- [ ] Add the possibility to connect multiple documents at once (to be implemented in a separated task).

![image](https://user-images.githubusercontent.com/6364153/27966572-ff505830-633f-11e7-9476-c9021e3ccf24.png)

**Comment by danicatalan** [comment]
965 was implemented but there are still issues with this search result.

Most searchs are prioritising full text search instead of title search, so if a user wants to connect to an entity is highly possible to not find that entity on that search:

![s1xhdehphm](https://user-images.githubusercontent.com/6364153/28263438-0fba0e24-6ae7-11e7-8981-6561ae8926b7.gif)

In this case I'm trying to connect a document with its process entity (called "Garibaldi") but I can't because it doesn't appear on the search.

**Comment by txau** [comment]
A reminder about this task. We need to decouple this search from the library search. We do not want full text search in this results AT ALL. We only want title search.

So we do not need to wait for #965 or anything.

**Comment by daneryl** [comment]
@dani i have solved the search issue on (a branch) by only searching by title and it seems to work properly.

do you have those designs in a branch ?

**Comment by danicatalan** [comment]
Nice, thanks @daneryl. The styles are on `1064-connections-sidepanel` branch.

**Comment by daneryl** [comment]
@dani created a PR #1200 with the styles merged and some minor css tweeks, do a quick css review pls.
