### ISSUE TITLE
Render Connection types on documents with more visual difference between them

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1065]
We did a great job rendering connections on entities, but we still ned to improve our connections on documents.

In this example, we have three connections type:

- It's clear that Batman **belongs to** DC, maybe because the different color on the blue tag makes a visual separation with the other cards.
- Instead is not clear the difference between all the Comic Characters. The connection type is obfuscated inside the metadata and is not clear which character is **Ally** or **Enemy**.

![image](https://user-images.githubusercontent.com/6364153/26931140-caa2487e-4c5f-11e7-8ae1-b6a13a9a7762.png)

**Comment by danicatalan** [comment]
We are going to implement the relationship navigator soon (the filters inside entities). This visual feedback won't be needed because connections and document types will be rendered as a filter instead of direct cards:

![image](https://user-images.githubusercontent.com/6364153/29462530-f94f9890-842f-11e7-9eb4-e42f4844616e.png)

**Comment by txau** [comment]
@danicatalan I guess this is fixed in the new relationships
