### ISSUE TITLE
Item component render is Slow, rendering 30 takes around 600ms

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazi#1066]

**Comment by txau** [comment]
We are experiencing very slow rendering in some areas, idk if its related:
- Loading side panel in library when the selected item has many connections.
- Loading entities with many connections.

**Comment by daneryl** [comment]
improvements on the whole app and specifically big ones on library/uploads.

@txau 
> We are experiencing very slow rendering in some areas, idk if its related:
> 
> Loading side panel in library when the selected item has many connections.
> Loading entities with many connections.

this cases are faster than before, but still a bit slow because we are rendering 800 or so connections, we need to think about a better solution for this or implement lazy render on those lists, maybe create another issue for this ?
