### ISSUE TITLE
Sometimes can't edit page contents

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1067]
Looks like an intermittent bug, I haven't been able to find a pattern for reproducing it. I'm trying to update some URLs in some pages (in CEJIL's instance).

**Comment by RafaPolit** [comment]
@txau Albert was doing some maintenance in the servers: restarting elasticsearch and other stuff... could that be it?  Is it still happening?

But its not the first time this behavior has come up... where the network responses 'coherent' or were they timedout or throwing server errors?

**Comment by txau** [comment]
Is still happening. I was getting JS errors. When I reload the browser they go away and I'm able to save. So I had to refresh several times to be able to edit all the pages.

Still I haven't spotted any patterns but, I receive this JS error.
![screen shot 2017-06-09 at 09 17 26](https://user-images.githubusercontent.com/489831/26982838-f345040a-4cf6-11e7-978c-bce1d73c3b70.png)

Another lead may be I'm working with several tabs open, in different languages. So maybe having a tab open with on language, opening another tab and switch language is causing this?
