### ISSUE TITLE
Research interoperability between Uwazi to existing mobile apps for data submission using Open Data Kit

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#1068]
What would it take for Uwazi to connect to mobile apps, if the mobile app has utilized the [Open Data Kit](https://opendatakit.org/ ) to guide their development? 

This way, we could use an app like [KoboToolbox](http://www.kobotoolbox.org/) to allow users to submit info to Uwazi via their mobile phone.

**Comment by txau** [comment]
- Is ODK compatible with Kobo?
- Can those apps work off-line? Because Uwazi's forms are already mobile ready, so the only advantage I see is offline collection of data.

**Comment by whyfrycek** [comment]
Yes and yes.

**Comment by kjantin** [comment]
Other mobile apps to consider for integration:
https://open-archive.org/
https://www.whistlerapp.org/

**Comment by txau** [comment]
This will eventually come from a project.

**Comment by kjantin** [comment]
We are currently looking at https://hzontal.org/tella/ for integration

**Comment by txau** [comment]
I guess this issue is being researched by our team in other spaces. I'm closing until we have something to implement.
