### ISSUE TITLE
Slow uploads for AU law and CJGEA - processing forever

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#1074]
Thanks @konzz and @daneryl  for the (distressing :) ) chat yesterday. Now, on the slow uploads:
1. I have asked for the pdfs. When they send to me will forward to you. 
2. To confirm, on CJGEA instance, yes, the upload is processing for days: one from June 8 and another from June 13. I have just added another now.. see screenshot below. CGJEA password is OnlineDatabase. This is similar to what I mentioned about the AU law one...
<img width="960" alt="slow processing" src="https://user-images.githubusercontent.com/22650647/27114206-ade60a8a-50ca-11e7-86e3-7e61d860c663.png">

**Comment by danicatalan** [comment]
Hi @HSips thanks for your report. We are currently working on this issue with max priority to solve the problem. I will let you know when the upload is available again.

Thanks for your patience!

**Comment by HSips** [comment]
@danicatalan Thanks so much. Pushing to get the pdfs to send to you.
Also, sorry but just realised I had not mentioned this. Thanks a lot for the addition to the date choosing options that allows user to jump years quickly instead of tapping through months. Working on some docs now from 2005 and it is SUPER helpful!

**Comment by danicatalan** [comment]
@HSips we fixed and deployed this just some minutes ago. Can check if you can upload the documents faster?

If the old ones are still on processing status, please delete them before trying to reupload again to have Uploads clean of processing files.
