### ISSUE TITLE
Ability for admins to access a log of recent activity

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#1087]
As an admin, I would like the ability to access a log of recent activity performed on the site, such as: 

- when documents/entities are uploaded and by whom
- when properties are added to which document/entity and by whom

**Comment by kjantin** [comment]
Log edit/delete calls
    Present data in a user understandable way
    Log the post data only in database (users can't see it)
    Track user and dates
    Action type, model
    Pagination

Estimate: 4-6 days

**Comment by RafaPolit** [comment]
This has been moved right to the top of the priorities.

For the time being, we will not be logging POST data.  There is a backend service that is already taking care of that for development purposes.  Admins will not require this, at least with the MVP we are currently proposing.

**Comment by RafaPolit** [comment]
- [ ] Add placeholder to find
