### ISSUE TITLE
View and edit metadata: remove the grey background boxes

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#109]
@danicatalan we have to discuss this sometime soon.

**Comment by danicatalan** [comment]
Sure. I'm going to upload some examples so we can to discuss further. They are useful for both https://github.com/huridocs/uwazi/issues/109 and https://github.com/huridocs/uwazi/issues/110.

**Comment by danicatalan** [comment]
![nobck-nobox](https://cloud.githubusercontent.com/assets/6364153/15801384/30ab43d6-2a93-11e6-9585-7b1d79616462.png)

![darkbck-nobox](https://cloud.githubusercontent.com/assets/6364153/15801382/30aafcaa-2a93-11e6-9b8c-7c257db83d7a.png)

![whtbck-nobox](https://cloud.githubusercontent.com/assets/6364153/15801383/30ab4930-2a93-11e6-8f63-7acd02303efc.png)

![whtbck-whtbox](https://cloud.githubusercontent.com/assets/6364153/15801381/30aaed78-2a93-11e6-92f1-4ef1c2217a97.png)

![whtbck-greybox](https://cloud.githubusercontent.com/assets/6364153/15801385/30ab6884-2a93-11e6-878c-c99539de5105.png)

![full-width-box](https://cloud.githubusercontent.com/assets/6364153/15801380/30aaa444-2a93-11e6-8c97-09a84b638258.png)
