### ISSUE TITLE
Highlighted area goes off the page in some instances

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#1092]
See how the highlighted section on line 5 of the paragraph on [this PDF](https://afchpr-commentary.uwazi.io/en/document/dp0pb0f0yi34413qizfxenrk9) goes beyond the text area. Is this because of the PDF itself? Or something we can fix in Uwazi?

![image](https://user-images.githubusercontent.com/354426/27340127-a52e4740-55a7-11e7-8070-098d3371a823.png)

**Comment by danicatalan** [comment]
OCR is doing strange things with fonts. This need to be checked by dev team.

![image](https://user-images.githubusercontent.com/6364153/27385850-3b494b34-5694-11e7-8b2b-8566cebd04e2.png)

**Comment by nwyu** [comment]
No longer an issue. Closing.
