### ISSUE TITLE
Delete error on missing/lost files

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#1094]
@konzz @daneryl I have deleted the missing/lost files from the AU law instance. However, about 17 files, marked 'EX CL' are refusing to delete.. gives an error message.
Kindly advice
<img width="960" alt="delete error" src="https://user-images.githubusercontent.com/22650647/27376036-a5704186-5679-11e7-90a1-fdc1f9d2f62c.png">

**Comment by RafaPolit** [comment]
@HSips 

Apparently some process (probably a purge we did of those documents with missing files) correctly deleted the entities from the Database, but kept the Elasticsearch indexing of those entities.

I have re-indexed your Elasticsearch index and now the upload section has re-synced with the database. 
 As expected, those entities are no longer showing.  Just to emphasize, these items were correctly reported in the database as deleted, they were just still lingering in the engine we use for searching those items.  After an automated re-sync, they are no longer in the Elasticsearch index.

I am closing this issue as resolved, feel free to comment further if you see any other inconsistencies.

Thanks,
Rafa.
