### ISSUE TITLE
CGJEA instance needs only English

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#1095]
The CJGEA instance is currently in Spanish and English. CJGEA will need only English. Kindly consider removing the Spanish version. @konzz

**Comment by danicatalan** [comment]
Related to #956.

**Comment by txau** [comment]
@HSips is this is valid?

**Comment by HSips** [comment]
Yes it is. I need to push them to get acting on their instance though..

**Comment by konzz** [comment]
@HSips @txau Maybe we can add this to sprint next week to see how we proceed to remove the language.
