### ISSUE TITLE
The curious case of disappearing dictionaries

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#1096]
Hey guys, so I have been noticing that sometimes I cannot find a thesaurus or two from time to time, and I kept assuming that it could be me.
Yesterday, had a discussion with one of the students working on the AU law instance and she also thought the same, and assumed I was deleting thesauri. Unfortunately I cannot tell what when how it happens.. well, sometimes after I have published a document, when I try to edit it in public library I cannot find a thesaurus..
Please just keep this in mind..
@kjantin @konzz @daneryl @danicatalan

**Comment by kjantin** [comment]
@HSips please provide more info, such as:

- When you are in the public library, what document are you in when you can't find the thesaurus? 
- What is the property that hosts the missing thesaurus? 
- Are you unable to find the thesaurus when you go to the settings section? 
- What was the name of the thesaurus?

Thanks!

**Comment by HSips** [comment]
Thanks @kjantin .
That's precisely my point. Just realised some thesauri are missing. Have not kept track.
The property is 'Theme/topic'
The thesauri that seem missing in public library are not missing when adding metadata to docs on Uploads. 
Can only think of one. 'African Common Position' - because I have been trying to use it more of late...

**Comment by txau** [comment]
@HSips since this is impossible to replicate, I'm closing the issue for now. Please reopen if it happens again.

**Comment by HSips** [comment]
@txau OK.. will do
