### ISSUE TITLE
Pro tip about multiple selection is not usable in the context of connections

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1102]
![screen shot 2017-06-28 at 09 58 20](https://user-images.githubusercontent.com/489831/27648088-a749003a-5bea-11e7-9427-5452ef61795d.png)

**Comment by danicatalan** [comment]
Once we have #1370 implemented it make sense to have multiselection, so maybe we should close this issue and open a new one to implement that feature.

**Comment by txau** [comment]
why close it?

**Comment by danicatalan** [comment]
The protip will be usable in the context of connections, we will need to develop multiple selection here. We can just rename this issue and add the information needed for implementation.

**Comment by txau** [comment]
This is no longer vigent.
