### ISSUE TITLE
Allow users to set the document language

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1105]
With our current fallback, we define the document language depending on the UI, but this is not true because what fallback really does is duplicate a document into other languages (for example, a Spanish document will be duplicated into English, but the document language is still Spanish, regardless the metadata).

Also we want to support other scenarios:

- An instance with one document language but different UI languages.
- An instance with different document languages with one UI language.

We should define a local language for every document to better managing.

Some thoughts about it:

- How to set the document language.
- What happens when the document language is not defined in the instance?
  - Add a selector with all languages available in Elasticsearch + "Other language" option.
- What happens when a document has multiple languages?

**Comment by danicatalan** [comment]
To review after implementing #965

**Comment by konzz** [comment]
Done in #1322
