### ISSUE TITLE
Artículos violados filter is broken

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1109]
- [ ] The internal condition should be an AND instead of an OR.
- [x] In the case of "strict mode" it should apply the strict mode condition (relation of violated articles).

**Comment by danicatalan** [comment]
Add examples of expected results here.

@danicatalan

**Comment by danicatalan** [comment]
These are some examples of expected results using the current collection of cases on CEJIL.

## I want to find entities that violated one specific article

- Convención Americana sobre Derechos Humanos.
  - 4.2

```
RESULTS

Hilaire, Constantine, Benjamin y otros
Boyce y otros
Raxcacó Reyes
Dacosta Cadogan
```

These entities violated the 4.2 at some point of the sentence. Easy peasy.

## I want to find entities that violated two specific articles

- Convención Americana sobre Derechos Humanos.
  - 4.2
  - 2

```
RESULTS

Hilaire, Constantine, Benjamin y otros
Raxcacó Reyes
Dacosta Cadogan
```

These entities violated the 4.2 and the 2 at some point the sentence, but not necessary together in the same line.

## I want to find entities that violated two specific articles together

- Convención Americana sobre Derechos Humanos.
  - 4.2
  - 2
- Strict mode activated.

```
RESULTS

Raxcacó Reyes
Dacosta Cadogan
```

These two entities violated the 4.2 and the 2 together, in the same line.

Yeah, _Hilaire y otros_ violated 4.2 and 2 at some point on the sentence, but with **strict mode** we search for cases where 4.2 and 2 are in the same line.

**Comment by danicatalan** [comment]
We think it's better to implement #1119 first. We will review this issue again once that issue is solved.

**Comment by txau** [comment]
Please keep the sprint label or we'll loose visibility on this task.

**Comment by kjantin** [comment]
@txau do you want us to apply the AND/OR toggle feature (as described in #1119) to this custom filter? Or just stick with the original request of changing the internal condition to AND instead of OR?

**Comment by txau** [comment]
This is custom filter that has a very particular logic, we need to keep that logic which is not exactly the same as the one described in #1119
