### ISSUE TITLE
Show property's title when rendering dates on cards

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1111]
When multiple date properties are rendered on cards is not possible to make any difference between those dates:

![image](https://user-images.githubusercontent.com/6364153/28056839-ae3504d2-661e-11e7-8a69-a0354fbae8a5.png)

We decided to always show the titles for dates by default.

**Comment by danicatalan** [comment]
We discussed this idea and already have the implementation where dates are displayed with titles, ready to merge:

![image](https://user-images.githubusercontent.com/6364153/28172483-f51c32b6-67eb-11e7-8f61-eaa67f468a6a.png)

Also they live together with tooltips (but you can't hover dates):

![image](https://user-images.githubusercontent.com/6364153/28172566-2ed90d6c-67ec-11e7-92d8-1257b8e774c5.png)

Anyway we have some questions to do to ourselves about how titles are showing:

- Do we want to keep tooltips? Now that properties as dates are well described, we don't need any tooltip to clarify obvious properties (like Country).
- How we deal with properties that are not dates but still need some clarification? For example, numbers for ages, years, categories... They deserve the same behaviour than dates.
- How we deal with a property is repeated and is not clear how to use it? For example, two properties that use Country (Perpetrator state, Supporting state).
- Should we remove tooltips in the future and allow admins show/hide the title of a property from Settings?

cc/ @txau @kjantin

**Comment by txau** [comment]
I think this solution works @danicatalan, IMO ready to merge.

Regarding your questions:

1. They do not harm. Lets keep them.
2. Lets take care of that problem when we actually see it happening.
3. Maybe an interesting approach would be disambiguating when we're using the same datatype+dictionary.
4. Maybe =)
