### ISSUE TITLE
Document ownership by users

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1113]
SACLS asked for document ownership, so they can set a new role that will edit just its own documents.

**Comment by kjantin** [comment]
They want to restrict the ability for their interns to only edit the documents they upload.

**Comment by txau** [comment]
I think this is related to: https://github.com/huridocs/uwazi/issues/1151

**Comment by txau** [comment]
Duplicate: https://github.com/huridocs/uwazi/issues/1246
