### ISSUE TITLE
Display document language on cards and metadata

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1114]
Once we have automatic detection of language, we will communicate users which language every document has. This is useful to display fallbacks easily to the user, for example, a document in Spanish inside the English interface.

Automatic detection will be implemented on #965.

**Comment by danicatalan** [comment]
- [ ] Show language of the document in card and metadata panel.
- [ ] If language of the document matches language of the UI, don't show it.

**Comment by danicatalan** [comment]
Once I started working on this I noticed the scope should be increased in more scenarios. This is the proposal for all of them:

- [ ] Show tag on cards when the document's language doesn't match with the UI language.

![image](https://user-images.githubusercontent.com/6364153/28310500-f4ca5f62-6bac-11e7-96fb-ced2e1b57e3d.png)

- [ ] When opening sidepanel, the tag is also rendered on the title.

![image](https://user-images.githubusercontent.com/6364153/28310479-e5eaf9e8-6bac-11e7-8786-72b54caa0ca8.png)

- [ ] Keep the language tag on sidepanel when opening documents. Also render it on the header.

![image](https://user-images.githubusercontent.com/6364153/28310067-8a2a7b48-6bab-11e7-9ed3-1c669fa8fc3c.png)

- [ ] If mulitple files are selected, we show this tag for each of one that doesn't match with the UI language.

![image](https://user-images.githubusercontent.com/6364153/28310458-d67f72fe-6bac-11e7-83ed-0b45b96d498d.png)

**Comment by txau** [comment]
@danicatalan in your examples the titles are short. You should try this with a more realistic dataset.

**Comment by danicatalan** [comment]
This is the same with larger titles (CEJIL dataset).

![image](https://user-images.githubusercontent.com/6364153/28377280-92703af2-6cac-11e7-8c8f-fea46a69b352.png)

![preview-languages](https://user-images.githubusercontent.com/6364153/28377792-442ab0d2-6cae-11e7-986c-441ca2607055.png)

![image](https://user-images.githubusercontent.com/6364153/28377351-c0cfcd5e-6cac-11e7-8bea-a7d5fff68d20.png)

**Comment by txau** [comment]
I'm not sure this is the right approach @danicatalan. The idea is to let users know if the document they are about to open is in a language other than their language of preference in the UI.

- Screenshot one: makes sense in the card, not so much in the side panel. If a user is opening from that side panel, the distance between the language tag and the open button is quite big.
- Screenshot two: the user is not going to open the documents, so no need to display the tag.
- Screenshot three: the user is already seeing the document, so no need to display.

**Comment by danicatalan** [comment]
@txau I thought the proposal was to always tag the document, not just before opening the document. This changes the user scenario, so I will rethink the designs with something more specific as you described above.

**Comment by txau** [comment]
To be honest, I'm not sure of what I'm saying, I'm just thinking aloud. But I feel like showing that information where is not adding any value for the users is a waste of real state and user attention.

**Comment by danicatalan** [comment]
I agree, if is not completely necessary let's keep the UI clean instead of adding more noise. I tried with the language tag below the button, but I think it feels weird. What do you think? I personally prefer the tag always on the title (although is not near the open button, I feel that's the place for that tag).

![language](https://user-images.githubusercontent.com/6364153/28427493-ac821f76-6d76-11e7-97ae-d70a41447b62.png)

**Comment by danicatalan** [comment]
I would go for the first idea we had - tag next to titles on cards and sidepanel. It's a good first approach, easy to implement and consistent with our UI.

![img](https://user-images.githubusercontent.com/6364153/28310479-e5eaf9e8-6bac-11e7-8786-72b54caa0ca8.png)

**Comment by RafaPolit** [comment]
@danicatalan Great that styles are on 1114-languages.  Can you please tell me where is 1114-languages?  It may reside only in your memory (or on your computer without being pushed? :)

**Comment by daneryl** [comment]
@RafaPolit remember this require a migration and a reindex on deploy.
