### ISSUE TITLE
Filters support to AND/OR logics

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1119]
## Update 1

We decided to implement a toggle to switch between AND/OR in each multiselect filter. The styles are on [1119-and-or](https://github.com/huridocs/uwazi/commit/13cdece0cf62c9adcdd95ee863df09133e1dc624) branch.

![img](https://user-images.githubusercontent.com/6364153/28423979-c7f73bec-6d6c-11e7-8521-7f15446f252d.png)

- - - - -

**Current behaviour**

All our filters work with OR logic.

**Expected behaviour**

Some properties doesn't make sense with OR logic. A specific example is **Descriptors** on CEJIL. They want to search documents with both properties, but know this is impossible because selecting two properties will show ALL documents with one of those properties.

**Next steps**

We should discuss how to implement AND/OR logics in our filters. Some questions to start this discussion:

- Should the admin set AND/OR by default while creating the property?
- Should the users be able to change between AND/OR depending on their needs?

**Comment by danicatalan** [comment]
- Should the admin set AND/OR by default while creating the property?

We are not going to allow admins to set AND/OR by default.

- Should the users be able to change between AND/OR depending on their needs?

Yes, users should toggle between AND/OR for each property on filters.

**Comment by danicatalan** [comment]
@konzz @daneryl @RafaPolit how do you want to implement this toggle?

I think something like Rightdocs would work right now:

![image](https://user-images.githubusercontent.com/6364153/28421542-c902035c-6d65-11e7-867a-469b44aeaf01.png)

**Comment by txau** [comment]
AND - OR - OFF? We already have a toggle in the filters. Although I don't think the OFF is needed since normally you jut reset all filters and research o unclick/blank the filters.

**Comment by danicatalan** [comment]
We thought about using the same toggle. We should remove the current one because the utility of that is not clear, what do you think?

Also, this toggle should work as a switcher, so no OFF.

![untitled-1](https://user-images.githubusercontent.com/6364153/28422962-e74f01b2-6d69-11e7-9bdf-83a0fd54a31f.png)

**Comment by txau** [comment]
The only problem is that is unclear whether the AN/OR is acting internally within the options in the filter or externally between the different filters. Maybe this is not a issue and users will figure it out quickly?

**Comment by danicatalan** [comment]
As they are all inside their own property, once you click on the switcher the multiselect below should update with the new options (show all if OR, show the matches if AND).

I think that will clear any doubt.

**Comment by txau** [comment]
Ok, makes sense.

**Comment by danicatalan** [comment]
Great! All the styles are ready on [1119-and-or](https://github.com/huridocs/uwazi/commit/13cdece0cf62c9adcdd95ee863df09133e1dc624) branch and we are ready to implement the functionality and test how it works.

**Comment by RafaPolit** [comment]
Am I the only one that find them really hard to see and/or read?

**Comment by txau** [comment]
@RafaPolit you are totally right. cc: @danicatalan

**Comment by kjantin** [comment]
I really like how @danicatalan explains the difference between AND/OR for users: 

> show all if OR, show the matches if AND

 
- any chance we could stick this in one of those "i" buttons next to it? If you think that's too much, let's be sure to explain this in the user guide.

**Comment by kjantin** [comment]
How do we handle single _select_ fields, in which select the AND operator doesn't make any sense?

**Comment by kjantin** [comment]
How will this switch look in other languages?

**Comment by danicatalan** [comment]
@RafaPolit @txau this is how it looks right now:

![image](https://user-images.githubusercontent.com/6364153/28865036-c0dfe118-776e-11e7-90d2-a6a2fbe657ec.png)

Do we want to give it more relevance? It's a secondary option and making it bigger or more colourful will add more importance to those buttons.

@kjantin We can translate them in other languages. For example, in Spanish that would be `Y - O`. In engineering we never translate boolean operators, but in the interface we can do it without problems.

About the select fields, users doesn't care about if the field is select or multiselect, so making different behaviours between those fields will be confusing. When AND is active, once the user clicks in one property the others should disappear.

**Comment by txau** [comment]
@danicatalan I think it needs a little bit more visibility. Give some size and color please.

"EDIT: @kjantin after seeing a demo with @konzz, we decided to keep the switcher hide on selects. Also we won't remove the properties with 0 results, we will keep them to give better feedback to the users."

Not removing the 0 results sounds wrong to me. Maybe I'm not understanding the reason why you don't want to remove them?

**Comment by danicatalan** [comment]
@txau I agree, but some combinations of filters hide all the filters because there's 0 results, so users couldn't see which properties are selected because they had 0 results.

@konzz can you give an example on how to replicate this?

**Comment by txau** [comment]
"but some combinations of filters hide all the filters because there's 0 results, so users couldn't see which properties are selected because they had 0 results."

@danicatalan then all we need is blank state for the filters. Showing a list of zero results is a bad solution, is deceiving for the users. I insist, do not change this implementation.

**Comment by konzz** [comment]
@danicatalan @txau The solution is not keep all the options with 0 results, the idea is:
The user selects Option A and option B from a list of 10, then switches to AND operator, we remove all options except A and B showing 0 results, so the user knows that combination has no results and can uncheck one of them, without needing to click the reset button.
