### ISSUE TITLE
Add search autocompleter

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1125]
**Expected behaviour**

- Search **19 com**.
- It suggest a list of keywords autocompleting **19 com**, for example, **19 comerciantes**.
- Click on the suggested keyword performs a search inside the library with that keyword.

![ezowlgscf5](https://user-images.githubusercontent.com/6364153/28114295-81d4d5ce-6700-11e7-88da-9f9bf5bfcb42.gif)

With the new full text search, we will remove the old search suggester because is adding noise and no value to our current searchs. We keep the styling to reuse it with the new functionality.

**Comment by kjantin** [comment]
@danicatalan can we allow the user to use their arrow keys to navigate through suggestions, as requested in #89 ?

**Comment by danicatalan** [comment]
@kjantin we should do that.

**Comment by txau** [comment]
"The match_phrase_prefix query is a poor-man’s autocomplete. It is very easy to use, which lets you get started quickly with search-as-you-type but its results, which usually are good enough, can sometimes be confusing."

https://www.elastic.co/guide/en/elasticsearch/reference/master/query-dsl-match-query-phrase-prefix.html
