### ISSUE TITLE
Showing "Rich text" properties on cards breaks the filters

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1126]
![image](https://user-images.githubusercontent.com/6364153/28121354-10ec6c26-671b-11e7-8954-a74379618bcd.png)

**How to reproduce**

- Install uwazi-fixtures.
- Open Settings, edit Entity type: Causa.
- Select Resumen, activate Show in cards.
- Go to the Library.
- Filter by Causas.

**Comment by danicatalan** [comment]
This bug is affecting critically on [HR Reports](https://hr-reports.uwazi.io). They have cards with rich text, so any attempt to enter the homepage breaks the browser.

cc/ @kjantin

**Comment by RafaPolit** [comment]
This is a minor issue on the card rendering, it has been corrected in the #1114 issue, as there has been work done on the card rendering.
