### ISSUE TITLE
Issues in installation instructions

### ISSUE THREAD

**Issue by habbes** [huridocs/uwazi#1127]
Some steps on the instructions in the main `README.md` file are missing or incomplete

- Maybe it would help to also mention the minium version of MongoDB
- There's not explicit step to `git clone` a copy of the repo when installing
- Running `./database/blank_state.sh` actually causes an error because a node module is not found. The solution was to
``` 
$ cd database
$ ./blank_state.sh
```

because the working directory is based on where the command is executed from and not where it's located

- `foreman start` starts the app on port 5000 instead of 3000 and this leads to error, the solution is to run `foreman start -p 3000` instead
- `node test_api.js` causes a `module not found error`, the actual module is `api_test.js` so maybe you meant `node api_test.js`

**Comment by txau** [comment]
@habbes I guess these are all old issues. Most of them already fixed. closing.
