### ISSUE TITLE
Highlight sorting property

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1131]
We need to help users quickly locate in the cards the sorting criteria property. 

![screen shot 2017-07-13 at 09 10 59](https://user-images.githubusercontent.com/489831/28173516-e0fda958-67ab-11e7-8619-463805ea6389.png)

**Comment by RafaPolit** [comment]
I still think that a nice icon next to the value reflecting a sort or filter would help quickly identify the property.

Also, if we go back to showing the label on all the fields, it could go on the label instead of the value.

**Comment by txau** [comment]
Duplicated: https://github.com/huridocs/uwazi/issues/1289
