### ISSUE TITLE
Wrong A-Z sorting in connections 

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1134]
The last element should be the first.

![screen shot 2017-07-13 at 18 18 17](https://user-images.githubusercontent.com/489831/28193248-85dea372-67f8-11e7-9b7b-1d496dac52b6.png)

**Comment by danicatalan** [comment]
This is also happening on the library. Bamaca and Millacura shouldn't be there:

![image](https://user-images.githubusercontent.com/6364153/28205695-63a3809e-6883-11e7-9697-82f7ecd0626b.png)

**Comment by RafaPolit** [comment]
These are two separate issues:
The one reported by @txau is an elasticsearch configuration issue, which we are currently fixing.
The one reported by @danicatalan is trailing whitespaces.  Bamaca and Millacura both have trailing whitespaces in the name.

How should we address this is probably open to discussion.  We could sanitize input fileds to remove trailing whitespaces, at least on certain field types (for instance RichText probably is not the place to do that?)

What do you guys think? @txau @daneryl @konzz

**Comment by RafaPolit** [comment]
I have applied a fix (on the branch) via a filter applied to the RAW property of String type fields of the type ['lowercase', 'asciifolding', 'trim'].  It solves both issues.

The problem I can see is that this applies that filter to all string properties, including "sharedId".

This has the following side-effects:
- sharedIds are transformed to lower case on the elastic search index.  As far as I know, this is not an issue, as our generated IDs are already lower case, but it gave errors on tests where manually-assigned IDs had camel-case construction.  Perhaps this is not an issue to worry ourselves with.
- aggregation's Keys are also returned with the same filter (as it uses the RAW property to create the key value).  There are tests also that tested against Camel Case values, but in the actual application use, I can see no side effect of this neither.

@konzz @daneryl Can you confirm these side effects have no real impact on the application? If so, I have adapted the tests to show this effect.  If this is an issue, we need to discuss further approaches, perhaps even indexing a new field for sorting, but that would involve a lot of work.

**Comment by RafaPolit** [comment]
To preserve the RAW field as actually RAW, we have created a new Sort field in the index for the types that require it.  This prevents future conflicts if we decide to use RAW for other properties.
