### ISSUE TITLE
Publish action button being displayed in non-public items

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1137]
![screen shot 2017-07-13 at 18 37 10](https://user-images.githubusercontent.com/489831/28193562-fb7175f4-67fa-11e7-98c8-c9bc0a710a1d.png)

- Is this the desired behaviour?
- Do we need to tweak the design of the cards for non pubic docs and entities?

**Comment by kjantin** [comment]
We need to test this further to see if that publish button actually works.

**Comment by danicatalan** [comment]
@kjantin there's a issue to review all publish buttons: https://github.com/huridocs/uwazi/issues/756

**Comment by danicatalan** [comment]
Already fixed.
