### ISSUE TITLE
Deleting document templates that have documents assigned should not be allowed?

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1140]
Further research proved that allowing deletion of templates, has blocked deletion of groups in my settings > filters, probably because the templates that were assigned to the groups don't exist anymore.

**Comment by RafaPolit** [comment]
I can confirm that the system is indeed allowing to delete templates that have documents assigned to them.

**Comment by RafaPolit** [comment]
This is the same issue as #1195 .  Passing development over to @konzz .

Please be sure to address the group deletion issue in Settings > Filters as well.
