### ISSUE TITLE
Multiple selection + assign document type fails

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1141]
1. Go to uploads.
2. Upload a few files.
3. Select them and hit edit.
4. Assign a doc type and save.
5. Shows success but the type is not assigned.

**Comment by daneryl** [comment]
@txau this is working as expected for me, can you provide a more detailed example, which document type are you assigning and in which instance ?

**Comment by daneryl** [comment]
@txau, @RafaPolit @danicatalan @konz i have replicated this now, it only happens when there you save it with the default type selected. 
what should we do here ? i see 2 options.

1 .- fix this behaviour and use the first type as default selected.
2.- use as default selected a blank value, forcing the user to select one.

**Comment by kjantin** [comment]
I vote for #2, don't have a default document type.
But, if we do want to have a default document type, can we allow the admin to select which type they want to be the default?

**Comment by txau** [comment]
@daneryl we already had similar bugs in the past with the default document type in uploads. Make sure this is tested please.

@kjantin that involves developing a small feature. Option 1 is just fixing a bug, I think we should go for that one.

**Comment by RafaPolit** [comment]
I agree with @txau on both accounts:
- Lets just go for the first item as default for now.
- We already had issues that the first selection was shown but not actually attached to the model.  This could be happening in other places as well. We should probably 'sweep' the app finding where this could be an issue and e2e test everything.

**Comment by daneryl** [comment]
@RafaPolit fixed this specific case with some tests #1182
