### ISSUE TITLE
Wrongly displaying upload failed status when uploading multiple files

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1145]
I tried to upload 12 files at once. 6 where loaded in parallel while the other 6 displayed an "Upload failed" status. When the first files finished uploading those displaying the error resumed upload.

![screen shot 2017-07-15 at 14 32 22](https://user-images.githubusercontent.com/489831/28242511-5b5c03e6-696b-11e7-9966-a4db74828172.png)

**Comment by kjantin** [comment]
Change "upload failed" default to "uploading" or "processing"
