### ISSUE TITLE
Improve search results styling on sidepanel

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1149]
- [x] Add the amount of results besides the magnifying glass icon, as we do with connections.
- [x] Improve page styling (both default and hover).
- [x] Make better use of blank space (with longer snippets or smaller height).
- [x] Match highlight from left panel to the documents one.

![image](https://user-images.githubusercontent.com/6364153/28263560-7420a01c-6ae7-11e7-8826-a7c154eee9b9.png)

![image](https://user-images.githubusercontent.com/6364153/28263737-30fa2d3e-6ae8-11e7-95b2-3cfbd6cd701e.png)

**Comment by danicatalan** [comment]
This is the concept for improve all styles related with full text search:

![image](https://user-images.githubusercontent.com/6364153/28331311-d6d4ba72-6bf0-11e7-9838-f45be489416c.png)

I fixed all the heights to the same amount to better render the results and use all the space available - so more results in the same space.

Also the behaviour for highlights has changed to one more desirable: we just highlight the keywords on the text, improving readability, and in case a user clicks on one of the results on the right, this will result and the related text on the left will highlight on blue as active search result.

Appart from a strange padding on the right of the results I need to fix, what do you think about these new styles? @txau @RafaPolit

**Comment by RafaPolit** [comment]
I still think that
page 7 -
page 12 -
etc
Uses an huge amount of space, and repeats unnecessarily the word Page.  Perhaps a page icon with the numbers inside would suffice? (it could be a challenge for pages with three digits).

Something like this:
![screenshot from 2017-07-18 12-56-06](https://user-images.githubusercontent.com/4309019/28331957-a06742f8-6bb8-11e7-80a7-6e863f22ac5a.png)

**Comment by danicatalan** [comment]
I really like both options: pg instead of page, or remove all wording and change it with an actual page icon. Obviously the second one is harder to implement but playing with opacity doesn't look saturated of icons.

![pg](https://user-images.githubusercontent.com/6364153/28359310-0359a5fe-6c72-11e7-8172-8f2162a60a45.png)

![pages](https://user-images.githubusercontent.com/6364153/28359309-03589722-6c72-11e7-9ccf-92f0b67ba59b.png)

**Comment by txau** [comment]
I like the option of only the number, no icon or anything. I also think that the snippets should be longer and in 2 lines.

**Comment by RafaPolit** [comment]
I tried for myself that approach of only numbers, but its not clear what that number is.  Perhaps a small 'column header' indicating what it is if we are to for-go every identifier?

**Comment by danicatalan** [comment]
We can make it into two lines, but should increase before the snippet size. Currently the snippets are rarely longer than one line (check screenshots above).

I think just the number is confusing. You save a lot of space but is unclear what that number means. My favourite approach in this case is **pg. #**, clean and short.

**Comment by txau** [comment]
Its pretty clear what the number is after clicking on it one or two times. Smarter people may even understand it without needing to click. So don't be cojudos and leave the number alone.

**Comment by txau** [comment]
@danicatalan I agree, we should increase the snippet size.

**Comment by danicatalan** [comment]
@txau I agree, let's take that solution (just number) and we will see if it's a problem with real users feedback.

**Comment by danicatalan** [comment]
Styles are merged into development. Closing this issue to implement the other changes here:

- Refine full text search highlights #1115
- Show search results number on tab #1157
- Increase the snippet size #1159

**Comment by txau** [comment]
@danicatalan do we have another task for displaying the amount of search results in cards?

**Comment by danicatalan** [comment]
It was in the initial scope #861 but was discarded because @daneryl found great performance issues with that feature.

![img](https://cloud.githubusercontent.com/assets/6364153/25745467/4a11cb88-319f-11e7-9abc-a1dade943e23.png)

I'm going to create a Discussion issue to talk about that before any further action.
