### ISSUE TITLE
Implement a 'per user' or 'favorites' folder to make collaborative document organising easier

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#1151]
_As a user, I would like to be able to separate the documents I am working on (organising, creating connections, etc) from the rest of the document library. This is especially helpful when I am working with a team of people._

**Comment by danicatalan** [comment]
Would like to ear more about the problems they want to solve.

- How many people will work together in the same documents?
- How they decide and assign who works in each document?

I think here we are trying to solve two different problems:

- Keep track of interesting documents for me (as a user), so I can access later to them.
- Keep track of which documents I'm working and sharing responsibilities with my team, so I can find and manage them easier with others.

**Comment by txau** [comment]
Duplicate: https://github.com/huridocs/uwazi/issues/1246

**Comment by txau** [comment]
This is being addressed as part of the permissions model. Closing for now.
