### ISSUE TITLE
Maintenance page

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1155]

**Comment by danicatalan** [comment]
![image](https://user-images.githubusercontent.com/6364153/28419548-963d3e1a-6d5f-11e7-8d29-cc71ff4b381d.png)

This is the design for our maintenance page. As talked with Albert, it must be a plain HTML so I injected a couple of simple styles and the svg inside the HTML.

I will wait until tomorrow to sent it to Albert, so you can check it and propose some feedback about the message.

**Comment by txau** [comment]
I think is great.

**Comment by kjantin** [comment]
looks great. the only thing I could imagine adding that might make it more informative is something like this:

> In the meantime, read about the latest Uwazi updates in our release notes (https://github.com/huridocs/uwazi/releases)

....so they can see all the things we're updating when we take down these sites for maintenance.

**Comment by danicatalan** [comment]
Ready!

![image](https://user-images.githubusercontent.com/6364153/28424913-26ca4c20-6d6f-11e7-9d3d-bdec27290d93.png)

**Comment by txau** [comment]
We could use the color logo too?

**Comment by danicatalan** [comment]
Absolutely we could, but making the logo on grey feels more like a maintenance page.

**Comment by txau** [comment]
PS2: Lets go for a real click bait "We were releasing new features and you won't believe what happened next...".
