### ISSUE TITLE
Show the amount of search results inside cards

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1161]
In the initial scope #861 the amount of search results were displayed below the most relevant snippet:

![img](https://cloud.githubusercontent.com/assets/6364153/25745467/4a11cb88-319f-11e7-9abc-a1dade943e23.png)

We had some talks about performance issues, so maybe we should talk again about this to find a solution.

cc/ @txau @daneryl @RafaPolit @konzz

**Comment by konzz** [comment]
Ask for more than one snippet and show "Show all results" in case there is more than one result
