### ISSUE TITLE
Include charts in the connections of entities

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#1164]
Current chart implementation would make it more or less straightforward to add charts to the connections pane in entities.

We could add one chart for every type of connection and show the amount of each type of document for that type of connection.

This could prove very useful for things like the "person" implementation that Japiqay is using: large collection of people that can be related in different ways to documents and cases.  For instance, a person can be listed as perpetrator in several cases, documents, etc., but also as victim in others.

Maybe its worth looking into it?

**Comment by txau** [comment]
I'd say not for now until we have a clearer vision on how both connections and charts are going to work.
