### ISSUE TITLE
Elasticsearch uses the first occurrence of a property to determine its type, numbers are having issues

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#1174]
Elasticsearch uses the first occurrence of a property's value to determine its type.

When creating numeric values, if your first document value for that property is an integer, it maps the type to "long", if it is a decimal number, it maps the type to "double".

The problem is that once a type is set, it uses that for all the future values.  So after being registered as type "long", adding values with decimal numbers treats them as "long" for purposes of filtering and ordering.

Also, re-indexing the elastic index has the same effect: it takes the first occurrence.  So, best case scenario: it keeps all doubles and longs consistent (meaning it is still broken but at least it acts the same), and worst case scenario: it changes some doubles back to longs in which case things are even more broken than before.

We need to decide if we are going to 'manually assign' type Double to all numeric input fields, if we create a custom mapping for those fields (this will involve some name spacing or something similar) or if we should take a different route, investigating what downside it could have to index all numeric values as Doubles.

**Comment by txau** [comment]
"Investigating what downside it could have to index all numeric values as Doubles" probably ony performance, if that is the case, I guess we could go for this solution on the short term.
