### ISSUE TITLE
When creating dictionary with values, values are created without labels

### ISSUE THREAD

**Issue by habbes** [huridocs/uwazi#1177]
On the New Dictionary form, if you create a new dictionary, add items to it then hit Save, the dictionary will be created but the items will have no labels. When you go back to edit the dictionary, you'll see the items listed with empty labels, but you will be able to set their names on edit form and save.

The dev tools network tab reveals that the API request is made with empty strings for labels instead of the strings the user entered on the form:

```json
{
  "name": "Test Dict",
  "values": [
    {
      "label": ""
    },
    {
      "label": ""
    },
    {
      "label": ""
    }
  ]
}
```

**Comment by txau** [comment]
@habbes is this still happening? How to replicate? Thesauri are working well for me.

**Comment by txau** [comment]
Apparently this has been fixed already.
