### ISSUE TITLE
Entities not appearing in filtered results

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1183]
This entity from CEJIL is not appearing in the results when filtering by "Medida provisional" and "Mexico":

https://cejil.uwazi.io/es/entity/vlgcm2oi9owbc7gp8613e4s4i

**Comment by RafaPolit** [comment]
When Elasticsearch reached its fields limit, it stopped indexing new documents.  With the reduction of the fields and a reindex, this is now resolved.

Closing the issue.
