### ISSUE TITLE
Configure Uwazi backups

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#1184]
How do we backup the files, database, etc of each Uwazi instance?

**Comment by txau** [comment]
Instances deployed in our server have periodic backup configured.

If we are talking about developing a backup feature, is don't think is going to happen anytime soon.

**Comment by kjantin** [comment]
More info from Albert: We have daily uwazi backup on our s3-like storage. Backup creation script already added to ansible rule, so every time you create an instance you create backup configuration for this instance too. There is backup for files and mongodb data
