### ISSUE TITLE
Is there a limit to the size of the uploaded PDF? Is it modifable? 

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#1188]
Japiqay is running into some issues uploading PDFs that are 100 MB. Is there a limit to the size of the PDFs that are able to uploaded in Uwazi? If so, what's the size? And can it be increased? Thanks!

**Comment by txau** [comment]
Seems to mee that 100MB PDF files are too big. It can be increased but their users are going to have problems loading them.

Do these PDFs have many images or maybe they need to be downsampled?

**Comment by txau** [comment]
There is no size limit.
