### ISSUE TITLE
Selecting a filter on a specific template in Uploads shows the 'No type' after the results

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#1193]
When filtering one type of document type in uploads, all the 'No type' documents get listed after the last occurrence of the selected type (tested in Japiqay)

## Steps to reproduce

- Go inside uploads, be sure to have at least one document without type (if needed, upload a PDF) and one with assigned type.
- Filter for that type of template
- You will see the documents assigned to that property first, and then all the 'No type' are listed.

**Comment by txau** [comment]
Working properly now. Closing.
