### ISSUE TITLE
Add API FAQs to documentation

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#1194]
We need to document the questions and answers that are being shared regarding the API.

**Comment by kjantin** [comment]
Documented here https://github.com/huridocs/uwazi/wiki/API-FAQs. Needs review

**Comment by kjantin** [comment]
Does every Uwazi instance have API information automatically created at https://yourinstancename.uwazi.io/api?

**Comment by txau** [comment]
@kjantin yes =)
