### ISSUE TITLE
Redesign admin page

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#12]
- Password change workflow
- Edit "Collection name"

**Comment by danicatalan** [comment]
![12_admin_page](https://cloud.githubusercontent.com/assets/6364153/15986148/d281dc70-3000-11e6-90df-0c6021730299.png)

@txau one doubt, usually all the system has and `old_password` + `new_password` input. Shall we make this or maybe it's a new functionality?

**Comment by danicatalan** [comment]
- [ ] Add sidebar.
- [ ] Remove title.
- [ ] Data binding between header name and input name.
- [ ] Repeat password (two-steps input).
- [ ] Remove redundancy inside buttons.
- [ ] View email and possibility to change it.

**Comment by danicatalan** [comment]
Updated: https://github.com/huridocs/uwazi-assets/tree/master/12_admin_page

**Comment by txau** [comment]
Awesome. Moving it to dev.

**Comment by konzz** [comment]
Solved with #162
