### ISSUE TITLE
Have a small footer telling the user when the content is finished

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#120]

**Comment by danicatalan** [comment]
I share with you some screenshots with mobile + desk version of the footer. It's positioned inside the content column as a feedback of when the content is finished.

I faked the links with some that seems logical to me, but we need to discuss the final ones.

![footer_mob1](https://cloud.githubusercontent.com/assets/6364153/16299603/72298ca8-393b-11e6-82cf-1a6531ed5503.png)

![footer_mob2](https://cloud.githubusercontent.com/assets/6364153/16299604/72417ca0-393b-11e6-9ca3-aa38b930f063.png)

![footer1](https://cloud.githubusercontent.com/assets/6364153/16299605/724ea876-393b-11e6-811c-ad40c86a68f2.png)

![footer2](https://cloud.githubusercontent.com/assets/6364153/16299606/724faa0a-393b-11e6-85bd-8e43a2ca7a4a.png)

**Comment by danicatalan** [comment]
- [ ] Remove (c)
- [ ] Clone links from **header** to **footer**.

**Comment by danicatalan** [comment]
@daneryl @konzz you can get the HTML from https://github.com/huridocs/uwazi/blob/120_footer/app/react/Library/components/DocumentsList.js

Use that branch if it's easier for you to create de component and propagate it trough the app.

**Comment by konzz** [comment]
@danicatalan I need the new css changes for the footer

**Comment by danicatalan** [comment]
@konzz you can find them here: https://github.com/huridocs/uwazi/blob/120_footer/app/react/App/scss/layout/_footer.scss

**Comment by konzz** [comment]
Solved with #189
