### ISSUE TITLE
Add numeric fields to the available SORT BY options.

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#1211]
We should probably include the numeric-type fields into the SORT BY options when they are checked as used as filter.

To me it makes a lot of sense to be able to order by numeric fields.  What do you guys think?

**Comment by txau** [comment]
We should, lets leave it in low priority for now.

**Comment by txau** [comment]
Dupp https://github.com/huridocs/uwazi/issues/1378. Closing.
