### ISSUE TITLE
We are indexing ATTACHMENTS in ElasticSearch, but we don't use them.

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#1213]
We are indexing the ATTACHMENTS array into ElasticSearch.

This is using memory, index fields (which we already run into issues for reaching the max limit).  It is using 27 fields.

I think we are not doing anything within Elastic with attachments.  Perhaps we are checking inside its file names as part of extended fullText searches?

Anyway, we should check if we want this behavior, or if we start limiting the elastic index.

**Comment by txau** [comment]
Do you think this has an impact in performance?

**Comment by RafaPolit** [comment]
Hard to say, really.  But given our particular hosting scenario, it might.

Since we have already hit the default limit by neglecting the mapping, it wouldn't hurt to have a good policy regarding what is indexed and what not.

But yeah, not a priority right now that every instance is small and with few contents.  That is why I added the priority tag.  This is not urgent at all.
