### ISSUE TITLE
Search and filter totals should be in sync

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1220]
- Filters say 267.
- Search tosses only 1 result.

It's misleading for users.

![screen shot 2017-08-10 at 11 06 27](https://user-images.githubusercontent.com/489831/29163234-2237c662-7dbc-11e7-9d2f-dce50b060d6f.png)

**Comment by kjantin** [comment]
Summary of sprint discussion: we will match the numbers and see how that works for users.
