### ISSUE TITLE
Weird redirect with plain text password

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1222]
![screen shot 2017-08-10 at 17 08 01](https://user-images.githubusercontent.com/489831/29177368-d59f4d2e-7dee-11e7-8754-cd5684fd9f70.png)
![screen shot 2017-08-10 at 15 26 39](https://user-images.githubusercontent.com/489831/29177370-d5d4b3d8-7dee-11e7-8092-9dd104cfc1ba.png)

**Comment by txau** [comment]
This has already been fixed.

**Comment by txau** [comment]
Apparently this was never fixed. It took me a while to figure out how to replicate. The login form has no default method configured (GET, POST), so by default it will behave as GET, sending the params in the URL.

Apparently the form gets instrumentalized when the app bundle loads and the method is changed to POST at some point. But in slow connections, users may be able to see and use the form before its method is converted to POST, thus exposing the credentials in the URL.

**Comment by daneryl** [comment]
@txau setting the method to post will fix the issue but then the submit will try to post to /login and gives an error, this ok ? or should i work on only submitting when the form is ready ?

**Comment by daneryl** [comment]
@txau should be fixed by #2811, the solution was to only render the form on the browser side, this means the form is always ready when it is rendered.
