### ISSUE TITLE
Optimize Elasticsearch searches, aggregations, snippets and reindexing changes

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#1229]
Current Elasticsearch mapping has full text appended as a child of the document which, as per the documentation, introduces several speed problems.

We are doing this because every change in template structure or even naming requires reindexing potentially all documents in a collection.

We need a better architecture for this issue.

**Comment by txau** [comment]
I think Elastic supports changes in the mapping without having to reindex everything. Right now, are we reindexing everything every time we make a change in the mapping?

**Comment by RafaPolit** [comment]
Yes we are. But not only when there are changes to the mapping.  We are reindexing a lot of documents when we change templates: names, remove properties, etc.

**Comment by konzz** [comment]
Closed in favor of #1297
