### ISSUE TITLE
Homepage hero for CEJIL

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1230]
- [x] Create homepage hero layout.
- [x]  Sync data amount (causas + medidas provisionales, documentos) with library.
- [x] Support translation.
- [x]  Don't use search box, add direct access to Causas and Documentos.
- [ ]  Look for background image.
- [ ]  Remove description title.
- [ ]  Reduce description size.

![home-header](https://user-images.githubusercontent.com/6364153/29305867-2433571e-819b-11e7-8d6f-fd287a82cfa8.png)

**Comment by RafaPolit** [comment]
@danicatalan I have created a {customhook} tag which will allow inserting into pages any type of component we design, to avoid having to program 'exceptions' to when things are displayed.

That should work perfectly for this.  So please design this as a completely separate component, and then we can easily include it in the pages with the custom hook escape code.

**Comment by RafaPolit** [comment]
This is done and has been incorporated into #1239.

The way to use the hero is:

```
{customhook}(component:cejilHero,title:'Busca en XX causas y YY documentos',subtitle:'Analizador de Jurisprudencia del Sistema Interamericano de DD.HH.',buttons:!('Causas','Documentos'))
```

The component will replace XX with the sum of Processes and Provisional Measures, and YY with the sum of all document types (currently exiting in the DB) in the main Title.  Subtitle and Buttons Labels are also configurable.

This will allow changing phrases and wordings without the need of a devs intervention.  Alas, it makes the implementation of the component a bit 'heavy'.

Here is the result:
![screenshot from 2017-08-17 14-35-45](https://user-images.githubusercontent.com/4309019/29430460-104217c0-835a-11e7-8884-d8099527e3d4.png)

ps. @danicatalan I think I liked the white text over darker background better?

**Comment by danicatalan** [comment]
@RafaPolit It depends on the background image. With the current cejil.org background it's better to keep it light. But with more complex background it's better to get the darker one.

![homepage-old](https://user-images.githubusercontent.com/6364153/29450548-69ad32d6-83ff-11e7-93c0-198bd2bf5574.png)

![homepage](https://user-images.githubusercontent.com/6364153/29450549-69b01cb2-83ff-11e7-9e26-d8f78a442cd3.png)

**Comment by RafaPolit** [comment]
Since the South America image was not royalty free, here is an alternative version:
![cejil-hero](https://user-images.githubusercontent.com/4309019/29474618-0ea212b2-8422-11e7-9057-96991c26ab37.png)

**Comment by danicatalan** [comment]
Thanks @RafaPolit 🔝  🔝  🔝
