### ISSUE TITLE
Add custom graphs on CEJIL homepage

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1231]
In the (near) future we will allow users to add custom code with their graphs, but right now we just want to add two very specific graphs to CEJIL homepage without any configuration.

![home](https://user-images.githubusercontent.com/6364153/29306368-95475836-819d-11e7-99d2-8704c7d42b60.png)

**Processes and provisional measures by country**

The first chart is the one we must develop for the CEJIL launch. This chart will render all the countries on X, and the amount of processes and provisional measures on Y. The only difference between this graph and the one we render in `1057-recharts` is that, instead of stacking processes and provisional measures, each entity should be rendered in their own bar:

![multibar](http://www.emathzone.com/wp-content/uploads/2014/08/multiple-bar-chart.gif)

- X axis: Country.
- Y axis: Amount of Processes / PM.
- Bar 1: Process amount per country.
- Bar 2: Provisional measures amount per country.

**Processes status by country**

The second chart is a nice to have but not a priority. The render will be the same (countries X, amount Y), and also multiple bar chart, but the data will be displayed differently.

In this case, we stack processes and provisional measures as usual - but we split the bar in two: one with all processes and provisional measures with the property *Status: Active* and another with *Status: Closed*.

- X axis: Country.
- Y axis: Amount of Processes / PM.
- Bar 1: Process and PM with *Status: Active* per country.
- Bar 2: Process and PM with *Status: Closed* per country.

**Comment by RafaPolit** [comment]
@danicatalan You use the word 'stack', yet you have referenced a side-by-side bar graph.  Which one should we do? Stacked or side by side?  Perhaps stacked is more useful for this data?

**Comment by danicatalan** [comment]
@RafaPolit I mean stack data into the same bar for two different document types (in this case, stacking the amount of processes and provisional measures). I hope these sketches clarify both graphs:

![image](https://user-images.githubusercontent.com/6364153/29351822-af5cfd08-8264-11e7-958e-64f36925b742.png)

![image](https://user-images.githubusercontent.com/6364153/29351832-b7d3bc74-8264-11e7-88ac-a659a4e5ef17.png)

For this specific case and after what we talked with them, I think there's no value in stacking bars and just add complexity to the development and the visualization (if you are referring to something like this):

![image](https://user-images.githubusercontent.com/6364153/29352058-9bbf58da-8265-11e7-80c1-7070c8926979.png)

**Comment by RafaPolit** [comment]
This is ready in a PR.

The way to insert this into a page (any page!) is to use the new **customhook** markdown escape.

```
{customhook}(component:cejilChart001,label:'Causas y medidas provisionales por país')
```

In the label property, you can configure whatever you want to appear as the title of the graph.  Here you would customize in each language of the page the different text you need as title.

All other components titles and translations are derived from the actual database data.

Here's a preview of what it could look like once inserted into pages:
![screenshot from 2017-08-16 16-04-37](https://user-images.githubusercontent.com/4309019/29385366-07ff3e98-829d-11e7-9dbd-3b66d65b0fb1.png)

**Comment by txau** [comment]
This is awesome. So via custom code we can embed any component in any page/rich text field?

**Comment by RafaPolit** [comment]
For now its only on pages, but it wouldn't take much to port that into every rich text field.  The problem is that since you can configure rich text fields to render in cards, it could be tricky to have something render good in a full page and in a card.

But yes, that's the idea.
