### ISSUE TITLE
Tell the user that they must select the type of connection

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#1235]
When creating a connection or a reference, let's make to more clear to the user that they need to select a "type of connection" in order to create the connection. Currently, you are able to select the target document without selecting a type of connection, but you can't save it and there is nothing instructing the user that the reason this isn't saving is because they haven't select a type of connection. 

![image](https://user-images.githubusercontent.com/354426/29337016-da5fb52c-81dd-11e7-8c47-a094c3505ae4.png)

**Comment by txau** [comment]
This works different now, not a issue anymore =)
