### ISSUE TITLE
Search box behaviour when refining a search

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1236]
This is a question related with how search box decides which documents displays in the library.

I made a query searching with one keyword:

![azrael](https://user-images.githubusercontent.com/6364153/29353348-293a8460-826a-11e7-9fa5-a9952ddea9e9.png)

Now I want to refine more my search adding more keywords to the query. What should be the expected results? Amplifying the scope or reducing the scope?

![azrael kc or](https://user-images.githubusercontent.com/6364153/29353128-6d9cdb4a-8269-11e7-8060-3cffac60b488.png)

![azrael kc and](https://user-images.githubusercontent.com/6364153/29353127-6d7cf9ba-8269-11e7-82b4-bd63733d4836.png)

The first result show all documents that have at least one of the keywords: "azrael", "killer" and "croc".
The second result show all documents that have at least each keyword once.

In my opinion, the second result is more optimised because those documents are useful for my research (both have the keywords inside the document, maybe not specifically in the same paragraph but reading them I can create matching points between all the keywords).

But the first result could be great for a user that is in exploratory mode, so he doesn't miss any piece of information (and **with relevance sorting the three results from the second option will be displayed in the first row**).

Anyway, I think we should add a easy way to refine a search if he user want to focus their search, but I don't know if that should be the behaviour by default or if we should ask the user if he wants to focus the search.

I'm thinking about something easy, like using some character like double quotes if the user wants to specify he wants just documents with all the keywords:

`azrael + killer croc (without quotes will show 22 results)`

`"azrael + killer croc" (with quotes will show 3 results)`

Opinions about this topic?

**Comment by txau** [comment]
This was addressed in the query string implementation: https://github.com/huridocs/uwazi/issues/1682
