### ISSUE TITLE
English Document with a connection to a French document affecting document card

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#1242]
Hey guys,
on the AfCHPR commentary https://afchpr-commentary.uwazi.io/en/document/8e03bf3c07eyu8fr - the document titled 'Transfers to the Commission' has a connection to a French document. It seems this makes the system automatically mark the document card as in Fr - see screenshot.
Any advice on how to avoid this?
<img width="960" alt="chruwazi-aug2017" src="https://user-images.githubusercontent.com/22650647/29453426-4d349ba4-8412-11e7-98d7-11c80e50cb4e.png">

**Comment by kjantin** [comment]
This is happening because there is _some_ French text in that PDF: "Association Juristes d’Afrique pour la Bonne Gouvernance v Côte d’Ivoire,"

**Comment by kjantin** [comment]
Can we allow the user to change the language code on a doc, if it is wrong?

**Comment by danicatalan** [comment]
Yes, we can allow users edit the language the same way they edit any metadata field.

**Comment by konzz** [comment]
Closed in favor of: #1316
