### ISSUE TITLE
Display truncated text

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1243]
We need either a tooltip or some other UI solution for the users to be able to easily access the truncated text:

![screen shot 2017-08-18 at 12 14 48](https://user-images.githubusercontent.com/489831/29454850-038c4df6-840f-11e7-9e85-19214f667ee4.png)

**Comment by danicatalan** [comment]
Trucanted text removed.

![image](https://user-images.githubusercontent.com/6364153/29577065-64082d04-876a-11e7-9e60-77370fe316b5.png)
