### ISSUE TITLE
Can I digitise and upload physical documents using mobile phone + Uwazi?

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#1245]
As a user, I want to be able to easily digitise and upload physical documents to Uwazi. Is it possible to take a picture of a document on a phone and then add that picture/PDF to Uwazi?

**Comment by kjantin** [comment]
Turns out there are a number of apps that scan documents and allows you to extract information. CamScanner has an API: https://dev.camcard.com/?language=en-us

**Comment by txau** [comment]
A nice alternative is AdobeScan: https://acrobat.adobe.com/us/en/acrobat/mobile-app/scan-documents.html 

It has in-built OCR and support multiple pages documents.

**Comment by kjantin** [comment]
It looks like the [AdobeScan app](https://itunes.apple.com/app/adobe-scan-pdf-scanner-documents-receipts/id1199564834?mt=8) is $9.99/month/user.
[CamScanner](https://www.camscanner.com/team/price) is $6.99/month/user.

**Comment by kjantin** [comment]
How to apply OCR to a scanned document using Google Drive (free) https://business.tutsplus.com/tutorials/how-to-ocr-documents-for-free-in-google-drive--cms-20460

**Comment by kjantin** [comment]
Another idea from @txau is to create an online tool for OCRing PDF docs based on [Tesseract](https://en.wikipedia.org/wiki/Tesseract_(software)) OCR.

**Comment by txau** [comment]
I've seen the results of this, and while it could be useful for certain situations, I don't see this is the right path to follow. Closing for now.
