### ISSUE TITLE
Advanced access levels for users (beyond admin and editor)

### ISSUE THREAD

**Issue by bertver** [huridocs/uwazi#1246]
Phase 1. purpose would be to allow account administrator at client to 
- Set permissions for access to different operations (editors, analysts, admins)
- Create user groups with permissions create-edit-delete in relation to different content types. 

Phase 2.
Ideally, it should even be possible to attribute permissions to individual users within these groups, as well as for indvidual fields.

**Comment by kjantin** [comment]
Related https://github.com/huridocs/uwazi/issues/1395

**Comment by kjantin** [comment]
![image](https://user-images.githubusercontent.com/354426/73686142-6eba5c80-4695-11ea-8146-c052be3b4fb9.png)

**Comment by kjantin** [comment]
from @RafaPolit

The proposed scenario is to achieve this in two phases:

1: Allow file owner to grant read-only permissions, or full edit permissions to a file by individual user name assignment (this covers almost every use case, but it's not really all that comfortable... still, works perfectly.
2: Create user groups that can be assigned instead of by individual user, this will create the 'circles', but with arbitrary names, not constrained by fixed names.

Phase 1: 30 days

Phase 2: 15 days

**Comment by kjantin** [comment]
Related https://github.com/huridocs/uwazi/issues/1395

**Comment by RafaPolit** [comment]
Our current way of indexing metadata poses a challenge with this model.  Metadata is indexed directly on an entity.  Controlling visibility of already 'inherited' or indexed data within an entity requires a lot of post-processing of documents.

So, our current approach is: the entity containing the info governs what is visible to a user through its metadata.  So, a linked-through-metadata entity will be visible if the parent document is visible, even if the child is hidden.  Relationships to those documents will still be hidden.

Example:
- Entity "Case A" has a victim assigned as a relationship to 'private' or 'hidden' "Victim X"
- Entity "Case A" has a perpetrator assigned as metadata (relationship template property) to 'private' or 'hidden' "Perpetrator Y"

Users will see Case A, they will see Perpetrator X's name (or whatever property is inherited) but they wont see Victim X.

This poses a challenge as to how to communicate this to users.

**Comment by kjantin** [comment]
Next step: collect all user stories and have a discuss with the team about the right approach.

**Comment by txau** [comment]
related: https://github.com/huridocs/uwazi/issues/1308

**Comment by nwyu** [comment]
The issues related to this milestone can be tracked here: https://github.com/huridocs/uwazi/milestone/35.
