### ISSUE TITLE
Implement 'most relevant results' sorting option for Full Text.

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#1247]
Current search results, being ordered by inner metadata properties, puts irrelevant results in front of more exact search matches.

The  issue is: when to use 'most relevant' results as the sorting option?

Current implementation derives the best sorting option using the priority sorting of the combined selected templates.  This has proven to work correctly for non-full text filterings.

So, what would happen here? If someone inputs text:
- it auto-shifts to 'most relevant'?

If so... if the user sorts those results manually by some other property and then changes the search term:
- Does the ordering revert itself to most relevant?
- Do we keep the user selected option?

If so, what happens when the user, without filtering any text term selects a custom sorting property AND THEN inputs a text? Again, do we change the ordering or keep the user selection (potentially never having most relevant results selected).

That is the tricky part to this implementation regarding UX.

**Comment by txau** [comment]
At the moment, full text search results make almost no sense if it is not sorted by relevance.

A quick approach (maybe annoying in some situations) is to always switch to relevance when using full text search. If you want something else, you have to manually select another sorting option?

**Comment by danicatalan** [comment]
I'm in to that solution. It makes a lot of sense as default behaviour and users can always undo the relevance sorting if they are trying to find content with another pattern (by name, by date...).

**Comment by txau** [comment]
Related? #1116
