### ISSUE TITLE
Full text search not working for some documents?

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1260]
https://cejil.uwazi.io/es/document/rfo8wd47zpirixitln9oogvi?searchTerm=derechos

**Comment by danicatalan** [comment]
Are they indexed? I'm trying the same search on the Entity viewer > Relationships tabs, and is not working either:

https://cejil.uwazi.io/es/entity/pm78nlocp2ai3sor

**Comment by RafaPolit** [comment]
I have diagnosed the issue:
- When you upload a document, the system correctly  assigns the "fullText" property inside the "file" property of the document in the database to ALL LANGUAGES!
- When you assign a Template Type and save the changes, the languages in which you DID NOT save the changes from, get the fullText property removed.

This is an important bug, as it will render languages unsearchable.  This will probably require a migration to re-fetch the fullText of all the documents after the bug has been solved.  It will be a lengthy migration.
