### ISSUE TITLE
UI performance drop when reading big documents

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1261]
This is barely usable on my computer:

https://cejil.uwazi.io/es/document/xey0ktht22nh4cxr?page=69&searchTerm=sentencia

**Comment by danicatalan** [comment]
My computer freezes each time I scroll in that document too.

**Comment by kjantin** [comment]
It's ok on my computer.

**Comment by daneryl** [comment]
@txau @dani its fast on my computer, going to try to improve, but probably we will need to do a call to debug.

**Comment by RafaPolit** [comment]
To test speed on this, try two different options with the link above:
- Delete the search terma and scroll
- Search again 'sentencia' and scroll again

I see a big difference in rendering speeds from one and the other.

**Comment by daneryl** [comment]
> To test speed on this, try two different options with the link above:
> 
> Delete the search terma and scroll
> Search again 'sentencia' and scroll again
> I see a big difference in rendering speeds from one and the other.

@RafaPolit @txau @danicatalan found a bottleneck with the instructions Rafa provided, change it to improve performance of rendering when a a search term is present. you can test it [here](https://deploy-testing.uwazi.io/es/document/xey0ktht22nh4cxr?page=69&searchTerm=sentencia)

**Comment by daneryl** [comment]
After some tests it seems the performance its much better, merged and cosing.
