### ISSUE TITLE
Add footer to custom pages

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1262]
We should add the library footer in the whole app, but right now we can start adding it to the custom pages. It will improve the homepage navigation, because right now users will scroll but is not clear where the pages end.

![image](https://user-images.githubusercontent.com/6364153/29707605-1edcd19e-8986-11e7-9343-9d7d29170535.png)

That footer is currently at the bottom of library:

![image](https://user-images.githubusercontent.com/6364153/29707528-d775d580-8985-11e7-8ed7-cdf47488349e.png)

**Comment by RafaPolit** [comment]
I agree!

Could we please get into the habit of reporting a problem on the issue instead of the solution? That way the team can have a discussion of the best approach to solve it? Thanks.
