### ISSUE TITLE
Change footer links to improve navigation

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1263]
Our current footer supports direct links to the main sections of each instance: 

- Library
- Login
- Uploads if logged as admin.
- Settings if logged as admin.

![image](https://user-images.githubusercontent.com/6364153/29707605-1edcd19e-8986-11e7-9343-9d7d29170535.png)

Some suggestions to improve it:

- Sync footer links with header links when custom menus are created.
- Improve footer layout to separate custom links with system links.
- Add Uwazi logo. Should we link the logo to our current website?

**Comment by kjantin** [comment]
Let's definitely update the Uwazi logo and somewhere add "HURIDOCS" to the footer. The rest can wait.

**Comment by danicatalan** [comment]
I created a new issue #1271 to achieve what @kjantin suggests.

I kept this one to talk about footer navigation in the future, and moving it to `Priority: Low`.

**Comment by danicatalan** [comment]
I updated the footer with the request from MFI to have more information inside the footer (not just the logo) also adding the header navigation to improve footer utility.

They want specifically a huge footer with that disclaimer and logo, but in most cases it will be just a paragraph with a logo.

![image](https://user-images.githubusercontent.com/6364153/33170626-3719d6a8-d049-11e7-9803-87fa5735a496.png)

This custom paragraph should be a field text or Markdown text configurable on settings. We can use this field to put current custom logos on the footer (CEJIL, Pretoria and Zorla for example) so we reduce the custom code on the app.

**Comment by danicatalan** [comment]
This is ready to implement, code in branch `1263-footer`

**Comment by txau** [comment]
@danicatalan was this ever merged?

**Comment by danicatalan** [comment]
Nope, never merged.

**Comment by txau** [comment]
This is a stale issue. If its requested again we can reopen or create a new one. Closing for now.
