### ISSUE TITLE
Unable to delete document

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#1267]
When a user clicks on "Delete" on a document, and they click on "Confirm" when asked if they are sure they want to delete, nothing happens - the document remains in the library.

**Comment by RafaPolit** [comment]
@kjantin In what instance is this happening? I just tested on my local machine and everything is working as expected.

**Comment by kjantin** [comment]
It was brought to my attention by the Centre for Human Rights https://afchpr-commentary.uwazi.io/en/library/?q=(order:desc,searchTerm:exhau,sort:creationDate,types:!(%2758b2e5993cad1a2c98dba8f1%27)). I tried it on my own demo instance and I wasn't able to delete a document https://hr-reports.uwazi.io. But, now I tried it again and it worked - so I guess it was a temporary bug!

**Comment by kjantin** [comment]
This is still an issue for Pretoria. They are unable to delete a duplicate file title "Exhaustion of local remedies – article 56(5)" w/ the date added Oct 13, 2016. When you click "delete" it doesn't delete, even after you refresh. 

![image](https://user-images.githubusercontent.com/354426/29773007-79e14616-8bc9-11e7-93de-b43550df8a87.png)

**Comment by RafaPolit** [comment]
Documents for this particular issue are now able to be deleted.

Nonetheless, there is a underlying bug that I am reporting on a new issue.
Closing this.
