### ISSUE TITLE
Unable to upload new documents

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#1270]
When trying to upload documents to https://afchpr-commentary.uwazi.io, the document is stuck in "processing" and never stops. 

![image](https://user-images.githubusercontent.com/354426/29772843-7c827490-8bc8-11e7-93ed-f31c0c5260a4.png)

It seems to only be impacting this instance - I am able to upload docs to other instances.

**Comment by kjantin** [comment]
I was able to upload a document. Will follow up with user to see if this is still an issue.

**Comment by RafaPolit** [comment]
Please, share the PDFs that were failing so we can test that from our side.
