### ISSUE TITLE
Vimeo support

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1281]

**Comment by RafaPolit** [comment]
Vimeo support is working.  Custom markup code is:

```
{vimeo}(https://vimeo.com/37942739)
```

Some other formats like **player.vimeo.com/id?properties** are also supported, as well as channels.  If there are video URLs that the parser is not able to extract the ID, there are some indicators included as well as the Vimeo own results.

**Comment by danicatalan** [comment]
@RafaPolit can we customize the iframe URL to clean up the viewer? Embeded videos on Uwazi are showing all the video metadata, and it would be great if we can clean all this noise.

<iframe src="https://player.vimeo.com/video/67430069**?title=0&byline=0&portrait=0**" width="640" height="480" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

**Comment by txau** [comment]
@danicatalan pleas create a new task!
