### ISSUE TITLE
Empty sorting properties in cards should render the label

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1290]
- Always display the label.
- Remove the quotes and display a dash or similar.

![screen shot 2017-09-07 at 09 03 39](https://user-images.githubusercontent.com/489831/30170118-779a7348-93ab-11e7-99e3-d4a28c8556b5.png)

**Comment by danicatalan** [comment]
![image](https://user-images.githubusercontent.com/6364153/30320246-6c035a4e-97b2-11e7-8d7a-35de776ca004.png)

This is working properly on empty properties.

I need some help to display it when sorting by a property and that property doesn't exists. I can display the dash but not the label. @RafaPolit can we look this together?
