### ISSUE TITLE
Overhaul user password set process

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#1292]
Current process of creating users and assigning password makes sense mostly if you are creating yourself as user.   But if you are granting access to someone else, there is little to no information available.

- You receive a mail with "password set", but other than the URL, you have no idea what this is about.  What page / instance, why you are receiving the mail, nothing.  Zero info as to what that mail is.  If you are not 'expecting it', you would probably dismiss it as spam or phishing.  You also have **NO IDEA what your user name would be**.
- Upon clicking on the link you reach a page with password set fields, again, with no info as to what user you are creating the password for or what you will be facing afterwards.
- Upon assigning a password, you are not redirected anywhere, not even the library (or better yet the login), you are left in that same page.

Again, if you are 'aware' this is happening, its bad, but not catastrophic.  If someone creates you an account without letting you know by phone or mail or message, then people are going to send our mails to spam!

**Comment by kjantin** [comment]
Draft text for the email:

Subject of email is currently “Password set”. Let’s change that to “Welcome to [uwazi-instance-name] | Complete account creation process

Hello!

The administrator of [uwazi-instance-name] has created an account for you under the username [username]. To complete this process, please create a strong password by clicking on the following link:
[set password link]

For more information about the Uwazi platform, visit https://www.uwazi.io. 

Thanks!
Uwazi team

**Comment by kjantin** [comment]
We should probably set an expiration for these password set links...can we do that?

**Comment by kjantin** [comment]
![image](https://user-images.githubusercontent.com/354426/31098649-5653dcc0-a791-11e7-8a94-a970acb7a7e7.png)

Can we add the username attached to this password/email to this page? The text there can be something like:

> To complete the account creation process, please create a password for your account.

**Comment by RafaPolit** [comment]
This is mostly finished, but I have some questions / suggestions:

- The mail is being sent by **Uwazi <no-reply@uwazi.io>** no matter which instance sends the mail.  This is less than ideal, but it may not be a deal-breaker.  If we want to change the sender, we would probably need to add to the 'collection' page in settings a 'collection mail', just as we have the collection site name.

**Comment by danicatalan** [comment]
I really think we should remove username and use emails for login instead.

When the user clicks in the link, a simple "Set a password for this email account" feedback should work. Once a user puts the password, we redirect to the login page and users can login with their email and password.

**Comment by RafaPolit** [comment]
I agree.

**Comment by kjantin** [comment]
+1 for removing username and just use emails.
I don't know the right answer for the email address question.
+1 for creating a separate issue for setting an expiration date.

**Comment by RafaPolit** [comment]
@danicatalan Just one thing: users log with user name, not email!
