### ISSUE TITLE
Elastic reindexing has been giving silent errors and there are ghost files ON THE DATABASE!

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#1294]
For some time, there were errors during document saves, deletes and editions.  This happened around January 2017.

There are documents on the Database with files no longer present on the hard drive.  Those files are not being correctly indexed, and therefore do not appear in Elastic.  But once a correct migration takes out the fullText of those ghost files, they will be indexed and REAPPEAR on the libraries and upload sections, potentially duplicating info.

We need to figure out a way of dealing with this, options including allowing the documents to get indexed and then rely on clients to delete manually.  Other option is to assume that this documents have been lost and delete them without any client interaction.

This needs discussion.

**Comment by daneryl** [comment]
@RafaPolit @konzz @txau @kjantin  this are the instances that are missing documents, all are from the same server,
so something happened on that server ?
im assuming that Humphrey fixed his instances and thats why it has not missing documents right now.

what do we do with this ?

Dra
Total Documents:  76
Missing Documents:  76

Kristin
Total Documents:  40
Missing Documents:  26

Cjgea
Total Documents:  10
Missing Documents:  3
