### ISSUE TITLE
Redesign login page

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#13]

**Comment by danicatalan** [comment]
![login](https://cloud.githubusercontent.com/assets/6364153/15975489/014f5c5c-2f4e-11e6-8e55-3dbd9ad00000.png)

@txau where can I get the logotype? I want to include it inside the login page.

**Comment by danieldesposito** [comment]
Eugene is redesigning it. Will be Uwazi. Not UwaziDocs.

On Friday, June 10, 2016, Dani Catalan <notifications@github.com> wrote:

> [image: login]
> <https://cloud.githubusercontent.com/assets/6364153/15975489/014f5c5c-2f4e-11e6-8e55-3dbd9ad00000.png>
>
> @txau <https://github.com/txau> where can I get the logotype? I want to
> include it inside the login page.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/huridocs/uwazi/issues/13#issuecomment-225267373>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AEONgnBTHNlJDJVS8VpY7UtlFfdGK17aks5qKbPYgaJpZM4Ipo-O>
> .
>


-- 
*Daniel D'Esposito*
Executive Director
<https://www.huridocs.org/>
Geneva Office
3, rue de Varembé
1202 Geneva, Switzerland
+41227555252
PGP: 7C04D782
<https://pgp.mit.edu/pks/lookup?op=get&search=0xAF3C91D57C04D782>
website <http://huridocs.org/> | facebook <http://facebook.com/huridocs> |
twitter <http://twitter.com/huridocs> | linkedin
<https://www.linkedin.com/company/huridocs> | newsletter
<http://eepurl.com/raFyP>

**Comment by danicatalan** [comment]
I get the old logo from the website: we will update it when Eugene designs the new one. Also I uploaded the video with all the feedbacks: wrong password & how to remember password #85.

https://github.com/huridocs/uwazi-assets/tree/master/13_login_page

**Comment by danicatalan** [comment]
- [ ] Avoid content jumping on feedback message.
- [ ] Login failed (mark both inputs as error).
- [ ] No e-mail address (just "login").
- [ ] "Send recovery e-mail" as button text.

**Comment by danicatalan** [comment]
Updated: https://github.com/huridocs/uwazi-assets/tree/master/13_login_page

**Comment by txau** [comment]
Good enough. There is a missing part, the landing page where the user resets the password. But there is no need for an extra design @konzz can figure it out based on these screens. Moving it to dev.

**Comment by konzz** [comment]
@danicatalan Where can I find the image of the logo? the one in uwazi-assets it's not the same as in the picture above.

**Comment by UjoNyawara** [comment]
@konzz can I send you the latest version of the logo?

**Comment by danicatalan** [comment]
Yeah, because the picture is older than the video. The right one is the svg inside assets, but it would be great if you have the new logo.

@UjoNyawara have you cleaned the typo alignement?

**Comment by daneryl** [comment]
finished, missing only the new logo, created #188
