### ISSUE TITLE
I want my users to see who added the document to the collection

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#1308]
One approach:
Each editor and/or administrator in Uwazi already has a username created by the administrator. But it would be nice if there was an additional field called "Display name" that the editor/admin could use to modify how their name is displayed in Uwazi. For this situation, some editors/admins may want to display the name of an organisation instead of their name, or maybe both their name and the org.

**Comment by danicatalan** [comment]
What about removing usernames and login with email? That way we don't mess the thing with two names (display name and username).

**Comment by txau** [comment]
@danicatalan that makes sense. So we keep only e-mail and display name.

**Comment by fnocetti** [comment]
@txau  I think this is a valid feature but it's not related to user permissions.
Permissions will need to consider this feature when implemented (or the other way around :D ) but definitively a separate issue. This can have a wide fan of side effects and probably won't even share the data structures or algorithms.

I'll re add the Enhancement tag and Needs review to check what's the better approach with the team. Also, I'm taking it out of the milestone.
