### ISSUE TITLE
Searching for a number shows the page numbers in the snippets

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#1309]
<img width="278" alt="screen shot 2017-09-21 at 16 49 49" src="https://user-images.githubusercontent.com/948117/30702370-0bf73232-9eed-11e7-9d92-9574769179a1.png">

**Comment by RafaPolit** [comment]
This was not only a problem of showing up in snippets, the error was actually using those strings as part of the search.

@daneryl 's fix involved changing the mapping of the elastic index, a much more extensive task than just removing the results from the snippets.
