### ISSUE TITLE
Improve whole App blank state

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1311]
- [ ] Review the current blank state when a developer makes a ` ./database/blank-state.sh`
- [ ] Remove uploaded documents / created entities.
- [ ] Remove document / entity types.
- [ ] Identify new issues in the user workflow while creating and uploading their first content.
- [ ] Replace "Our story" document with a new "Uwazi Manual" cc/ @kjantin

**Comment by RafaPolit** [comment]
@danicatalan do we have the manual in PDF?

**Comment by danicatalan** [comment]
@kjantin should make a draft, if she doesn't have time I can prepare something but not as good as she could.

One doubt I have with this is - if a blank state doesn't have document types... what kind of type is this document?
