### ISSUE TITLE
Connect to paragraph throws JS error

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1314]
![screen shot 2017-09-26 at 11 37 12](https://user-images.githubusercontent.com/489831/30874944-1f96857a-a2af-11e7-9a52-22b4b16f1fe2.png)

**Comment by daneryl** [comment]
@txau can not replicate in any instance, can you check this again ?

**Comment by daneryl** [comment]
fixed problems found with pdfjs worker config, error was showing on firefox.
