### ISSUE TITLE
Fulltext search problems when the search matches in different languages

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#1319]
Fulltext search problems when the search matches in different languages

Example: 
If you search "las victimas", "las" is a stop word in Spanish, but not in Portuguese (it means something like "the women")  this causes ElasticSearch to return some Portuguese documents matching "las" as the most relevant.

We can boost one language, so we get better results, but the problem will be to know which language is the search on, one posibility is try to detect the language of the search term ("las victimas") the same way we do with the documents, but its not guaranteed that we will always get it right, another idea is use the language the user has selected in Uwazi, but again that does not mean the user is searching in that language.

**Comment by konzz** [comment]
@txau we discussed this during the sprint planing, any ideas?

**Comment by txau** [comment]
I guess that is only a problem when you have documents in different languages mixed, which is not so common. And even though, is unclear whether that is a problem, because if you are actually searching in Portuguese, that result is a good result.

I don't think we need to fix this atm.
