### ISSUE TITLE
issue on local installation: User creation

### ISSUE THREAD

**Issue by bertver** [huridocs/uwazi#1334]
South Asian Centre for Legal Studies

contact person: Chrishanthan Daniel <chrishanthan.daniel@gmail.com>

When creating a user, the system requests for an email ID but the password is not received at the given email address. 

We previously got an error on the Ubuntu terminal, but after installing sendmail the error has gone, but still the email isn't getting pushed to the user

**Comment by RafaPolit** [comment]
There needs to be a correct smpt configuration for the mailing system to work.

Is sendmail working outside the uwazi platform?

**Comment by chrisha88** [comment]
We are not using sendmail for anything else.

How do we do the smtp configuration?

**Comment by RafaPolit** [comment]
The easiest way to configure SMTP is in the settings area: settings -> collection.

The SMPT configuration expects a Nodemailer configuration object.  Something like:

```
{
    host: 'smtp.example.com',
    port: 587,
    secure: false, // upgrade later with STARTTLS
    auth: {
        user: 'username',
        pass: 'password'
    }
}
```

For more detailed options, please check: https://nodemailer.com/smtp/

Once that is working, that configuration object can be moved to the file:
 /api/config/mailer.js

for a more secure and private location.

You would, of course, need an SMTP provider or some mailing service that allows for some of the available methods (of which Nodemailer has plenty of).

Hope this helps.

**Comment by chrisha88** [comment]
@RafaPolit we don't have a location as /api/config

**Comment by chrisha88** [comment]
Hi @RafaPolit, I updated the settings. We use Gmail back-end for our mail server so what should be the host and port values?
Also the username should be withing quotes? (eg: If username is foo should the value be _foo_ or _"foo"_).

**Comment by RafaPolit** [comment]
@chrisha88 Please, check the documentation of Nodemailer for Gmail.

Gmail protocol will require that you set the account to less secure settings, so I'm not sure that is the best way to go.

Please read this two links for configuration options using Gmail:
https://nodemailer.com/smtp/oauth2/
https://community.nodemailer.com/using-gmail/

**Comment by chrisha88** [comment]
alternatively I have installed MongoDB compass, so I could insert a user via a query too?

**Comment by RafaPolit** [comment]
That should be a last resource, there are things that the process does beyond the user creation: activate account, validate email for password recovery purposes, etc.

Lets try to configure the mail first.

**Comment by chrisha88** [comment]
@RafaPolit, this issue is solved. But the link to activate the account starts with local host hence doesn't accept the new password keyed in.
This will be under issue 1335 though isn't it?

**Comment by RafaPolit** [comment]
Glad to hear.

The issue with the 'localhost' URL is happening because you are using a localhost address to create the accounts.  I'll explain:  if you are accessing the instance as localhost, for instance: http://localhost:3000/settings to send the invitation, it will use that address as the instance URL.

So, if you have a proper domain, please, create the account from that url, for instance: http://yourdoumain.com/settings.  This will send a 'yourdomain.com' URL.

If you are using a local IP, for an intranet installation, then use something like http://192.168.xx.yy/settings for it to send with that address.
