### ISSUE TITLE
Unable to connect text in one document to text in another document

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#1346]
When I highlight text in this document https://hr-reports.uwazi.io/en/document/wcf0ceykn5sode5ja038r529 and try to connect it to text in another document, when I click on the green arrow I expect that it will bring me to that document I selected in order to highlight the target text. But instead it doesn't do anything - I click the green arrow and nothing happens.

**Comment by danicatalan** [comment]
@kjantin have you selected the connection type?

**Comment by kjantin** [comment]
Hm, I don't remember whether I selected that or not before, but now when I try it it works fine. So I guess I missed that step. :) I'll close this issue.
