### ISSUE TITLE
Cannot see any uploaded files on ihrda.uwazi.io

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#1354]
Hey guys,
So, we at IHRDA cannot see any files on Uploads in IHRDA.uwazi.io
This is what we see. After uploading several docs. So, we are stuck. **Cannot  #work.**
@kjantin @danicatalan @konzz 
<img width="960" alt="ihrda1" src="https://user-images.githubusercontent.com/22650647/32490711-2deb7d10-c3c5-11e7-9584-386245afac94.png">

**Comment by kjantin** [comment]
@HSips try changing the way the documents are being sorted. When I changed "sorted by: Case head notes" to "sorted by: Title" I was able to see all the PDFs. Let me know if that doesn't work.

**Comment by txau** [comment]
@daneryl @RafaPolit @konzz this might be a bug, totals display zeros until you change the sorting criteria, then it works. Please check when possible.

**Comment by HSips** [comment]
Thanks for this guys. Just checked and yes, the first time the docs are there. After deleting a number of failed uploads I tried to refresh Uploads and it's not responding to the change in sorting preferences. SO hanging again.

**Comment by HSips** [comment]
Hey guys, now.. even when changing sorting criteria.. results is now zero..
<img width="960" alt="ihrda2" src="https://user-images.githubusercontent.com/22650647/32537901-39ffa936-c475-11e7-9229-d92009b07fed.png">

**Comment by daneryl** [comment]
@HSips this is fixed now, AfCHPR Dissenting Opinion -> Rights Violated was not properly configured, but it was showing as if it was, i`ve just selected again the correct thesauri.

@txau @kjantin this is a bug, do not know what happened, but Rights Violated on this template was pointing to a nonexistent thesauri, we need to show this properly in the template configuration and make sure that even if this scenario occurs again be able to see the uploads list ?
