### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Ngenarr** [huridocs/uwazi#1361]
Translations of ACHPR Provisions added recently on ihrda.uwazi.io refuse to save

**Comment by daneryl** [comment]
@Ngenarr can you explain with a more detail the problem ? so i can take a look ? thank you.

**Comment by Ngenarr** [comment]
The translations for ACRWC provisions  refuse to change even after the
translations are put in and saved. It automatically goes back to English.

Ngenarr-Yassin Jeng
Tel: +220 7372477
Email: ngenarryassin@gmail.com | ngenarryassin@yahoo.com
Facebook: Ngenarr-Yassin Jeng
Twitter: @miss_petite_j (Ngenarr-Yassin Jeng)

**Comment by konzz** [comment]
@Ngenarr We found the issue, and it will be fix as soon as we deploy.

**Comment by daneryl** [comment]
solved #1374
