### ISSUE TITLE
Sort by relevance when no full txt search

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1365]
Apparently sorting by relevance when no full text search has been queried is confusing. Maybe this property should not appear unless you've launched a full text search?

**Comment by danicatalan** [comment]
Yeah, and we can change "Relevance" to "Search relevance" to specify that this sorting is only available while searching and not in other contexts.

**Comment by habbes** [comment]
After you search for something, the sorting is set to "Relevance" automatically. When you try to change the sorting to use another field, it goes back to "Relevance". Is this a bug? Should I try to fix it as well, or is that how it's intended to work?

**Comment by txau** [comment]
@habbes do not fix this for now. We have other priorities.

**Comment by habbes** [comment]
@txau, technically it's already fixed. It needs QA though. I may have taken some low-priority tasks last week that were not in the sprint.

**Comment by txau** [comment]
@habbes great. Thanks! Let's ask @RafaPolit and @konzz for a QA.
