### ISSUE TITLE
https://www.uwazi.io/ returns 404 as status code

### ISSUE THREAD

**Issue by konstin** [huridocs/uwazi#1366]
[I don't if this is right place to report this, but I don't know any better one]

When opening https://www.uwazi.io/, an error 404 is returned despited the actual content being delivered. I only noticed because that status code triggered the Wayback Machine addon.

**Comment by txau** [comment]
Thanks for reporting @konstin. I'm going to check it out.

**Comment by danicatalan** [comment]
This should be fixed now, thanks for the report @konstin!
