### ISSUE TITLE
Make the drag&drop area smaller in uploads. Rearrange text

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#137]

**Comment by danicatalan** [comment]
I have made two reductions for the D&D area.

![one-line](https://cloud.githubusercontent.com/assets/6364153/16087622/eb715988-3323-11e6-9bdf-176ff946afa1.png)
![two-lines](https://cloud.githubusercontent.com/assets/6364153/16087623/eb8b5d6a-3323-11e6-88a9-3e1ea31ddde6.png)

Personally I think the one-lined is the better one. @txau what do you think?

**Comment by txau** [comment]
I prefer the one liner too, but with "or click here to browse your local files" instead of "or choose your file"

**Comment by danicatalan** [comment]
![one-line-](https://cloud.githubusercontent.com/assets/6364153/16087892/07c2daca-3325-11e6-9b2a-a57929a92f78.png)

Don't you think it's too much long?

**Comment by txau** [comment]
I think its ok. My only concern is how it is going to be displayed in smaller devices.

**Comment by danicatalan** [comment]
Ha! We didn't think about it, but there is no D&D in mobile.

![mobile](https://cloud.githubusercontent.com/assets/6364153/16088144/0193d02c-3326-11e6-8d0d-d271b2536876.png)

**Comment by txau** [comment]
Good point
