### ISSUE TITLE
URLs with parentesis break markdown links

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1380]
**How to reproduce it**

Add a filter URL to a link, for example http://localhost:3000/en/library/?q=(order:desc,sort:metadata.date)

`[This will break closing on the first parentesis](http://localhost:3000/en/library/?q=(order:desc,sort:metadata.date))`

**Comment by daneryl** [comment]
@RafaPolit @danicatalan its a Marked.js issue, https://github.com/chjj/marked/issues/619, its a difficult one explained on that issue, also the maintainer seems that is not active for a long time, https://github.com/chjj/marked/issues/756
i think we should change the library we use for markdown, maybe https://github.com/markdown-it/markdown-it ?

**Comment by kjantin** [comment]
Idea for solution: create custom hook for internal URLs
