### ISSUE TITLE
Flag icon is now displaying as text

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#1384]
On the Japiqay.uwazi.io instance, instead of the Peru flag displaying on the cards, the text "Peru flag" is displaying.

![image](https://user-images.githubusercontent.com/354426/33135615-e96072ec-cf70-11e7-9d78-dc2def6864e7.png)

**Comment by HSips** [comment]
1. This is also happening in IHRDA CLA..
2. I don't know if this is same or different issue.. but some (not sure the number as yet) of decisions are against more than one country in IHRDA CLA... See screenshot.. can more than one flag be displayed?
<img width="961" alt="ihrda3" src="https://user-images.githubusercontent.com/22650647/33159494-699df3ea-d024-11e7-984a-c885f62d434f.png">

**Comment by daneryl** [comment]
fixed e73ac7ea48dfb930715540e3caeddd4414c96c25
