### ISSUE TITLE
Select / multiselect with custom values

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1388]
Instead of thesauri or entities, this properties (select / multiselect) should have an option to add a custom list of option for just that property.

**Comment by txau** [comment]
How is that different from a thesauri and why select/multiselect should have that option?

**Comment by danicatalan** [comment]
Users understand why they need to create thesauri for long lists of options, but not for booleans, for example. They expect creating the thesauri directly from the property should be allowed for small options like Yes/No, Active/Inactive...

**Comment by txau** [comment]
I think this needs further explanation. I'm totally up for being able to add values to thesauri from the field, but still I don't understand how that is different from "custom list of options".

**Comment by danicatalan** [comment]
We already solved this creating a thesauri (as usual), so we don't need to focus in this now but I would like to keep this task on backlog for the future when we can focus on improving and implementing nth features.

**Comment by txau** [comment]
LGTM!

**Comment by txau** [comment]
Duplicated: https://github.com/huridocs/uwazi/issues/277
