### ISSUE TITLE
Text markers for showing references

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#139]
- [ ] On click on the markers, it will highlight the referenced text
- [ ] On lick on the marker, it will show the reference(s) in the right panel

**Comment by konzz** [comment]
Added UX label, Dani needs to investigate how can be done

**Comment by danicatalan** [comment]
There's a problem with the markers and the html conversion, because all the text is `position: absolute`.

I self assign this to research how can we position these markers.

**Comment by txau** [comment]
Keep it simple, underline or soft highlight all references when the connection panel is open.
