### ISSUE TITLE
Full text search highlights when opening a document

### ISSUE THREAD

**Issue by whyfrycek** [huridocs/uwazi#1390]
Story:

-  perform a full text search, for example using "torture" on https://minorityforum.uwazi.io
- I receive all cards that include this word, with highlights of the text
- I open the document in the card
- I do not see the highlights

Expected behaviour: I see the highlights within the document

**Comment by txau** [comment]
@whyfrycek but highlights are being displayed within the text:

![screen shot 2017-12-03 at 17 13 10](https://user-images.githubusercontent.com/489831/33531022-44ad53ec-d84d-11e7-9dc5-9b039a661306.png)

**Comment by danicatalan** [comment]
An easy solution should be opening the document in that tab with the query from the library.

**Comment by whyfrycek** [comment]
Yes, exactly! Right now it feels that Uwazi "forgets" my query when I open the document.

So, right now the story is:
- I search for "torture"
- documents are displayed with highlights in cards
- I open document
- I need to search for "torture" again to see highlights

Expected would be that instead of the last part:
- my search for torture is carried over

**Comment by danicatalan** [comment]
Yeah, Uwazi doesn't stores the query when opening the document from the library. It only stores the query if accessing from the Search tab when clicking a page number.

**Comment by txau** [comment]
Related: https://github.com/huridocs/uwazi/issues/1391
