### ISSUE TITLE
How to organize documents before knowing the data model?

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1394]
As a user, I have a collection of PDF documents in my computer that I want to upload in Uwazi, but I don't have time to work on the data right now - I need to upload all the documents first and organize them quickly to later access them and work on the data.

I still don't know the data model, and still didn't organize them per type, but I know that all the documents I uploaded right now are from the Human Rights Council, session 35.

I will keep uploading documents from different session, and when I have the data model ready, I would like to select all the documents from one session and work on them at once, so I can organize my workload by batches (for example, complete the metadata of all the documents in a session each day).

How can I achieve this?

**Comment by txau** [comment]
I guess for this scenario users should:

- At least create a document type.
- Select all of them, assign the doc type and publish.

Do you feel like there is anything wrong about this approach?

Another possibility is having a default template for documents and entities that only have the default properties (title and upload date) that way is super quick for users. Even if these templates are not very useful, we can consider them auxiliary templates.

**Comment by danicatalan** [comment]
Publishing is not mandatory - is more for self-organization before adding data to the documents.

For example, I have 300 documents in three different folders (Leak1, Leak2, Leak3) and I want to publish them with Uwazi. I upload the whole collection today to see how the documents are stored in Uwazi, and I will evolve the data model once I played around the interface and understand where are my documents and what can I do with them.

If I want to upload the 300 documents now and organize them quickly, I need to:

- Create a fake document type (**Test document**).
- Create a fake thesauri (**Leaks**) with Leak1, Leak2, Leak3.
- Create a fake multiselect on the document type (**Leaks**).
- Upload the first 100 hundred documents, assign Test document, select Leak1 from Leaks property.
- Upload the second 100 hundred documents, assign Test document, select Leak2 from Leaks property.
- Upload the third 100 hundred documents, assign Test document, select Leak3 from Leaks property.

It would be nice if I can upload and tag them without creating any document types or thesauri, so I have some "default documents" with some tags I can use later to review the batch and start assigning Document types and metadata.

I don't know if this tagging is useful once the documents are published.

**Comment by txau** [comment]
Lets have a discussion about this sometime soon. I think there is more to it.

**Comment by txau** [comment]
This will be part of the template-less features. Closing for now.
