### ISSUE TITLE
Create a role restricting consultation and editing of non-owned documents

### ISSUE THREAD

**Issue by AlWalid** [huridocs/uwazi#1395]
Request by a deployed instance beneficiaries to create a role that is only able to input and edit its own documents/entities. any other user with the same level of permissions will not be able to see his colleagues documents.  Higher user privileges are able to consult and modify.

**Comment by danicatalan** [comment]
Related to #1113 and #1246.

**Comment by kjantin** [comment]
I believe this is being addressed by hosting multiple Uwazi instances and then writing a script to import data into one "parent" instance.

**Comment by txau** [comment]
@kjantin I think this particular permissions could be implemented. They look simple and I think is something we want for everyone.

**Comment by txau** [comment]
Duplicate: https://github.com/huridocs/uwazi/issues/1246
