### ISSUE TITLE
"Learn more" link does not link to the right place

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#1396]
In the new benetech.uwazi.io instance, i noticed that when you click on a filter, you see the "No common filters" message, and a "Learn more" link, but that link just opens up another tab with the same benetech.uwazi.io instance. I think it's supposed to link to the user guide?

![image](https://user-images.githubusercontent.com/354426/33454566-42b4dcf8-d5e7-11e7-9829-bac0d4ea5ce0.png)

**Comment by danicatalan** [comment]
Yes, it should.
