### ISSUE TITLE
List view as complement to cards

### ISSUE THREAD

**Issue by whyfrycek** [huridocs/uwazi#1397]
Rather than in cards, I want to see the collection as a list (bonus: with thumbnails). It makes it much easier to compare entries by metadata. This does not mean we should not have cards, but perhaps allow this through a toggle.

Is this already addressed in #1110 ?

**Comment by danicatalan** [comment]
@whyfrycek this is something similar to that issue, but instead of changing the visualization from cards to graphs, it should change from cards to list.

**Comment by txau** [comment]
Not so sure of that feature. We should discuss. The thumbnails part should be a separate issue (they can also be displayed in cards).

**Comment by danieldesposito** [comment]
The thumbnails is the real feature am interested in.
There is already some code for Wordpress that does this: https://wordpress.org/plugins/pdf-thumbnails/

**Comment by danieldesposito** [comment]
There is also a thumbnail feature in Document Cloud. Its not an important feature for sure. But useful for repositories of manuals where there is a cover page.

![screen shot 2017-12-18 at 16 32 13](https://user-images.githubusercontent.com/4427138/34114123-2be8e6e8-e412-11e7-893f-f4d5c6f225be.png)

**Comment by danicatalan** [comment]
@danieldesposito thanks for sharing this! We already have a issue to implement thumbnails on documents, it would be great if you share this inspiration there so we can use all information available once we start developing this feature.

https://github.com/huridocs/uwazi/issues/817

**Comment by txau** [comment]
We definitely want the thumbnail feature. Unfortunately we are not going to be able to tackle this issue soon.

**Comment by simonfossom** [comment]
@txau is this still relevant? 
Could you provide more details if it is pls. Thank you! :)

**Comment by txau** [comment]
@simonfossom I think you are in a btter position to answer that question. I guess the initial request is already covered by #3050 but there is a comment asking for another kind of view. Do you think we should implement that as well?

**Comment by simonfossom** [comment]
I think we've covered this with the table view. If user wants to have just list of titles, he can do this by hiding other columns. 👍

**Comment by txau** [comment]
@simonfossom I think rather than a list of titles they are asking for card list with screen-wide cards and properties distributed in the real state. As in @danieldesposito 's screenshot.

**Comment by simonfossom** [comment]
The only difference is a thumbnail. It makes row 4x higher, but still, images are very small and they are very similar to each other. I have trouble believing that this thumbnail can be used as a visual cue to recognize the document.

I think table view is much easier to navigate, but we'll list people that asked for list view and talk to them to see if table view solves their problem or do they sill think this kind of view is needed.

**Comment by txau** [comment]
@simonfossom my interpretation is that the initial request from @whyfrycek is covered by table view. The added comment from @danieldesposito has the particularity of displaying the metadata in lines. 

So in card view you get:
```
Title
Thumbnail
Date
Metadata 1
Metadata 2
...
```
In table view you get:
```
Thumbnail | Title | Date | Metadata 1 | Metadata 2 | ...
```

In @danieldesposito 's suggestion you get something like:
```
Thumbnail | Title
          | Date | Metadata 1 | Metadata 2
          | Metadata 3 
          | ...
```
This is actually a common layout, ie:
https://arxiv.org/search/?query=ai&searchtype=all&source=header
http://www.arxiv-sanity.com/toptwtr

**Comment by simonfossom** [comment]
I see. But this is a completely different layout from table-view. It'a more like different card-view than table-view.  And it would lose all filtering and sorting functionality imagined for the table view.
Honestly, I'm not sure what problem this solves. 🤔

**Comment by txau** [comment]
Ok. I'm convinced =)
