### ISSUE TITLE
Make filters visible without having to select document collection

### ISSUE THREAD

**Issue by whyfrycek** [huridocs/uwazi#1398]
In filters, make the thesauri visible without having to click the collection first, so as to make the structure immediately visible. User reports: "Otherwise I just looks like a wall of documents."  

Possible solution: if there is only one document type, it should default to the taxonomies. For more than one, this would merit discussion. If there are many filters, other document types could get lost.

**Comment by danicatalan** [comment]
Related to #1086.

**Comment by txau** [comment]
The default filters when there is only one document type is part of the solution. We've been discussing for a while a revamp of how filtering works. I guess we need rather a way to configure the default filters even if there are more then one document type.

**Comment by konzz** [comment]
@whyfrycek @txau @danicatalan I've checked and now we only calculate the common filters when there is a type of entity selected, as an easy solution we could change it so is also calculated when there isn't any type selected so you will see the filters that all type of documents have in common.

**Comment by txau** [comment]
@konzz that is not the solution to this problem. Most likely, they are not going to have a common filter for all kind of documents. What we need is a settings section for defining default filters. 

Ie. a "Country" filter may be available for 7 out of 8 templates, thus this filter won't appear as common to all templates. But you can force it to appear as default, therefore, if used, it will leave all results from one of the template types out of the results.

**Comment by txau** [comment]
Related: https://github.com/huridocs/uwazi/issues/1086

**Comment by danicatalan** [comment]
Add a checkbox on Setting "Show by default on filters". Add a tooltip to explain the property will be showed in filters if there is no document type selected.
