### ISSUE TITLE
Discuss amount of information shown in the cards

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1400]
This kind of scenarios makes me think that probably cards should have limited space per property for rendering, using side panel in case of wanting more info:

![screen shot 2017-12-03 at 16 36 47](https://user-images.githubusercontent.com/489831/33530712-a86ce84c-d849-11e7-84e9-934456c426eb.png)

**Comment by danicatalan** [comment]
I like how this website crops the description of long texts to keep a consistent layout:

![screenshot 137](https://user-images.githubusercontent.com/6364153/33554078-93104e64-d8fb-11e7-8a08-0d7a6bd97026.png)
