### ISSUE TITLE
Restrict viewing information to only logged users

### ISSUE THREAD

**Issue by AlWalid** [huridocs/uwazi#1402]
Actually, users can see documents even if they are not logged.
It is important to have a feature that enable hiding information for non-logged users especially when the documents are not meant to be shared publicly

**Comment by kjantin** [comment]
Proposed solution: add option to "Settings" to check whether or not this instance is private. (added to all instances)
Question to @AlWalid - is it ok if all the users are able to edit all the documents (for now)?

**Comment by AlWalid** [comment]
Ideally users shouldn't be able to view / edit other users documents. But it is related to #1395 
Having a new role that enables the consultation and editing of only the user document/entities
