### ISSUE TITLE
Upload box doesn't appear after creating the first template

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1405]
**Current behavior**

- I create a new instance without any document type - My files is showing a placeholder saying "You must create some templates...".
- I create a template for documents called "Law".
- I come back to My files to start uploading my documents.
- I can't find the upload box.
- I refresh the page, the upload box appears.

**Expected behavior**

- Upload box appears once I create the template and I'm back to my files without refreshing the page.

![screenshot 210](https://user-images.githubusercontent.com/6364153/33650934-43cca284-da64-11e7-9e64-a6c7982d95e7.png)

**Comment by txau** [comment]
There are some similar issues in several places of the app. For certain information is not available after creation until you refresh, confusing users.

**Comment by konzz** [comment]
@danicatalan tested it, and can't reproduce.
@txau can you explain where it happens and how to reproduce?
