### ISSUE TITLE
Add two factor authentication to login process

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#1406]
To improve the security of the system, we can add 2fa using Google Authenticator or Yubikey (or both, or other?).

**Comment by kjantin** [comment]
Estimated time to integrate this into Uwazi: 5 days

**Comment by RafaPolit** [comment]
There is a growing interest for this feature.  Changing priority.

**Comment by bertver** [comment]
This request is included in the project with Freedom House and partner in the Philippines, with four days of development time and one day of coordination time at 500 USD per day.

**Comment by mareknerko** [comment]
adding Michael @vorburger  as he is interested to help with it?

**Comment by kjantin** [comment]
We're again looking for someone to develop this - anyone interested? :)

**Comment by vorburger** [comment]
@mareknerko my priorities are, erm "evolving", and I won't have the time
for this in November and December. Maybe January, but if you have anyone
else who gets to it before, I will take no offense at all- on the contrary!
;)

>

**Comment by RafaPolit** [comment]
Currently looking into https://www.npmjs.com/package/otplib to give support for Google Authenticator.

Most referenced library is Speakeasy, but that has not received any support in 3 years.

**Comment by RafaPolit** [comment]
- [ ] Check cookie validity / expiration date
