### ISSUE TITLE
Problem with facets when I set a collection as home page

### ISSUE THREAD

**Issue by danieldesposito** [huridocs/uwazi#1410]
When I set my collection as home page in the collection settings, the facets are no longer active, I click on them but no filtering happens: https://nonprofit.uwazi.io
Actually most of the other hyperlinks don't work either.

**Comment by konzz** [comment]
Hi @danieldesposito can you provide more information on how to reproduce it?
How do you set the collection as home page in the collection settings?

**Comment by txau** [comment]
@danieldesposito tried to reproduce the problem without luck. Looks like this has already been fixed. Closing for now, please reopen if the problem persists.
