### ISSUE TITLE
Editing metadata while processing

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1413]
If a file is uploaded and keeps looped in processing, users can edit the metadata. Should we block this behavior?

They spend a lot of time filling the metadata in docs that should be deleted because this processing loop.

**Comment by txau** [comment]
I guess we need to prevent the processing lock, not preventing the users from filling in the metadata. They could even re-upload the document without loosing the work they've done in metadata.

In other words, if we have a bug in processing, lets fix that bug instead of cutting down usability.
