### ISSUE TITLE
Issue when creating user

### ISSUE THREAD

**Issue by chrisha88** [huridocs/uwazi#1414]
Hi guys,

I am getting the attached error when trying to create the user.

![create user](https://user-images.githubusercontent.com/33055856/34027102-81f05b82-e180-11e7-8ac9-b5221e909657.PNG)

**Comment by RafaPolit** [comment]
User creation requires a working mailing system configured.  The preferred method would be a SMPT server.  Have you configured Uwazi to point to an SMPT server?

**Comment by chrisha88** [comment]
We have set up a SMTP server. There is no issue when creating the 2nd user. The above error occurs when creating the 3rd user.

**Comment by chrisha88** [comment]
Still getting an error when creating the 3rd user. Below script is the Error log from the browser.

Error in parsing value for 'transition'.  Declaration dropped. new
POST 
XHR 
http://localhost:3000/api/users/new 
[HTTP/1.1 500 Internal Server Error 15ms]
Headers
Response
Cookies
Connectionkeep-aliveContent-Length113Content-Typeapplication/json; charset=utf-8DateFri, 26 Jan 2018 04:26:04 GMTETagW/"71-hh93mNDx0Qfn4PwZ+9cNtxv8fBE"VaryAccept-EncodingX-Powered-ByExpress
Acceptapplication/jsonAccept-Encodinggzip, deflateAccept-Languageen-GB,en;q=0.5Connectionkeep-aliveContent-Length68Cookielocale=en; io=HS0GYNdugP8JQPVKAAAC; connect.sid=s%3Am9qqr6mv00MUweAGQZBOQrX729W5yHJ0.vfWJGRR%2FIURn7SMOunsmNZeR1u3fapNjmSzckqut6hMHostlocalhost:3000Refererhttp://localhost:3000/en/settings/users/newUser-AgentMozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0content-languageencontent-typeapplication/jsonoriginhttp://localhost:3000

**Comment by txau** [comment]
@chrisha88 since this was a server configuration issue, I'm closing for now. 

We understand we need to provide better feedback on errors in mailing on user creation and we will improve it when we have a chance. Thanks for the feedback!

**Comment by kjantin** [comment]
Related to https://github.com/huridocs/uwazi/issues/1334
