### ISSUE TITLE
Connection visualization - not displaying

### ISSUE THREAD

**Issue by AlWalid** [huridocs/uwazi#1415]
Entities were created and linked with connections.
Connections appear in the filter to the right, but do not show in the left section.

**Comment by txau** [comment]
@AlWalid can you point to the particular URL so we can check? ty!

**Comment by AlWalid** [comment]
@txau : Done !

**Comment by AlWalid** [comment]
Any advancement regarding that?

**Comment by kjantin** [comment]
![image](https://user-images.githubusercontent.com/354426/34951217-8cd6bc96-f9e3-11e7-8d40-d51455a34fa6.png)

**Comment by konzz** [comment]
Does this happen everywhere or can you point to the url with this issue?

**Comment by kjantin** [comment]
We aren't able to share the URL publicly.

**Comment by AlWalid** [comment]
Hey team,

am facing the same issue in a second instance.
Can you please look into it ?

thanks !
Al Walid.

**Comment by txau** [comment]
@AlWalid the solution is incoming! just a few more days =)

**Comment by AlWalid** [comment]
@txau : Great , thanks for the update ^_^

**Comment by konzz** [comment]
@AlWalid @kjantin tested with the new relationships and the relationships appear normally, I'm closing this issue

**Comment by AlWalid** [comment]
Thank you @konzz !
