### ISSUE TITLE
Full text search not working in some instances

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1417]
Full text search is not working for https://adrd.uwazi.io/en/

**Comment by konzz** [comment]
I think this was fixed after a redploy

**Comment by danicatalan** [comment]
I confirm its working, thanks @konzz

**Comment by daneryl** [comment]
@konz @dani, elasticsearch Persian analyzer is not properly configured, this is causing the issue most likely.

**Comment by daneryl** [comment]
fixed by e03cd53f89e55c4e63988bab99fbd767691e275a and deployed, https://adrd.uwazi.io/en/ should not have this problem anymore.
