### ISSUE TITLE
How do the filters and search functions interact, if at all?

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#1418]
Some feedback from a user:

> I took me quite a while to get used to navigate and how to search for information. It would be useful if they could explain somewhere how the filters and search functions interact (if they do) and what possibilities there are to do them. To this day, I am not sure whether I can combine a filter with key word search and the results I get, are not consistent...More generally, it would be useful to explain somewhere how content can be accessed, the search possibilities, its limitations etc

How do the filters and search functions interact, if at all?

**Comment by danicatalan** [comment]
@kjantin search will perform a query giving back all the documents containing the keywords on the title or the document text.

Filter will perform a similar query but returning all the documents with properties matching the selecting one.

That said, search and filters should work together to give back a combined results, no matter the order. So, if I search for "freedom" and there are 100 docs in the collection, filters should update to match that amount of docs. On the other hand, if I filters docs by Argentina, when i perform the query it will search just on Argentina's documents.

We should ask more feedback to review the inconsistencies this users is perceiving.

**Comment by txau** [comment]
I think this is a matter of documentation or user getting used to the interface.
