### ISSUE TITLE
Read more button on Rich text fields

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1420]

**Comment by txau** [comment]
@danicatalan Is this meant for cards or for the side panel?

**Comment by danicatalan** [comment]
Closing this task. We will follow the approach of fixed card sizes and crop longer info in favor of expand the information always on the sidepanel.

**Comment by txau** [comment]
@danicatalan yeah, I've been thinking about it and I believe we should implement this for the sidepanel. Maybe not only for rich text fields, but for all fields bigger than certain height?

**Comment by simonfossom** [comment]
We've talked about giving users the ability to collapse properties. That is different than "_Read more_" ofc. 

I would suggest that all properties can be collapsed or at least any property that has more than 2 lines. 
And to have "_Read more_" only on rich-text properties.

**Food for thought:**
My questions would be, if users are looking for some specific info and collapse all but few properties on an entity, would Uwazi remember that for all entities of that template for this session?
I'm guessing if they would do this for one entity they are interested in the same info in all entities of the same template they are opening.
What do others think?
