### ISSUE TITLE
Better pagination links

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1421]
On the first query, the limit on the library is 30. Users can increase the limit in batches of 30 clicking on the button, but to show all the docs, they should modify the limit by hand on the URL.

We should provide an interface to let users show all the docs on a query in addition to the current one for batches.

**Comment by txau** [comment]
Gotta be careful with show all it could be thousands. We need some smart button here.

**Comment by txau** [comment]
@danicatalan @RafaPolit what about a new version of this. "Show more 30 100 1000"

**Comment by txau** [comment]
BTW this pagination is used in several sections of Uwazi. Please make sure is working correctly in all of them:
- Library
- Uploads
- Relationships

**Comment by txau** [comment]
Also make sure pagination can be indexed by search engines.
