### ISSUE TITLE
Search in multi-select is not obvious for users

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1422]
Some user have reported that clicking on the search box is not obvious.

![screen shot 2018-01-03 at 12 30 19](https://user-images.githubusercontent.com/489831/34533958-fb5ec28c-f081-11e7-91c8-ac2f80cd9b46.png)

**Comment by danicatalan** [comment]
Copy styles from default searchbox:

![image](https://user-images.githubusercontent.com/6364153/42288587-a9957e90-7fbb-11e8-9b92-b0e0d36e304e.png)
