### ISSUE TITLE
"Login failed" before trying to login

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1425]
The password field appears as "Login failed" instead of "Password":

![screenshot-moonsheep uwazi io-2018-01-12-11-40-26-187 png](https://user-images.githubusercontent.com/6364153/34872119-0c1c7b4a-f790-11e7-943b-df668b5fff0f.jpeg)

**Comment by kjantin** [comment]
This issue is happening on a private instance. Please ask me or Nancy for the URL. :)

**Comment by txau** [comment]
@kjantin that was due to a wrong translation for password. This has been fixed, if this instance is still suffering from this the way to fix it is to change the translation in settings > translations > system > password
