### ISSUE TITLE
Expand filters dropdown by default

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1426]
Current default:

![image](https://user-images.githubusercontent.com/6364153/35087724-803a840e-fc31-11e7-92b5-dd62c19a4c30.png)

Expected default:

![image](https://user-images.githubusercontent.com/6364153/35087733-8d278c48-fc31-11e7-9db2-61a918899e16.png)

**Comment by danicatalan** [comment]
Related to #1398

**Comment by txau** [comment]
Actually since we added the default filters this functionality is not that necessary.
