### ISSUE TITLE
Searchbox not working on entity titles

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1427]
Current behaviour:
Search box does nothing.

Expected behavior:
Show entities matching the keyword with the title.

Seems is a specific bug for this project, ping me on MM so I can give you access to the specific data.

![image](https://user-images.githubusercontent.com/6364153/35088701-de19da4a-fc34-11e7-9109-82fdcabf0c1d.png)

**Comment by konzz** [comment]
Fixed
