### ISSUE TITLE
Highlight titles on text search

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1428]
When users search on documents, keywords are highlighted in the text snippet.

![image](https://user-images.githubusercontent.com/6364153/35088841-5106b4b0-fc35-11e7-8dbb-cc7ca5c5cb11.png)

Users expect the same behavior searching titles (entities and documents).

![image](https://user-images.githubusercontent.com/6364153/35088830-48d2061e-fc35-11e7-916a-79a563ea372a.png)

**Comment by txau** [comment]
Now titles are being shown as part of the result snippets, so this is fixed in an alternative way:

![screenshot from 2018-09-15 09-38-45](https://user-images.githubusercontent.com/489831/45583942-33b26000-b8cb-11e8-9a7a-7afd58fffd15.png)
