### ISSUE TITLE
Search by properties on the searchbox

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1433]
Apart from full text search, the search box in library could search by properties. So for example, if a user types "Egypt" on the searchbox, all the cards with that entity as property should appear.

This could be related with searching through relationships.

**Comment by txau** [comment]
We really need to review the relevance algorithm again. It's tossing too many results, it makes it unusable for users. We either improve the UX or decrease the fuzziness.

**Comment by txau** [comment]
Related: https://github.com/huridocs/uwazi/issues/385

**Comment by chrisha88** [comment]
We are unable to search anything. Basically the search doesn't give out any results. Is there anything wrong in the configuration?

**Comment by txau** [comment]
@chrisha88 are we hosting our instance or it is self-hosted? If self-hosted please provide some debugging information, maybe a log showing an error. Also try reindexing in ElasticSearch.
