### ISSUE TITLE
IHRDA: Some features not responding

### ISSUE THREAD

**Issue by djbmartial** [huridocs/uwazi#1435]
1. The translations for the following document types do not get saved: 
- Under "ACmHPR": Case Head Notes, Rights Alleged to be Violated, Rights Not Violated, Type of Document
- Under "ACmHPR Soft Law": ACmHPR Soft Law

2. Changes on some document types not showing on translation pages:
- Under "EACJ Decisions": Rights alleged to be violated; Rights Not Violated, added but not showing on translation page

3. On the translation page for "Country/Respondent", we had deleted Attorney General for Burundi, Kenya and Rwanda – yet they are always appearing.
 
4. Under "ECOWAS Court" when creating case cards, “Rights Alleged to be Violated” and “Rights Not Violated” rather show list of countries as options to choose from.

5. On the upload page, I realize that some of the 30 cases thee present (such as “006/2012 African Commission on Human and Peoples’ Rights v the Republic of Kenya”, “272 03 Association of Victims of Post Electoral Violence & INTERIGHT Cameroon”, “321 06 Law Society of Zimbabwe et al  Zimbabwe” and “07 08 JUD Luke Muyandu Tembani v. Zimbabwe” – changes on the cards are not saving. These four examples are the first 4 on that list of 30 cases uploaded; i don't know how the other cases would respond when the cards are edited.

Thanks.

**Comment by txau** [comment]
Hi @djbmartial. Since you closed the task, can we assume this is working now?

**Comment by djbmartial** [comment]
Hi. I perceive the 5th point is no longer a problem, as the ones i have been working on are now saving.

**Comment by djbmartial** [comment]
If I closed the task, then i must have done so unknowingly. I am still new on this platform. Sorry about that.

**Comment by txau** [comment]
Ok! I'm reopening then, so it doesn't slip under the radar.

**Comment by txau** [comment]
@djbmartial I'm going to try to have a dev check this out.

**Comment by txau** [comment]
> 1. The translations for the following document types do not get saved:
> - Under "ACmHPR": Case Head Notes, Rights Alleged to be Violated, Rights Not Violated, Type of Document
> - Under "ACmHPR Soft Law": ACmHPR Soft Law

Apparently you changed the case for some title and the system is taking them as different items to be trasnlated. This is a bug in our end, we're going to review it. Meanwhile, you need to retranslate the property with the new casing. You'll find it duplicated: 
- ACmHPR soft law (old one)
- ACmHPR Soft Law (new one).

> 2. Changes on some document types not showing on translation pages:
> - Under "EACJ Decisions": Rights alleged to be violated; Rights Not Violated, added but not showing on translation page

For some reason that we are not aware of, some of the properties didn't create their translation options upon creation. I resaved the templates and the properties are now available for translation.

> 3. On the translation page for "Country/Respondent", we had deleted Attorney General for 
> Burundi, Kenya and Rwanda – yet they are always appearing.

This is bug in our end. Apparently when deleting thesauri options their translations do not get deleted.

> 4. Under "ECOWAS Court" when creating case cards, “Rights Alleged to be Violated” and “Rights Not Violated” rather show list of countries as options to choose from.

This is working properly. Can you recheck please? If is still happening please explain the steps more detailed. This may have been fixed while resaving the template.

>5.  On the upload page, I realize that some of the 30 cases thee present (such as “006/2012 African Commission on Human and Peoples’ Rights v the Republic of Kenya”, “272 03 Association of Victims of Post Electoral Violence & INTERIGHT Cameroon”, “321 06 Law Society of Zimbabwe et al Zimbabwe” and “07 08 JUD Luke Muyandu Tembani v. Zimbabwe” – changes on the cards are not saving. These four examples are the first 4 on that list of 30 cases uploaded; i don't know how the other cases would respond when the cards are edited.

It looks like you guys managed to set the metadata and publish these documents? Maybe the database was down at the moment you tried to save, for maintenance. Is this still happening?

BTW, we found this document published but lacking the metadata, please review it when you have a chance:  https://ihrda.uwazi.io/en/document/kpxzlg8279oa10m9jug7j5rk9

**Comment by djbmartial** [comment]
Thank you for the response. I have taken note of the remarks under points 1, 2 and 3. Meanwhile, points 4 and 5 are OK now. Thanks once more.

**Comment by konzz** [comment]
@djbmartial Translations should be correct right now. Translations need some rework to avoid future problems, but I think your translations should be fixed now. I'm closing the issue and if you find any more problems feel free to reopen it or create a new one.
