### ISSUE TITLE
items in thesauri 'disappearing' in humphrey instance

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#1438]
Hey guys,
we have been working in a team of 6 on humphrey instance. the tagging work involves creating items in thesauri. However, we are realising that the new items tend to 'disappear' after we have created them.
I have created user accounts for the team members, all with admin rights but this is not helping situation. what could we be doing wrong?

**Comment by konzz** [comment]
@HSips Hi, I've checked, and the options selected in the document, do not exists in the list of thesauris, at least not with the same ID that is what we use to match the values internally. Is it possible that someone deleted the option to create it again? To modify the name or the order?

**Comment by txau** [comment]
@konzz maybe add a restriction to thesauri item deletion when the value is in use?

**Comment by txau** [comment]
Related to https://github.com/huridocs/uwazi/issues/628

**Comment by HSips** [comment]
Thanks @konzz actually, they were disappearing as we worked on them. Not possible other user deleted. I think it is related to the fact that we had first all logged in as the original admin..

**Comment by txau** [comment]
@HSips were they created after you logged in? That could explain why some users could see them and others couldn't

**Comment by HSips** [comment]
@txau several of us, I think 3, were logged in in same user (admin)... but then was affecting other users as well.

**Comment by HSips** [comment]
@txau Just logged into AWA instance, yes, in the uploads there are a number of failed uploads but these are recent. Last couple of weeks. Is his the time frame you were asking or earlier?
<img width="960" alt="30may2018" src="https://user-images.githubusercontent.com/22650647/40709055-b8727492-63fd-11e8-9c33-bd432ea82ac3.png">

**Comment by HSips** [comment]
@txau yes, regarding items in dictionaries, from user experience, could be same bug. We have noticed that disappearance of dictionary items when we are doing a sprint, so having 5-6 people together adding metadata and doing connections.. Also the reason we started creating user accounts for each user as we thought several people, having logged in with one user and adding items at once is making the system hang.

**Comment by txau** [comment]
@HSips ok. I'm going to close this issue for now. Please reopen or create a new one if you detect these issues again =)

**Comment by HSips** [comment]
thanks!
