### ISSUE TITLE
admin user cannot revise new user account details

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#1439]
I have created 6 new user accounts of admin level for the team working on humphrey instance. However, i just realised original admin cannot revise the details, even check if the email used is the right one. I guess this is a long term thing but maybe we could do something here?

**Comment by konzz** [comment]
@HSips Right, admins can only modify the type of account once created. And users are the only that can modify their own email and details. What do you need propose?

**Comment by txau** [comment]
@konzz I guess what he needs is that admins can modify other user's account, including other admins.

**Comment by HSips** [comment]
Thanks @konzz @txau well, one of the users did not get the email notification to set up password, so wanted to check if had typed email address wrong.. then I realised I can't view.
So yes. like @txau says, modify other users.
I have created the other users as admins since I need them to be able to create dictionaries
