### ISSUE TITLE
Display relationships on sidepanels

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1441]
We need designs for a condensed version of the relationship tree.

**Comment by juanmnl** [comment]
Approved first iteration for introducing the relationships into the side-panel.

- Sticky group flag (left side flag on desktop), once the next main flag gets to the top it should replace the previous one. ([example of the proposed behavior on scroll](https://twitter.com/argyleink/status/1556760472245788672?s=20&t=NuHKRVq-qEZriZBC_owRyg))
- Collapsible/expandable groups (right side flags on desktop) for easier navigation of the structure of many subgroups.
- The ability to "preview" a nested entity without full side-panel navigation to avoid nested hell. The user can still click view for that entity and navigate to the full view.
- Collapse/expand all actions.

[Figma designs](https://www.figma.com/file/kpGAA005yHdL6Ch1rncaB2/SaaS-Improvements?node-id=78%3A84)
[Prototype](https://www.figma.com/proto/kpGAA005yHdL6Ch1rncaB2/SaaS-Improvements?page-id=78%3A84&node-id=199%3A2223&viewport=221%2C-741%2C0.11&scaling=min-zoom&starting-point-node-id=199%3A2223)

**Full interaction:**
![2022-08-22 11 25 19](https://user-images.githubusercontent.com/699945/185889950-7d038ec0-f1a1-41f7-a0f7-cb064eaca26b.gif)

**Simplified nested entity view (only main info):**
![simplified nested entity view](https://user-images.githubusercontent.com/699945/185889739-2e432308-4c45-4fcb-a0c2-9f39642ee495.gif)
