### ISSUE TITLE
Clean Vimeo embedded video

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1443]
Embedded videos on Uwazi are showing all the video metadata. Vimeo allows to remove all this noise adding some parameters in the URL to feed the iframe.

**... ?title=0&byline=0&portrait=0 ...**

`<iframe src="https://player.vimeo.com/video/67430069?title=0&byline=0&portrait=0" width="640" height="480" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>`

Can we add those parameters to our custom markdown?

**Comment by txau** [comment]
Duplicated: https://github.com/huridocs/uwazi/issues/1446
