### ISSUE TITLE
User on IHRDA uwazi not receiving notification

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#1444]
Guys,
one of the user accounts created last Saturday has not received notification. mainatito1@gmail.com
This is linked with #1439
<img width="960" alt="user acc not recognised" src="https://user-images.githubusercontent.com/22650647/35716311-3cdc2320-07e9-11e8-96a4-cd384a498ed9.png">

**Comment by txau** [comment]
Maybe its in the spam folder?

**Comment by HSips** [comment]
Stupid me.. sorry.. we found it.. thanks!
