### ISSUE TITLE
Scanned pdfs not highlighting in IHRDA CLA

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#1445]
we are working on IHRDA CLA. the following 2 documents seemed to have been scanned are not highlighting, so we cannot make connections:
1. 001/2012 Center for Human Rights (University of Pretoria) and Rencontre africaine pour la defense des droits de l'Homme v Senegal - https://ihrda.uwazi.io/en/document/q9oefdqfrcotrxn44iqp30udi
2. 003/2015 Minority Rights Group International & SOS-Esclaves (on behalf Said Ould Salem & Yarg Ould Salem) v Mauritania - https://ihrda.uwazi.io/en/document/6m1tl55qoczbvkb6mtfvx9lik9

Kindly advice

**Comment by txau** [comment]
@HSips if scanned documents haven't been OCRed they are just images with no text layer. You can use https://convertio.co/ocr/ for a quick and free OCR. Also Adobe Acrobat supports OCRing existing PDFs.

We keep in our roadmap the possibility of adding built-in OCR support, probably based on https://github.com/tesseract-ocr/ but so far this is low in the backlog priority.

**Comment by HSips** [comment]
Thanks. OK. Will do...
