### ISSUE TITLE
Changing template of a document resets the properties

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1456]
This is more a reflection than a real issue, because two different approaches coexist in Uwazi right now:

- If I select a document and change the document template, it resets all the properties that document has, so I need to fill them again.
- If I select multiple documents and change the document template for all of them, it keeps the metadata in case the property is also used in the new template. Quite useful when changing document types.

Do you think the second one should be our default approach also when changing a single doc template?

**Comment by txau** [comment]
@danicatalan ideally yes, it clearly improves the usability. We don't really know how often this is happening though.
