### ISSUE TITLE
Graphs for CEJIL

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1462]
Lets give some love to the page https://sidh.cejil.org/es/page/59hhexlzlpthf8gi8gerd4pldi . Add graphs for:
- [x] Total judges in the court by country. Segregated by sex.
- [x] Total judges in the commission by country. Segregated by sex.
- [ ] Judges in the court over time (split in years). Segregated by sex.
- [ ] Judges in the commission over time (split in years). Segregated by sex.

**Comment by RafaPolit** [comment]
While this sounds really nice on paper, this is the result:
![screenshot from 2018-03-23 17-36-48](https://user-images.githubusercontent.com/4309019/37856190-1a6a92c8-2ec1-11e8-8c48-5612d8565369.png)
There is one judge per country and one of them is female, but since there isn't any more, the sex separation and the count by country seems not all that useful.

Judges in the commision will look the same.

Split by years, there may appear some variation as to how many males and females have taken office, but it may not be all that useful either. 

Any thoughts?

**Comment by RafaPolit** [comment]
A new configurable CustomHook has been configured to allow for members of the court or members of the commission (by country) to be added.  The syntax is:
```
{customhook}(component:CejilChart002,filterProperty:'mandatos_de_la_corte',label:'Members of the Court')
```


```
{customhook}(component:CejilChart002,filterProperty:'mandatos_de_la_comisi_n',label:'Members of the Commission')
```
The 'label' is optional.

The end result is:
![screenshot from 2018-03-27 17-56-09](https://user-images.githubusercontent.com/4309019/37999815-31e664c8-31ea-11e8-9c95-1329a99e0521.png)

**Comment by danicatalan** [comment]
Cool work on the custom hooks @RafaPolit! I will spend some time to upgrade the visuals to better reflect what we want to tell, but anyway this is a good first approach to update the Judges page.

Please merge this but don't close the issue, you can assign it to myself and tag it as UI once this is merged in development, so we can add this charts on CEJIL as a first step.

**Comment by txau** [comment]
@RafaPolit @danicatalan  I guess there are two graphs missing before merging.

**Comment by RafaPolit** [comment]
We discussed this on the sprint planning and we decided that the 'by year' would be bars of the same heights.  Which other two graphs are missing?

**Comment by RafaPolit** [comment]
If you are referring to the cumulative judges to showcase how there are more female judges, there are a total of 4 female judges in the entire database.  There is no such 'growth'.  The graph would be a list of years all with the same number of judges each year, and just 4 female judges encompassing all the years.

I don't think that graph is going to be of any interest.  Maybe I'm wrong.

**Comment by txau** [comment]
Good enough!
