### ISSUE TITLE
Connections to ACHPR - 'overhighlighting' in yellow?

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#1463]
The African Charter on Human and Peoples' Rights is the primary treaty for the IHRDA CLA. So it will have highest no of connections. When connecting to it, its most connected arties show overhighlight of yellow, so much that one cannot read:
<img width="960" alt="achpr connections overload1" src="https://user-images.githubusercontent.com/22650647/36061283-5a9b4950-0e69-11e8-90a0-06a0cecbdbf0.png">

Then when you click on a paragraph, it then shows..
<img width="960" alt="achpr connections overload2" src="https://user-images.githubusercontent.com/22650647/36061290-7462635a-0e69-11e8-8a81-b9b9bbdcbade.png">

Does this happen with the American Convention in the CEJIL CLA?

**Comment by txau** [comment]
@HSips thanks for pointing this out. This feature needs a redesign. We will be working on it soon.

PS. In CEJIL they are not using text references so far, so they are not facing this kind of usability issues.

**Comment by HSips** [comment]
Cool
