### ISSUE TITLE
Cannot amend connection type once used

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#1464]
Trying to amend a connection type in IHRDA CLA from 'treaty body' to 'treaties and softlaw only' but system does not let me. This connection type is already being used in various documents
Any advice?

**Comment by txau** [comment]
@HSips looks like it is a bug.

**Comment by konzz** [comment]
@HSips We tested this with the new relationships and is working fine, we will deploy it this week, so will keep this issue open until then.

**Comment by RafaPolit** [comment]
@HSips We have tested this on your production build and it appears that all is well.

I'm closing this issue.  If there are further problems, please report back or open a new issue.

Thanks.

**Comment by HSips** [comment]
Many thanks @RafaPolit We will check in the course of next week and give feedback in there are problems. Again, thanks!
