### ISSUE TITLE
Revamp translations system

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#1465]
- [x] Implement partial updates on client side
- [ ] Move responsibility of detecting translation changes from templates to translations.

**Comment by bertver** [comment]
there is still an issue with saving translated terms: I translate a term and save it. When I reopen it, translated term is not displayed. Example: Estado under Translations.

**Comment by bertver** [comment]
![uwazi-translations-3](https://user-images.githubusercontent.com/11311296/42285507-20e46332-7fb0-11e8-87ac-30759bc6a70c.png)
![uwazi-translations-2](https://user-images.githubusercontent.com/11311296/42285522-26876852-7fb0-11e8-8626-7cbc48d9acd7.png)
![uwazi-translations-1](https://user-images.githubusercontent.com/11311296/42285530-2ac0b414-7fb0-11e8-88d7-dc0acd2f72f2.png)

**Comment by txau** [comment]
@bertver this is a bug totally unrelated to this. I opened a issue: https://github.com/huridocs/uwazi/issues/1747

**Comment by txau** [comment]
@bertver BTW that particular connection, I think it means Status rather than state. Try the new translations option, you can see the icon at the top bar beside the languages.

**Comment by RafaPolit** [comment]
Moved remaining actions to #1902.

Closing.
