### ISSUE TITLE
Strange message when trying to delete document type

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#1467]
When I try to DELETE the "ECOWAS Softlaw" document type from https://ihrda.uwazi.io/en/settings/documents...

![image](https://user-images.githubusercontent.com/354426/36115254-83612f60-1000-11e8-8e45-00b2ddf2111c.png)

It gives me a confusing message:

![image](https://user-images.githubusercontent.com/354426/36115187-557f3556-1000-11e8-97a7-fe5c5f2d4ce0.png)

**Comment by konzz** [comment]
@kjantin It's a translation problem, the default value is misleading and we changed it, you can update the translation in Translations -> System:
- Confirm delete document type message
- Confirm delete document type title
