### ISSUE TITLE
Exclude keywords from search

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1475]
"I am inventing this example: you have a collection of documents on torture and you are looking for all reports on Pakistan issued by the OMCT from 2009-2013, and you want to exclude the keyword "death penalty". "

**Comment by konzz** [comment]
This will be fixed once #1795 is merged and deployed. Users can now user "Query string" search in the library. The documentation for "Query string" search can be found [here](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/query-dsl-query-string-query.html)
