### ISSUE TITLE
Feedback button

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#148]
I have been looking the new Google Fonts website (https://fonts.google.com/) and they added a little button that I think we can take in our footer - in addition to several functionalities we can check for our project in the future.

Take a look at the feedback modal, it's quite good for us.

![feedback button](https://cloud.githubusercontent.com/assets/6364153/16077207/beaaae44-32f7-11e6-84bb-1ba0f024e78c.jpg)

**Comment by txau** [comment]
Yes this is a great idea. Its in our roadmap by the way.
