### ISSUE TITLE
todos ML

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazi#1489]
- [x] filter by probability (de 90 - 100 etc..)
- [x] do not repeat documents on the predict batches.
- [x] document name on the suggestions
- [x] document counter to show how many have been predicted
- [x] button to remove ALL current suggestions
- [x] ML api will only return the top 100 predictions by probability
- [x] predict 20 documents instead of 10 for batch predictions

**Comment by txau** [comment]
LGTM
