### ISSUE TITLE
Filter count 0

### ISSUE THREAD

**Issue by chrisha88** [huridocs/uwazi#1492]
Hi, we are experiencing an issue that the filter count in the library is always 0. Please see attached screen shot.
When we click the filter it is working but as you can see there are 5 documents but the panel is reading as 0.
![screenshot from 2018-03-02 11-16-37](https://user-images.githubusercontent.com/33055856/36885266-fc0a2296-1e0b-11e8-9a16-e6e4fee83b5a.png)

**Comment by RafaPolit** [comment]
Good day.

This is probably related to the fact that your elastic indexing is not going through as reported in your other thread #1497.  Once that is sorted out, this will hopefully work out as expected.  Lets take care of the other two issues first and then return to this one if it is not resolved by the others.

Best regards,
Rafa.

**Comment by txau** [comment]
Hello @chrisha88. I hope you managed to make your instance work. I'm closing this issue for the time being. Please reopen or create a new one if you need further support.
