### ISSUE TITLE
Search function does not work

### ISSUE THREAD

**Issue by chrisha88** [huridocs/uwazi#1497]
Got the below error in the panel when trying to re-index elastic search using

node database/reindex_elastic.js

Error: Cannot find module '../../../../app/api/config/elasticIndexes' at Function.Module._resolveFilename (module.js:469:15) at Function.Module._load (module.js:417:25) at Module.require (module.js:497:17) at require (internal/module.js:20:19) at Object.<anonymous> (/home/dell/uwazi/app/api/search/search.js:1:1) at Module._compile (module.js:570:32) at loader (/home/dell/uwazi/node_modules/babel-register/lib/node.js:144:5) at Object.require.extensions.(anonymous function) [as .js] (/home/dell/uwazi/node_modules/babel-register/lib/node.js:154:7) at Module.load (module.js:487:32) at tryModuleLoad (module.js:446:12) at Function.Module._load (module.js:438:3) at Module.require (module.js:497:17) at require (internal/module.js:20:19) at Object.<anonymous> (/home/dell/uwazi/database/reset_elastic_index.js:3:1) at Module._compile (module.js:570:32) at loader (/home/dell/uwazi/node_modules/babel-register/lib/node.js:144:5)

**Comment by RafaPolit** [comment]
This is really weird, as the reindex_elastic file does an include of the same file, which is not failing.

Can you please make sure that your dependencies are up to date with:
```
$ yarn install
```
, and see if there were packages missing, or that may have been updated or even added if you have recently pulled some of the changes we have developed?

If that doesn't work, there may exist some corruption in the node_modules packages.  Please do a:
```
$ sudo rm -R node_modules
$ yarn install
```
This will take a little longer, but it may fix some problems.

Make sure you have the latest yarn version, as some previous yarn versions presented conflicts with different versions of the same packages required by different modules in the dependencies.

Please, let us know the results of this procedures.
Best regards,
Rafa.

**Comment by txau** [comment]
Hello @chrisha88. I hope you managed to make your instance work. I'm closing this issue for the time being. Please reopen or create a new one if you need further support.
