### ISSUE TITLE
Relationships edition UI

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#1505]
- [x] Remove checkboxes when adding new relationships
- [x] Add visual feedback when hover of the relationship or when clicking them.
- [x] Show success alert on click. "You added a relationship to the hub".

**Comment by danicatalan** [comment]
![sidepanel-action](https://user-images.githubusercontent.com/6364153/37468975-87cab72a-2864-11e8-8f82-47ce1bcf50cf.gif)

**Comment by RafaPolit** [comment]
@danicatalan This commit also changed the regular text-based references inside document.  Now, there is no visual feedback that you have selected a document when creating text based references.

It was not enough to just 'remove' the feedback, it needed to be done on a by-case scenario.

**Comment by RafaPolit** [comment]
Fixed in https://github.com/huridocs/uwazi/commit/606144fad80deac85b6a2db5188ff72073b01fde
