### ISSUE TITLE
Error while upgrading to UwaziDocs V1

### ISSUE THREAD

**Issue by KKNomad** [huridocs/uwazi#1507]
Hi,

I had installed the earlier release of UwaziDocs and now I am trying to upgrade it to the current release. Following the instructions on how to run an upgrade, I get the below error on running the second command (_./app/api/migrations/assign_file_languages.js_):

### **

> root@user:/home/user/uwazi# ./app/api/migrations/assign_file_languages.js
> ./app/api/migrations/assign_file_languages.js: line 1: import: command not found
> ./app/api/migrations/assign_file_languages.js: line 2: import: command not found
> ./app/api/migrations/assign_file_languages.js: line 3: import: command not found
> ./app/api/migrations/assign_file_languages.js: line 5: import: command not found
> ./app/api/migrations/assign_file_languages.js: line 7: syntax error near unexpected token `{type:'
> ./app/api/migrations/assign_file_languages.js: line 7: `entities.get({type: 'document'}, {_id: 1})'

**

Any assistance will be much appreciated.

Thanks.

**Comment by daneryl** [comment]
@KKNomad  try to run the migrations like this from the root

`node run_migration.js ./app/api/migrations/migration_file.js`

**Comment by RafaPolit** [comment]
There is a mistake on the Docs.  The correct instructions should read:

```
$ node run_migration.js ./app/api/migrations/assign_file_languages.js
$ node ./run_migration.js ./app/api/migrations/fix_entity_based_references.js
```

Sorry for the inconvenience.

**Comment by KKNomad** [comment]
Thanks @daneryl and @RafaPolit 
Managed to run the upgrade successfully.
