### ISSUE TITLE
Default filters appearing in uploads section

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1509]
![screen shot 2018-03-14 at 18 09 48](https://user-images.githubusercontent.com/489831/37419791-8ba8e0a6-27b5-11e8-94dd-9599d5f1f83f.png)

**Comment by danicatalan** [comment]
Bug or feature?

I think it is okay to have them, specially for instances with lot of private documents. What is missing here is a blank state.

**Comment by txau** [comment]
@danicatalan ok, lets discuss this further. Maybe a good blank state could do.

**Comment by txau** [comment]
Already fixed since now we have the "No value" option. Pretty handy actually =)
