### ISSUE TITLE
Add CEJIL's videos to timelines

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1510]

**Comment by RafaPolit** [comment]
Any additional info? Are they to be rendered as circled-entries as well? Do you want them to somehow play from within the timeline?

We are going to need to tag the videos with consistent dates for them to show in the timeline, and this cannot be extracted from the video, yet we are using videos from a rich text markup, so we need to discuss a bit how to implement this correctly.

**Comment by txau** [comment]
@RafaPolit do not work on this for now please. We will discuss. I just created the task as a reminder!

**Comment by RafaPolit** [comment]
No, I'm certainly not going to work on anything not in sprint. Just going over the backlog and seeing what needs further details to be workable when time comes.

**Comment by txau** [comment]
Since this is a project specific request, I'm going to remove it from the backlog.
