### ISSUE TITLE
Hide panels when they have no content and users are not logged in

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1512]
![screen shot 2018-03-14 at 18 59 00](https://user-images.githubusercontent.com/489831/37421554-d7c3b50c-27b9-11e8-9651-d74928b35e74.png)

**Comment by danicatalan** [comment]
Removed UI because this can't be managed just with styles.

We can check if the user is logged OR if the array has items to render the component.

**Comment by txau** [comment]
@simonfossom do you think this is a desired behavior?

**Comment by simonfossom** [comment]
If I understand correctly, you are asking me if we should hide tabs of sidepanel for entities where there is no info in them, right?

No, I wouldn't hide them. Even if we don't have info for that entity, others might have. Those are part of navigation and teach users how we structure information and what to expect even when some entities might not have some.

That being said, we might want to give admins options to turn off some of these if they do not want to use them on their instance. For example connections, references, or ToC.

Let me know if this answers it.

**Comment by txau** [comment]
I'm actually going to close this issue and address it as separate issues.
