### ISSUE TITLE
Overhaul of unpulished entities in metadata sanitizing

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#1530]
One missing aspect of the new implementation of being able to connect unpublished entities is that relationships that have been assigned to the metadata are returning to client. The value itself is not shown, because the thesauris don't have a match for that value. However, the value is returning to client nonetheless, and if you inspect the result of the server request you can have access to unpublished entity's shared ids.

- [ ] Sanitize server response in metadata when an unpublished entity has been stored in a relationship field and is requested by a non-logged user.
- [ ] Ensure this procedure as well for elastic searches

**Comment by txau** [comment]
@RafaPolit right now is only sharing the sharedId when the entity is not published. I think its secure enough.
