### ISSUE TITLE
Relationship field is not filtering by document type when searching the target document

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1551]
**How to reproduce**

I created a Relationship field to connect Resolutions with Countries. I used the select list to show just countries on this field.

![image](https://user-images.githubusercontent.com/6364153/38022205-333ed4be-327f-11e8-8303-76f7cc0cd790.png)

This select limit is working properly if I add the relationship through the metadata panel:

![image](https://user-images.githubusercontent.com/6364153/38022406-af2b93f0-327f-11e8-8ab5-47ed4e7a2e3d.png)

As a user, I expect the same behavior adding the relationship through the relationship view, but instead I get other types than Country on the query result:

![image](https://user-images.githubusercontent.com/6364153/38022308-6c09662e-327f-11e8-8c27-66004e2778bc.png)

**Comment by RafaPolit** [comment]
Dani, I think there is a confusion here.

A property in a document or entity type is a 'mapping' into which the previous or new relationships are 'filtered' through.

So, we always want an entity or document to have all the options available to them.  The fact that you have mapped a relationship type to a particular document type, does not mean that you cannot make a relationship of that type to a different type of document.

What a property in the template means is that you will only MAP the relationships of that particular type to a particular type of document into the document metadata.

So what you are describing is not only NOT a bug, but it is a desired feature we want to keep and was one of the reasons for the hubs change.
