### ISSUE TITLE
Changing a doc/entity type name doesn't change name on filters

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1552]
How to reproduce:

- Add some document and entitites to the filters panel.
- Change the name of one document or entity type.
- Come back to filters, name doesn't change.

Additional info:
- If we delete the filter and refresh the page, the filter appears with the new name.

![image](https://user-images.githubusercontent.com/6364153/38026383-2e6e763a-328c-11e8-8a2c-5d11e88dd270.png)

**Comment by txau** [comment]
@danicatalan is this somewhat related to translations? Have you tried changing the name in tanslations?
