### ISSUE TITLE
i18n JS error when trying to add a relationship field

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1567]
1. Go to settings > entities > countries
2. Add a relatoonship field
3. Select list "Causa"
4. Relationship "País"

This triggers the following error:

![capture](https://user-images.githubusercontent.com/489831/38282910-02f24f3e-3770-11e8-8047-56e8ffc79aed.PNG)

**Comment by txau** [comment]
Actually just accessing the settings tosses that JS error. It behaves extrange (the field I was adding disappeared). Moreover, the field is not being shown in the entity view.

**Comment by konzz** [comment]
@txau That error is thrown by us when we forget a translation but shouldn't affect anything.   I tried to reproduce but even though I have the same error the field is created properly.

**Comment by txau** [comment]
The case list is not being shown because they have no relationship defined. This is working as intended, eventually will reopen as a feature request.
