### ISSUE TITLE
Search engine not responding 

### ISSUE THREAD

**Issue by djbmartial** [huridocs/uwazi#1568]
I realize that the search engine for uploaded case does not function. I have filtered down to search cases just within the ECOWAS Court, but the engine does not respond.
[Search engine not responding.docx](https://github.com/huridocs/uwazi/files/1876779/Search.engine.not.responding.docx)

**Comment by konzz** [comment]
@djbmartial can you explain a bit more what is the problem and how to replicate it?

**Comment by djbmartial** [comment]
Normally, one can use the search engine to easily locate a document that has already been uploaded on the platform. I am using the search engine to identify the documents have been uploaded under the ECOWAS Court; but I realize that the search engine provides no result even for documents that have already been uploaded. Apparently, that function does not respond.

**Comment by konzz** [comment]
@djbmartial is your instance public? Can you provide a link to the search you are doing and to the documents that should appear?

**Comment by daneryl** [comment]
@djbmartial this is a problem with Arabic text indexation, we are working on it, sorry about the late response.

**Comment by daneryl** [comment]
@djbmartial this is fixed and deployed.

**Comment by djbmartial** [comment]
Thanks a lot. Yes, I see it works now!
