### ISSUE TITLE
PDF.js Overhaul

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#1576]
We need to move part of the logic of PDF.js away from Client.

First approach idea:
- Serve HTML instead of PDF to Client (this could potentially rid the client of PDF.js, search with SEO, etc.) 
- Store the HTML served to prevent issues with upgrading PDF.js versions
- Figure the best way to create the HTML: client, server, service?

There are some issues already talking about this approaches or the problems we are facing with the current implementation:
#671, #722, #814, #1393

**Comment by txau** [comment]
This may be related as well: https://github.com/huridocs/uwazi/issues/1223

**Comment by RafaPolit** [comment]
Also:
- [ ] Create First page Thumbnail

**Comment by danicatalan** [comment]
Thumbnail related to #817

**Comment by danicatalan** [comment]
Thumbnails were designed for AOT, take UI as reference: http://aot.netlify.com/learning

**Comment by txau** [comment]
@RafaPolit I guess this issue is obsolete now due to other strategies already implemented. Shall we close it?

**Comment by RafaPolit** [comment]
This is still useful for PDF server side rendering and, perhaps, even SEO optimization.

It's a long implementation, but it's worth discussing if it still has merit to leave as tech debt.

**Comment by txau** [comment]
We have already upgraded PDFjs and all the issues linked here are fixed.
