### ISSUE TITLE
minimum system requirement of Uwazi install

### ISSUE THREAD

**Issue by hakkiunlu** [huridocs/uwazi#1578]
Hi, I want to install uwazi as a ubuntu server. But I am constantly having trouble setting up the elastic search from the beginning. What is the minimum system requirement of Uwazin? Where can I find the open codes of the setup if possible?

**Comment by konzz** [comment]
Hi @hakkiunlu we can't provide support for installing Elasticsearch. You can follow these instructions to install Elasticsearch 5.5 https://www.elastic.co/guide/en/elasticsearch/reference/5.5/install-elasticsearch.html

All the setup process is described in the [installation guide](https://github.com/huridocs/uwazi#intallation-guide).

**Comment by fititnt** [comment]
@hakkiunlu if you have docker-compose installed on your Ubuntu, you can run Elastic Search 5.5 Mongo 3.4 with these commands, and run the Uwazi directly on your Ubuntu.

```bash
git clone git@github.com:fititnt/uwazi-docker.git
cd uwazi-docker 
docker-compose up elasticsearch mongo
```
At this moment https://github.com/fititnt/uwazi-docker just do not have the full and tested install with docker compose, just Elastic Search and Mongo. You can ask there about how to install the non-uwazi part, and some beta-testing is welcome.

At [chatops-wg](https://github.com/fititnt/chatops-wg) we have open the setup configuration of a Ubuntu server with docker at lobook files on another repository, see https://github.com/fititnt/chatops-wg-infra

**Comment by txau** [comment]
@hakkiunlu I hope you managed to successfully install. I'm closing this issue for the time being. Please reopen or create a new one if you need further instructions.
