### ISSUE TITLE
MongoError 

### ISSUE THREAD

**Issue by mtuchi** [huridocs/uwazi#1579]
Hello Am having this error when i try to edit a document when i save am getting an error below 
`{"error":{"name":"MongoError","message":"The 'cursor' option is required, except for aggregate with the explain argument","ok":0,"errmsg":"The 'cursor' option is required, except for aggregate with the explain argument","code":9,"codeName":"FailedToParse"`
My setup
`Mongodb version 3.6.3`

**Comment by konzz** [comment]
Hi Uwazi uses MongoDB 3.4.x https://docs.mongodb.com/v3.4/installation/ (there are known issues with 3.6, please ensure 3.4)

I'm closing the issue, reopen if the problem persssist
