### ISSUE TITLE
calendar

### ISSUE THREAD

**Issue by bertver** [huridocs/uwazi#1588]
suggest two improvements to calendar:
a. allow for scroll down by decennia instead of by years only
b. use the most common dd-mm-yyyy format

**Comment by bertver** [comment]
thanks Dani! That resolves one issue. What about the decennia?

**Comment by txau** [comment]
@bertver I think when you need to do big "jumps" on dates, its better to manually input the date. Does that fix the other issue?

**Comment by txau** [comment]
@bertver closing for now. Let me know if the solution is acceptable.
