### ISSUE TITLE
Map issues when rendered on homepage

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1615]
![screenshot from 2018-05-02 07-48-23 png](https://user-images.githubusercontent.com/6364153/39528055-5cf7fbfe-4e23-11e8-8a94-8a1b6ef1a628.jpg)

**Comment by konzz** [comment]
@danicatalan @txau Can we have a description of what is the issue?

**Comment by txau** [comment]
@konzz as you can see in the screenshot, the columns wit the filters are bigger than the space allocated for the map. Also, the map is not adjusted to the space, you can see a top margin.

**Comment by txau** [comment]
@danicatalan its still happening after updating the map feature, so I guess its a matter of updating the home page CSSs

**Comment by danicatalan** [comment]
Will be fixed automatically after next deploy. The map component needs to be updated with latest changes so it receives height prop correctly.

**Comment by danicatalan** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/6364153/41223953-7f3845b8-6d6b-11e8-8b40-270d5a7a3607.png)
