### ISSUE TITLE
Cannot save more than 33 property elements in the Thesauri

### ISSUE THREAD

**Issue by CESRadmin** [huridocs/uwazi#1619]
Cannot save more than 33 property elements in the Thesauri. This is for our country property in particular. The Thesauri allows us to add multiple new elements to the property, but after pressing the save button, these new property elements do not get saved. When navigating to the document edit field, the new property elements do not appear, and when navigating back the Thesauri, the new property elements that were added have disappeared.

Here is a link to the site. It is still in a development stage. 
https://cesr.uwazi.io/

<img width="1280" alt="screen shot 2 2018-04-27 at 10 30 18 am" src="https://user-images.githubusercontent.com/38893920/39643617-5958a2f6-4fa3-11e8-9077-0c37e7765a1e.png">
<img width="1280" alt="screen shot 1 2018-04-27 at 10 29 34 am" src="https://user-images.githubusercontent.com/38893920/39643618-596a60ae-4fa3-11e8-9bcd-cdef23ef9cad.png">

**Comment by txau** [comment]
@CESRadmin thanks for reporting the issue. I've been able to replicate the problem and actually its not the number of items but the total length of items saved at the same time. So with short item names, you could save more than with longer item items.

In the tests I ran, I was able to save 40 elements at once with short item names, but only 26 when saving items with long names.

As a short-term workaround, save your items in small batches of 10-15.

**Comment by txau** [comment]
I can't reproduce the bug after the latest thesauri changes, so probably its solved.
