### ISSUE TITLE
Sorting by string in results do not order numbers in a user expected way

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#1622]
the listing of documents on the Atrocities Watch instance, which are numbered, do not count down, say from 1-100 but by decades, so 2;20-29 then 3;30-39 and so on..

https://atrocitieswatch.uwazi.io/en/?q=(limit:90,order:asc,sort:title,types:!(%27593514243859ad199bb8275f%27),userSelectedSorting:!t)

**Comment by txau** [comment]
@HSips I also think this behavior its more desirable for users, although its not how standard alphabetical ordering work in computers. We are giving this low priority but we will try to fix it when possible.

**Comment by txau** [comment]
@HSips a short-term workaround could be prefixing the numbers with 0s. Ie.

- "Burundi Watch Update 1" becomes "Burundi Watch Update 001"
- "Burundi Watch Update 10" becomes "Burundi Watch Update 010"
- "Burundi Watch Update 100" remains "Burundi Watch Update 100"
- "Burundi Watch Update 33" becomes "Burundi Watch Update 033"

And so forth.

**Comment by txau** [comment]
Related: https://github.com/huridocs/uwazi/issues/2050
