### ISSUE TITLE
Library wrongly display in two columns on 13" fullscreen browser

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#163]
Probably an unwanted margin.
![screen shot 2016-06-22 at 00 04 11](https://cloud.githubusercontent.com/assets/489831/16248060/34a38700-380d-11e6-9a9f-0d9958fa45a4.png)

**Comment by danicatalan** [comment]
@txau I studied better the fixed size on cards and I've made a change: now the card is **flexible** but the content inside it is **fixed**. I've made tests in every viewports and performs great (and it will render ok when we decide to expand the sidebar always on desktop).
