### ISSUE TITLE
Recovery of log in details for user accounts

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#1646]
I think this has come up before but can't locate the issue. Please let me post a new. One of my student says.. "I am experiencing problems logging into my account. My old password won’t work and I am unable to change the password (I’ve tried to change the password and use the new one but it won’t pick and so I still can’t log in)".
This is IHRDA instance. As admin, there is not much can do from my side. The accounts is 'Sandra'

**Comment by txau** [comment]
@HSips this and other account related issues (ie, recovery email not working) have been addressed: https://github.com/huridocs/uwazi/issues/1624

It will be available upon next deploy (likely this week).
