### ISSUE TITLE
data in fields are taken over when changing document type

### ISSUE THREAD

**Issue by bertver** [huridocs/uwazi#1661]
Different document types can have the same fields. Now when changing the document type for a document all information recorded is lost. Would it be possible to allow users to select to take over existing values if they want to modify the document type?

**Comment by txau** [comment]
Yes, this has already been reported: https://github.com/huridocs/uwazi/issues/1456

**Comment by txau** [comment]
Dupp https://github.com/huridocs/uwazi/issues/1456. Closing.
