### ISSUE TITLE
buttons on upper right corner are not visible

### ISSUE THREAD

**Issue by bertver** [huridocs/uwazi#1662]
Since today I cannot see the standard buttons (languages, account etc. in both Chrome and Firefox.
![screen shot 2018-06-06 at 17 22 01](https://user-images.githubusercontent.com/11311296/41048212-8adfbc9a-69ae-11e8-9c82-3e2012278f79.png)

**Comment by bertver** [comment]
screenshots are from https://gcvhrv.uwazi.io/, is same with https://hr-reports.uwazi.io/

**Comment by txau** [comment]
Hi @bertver, I can see them. Can you force reloading your browser? If I'm right about this, those icons are based in font-awesome which we load from a CDN. It could be that the connection to the CDN failed. @danicatalan correct me if I'm wrong.

**Comment by txau** [comment]
@danicatalan I can confirm. Font awesome is not working for firefox, but its working for Chrome. Also, I'm not sure if we want to load it from the CDN, I guess we rather load it from local.

**Comment by danicatalan** [comment]
@txau yeah, adding FA as a local module will give us some advantages:

- No dependency on CDN changes or server status (they use to be stable, but sometimes fails happen).
- Reduced loading weight (we can manage locally which fonts we want instead of the whole package).
