### ISSUE TITLE
Make use of a search syntax to search only "exact phrases" in documents

### ISSUE THREAD

**Issue by CESRadmin** [huridocs/uwazi#1682]
It would be very useful to have the option to search for only an exact phrase, rather than for the search to result in all of the potentially relevant phrases. Perhaps a search syntax can be added to enable this?

**Comment by txau** [comment]
@CESRadmin thanks for your input. This has been in our roadmap for a while now. It should be pretty straight forward as that kind of query is natively supported by ElasticSearch: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html.

Likely we are sanitizing some of the needed special chars, but I can't confirm without looking into the code.

Let's see if we can move it to sprint soon.

**Comment by txau** [comment]
Related: https://github.com/huridocs/uwazi/issues/1475

**Comment by konzz** [comment]
This will be fixed once #1795 is merged and deployed. Users can now user "Query string" search in the library. The documentation for "Query string" search can be found [here](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/query-dsl-query-string-query.html)
