### ISSUE TITLE
Add nesting to relationship fields

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1687]
Responding to user needs such as having a relationship field with countries and wanting to group them in continents.

This could be easily achieved by using a property of the used entity for nesting criteria. Ie. in the cae of countries they could have a property "Region".

**Comment by fnocetti** [comment]
To be implemented in relationships v2. Supported by this https://github.com/huridocs/uwazi/issues/5346

**Comment by txau** [comment]
@fnocetti this is not currently supported in Uwazi. Is this going to be implemented for sure?
