### ISSUE TITLE
Highlighted text that spills over in connections

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#1691]
When selecting text to highlight in connections, if text spills into next page, it highlights entire next page. I think it may be linked to issue #1645.
<img width="1280" alt="connection highlighting" src="https://user-images.githubusercontent.com/22650647/41408410-4219fac4-6fdb-11e8-8333-5d2174dfe3a9.png">

**Comment by daneryl** [comment]
this does not happen anymore.
