### ISSUE TITLE
Generic Components: queryCounter

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#1698]
This is a large number result of a particular query.  The name is still very fuzzy @txau ?

Basic functionality:
- Pass a query
- Prints a large number with the TOTAL results of a query
- Has a label for it
- Is a link to that search within the library

**Comment by txau** [comment]
A suggestion for the name: Total.

Make sure that the label is translatable.

**Comment by daneryl** [comment]
@txau name is Counter, i think Total is better, anyways we did the smalles possible solution, does not include anything, just prints the total, so we can compose and create any layout we want, the PR is ready, should we change the name to total ?
