### ISSUE TITLE
Allow uploading 'instance images' (not attached to a specific entity)

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#1708]
We need to allow the uploading of generic 'instance' photos that can be used in Heroe's or Pages.

**Comment by txau** [comment]
Related: https://github.com/huridocs/uwazi/issues/881

**Comment by danicatalan** [comment]
@txau maybe related to https://github.com/huridocs/uwazi/pull/1688?

**Comment by txau** [comment]
@danicatalan yes =) But that is an spike I am working on, not really to take it into consideration until we can really tackle it.
