### ISSUE TITLE
JS error while trying to edit an entity

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1713]
https://atlas-of-torture.uwazi.io/en/library/?q=(filters:(),order:asc,sort:title,types:!(%275b27fddf840f425ff3ca5a32%27))

![screenshot from 2018-06-20 19-55-54](https://user-images.githubusercontent.com/489831/41693759-ffcd908e-74c3-11e8-87ad-7fabc361d8d6.png)

**Comment by habbes** [comment]
Error seems not to occur when running local instance using `yarn hot`, only on the online instances.

**Comment by habbes** [comment]
I've updated my branch and now I can reproduce the error locally. I think an update to Uwazi introduced an incompatibility.

**Comment by habbes** [comment]
I think there was a change in how the thesauri stored or rendered that causes the error. That error is thrown from the function that's sorting thesauri items, presumably before they're displayed.

**Comment by RafaPolit** [comment]
For some reason, the Select now receives as options label a React Element instead of a string.

I'm going to do a quick and dirty fix, but I have written to @konzz so we can figure the best place to handle this.

**Comment by txau** [comment]
@konzz related to this, there is also a malfunction in the tooltips for the multiselects items showing [Object object] instead of the actual title.
