### ISSUE TITLE
Design and complete the settings/customizeUploads routes

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#1723]
The custom image uploads need to be public, designed and useful as full functionality.

**Comment by danicatalan** [comment]
- [ ] Add both sections inside Settings > Collections.

**Comment by danicatalan** [comment]
Now there's a couple of buttons on collection to access the routes:

![image](https://user-images.githubusercontent.com/6364153/42327562-50e1bc1c-806c-11e8-9afa-45c69e5d9535.png)

CSS editor has been improved with a monospace font for better readability and it's also flexible to fit all screen sizes:

![css custom](https://user-images.githubusercontent.com/6364153/42328079-b64de3c2-806d-11e8-90a8-31f3a9596391.gif)

Uploads had a style rebump last release, this time I focused in the upload box with better styles and also adding the uploading alert inside the upload box:

![uploading](https://user-images.githubusercontent.com/6364153/42328283-2056f57e-806e-11e8-9ce0-9c2babc4f912.gif)
