### ISSUE TITLE
Missing icon

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1733]
![screenshot from 2018-06-28 17-14-31](https://user-images.githubusercontent.com/489831/42065225-f40d5b10-7af6-11e8-9f6f-626e14106501.png)

**Comment by danicatalan** [comment]
This will be fixed with the update to local icons. Keeping the issue opened because we should review all icons are correctly migrated though.

**Comment by daneryl** [comment]
@txau @danicatalan fixed, probably #1738, closing.
