### ISSUE TITLE
When editing an entity and there are nested multiselects, the component is showing Undefined for aggregations

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#1740]
When I try to edit an entity, and there is a property with a nested thesuari set to multiselect, the component is apparently trying to render an aggregation number, but instead shows Undefined:
![screenshot from 2018-07-02 12-33-57](https://user-images.githubusercontent.com/4309019/42178186-03441316-7df5-11e8-9bfd-0cb73dd462af.png)
Can you confirm this is the problem @konzz

**Comment by txau** [comment]
This was already reported and fixed: https://github.com/huridocs/uwazi/issues/1728
