### ISSUE TITLE
Common filters not showing warnings

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1741]
When editing properties used as filters, there was a warning if the properties match the names but not the thesauri to let know the user those properties won't be used as common filters regardless the name. 

There's no visual feedback working here:

![image](https://user-images.githubusercontent.com/6364153/42208096-a5552684-7eab-11e8-8033-7e68d4fe5916.png)

**Comment by txau** [comment]
Fixed in https://github.com/huridocs/uwazi/issues/2971
