### ISSUE TITLE
Multi-select searches are not looking into groups

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1742]
The item "Derechos laborales" is inside a group and should appear in this search:

![screenshot from 2018-07-03 08-06-10](https://user-images.githubusercontent.com/489831/42224750-11ee07a2-7e98-11e8-8a3c-bd57337a5b74.png)

**Comment by habbes** [comment]
@txau since Derechos laborales is nested inside a group, how should it be displayed? Should the group that contains it be displayed? Should it be expanded?

**Comment by txau** [comment]
This is very low priority, so lets go for the simplest solution. If not displaying the groups takes less work, go for that one, otherwise, display the groups.

**Comment by txau** [comment]
@habbes I suggest not fixing the automatic expansion of groups for now. At least the search matches are not being lost which was the important point of the issue. We can refine this UX some other time when we have time.
