### ISSUE TITLE
JS warning related to markdowns

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1743]
![screenshot from 2018-07-02 15-12-27](https://user-images.githubusercontent.com/489831/42231603-3904577c-7ea9-11e8-9b0a-3bd48d2b73c2.png)

**Comment by daneryl** [comment]
@txau where can i replicate this ?

**Comment by txau** [comment]
@daneryl I think any entity using a markdown. With the dev fixtures, open a "Causa" on the side panel from library.

**Comment by txau** [comment]
1. yarn fixtures
2. yarn hot
3. reload and go to library
4. filter by cause
5. select "Anzualdo Castro"
