### ISSUE TITLE
If I assign a property filter with name 'types', what happens to the aggregations?

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#1744]
Verify what happens if I create a property type as filter with name 'types'.

Since the aggregations have a key named 'types' for the template type aggregations, and then one key for each property name, if I use the name 'types' this may cause a conflict.

Check if there is a problem.

**Comment by txau** [comment]
@RafaPolit it does have an effect. It doesn't break searching or filtering. But it messes up with the counters for the templates as you can see in the screenshot (all counters to 0). Even after deleting the property, keeps messing the counters.

![screenshot from 2018-08-14 11-49-01](https://user-images.githubusercontent.com/489831/44084923-58787ec8-9fb8-11e8-874f-5927d4f050af.png)
