### ISSUE TITLE
Connection label's translations are not being saved

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1747]
1. Go to settings > translations
2. Edit a connection's translation
3. Save.
4. Exit and come back to edit the same connection translation.

New values were not saved.

**Comment by RafaPolit** [comment]
This is working as expected for the local fixtures.  Can you point to the instance where this is failing?

This procedure is sending all the contexts of translations, which could be getting too large in some requests?  To determine this it would be best to know which instance is failing.

**Comment by txau** [comment]
@RafaPolit CEJIL

**Comment by txau** [comment]
Actually, there was a problem with the database of this particular instance, it never was a bug.
