### ISSUE TITLE
We need server validation of metadata values (selects and multiselects)

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#1760]
There are certain flows that allow for invalid values to be stored in metadata.

One such flow is:
- Load two tabs of the browser, one editing an entity, one editing thesauri values
- Select a thesauri A on the entity editing pane
- Delete the thesauri value
- IMPORTANT! The value disappears from view on the entity select (through sockets, the thesauris have been updated), but the model is ALREADY ASSIGNED THAT VALUE, even if the option is no longer valid
- Without doing anything else, just save the entity

Now the entity has an invalid value that cannot be sanitized.

The correct approach is data validation upon save on server side for every operation.

**Comment by daneryl** [comment]
already fixed.
