### ISSUE TITLE
Filter by "No label" not working

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1782]
**How to replicate**

- Albinism instance.
- Go to Uganda.
- Open relationships.
- Filter by "No label".
- No results (Console throws no error).

![bug](https://user-images.githubusercontent.com/6364153/42556288-656d4b46-84eb-11e8-8403-27fd20f0c7e9.gif)

**Comment by txau** [comment]
This has been fixed in some other PR.
