### ISSUE TITLE
Create a specific card design for connections so they are better identified vs documents

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#179]
Moved to https://github.com/huridocs/uwazi/issues/425
- [ ] Connections have inbound/outbound/global icon (rethink those icons)

- - - - -

Moved to https://github.com/huridocs/uwazi/issues/426
- [ ] Group connection by source/target document.
- [ ] Display each connection in one row.
- [ ] Connections may show a snippet of the source/target text (if it's a connection to a paragraph). This can be expanded/collapsed.
- [ ] Filter by connection type.

- - - - -

- [x] Connections have type (like a document type tag).
- [x] Connections have an open document icon.
- [x] Think new ways of display this connections on sidepanel (maybe other than cards).
- [x] Fix delete button (remove unlink icon, add trash icon).
- [x] Fix little padding on selected connection (https://github.com/huridocs/uwazi/issues/254)

**Comment by danicatalan** [comment]
View connections (with hover and active states):

![screenshot 2016-09-15 18 30 54](https://cloud.githubusercontent.com/assets/6364153/18558271/c7de1f00-7b72-11e6-8d89-7540af169f30.png)

![screenshot 2016-09-15 18 31 10](https://cloud.githubusercontent.com/assets/6364153/18558272/c7de9e62-7b72-11e6-85a2-11970265a096.png)

Select an item to create a connections:

![screenshot 2016-09-15 18 32 14](https://cloud.githubusercontent.com/assets/6364153/18558270/c7daa456-7b72-11e6-9a1b-49744f8e0851.png)

**Comment by RafaPolit** [comment]
@danicatalan Is the removal of the 'delete' button on purpose? How will the connections get deleted once created?

**Comment by danicatalan** [comment]
This is updated on `179-connections`.

We need to do one more thing to deploy this into development. The **item-type** for every document is on plain HTML. We need to get this info from the document data.

Ping me if you have any douby!
