### ISSUE TITLE
Full text search should display result snippets for rich text fields as well

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1792]
Ie. In this case users don't know why these results are matching for the search "garcía", which is in the description field.

![screenshot from 2018-07-18 17-30-29](https://user-images.githubusercontent.com/489831/42913133-56ade80c-8ab0-11e8-810c-0f996abf6933.png)

**Comment by habbes** [comment]
@txau by result snippets you're referring to highlighting the text that matched the search term?

**Comment by txau** [comment]
@habbes exactly. So when you run a full text search you get these snippets with the highlights:

![screenshot from 2018-07-26 23-06-32](https://user-images.githubusercontent.com/489831/43288581-a01ef728-9128-11e8-8d2d-5c2423c5e4ef.png)

These matches are found in the document's text, but when the matches are coming from a rich text field no snippet is shown. This is confusing users since they do not understand why a particular document is a search result.
