### ISSUE TITLE
System hangs when trying to edit thesauri in OAU-AEC-AU instance

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#1793]
System hangs and shows a blank page when we try to edit thesauri on OAU-AEC-AU instance.
This especially with the 'PSC Meetings' dictionary. Also means that we can't finish doing metadata for any doc that needs that 'PSC Meetings' dictionary.
I have tried to add a new dictionary 'PSC Meetings2' but result is the same. Earlier dictionaries still work fine.
Kindly advice.

**Comment by konzz** [comment]
@HSips can't find the instance "OAU-AEC-AU" can you give me the exact name? like "OAU-AEC-AU.uwazi.org"

**Comment by HSips** [comment]
@konzz Thanks Alberto. Kindly advice. What do you mean by 'values'?

**Comment by txau** [comment]
@HSips thesaurus items.

**Comment by HSips** [comment]
@konzz @txau thanks!
Actually, then maybe also note that PSC Meetings had values. I had added about 20. Will delete and restart again, because we have a work sprint meet tomorrow with my students so we need something to do. But maybe the prob started on that point. that the values disappeared. There are about 783 PSC Meetings so will be adding many..

**Comment by HSips** [comment]
Hey, sorry to be back again. PSC Meetings thesauri cannot be deleted.
<img width="960" alt="26072018" src="https://user-images.githubusercontent.com/22650647/43252965-730e0a78-90cc-11e8-8ba2-ed0b1b66c980.png">

**Comment by txau** [comment]
@HSips why do you want to delete the thesaurus? This is working as intended, if you want to delete it you first need to manually remove the values from any entity or document using them. This can be easily achieved using the bulk update option. 

I've bee checking you instance but this field does not seem to be activated as filter, so I cannot check if its being used.

**Comment by txau** [comment]
@HSips I just verifgied this and the bug is already fixed.
- Now a thesauri will not crash if its saved with no values. So you can use PSC Meeting as it is.
- This dictionary is configured in properties in entities and docs, so it cannot be deleted. If you want to delete it and recreate it from the scratch, you need to first remove it from the templates. Anyway, I don't see what is the advantage of deleting it if you are going to create it again.

**Comment by HSips** [comment]
@txau thanks a mil for this! 
No worries on the delete. Yes, we will continue to use as is.
Also activated the various filters.
