### ISSUE TITLE
Full list of filters does not show on OAU-AEC-AU instance public page

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#1794]
The public page of the OAU-AEC-AU instance only shows one filter with 96 docs, but clearly indicates 857 docs published.
<img width="960" alt="21072018" src="https://user-images.githubusercontent.com/22650647/43031701-ae00f256-8caf-11e8-800d-76a7fe62cd9f.png">

When one logs in, the public page looks like below: still one filter, but different set of docs
<img width="960" alt="21072018-2" src="https://user-images.githubusercontent.com/22650647/43031746-87f578e2-8cb0-11e8-8e19-42dfbbff057b.png">
But in the 'Private docs' section, the whole range of work done is shown. 384 docs yet to be sorted and published, and the right column shows all doc types already published.. 
<img width="960" alt="21072018-3" src="https://user-images.githubusercontent.com/22650647/43031759-e0a28d9a-8cb0-11e8-90c7-25cc52fbf718.png">

So what are we doing wrong in the settings? Kindly advice

**Comment by konzz** [comment]
@HSips Looks like the instance is configured to only show that type of documents, if you check Settings -> Filters, you will see that in the list there is only "AU Assembly declarations", if you want all the types to appear, just empty that configuration and all types will be shown by default, or you can create groups etc.. there is a small guide in the section. 

Closing the issue, if you need further help just reopen it.
