### ISSUE TITLE
Improve search bar

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#180]
Related to https://github.com/huridocs/uwazi/issues/90.

Collapse search bar by default and activate it with the sidebar, when:

- Click on floating action button (opens both search bar and sidebar).
- Click on header search button (opens both search bar and sidebar).

![searchbar0](https://cloud.githubusercontent.com/assets/6364153/16567065/ef0c0ba0-421a-11e6-8363-dc7eb7bdbdef.png)
![searchbar1](https://cloud.githubusercontent.com/assets/6364153/16567066/ef0dfdc0-421a-11e6-9a32-9709350ddac7.png)

**Comment by danicatalan** [comment]
![screenshot 2016-08-08 20 00 02](https://cloud.githubusercontent.com/assets/6364153/17490451/274da53e-5da3-11e6-99c3-53f19668d5fd.png)
![screenshot 2016-08-08 20 00 10](https://cloud.githubusercontent.com/assets/6364153/17490453/275126fa-5da3-11e6-8dc6-9d1da934e4b8.png)
![screenshot 2016-08-08 20 00 28](https://cloud.githubusercontent.com/assets/6364153/17490454/2750ec58-5da3-11e6-8a67-921051c5ccf0.png)
![screenshot 2016-08-08 20 01 20](https://cloud.githubusercontent.com/assets/6364153/17490457/2767b6cc-5da3-11e6-9bcc-09f8ea452ab7.png)
![screenshot 2016-08-08 20 01 41](https://cloud.githubusercontent.com/assets/6364153/17490458/2767f92a-5da3-11e6-8f43-ba26f9ef3ab4.png)
![screenshot 2016-08-08 20 01 50](https://cloud.githubusercontent.com/assets/6364153/17490456/276575c4-5da3-11e6-8a4b-8d7c18174c32.png)

**Comment by danicatalan** [comment]
@daneryl we need to check the test suite and fix this:

![close-on-click](https://cloud.githubusercontent.com/assets/6364153/17557090/2316ef6a-5f16-11e6-96ce-faaba79102e1.png)

If a user clicks on the button, the suggester must close.

Branch https://github.com/huridocs/uwazi/tree/improve-header

**Comment by txau** [comment]
Implemented in #289
