### ISSUE TITLE
Navigation on Link component doesn't scroll to top

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1813]
As a user, when I click on a <Link> component I expect the same behavior than clicking on a regular <a> component: navigate to the URL and start reading the content from the top of the page.

Currently, the <Link> component scrolls to the same Y position in the next page, making the user scroll manually to the top of the page.

The expected behavior should be:

- Click on a Link component.
- Go to the next page.
- Start reading from the top of the page.

**Comment by danicatalan** [comment]
![scroll](https://user-images.githubusercontent.com/6364153/43652115-9015ec16-9744-11e8-96bf-70b00661f47d.gif)

**Comment by OzrenMuic** [comment]
This is resolved
