### ISSUE TITLE
Add % on gauges

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#1814]
We need to add the suffix to the implementation so users understand is a percentage scoring.

**Comment by daneryl** [comment]
So, there is a few changes (especially for @danicatalan)
There is a new component named Value, which outputs a metadata value. This can be used anywhere! So:  ```<p>Ghanda has completed <Value dataset="anEntityDataset" property="completion" />% of its work</p>```. This is really useful for using those values anywhere in the text.
For the Gauge component, you no longer need to pass the "label" prop as true or false to show or not the value. You create whatever you want inside as usual HTML children. If you don't want the value printed, you just don't put anything inside the component. Much more elegant.
Using a 'Value' element within the Gauge inherits the parent's dataset and property values, so there is no need to repeat them. So:
```
<GaugeChart max="100" dataset="anEntityBasedDataset" property="propertyName"><Value />%</GaugeChart>
```
Will give you exactly what you want.  But you could do that for money, for instance, and add the dollar symbol in front: 
```
<GaugeChart property="propertyName">$<Value /></GaugeChart>
```
it's a lot more versatile.
