### ISSUE TITLE
Relationships target search is not matching partial words

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1821]
As you can see in the example, it is not showing results for "Alv", but its showing for "Alvaro".

![screenshot from 2018-08-13 15-21-19](https://user-images.githubusercontent.com/489831/44034143-ae2f245e-9f0c-11e8-982b-0f8c2b369680.png)
![screenshot from 2018-08-13 15-21-04](https://user-images.githubusercontent.com/489831/44034144-ae5c2878-9f0c-11e8-9285-d7bea5a7cb48.png)

**Comment by konzz** [comment]
@txau I've investigated the issue, and it requires further discussion for the possible solutions.

**Comment by txau** [comment]
Actually this functionality is supported via query string options (ie, wildcards, as in searching for alv*).  We are going to add some user help instead. Closing in favor of: https://github.com/huridocs/uwazi/issues/1856
