### ISSUE TITLE
Improve editing / deleting effects on pages when triggered from the side-panel

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#1840]
The new pages side-panel shows entities / documents data now, and a logged user can edit that data.

Saving the edit or deleting the document does not update the values on the center page lists.  This should be dealt with somehow:
- [x] Update the center data with the server-success response
- [ ] Reload the datasets in the page (which could potentially mean that the document disappears from view)
- [ ] Prevent editing from the page side panel (@txau has voiced against this approach)

**Comment by konzz** [comment]
Tested and this is no longer happening.
