### ISSUE TITLE
Map: Please select a valid value

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1843]
![image](https://user-images.githubusercontent.com/6364153/44675903-07c15e80-aa32-11e8-91f9-2bc171a744a9.png)

**Comment by txau** [comment]
This bug is pretty consistent rendering geolocation field unusable.

Please make sure we have an e2e test for this functionality.

**Comment by txau** [comment]
@konzz not sure how to test it, its not really working for me.

![screenshot from 2018-09-20 15-42-32](https://user-images.githubusercontent.com/489831/45822492-e29bd500-bceb-11e8-8298-5a68555844da.png)
