### ISSUE TITLE
Slider not following the library sort order

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1844]
![image](https://user-images.githubusercontent.com/6364153/44676950-f0d03b80-aa34-11e8-92d7-d9f1a9563714.png)

![image](https://user-images.githubusercontent.com/6364153/44676977-080f2900-aa35-11e8-8009-b4407da13b81.png)

**Comment by txau** [comment]
This is barely a bug:
- The URL used for configuring the slider didn't contain the sorting criteria explicitly (this may be part of the problem).
- Even if it did, the slider will show the first element of the collection in the middle. So the first element from the right actually is the last of the collection.

This could be improved, but I guess is not so bad =)
