### ISSUE TITLE
Search term instances in document view not highlighting

### ISSUE THREAD

**Issue by CESRadmin** [huridocs/uwazi#1878]
When in document view, the instances of each search term are not being highlighted, which makes research very cumbersome. I image that this is a bug.

Attached is an image demonstrating this. After clicking on the page number "9", the instance (displayed in the body of the text on the left) does not highlight.

Here is a link to the site: https://cesr.uwazi.io/

![no-highlighting_image](https://user-images.githubusercontent.com/38893920/45233133-c9cd0180-b29f-11e8-9b7b-c7c83aefaffb.png)

**Comment by txau** [comment]
Indeed its a bug that we may have introduced during the last deploy. I'm going to move this to high priority.

Related: https://github.com/huridocs/uwazi/issues/1391 https://github.com/huridocs/uwazi/issues/1390

**Comment by txau** [comment]
This has been partially addressed in https://github.com/huridocs/uwazi/pull/1895. There are still some edge cases failing that will be addressed in an additional development.

**Comment by txau** [comment]
This issues has been fully addressed in #1924
