### ISSUE TITLE
place the new logo into the login page

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazi#188]

**Comment by konzz** [comment]
@danicatalan @UjoNyawara @txau Can someone attach the new logo file to this issue? Thanks :)

**Comment by danicatalan** [comment]
We can't attach svg on GitHub. I'm working on this branch, you can get it from here: https://github.com/huridocs/uwazi/commit/fea0d3a11da0790a6d7d0403f77e00f00e208fa7
