### ISSUE TITLE
Fix text mode for mobile

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1881]
- Make sure the button does not overlap the pagination controls.
- Make the text responsive.

![screenshot from 2018-09-10 17-23-11](https://user-images.githubusercontent.com/489831/45307053-58e74d00-b51e-11e8-9dce-ac3b071822da.png)

**Comment by RafaPolit** [comment]
The first bullet point seems to be fixed.  The second issue is still happening.

**Comment by txau** [comment]
I described the second problem as a feature request: https://github.com/huridocs/uwazi/issues/4779
