### ISSUE TITLE
Request/Idea: Add an automated "Date updated" property option

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#1893]
I'm putting together a collection of tools and resources related to human rights documentation (https://doc-resources.uwazi.io). This is meant to be a living collection. It would be really helpful if visitors could see the "Date updated" instead of "Date added" so they know when the information on that card has last been updated.

**Comment by daneryl** [comment]
@txau @grafitto @kjantin 
there are some actions that update entities as a side effect:
 - updating an entity title (in future implementations this can be other properties) will update all entities related to the updated entity.
 - updating a template will update all its entities in certain actions, like deleting a property.
 - there may be more but i am not sure.

should we take this into account ? or only update the "updatedDate" on explicit entitiy update ?
