### ISSUE TITLE
Allow limiting chart and lists datasets

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#1894]
When using charts or bulleted lists, it would be nice to have an option to limit the amount of data items to show.  Ideally, the remaining items would be aggregated into an 'other' entry.  Perhaps the 'other' could be also an option? True or false, it either aggregates or not.

**Comment by txau** [comment]
Moreover, passing in a list of the wanted properties and the desired order of appearance.

**Comment by daneryl** [comment]
@RafaPolit @txau 
ListChart, BarChart and PieChart right now support a "maxCategories" that will show the number of categories passed + all the others aggregated on "others" category, the order can not be specified.

**Comment by txau** [comment]
@daneryl so I moved order and arbitrary properties to two other smaller issues:

- https://github.com/huridocs/uwazi/issues/2434
- https://github.com/huridocs/uwazi/issues/2435

Can we maybe close this one?

**Comment by daneryl** [comment]
yes, closing ...
