### ISSUE TITLE
Fix charts legends

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1898]
Some of our charts are failing to properly display the labels of the graphed values:

![screenshot from 2018-09-15 08-15-14](https://user-images.githubusercontent.com/489831/45583298-900f8280-b8bf-11e8-9e08-84f844f2d54b.png)

**Comment by txau** [comment]
A proposed solution is to be able to provide a map of short names or acronyms to substitute long titles.This map will be an extra param when instantiating the graph.

**Comment by RafaPolit** [comment]
The implementation, as discussed, is to provide a map of shortened values.  This will be passed in the `shortLabels` property as a JSON object:

```
<BarChart ... shortLabels='{ "A long label": "shrtLabel", "United Nations (UN)": "UN" }' />
```
