### ISSUE TITLE
Add SMTP mail configuration options

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#190]
Email notifications (password recovery, etc) are sent via SMTP. We need a screen under the admin section to configure these SMTP parameters.

**Comment by RafaPolit** [comment]
- The question mark after 'failing' the password is not intuitive.  There should be a permanent option to recover password
- When recovering the password, the field asking for email should not be pre-filled with the user name already entered in the field before
- Think about how we want SMPT to be configured: in admin? configured natively from our instances? other installations should change the code?
- Down the road: two-step verification? Google signup? Other?

**Comment by konzz** [comment]
Already Implemented
