### ISSUE TITLE
Add vertical size hidden overflow to all properties in cards

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1900]
Some users are accidentally getting these kind of results:

![screenshot from 2018-09-15 09-44-52](https://user-images.githubusercontent.com/489831/45583986-1205a880-b8cc-11e8-8013-7b159cef5b5a.png)

**Comment by RafaPolit** [comment]
I'm not sure we want to limit the height arbitrarily.  What if this long view is what the users are expecting?

**Comment by nwyu** [comment]
Closing this issue for the time being. We can open it again if there is an expressed need, but so far, no partner has requested to limit the card height.
