### ISSUE TITLE
Move responsibility of detecting translation changes from templates to translations

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#1902]
Discuss if this is still desired:
Move responsibility of detecting translation changes from templates to translations

Moved from #1465

**Comment by txau** [comment]
@konzz @RafaPolit can you guys explain what this is about?

**Comment by RafaPolit** [comment]
I just moved the missing bullet point from issue #1465, no idea what this is actually. Sorry.

**Comment by txau** [comment]
I hope @konzz can clarify.

**Comment by konzz** [comment]
Closing infavour of  translations revamp #3344

**Comment by daneryl** [comment]
> Closing infavour of translations revamp #3344
