### ISSUE TITLE
Error message "No common filters" but there is a common property/filter

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#1904]
In this Uwazi instance: https://doc-resources.uwazi.io
I have a property related to the "documentation purpose" on the entity "tool", "online resource" and the document type "document". But when I try to filter all of these entity/document types by this property, I get this error message:

![image](https://user-images.githubusercontent.com/354426/45643885-25f70900-ba8a-11e8-9ecb-a1d5b5bacb57.png)

I expect to be able to access that common property, and therefore filter all the entities/documents with that property.

**Comment by txau** [comment]
@kjantin I guess this can be closed =)
