### ISSUE TITLE
Admin section needs to have a scroll bar

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#194]
When the viewport size is smaller than the content, the scroll bar doesn't show up.

**Comment by danicatalan** [comment]
This is the same as #116. I think I will fix both at the time.

**Comment by danicatalan** [comment]
PR doesn't work on Firefox.

**Comment by txau** [comment]
Actually not working.

**Comment by danicatalan** [comment]
We made the QA without merging development into the branch. I tried in local and it breaks. I will fix it and reupload the code.
