### ISSUE TITLE
Review "Password" label translation

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1957]
Some users have reported that their password field is being displayed as "Login failed":

1. Review the blank state fixtures to make sure this is fixed.
2. Create  a migration so that this is updated in all current instances.

![image pasted at 2018-10-5 08-21](https://user-images.githubusercontent.com/489831/46537800-78219200-c8b2-11e8-866c-21bb62ce904e.png)

**Comment by txau** [comment]
@kjantin this was already fixed and is not happening in new instances. For old instances, user should fix this manually using translations.

**Comment by kjantin** [comment]
Ok, so the existing instances have "Login failed" as a translation of "Password" under the "System" translation section:

![image](https://user-images.githubusercontent.com/354426/46544517-d427ee80-c891-11e8-8c99-7791383a7130.png)

And everyone needs to go there and replace "Login failed" with "Password" to fix this.

**Comment by txau** [comment]
@kjantin yes
