### ISSUE TITLE
Provide a Docker image?

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#1961]
I am looking into test-driving Uwazi for a human rights documentation project I am involved in and the first thing I thought when skimming through the list of dependencies was whether one couldn't make things a lot easier by providing a docker image with everything in place... 

Just a suggestion...

**Comment by whyfrycek** [comment]
As mentioned over email - there was https://github.com/fititnt/uwazi-docker @daneryl @txau do you know if it works?

**Comment by txau** [comment]
Related: https://github.com/huridocs/uwazi/issues/1595

I'm going to take a look to the current status of this image.

**Comment by fititnt** [comment]
Nice. More people to test.

@vasyugan about the more specific issues with docker, you can comment there. It was more tested for the version 1.1 and I updated to 1.2.

The Uwazi 1.3 released yesterday maybe will not work out of the box at this moment since have a few more dependencies

**Comment by vasyugan** [comment]
Docker is definitely the way to go to avoid messing with the host system too much and prevent mongodb and elasticsearch from exposing their ports. 
What I think it particularly important is having proper separation between persistent data and containers which contain the apps, something Docker really shines at. You really don't want to loose your data because you deleted the uwazi container.
Also, I

**Comment by txau** [comment]
I see you guys figured out some docker issues and its working for you, so I'm closing this issue for now.
