### ISSUE TITLE
More complete instructions for building and configuring

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#1963]
# build instructions:

* don't skip the step of git cloning the code and *changing into* the uwazi directory. Make clear that "yarn install" has to be executed inside this directory. This may seem obvious to the developers, but for who has not worked with these tools, it is not, and because of that, everything goes wrong. I had no idea what "yarn install" does, so I just ran it in my home dir, later cloned the code, changed into it and ran "yarn production-build" which produced failure over failure. I desperately tried to satisfy all depends manually but to no effect. A simple note that "yarn install" is something that needs to be run where the code is would have saved me hours.
# Configuration
* Once the build is through, it still fails because elasticsearch can't be started, unless there is a java installed. For some reason, the deb doesn't depend on Java... On debian, I recommend building an oracle java deb with [java-package](https://wiki.debian.org/JavaPackage) Works much better than OpenJDK, especially on machines with limited RAM
* It should be added that one has to enable elasticsearch and mongod via systemctl (systemctl enable --now ...)
* And, as I wrote in #1966 once I had the system up and running, I had no idea how to log on, as the default credentials don't seem to be documented anywhere.
* Which brings me to the lack of information on how  / where to configure SMTP settings for recovery email or any other mail the system may want to send. 
* The documentation does not say, whether Uwazi can handle https on its own or whether it has to be proxied trough a web server for https (I suspect the latter)
* I saw in the log directory that there is a debug log, but it is empty, and it is not documented where and how to enable debugging. 

# Maintenance
* I haven't found in the documentation what is best practice for backup and restore.
* Finally, since this is installed in the user's home directory, it should be documented what the recommended way of starting / stopping the service is. For now, you don't seem to be using systemd to have it started and stopped automatically, but one has to manually log on, change to the directory where the application is locate and run "yarn run-production". I guess there must be a more elegant solution than that.

**Comment by txau** [comment]
@vasyugan thanks for this detailed feedback.

I edited the README and some wiki pages to reflect these questions. Please feel free to take a look a provide further feedback.

> It should be added that one has to enable elasticsearch and mongod via systemctl (systemctl enable --now ...)

I think this kind of stuff is covered in Mongo and ElasticSearch's user support literature. It may vary from one system to another or among versions.

> The documentation does not say, whether Uwazi can handle https on its own or whether it has to be proxied trough a web server for https (I suspect the latter)

This is being discussed in https://github.com/huridocs/uwazi/issues/1985 and hopefully can be sorted out soon.

> I saw in the log directory that there is a debug log, but it is empty, and it is not documented where and how to enable debugging.

We don't have a debugging flag across Uwazi that will log all debugging information. This log is used sometimes both in production and development to hunt down elusive bugs (we had a couple of poltergeists in the past). 

> Finally, since this is installed in the user's home directory, it should be documented what the recommended way of starting / stopping the service is. For now, you don't seem to be using systemd to have it started and stopped automatically, but one has to manually log on, change to the directory where the application is locate and run "yarn run-production". I guess there must be a more elegant solution than that.

In development we run it manually in our local environments. For production we have system services. This also may be different from one system to another, different scenarios different solutions.
