### ISSUE TITLE
Document default login / password

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#1966]
After

yarn blank-state
yarn run-production

I visit http://uwazi:3000 (Uwazi is the hostname for the VM with my test install), and I am greeted by a screen where I am supposed to provide a user name and password. While I do both, I cannot log on with them later. I get "login failed" and am given the option to send a recovery email. but since I haven't even gotten around to configuring SMTP, no mail is sent. The error log says nothing about the login error. Also, I see no related console output.

**Comment by whyfrycek** [comment]
Default log in is admin / change this password now

- should be added to readme

**Comment by txau** [comment]
@vasyugan failed logins are not meant to be logged in the error log. Is the problem related to the default password as @whyfrycek suggested?

**Comment by vasyugan** [comment]
Am 10.10.2018 um 10:53 schrieb Jaume Cardona:
>
> @vasyugan <https://github.com/vasyugan> failed logins are not meant to
> be logged in the error log. Is the problem related to the default
> password as @whyfrycek <https://github.com/whyfrycek> suggested?
>

Yes it it, I couldn't find it in the documentation. I guess how to log
in should be documented either in the install instructions or the wiki.

**Comment by txau** [comment]
@vasyugan Definitely!

**Comment by vasyugan** [comment]
You might want to add that not only the password but also the user name can be changed (which is not the case on most other systems I am familiar with)
