### ISSUE TITLE
No documentation on how to create a "select" list

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#1970]
One can add a "select" property to documents, entities and other data objects, but it is unclear how to populate the select list with  items. There is no link, no tooltip and no explanation in the Wiki.

**Comment by vasyugan** [comment]
Found it out, one first has to create "thesauri", which is a bit of a confusing term in that context. Should be documented.

**Comment by txau** [comment]
Hello @vasyugan, thanks for you feedback. 

Added explanatory notes in entity (https://github.com/huridocs/uwazi/wiki/Create-entity-types) and document (https://github.com/huridocs/uwazi/wiki/Create-document-types) creation pages.
