### ISSUE TITLE
Pretty 404

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1981]
Give it some love.

![screenshot from 2018-10-10 16-07-44](https://user-images.githubusercontent.com/489831/46742109-a504e900-cca6-11e8-99a1-781a442459d0.png)

**Comment by konzz** [comment]
This is in theapp/react/App/NoMatch.js component

**Comment by txau** [comment]
Maybe @simonfossom can create something nice such as:

![image](https://user-images.githubusercontent.com/489831/101916181-35435f00-3b8c-11eb-9b5d-d6bd282bf3e4.png)

**Comment by simonfossom** [comment]
I'm on it. 

BTW what are all the cases of 404 that can happen on Uwazi?
Missing documents, deleted entity, and change permissions shouldn't be handled as 404. Only missing _pages_.

**Comment by konzz** [comment]
As for now 404 happens whenever a URL does not match any result it also includes deleted entities but we can take care of it in a different issue.

Another detected problem is that redirect to 404 from server does not happen.

**Comment by simonfossom** [comment]
[Design is done](https://www.figma.com/file/xjsz7r65epN4B0b96zilac/0-uwazi-redesigns?node-id=1455%3A29767)

![uwazi 404](https://user-images.githubusercontent.com/8134850/102202477-a4d88780-3ec7-11eb-8e59-1b9043253706.jpg)

**Comment by txau** [comment]
We don't have a pretty design but we don't have that ugly 404 from the past. Closing for now.
