### ISSUE TITLE
Entire content gone after unclean shutdown

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#1983]
I am shocked to see that after the hosting machine was powered off and rebooted, all the content is gone. Can it be recovered in some way? How is data integrity supposed to be protected?

**Comment by vasyugan** [comment]
to be more exact, all the metadata is gone, the uploaded documents are still sitting in the folder, but document types and entity types are gone, so the documents don't show up and all the entities are gone. The thesauri are stil there. No, I ran neither of those commands.

**Comment by vasyugan** [comment]
i just restarted the server with yarn run-production

**Comment by vasyugan** [comment]
Weird, but relieved: The content has returned. Not sure what this means.

**Comment by txau** [comment]
@vasyugan from what you describe, the content was there in the database but elastic search was reindexing it. I don't know exactly why this happened since once the content is indexed, it remains indexed.

Very relieved to know you didn't loss your data.

**Comment by vasyugan** [comment]
@txau Where is the database stored anyway? I was pretty surprised that Uwazi doesn't require credentials to talk to mongodb

**Comment by txau** [comment]
@vasyugan yup, that is one of the pending issues. We are assuming scenarios where the access to mongo and elastic is firewalled or restricted to certain users.

The data is stored in mongo and shared with elastic for search and filtering.

**Comment by vasyugan** [comment]
@txau Actually I don't understand how a default install of a database server allows access without any credentials, including the right to create a new database. Apparently, mongo by default grants full passwordless access to local users, am I guessing correctly? Because all the uwazi install is local to the user, at no point is system-wide configuration touched. So this behaviour of mongodb seems to be preconfigured that way.

**Comment by vasyugan** [comment]
Unfortunately, I see something quite similar again: I today moved the data to a dedicated server, installed uwazi there (non dockerized), restored an database dump and copied the uploaded_documents directory over. And again all the documents and all the entities are gone, only settings and thesauri have survived the migration. How can this be? Aren't at least the entities stored in the mongo database (the aren't physical files, after all). And wouldn't files stored in the uploaded_documents directory be indexed by elasticsearch after some time? The files are world readable, the directory has mode 755. But somehow even after several hours, they don't show up.

**Comment by vasyugan** [comment]
ran yarn migrate in the directory, but while the output suggested that it had found 9 pdfs, the are not listed (in private documents)

**Comment by vasyugan** [comment]
a, ok yarn reindex did the trick.
