### ISSUE TITLE
Support for / instructions on how to enable https

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#1985]
It should be documented whether or not Uwazi handles https and what steps are required to set it up.

I suspect that Uwazi by itself does not support https but has to be proxied through a web server, which provides both the encryption and handles the SSL certificate. 

If so, it should be explained, how I can stop Uwazi from listening on other interfaces than 127.0.0.1 because I definitely don't want it to remain accessible through an unencrypted connected on port 3000.

**Comment by txau** [comment]
@vasyugan so far we are using an nginx proxy. But I guess this is important enough to set it as high priority and implement it soon.

**Comment by vasyugan** [comment]
thanks @txau We are also using nginx on our server, so if you could add a same config to the Wiki, that would be awesome. Also, beside setting up the proxy, one probably would want Uwazi to stop listening on interfaces other than 127.0.0.1 for unencrypted http connections on port 3000. Or do I have to block it via iptables?

**Comment by vasyugan** [comment]
It is probably going to look somewhat similar to the instructions given by Nextcloud on how to set a reverse proxy in Nginx for Collabora Office: https://icewind.nl/entry/collabora-online/

**Comment by txau** [comment]
@vasyugan at the moment we are blocking it via IP tables.

**Comment by fititnt** [comment]
About  HTTPS, the most common way to do it is not implement the full HTTPS stack on the app, but break with smaller services. So NGinx, Apache or even traefik (for who loves microservices) tend to be a good way to do it. I'm saying this because node _can_ provide HTTPS, but it could add to much complexity and not really used in production at all, but document how to use with one or more options, in my honest opinion, seems to be sufficient.

Also, if have to choose one of those, NGinx is pretty popular for both bare and container usage. If have some documentation on this and interest on testing, I could add also one or more services to https://github.com/fititnt/uwazi-docker, even if the default certificates could be self signed and the NGinx installation is also just one extra quick reference.

**Comment by vasyugan** [comment]
@fititnt Another reason why a reverse proxy is probably better is because of certificate handling. All mechanisms I know of for creating and renewing Letsencrypt certificates are designed to work with common web servers. 
But what it probably less difficult is to ensure that uwazi doesn't listen on ports other that 127.0.0.1, rather than having to block the port manually via iptables

**Comment by vasyugan** [comment]
@fititnt I don't think that a nginx with a self-signed certificate would be a good solution.  When you have a real FQDN, you can always get a letsencrypt certificate for Nginx or Apache in an automated manner (with the official letsencrypt client or acme.sh or maybe many others). So if you have an FQDN, there is absolutely no need for a self-signed cert.

**Comment by fititnt** [comment]
If I'm not wrong (and I could be), the Uwazi serves both the dynamic requests and stream the files download with via NodeJS. This consumes a bit more CPU than would be serving static files directly via NGinx/Apache, but makes easier for access control and (this matter here) maybe just need to **proxy all requests from a domain to a specific port inside the local network**. So possibly almost any example of reverse proxy would work here.

As reference, NGinx configuration would be more simple like https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04 than references like https://icewind.nl/entry/collabora-online/ or https://docs.moodle.org/35/en/Nginx.

So in this case, maybe just would require that in some part of documentation (if already is not explained and if already does not bind port 3000 only for local connections) write one way to expose the Uwazi port only to localhost. I think most NodeJS developers use some sort of management to keep the process alive and restart automatically if it fails, and these sort of strategies already have their own way to bind a port only for a specific ip, like the 127.0.0.1. The tutorial from digital ocean, for example, uses PM2 (http://pm2.keymetrics.io/) for this.

So, maybe this issue would be 
1. Just document more about (example: suggest the user to use a reverse proxy to access the port 3000 and then block this port outside the machine)
2. If the default way to run Uwazi with docker bind to 0.0.0.0 (allow access for every computer outside) and does not have some option to bind to 127.0.0.0 (only localhost) without some more complex change or knowledge of how NodeJS works, then change the Uwazi code to allow it without need of more complex stack. (if the `yarn run-production` does not bind access only to localhost access)

Just to make clean: the point 2 does not means that the actual and older versions of Uwazi would have the port exposed, just means that was required additional way to block these ports with firewalls, handle SSL, etc when running in production.

**Comment by txau** [comment]
Along with the LOCALHOST_ONLY config flag, I added a note for using reverse proxy for HTTPS.

https://github.com/huridocs/uwazi/wiki/Install-Uwazi-on-your-server

I haven't added examples on how to configure nginx or any other solution, but there is plenty of information about this on the internet.
