### ISSUE TITLE
Uwazi needs working /usr/sbin/sendmail. Without it, mail delivery fails silently

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#1986]
When setting up new users, the password field is present but one cannot fill it out (which is in itself confusing), obviously, Uwazi tries to send mail to the user, allowing them to set up their own password.

However, when /usr/sbin/sendmail is not there or does not work for external mail delivery, then the administrator is not notified of the failure in any way. I only discovered in the error log that Uwazi had been looking for /usr/sbin/sendmail I think there should be an immediate visual feedback in the admin interface.

**Comment by txau** [comment]
Actually Uwazi supports SMTP configuration for scenarios without sendmail. Find the configuration option in settings > collection.

That said, it should definitely offer some kind of feedback to the admins in case there is something wrong with the mailing.

**Comment by txau** [comment]
Fixed in #2009
