### ISSUE TITLE
Add piwik / matomo support

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#1994]
I see the system supports Google analytics, and I found #971 which talks about it.  I understand, back then it was decided to go for Google Analytics, but a year later, the EU General Data Protection Regulation changes the picture. From a privacy / data protection point of view, it would definitely be much better to support self-hosted Matomo (formerly piwik), at it is not a tracker following you around whereever you go on the internet. 

Also, as a server operator, I would rather avoid having to get a google analytics id just for this service.

**Comment by txau** [comment]
@vasyugan 100% with you on this one. Let's try to get this done ASAP.
