### ISSUE TITLE
Improve user feedback when attempting to download a document that doesn't exist

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1995]
- Broken link (file doesn't exist)
- Wrong id
![screenshot from 2018-10-11 11-48-00](https://user-images.githubusercontent.com/489831/46795946-b05e2000-cd4b-11e8-9f14-05cb6ccf667b.png)

**Comment by daneryl** [comment]
We should Throw a 404 error on any attachment that for any reason does not exists.

**Comment by txau** [comment]
@daneryl @habbes unless we actually have the file registered in the database but the file does not exist in the file system. In this case a 400 will log the problem.

**Comment by habbes** [comment]
@txau when the attachment exists in the database but does not exist in the file system, it currently returns a 500 error with the following message:
```
{
    "error": "Error: ENOENT: no such file or directory, stat '/path/to/uwazi/uploaded_documents/1540935218679ovspsvkgouf.jpg'"
}
```
It also logs the error

**Comment by txau** [comment]
@habbes no, in this case its ok to leave the 500.

**Comment by habbes** [comment]
Here's a PR #2060
