### ISSUE TITLE
Uwazi v1.3 poppler dependency

### ISSUE THREAD

**Issue by fititnt** [huridocs/uwazi#2002]
refs: https://github.com/fititnt/uwazi-docker/issues/18

> Uwazi v1.3 released yesterday (https://github.com/huridocs/uwazi/releases/tag/v1.3) have a new dependency, pdftotext version 0.67.0.

> The base image node:8-slim provably will load the version 0.26.5-2+deb8u4 (refs https://packages.debian.org/pt-br/jessie/poppler-utils) from Sat Sep 27, 2014, but the poppler-0.68 was released on Sun Aug 19, 2018 (https://poppler.freedesktop.org/releases.html). So the developer used a pretty recent version, maybe with very good reason.

----

I'm opening this issue on poppler to have some feedback / testers when running on docker. But possibly the instructions could serve to also work on any debian/ubuntu installation, so this issue could be referenced later too.

**Comment by fititnt** [comment]
Ok, so just a question, the poppler **must** be version 0.67, or was not just tested on older versions, that already are release by default on some linux distros?

If the version must be around 0.67, did you here have some reference on how to build from sources?

**Comment by txau** [comment]
@fititnt it was tested in older versions and the results are pretty much the same. 

The only reason why we are recommending to use the latest is because we are assuming its providing better results (although we haven't found any case that proves this point).

**Comment by txau** [comment]
@fititnt I updated the README to reflect this topic:
> pdftotext (Poppler) tested to work on version 0.26 but its recommended to use the latest available for your platform https://poppler.freedesktop.org/
