### ISSUE TITLE
Separation of programme code and user data

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#2005]
For running uwazi dockerized, user data and programme data need to be separated, so that all the user's work isn't gone when the current container is replaced. Therefore in docker the uploaded_documents directory needs to be mounted via the VOLUME command. Volumes are meant to be persistent while containers may be transient. However, when I put 
VOLUME ["/home/node/uploaded_documents"]
into the Dockerfile, git clone fails because the directory /home/node/uwazi already exists.
I thought that a workaround is to move the VOLUME command to after the git clone process. 

But in terms of hygiene and with a view to protecting valuable user data, it is probably a good idea to have the separation of user data and programme data anyway and to place uploaded documents into a directory outside the programme directory.

I am really worried how easy uwazi it makes to wipe all your data by accident, and I think a clear separation between programme code and user data would be the first step towards easing backup and restore...

**Comment by txau** [comment]
@vasyugan actually that is already implemented. You can use these two env vars to specify where you want your data:

Environment=UPLOADS_FOLDER=/path/to/uploaded_documents
Environment=LOGS_DIR=/path/to/log

**Comment by vasyugan** [comment]
@txau great, so that should definitely be in the dockerfile then

**Comment by txau** [comment]
@vasyugan thanks to your feedback I'm documenting a lot of undocumented stuff. I just added that info along with an example service here: https://github.com/huridocs/uwazi/wiki/Install-Uwazi-on-your-server
