### ISSUE TITLE
does Uwazi have to run under top level address (need sub level address under host)

### ISSUE THREAD

**Issue by whisere** [huridocs/uwazi#2025]
Hello, I am trying to run Uwazi under host directory with apache proxy:
something like this:
<VirtualHost *:80>
ServerName hostname
Proxypass "/uwazi" "http://localhost:3000/"
ProxyPassReverse "/uwazi" "http://localhost:3000/"
</VirtualHost>

But when I go to hostname/uwazi the stylesheet messed up and it reported can't find /en directory.
Does Uwazi have to run under top level of the host ?  Thanks!

**Comment by txau** [comment]
@whisere I'm afraid as of today, it does. Probably this is easy to fix but I don't think we are going to be expending time on this sometime soon. Sorry =(

**Comment by whisere** [comment]
@txau No problem, I have solved it by getting a top level address. Thanks for letting me know : ).
