### ISSUE TITLE
Filter or search by metadata (country, data etc) 

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#2030]
The filter only allows for filtering for entity and document type. But when we put all our effort into meticulously categorizing the documents by country, date and a myriad of other properties, you also would want to be able to search for it. E.g. all cases relating to a certain industry sector, all cases from country X etc. How can this be done?

**Comment by txau** [comment]
@vasyugan filtering is supported by most, if not all the metadata properties. You'll find a "Use as filter" option in the metadata properties in document and entities templates.

There is also a "Default filter" option, meaning that filter will be shown even the user don't have that particular template selected.

The menu "Filters" in settings > filters is a whole different thing, and probably poorly named and misleading. That is optional and only used for re-arranging the way all the templates are shown on the top of the side panel. This allows to nest them in groups, order them in a particular way and exclude those you don't want to be displayed.

**Comment by vasyugan** [comment]
Thanks, yes! You helped me a lot. Would not have crossed my mind that I have to look there. This should all be documented then, because under search or filter I cannot find it.
