### ISSUE TITLE
how to enable https for security?

### ISSUE THREAD

**Issue by whisere** [huridocs/uwazi#2033]
I am wondering what is the configuration to enable https for Uwazi? Thanks!

**Comment by txau** [comment]
Closing since this is a duplicate: https://github.com/huridocs/uwazi/issues/1985

Short answer, currently you need to configure a proxy. Ideally Nginx.

**Comment by vasyugan** [comment]
Plus you have to close port 3000 for the outside world.

**Comment by whisere** [comment]
@vasyugan Thanks.
