### ISSUE TITLE
'conversion failed' for pdf document

### ISSUE THREAD

**Issue by whisere** [huridocs/uwazi#2035]
Hello, I tried to upload pdf documents but run into 'conversion failed' error
In the debug log:
{"message":"Upload Process for 5bc916172154864b821942c2","level":"debug"}
{"message":"Original name false","level":"debug"}
{"message":"File exists true","level":"debug"}
{"message":"Documents saved as uploaded for: 4A.pdf","level":"debug"}
2018-10-18T23:24:07.789Z [uwazi_db] undefined
{"message":"Starting conversion of: 4A.pdf","level":"debug"}
{"level":"debug"}

I also tried the pdfs in this link they all have the same problems too. 
https://github.com/huridocs/uwazi/issues/1031

Any idea? Thank you!

**Comment by whisere** [comment]
It is solved,
I did: yum install poppler 
but seems it needs:
yum install poppler-utils
Thanks!

**Comment by whisere** [comment]
can test with command pdftotext

**Comment by txau** [comment]
@whisere I think we assumed Poppler was installing poppler-utils as well. Probably I should update the documentation to reflect that.

**Comment by whisere** [comment]
@txau it works when I did 'brew install poppler' in Mac, but under redhat I need to do 'yum install poppler-utils'.  'yum install poppler' only didn't work, it may depend on the platform I guess.
