### ISSUE TITLE
Show Uwazi version on web interface

### ISSUE THREAD

**Issue by fititnt** [huridocs/uwazi#2041]
Similar to #2010, but now is on web interface for administrators.

---

This maybe is simple to implement, or maybe not. But one indication on web interface (that, in my opinion, could be only available to admins, or some sort of super admin, not for general public) could show the Uwazi version (based on last stable release, e.g. v1.3, v1.2, v1.1...).

Since (I suppose, I'm not sure on this) is possible to have "two" versions:
1. Code: one that code on disk think it is, possible to take from package.js file
2. Database: MongoDB data could still from an older version and it's data was not updated with a new release

One screen could show this, so, even if by default it does not alert one admin, at least could make simple to be aware of this. If the Uwazi does not update it's database without run something like `yarn migrate` and already does not show some warning if database was not updated with the latest version, this screen (or just a footer note on Uwazi version) could make it clear the version and avoid errors only when a feature is used.

**Comment by txau** [comment]
An end-point was added to check the version from the web interface at /api/version
