### ISSUE TITLE
validation error for password

### ISSUE THREAD

**Issue by whisere** [huridocs/uwazi#2044]
Hello, I was trying to create a new user but receive this error:
ValidationError: "password" is not allowed

Have tried different password, long text with number and symbol combination etc. Any idea?
Thanks!

**Comment by txau** [comment]
hello @whisere, this issue was recently fixed: https://github.com/huridocs/uwazi/issues/2027

Please update your Uwazi to the latest version: https://github.com/huridocs/uwazi/tree/master

**Comment by txau** [comment]
hello @whisere, this issue was recently fixed: https://github.com/huridocs/uwazi/issues/2027

Please update your Uwazi to the latest version: https://github.com/huridocs/uwazi/tree/master

**Comment by txau** [comment]
@whisere as you can see GitHub is also playing tricks on me =D

**Comment by whisere** [comment]
@txau Many thanks! It is issue about issue on GitHub : D
