### ISSUE TITLE
listen on port 3000 only on 127.0.0.1

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#2047]
Since the connection on port 3000 is unencrypted, uwazi/node should only listen on localhost, assuming that connections to the outside world are going through a reverse proxy.

**Comment by txau** [comment]
@vasyugan this is a matter of infrastructure configuration. In our case, the load balancer is in a different server connected via LAN with the Uwazi server. So we need Uwazi to listen on other addresses.
