### ISSUE TITLE
Separate new document when creating a connection to a paragraph

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#206]
There are a lot of glitches when a user creates a new connection to a paragraph with the open document animation (like scrolling both documents, open the second document if the user scrolled before creating the connection...).

We need to separate both viewers, so, when a user clicks on next button, we open a new clean document.

![step2](https://cloud.githubusercontent.com/assets/6364153/16694045/7b854aae-4538-11e6-8527-19c2563af81a.png)

**Comment by konzz** [comment]
Solved in #235
