### ISSUE TITLE
Feature request: Allow users to see translations of docs on the right sidebar

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#2070]
![image](https://user-images.githubusercontent.com/354426/48149731-d6afa680-e28a-11e8-807f-997b668cafe8.png)

**Comment by txau** [comment]
@kjantin looking at your screenshot I guess we need a field for hyperlinks.

**Comment by kjantin** [comment]
I'm going to close this issue since it's a duplicate of https://github.com/huridocs/uwazi/issues/2221
