### ISSUE TITLE
Slow typing in thesauri

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2071]
When creating a group and moving items around the interface responds delayed.

**Comment by konzz** [comment]
@txau didnt notice the delay, but noticed weird css in this form, could you check and update this issue if needed?

**Comment by txau** [comment]
I re-checked this issue in FF and Chrome (Linux), its still happening. I used the long thesaurus from our fixtures: http://localhost:3000/en/settings/dictionaries/edit/58ada34c299e826748545099

When attempting to type in a new item, the input is notably delayed, so probably we have a re-rendering problem.

**Comment by daneryl** [comment]
@txau merged, tested it and i can notice an improvement, but did not test it on linux.
