### ISSUE TITLE
Mapbox hardcoded user key

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#2075]
In the mapbox config file app/react/Map/style.json we have hardcoded a key that the OpenStreetmaps requires to request their api, this key is free but has his limitations, and if all instances use it, it may become a problem

**Comment by RafaPolit** [comment]
Discussed solution is to create a Settings -> Collection entry (like there are many others, ex. the mailer config).   If an API key is configured, used that one, if not, use the Uwazi default one (hardcoded in the code).

**Comment by mfacar** [comment]
@RafaPolit should the collection entry be managed like a password or like a plain text entry?

**Comment by RafaPolit** [comment]
The default for the map key will be stored on the mongo model, preventing the need for parsing the file on client and keeping the default in several places.

**Comment by mfacar** [comment]
Effectively, the default value set at the schema is not taking into account at the moment of saving the model. As a workaround, I'm setting the default at the get settings method, in this way the value is still stored at the database, and the default is returned if it is is not yet at the db. What do you think about this @RafaPolit?

**Comment by RafaPolit** [comment]
The default is not meant to work at the save level, but at the request level.  The question here is whether our use of `lean` is preventing the default to populate the key during a GET action.  Ideally we should not override the get method unless strictly neccessary.

**Comment by RafaPolit** [comment]
As explained here: https://stackoverflow.com/questions/35066362/do-mongoose-defaults-get-applied-to-existing-documents

Apparently LEAN is preventing the functionality we expected.  Yes, we need to figure out a workaround.  Maybe your approach of extending the GET works, can we see what you mean? Can you create a DRAFT PR so we can take a look at it?

**Comment by mfacar** [comment]
I've created the following draft pull request https://github.com/huridocs/uwazi/pull/2919, please can you check it?
