### ISSUE TITLE
Filtering by relationship metadata not working when updating the data via API

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2092]
When adding/updating data via the API, the aggregations for the filters by metadata don't get automatically updated and a manual reindex needs to be run in order to get the up to date aggregations.

**Comment by RafaPolit** [comment]
We probably should unify the api.  The problem is that now, all our client end-points use the bulk process... which probably has everything 'correctly' configured.

Yet we expose other API endpoints that work at the DB level, but do not index elastic.

We should unify all this so it only has to be addressed in one place.

**Comment by konzz** [comment]
@txau @RafaPolit I've check and there is only three end points to update an entity/document. Saving an entity or document call /api/documents or /api/entities and updating many at one call /api/entities/multipleupdate but all three work fine with the client that is basically "adding/updating data via the API"
Can we have more info on how those updates are being done? Are they using the models directly and not actually using the API?

**Comment by habbes** [comment]
@konzz @RafaPolit this behaviour has been observed when migrating data using the OE to Uwazi script. The script uses the Uwazi API to migrate documents. However, after the migration, the data doesn't seem to be indexed, and we have to manually run `yarn reindex` in order for the aggregations to be correct. I don't remember whether this happens in all the cases, but there's a particular instance for which this seems to always happen.

**Comment by txau** [comment]
Relationship's metadata as it is today is deprecated. It will be soon replaced by another solution (likely storing relationship metadata in intermediate nodes).
