### ISSUE TITLE
languages mixed up in translation function?

### ISSUE THREAD

**Issue by bertver** [huridocs/uwazi#2115]
just added Spanish as second language in https://janus.uwazi.io.

I translated term of user interface into Spanish, but it appears that Spanish translation is shown under English and English translation under Spanish. see screenshots
![uwazi-janus-translation-1](https://user-images.githubusercontent.com/11311296/50962223-0e74dd80-14ca-11e9-9449-9b59188636ef.png)
![uwazi-janus-translation-2](https://user-images.githubusercontent.com/11311296/50962224-0e74dd80-14ca-11e9-9647-0e1203f9e751.png)
![uwazi-janus-translation-3](https://user-images.githubusercontent.com/11311296/50962225-0f0d7400-14ca-11e9-9179-462124d06463.png)

**Comment by txau** [comment]
@bertver this is actually related to another misbehavior #2083.

So if you reload you browser the translations should be correct.
