### ISSUE TITLE
translation of user-generated content

### ISSUE THREAD

**Issue by bertver** [huridocs/uwazi#2116]
Using translation function in Uwazi instance https://janus.uwazi.io, I can only translate UI terms but not user-generated content (names and fields of entities, thesauri...)
![uwazi-janus-translation-contents-1](https://user-images.githubusercontent.com/11311296/50962454-90650680-14ca-11e9-92dc-60db9e5083e4.png)

**Comment by txau** [comment]
@bertver its not translatable in that particular view, but for instance for template names and field names, you can translate them in settings > translations. Or you can also activate the translation tool in library or when viewing an entity.

**Comment by vasyugan** [comment]
@txau  Actually it does not work: I can translate standard interface elements but not the contents of theauri.
![screenshot_2019-02-07 settings fpic](https://user-images.githubusercontent.com/3313208/52414508-d79fe080-2ae4-11e9-91e4-1d1b0b7238f8.png)

In settings > translations, it is not there, and in the actual library, the strings also don't get underline and I thus cannot translated them.
