### ISSUE TITLE
can't translate thesauri

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#2174]
There is no way to translate the contents of Thesauri, neither when viewing a document, nor in settings/thesauri nor settings/translations 

![screenshot_2019-02-07 settings fpic](https://user-images.githubusercontent.com/3313208/52417219-a4ad1b00-2aeb-11e9-8a62-e2558dc881ab.png)

**Comment by konzz** [comment]
Hi @vasyugan I tested the creation and translation of a thesauri and works fine for me, does it happen to you with all the thesauris?

**Comment by vasyugan** [comment]
> Hi @vasyugan I tested the creation and translation of a thesauri and works fine for me, does it happen to you with all the thesauris?

I have four of them, and neither is translatable. Just tested them all.

**Comment by konzz** [comment]
Hi, are you trying to translate them only with the inline translation optión? or also in the form that is in settings -> translations -> name of the thesauri?
I tried and I can create and translate thesaurus, is your code up to date?

**Comment by vasyugan** [comment]
I tried both and both don't work.
I am using the latest stable release. Should I git upgrade to the master branch?

**Comment by txau** [comment]
@vasyugan can you check the errors logs?

**Comment by vasyugan** [comment]
There are two log files, debug.log and error.log and both are last modified 15 February. So whatever is going wrong doesn't seem to make it into the logs, unfortunately.

**Comment by txau** [comment]
@vasyugan is this still happening? do you think is somewhat related to https://github.com/huridocs/uwazi/issues/2207?

**Comment by vasyugan** [comment]
It would have been surprising if it just went away... I have no way of knowing whether it might be related. The one message I see repeating itself over and over is

```
TypeError: Cannot read property '7' of undefined
    at Object.getRawPage (/home/node/uwazi/app/api/entities/entities.js:383:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
2019-03-14T13:38:22.591Z [uwazi_development] 
url: /api/entities/get_raw_page?sharedId=9sze2tqn8ka&pageNumber=7
query: {
 "sharedId": "9sze2tqn8ka",
 "pageNumber": "7"
}
```
But I don't have the slightest clue what this might be about.

**Comment by txau** [comment]
@konzz could this be related to? https://github.com/huridocs/uwazi/issues/2202

**Comment by konzz** [comment]
Maybe the error log was related to #2202, but I don't think that error is related to this issue.
@vasyugan can you create new thesaurus and check if you can translate them? If you can translate them I guess there was a problem when creating those four thesauri and the translation was not generated in the database.

**Comment by vasyugan** [comment]
With the latest version, it seems thesauri can now be translated from settings->translations. Thanks!
