### ISSUE TITLE
Reference position within document

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#2177]
It would be great if one could reference a particular place within a document. We are currently creating a database on FPIC protocols (FPIC stands for [Free, Prior and Informed Consent](https://en.wikipedia.org/wiki/Free,_prior_and_informed_consent), a key right of indigenous peoples), and to make the database meaningful we need the ability not only to reference a document because it mentions X but also to reference the place where it does so in order for the user to be able to see what it actually says about X. E.g: One possible document property will be: "Contains provision on how to amend the protocol" which would be a simple yes/no, but if the answer is yes, then it would be great if we could directly link to the place within the document where this provision is.

**Comment by txau** [comment]
@vasyugan Uwazi supports text references, I guess this is same thing you are asking for? https://github.com/huridocs/uwazi/wiki/Create-references

**Comment by vasyugan** [comment]
Thanks, I have to think about whether it is doable like this. Maybe I would have to define the key terms as entities and from these entities reference the paragraphs where these terms are defined / dealt with in the individual documents. This is maybe not quite how I envisaged it, but maybe it is a way.

**Comment by txau** [comment]
@vasyugan if I'm following you, what is missing is the ability to reference a piece of text in a document, from an entity (which has no associated document). Actually this is only doable the other way around, referencing the entity from the document text. Clearly this is a flaw in the user workflow =/

Let's see if we can address it soon.

**Comment by vasyugan** [comment]
Yes, maybe it helps if I explain a use case: The database should e.g. give clarity about which protocols contain explicit definitions of key terms, such as "free", "prior", "informed" and "consent"  or whether they specify what triggers their application or whether they make any provisions on how they are changed/amended. Here, a possible solution would be to create an entity for the given term and from there, create references to paragraphs in our documents, where they are being defined/elaborated on.

**Comment by txau** [comment]
@vasyugan that would work. The result would be a list of text snippets describing the concept in the connections panel for that item.

Still, the connections need to be made from the text documents, they can't be done from the concept itself. So that is an improvement point for us to think about.

**Comment by vasyugan** [comment]
OK, will try as you advise. Thanks!!
