### ISSUE TITLE
embedding Wikipedia content

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#2196]
It would be awesome if we could embed Wikipedia content to entities, primarily the featured image (if any) and the excerpt of the respective article. Musicbrainz does the latter for artists: e.g. [Sandy Denny](https://musicbrainz.org/artist/08d86aab-8e58-4d9f-90e4-cfc3d2f0b867) if you add a Wikipedia link. 
In the Database I am currently working on, which is about indigenous peoples and Free Prior Informed Consent, we have an entity for each ethnic group, and it would be great if those entities could be augmented with Wikipedia content instead of having to add images and description manually.

**Comment by txau** [comment]
@vasyugan thanks so much for this idea. In fact, it would be great to have other automations for embedding contents such as tweets. We've been thinking about maybe integrating Uwazi with verification tools such as https://meedan.com/en/check/

**Comment by txau** [comment]
@vasyugan just to give you a heads up on this there is an integration for Uwazi+Digital Evidence Vault: https://chrome.google.com/webstore/detail/open-digital-evidence-vau/hdjibbnkingjmhiobjadmoeppgdnapej

Is not exactly what you are requesting, but maybe it could help in some cases.
