### ISSUE TITLE
geolocation pin point not getting centered when selecting a card

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2199]
To reproduce:

1. Select a card with a geolocation property in library. The side panel opens showing the map and the pin point.
2. Select another card with the same geolocation property. The side panel shows the new information and the pin point gets updated, but the map is not centered around the pin point and the user gets and empty map.

**Comment by RafaPolit** [comment]
Noticed this myself.  I'll fix it in a different PR so that @konzz can integrate his part of the inheritance.

**Comment by konzz** [comment]
@RafaPolit I can't replicate this, was fixed in the changes to the map?

**Comment by txau** [comment]
@konzz I just tried it and looks like its working properly now.
