### ISSUE TITLE
Validation errors

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2201]
![screenshot 4](https://user-images.githubusercontent.com/489831/53429114-48536200-39ec-11e9-8430-146b454501c4.png)
![screenshot 1](https://user-images.githubusercontent.com/489831/53429115-48ebf880-39ec-11e9-9816-0c612bc45a98.png)

**Comment by RafaPolit** [comment]
I am getting this errors as well when trying to publish documents:
Using Uwazi Fixtures:
- Upload a File
- Assign Order of the Pressident without filling any other field, save the document
- Try to publish
![screenshot from 2019-02-26 14-10-05](https://user-images.githubusercontent.com/4309019/53439661-8b9fd780-39d0-11e9-80d2-9212f1664723.png)

**Comment by txau** [comment]
Related https://github.com/huridocs/uwazi/issues/2201
