### ISSUE TITLE
New thesaurus created but not listed, name conflict?

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#2204]
I have created an entity type "Definition" and now I have also tried to create a thesaurus with the same name. On saving, the thesaurus does not appear in the list and is not available for select or multiselect properties. So I tried to create it again, only to be told that it already exists. 
I next created the thesaurus under a different name and lo and behold it did appear. So there seems to be some sort of conflict when you create entity types and thesauri with the same name.

**Comment by txau** [comment]
Duplicate: https://github.com/huridocs/uwazi/issues/2207
