### ISSUE TITLE
Unable to get to the "edit" screen of an entity from the relationships display

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#2205]
When I go to look at the people (entity) related to an "event" in this Uwazi instance, https://hr-reports.uwazi.io/en/entity/l80czdj4utf I want to be able to "open" one of the person entities so that I can edit it.....but I can't find anywhere to click to get there. When I click on "view" I only see the sidebar data and I don't see any option to edit. Am I doing something wrong?

![image](https://user-images.githubusercontent.com/354426/53593915-c0926280-3b67-11e9-9377-edebdbe847ec.png)

**Comment by RafaPolit** [comment]
It’s a bit confusing, I agree.

The fact is that you are within the ‘relationships’ view of an entity.  If you click on view on a different entity, you will move that new entity’ relationships view.

This allow for you to navigate through connections quickly.

If you want to edit a particular entity, you have to go to it (view), and then shift to the ‘info’ button (i icon) on the top right section, above the side panel.

That will take you out of relationships view and into info view where you can edit an entity.

**Comment by txau** [comment]
@kjantin this has been proposed recently as "Be able to add/edit entities from the relationships view".

**Comment by kjantin** [comment]
I ran into this unexpected behavior again while working on creating relationships in another Uwazi instance. What was frustrating, was that I was unable to even "view" an entity that is displayed in the relationship tab. In the gif below, I am looking at the things related to a person, and when I click on "view" for the Act that it's related to, it puts the Act on the left side, as it is intended. But then there is no way for me to actually "view" this entity and its properties - not even on the right side panel (there is no way for me to get to the "info" button). 

http://g.recordit.co/PFwk3jlAAc.gif

I propose we save the action "view" to bring the user to a place where they can see the metadata of that entity. 
And for the action to switch around the display of the relationships - this needs a different name.

**Comment by txau** [comment]
@kjantin I guess the problem gets solved by being able to just edit properties in that same screen. Even better, being able to create new entities connected to a particular entity in the relationships tree.

You can view and edit the metadata by clicking on the metadata icon (circle with a "i" inside). But of course this means more clicks and its frustrating.

**Comment by txau** [comment]
Closing for now since this is to be addressed as a new functionality rather than a bug.
