### ISSUE TITLE
"duplicated name" error trying to save a changed thesaurus

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#2207]
I just edited some items in a thesaurus, and when I try to save it, I get a red alert saying "duplicate name" However, there are no current entries in the log files, so I have no idea what is going wrong here.

**Comment by konzz** [comment]
That means that there is another thesaurus with the same now, I've detected that now is also checking name duplicity with templates, and that's incorrect, is it your case?

**Comment by txau** [comment]
related: https://github.com/huridocs/uwazi/issues/2204

**Comment by vasyugan** [comment]
The clash here seems to be between entity names and thesauri entries

**Comment by konzz** [comment]
Hi @vasyugan we are considering if that's a bug or should keep working that way. We don't want templates to have the same name, to avoid confusion, and maybe for the same reason templates and thesaurus should not share names. We are discussing it.

**Comment by daneryl** [comment]
fixed by allowing templates and thesaurus to have the same name

**Comment by vasyugan** [comment]
> Hi @vasyugan we are considering if that's a bug or should keep working that way. We don't want templates to have the same name, to avoid confusion, and maybe for the same reason templates and thesaurus should not share names. We are discussing it.

If you want to keep it this way, please add a warning, because now, the item just silently disappears and one has no idea why
