### ISSUE TITLE
Error when navigating to homepage

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2209]
1. Open the instance TGEU
2. Navigate to countries > Hungary
3. Navigate to home

Tosses a JS error and you get a blank page.
![screenshot from 2019-03-04 12-42-33](https://user-images.githubusercontent.com/489831/53731435-035f7d80-3e7b-11e9-9a40-a8aff7a11280.png)

**Comment by daneryl** [comment]
@txau i dont think this is happening anymore ? confirm ?
