### ISSUE TITLE
Error with bluk edit on blank thesauri

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2216]
After a "yarn blank-state":
1. Go to uploads and upload a bunch of files
2. Bulk select them and hit the edit button

![screenshot from 2019-03-06 18-35-31](https://user-images.githubusercontent.com/489831/53901237-cb089c80-403e-11e9-93a2-ff7cad195239.png)

If an empty thesauri is created the bug does not occur.

**Comment by habbes** [comment]
I've not been able to reproduce the issue. Should the templates of the uploaded files have any special condition? Like have select/multiselect fields? How is that error related to empty thesauri? And by empty thesauri you mean a thesaurus list without any items or a thesaurus select field without a value?

**Comment by txau** [comment]
@habbes sorry about the bad explanation. As stated: "After a "yarn blank-state"

So the answer to your questions is whatever the blank state is doing now. But essentially, when we have no thesauri at all.

This is a rather rare state to be in Uwazi, but its the blank state, so users may run into this error.

(please note that thesauri is the plural of thesaurus, so by empty thesauri I meant "when there is not even a single thesaurus created in Uwazi, even if its a thesaurus with no items at all").

**Comment by habbes** [comment]
Thanks @txau. I had missed yarn blank-state step. I was also creating entities then uploading files to the entities, I had not realised I could simply upload files directly.

However I'm still not getting the error. Here's what I've tried:

- yarn blank-state and then run Uwazi
- go to uploads, uploaded a couple of pdf files
- bulk selected the files (I assume this refers to shift + select)
- click the edit button
not error occurs, a form opens up on the sidepanel where I can set the metadata, I then hit the save button, and I get a success message.

The console also only has CORS errors related to loading font files, but there's no error mentioning thesauri or Uwazi does not crash.

**Comment by txau** [comment]
@habbes you are right. I couldn't replicate the bug again. Maybe some of the recent changes to thesauri fixed this. Closing for now.
