### ISSUE TITLE
Discuss: Is it worth it to translate the template names on SETTINGS?

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2219]
From the process of creating RTL view, there was an issue brought up:

The language that you create the template in is 'forever' that template's name in settings.  You cannot translate the Template list in settings. If someone creates them in Arabic, for instance, or Chinese, they will show in non-latin characters for everyone in settings, sometimes making it difficult to read.

Perhaps a solution is to display the original name alongside with the translation to the current selected language?  Maybe there is just a protocol that, if several people from different languages are going to access your instance, that you instruct everyone to create them in English?

This is not critical, but would be interesting to get addressed.

**Comment by txau** [comment]
somewhat related to this: https://github.com/huridocs/uwazi/issues/1552

**Comment by MatelSow** [comment]
Adding to the discussion here after realising earlier created issue already exists

**Use case**: I have created entities in a specific languages (ex: French). I have provided the English translations of those entities under the translations tab in settings. When I switch to the English page, I would like to see the entity titles + properties translated into English (just like everything else on the instance).

![1](https://user-images.githubusercontent.com/56391759/86578541-3e485880-bf7c-11ea-9c06-6f73eaa0a0e1.png)

**Comment by RafaPolit** [comment]
The decision is to include BOTH values: 
- We need to keep the "true" value that is the same across all languages
- We can show next to it, or in parenthesis, or whatever UI solution we decide, the TRANSLATED value for that term on the current language.

The idea is to disambiguate the fact that the user SHOULD NOT change the UI language in order to translate this value.
