### ISSUE TITLE
Display what other language versions of a document are available

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2221]
Since we developed a 'fallback' document system, its not always clear if there are different versions of a particular document.

There are times when you want to see / know if the instance has a particular language of a particular document without actually changing the UI language.

For that, it would be useful to hold, underneath the 'document' section of Document View, a list of what 'other' language versions of the same PDF are available and have them ready for download.

As a nice to have, you could click on a particular language version and render that PDFs version in the viewer without actually changing the UI language.

**Comment by txau** [comment]
More over, along with this we should tweak the way Uwazi is presenting the documents so that users can see the document in one language regardless of the UI interface.

**Comment by txau** [comment]
Same as: https://github.com/huridocs/uwazi/issues/2070

**Comment by txau** [comment]
Fixed in #2070
