### ISSUE TITLE
Better error reporting on wrong file format

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2226]
When uploading a malformed PDF or if the file gets wrongly truncated during upload (ie, due to a socket error), the error reported is just "Undefined". Improve this messaging.

**Comment by habbes** [comment]
@txau how can I reproduce this error?

I've tried disconnecting the network or server midway through an upload (using Chrome dev tools), and no error message was displayed. The network tab however shows that the request failed.

I tried disconnecting the server midway through an upload, and the error displayed was "Lost connection to the server, your changes may be lost"

**Comment by txau** [comment]
@habbes just create a malformed file by renaming something that is not a PDF to .pdf.

**Comment by habbes** [comment]
@txau, thanks, don't know why I didn't think of that.

**Comment by habbes** [comment]
@txau I've tried that with an image and video. The document gets uploaded fine, but after the upload, it displays the following error on the card "Conversion failed".

**Comment by txau** [comment]
@habbes you'll see the error message in the console or in the error log.
