### ISSUE TITLE
Only one browser at a time can receive real-time socket updates

### ISSUE THREAD

**Issue by habbes** [huridocs/uwazi#2229]
There's a bug in the socketio middleware that causes only one browser (technically only one cookie session id) to receive notifications.

### How to reproduce
This bug is easy to reproduce when using semantic search:
- Open two browsers
- Start a semantic search
- Only one of the browsers will display real-time progress of the search

If you refresh the browser that's not receiving the updates before the search ends, then this browser will start getting the updates and the other browser will stop receiving the updates.

Upon closer inspection of received updates (e.g. using log statements), it is revealed that the browser that receives the updates receives the updates notifications meant for the other browsers i.e. if you have two browsers open, one browser will receive duplicate updates while the other receives none.

This problem likely also affects updates from document uploads and other places where socketio is used.

**Comment by habbes** [comment]
### What I think is the source of the bug

Each request goest through the socketio middleware, which attaches a `getCurrentSessionSockets` method to the `req.io` object. This method returns all current sockets that have the same session id as the request. And notification is sent to these sockets using `req.io.getCurrentSessionSockets().emit(event, payload)`.

The problem here is that the method is attached to `req.io`. `io` is the instance of the socketio server, it's a single object shared by all requests.

Let's assume some request `req1` arrives. It will go through the middleware and will get the method attached to `req1.io`. At this point when you call `req.io.getCurrentSessionSockets()`, you will get all the sockets that match `req1`'s session.

Now comes a second request `req2`. It goes through the same middleware and a new `getCurrentSessionSockets()` method is generated for it, this method returns all sockets matching `req2`'s session. This method is attached to `req2.io`. But `req1.io` and `req2.io` are the exact same object. So `req2`'s method replaces `req1`'s method. Now when you call either `req2.io.getCurrentSessionSockets()` or `req1.io.getCurrentSessionSockets()`, you will get all the sockets that belong to `req2`.  Therefore, if you want to update all clients and call both `req1.io.getCurrentSessionSockets().emit()` and `req2.io.getCurrentSessionSockets().emit()`, it will send the event to `req2`'s sockets twice (hence the duplicate events when running semantic search).

**Comment by habbes** [comment]
### Proposed solution

Based on my understanding of the problem, I think it can be solved easily by attaching the method to the request itself, i.e. `req.getCurrentSessionSockets()` instead of `req.io.getCurrentSessionSockets()`.

This way each request will have its own method that returns sockets based on its own session and won't be replaced by new requests.

I've tested this locally and it seems to solve the problem for semantic search updates, I've tried it on other scenarios.

**Comment by habbes** [comment]
It appears that this bug does not affect other parts of the code as much outside of semantic search. In most cases, `req.io.sockets.emit` is used, which broadcasts a message to all connected clients regardless of their session cookie and regardless of the actual request object. These cases are not affected by the bug.

The only other place I found where this bug could have an impact is during document upload. And in this case, it's also difficult to reproduce as it would require two clients to be on the uploads page trying to upload documents at the same time. One way to see the issue is to open two browsers and visit the uploads page, and then in each browser (almost) simultaneously upload a large number of documents (maybe 20+). After a while, when all the documents finish uploading, you'll notice that in one browser they have documents are marked as complete, but in the other browser the documents will indefinitely be in the "processing" state until you reload the page. This happens because that latter browser did not receive all the updates as they were sent to the other browser.

**Comment by txau** [comment]
@habbes if you need to test the conflict you can activate bandwidth throttling in you developer tools in the browser. Anyway, if the fix is working maybe there is no need to invest more time into this.

Glad to know the side effects were rather small.

**Comment by habbes** [comment]
@txau, I didn't think of that, thanks. But I managed to achieve something similar by temporarily adding a `setTimeout` delay of a few seconds before completing the document processing.

**Comment by txau** [comment]
@habbes great. So the PR is ready for QA?

**Comment by habbes** [comment]
Yes, it is.

**Comment by txau** [comment]
@habbes can we close this issue?

**Comment by habbes** [comment]
Yes, I think the PR was merged.
