### ISSUE TITLE
Fix migration system: require used in the migrator prevents multiple exports

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2232]
The migrator uses a require to include migration indexes.  If the index.js file of a migration has exports other than the default, it changes the structure of the included file and the migration is not registered as a valid migration.

There needs to be a solution to prevent such errors:
- Change the migration so that it exports (by agreement) a named object, such as .migration
- Other options?
- Just convene that we cannot export anything but the default object (not ideal)

**Comment by daneryl** [comment]
> Just convene that we cannot export anything but the default object (not ideal)

has this been a problem since ? i think its working fine like this, should i close ?

**Comment by txau** [comment]
not a problem
