### ISSUE TITLE
"validation error" when trying to save new filter group

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#2236]
I just created and populated a new filter group and when I tried to save it, I get the following rather cryptic message:

ValidationError: child \"filters\" fails because [\"filters\" at position 1 fails because [\"container\" is not allowed, \"index\" is not allowed]]","level":"debug"}

**Comment by vasyugan** [comment]
It appears to happen when dragging filter groups around and saving the result.

**Comment by txau** [comment]
Great error message =) 

Moving this to sprint.

**Comment by txau** [comment]
@vasyugan I've been playing with the filters during 15 minutes trying all sorts of combinations without luck getting the error. Is there any other hint?

This could be related to: https://github.com/huridocs/uwazi/issues/2229

**Comment by vasyugan** [comment]
The debug log is here: https://gist.github.com/vasyugan/8ae17ebf93cd2a98dd80908d5536b545

**Comment by txau** [comment]
@vasyugan Let's hold the resolution of this one until you have the latest release.

**Comment by txau** [comment]
@vasyugan feel free to try v1.5: https://github.com/huridocs/uwazi/releases/tag/v1.5

**Comment by txau** [comment]
@vasyugan please let me know if you had the chance to upgrade. Is the bug still there?

**Comment by vasyugan** [comment]
I just upgraded to 1.5. Unfortunately this hasn't improved things.
![Screenshot_2019-03-26 Settings • FPIC](https://user-images.githubusercontent.com/3313208/55000162-34daed00-4fd2-11e9-9723-5de213ad5587.png)

**Comment by vasyugan** [comment]
oops sorry, wrong bug, this one is indeed fixed now. Thanks!

**Comment by txau** [comment]
@vasyugan awesome!
