### ISSUE TITLE
"view" should take one to the referenced paragraph, not just the document

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#2237]
Here is a reference I created:
![Screenshot_2019-03-14 Free • FPIC](https://user-images.githubusercontent.com/3313208/54374222-491f0180-4644-11e9-8a74-a647dd67ea73.png)
When I click "view", I would expect to be taken to the referenced paragraph, but what I end up is this:
![Screenshot_2019-03-14 PROTOCOLO CP Y CPLI DEL PUEBLO NASA CERRO TIJERAS • Page 1 • FPIC](https://user-images.githubusercontent.com/3313208/54374307-7a97cd00-4644-11e9-9306-d762f3879841.png)
So, that's the beginning of the document, not the referenced paragraph. That's quite impractical.

**Comment by txau** [comment]
I agree. Still,I think we need to come up with a better UI for text references, including that particular screen.

**Comment by txau** [comment]
Same as: https://github.com/huridocs/uwazi/issues/687
