### ISSUE TITLE
Several bugs related to relationships in an entity

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2249]
Several bugs with this entity:

https://sidh.cejil.org/en/entity/xnac33w095r

- It doesn't load the timeline
- When logged in, it tosses an error:

url: /api/references/group_by_connection/xnac33w095r 
TypeError: Cannot read property 'template' of undefined

**Comment by RafaPolit** [comment]
I have repeatedly insisted that we need to assign the default template to both processes of uploading documents: on entity creation (which is now happening correctly) and on document upload. 

We would free dozens of bugs and complex logic with this incredibly simple step.

**Comment by RafaPolit** [comment]
Proposed on #2206

**Comment by txau** [comment]
@RafaPolit totally agree

**Comment by txau** [comment]
- [ ] Purge connection to non-existent entities before sending to the client
- [ ] Toss a server error for logging purposes when this situation happens
