### ISSUE TITLE
Redesign metadata section

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#225]

**Comment by danicatalan** [comment]
![metadata-admin](https://cloud.githubusercontent.com/assets/6364153/17149822/41742572-536d-11e6-9fc0-b53430fd6f35.png)

**Comment by danicatalan** [comment]
**Relationship (edit mode)**
![screenshot 2016-07-26 20 18 42](https://cloud.githubusercontent.com/assets/6364153/17150056/37558d96-536e-11e6-9ca2-e520af33fe09.png)

**Comment by danicatalan** [comment]
![screenshot 2016-07-27 00 10 46](https://cloud.githubusercontent.com/assets/6364153/17157277/9ad0d8c4-538e-11e6-95bf-fbe46647bae8.png)
**Relationships (edit mode)**

**Comment by danicatalan** [comment]
![screenshot 2016-07-27 00 43 36](https://cloud.githubusercontent.com/assets/6364153/17158028/bf49d624-5393-11e6-971b-f130454e09b5.png)
![screenshot 2016-07-27 00 47 14](https://cloud.githubusercontent.com/assets/6364153/17158029/bf4a0d38-5393-11e6-85d2-bbee25cff843.png)
**Thesauris (UI states)**

**Comment by danicatalan** [comment]
![screenshot 2016-07-27 14 49 31](https://cloud.githubusercontent.com/assets/6364153/17175706/5e5e26aa-5409-11e6-95f7-bbfe5fe5da5e.png)
**Document type (edit mode)**

**Comment by danicatalan** [comment]
![screenshot 2016-07-27 16 08 40](https://cloud.githubusercontent.com/assets/6364153/17178105/6a204814-5414-11e6-9a8c-77a1cf3a0c62.png)
**Document type (cleaner edit mode, needs improvement on "Use as filter"**

**Comment by danicatalan** [comment]
Hi @konzz,

We are gonna implement the first part of this task to development: **move all sections to settings**.

Here are the screenshots for current sections on dev. The code is in `225-metadata` branch.

![screenshot 2016-07-29 16 02 10](https://cloud.githubusercontent.com/assets/6364153/17250936/cbd24880-55a6-11e6-858b-6ddbc43340b3.png)
![screenshot 2016-07-29 16 03 42](https://cloud.githubusercontent.com/assets/6364153/17250934/cbcc65aa-55a6-11e6-9fc5-63195734128b.png)
![screenshot 2016-07-29 16 05 08](https://cloud.githubusercontent.com/assets/6364153/17250935/cbd1b6b8-55a6-11e6-9f6b-1429dd2a34af.png)

Let me know if you have any doubt!

**Comment by danicatalan** [comment]
This is for **design QA** @txau:
![screenshot 2016-07-29 17 57 29](https://cloud.githubusercontent.com/assets/6364153/17254729/4d6dd878-55b6-11e6-976c-e8dd9523380f.png)
![screenshot 2016-07-29 17 59 03](https://cloud.githubusercontent.com/assets/6364153/17254727/4d6d80bc-55b6-11e6-91fc-c0d446123477.png)
![screenshot 2016-07-29 17 59 17](https://cloud.githubusercontent.com/assets/6364153/17254728/4d6da7cc-55b6-11e6-84e7-1cc57ce30d37.png)
![screenshot 2016-07-29 17 59 29](https://cloud.githubusercontent.com/assets/6364153/17254730/4d6f5310-55b6-11e6-97ba-a20ded2ae74c.png)

**Comment by danicatalan** [comment]
Blank states @txau 

![screenshot 2016-07-29 18 07 08](https://cloud.githubusercontent.com/assets/6364153/17255059/d2ca8c40-55b7-11e6-8039-187104756d67.png)
![screenshot 2016-07-29 18 07 56](https://cloud.githubusercontent.com/assets/6364153/17255058/d2c8ae48-55b7-11e6-991b-f2f5deb00420.png)
![screenshot 2016-07-29 18 10 02](https://cloud.githubusercontent.com/assets/6364153/17255057/d2c88d8c-55b7-11e6-8e6e-3a59a44ee4f9.png)

**Comment by danicatalan** [comment]
@konzz this is updated on https://github.com/huridocs/uwazi/tree/225-metadata-editor

You can continue here or close this one and create another for implement this views. Let me know if you have any doubt!

**Comment by konzz** [comment]
solved in #275
