### ISSUE TITLE
add web link property / relationship to templates or render http(s) links automatically

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#2250]
many entities, e.g. courts or NGOs  have their web sites, also, there may be canonical locations for some of the archives documents, e.g. court rulings, UN documents. For now, I can use text fields to enter URLs, but they are not automatically rendered clickable. Therefore  Uwazi should either by default automatically render http(s) links or a special field type should be added, whose contents are rendered as links

**Comment by txau** [comment]
@vasyugan there is a "Link" field type =)

**Comment by vasyugan** [comment]
Is there? Can you tell me which one in the attached screenshot? Because I cannot find it. 

![Screenshot_2019-03-19 Settings • FPIC](https://user-images.githubusercontent.com/3313208/54601596-b3b6af80-4a3f-11e9-9f18-ed1a26b6cc4a.png)

**Comment by txau** [comment]
@vasyugan weird! are you running the latest code? because its right there, between Rich Text and Image: 

![Screenshot from 2019-03-19 12-11-10](https://user-images.githubusercontent.com/489831/54601765-2de73400-4a40-11e9-81ad-6d5e69cfb027.png)

Could it be a browser cache issue?

**Comment by vasyugan** [comment]
I am running the latest released code. Is it in master?

**Comment by vasyugan** [comment]
Tried with a different browser. No cache issue. How could it? Has this field type been added recently? Is it still in master only?

**Comment by txau** [comment]
The field is merged into master and it was developed recently: https://github.com/huridocs/uwazi/issues/2088

**Comment by vasyugan** [comment]
ok, then I'll wait for the next release, because downgrading from master to a release version at a later point might cause issues, I guess.

**Comment by txau** [comment]
ok, I'm working on the release notes already, so coming soon!

**Comment by txau** [comment]
@vasyugan BTW last merge to master was 7 days ago. We keep master up to date regardless of the official releases. So you can go ahead and upgrade, since this is the version running in our production servers at the moment.
