### ISSUE TITLE
New document type does not appear in filter

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#2251]
I have created a new document type "court ruling", put a document into  this category and published it, yet it does not appear alongside the other document types in the filter, even though the document is published and can be found through searching. It is the first one in the screenshot. Unfortunately, the background of the label is white, so the text "court ruling" is not legible. However, you can see that in the right pane, under "Filters", where it says "Type of document", there should be another checkbox labelled "Court ruling", yet there is not. I suspected that this is an indexing issue, so I ran yarn reindex, yet to no avail.
![Screenshot_2019-03-19 Library • FPIC](https://user-images.githubusercontent.com/3313208/54604010-ff6c5780-4a45-11e9-8b66-55942b7f8526.png)

**Comment by txau** [comment]
@vasyugan we will try to address the label coloring as soon as possible!

Regarding the other feedback, I guess you need to add the new document type to the group "Type of document" in settings > filters.

**Comment by vasyugan** [comment]
Sorry, my bad! I forgot that the filters are maintained manually.
