### ISSUE TITLE
Possible issue when saving from the Library side panel which sends ELASTICSEARCH data

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2253]
I think we have a conceptual error regarding saving procedures in the Library:

- The Library gets its data from Elastic Search to create the cards, but it loads all the entity's info to populate the side panel when a card is clicked as well.
- When one clicks a card, one is still seeing the Elastic Search data in the side panel.
- When one clicks on EDIT, it is the Elastic Search data that is loaded into the forms, AND NOT the Database data.
- When you save that form, you are sending Elastic Search data into the Database instead of the original database content.

If, for whatever reason, something failed in an Elastic indexation, we are corrupting the Database data with the incomplete / corrupted Elastic data.

On the other hand, if we ever want to store slightly different data in Elastic than the one in the DB, we have an issue.  We may want auto-generated fields (like inheritances), or post-processed fields, etc.  This may cause an issue.

I think it is desirable to have the side panel show the Elastic data, but when the user clicks on EDIT I strongly believe we should load the DB data to ensure there are no inconsistencies.  This reduces the probability of the user sending old data from an old query into an entity until we have some form of version control or optimistic offline lock.

What do you guys think @txau @daneryl @konzz

**Comment by RafaPolit** [comment]
I'm escalating this issue to critical.  The problem is that, by fetching the data from the STORE (populated with Elasticsearch data), if you manipulate entities from the library, you can do things like:
- Delete entity A that has been selected as a relationship to entity B
- Edit entity B without reloading any data, and save.

At this point, you have sent the connection to entity A (which no longer exists).

With this procedure you could be:
- Sending obsolete data for the entity that has been overridden by a different save
- Sending thesauri or entity values that are no longer present in the DB
- Sending template structure that has changed

Editing a document should fetch new data and bring that directly from the DB.  Ideally, thesauris and template data should be updated (this probably already happens via sockets, at least for templates, should also happen for thesauris).

**Comment by konzz** [comment]
This can happen with 2 users working at the same time, refresh data before editing helps, but still does not prevent this from happening.

I agree with the part of what happens if we want different data in the same property for elastic and for mongo. That could be an issue yes, but we dont have it now.

And to really avoid creating ghost relationships we need to validate them in the backend.

**Comment by daneryl** [comment]
@RafaPolit i agree reloading entity data for the form will help a lot, we should do it, and as a separate issue we have #2241 to avoid conflicts between multiple users, should i work on this @txau ?

**Comment by txau** [comment]
@daneryl ok
