### ISSUE TITLE
"date added" property should be delesectable for cards

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#2256]
As requested in #978, we should have the ability to hide "date added" from cards, where don't want it to be there. I have got a number of entities, where "date added" looks strange, because these are entities like ethnic groups, organisations, institutions, definitions etc. For documents, date added to the library might make sense, but for an entry about an organisation which was founded in 1958, an indigenous group which has been around for centuries or a definition of a term, which has no date when it was first established, this makes no sense. It is rather irritating.

**Comment by txau** [comment]
@vasyugan definitely. At the same time, "date added" appears when there is no other "priority sorting" selected. Try configuring ie. Title as the priority sorting and date added will not appear as default in cards/sorting, but only if users explicitly select it.

**Comment by kjantin** [comment]
Maybe an option to not publish the 'date published' on the entity, but the property can still remain on the backend?
