### ISSUE TITLE
Duplicating entities bottleneck when adding a language.

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#2260]
In the process of adding a language and duplicating entities, thumbnails are generated per entity, the process wirks in batches but does not wait till the thumbnails are generated to call the next batch. Check the line below.

https://github.com/huridocs/uwazi/blob/0fb4c56e5dc2e657ced05e81cb21ae60543ba322/app/api/entities/entities.js#L498

**Comment by RafaPolit** [comment]
Indeed this was launching hundreds of processes.

We should never create a 'floating' promise that responds to no one.  All promises should be waited.

**Comment by txau** [comment]
Fixed
