### ISSUE TITLE
Elastic search mapping conflict when reusing property names.

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#2261]
Deleting a property and reusing the name for a different type of data, for example, deleting a text field named "date" and then adding a date-range field named date provokes an indexation error since the value has changed from text to object.

To prevent this we can suffix all property names with the type of property: date_text date_daterange. The same implementation is used in geolocation fields to properly map them in Elastic.

**Comment by RafaPolit** [comment]
A good approach could be: #2971

**Comment by txau** [comment]
Getting fixed in #3090
