### ISSUE TITLE
Edit dialogue shows wrong location on map

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#2269]
Here is a screenshot of an entity with geolocation in view mode:
![Screenshot_2019-03-26 Argentinian National Ombudsman • FPIC](https://user-images.githubusercontent.com/3313208/55001768-9f415c80-4fd5-11e9-9fed-c55be3675fa0.png)

When I switch to edit, the map display does not conform to the already existing geodata:
This is a minor annoyance, but it is irritating.
![Screenshot_2019-03-26 Argentinian National Ombudsman • FPIC(1)](https://user-images.githubusercontent.com/3313208/55001894-df084400-4fd5-11e9-9cce-be76edd765dc.png)

**Comment by RafaPolit** [comment]
Confirmed.  Steps to reproduce:
- Asign an entity a geolocation point
- Go into entity view, the view center on the marker
- Switch to edit -> the marker is positioned, but the view is not recentered

For this to be visible, the point needs to be outside the Europe area where the map automatically centers itself.
