### ISSUE TITLE
When editing / creating an entity, relationship fields pointing to templates that have no entities gives no feedback

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2270]
When editing or creating an entity or document for a template that has a relationship field pointing to a particular type of template... if that template has no valid entities assigned, the form shows the label and no options to select, nor any feedback that there are no entities of that type to select from.  Its confusing.

Provide feedback that 'no entities of type X found'.

**Comment by habbes** [comment]
This also appear to happen with empty thesauri lists.
