### ISSUE TITLE
Be able to select the same template as target for a relationship field

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2271]
If I am configuring template A, I could potentially have a relationship field that binds a relationship to entities of the same template.

For instance, if I have a template called "Person of interest", I could have two people that have a connection between them: one a victim, one a perpetrator, or configure them as accomplices.

But I cannot select 'myself' as the target template of a relationship metadata field.

**Comment by kjantin** [comment]
A few more use cases:

I have a template called "Person" and I want to reflect familial relationships between people in the database: father, mother, brother, sister. But I cannot select the "Person" template for these relationships.

I have a template called "Person" and I want to reflect the hierarchy/relationships/chain of command between people in an armed group.

**Comment by kjantin** [comment]
A workaround is to separate the types of Persons.

**Comment by habbes** [comment]
@RafaPolit 
Should we allow an entity to have a relationship with itself.

**Comment by txau** [comment]
> @RafaPolit
> Should we allow an entity to have a relationship with itself.

Conceptually speaking, this seems wrong to me. I would say no, but there may be use cases that I cannot think of?

**Comment by habbes** [comment]
@txau alright. Let me omit it for now.

Regarding potential use-cases, maybe in the case of attacks inflicted on self (e.g. suicide), an individual could be considered both the perpetrator and victim?

**Comment by txau** [comment]
@habbes just go for the less possible effort implementation. So do not add code to prevent entities from having relationships to themselves, nor to allow it. Just leave it as Uwazi's default architecture works, whatever it is.

**Comment by habbes** [comment]
@txau got it

**Comment by RafaPolit** [comment]
We have a "relationships paradox" that needs to be discussed further in order to move forward with this.  Putting this on hold.

**Comment by RafaPolit** [comment]
So this "paradox" only affects the metadata-created relationships, but works nicely if controlled through the relationships tree.  We should remove this blocker but make the property read-only from that point on, either automatically or manually selected as read only.

**Comment by fnocetti** [comment]
This is implemented in relationships V2
