### ISSUE TITLE
Enable HTML in templates' rich text fields (8pts)

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2275]

**Comment by RafaPolit** [comment]
This is just extending the markdown parser to be able to use HTML (with the correct restrictions) in rich text fields.  This DOES NOT give access to all the custom components, dedicated datasets on pages and entity pages, etc.  Just to be able to parse HTML for having more versatility at the time of rendering data (for example, multiple links that open links in new windows... that sort of thing).

**Comment by txau** [comment]
@RafaPolit your suggestion makes sense and can be a great addition to Uwazi.  

I think we are talking about different features then. My point is that if we could use markdown fields as "programmable" fields, we could address many scenarios that now are considered custom components or entity pages with less overhead.

Ie. for timelines, the rendering of the entity is ok by default, except an area that needs to render the timeline. If we go for entity pages, we need to create and maintain the whole page with all metadata fields just to be bale to render the timeline. But if we could just use a markdown field to run the code needed for timelines we could keep the default entity page and just add the custom functionality to that markdown field.

Another possibility is to consider this apart from the markdown field, and have a new type of field that is programmable (similar or the same as the proposed lambda fields).

For now we can just simplify and assume that whenever users want to achieve this kind of custom rendering, they necessarily need to go for an entity page. In that case I think the needed addition would be to be able to render the entity pages on side panels as well, not only on the full entity view.

**Comment by RafaPolit** [comment]
I see the scope of this.  I can think of several things:
- we have a component that renders EXACTLY our current metadata that you could use in such custom pages, the only thing is that you would need to add one line per property.  Still, if you would change the template afterwards, then you would need to come into the page and do the changes.  It's a minor inconvenience for sure to your "ideal" scenario, but it could be a good enough compromise as you mention in the last point.
- The entity page on side panel is a must in my opinion, makes a lot of sense from several perspectives
