### ISSUE TITLE
Selecting a text reference no longer highlights the text region it is pointing to

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2280]
When selecting a text reference in the side panel, the text snippet that corresponds to that reference is no longer being highlighted or distinguished in any way.

**Comment by txau** [comment]
Dupp: https://github.com/huridocs/uwazi/issues/687 https://github.com/huridocs/uwazi/issues/2237

**Comment by RafaPolit** [comment]
This is not the same issue.  I'm not talking about the scrolling (which when clicking the side panel references work), I'm talking about the yellow-highlighted region.  When a sidepanel reference is selected, the region used to change to green so you knew which part of text you were referring to.

Now this no longer works.  I may be solved with the others, but I don't believe they are talking about the same thing.

**Comment by konzz** [comment]
@RafaPolit it does highlight for me, a very subtle yellow, but its highlighted.

**Comment by habbes** [comment]
It's highlighted on my end as well. Maybe the yellow just needs to be darker?

**Comment by daneryl** [comment]
@RafaPolit this fixed it ? #2655

**Comment by txau** [comment]
There are certain weird combinations that fail to highlight, but I guess is more related to the oddities of the PDF structure than a bug in our end.
