### ISSUE TITLE
Document search in text references style has lost it's styling

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2282]
The text reference document selection side panel has lost most of its styles:
- Search input has no input to show, just a 'search' word floating in the space
- The search icon is floating well bellow the search text
- There is a search tips link with an dotted underline that rests 40px or so below the link and on top of the first results.
- The checkbox selector for type of relationship has no label as to what that checkbox is for
- The checkbox is adhered to the text with no separation
- The results don't show the template type aligned to the right as the cards do

**Comment by RafaPolit** [comment]
![Screenshot from 2019-03-29 09-58-16](https://user-images.githubusercontent.com/4309019/55241756-c41e1580-5209-11e9-946d-7c5557610dd6.png)

**Comment by habbes** [comment]
Hey @RafaPolit 
What did you mean by "The results don't how the template type aligned to the right as the cards do"?

Cards display the template type tag on the left end of the card.

<img width="952" alt="Screenshot 2019-05-17 at 15 26 22" src="https://user-images.githubusercontent.com/8460169/57927950-26190400-78b8-11e9-9ba3-69fef0abd4d2.png">

**Comment by habbes** [comment]
@RafaPolit also, the results on the connections panel seem to be displayed in the same way as on the text references panel

<img width="400" alt="Screenshot 2019-05-17 at 15 27 45" src="https://user-images.githubusercontent.com/8460169/57928064-66788200-78b8-11e9-906b-bfba359a0e46.png">

Are you suggesting that they be aligned to the right of the list item instead?

**Comment by habbes** [comment]
Hey @RafaPolit, how does this look?

I've tried reusing the same styles used in the relationships page as well as the library filters for the multiselect.
I changed the alignment of references results such that the template tag is at the right end. I also reduced the margin between list items cause I noticed what was on your screenshot was much smaller than what was on mine. Let me know if this was also something I was supposed to fix, or whether I've just broken it

<img width="1680" alt="Screenshot 2019-05-17 at 17 18 21" src="https://user-images.githubusercontent.com/8460169/57934486-84e67980-78c8-11e9-98e4-0c2a2ed87b40.png">

**Comment by habbes** [comment]
@RafaPolit I've made a PR with these changes here: https://github.com/huridocs/uwazi/pull/2350

**Comment by RafaPolit** [comment]
I think it look much, MUCH better!

Perhaps the search field right end point and the ‘search tips’ could have a higher right margin to be aligned with the template type boxes and allow for the scroll bars to sit better?

Also, how do these look with really long titles for entities?

Thanks!

Rafa Pólit

**Comment by habbes** [comment]
@RafaPolit when there title is too long, it wraps to the next line:
<img width="397" alt="Screenshot 2019-05-20 at 16 21 32" src="https://user-images.githubusercontent.com/8460169/58024678-6f1cc280-7b1b-11e9-9b6a-ec26a7191ebd.png">

**Comment by habbes** [comment]
@RafaPolit I've update the styles: https://github.com/huridocs/uwazi/pull/2350
