### ISSUE TITLE
Footer link to library is taking you to home instead

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2284]

**Comment by konzz** [comment]
There is a method in the Menu component that calculates the libraryUrl and the uploadsUrl, those methods should be abstracted and used in the Footer component to point to the right URLs

**Comment by daneryl** [comment]
@txau @konzz do we want to go to library with the filters we had or clean link to library?

**Comment by txau** [comment]
@daneryl clean link

**Comment by daneryl** [comment]
@txau 5 minutes if we do it without the filters we had before, @elric-wamugu pls change the link url

**Comment by elric-wamugu** [comment]
Okay
