### ISSUE TITLE
app/react/Library/components/FiltersFromProperties issues

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2286]
The file app/react/Library/components/FiltersFromProperties issues has some important issues:
- There is a direct circular reference to ./RelationshipFilter which requires the FiltersFromProperties right back, this needs to be sorted out.
- The default return of the component assigns key={property.name}.  If two properties set as filters from different templates have the same name (easiest way is to create a Relationship field that points to two different sets of data), then there is a duplicate key warning from React, but this could be affecting filter selection, etc.

**Comment by daneryl** [comment]
already fixed.
