### ISSUE TITLE
Getting a "Duplicate name" error in wrong scenarios

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2297]
When editing the properties of a template:

1. Adding a field with a duplicate name, delete the field. When you try to save you still get a "Duplicate name" error even if the field was deleted.
2. Add a relationship field, try to save. You get a "Duplicate name" error but actually the error is a required error (since the relationship type wasn't specified)

**Comment by habbes** [comment]
@txau when I add a relationship and then save, the relationship field is highlighted but it does not have an error message. Furthermore, the relationship dropdown inside the field config is also highlighted. So maybe the behaviour has changed since the issue was created. Is this new behaviour still considered a bug?

**Comment by habbes** [comment]
When you remove the relationship with the error from the template and try to save, the form still shows the "The template has errors message" and doesn't save. Actually this seems to happen with any field. If a field is invalid, removing it still causes the form not be saved. So far, I think there may be a bug with react-redux-form.

**Comment by habbes** [comment]
Even after removing an invalid  field, its validators still appear in `$form.validity` and the `$form.valid` is still `false`. This happens even though the `validators` object passed to the form component do not have references to the removed field.
Maybe this could be related to [this reported issue](https://github.com/davidkpiano/react-redux-form/issues/913) on the react-redux-form repository. It dates from 2017  and doesn't seem to have had enough attention.

**Comment by daneryl** [comment]
@habbes explicitly reseting form validity on delete solved the problem for me
```
export function removeProperty(index) {
  return (dispatch) => {
    dispatch(formActions.remove('template.data.properties', index));
    dispatch(formActions.resetErrors('template.data'));
  };
}
```
change removeProperty function to that, small refactor and explicitly reset errors

**Comment by habbes** [comment]
Thanks @daneryl, that fixed the issue

**Comment by habbes** [comment]
I've created a PR: https://github.com/huridocs/uwazi/pull/2335
@txau could you check whether the behaviour of the Relationship field is okay? I haven't changed it, but it doesn't behave as described in this issue's description.

**Comment by txau** [comment]
@habbes seems to be working properly for me know for the two described scenarios.
