### ISSUE TITLE
Inherit property issues

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#2312]
- When editing the options in settings > templates for an inherited property, if I have a library open in another browser tab it automatically crashes with this error:
https://user-images.githubusercontent.com/489831/55721977-209ce400-5a05-11e9-99b4-f4f647b78650.png

- Inheriting a thesauri based property is not showing the values.

- ~~Getting an error when editing an entity with two inherited properties~~ (should not happen since we wont allow two of the same relationship)

- Inherited fields disappear when editing:
Go to the entity view of an entity with inherited properties.
From this view, edit the entity.
Save.
The inherited fields disappear.

**Comment by txau** [comment]
Selecting "Any entity" will cause this bug in the configuration that leads to a library error:

![Screenshot from 2019-04-11 19-27-16](https://user-images.githubusercontent.com/489831/55977964-df6c3480-5c8f-11e9-8954-01c71ff45e19.png)
