### ISSUE TITLE
CSV Importer should be case insensitive when matching title or thesauris

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#2323]
CSV importer duplicates thesauri entries when they have a different case. For example "blue" and "Blue" are detected as different values in a thesaurus, but they should be the same.

**Comment by daneryl** [comment]
@txau @konzz i remember talking about this and deciding not to do it ? do we still want not to fix this ?

**Comment by txau** [comment]
@daneryl tough one, from the UX perspective, do you expect Uwazi to be case sensitive? In which cases being case sensitive or not is an advantage?

Ie. Generally speaking, for names etc you want it to be case insensitive so ie "Spain" and "spain" should be the same.

While I personally prefer my systems to be case sensitive, my intuition is that generally speaking case insensitive is more user friendly.

**Comment by daneryl** [comment]
@txau maybe in the particular case of CSV import for thesauri creation it is better for the user to be case insensitive as you say, i think in this case it is more often a typo than a real different thesauri value ?

another option is to be able to choose for CSV import what mode do you want, with insensitive as default.

**Comment by txau** [comment]
@daneryl let's not complicate things with modes. Let's go for case insensitive then.
