### ISSUE TITLE
Allow admin to change the label of "Title" on entities

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#2333]
I am working on an Uwazi instance that has an entity called "Person". I'd like to be able to change the "Title" field to "Name" so that it's clear to the person entering the data what kind of info goes there (and to avoid having 2 fields - one for title and one for name).

**Comment by RafaPolit** [comment]
The approach will be:
- Keep the title property on the entity root
- Allow for configuring in the template the 'label'
- Probably store that in the commonProperties key of the template
- Needs to be translatable

**Comment by kjantin** [comment]
Yes please!
