### ISSUE TITLE
Implement metadata lists in the settings

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#234]
Implement the new design in #225 of the metadata lists in the settings section.
The branch with the designs html is 225-metadata

**Comment by danicatalan** [comment]
![screenshot 2016-07-29 16 02 10](https://cloud.githubusercontent.com/assets/6364153/17250936/cbd24880-55a6-11e6-858b-6ddbc43340b3.png)
![screenshot 2016-07-29 16 03 42](https://cloud.githubusercontent.com/assets/6364153/17250934/cbcc65aa-55a6-11e6-9fc5-63195734128b.png)
![screenshot 2016-07-29 16 10 09](https://cloud.githubusercontent.com/assets/6364153/17250960/f7221f9c-55a6-11e6-8707-d88ec991be08.png)
