### ISSUE TITLE
Certain combinations result in the same entity being assigned as his own relationship

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2348]
To reproduce:
- Assign a relationship property to a template, and leave 'any entity type' as target
- create two entities of that type
- select in the metadata of the first the second entity as the target of the first entity

Result:
- The first entity has a correct value (in the metadata) to the second entity
- The second entity has itself (in the metadata) as its value

The relationships are actually correctly created, it's the metadata population that is wrongly interpreting the situation.

**Comment by txau** [comment]
@RafaPolit what is the issue?  What does "wrongly interpreting the situation" translates to in terms of errors or UX misbehavior?

**Comment by txau** [comment]
@RafaPolit bump

**Comment by daneryl** [comment]
already fixed.
