### ISSUE TITLE
Swap property names in a template throws a mongo error

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#2349]
Swapping the names of two existing properties in a template throws an error like:
`MongoError: Cannot update 'metadata.people' and 'metadata.people' at the same time`.

It's not clear what problems this may cause, but the template does get updated but probably not the entities metadata.

**Comment by RafaPolit** [comment]
Also, perhaps related, if we use a previously-used property name with a different Elastic type (for instance Geolocation), we get indexing errors.

For example, if you have assigned a property name: "House geolocation" of type text, and then create a "Home" property of type geolocation (which would be created as house_geolocation internally), the elastic mapping will throw an error.

**Comment by RafaPolit** [comment]
We have talked a little bit about this, perhaps the solution is to escape every property in Elastic and leave them without any typing (including geolocation!) within Mongo.

Still, this does not solve the mongo issue which is a separate thing.  It would be good to probably tackle this two things together.

**Comment by konzz** [comment]
@RafaPolit what you are commenting has its own issue #2261

**Comment by RafaPolit** [comment]
For the original behavior to occur, there NEEDS to be an entity holding that data.  The issue is NOT with the template editing process, but the entity sanitizing one.
