### ISSUE TITLE
Allow admin to assign a country to a geolocation property (as opposed to coordinates)

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#2351]
As an administrator of https://cyrilla.org/en/, I want to capture the related country of each law-related document/entity in the collection. I plan to import the HURIDOCS location thesaurus once the import feature is completed (as entities?):

https://docs.google.com/spreadsheets/d/1mJj9dlDl78pOUeGJan9R0tXd5f7e6yJmW5pRuKEeELM/edit#gid=152909758 

And I want the filtered collection to be represented on a map, for an engaging way to bring the researcher into the collection.

I tried to find info about whether this is possible on https://openmaptiles.org/ but gave up after 30 min :)

**Comment by konzz** [comment]
Hi Kristin, this can be done with the inherit functionality.
- You can have the countries as entities with a geolocation property. 
- Then in the entities you want to select the country, you configure a relationship field to the countries and inherit the geolocation.

They will appear in the map as if they had the geolocation themselves.
Hope this solves it, I'm closing the issue but feel free to reopen it if you have further questions or this does not solve your problem.
