### ISSUE TITLE
Password recovery marked as phishing

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#2352]
Hey guys,
password recovery function on oau-aec-au-documents seems to be down. Shows an error message. Kindly advice

**Comment by konzz** [comment]
Can you put here the error message?

**Comment by HSips** [comment]
![210519](https://user-images.githubusercontent.com/22650647/58067890-cfe9e080-7b97-11e9-8167-3103a77f07c2.png)
it shows up for a few seconds

**Comment by konzz** [comment]
Hi @HSips, I've dug up a little in the problem and seems that the email is being detected as possible phishing and it's being blocked.

Part of the error message is:

`Error: Message failed: 550 5.7.1  Reject for policy reason RULE2_1. See http://postmaster.gandi.net
    at SMTPConnection._formatError (/srv/datadisk16/uwazi/core/node_modules/nodemailer/lib/smtp-connection/index.js:606:19)`

And the policy RULE2_1:
Reject for policy reason. RULE2_1: [Message considered as phishing either by heuristic analysis or a suspicious link found in it.](https://docs.gandi.net/en/gandimail/faq/error_types/rule2_1.html)

**Comment by HSips** [comment]
Thanks!

**Comment by HSips** [comment]
@konzz Thanks! Pw recovery is working. Only that now, the system says account locked, check email, but nothing comes to my email. Account linked to lcosmos910@gmail.com
Kindly advice
![280519](https://user-images.githubusercontent.com/22650647/58452502-42226e00-8120-11e9-9135-f9654396a733.png)

**Comment by HSips** [comment]
Dear @konzz Any advice on above?

**Comment by konzz** [comment]
@HSips the account is now unlocked, please check that no one has wrongly configured the mailer.

**Comment by HSips** [comment]
@konzz Thanks. Let me log in. How do I check wrong mailer configuration?

**Comment by txau** [comment]
@HSips check out the wiki page about it: https://github.com/huridocs/uwazi/wiki/Edit-your-site-information

**Comment by HSips** [comment]
Hey! @konzz So so sorry to come back to you on this. Still giving the account locked message from multiple comps..
![080619](https://user-images.githubusercontent.com/22650647/59145285-1fc70500-89ea-11e9-9e16-5972f0ea8da8.png)

**Comment by HSips** [comment]
@txau Thanks! Will do once account unlocks.

**Comment by txau** [comment]
@HSips is the account unlocked? Can we close this issue?

**Comment by HSips** [comment]
@txau sorry for going quiet.
Well. Not yet. still same message.

**Comment by txau** [comment]
@konzz can you please unlock the account?

**Comment by HSips** [comment]
Much obliged. Will keep checking.

**Comment by konzz** [comment]
@txau @HSips The admin account has been unlocked, but the account linked to lcosmos910@gmail.com has "elvis.c" as the username. The admin account has "humphrey@huridocs.org" as linked email. Maybe you mixed accounts/passwords?
