### ISSUE TITLE
Semantic search BETA

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2355]
- [x] Remove launching the search from the selection of documents. Launch always on the filtered documents/whole library.
- [x] When we have pagination it will only run the search on the documents displayed. It should run the search in all the documents affected by the filtering.
- [x] Remove the search box from the panel and instead add a toggle button in library's search box.
- [x] Make a component that will create a description of the search based in the multiselect options. Use this description as part of the title for the saved semantic search.
- [x] Add an explanation of the feature on the side bar where the threshold and minimum relevant sentences are.
- [x] Format the threshold % to just 2 decimals.
- [x] Remove the "More" before More precision and More exploration labels.
- [x] Add "per document" to the minimum sentences label.
- [x] Also add the description of the search (created from the selected filters) in the semantic search results.
- [x] Add the total amount of sentences in the cards. Ie. 345 out of 500.
- [x] Remove the "Average sentence score" from the cards.
- [x] Add a hard-coded order criteria "% of document above the threshold".
- [x] Add the % of document sentences above the threshold in the cards.
- [x] When you select a result, in the side panel, replace "Average sentence score" by "% of document above threshold".
- [x] Add a bulk edit button that will trigger bulk edition for all documents above the thresholds.

**Comment by habbes** [comment]
@txau since we're adding the total amount of sentences in the card in the for "345 out 500), instead of adding another field for "% document above threshold", I display the number of sentences above of threshold as "345 out of 500 (69.00%)" to avoid redundancy. Is this fine?

**Comment by txau** [comment]
@habbes yes, I think it makes sense.

**Comment by habbes** [comment]
@konzz @txau If you don't specify a limit, uwazi search defaults to 30 results (hardcoded). Now if you remove the limit from the internal search query passed to Elasitc Search, ES will default to returning only 10 results. So I'm not sure how to tell the query to search for all documents in the library. Should I specify an arbitrary large number? What's the ideal approach for this?

**Comment by habbes** [comment]
@txau should the search description be based on fields in the filter or the selected templates? Or both?

**Comment by txau** [comment]
@habbes lets go only for select and multiselect fields now. We will eventually improve this.

**Comment by Tilana** [comment]
Here is the semantic search explainer:

Semantic search is a technique to provide contextual results.
Its ability to capture concepts and word associations in human language enables the retrieval of related information such as synonyms, connected categories or entities, etc. .

The treshold determines how close the results match the search concept.
Move the slider to the right to narrow down the concept of the search query. The obtained results will be more precise.
Move the slider to the left to more broaden the concept and explore related content.

Semantic search is applied to each sentence in a document.
Filter the documents by the minimum number of sentences that exceed the threshold.

**Comment by habbes** [comment]
@txau @konzz 

I've created a component for generating search descriptions from property filters

Here's how it looks on the results page
<img width="975" alt="Screenshot 2019-06-07 at 02 12 44" src="https://user-images.githubusercontent.com/8460169/59072164-3b3aee80-88ca-11e9-84da-00486d5381e2.png">

And here's what it looks like on the side panel
<img width="380" alt="Screenshot 2019-06-07 at 02 12 33" src="https://user-images.githubusercontent.com/8460169/59072179-4d1c9180-88ca-11e9-9249-ce30fde48ecb.png">

To implement this, I used the same function that's used to generate the properties and value options used in the library filters. This function is called for each title description that has property filters. So I think this could be inefficient, though I have not noticed a significant lag in my tests. But if this is a concern that needs to be solved before the MVP, then I'll work on making it more efficient. And I could use some help with that.

Furthermore, I need to know what pattern to use to generate the description. Currently I've used the following pattern: 

```
<search term> with <property 1>:<prop 1 val 1>, <prop 2 val 2> and <property 2>:<prop 2 val 2> ...
```

Also, how does one enable translation for such a dynamically generated piece of text?

**Comment by txau** [comment]
@habbes looks good to me.

1. Why do you think it could be inefficient?
2. The pattern is ok, but if we create a pattern that doesn't need any translations it could simplify the task? In this case I think its just removing the "with".

**Comment by habbes** [comment]
@txau 

1. The function populates all the value options for each select/relationship/mulitselect property on the search's filters, and then the search description goes through those options to find the labels of the values that were selected. This is done for each search description. So I just had the impression that all that is expensive and maybe could be improved. But I have not noticed any visible performance hit so far.
2. I've changed the pattern, removed 'with' and replaced 'and' with a `-`
