### ISSUE TITLE
Erratic behaviour when switching languages

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2357]
A couple of malfunctions.

1. Go to a page in one lang.
2. Manually set the URL to another lang.

Probably server is rendering in one lang and client is overwriting with the cookie lang. The header menu switches to the cookie lang.

1. Fast switch between two languages.
2. Eventually it triggers a mismatch between the lang in the lang menu and some of the content loaded in a page.

**Comment by RafaPolit** [comment]
Another information regarding languages:

If working on two or more tabs, if you change the language on one, the other tab keeps showing the 'original' language, but requests use the cookie's language (that has changed to the second-tab's language) leading to corrupted or inconsitent data.

**Comment by RafaPolit** [comment]
Being documented in #2368
