### ISSUE TITLE
Country flags not being displayed in cards

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2362]
These
![Screenshot from 2019-06-03 15-15-20](https://user-images.githubusercontent.com/489831/58804593-832fec00-8612-11e9-8277-1ce11c16f3b9.png)
 countries have the flags configured and they appear in other places (ie, in multiselects), but not in the card list:

**Comment by daneryl** [comment]
@txau ive just checked and those entities do not have flag icon configured
