### ISSUE TITLE
Error when saving an entity

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2364]
In this URL: https://sidh.cejil.org/pt/library/?q=(filters:(pa_s:(values:!(%274xxex83924piizfr%27))),limit:30,order:desc,sort:creationDate,types:!(%2758b2f3a35d59f31e1345b48a%27))

Just edit and save. Then getting this error:

![Screenshot from 2019-06-05 15-17-52](https://user-images.githubusercontent.com/489831/58959368-37617c00-87a5-11e9-83ab-86ed29f4a1d5.png)

**Comment by RafaPolit** [comment]
Should be solved by #2370

**Comment by RafaPolit** [comment]
@daneryl Will deploy and report back if this is fixed.

**Comment by daneryl** [comment]
@RafaPolit still giving an error, it seems a different one though

**Comment by daneryl** [comment]
@RafaPolit @konzz  not clear yet how to solve, lets discuss this again plz, everything i think of looks like a bad hack, i prefer to suppress the error for now and find a better solution for this inherit geolocations and update on library/map flow.

**Comment by daneryl** [comment]
@RafaPolit @konzz proposed PR with a hack fix to prevent instances to crash on entity save. this needs a more complex solution. https://github.com/huridocs/uwazi/pull/2384
