### ISSUE TITLE
We use cookies notification popup

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#2372]
Create a popup that displays a message about the use of cookies in Uwazi

**Comment by mylaa** [comment]
**_Proposed text:_**

"Cookies notice:
This website uses cookies to offer you a better browsing experience. Find out more on how we use cookies, how you can change your settings and on your rights as a user in the privacy statement [ability to add a link to a privacy policy].

**I accept cookies | I refuse cookies**

**Comment by RafaPolit** [comment]
We have an issue right now.  Refusing cookies is not an option.  That requires development and talking through how to approach this.  The cookie is mostly for storing the language preference, nothing more.

Is there a way to just say: we use cookies, I accept.  Without a refusal?

**Comment by txau** [comment]
@mylaa in other words. What is the expected behavior if they refuse?

**Comment by konzz** [comment]
Also, matomo, google analytics and socket.io use cookies

**Comment by mylaa** [comment]
@txau so basically, the idea is that if a user "refuses", the cookies file are not stored on the devise. 

Is that a possibility? 

We can also have an option: _"_ More info"._ with the following information (a copy from a partner's privacy policy): 

_“Cookies" are small files that are stored on the user's computer. A cookie is primarily used to store information about a user (or, more precisely, about the device on which the cookie is stored) during or after the user's visit to an online service. Different data can be stored within the cookies. Cookies that are used by the Atlas of Torture are referred to as “first-party cookies” and those used by our partners/others as “third-party cookies”.

For the purpose of analysing the use of our website and for the purpose of user handling in the administration area of the website, the IP data of the connection owner is stored within the framework of first-party cookies. In addition, we store your preferred language, other personal page settings as well as the type of your terminal device.

The use of cookies increases the user-friendliness and security of this website. However, the use of our website is basically possible without cookies.

If you do not want first-party cookies to be stored on your end device to measure your range, you can object to the use of these files here: (here we would also have to put the link to the cookie notice)

In addition, common browsers offer the option not to accept cookies. Stored cookies can be deleted in the system settings of the browser. However, the exclusion of cookies can lead to functional limitations of this online service._"

**Comment by txau** [comment]
@konzz what would happen if someone disabled cookies in their browser?

**Comment by konzz** [comment]
For Admins and Editors, it just won't work.
For other Uwazi visitors, we did not detect problems, but I did not a super extensive search over the application so maybe there is a problem but I did not found anything.

The big problem here is that we not only use our own cookies, but also libraries that we use to store cookies, like Matomo, and do all the modifications required in order to wait until the user give us permission to store cookies before we load thos libraries and it's a huge development,

**Comment by RafaPolit** [comment]
I really think that "We use cookies to provide you with the best experience" is perfectly acceptable, without the need to provide for a 'refusal' path.

Users always have the option to just select not to use cookies in their browsing experience if that is their preference without us having to develop anything special for that scenario.  As mentioned, most everything will work.

What has to be clear is that doing any of the admin work is just NOT possible if they have cookies disabled.

**Comment by mylaa** [comment]
ok, thank you for this explanation @RafaPolit. I do agree with the proposal: "We use cookies to provide you with the best experience". 

In case this conflicts with any of the partners' security policy, we will discuss how to address it.

**Comment by mylaa** [comment]
It's just very important to have this set up by 25th June.
