### ISSUE TITLE
Issue with Deleted Entities / Ghost Relationships pointing to Entities

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2377]
We have several scenarios that end with Relationships pointing to Entity IDs that are no longer in the database.

It's unclear how this happens.  

First place to look:
- [x] Follow the entity Delete procedure and ensure that relationships are being deleted correctly
- [x] Ensure that if some part of the process gives an error, that this happens 'in the correct order'.  For instance, if I delete an entity and the relationship delete fails, then we have a ghost.  This should probably start with the relationships and ONLY if that succeeds, delete the entity.

The flow should be revised first.

Still, the reports suggests that no one is deleting these entities, so the issue may reside elsewhere. 

Having a proper log could really help knowing what type of actions trigger this behavior.  Perhaps up priority of #1087? @txau

**Comment by daneryl** [comment]
@RafaPolit, @txau 
The Endpoint causing this is "relationships/bulk", what happens is the connections is saved after the entity that is being used for the connection has been deleted, we do not have any mechanism to check whether the entity exists or not, we should implement something like that, should we return an error or just ignore connections with nonexistent entities ??
