### ISSUE TITLE
ESlint and CodeClimate rule changes

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2381]
- Investigate removing "repeated code" warning on tests (Wont change)
- [ ] Improve the Label - htmlFor rule to better reflect our stack
- [ ] React/destructuring-assignment try ignoreClassFields? (https://github.com/yannickcr/eslint-plugin-react/issues/1968) read about scope and the consequences of calling this.props.func() )
- [ ] Research removing all the styling rules and passing this responsibility to Pretier.  Ensure that this is somehow run automatically (git hooks? part of the PR process?, not left to user discretion)

**Comment by daneryl** [comment]
from https://docs.codeclimate.com/docs/excluding-files-and-folders
>Exclusions can only be made at the global level (excluding code from all analysis) or at the plugin-level (excluding code only from specific third-party plugins). Currently, exclusions cannot be made for individual maintainability checks.

we can not deactivate code duplication only for tests.
