### ISSUE TITLE
Notification message appears over button

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2386]
When creating several entities in a row in uploads, the notification pop-up appears over the "New entity" button. The user is forced to wait until the message is gone to operate.

![Screenshot from 2019-06-17 22-31-35](https://user-images.githubusercontent.com/489831/59634729-bc5a7700-914f-11e9-866b-a63d3d6d22dd.png)

**Comment by daneryl** [comment]
@txau, you can click on the notification and it should disappear, but i agree that is confusing, also it is not clear that you can close the notification

**Comment by txau** [comment]
@daneryl still, even if you can click on it, it's annoying =)

**Comment by daneryl** [comment]
@txau what about put it on the top ?
<img width="534" alt="Screenshot 2019-06-18 at 12 12 31" src="https://user-images.githubusercontent.com/1386423/59673933-78ed2080-91c2-11e9-87b5-33b0fd8890e1.png">
<img width="1424" alt="Screenshot 2019-06-18 at 12 13 03" src="https://user-images.githubusercontent.com/1386423/59673942-7be81100-91c2-11e9-9162-59939c0f956e.png">

**Comment by txau** [comment]
@daneryl what about instead of moving the notification (that is coherent across all UIs) we move the buttons to the right where all that white space is?

**Comment by daneryl** [comment]
@txau we are not going to have that space on mobile.

**Comment by txau** [comment]
@daneryl what do you think of putting the buttons in the middle of the screen, right below the pro tip and over the search box

**Comment by daneryl** [comment]
@txau it should work, let me try it.

**Comment by RafaPolit** [comment]
How about having them as round action buttons fixed at the bottom of the screen like everywhere else?  Maybe now that the success alerts can be closed, this is less of an issue and can wait for the UX feedback?
