### ISSUE TITLE
PublicForm submit to other Uwazi

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#2388]
Allow public form submissions to other Uwazi instances authenticating with a captcha from the other instance.

**Comment by RafaPolit** [comment]
We have talked during the Tech call and we are going to kill two birds with one stone here.

There are two main problems with this implementation:
- Any instance, from now on, would have a "back door" into creating entities to ANY template.  This is a bit extreme.
- If the public form sends the wrong template (if the instances are not synced), this would break the private instance receiving the data.

So the proposed solution is:
- [ ] Whitelist in the Settings collection the template ids that can be remotely created

With that, we limit not only the templates that can be created, but if none are configured, the instance simply does not have this possibility enabled at all.  Also, the nice thing about whitelisting is that, by default, every existing instance would have this disabled, so we don't need to do any migration.

Also, this solves the syncing situation: if for some reason, the remote and private are not synced, it would reach the same point and simply ignore the request.

There is still an issue with the public form not being completely in sync with the private, but we can address that at a later date.
