### ISSUE TITLE
Screwed up CSS for videos

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2391]
![Screenshot from 2019-06-18 18-42-31](https://user-images.githubusercontent.com/489831/59702825-ea47c600-91f8-11e9-852f-9af664e029c6.png)

**Comment by txau** [comment]
@RafaPolit related: https://github.com/huridocs/uwazi/issues/1686

**Comment by habbes** [comment]
@txau I'm having a hard time reproducing the issue:
<img width="1680" alt="Screenshot 2019-07-17 at 14 56 39" src="https://user-images.githubusercontent.com/8460169/61373716-2d9e5e80-a8a3-11e9-8701-259655441fa3.png">

The video player seems okay on my end.

**Comment by habbes** [comment]
I noticed that in your screenshot you have 5 cards in the same row. So I thought maybe I could reproduce the issue so I tried to zoom out (using the zoom out button in  the library), but it still looks fine:

<img width="1680" alt="Screenshot 2019-07-17 at 15 01 10" src="https://user-images.githubusercontent.com/8460169/61375093-a9e67100-a8a6-11e9-83a1-a8f3570f56ed.png">

**Comment by txau** [comment]
@habbes 

- The videos you are seeing in the screenshot I posted are self-hosted videos. They render different to embedded videos, as you can see.
- In the screenshots you posted, the videos are not rendered properly either, they are cropped and they have big dark area in the background.

So they should look like in my screenshot (not cropped and that size), but without all the blank space for both self hosted and embedded videos. 

Please test the embedding for both youtube and vimeo.

Also, please check if the media player lib needs upgrade.

**Comment by habbes** [comment]
@txau I did see the issue with self-hosted videos and am working on that. Regarding the videos being cropped with the dark area in the background, I assumed that's what it was supposed to look like cause of the aspect ratio. But I've noticed this has been reported as a bug in the related issue so I'll look into that as well.
