### ISSUE TITLE
Menu translations get deleted

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2395]
When editing settings > collection > custom CSS, Menu translations get deleted.

1. Add a menu to a blank Uwazi with at least 2 languages.
2. The translations are created in settings > translations > menu.
3. Go to settings > collection > custom css
4. Edit and save.
5. Go to settings > translations > menu. The translations have disappeared.

**Comment by RafaPolit** [comment]
There was a severe bug in the Settings -> Save procedure.

It was always processing translations for Menu and Filters, no matter what they receive.  So, updating a partial part of settings (like custom CSS, but potentially many, many other procedures) would zero out translations for Menu and Filters.

This has been corrected. Affected instances should re-create their affected translations:
- go into the menu links and save them
- go into the filters groups and save them

That should be enough to re-create the missing translations.  Should we create a migration to force this procedure from our end?  It would be time consuming, and we cannot recreate past values for translations, so translations would have to be done manually nonetheless, so I am hesitant to invest time in the migration. @txau ?

**Comment by txau** [comment]
@RafaPolit I think we can live without the migration. But let's merge and deploy ASAP.
