### ISSUE TITLE
Stuck "Lost connection to the server" message after file download

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2397]
In any Uwazi instance, 

1. open the side panel for a document and click in the link for downloading the main file. 
2. Hit ok to save when prompted by the browser.
3. Wait for a few seconds, the message appears and stays

![Screenshot from 2019-06-26 15-23-23](https://user-images.githubusercontent.com/489831/60183349-690ab780-9826-11e9-917f-0368aad19287.png)

**Comment by daneryl** [comment]
@txau only happens on firefox for me, solved by #2414
