### ISSUE TITLE
Upgrade mapbox-gl and react-map-gl

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2398]

**Comment by RafaPolit** [comment]
The version upgrade broke the clickable clusters that show the entities on the side panel.

Please, re-upgrade to the new version ensuring:
- correct assignable values by clicking on map
- correct display of map in library
- correct click functionality in library for both individual entities and clusters (cursor no longer shows as pointer, clicking on clusters NOT WORKING)
- attempt at e2e to test the assignment functionality when creating metadata (by clicking on the map, not assigning coordinates)
- attempt at e2e to test that library shows an interacts correctly with entities and clusters
