### ISSUE TITLE
Synced (child) instances should probably be 'edit disabled' for anything but pages

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2415]
An instance that is being fed by a parent instance (sync), we should flag that instance as 'guest' or 'child', and disable the editing of that instance, as that could break a lot of things (mainly, remote public form)

**Comment by txau** [comment]
@RafaPolit I think that is ok. I would not enforce any changes by the system, but rather but agreement with the users. These rules are difficult to apply. IMO we should not be expending time on this unless if it is for doing another sync iteration and it comes along with more stuff.
