### ISSUE TITLE
Implement UI for importing CSV Thesauri (and MicroThesauri)

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2425]
Allow importing values from Settings -> Thesauri

Our first hunch is to do this as follows:
- Go into settings, thesauri
- Select to edit an existing thesauri or create a new one
- Assign a name to the thesauri (if it hasn't got one) - we could infer the name from the file name when selecting the file, but this is pushing it)
- Save

What do you think @txau

**Comment by txau** [comment]
@RafaPolit yes

**Comment by habbes** [comment]
@RafaPolit it seems that you have not mention the actual step that imports the csv. If I remember correctly from the sprint call, the suggestion was to have add a floating button for the import, right?

**Comment by habbes** [comment]
@RafaPolit another question, what's the different between Thesauri and MicroThesauri in the title?

**Comment by habbes** [comment]
It appears that the current csv import functionality only accounts for entities. I assume importing thesauri will be added with [PR 2423](https://github.com/huridocs/uwazi/pull/2423).
