### ISSUE TITLE
Cannot delete Templates used as relationships targets without any feedback

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2429]
Templates that have been assigned as Relationship fields in other templates cannot be deleted.  Still, there is no input to the user as to what they have to do in order to get the template deleted.

The question is: how much feedback does the user need?  Do we tell them where it's being used and how?  Does this include listing all the entities that may be assigned to this template?  Is it more a 'generic' info and the user needs to find out where.  Something in the lines of: "The template is being used as relationship target in other templates". 

This is somewhat less useful, but could be much easier to implement that first and then evolve into the more detailed feedback?

**Comment by daneryl** [comment]
@RafaPolit i would say we implement it as more generic, enough information for the user to know whats happening, for now, detailed info to the point on in which property i do not think is necessary for a rare case like this.

**Comment by RafaPolit** [comment]
We are going to allow to delete the template being used as relationship (as long as there are no entities assigned to that template, of course).  We would add a disclaimer saying: "This will delete the template and all relationship properties from other templates pointing to this one" (or something like that)
