### ISSUE TITLE
Have tabs for connections and metadata

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#243]
- [x] Have tabs for connections, metadata and TOC.
- [x] Wrap title, close icon and tabs in a sticky header #286 

Old tasks (check comments):

- [ ] (viewer) Add download document button to metadata sidebar
- [ ] (viewer) Add delete document button to metadata sidebar
- [ ] (viewer) Add edit/save metadata document button to metadata sidebar
- [ ] (viewer) Add publish/unpublish document button to sidebar

**Comment by danicatalan** [comment]
I break down this story in four more:

#266
#267 
#268  
#269

**Comment by danicatalan** [comment]
With the new tabs, now we have duplicated content (see the attachment). Do we use this title as a document title? Do we prefer to remove it and get more space for the side panel content?

![screenshot](https://cloud.githubusercontent.com/assets/6364153/17520769/38ede4b2-5e51-11e6-9ea2-96edc65e0eb6.png)

**Comment by txau** [comment]
@danicatalan about the title question. Do you have your answer yet?

**Comment by danicatalan** [comment]
Yes. I commented before our call yesterday :)

**Comment by danicatalan** [comment]
@daneryl https://github.com/huridocs/uwazi/tree/243-tabs

**Comment by txau** [comment]
Closed in #316
