### ISSUE TITLE
scroll on document viewer not working properly

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazi#2432]
sudden jumps of page happening when scrolling, like if im halfway down to the next page it automatically jumps to the page.

**Comment by habbes** [comment]
@daneryl what did you mean by "it automatically jumps to the page"? Did you mean "top of the page" or "bottom of the page" or "previous page" or something else?

**Comment by habbes** [comment]
@daneryl I've found that it jumps to the next page abruptly while you're scrolling past half-way on the current page. I assume this  is what you  meant?

**Comment by habbes** [comment]
> @daneryl I've found that it jumps to the next page abruptly while you're scrolling past half-way on the current page. I assume this is what you meant?

And also scrolls to the top of the previous  page when scrolling up towards the top of the current page.

**Comment by daneryl** [comment]
> @daneryl I've found that it jumps to the next page abruptly while you're scrolling past half-way on the current page. I assume this is what you meant?

@habbes yeah that is what i meant, i expect the scroll to work smoothly and the url to change accordingly to be able to copy the link pointing to specific page.

**Comment by habbes** [comment]
So I've looked into it, and it seems that the page is designed to change automatically when the new page is more visible than the current page.

There seems to be code that first check whether the new page is already visible before scrolling to it (I guess to avoid scrolling to an already visible page). I figure this is the code that contains the bug, I'm going to try and fix that method method (`Scroller.isVisible()`).
