### ISSUE TITLE
Print defaults to Black and White, with no option to change it.  

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2440]
Printing any part of uwazy renders a perfectly black and white image.  We should look into what is doing this, and maybe allow the user to do that on the print dialog instead of forcing this solution on them?

**Comment by txau** [comment]
@RafaPolit not so sure it defaults to B&W:

![Screenshot from 2019-07-19 13-30-32](https://user-images.githubusercontent.com/489831/61560409-7122d500-aa29-11e9-974a-f9db9afe6024.png)

**Comment by txau** [comment]
@RafaPolit rather than black and white we have quite a mess in printing CSS. I'm going to close for now.
