### ISSUE TITLE
Group Filters are not working

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2448]
Groups in filters are not working as expected. Te reproduce:
- Create a group
- Create a second group
- Drag de second group inside the first

At this point, you can no longer delete the child group, nor the parent one.  You also cannot edit the names anymore of child groups.

**Comment by daneryl** [comment]
@RafaPolit if you drag the nested group out you can delete both again, what is the expected behaviour ? you can not nest a group inside a group ?

**Comment by daneryl** [comment]
@RafaPolit ive prepared a PR to not allow nesting groups on the filters form, if that is the expected behaviour QA it pls https://github.com/huridocs/uwazi/pull/2449
