### ISSUE TITLE
Performance issues detected when handling large amount of documents

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#2450]
Issues detected:
First  scenario:
A Document with a relationship field pointing to 500 entities of a different collection with around 76k entries. Takes around 22s~to render the entity.

The problem:
The MetadataFormater, for each of those relationships(500) goes over the 76k documents to transform the "sharedId" to the title. 500 * 76k = 38M

Possible solution:
Iterate over the 76k only once, translating the relationships in that iteration.

Second scenario:
Template a select / relationship / multiselect with 76k values.

The Problem:
Takes around 5s to render the form, even though we only render the top 5 options.
It will be also a problem when the user expands the list to see the other 76k options.

Possible solution:
Change the select to a lookup of the options instead of loading the 76k options.

**Comment by RafaPolit** [comment]
Places that are depending on locally loaded Thesauri

- [ ] Multiselect
- [ ] Select
- [ ] Aggregations
- [ ] Charts
- [ ] Custom pages?
- [ ] Cejil timeline ?

**Comment by txau** [comment]
@konzz @daneryl related: https://github.com/huridocs/uwazi/issues/2609

**Comment by txau** [comment]
Related? https://github.com/huridocs/uwazi/issues/2787

**Comment by txau** [comment]
Probably related: trying to load this page crashes the server: https://ihrda.uwazi.io/en/entity/dxy8dzjacebcxxsahc55xez5mi?searchTerm=african%20charter

**Comment by txau** [comment]
Related? https://github.com/huridocs/uwazi/issues/2276

**Comment by RafaPolit** [comment]
@konzz Apparently the inherited properties are also still using the thesauri store point?  because the inherited value is not actually stored in the metadata, only the name of the inherited document.

- [ ] Inherited properties

**Comment by txau** [comment]
@simonfossom @RafaPolit @konzz @daneryl this could be part of the solution for exploring long lists of relationships while loading only part of the information, plus we get an extra decent feature: https://github.com/huridocs/uwazi/issues/1687

**Comment by RafaPolit** [comment]
Not sure it solves the issue... this assumes that there will be some form or hierarchy.  What happens if it doesn't? I think it's a nice feature, but not necessarily a solution to this.

**Comment by txau** [comment]
@RafaPolit that is way it is stated as " part of the solution ". The point being that when we say "explore options" definitely a good practice for long lists is to have it grouped. I'd like to test this assumption against real data, I have the feeling is going to solve many scenarios, while not perfectly, at least pointing the user in the right direction.

**Comment by RafaPolit** [comment]
Please ensure that:
- [ ] Labels are stored in the language of the entity so that filtering aggregations work as expected

**Comment by RafaPolit** [comment]
- Most conflicts arising from the Topic Classification have been addressed
- @gabriel-piles  to test the ML part of the implementation to ensure this is not affected by removing the entity names from the store
- @daneryl is helping with the process to speed things up
