### ISSUE TITLE
Language misbehavior 

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2454]
A couple of problems, likely related are happening in an instance:

- I'm not able to translate the menu items:
1. While in Spanish, go to settings > menu.
2. Add some translations and save.
3. While in English, go to settings > menu.
4. It has been overwritten by the Spanish version of the menu.
5. Add the English translations and save.
6. While in Spanish go to settings > menu.
7. It has been overwritten by the English edition.

- When loading certain pages, a wrong version of the page is presented. It is likely that its the version in another language. This issues is intermittent and in order to reproduce it you need to reload the same page over and over again until something triggers the problem.

**Comment by daneryl** [comment]
@txau regarding the menu translations, what you see on settings -> menu is not the translation but  the default language value or what its used as a key, if you want to translate menu you should go to settings->translations->menu or inline translation with the button on the left of the languages list in the header.
i agree on that this behaviour is confusing and should be reviewed and improved, in general how we work with languages its not intuitive.

**Comment by daneryl** [comment]
> When loading certain pages, a wrong version of the page is presented. It is likely that its the version in another language. This issues is intermittent and in order to reproduce it you need to reload the same page over and over again until something triggers the problem.

this is a race condition that can happen when multiple users reload, on server we have a singleton api to configure the language of the internal requests, that means you are seeing another user language on your reload. working on it.

**Comment by txau** [comment]
@daneryl ok, regarding the menu, its good enough then. My bad =)

" a race condition that can happen when multiple users reload" - thanks, finally found the culprit.
