### ISSUE TITLE
Ensure correct import / cast of values for Geolocations

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2460]
Some instances have recorded strings instead of numbers in their geolocation fields after import.

Also, there are some values that have been imported with non-geolocation values.  Should we implement some sort of validation for the CSV import?

**Comment by RafaPolit** [comment]
Please confirm if this is still happening.

**Comment by RafaPolit** [comment]
We are going to approach this on model-type layer, not individually on the CSV.  Being tracked here:
#2596

**Comment by daneryl** [comment]
closing in favor of #2594
