### ISSUE TITLE
Search function on AU database hangs/doesn't return results

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#2461]
When I do a search on the uploads page, it goes blank.
this is what is in the address bar
https://oau-aec-au-documents.uwazi.io/en/uploads/?q=(order:asc,sort:metadata.full_document_title,treatAs:string)

**Comment by txau** [comment]
@HSips can you please create an account for me?

**Comment by txau** [comment]
Ok. I can confirm that going into uploads and searching for "africa" crashes the client:

![Screenshot from 2020-03-09 10-00-04](https://user-images.githubusercontent.com/489831/76232788-d3189080-61ec-11ea-9925-0a52a50e0d1f.png)

**Comment by HSips** [comment]
Thanks Jaume.
As always, your help is much appreciated.

warmest
---
Consultant
HURIDOCS, Nairobi

HURIDOCS Secretariat
Rue de Varembé 3
1202 Geneva, Switzerland
http://www.huridocs.org

Humphrey Sipalla http://ssrn.com/author=2593184

**Comment by txau** [comment]
@HSips this error has been fixed in some other patch. Closing for now.
