### ISSUE TITLE
Full text search on mobile suffers from not very responsive search button

### ISSUE THREAD

**Issue by whyfrycek** [huridocs/uwazi#2464]
This comes from observing a user and then trying the same behaviour.

I am on Android, using Firefox mobile.

1) I go to a library, in this case https://atlas-of-torture.org/en/library/?q=(filters:(),order:asc,sort:title,types:!(%275b7e494799dc4c43490ca3d0%27))
2) I type "Un resolution" into the search bar
3) I am trying to press the magnifying glass
4) It begins marking the sentence

Expected behaviour for 4) Search and give me results for documents/entities in question.

**Comment by txau** [comment]
Tested on FF for Android and this behavior is no longer happening.
