### ISSUE TITLE
Blank spaces in rich text field html parsing are a UX nightmare

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2466]
For HTML this fails:
```
<div>

   <p>Some text</p>
</div>
```
While this works:
```
<div>
   <p>Some text</p>
</div>
```

And it gets even worse if you are mixing HTML with markdown.

**Comment by daneryl** [comment]
@txau both scenarios work for me, on mixing markdown and html do we have some scenarios that do not work properly ?

**Comment by txau** [comment]
@daneryl looks like it got fixed =)
