### ISSUE TITLE
Aggregations for Thesauri no longer displaying ordered from higher to lower values

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2481]
Aggregations for Thesauri-based properties, no longer show the aggregated results in order from higher count to lower count when the group is collapsed.

Recently, a patch was made to allow for alphabetical display of certain results, perhaps this broke the display for thesauri values when collapsed?  Entity-based aggregations are behaving as expected.

**Comment by RafaPolit** [comment]
Please include this in an e2e so this functionality is never broken again.

**Comment by habbes** [comment]
I could take this up since I'm probably the one who broke it.

**Comment by habbes** [comment]
@RafaPolit so just to test whether my understanding of the expectations is correct, does the following accurately capture the expected spec?
- thesauri values should be displayed in order of their counts in the aggregation on the library page
- entity-based values should also be displayed in order of their counts on the library page
- when selecting a thesauri value in a (multi)select field during entity creation or update, the values should be ordered in the same user-defined order they are arranged in in the settings
- when selecting an entity value in a (multi)select field during entity creation or update, the values should be ordered alphabetically

**Comment by RafaPolit** [comment]
Yes, exactly, except for point 3: I think there is a chance that thesauri are not purposely ordered.  In that case, what would we do?  But since there is a button to order the thesauri, yes... go ahead and do it as you have explained. That is the correct behavior.
