### ISSUE TITLE
Languages redesign & Import system translations

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2487]
There has been a request to include System-level translations for the most used languages of current / potential users:
- English (default, already implemented)
- Spanish
- French
- Russian
- Arabic

We could develop them as 'importable' files, or we could hard-code them on the system.  The added overhead perhaps is not worth the whole import solution.

**Comment by txau** [comment]
@RafaPolit I think they should be imported, the point being, they can be easily updated, extended to other langs, etc.

One a side note. What is Uwazi's behavior regarding unused keys? Do we just keep them?

**Comment by RafaPolit** [comment]
Creating import translations of contexts (System being just another context) should not be hard on a 'per language' bases, but given our interface of showing all languages for a given context, import would need to update a single language at a time.  Another option is to include all desired languages in the CSV, but that blocks a bit the possibility of having repos with the translations to each language, so I'd go with the former approach.

**Comment by simonfossom** [comment]
It would be nice to have that UI checks Uwazi repo for available translations, displays available, and upon selection pulls them in.

**Comment by simonfossom** [comment]
Changes:
- [ ] moving `Uwazi UI - System` from _Translations_ to _Languages_ 
- [ ] renaming _Languages_ to _Interface languages_ (don't feel strongly about this, but it is a better description)
- [ ] adding tabs: current page goes under _Active Languages_ and UI translations goes under _Interface Translations_tab
**Active Languages**
- [ ] pills to mark _Default language_ and _Language in use_
- [ ] tooltips 
- [ ] adding languages from dropdown
**Interface Translations**
- [ ] content of `Uwazi UI - System` 
- [ ] add import translations FAB

[Design link](https://www.figma.com/file/xjsz7r65epN4B0b96zilac/0-uwazi-redesigns?node-id=371%3A0)

![dropdown](https://user-images.githubusercontent.com/8134850/116519977-6b327700-a8d2-11eb-8d24-12f2cc6d83a7.png)
![language added](https://user-images.githubusercontent.com/8134850/116519988-6f5e9480-a8d2-11eb-98d3-b80918280d5e.png)
![translations](https://user-images.githubusercontent.com/8134850/116520002-72598500-a8d2-11eb-809f-4888b0b41ac7.png)

**Comment by konzz** [comment]
Closed in favour of #3643
