### ISSUE TITLE
validation feedback on thesaurus

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazi#2490]
some weeks ago we added some validations on thesaurus, when any of this errors happens the client only shows Validation error, not giving enough information to the user on how to fix the error.

**Comment by OzrenMuic** [comment]
@daneryl 
We need to describe the error and hide details. Can you tell me more about the error?

PS could you please attach screenshot

**Comment by txau** [comment]
@daneryl why do we have a check on duplicate items in thesauri?

**Comment by daneryl** [comment]
@txau duplicated items on thesauris means duplicated keys on translations, unless we changed how translations work, we can not allow it, we decided this was the best/faster approach, anyways there is no reason to have duplicated thesauris right ?

**Comment by daneryl** [comment]
@txau yes i can see that, sorry i was refering at the error that server returns, it is receiving duplicated items error but it is just showing a generic.

**Comment by gabriel-piles** [comment]
![output2](https://user-images.githubusercontent.com/22240564/66390820-c38de500-e9cb-11e9-9a98-ab01ed7f0b2f.gif)
