### ISSUE TITLE
Create User Guide for the CSV import

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2495]
Create the USER guide for the CSV import in the Markdown format to append to the wiki.

**Comment by txau** [comment]
This is the page being improved: https://github.com/huridocs/uwazi/wiki/Import-CSV

**Comment by daneryl** [comment]
@RafaPolit @txau 

> 6. The names of columns should not contain empty spaces, use the actual property name/key value of the template field.

Not really, you can use the actual labels, the name transformer function is the same as the one used on templates, if it is not it should be.

> 8. For links to external documents, use the convention `[Name](link)`, for example `[HURIDOCS Micro-thesauri](https://www.huridocs.org/resource/micro-thesauri/)`. These links are to be migrated to a Rich Text field in Uwazi.

this is for markdown (rich text), you can also use a Link field with 2 diferent formats suported:
  - only the url, will use the url as the label of the link also.
  - "label|url" will create a link with the specified label.

> 14. Attachments can be imported as a ZIP file of PDFs. There should be a CSV file with the title of the record to which the attachment is to be linked and the name of the file.

Attachments are not supported yet on the csv import that i know of ? only the main pdf file.
this works exactly like explained, only for the main file.

**Comment by txau** [comment]
@nwyu can this be closed?

**Comment by nwyu** [comment]
Yes - all documentation, including how to import csv, lives here [https://uwazi.readthedocs.io/en/latest/](https://uwazi.readthedocs.io/en/latest/).
