### ISSUE TITLE
When creating a reference, library links to documents remain in "TargetDocument state"

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazi#250]
caused by #206.

Replicate: 
- Go to a Document
- Select text
- Click on Create Connection to paragraph
- Select Document and relation type
- Load the Target Document
- Go to library and try to View any Document
- Results in Every Document you navigate its in "TargetDocumentMode".

**Comment by txau** [comment]
@konzz @daneryl I'm closing this issue:

- Its not very likely to happen
- It actually allows a user to select a target document through library
- The user can always unblock this by hitting the "back" button

**Comment by txau** [comment]
Solved in #311
