### ISSUE TITLE
Import CSV thesauri requires more info for users

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2501]
@OzrenMuic has pointed out that importing CSVs in thesauris is not very intuitive nor has any info regarding how to prepare the file, etc.

![import CSV](https://user-images.githubusercontent.com/4309019/64119866-6ebdd580-cd60-11e9-848b-953f82c79803.jpg)

**Comment by nwyu** [comment]
Closing this issue as the modal with drag-and-drop is no longer preferred.
