### ISSUE TITLE
Saving a page while the server was down didn't provide proper user feedback

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2503]
While working on a page, the server side went down and I didn't receive a proper error message when trying to save a page. This could be affecting other areas of Uwazi as well.

This bug is particularly evil since users get the impression of their changes being saved, when actually they didn't.

**Comment by habbes** [comment]
This is also occurs when saving an entity form when the server is down, you don't get feedback. So there is chance this affects all other requests as well.
