### ISSUE TITLE
Connections showing up in two templates

### ISSUE THREAD

**Issue by whyfrycek** [huridocs/uwazi#2505]
What I am trying to achieve: I want to link two templates, for example "Advisory Board Member" and "Person" in https://friedhelm.uwazi.io/en/ using the connection "Partner in Crime" with the label "friedhelm test".

What happens is that very different connections start to appear. For example: take this entity "mum", where the display of different connections "is dudly dude with" and "partner in crime" which I haven't even linked: https://friedhelm.uwazi.io/en/entity/8davvydbmaxaejx6x38wha1yvi

**Comment by txau** [comment]
> using the connection "Partner in Crime" with the label "friedhelm test".

What does that mean? Partner in crime is already the label for the connection? Unless you are referring to the translation of that connection's label?

I've been through the scenario several times and I fail to understand what is supposed to be wrong. Could you provide a more detailed explanation?

**Comment by txau** [comment]
Stale. Closing.
