### ISSUE TITLE
Create more extensive Page and Graphs-in-Page e2e Tests

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2511]

**Comment by elric-wamugu** [comment]
Hey @RafaPolit, any specific test scenarios I should look into or put more focus on?

**Comment by RafaPolit** [comment]
We are waiting for puppeteer because screenshot testing is not working across platforms.

**Comment by txau** [comment]
@RafaPolit working on it

**Comment by RafaPolit** [comment]
Now that we have some Puppeteer examples, please migrate this code to puppeteer.
