### ISSUE TITLE
Using *** in markdown fields is breaking the parser

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2526]
Three asterisks are used as port of the markdown spec for creating an horizontal rule. Apparently this is breaking the page render.

**Comment by daneryl** [comment]
@txau the react parser needs single tags to be self closing, in this case markdown parser is creating ```<hr>``` instead of ```<hr/>``` this is making everything after the *** to be a child of the hr element created breaking the page, configured markdown parser to output self closing tags #2608
