### ISSUE TITLE
Display inbound connections in target document when creating a connection to a paragraph

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#253]
On the target document the connections side panel is currently only showing outbound connections, it should display both inbound and outbound.

**Comment by RafaPolit** [comment]
Part of this task should probably include updating the 'select exisitng connection' when the task is inbound (these were not shown when #240 was created).

There is a current bug that the wrong text gets highlighted if you choose an existing 'inbound connection'.

**Comment by txau** [comment]
@RafaPolit 

"Part of this task should probably include updating the 'select exisitng connection' when the task is inbound (these were not shown when #240 was created)."

Definitely.

"There is a current bug that the wrong text gets highlighted if you choose an existing 'inbound connection'."

Shall we open a new issue for this or fix it within this card?

**Comment by RafaPolit** [comment]
@txau No, its OK, I was just reporting here to be sure we make this and not forget it in the process.  Should this sort of 'to-dos' or extra explanations be kept somewhere else?

**Comment by txau** [comment]
Closed with #281
