### ISSUE TITLE
When the orange strip is shown on the Reference 'card' on the side panel it changes available text space

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#254]
When a reference is showing the colored strip on its side, it alters the card's available inside area, or paddings or font-spacing.  Its a fairly small change, but for some particular content, it changes the word wrapping.  Attaching an animated GIF as example.

Also, the text inside is not using the full available width of the card either.  This may be a design decision, just noting in case it is not.

![referencecardbug1](https://cloud.githubusercontent.com/assets/4309019/17450787/f26f29f0-5b27-11e6-8a58-81d3bc38e3d1.gif)

**Comment by txau** [comment]
@danicatalan a couple of quick fixes

**Comment by txau** [comment]
Fixed, not sure where =)
