### ISSUE TITLE
Instances with sync configured, fail to save settings from the UI

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2540]
Some sync instances reporting problems with synced instances.

**Comment by daneryl** [comment]
@RafaPolit is this still an issue ? even if it is working we do not have any automated test for this feature, maybe we should think how to implement a simple one at least if possible, does not seems easy though

**Comment by RafaPolit** [comment]
Maybe the staging server could be a good middle ground to test this?

**Comment by RafaPolit** [comment]
What is happening is that the SYNC property is not allowed on the joi validation of the settings route, making it impossible to save settings on a synced collection.

**Comment by kjantin** [comment]
Is this issue related to this sync issue reported by a user https://github.com/huridocs/uwazi/issues/2779 ?

**Comment by daneryl** [comment]
@kjantin almost sure this is not related.
