### ISSUE TITLE
UI to add, edit and filter metadata on relationships

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#2545]
Currently, Uwazi admins are able to add/edit metadata (properties) on entities. This metadata allows users to filter and find the kind of information they are looking for, and also allows for some analysis of this metadata. 

It would be helpful to be able to add/edit metadata on **relationships** too. This would allow users to filter and analyse metadata related to relationships. 

Examples to come!

**Comment by kjantin** [comment]
Related to https://github.com/huridocs/uwazi/issues/2092

**Comment by RafaPolit** [comment]
The team has an idea of how to accomplish this in terms of architecture. I'm moving this to sprint so we keep an eye on this, as we need to start working on this really soon.

**Comment by RafaPolit** [comment]
@OzrenMuic @txau Please start discussing UI approaches for this, so that when development starts we already have a working UI.

**Comment by kjantin** [comment]
User story for "relationship attributes" from Japiqay project:

> One of the biggest stumbling blocks that seem to be present for an implementation of the data model on top of the Uwazi platform, is the fact that a number of relationships between entities need to be tagged with their own attributes.
> As an example, the relationship of implication of a person with a report from the investigative commission. It is necessary not only to draw that relationship, but it is absolutely necessary to specify for what motive that person has been implicated. That would be a relationship attribute.

**Comment by kjantin** [comment]
User story:

> 
> As a researcher, I want to know the age of a person at the time they were a victim (which is represented as a relationship type "victim") of a human rights violation.
> 
> As a researcher, I want to filter people who are victims of a certain type of human rights violation, who are between the ages 16 and 18.

**Comment by txau** [comment]
This is going to be solved mainly via multiple inheritance. Closing for now.
