### ISSUE TITLE
Loading path /page/wrongid shows wrong 404 error

### ISSUE THREAD

**Issue by gabriel-piles** [huridocs/uwazi#2556]
Going to a path like /page/wrongid shows the following error:

<img width="596" alt="Screenshot 2019-10-03 at 15 42 18" src="https://user-images.githubusercontent.com/22240564/66132354-36c2e000-e5f5-11e9-8a68-62ee1d05b88c.png">

Instead of showing the right 404 error

<img width="471" alt="Screenshot 2019-10-03 at 15 43 27" src="https://user-images.githubusercontent.com/22240564/66132363-3b879400-e5f5-11e9-9dd9-3fe2f274c1b1.png">

Note that this behavior only occurs when the path is like "/page/something"

**Comment by daneryl** [comment]
already fixed
