### ISSUE TITLE
We need a way for users to recover their user/account name

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#2560]
I have heard from several users (and it has happened to myself), that it is possible to recover your password from the Uwazi system, but it is not possible to recover the username/account name. Therefore, if you forgot the username, there's no way to get it back without contacting HURIDOCS.

**Comment by OzrenMuic** [comment]
Easy way to go around this is to set login with email instead of username

**Comment by whyfrycek** [comment]
This is made more difficult, as user names are also case sensitive, so I have had the case to get an error for "friedhelm" when my user name was set to "Friedhelm".

**Comment by txau** [comment]
Using e-mails for logins let's a potential attacker easily guess usernames since e-mails tend to be publicly known. I consider this a feature rather than a flaw. If we are hosting these instances they can request our support.
