### ISSUE TITLE
Quick render of the library when in private mode

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2587]
I noticed (due to low connectivity) that the library gets rendered for an instant on private instances before being sent out to login. I don't know if this is something to be concerned but we should double check.

**Comment by RafaPolit** [comment]
The layout will render, but no data should be sent at all.  Yes, we should check for sure.

**Comment by txau** [comment]
@RafaPolit that makes sense. Still, I wonder why the layout renders? ideally you go straight to login.

**Comment by txau** [comment]
I guess this is not important at this stage. If no data is being rendered we can ignore this issue for now.
