### ISSUE TITLE
Server crashes when you create an entity with non-existent template

### ISSUE THREAD

**Issue by habbes** [huridocs/uwazi#2589]
To reproduce this error, it's easiest to make a request to the API directly without going through the client.

Create an entity with a non-existent template, e.g.:

```
POST /api/entities
{
   "title": "test",
   "template": "asdf"
   "metadata": {}
}
```

This causes the server to crash, it does not appear as if the error is logged.

**Comment by daneryl** [comment]
@habbes this should have a proper validation, maybe we should add this kind of validation also on #2596

**Comment by daneryl** [comment]
Server does not crash anymore with the new validation #2622
