### ISSUE TITLE
Documentation and validation of metadata properties.

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazi#2596]
in order to use our api there is no way to know the structure needed to be used, for static properties we have the api documentation but for dynamic ones we have nothing, i think we should:

- document and validate template properties configuration
- document and validate entity metadata properties according to the template property configuration.

i think it is more important that we validate this data because even with documentation the data can be sent wrongly formatted, being saved to the db without any error and breaking the application unless detected and changed. this validation could also be used as documentation for people using the api and getting feedback errors on how their data should be structured.

**Comment by habbes** [comment]
Where should the documentation be done @daneryl ?

**Comment by daneryl** [comment]
@habbes i dont know, de only api documentation we have is on swagger, maybe extend what we have on entities and do the templates if it is possible to encode this dynamic properties somehow ?
