### ISSUE TITLE
No indication that your log-in was successful...

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#2602]
Something strange is going on when I log-in to an Uwazi instance. I put in my name and pw and click log-in, and for a split second I see the library but then it sends me back to the log-in page as if my log-in was wrong...but it actually did log me in. Weird, eh?

![image](http://g.recordit.co/kUGSssM8Yc.gif)

**Comment by RafaPolit** [comment]
I think that the login redirects to the page you requested prior to the login.

If the page you requested IS the login, you are redirected there after the login. 

That is the wrong behavior for sure.

**Comment by txau** [comment]
@RafaPolit @kjantin I tested you assumption and is not behaving that way. Could it be that the default page configure in settings is the login page?

@kjantin does it happen in a consistent way?
