### ISSUE TITLE
Using the numeral character breaks the search function

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2603]
Appending a (#) charater into the library search includes a quote (') in the search query which rison is not able to decode properly.

**Comment by daneryl** [comment]
@RafaPolit appending # to the url breaks it in 2 and the rison decoder receives only half of the string it should, i did a quick solution by url encoding # when present, it prevents the error but it is misleading because elasticsearch apparently is ignoring this character for the search, would like to know which is the use case for this, anyway we need to fix the fatal error.

**Comment by txau** [comment]
@daneryl @RafaPolit also when users enter broken quotes or double quotes the query fails. I guess it makes sense to preprocess the query an sanitze certain things.

**Comment by RafaPolit** [comment]
The use scenario would be searching for a title that has a # .  So if the entity is named `paragraph - #3`, and I have 100 paragraphs, I was hoping to search by the name using the hashtag.

**Comment by txau** [comment]
@RafaPolit we can encode on the front-end and decode before passing it to Elastic. Then also sanitize. So everything should work.

**Comment by daneryl** [comment]
> @RafaPolit we can encode on the front-end and decode before passing it to Elastic. Then also sanitize. So everything should work.

@txau  yes that works well and we should solve that problem to prevent the app from crashing, the problem then is elastic ignoring # and other special chars, it will find #title and title the same, i mean its not a problem its just has no effect on the search.

**Comment by txau** [comment]
@daneryl I guess when I say decode/sanitize, I also mean to do it in a way that works for Elastic. Idk exactly how Elastic expects the character '# ' to be encoded/scaped so it can search for it, but that is what we should do.

**Comment by txau** [comment]
Related: https://github.com/huridocs/uwazi/issues/2604

**Comment by txau** [comment]
Another case from our logs:
```
 "searchTerm": "\"",
```

**Comment by txau** [comment]
@konzz another failing query for revision: 

```
url: /api/search_snippets?searchTerm=UNGA%20resolution%2C%20Torture%20and%20other%20cruel%2C%20inhuman%20or%20degrading%20treatment%20or%20punishment%20(2017)%2C%20A%2FRES%2F72%2F163%2C%20PP%201.&id=nq730xczmm
query: {
 "searchTerm": "UNGA resolution, Torture and other cruel, inhuman or degrading treatment or punishment (2017), A/RES/72/163, PP 1.",
 "id": "nq730xczmm"
}
```

**Comment by daneryl** [comment]
@txau just created another issue #2672 to deal with searches with "/" this is more related to #2663 than this one.
