### ISSUE TITLE
How to filter entities by different levels of geolocation (country -> governorate -> municipality -> neighborhood)

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#2605]
I am building a database to investigate human rights violations. As the database manager, sometimes, I have very specific data on the location where the violation took place, such as a specific street corner or address. Other times, I have more vague information on the location, such as the municipality where the violation took place. I want to be able to capture the location with as specific/concise data that is available to me. 

Similarly, as a researcher who is using the database to investigate patterns and trends in violations, I want to be able to filter the violations in the database by different location levels of specificity - such as country, governorate, municipality, neighborhood. 

Uwazi has the ability to capture the latitude/longitude coordinates of a specific location - but is there a way to filter down to all the points on a map in a specific governorate, for example? How could this be done?

Alternatively, if I use a thesaurus, I would need at least 4 levels of nested lists in order to filter the violations by these different location-levels. 

What would be a good way to address this kind of user story?

Related to https://github.com/huridocs/uwazi/issues/2351

**Comment by txau** [comment]
@kjantin actually in Uwazi we have actively avoided having so many levels of nesting and consider it an anti-pattern: the thesauri would be a monster with thousands of members.

I suggest an alternative. Create a template called "Location" and add to properties to it:
- Type: a select based on a thesauri with the values "Country, Governorate, Municipality, Neighborhood.
- Geolocation (a geolocation field).

In the other template (Violation?), add this as an inherited relation field. You can create connections to several of these Locations (so you can add ie. the Country and the Governorate). This will allow you to filter and display in a map.

There is a pitfall though. At the moment you can only inherit one property, so either you inherit the location title, the type of the geolocation.

@RafaPolit what do you think?

**Comment by RafaPolit** [comment]
I full agree with your proposed solution, but that would still leave the filter available a the lowest level of the structure.

This is the precise use of multi-inheritance we are so desperately requiring in so many data models now!  I really think we should move the priority of the multi inheritance to a much sooner development.

Still, none of this solutions would reflect the hierarchical nature of these fields.    That said, I don't think the hierarchy is all that necessary and sometimes its even cumbersome... so our proposed solution would work ideally if we had the multi-inheritance in place.

**Comment by kjantin** [comment]
Ok, here's what I'm thinking now:
* We need to agree on a standardized level of specificity for the locations of acts in order to organise them in a consistent way. So for Syria, for example, we could use Governorate > District > Subdistrict. I think this is what Syrian Archive does:

![image](https://user-images.githubusercontent.com/354426/68042941-8525d600-fcaa-11e9-9e04-0f35c7658899.png)

* With this standardized list, I would have an entity type called "location" as @txau suggested above, but instead of having a thesaurus for each level (e.g. governorate), I could create an entity that would represent every subdistrict, along with the geo coordinates for the capital of that subdistrict. 
* For acts that have a very specific location, perhaps I could include an additional property on the act called "Precise location" if that is available? I'm not sure how we would want to display that to the visitor, but i'm sure it something important to capture in some way. 

But regarding the conversation here about capturing and representing the hierarchical nature of locations -- hasn't this already been solved by using layers on top of maps? For example, I'm sure that someone has already created a map layer for Syria that includes all of this info about which district any given subdistrict is in, etc so that we don't have to do this ourselves -- isn't this something we can include in Uwazi? Maybe in the future?

**Comment by txau** [comment]
@kjantin it depends on what you are trying to achieve. The way I understood it is not so much about getting map layers, but about getting aggregations by Country, Governorate, Municipality and Neighborhood, so you can filter by this criteria or get stats around it.

We can explore the possibility of having map layers with that kind of information, it will make a richer data visualization and eventually get the same aggregations based in a geolocation query. But this is definitely another set of features for Uwazi that go deeper into handling geolocated data.

**Comment by txau** [comment]
@kjantin stale issue. Closing.
