### ISSUE TITLE
Running the tests on app/api/search alone fails 90% of the time

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2612]
Running only the search module of tests fails 90% of the time with a query_shard_exception

This is, apparently, an intermittent test that does not fail on the CI server ever, but locally fails almost every time (if run alone)

**Comment by bdittes** [comment]
All in app/api/search/specs/index.spec.js?

**Comment by RafaPolit** [comment]
@konzz and @daneryl have found the source of the issue on the elastic index naming procedure. Looking into a fix.
