### ISSUE TITLE
SYNC scenario: if an entity is changed from a synced template to a non-synced, it remains in the remote

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2617]
SYNC does not take into account entities changing templates to templates that are not synced.

Scenario:
- Create an entity in a template that is synced
- Change the entity to a non-synced template (in the master instance)
- The remote-synced entity remains with previous template

This is not as simple as 'deleting' the remote entity, because that entity could be related to templates that are synced and that deletion would not detect.

**Comment by txau** [comment]
Already fixed
