### ISSUE TITLE
Editor user gets redirected to login on library.

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazi#2635]
to replicate:
  - set blank state
  - create an entity and publish
  - create an **editor** user
  - log in with new created user
  - this redirects you to Login page

**Comment by daneryl** [comment]
the requests causing this are /api/semantic-search/notify-updates and /api/semantic-search that are performed on library first load.

**Comment by RafaPolit** [comment]
I can't understand why there are requests made by the semantic search functionality even when the feature is not even activated on the instance.

But, if it is activated, obviously these redirects are not what should happen.

**Comment by RafaPolit** [comment]
@daneryl I don't see anything on that PR that could change this behavior you reported.  Maybe it's more subtle than what it seems, but I don't think any redirect is affected.

**Comment by daneryl** [comment]
@RafaPolit the redirect is not the problem, but the fact that semantic-search is doing some requests even in a blank state uwazi without doing anything else, this should not happen, also the redirect happens because the user is an editor, does the editor will not have permission to use semantic search features ?

**Comment by kjantin** [comment]
This is still happening for at least one partner, and I think it may be happening to more than just the "editor" role.

**Comment by kjantin** [comment]
Hi, our partners are still unable to log-in to Uwazi - any updates on this one? This is a huge blocker for them. Thanks!

**Comment by daneryl** [comment]
@RafaPolit @txau is the semanticsearch feature expected to work for editors ? or just admins ?

**Comment by RafaPolit** [comment]
Sorry that we didn’t see this earlier.

Apparently only Admins.  We need to have a talk about this feature so we all understand its implications.

**Comment by kjantin** [comment]
Just to clarify, I am able to log-in using my admin user credentials, but I see this warning message for a moment before it goes away:

>Could not reach server. Please try again later. 

I am still unable to log-in using an editor user credentials.

**Comment by daneryl** [comment]
@kjantin still working on this, will have a fix today.
