### ISSUE TITLE
Uwazi stopped rendering the map

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#2637]
today I noticed that my Uwazi instance no longer renders the map. My instance is dockerized, based on Debian stretch. Both log files have no fresh entries. List view works as normal, just the map stays empty.

**Comment by RafaPolit** [comment]
Hello! 

There was a change on the URL for the tile server we use for Uwazi.  This was addressed a bit back in Oct 14 in Pull Request #2574 .

Have you updated your Uwazi instance after that date?

If not, we suggest you follow the procedure to update your instance with the most recent Master branch.  Have you done this before?

**Comment by vasyugan** [comment]
I gu

> Hello!
> 
> There was a change on the URL for the tile server we use for Uwazi. This was addressed a bit back in Oct 14 in Pull Request #2574 .
> 
> Have you updated your Uwazi instance after that date?
> 
> If not, we suggest you follow the procedure to update your instance with the most recent Master branch. Have you done this before?

Thanks! No, I use the stable release 1.5. If it is just about a changed URL, wouldn't it make sense to backport it to a maintenance release? Since my Uwazi install is basically still a pre-alpha, upgrading to git master probably wouldn't do much harm but once it goes public, I would prefer to have a stable version running, and I don't know if it is going to be safe to downgrade to a stable version at that point.

**Comment by txau** [comment]
@vasyugan we are waiting for some major changes to be ready to announce a new stable release soon. 

That said and regardless of the official releases, the master branch (https://github.com/huridocs/uwazi/tree/master) it's consider stable code since it has already gone through QA, testing and has been deployed to production servers (and hot fixed if necessary).

My advice would be to go ahead and upgrade without waiting for major releases.

**Comment by vasyugan** [comment]
> @vasyugan we are waiting for some major changes to be ready to announce a new stable release soon.
> 
> That said and regardless of the official releases, the master branch (https://github.com/huridocs/uwazi/tree/master) it's consider stable code since it has already gone through QA, testing and has been deployed to production servers (and hot fixed if necessary).
> 
> My advice would be to go ahead and upgrade without waiting for major releases.

OK. Have external dependencies changes (mongodb and elasticsearch versions)?

**Comment by vasyugan** [comment]
> My advice would be to go ahead and upgrade without waiting for major releases.

I have made several attempts in upgrading, but each time the result was the same: After setting up the new uwazi from master and importing the Mongo database and documents year, running yarn migrate and yarn reindex, almost everything from the previous version was gone, see #2645 

I would welcome if someone had time and opportunity to look into the issue with me, because I am pretty lost, I have no idea how this can be fixed.

**Comment by vasyugan** [comment]
fixed it now for myself. The problem had to do with the additional complexity of docker.

**Comment by txau** [comment]
@vasyugan is this issue fixed?

**Comment by vasyugan** [comment]
> @vasyugan is this issue fixed?

Yes, thank you very much!
