### ISSUE TITLE
yarn install fails on Debian stretch: error /home/jr/uwazi/node_modules/pngquant-bin: Command failed

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#2646]
I just tried to build uwazi from Master on a Virtualbox VM with Debian Stretch. (I used Stretch rather than Buster because Mongo's packages for buster start at 4.2, while Uwazi wants 4.0)  I installed a minimal Debian system and the dependencies described, including libpng-dev:
`
i  libpng-dev:amd64                     1.6.28-1+deb9u1         amd64                   PNG library - development (version 1.6)`

Yet yarn install fails, here is the output:

```
[11/15] ⠐ mongodb-memory-server
[13/15] ⠐ node-sass
[10/15] ⠐ pngquant-bin
[12/15] ⠈ electron
error /home/jr/uwazi/node_modules/pngquant-bin: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments: 
Directory: /home/jr/uwazi/node_modules/pngquant-bin
Output:
⚠ The `/home/jr/uwazi/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✔ pngquant pre-build test passed successfully
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed

```

**Comment by RafaPolit** [comment]
Please, follow the instructions in the README.  There are a couple of dependencies for those packages as well as, depending on your distro, the need to install build-essential package.

This fail has nothing to do with Uwazi, but with commonly used libraries, so a quick google search of these errors of build will throw quick answers to your required packages missing.

**Comment by vasyugan** [comment]
Sorry, I had the libpng package installed but somehow I had forgotten poppler-utils.
