### ISSUE TITLE
after yarn migrate: yarn reindex fails

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#2647]
This is what I see running yarn reindex after running yarn migrate from uwazi's master branch:

```
root@660bc7a7ab1c:/home/node/uwazi# yarn reindex
yarn run v1.6.0
$ node run.js ./database/reindex_elastic.js
Deleting index... uwazi_development
Creating index... uwazi_development
2019-12-03T20:26:42.754Z [uwazi_development] ERROR Failed to index document 5bbdb69a5d49fb064c80caf6: {
 "type": "illegal_argument_exception",
 "reason": "mapper [metadata.population__estimate__min_] of different type, current_type [text], merged_type [double]"
}
Indexing documents and entities... - 10 indexedd
Done, took 3.999 seconds
Done in 5.38s.

```

Looking in the documents directory, I see that there is no document 5bbdb69a5d49fb064c80caf6.*

**Comment by RafaPolit** [comment]
That is MongoDB document (mongo uses Document to describe each of its individual records)... not a document file in your system. You need to inspect the Mongo collection called "entities" for that ObjectID.  You will find it contains a metadata property which is an object.  The key "population__estimate__min_" will contain a number.   Some of your documents hold a number, some others contain a string for that same property.

You must unify them in order for elastic to correctly index them.  If you run this again without that sanitizing of values, you will end up with a different ID of another casting error.

**Comment by vasyugan** [comment]
> That is a MongoDB document (mongo uses "Document" to describe each of its individual records)... not a document file in your system. You need to inspect the Mongo collection called "entities" for that ObjectID. You will find it contains a metadata property which is an object. The key "population__estimate__min_" will contain a number. Some of your documents hold a number, some others contain a string for that same property.

Well, that sounds like a bug in uwazi then, because all entities that use this property have numbers for it and the template, it is defined as a numeric value. It never was anything else. How come types are mixed? 

> You must unify them in order for elastic to correctly index them. If you run this again without that sanitizing of values, you will end up with a different ID of another casting error.

Well, I have been fiddling around with nosqlclient for a while, but I don't really understand, so I just deleted the document which caused the error. But this doesn't fix it. Still, exept for some unpublished documents all of my content is gone. BTW, I see this now in Uwazi 1.5 as well...

**Comment by txau** [comment]
@vasyugan that is related to how ElasticSearch handles dynamic mapping of properties. We are addressing this issue in #3090 since it has been causing problems in some scenarios. It is indeed a bug in Uwazi.

If you don't want to wait until that patch is shipped, a short term solution would be to somehow make sure that particular property gets mapped as text instead of numeric. You can achieve this by setting up a explicit mapping for Elastic for that particular property in `database > elastic_mapping > base_properties.js`. Something similar to:
```
population__estimate__min_: {
    type: 'text',
    index: true,
    fields: {
      sort: textSorting,
    },
    term_vector: 'with_positions_offsets',
  },
```

note. I haven't tested this solution myself.

**Comment by vasyugan** [comment]
> @vasyugan that is related to how ElasticSearch handles dynamic mapping of properties. We are addressing this issue in #3090 since it has been causing problems in some scenarios. It is indeed a bug in Uwazi.
> 
> If you don't want to wait until that patch is shipped, a short term solution would be to somehow make sure that particular property gets mapped as text instead of numeric. You can achieve this by setting up a explicit mapping for Elastic for that particular property in `database > elastic_mapping > base_properties.js`. Something similar to:
> 
> ```
> population__estimate__min_: {
>     type: 'text',
>     index: true,
>     fields: {
>       sort: textSorting,
>     },
>     term_vector: 'with_positions_offsets',
>   },
> ```
> 
> note. I haven't tested this solution myself.

Thank you. As for me, one of your colleagues (I think it was @konzz ) was so kind to have a look at the DB with me, and I deleted the offending entity, after which the migration went through smoothly

**Comment by txau** [comment]
> Thank you. As for me, one of your colleagues (I think it was @konzz ) was so kind to have a look at the DB with me, and I deleted the offending entity, after which the migration went through smoothly

Ok. That was another solution =) Anyway @konzz is working now on the fix, to be released soon. I'm closing this issue for now.
