### ISSUE TITLE
Table of contents assistant

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#265]
- Design panel with the table of contents
- Be able to delete elements
- Be able to indent elements
- Have button/workflow to add elements to the TOC
- Click on TOC item to go to he section in the doc

**Comment by danicatalan** [comment]
![screenshot 2016-08-22 19 00 50](https://cloud.githubusercontent.com/assets/6364153/17863658/d347329a-689a-11e6-9f31-1afeed301a73.png)

![screenshot 2016-08-22 19 00 35](https://cloud.githubusercontent.com/assets/6364153/17863657/d344afd4-689a-11e6-97c5-b11feb18af63.png)

**Comment by txau** [comment]
Closed in #331
