### ISSUE TITLE
move 'Import' and 'Create new' to where the rest of action buttons are

### ISSUE THREAD

**Issue by simonfossom** [huridocs/uwazi#2652]

**Comment by txau** [comment]
Maybe also the "New" button?

![Screenshot from 2020-01-06 15-30-58](https://user-images.githubusercontent.com/489831/71850280-92d84d00-3099-11ea-99d6-796260fd22ec.png)

**Comment by OzrenMuic** [comment]
> Maybe also the "New" button?
> 
> ![Screenshot from 2020-01-06 15-30-58](https://user-images.githubusercontent.com/489831/71850280-92d84d00-3099-11ea-99d6-796260fd22ec.png)

Yes, makes sense.

**Comment by konzz** [comment]
@OzrenMuic @txau What should we do with the top bar in uploads where those buttons are? remove it? leave it with the text that says "My files" ?

**Comment by simonfossom** [comment]
**Here's new proposal:**

[Private docs redesign figma design](https://www.figma.com/file/IvRY0mPDHdOZz7tZB5kNAg/Untitled?node-id=2%3A38)

See how much you can implement with this issue. 
Comment or ping me for any questions.

**Comment by simonfossom** [comment]
FYI 'search' button should go out everywhere. 
It does nothing.

**Comment by txau** [comment]
Related/dupp: https://github.com/huridocs/uwazi/issues/2769 https://github.com/huridocs/uwazi/issues/2386

**Comment by nwyu** [comment]
Closing this issue in favor of https://github.com/huridocs/uwazi/issues/3384
