### ISSUE TITLE
Can't save entities with custom nested field

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2658]
A partner is receiving a "validation error" when trying to edit an already existing entity with a geolocation property. When viewing the metadata, the geolocation field is present, when editing it the geolocation field disappears, so probably that field is the culprit.

![Image Pasted at 2019-12-11 10-48](https://user-images.githubusercontent.com/489831/70627423-d13e3180-1beb-11ea-9a84-ad9a27143029.png)

**Comment by RafaPolit** [comment]
This is solved on Metadata Object branch, will get fixed when merged.
