### ISSUE TITLE
New API endpoint: query number of references

### ISSUE THREAD

**Issue by OzrenMuic** [huridocs/uwazi#2671]
We need **query by number of references**.  

use case: 
chart shows top 10 most referenced **laws** in **caselaws**

---

Rafa's comment:

_For example, if a law has all 200 countries adhering to it, then that would be the entity with most relationships._

_You want to know: "of this particular type of entity (template), give the ones with most connections to this OTHER type of entity"._

_That is a very 'custom' query, and yes, that would require specific endpoints to pass, for example, the two template criteria.  Or the template and the amount of connections for property X, etc.  This would require new endpoints on the API for sure._

**Comment by txau** [comment]
@ozren isn't that already covered by the aggregations generated by the relationship fields? Following your example:
- Entity A are laws
- Entity B are countries
- Entity A has a relationship field configured for the countries
- The field is set as "use as filter"

This gives this kind of aggregation.

**Comment by RafaPolit** [comment]
For the particular use case that Ozren asked for... actually yes, I think that a 'reverse' interpretation of the aggregations could lead to this answer, yes, with one caveat: this would REQUIRE that the relationship is also created as a metadata property. 

If these are 'free' relationships, then it wouldn't be possible with the aggregation system.

**Comment by txau** [comment]
I wonder if creating the field is a valid workaround?

**Comment by OzrenMuic** [comment]
I just need to know if we can get top 10 most referenced entities from 'Law' template in template 'Caselaw'.

I've copy-pasted Rafa's comment from Mattermost. He said this could be useful. 

You guys will know better how to structure this issue and if we need it or this can already be done.

**Comment by txau** [comment]
@RafaPolit @OzrenMuic can we live with the workaround for now? Reopen if you think that is not the case.
