### ISSUE TITLE
Add action buttons to sidebar

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#268]
- [x] Add edit/save metadata document button
- [x] Add publish/unpublish document button
- [x] Add delete document button
- [x] Add download document button

**Comment by danicatalan** [comment]
@daneryl I included this button inside the sidepanel-footer but I need to get the functions from the floating button, and maybe the tests. Can you check this? It's on https://github.com/huridocs/uwazi/tree/268-edit-metatada-btn

![screenshot 2016-08-14 14 09 03](https://cloud.githubusercontent.com/assets/6364153/17649006/b021cd8e-6228-11e6-9170-c50a6460bb40.png)

**Comment by danicatalan** [comment]
![screenshot 2016-08-15 20 20 00](https://cloud.githubusercontent.com/assets/6364153/17674521/294523d4-6326-11e6-82cd-729c3c1e4142.png)
![screenshot 2016-08-15 20 20 44](https://cloud.githubusercontent.com/assets/6364153/17674522/2946d814-6326-11e6-9c9f-9b2b538abed6.png)
![screenshot 2016-08-15 20 21 01](https://cloud.githubusercontent.com/assets/6364153/17674523/294817c4-6326-11e6-87a7-9ec387c69136.png)

Updated with screens and code on https://github.com/huridocs/uwazi/tree/268-edit-metatada-btn

**Comment by txau** [comment]
@danicatalan I like the idea of the sticky footer with solid background better. Also, the action buttons could be way smaller.

**Comment by txau** [comment]
Closed in #316
