### ISSUE TITLE
Migrate numeric properties to be numbers (not string of numbers) and up the validation to not allow stringified numbers.

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2695]
We are merging a more lenient validation, allowing for numeric fields strings that evaluate correctly to numbers.

This is to prevent validation errors on previously imported CSVs that incorrectly represented numbers as strings.  This has since been fixed, but the underlying data requires migration.

- Migrate every entity's numeric properties to be a number
- if current value is not parseable as number, LEAVE THE STRING, this should fail on validation as it is an incorrect value
- remove the more lenient validation to now allow strings parseable as numbers

**Comment by kjantin** [comment]
I'm trying to import geolocation coordinates for countries into an Uwazi instance (here https://docs.google.com/spreadsheets/d/1oSr-denZweXygvdZRuovOPaMMyXhMPtjWXkNbz_IFGc/edit#gid=786252492) and I receive this error:
![image](https://user-images.githubusercontent.com/354426/73126550-16db7180-3f82-11ea-841d-4fc7e14e21b5.png)

(I'm not able to access the entire error message)

Is this error related to this github issue?

**Comment by RafaPolit** [comment]
@kjantin That appears to be a different issue.  I have created a new issue to track the problem.

**Comment by txau** [comment]
this has been fixed with the static mappings
