### ISSUE TITLE
Fix test warnings and console logs.

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2699]
We have several warnings / errors when launching the battery of tests:

- [ ] hide (for the test) a console log on a migration (metadata entity) - not removing the actual log which is useful
- [ ] Solve the unhandled promise rejection warnings we have
- [ ] Solve recently-added unhandled errors of warnings claiming "Use of expired sessions is not permited"

**Comment by daneryl** [comment]
this is old and the majority of them where solved recently except one, that will be solved by #3566
