### ISSUE TITLE
Multiple issues with inbound connections when they reference the entire document.

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#270]
Inbound connections that reference an entire document have several problems, not only visual but some do affect user interaction.

### Problems with entire-document inbound connections
- It is not visually clear that the connection is global, as there is a 'particular text' referencing this entire document.  We probably need some sort of visual diferentiation.
- The issue still has hover and on-click behaviors but hovering or clicking it highlights nothing (as there is no specific text to highlight - or maybe should it highlight everything? -

These problems are true also for when in 'targetDocument' mode, plus some more serious ones:
### Problems for targetDocuemnts
- There is functionality to select an existing connection by clicking on the card on the left pane, but when this is an all-document connection, the resulting selected text is wrong and matches the position of the selected text on the sourceDocument.

Should we disallow clicking, should we NOT SHOW inbound all-dcoument connections on targetDocument mode?

**Comment by txau** [comment]
First two points are UX issues. We will address them sometime.

3rd point is an actual bug that should be fixed. I think it makes sense to deactivate click for all-document connections when in target document mode.

**Comment by txau** [comment]
Fixed with #281
