### ISSUE TITLE
Counter on the main screen stops at 10'000 (3pts)

### ISSUE THREAD

**Issue by mylaa** [huridocs/uwazi#2708]
Uwazi seems to have a hard-coded imposed limit on its search to determine the counter on the main screen, which stops at 10'000 regardless of the number of records in a collection. 

This needs to be changed, especially for collections where there are 10'000+ records. 

![Screenshot 2020-01-17 at 16 52 35](https://user-images.githubusercontent.com/22371911/72625834-d492ae80-3949-11ea-8956-5f01bc72e5c1.png)

**Comment by konzz** [comment]
This is due to a limitation of size limit in queries to elastic of 10000, it applies to aggregations too, which we get that number from.

**Comment by txau** [comment]
@konzz If we can't display the actual number due to technical limitations, at least we could fix the UX of it by ie, converting that 10.000 in "10.000+ documents". What do you think @mylaa @konzz

**Comment by mylaa** [comment]
Great proposal @jaume, it'll address my concern for the time-being.

**Comment by konzz** [comment]
Sounds good

**Comment by txau** [comment]
@simonfossom what do you think of this solution?

**Comment by simonfossom** [comment]
Sure, as a quick fix. Hope we'll have time to address the underlying issue soon.

**Comment by simonfossom** [comment]
Could we maybe just to take an hour to explore the problem before we jump onto quick fix?

https://discuss.elastic.co/t/how-to-increase-the-default-size-limit-from-10000-to-1000000-in-elasticsearch/208807

**Comment by kjantin** [comment]
Regarding the issue of our "limitation of size limit in queries to elastic of 10000" - is this something we want to address?

**Comment by txau** [comment]
@simonfossom a user may need to have more than 10K results when:
- Exporting as CSV
- Running bulk operations on a big part of the data

While these two can be addressed in several ways, what is the point of having more than 10k results for browsing? The current proposal is that users run searches and filters to narrow down the data they are exploring. The information about the totals is displayed in the filters, on a side panel right beside the results.

**Comment by simonfossom** [comment]
Here for browsing - no. But some users might need the total number for something. (Calculation or something - but this is definitely  not a priority.)

**Comment by RafaPolit** [comment]
Elastic search already returns additional info.  When there are more than 10.000, it returns a "gte" value as part of the response so that users can know there are more than N number of results.

That is really useful to present the `10.000+` scenario.

Also, combined with pagination (which is 90% implemented on the API), could lead to easier queries for those needing more than the 10.000 results, but not all at the same time.

Perhaps implementing that as part this issue is enough to have every scenario covered?
