### ISSUE TITLE
Colors asigned to templates disappeared

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2712]
Templates that previously had a color assigned have no color now (it should appear to the right of the title):

![Screenshot from 2020-01-17 13-50-33](https://user-images.githubusercontent.com/489831/72641726-67beea80-3930-11ea-8484-c1be94d1dc32.png)

**Comment by kjantin** [comment]
![image](https://user-images.githubusercontent.com/354426/76246028-5a78fa80-6213-11ea-8bb6-6603158bd02e.png)

I confirm that this is a problem.

**Comment by txau** [comment]
Fixed as a side effect of other patch.
