### ISSUE TITLE
Filtering date range - Error message

### ISSUE THREAD

**Issue by AlWalid** [huridocs/uwazi#2726]
![Screenshot 2020-01-22 at 11 27 46](https://user-images.githubusercontent.com/504692/72886327-e25d8080-3d09-11ea-9428-daa10bd85db2.png)

- The bug is happening when searching a date range
- This was reported on a private instance after latest deployment, however I am not sure if it is related to it
- Private instance

**Comment by konzz** [comment]
Fixed by #2716 will be deployed soon.

**Comment by AlWalid** [comment]
Thanks for the update!
