### ISSUE TITLE
Unable to remove a field

### ISSUE THREAD

**Issue by Ilyes-Chiha** [huridocs/uwazi#2734]
* I created a template with different fields
* The filed is not showing anymore on the template but still showing in the translation
* Given that this specific field was created in Arabic , the translation do not commit and generate an error
* I am not able to translate and not able to remove that specific field so the translation process can be finished
* It is a private instance

**Comment by txau** [comment]
@Ilyes-Chiha thanks for the detailed report. I think this is the result of an unfortunate combination of two flaws in Uwazi at the moment:

- The bug with the Arabic field names, reported here: https://github.com/huridocs/uwazi/issues/2358
- The inability  of Uwazi for deleting translations, therefore, tossing a validation error (I presume?)

Fixing either of these issues will unblock your instance. I'd like @RafaPolit to confirm if this is the case.

**Comment by RafaPolit** [comment]
Yes, indeed, this is correct.

All template property names should avoid non-latin characters for the time being, we apologize for this condition.  

Can you try deleting the property from the template? Delete, and save.  That should delete the translation key.  Afterwards, re-create the property, using latin charactes.  Afterwards, go into the translation and assign the Arabic translation to that property.

That should work.

**Comment by Ilyes-Chiha** [comment]
@txau 
 @RafaPolit 
Dear Jaume and RafaPolit

Thank you for your feedback. The difference is that in the template which is the default entity in the system, we delete the only field in Arabic character and we left only the fields in Latin characters. However, in translation the field we deleted always exists. So we have 22 fields in the template versus 23 fields in the translation of the template fields.

Thank you,
Ilyes Chiha

**Comment by RafaPolit** [comment]
We have some pending development regarding properties with non latin characters, and translations as well.  Sorry for all the trouble.

Do you have a tech-savvy person in your group that could delete inside the database that translation?  We could provide detailed instructions, but we would need to know some ID's and names to accomplish this at this point.  

Do you have a lot of documents currently in the dabatase?

**Comment by RafaPolit** [comment]
(By private instance I understand you are hosting this collection, and not us, right?, because if we are hosting this, we can just go in an fix it).

**Comment by txau** [comment]
@Ilyes-Chiha I guess since you are blocked, the fastest workaround is to fix the field in the database. If your instance is hosted with us, please let us know and we will unblock it.

**Comment by txau** [comment]
Since the issue with the Arabic names is already reported here: https://github.com/huridocs/uwazi/issues/2358 I'm closing this issue for now.

Please @Ilyes-Chiha let us know if you need assistance with the database fix.

**Comment by Ilyes-Chiha** [comment]
@txau  @RafaPolit
Dear Jaume and Dear Rafael  

first of all thank you for your interest and speed of response. I apologize for the late reply. I took a few days off from work, i see that my ticket #2734 is closed and i understand that it is linked with [#2358](https://github.com/huridocs/uwazi/issues/2358) bug ( or it is a consequence one). So, despite the closing of the ticket I have a few talking points
1.  i need to remove all arabic fields and replace it with Latin one to fix this problem. please, if you can help me to replace it directly on database. our instance is dchr.uwazi.io . I Will provide further details if you which. this is screen shot will probably help you
![error1](https://user-images.githubusercontent.com/59965164/73352446-688d4000-4291-11ea-8477-ea25a5d234b4.png)
2. i propose that you  setting up a procedure which prevents the creation of new entity in non-Latin language (Arabic or other which can cause problems later until you will surely find a solution to this bug # 2358)

Thank  you
Ilyes CHIHA

**Comment by RafaPolit** [comment]
Thank you for the detailed explanation.  We can work on this directly.  This will be ready in a few hours.

**Comment by RafaPolit** [comment]
I have removed the offending keys in the Database.  Can you please try now and see if things work as expected?

**Comment by Ilyes-Chiha** [comment]
> I have removed the offending keys in the Database. Can you please try now and see if things work as expected?

just 10 min i check

**Comment by Ilyes-Chiha** [comment]
> > I have removed the offending keys in the Database. Can you please try now and see if things work as expected?
> 
> just 10 min i check
Thank you @RafaPolit  the translation is done and i don't have error message
In this case i can delete the problematic field however in other similar cases which I can neither delete the field nor the template itself or thesauri, they contain sensitive information and i have no backup

**Comment by RafaPolit** [comment]
I'll ask your PM within HURIDOCS to contact you, we will find a way to migrate the data or fix the keys by hand.  We have a safe area where we can discuss these so as to not expose sensitive information here on GitHub.

I'll close this issue for now.  Sorry for the inconveniences and thanks for your patience.

**Comment by Ilyes-Chiha** [comment]
thank's a lot
