### ISSUE TITLE
Error trying to import geolocation coordinates for countries into an Uwazi

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2739]
I'm trying to import geolocation coordinates for countries into an Uwazi instance (here https://docs.google.com/spreadsheets/d/1oSr-denZweXygvdZRuovOPaMMyXhMPtjWXkNbz_IFGc/edit#gid=786252492) and I receive this error:
![image](https://user-images.githubusercontent.com/354426/73126550-16db7180-3f82-11ea-841d-4fc7e14e21b5.png)

(I'm not able to access the entire error message)

Is this error related to this github issue?

_Originally posted by @kjantin in https://github.com/huridocs/uwazi/issues/2695#issuecomment-578437478_

**Comment by RafaPolit** [comment]
I believe that the presence of “non assigned values” in the CSV could be causing the issue.

**Comment by daneryl** [comment]
@RafaPolit @kjantin errors were caused by csv importer itself, it was creating the geolocation objects not matching the validation, lat and lon were strings instead of numbers, fix on this PR #2800 , i have included an integration test for this to have better feedback in case validation changes.
