### ISSUE TITLE
Allow document viewer to show documents in different languages

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2741]
We need to be able to navigate to a document and select which language version we want displayed on the viewer.

- Default should be the same language as the UI
- Fallback should be default collection language
- you can change to whatever language you want

This opens up the possibility of having text references from documents in any language to any other language (including versions of the same document in different languages) and also frees the user interface language from the files.  Right now, adding a new language to the system required dubious flows of duplicating an existing file.  That will no longer be the case.

This is a major improvement in the documents flow.

This also resolves #2221

**Comment by txau** [comment]
@RafaPolit if I recall correctly, we agreed to leave the constrain UI language-document language as it is now, since it is easier to implement. The 3rd point you mentioned is desirable but unessential. Did anything change?

**Comment by RafaPolit** [comment]
Several things:
- There was going to be a lot of logic on which file to show if there is not an exact match on UI languages
- Once you do that, some PDFs could become inaccessible from the UI
- If a particular document is not present in the current UI language... in what language will you be creating the text relationships? (this is also true as of today, and it is the wrong approach)

So, instead of developing half-way functionality that will need to get addressed further down the road, we decided that doing the ACTUAL implementation of decoupling the languages was almost as much effort, if not less in some cases.

There are some issues on Elastic Indexing that are not yet fully solved, but @daneryl already has a plan to do incremental tests to see where he needs to stop in terms of the ES indexing.

**Comment by kjantin** [comment]
Hi @daneryl - it looks like this feature is almost complete - is that the case? Can you share a quick update? Thanks!

**Comment by daneryl** [comment]
hi @kjantin, not complete yet, still working, we expect to finish it by the end of the week
