### ISSUE TITLE
Adding language is not duplicating all data

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2743]
Check that adding a language is correctly duplicating all existing data.

**Comment by gabriel-piles** [comment]
In one run, this error appeared when adding Spanish to an instance only in English and 116827 entities

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x3f607a7dbe3d]
    1: StubFrame [pc: 0x3f607a7c09d2]
    2: StubFrame [pc: 0x3f607a81dbef]
Security context: 0x1d456c29e6e9 <JSObject>
    3: resolveProp(aka resolveProp) [0x1d451433b1d1] [/Users/gabrielpiles/projects/uwazi/app/api/entities/entities.js:36] [bytecode=0x1d45b1d2d6e9 offset=224](this=0x1d45bcb826f1 <undefined>,key=0x1d456c2b1f01 <String[4]: body>,value=0x1d45c36d0489 <JSArray[1]>)
    4: /* anonymous *...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10003d041 node::Abort() [/Users/gabrielpiles/.nvm/versions/node/v10.17.0/bin/node]
 2: 0x10003d24b node::OnFatalError(char const*, char const*) [/Users/gabrielpiles/.nvm/versions/node/v10.17.0/bin/node]
 3: 0x1001b8e25 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/gabrielpiles/.nvm/versions/node/v10.17.0/bin/node]
 4: 0x100586d82 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/gabrielpiles/.nvm/versions/node/v10.17.0/bin/node]
 5: 0x100589855 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/Users/gabrielpiles/.nvm/versions/node/v10.17.0/bin/node]
 6: 0x1005856ff v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/gabrielpiles/.nvm/versions/node/v10.17.0/bin/node]
 7: 0x1005838d4 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/gabrielpiles/.nvm/versions/node/v10.17.0/bin/node]
 8: 0x10059016c v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/gabrielpiles/.nvm/versions/node/v10.17.0/bin/node]
 9: 0x1005901ef v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/gabrielpiles/.nvm/versions/node/v10.17.0/bin/node]
10: 0x10055fb34 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/Users/gabrielpiles/.nvm/versions/node/v10.17.0/bin/node]
11: 0x1007e7e14 v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/gabrielpiles/.nvm/versions/node/v10.17.0/bin/node]
12: 0x3f607a7dbe3d

**Comment by gabriel-piles** [comment]
Decreasing from 100 to 50 the batch in the creation of entities in a new language solves this problem in the short term, but a better way should be implemented.

app/entities/entities.js

 ''' async addLanguage(language, **limit = 50**) {
    const [lanuageTranslationAlreadyExists] = await this.get({ locale: language }, null, {
      limit: 1,
    });
    if (lanuageTranslationAlreadyExists) {
      return;
    }
```

One idea is to instead of having a fix bach size, calculate the batch size using the size of the data
