### ISSUE TITLE
Reindex based on "size" instead of amount

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#2746]
After studying the reindex memory consumption, the batch size affects the memory heap consumption. To avoid out of memory errors from elastic, the batch size should be based on "size" of these entities, rather than amount.  

Related to #2745

**Comment by RafaPolit** [comment]
How would you accomplish this? Appending to a buffer one entity at a time, and count the size?  Have you thought of any approach at all?  This sounds like an interesting challenge.

**Comment by txau** [comment]
@RafaPolit I guess the very basic idea is what you mentioned. If there are performance problems related to this approach I'm pretty sure we can come to a smarter approach. The point is to keep the size always under control.
