### ISSUE TITLE
Highlights on docs require extra click to show

### ISSUE THREAD

**Issue by MatelSow** [huridocs/uwazi#2749]
When document is in regular "view" mode, highlights do not appear. Only when the references view is turned on do highlights show. Is this how it was intended?
![1](https://user-images.githubusercontent.com/56391759/73674184-4429cd00-46b0-11ea-929d-27dfdfe40c75.png)
![2](https://user-images.githubusercontent.com/56391759/73674190-47bd5400-46b0-11ea-9fa9-f4ebc58e6492.png)

**Comment by txau** [comment]
I guess that was intended, yes. What is all that blue background?

**Comment by MatelSow** [comment]
The blue background is just from my computer. I was using two monitors.
@txau is this something we would be interested in discussing further as it's both a partner request but also a ux/ui issue for end users. They might miss all the references on a particular doc, altogether. That would be a shame given the work that goes into creating those references.

**Comment by txau** [comment]
@MatelSow I understand your concern. On the other hand, when the text references are big chunks of text, you get all the interface polluted with highlights. So I guess we need @OzrenMuic to give it a thought.

**Comment by simonfossom** [comment]
If you ask me highlights should be always visible. 

There is no overlap of information with other tabs so there is no reason to hide it when you are in any other tab.

**Comment by txau** [comment]
@simonfossom when there are multiple highlights to big chunks of text (ie, when a whole legal article is being referenced) you risk to have all the document highlighted at all times. Ie. check some of the pages of this documents: https://ihrda.uwazi.io/en/entity/ofdfmorlv3qxytd284xxswcdi?page=16 And some documents have hundreds of references.

**Comment by txau** [comment]
@MatelSow @simonfossom closing as this is getting stale. Reopen if you consider it necessary.
