### ISSUE TITLE
Improve the workflow for adding information to Uwazi that will live in multiple, related entities

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#2750]
As a user, when I want to add information about a violation, I need to add information about the victim in an entity then publish, then I add info about the perp in another entity and then publish, then I add info about the event in another entity and then publish...and then finally I create the relationships between them. It's a very tedious process. 

One idea to address this is "Be able to add/edit entities from the relationships view" (as @txau describes it) - so that as a user I can create the event entity, then look for any existing entities I want to connect it to, and if those entities don't exist yet I can create them there from the relationships tab.

**Comment by kjantin** [comment]
Next steps on this one:
* organise a meeting to get on the same page with UX
* UX to design wireframe

**Comment by kjantin** [comment]
It would be really good if we could figure out a way to avoid creating duplicates. Currently, it's very difficult to find the right entity that you want to connect an entity to (if there are 1000 people named John, it will take a very long time to scroll through all of those entities, and if there are 10 people named John Smith, it is impossible to tell one apart from each other because you can only see the title of the entity). There is probably a github issue on this - but I can't find it at the moment. 

So I wonder if there can be an easy workflow so that before someone creates a new entity, they are asked to find out if it already exists, or as they are typing a title (or another property), the system can suggest existing entities that already exist (kind of like it does here in github before you add new issue!). (this is a feature that is being requested by a partner)

**Comment by kjantin** [comment]
[Notes from design meeting] 
What a user will be able to do:

- When a user is on the relationship tree/panel, they are able to create new entities. 
- As they are going through the process of creating a new entity, they should be able to find out if the entity already exists in the database. One idea for this is to have an automatic look-up functionality that will look for existing entities as you start typing the title. Rafa said this look-up functionality would not be too difficult to develop. 
- Eventually, it would be helpful for the admin to be able to configure a structure of entities + relationships. For example, you can configure a "case" entity template to identify the entities that this is usually related to. So that, when you go to the relationships tree, you already see pre-configured empty placeholders where you add those entities. So a "case" entity would have an empty place holder for "perpetrator" entity, and one for "victim" entity. (You can also create a brand new entity that is not included in this pre-configuration.)
- Should the admin be able to create entity templates or template-less entity from the relationship tree? This is probably too complex for this stage. 
- The risk with this approach is that it is more likely that users will create duplicates. 
- Do we need to stick with the side panel approach? Using the existing side panel approach would make it easier for the sake of consistency. 

Next steps:
- Simon will put together some design proposals.

**Comment by kjantin** [comment]
Hi @simonfossom - there is another feature request that has been shared by several organisations, to have an automated unique ID property that can be assigned to specific entity templates. One of the reasons people have requested this is because it can be really tough to find the entity you are looking for when you search for it as you are creating a relationship between two entities. What people need is an easier way to distinguish one entity from another, without relying on just the words/phrase in the title field. I wanted to flag it here because it might be related to the design for this workflow. More info: https://github.com/huridocs/uwazi/issues/1173#issuecomment-603458753

**Comment by simonfossom** [comment]
@kjantin unique id, it seems to me, is not directly linked with this issue. Although it is connected to user flow of finding entity in connections. We'll try to resolve #1173 without adding unique id and see if more requests for unique id comes afterwards.

**Comment by txau** [comment]
This feature has been developed and deployed.
