### ISSUE TITLE
Structure synchronisation without data, to multiple Uwazi instances

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#2753]
The approach that has been discussed so far:

There is a "master structure", where the admin will create the thesauri, connection names, templates. This will be synced into each Uwazi instance - each of these Uwazi instances is a "data-holder instance", where no configuration will be modified -- **only the data** will be entered/edited.

Example from the CYRILLA project:

![image](https://user-images.githubusercontent.com/354426/73844353-6b86b400-47ee-11ea-8b61-bc37e835c189.png)

**Comment by kjantin** [comment]
Next step: After we're able to sync the structure, we designate the "parent" instance and the "child" instances and sync the data.

**Comment by RafaPolit** [comment]
We have gone with a different route for this particular scenario, which is to use a master instance and have individual synced instances that hold only partial data through conditional sync #3270 .

Still, using conditional sync this could be achieved if no entity passes the conditional comparator.
