### ISSUE TITLE
remove specific wait from e2e waitToClick helper

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazi#2760]

**Comment by txau** [comment]
@daneryl can you provide some explanation for this issue?

**Comment by daneryl** [comment]
@txau specific wait time on the e2e is prone to errors on different environments, waitToClick is a custom action that waits for a specific selector on the page, but also contains a specific time to wait, i do not know why but in principle it should not.

https://github.com/huridocs/uwazi/blob/c6f298c2acc23b9db81c95347a009c7cb9d70c8b/nightmare/helpers/extensions.js#L137-L146

**Comment by txau** [comment]
We are addressing this in the new e2e.
