### ISSUE TITLE
Remove 'Search' flouting action button

### ISSUE THREAD

**Issue by simonfossom** [huridocs/uwazi#2769]
It does nothing

**Comment by txau** [comment]
@simonfossom actually it does the same as the magnifying glass icon inside the search box. Still we can remove this one. Adding a screenshot for clarification.

![Screenshot from 2020-03-07 10-15-06](https://user-images.githubusercontent.com/489831/76146885-9f0e6580-605c-11ea-8ce6-2a1bdb0c3c82.png)
