### ISSUE TITLE
Allow configuring colors in BarChart

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2775]
We have configurable colors in PieChart and FreeBarChart.  That exact same functionality needs to be included in the regular BarChart.  The implementation is identical to the FreeBarChart.

**Comment by fnocetti** [comment]
Now you can provide colors to the chart as you do with FreeBarChart.
You need to provide a comma-separated list of values in the "colors" attribute of the component. If no color is provided it will fallback to the default dark blue.

**Comment by txau** [comment]
@fnocetti thanks for explaining. Can you provide a code sample?

**Comment by fnocetti** [comment]
Done. Edited my previous comment.
