### ISSUE TITLE
When completing metadata on a document, ask me, if I want to publish?

### ISSUE THREAD

**Issue by whyfrycek** [huridocs/uwazi#278]
When I complete adding metadata to a document, usually I want to publish it right away. Would it make sense to add a dialogue after saving to ask whether I want to publish?

Right now, I need to find the document again, which takes some orientation if I have many pending ones.

**Comment by txau** [comment]
We are currently working on this issue. In the same metadata side panel you will have both save and publish options (publishing will save right away).

@danicatalan

**Comment by whyfrycek** [comment]
Awesome!
