### ISSUE TITLE
yarn migrate hangs at  UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'contexts' of undefined, run-production fails

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#2780]
This occurred while upgrading from 1.5 to master:

(I had already upgraded mondodb to 4.0.x following the upgrade instructions as well as elasticsearch to 7.x

```
metadata-structured-object...
(node:29017) DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use Collection.countDocuments or Collection.estimatedDocumentCount instead
(node:29017) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'contexts' of undefined
    at contexts (/home/jr/uwazi/app/api/migrations/migrations/17-metadata-structured-object/index.js:24:17)
    at getContext (/home/jr/uwazi/app/api/migrations/migrations/17-metadata-structured-object/index.js:63:29)
    at Array.map (<anonymous>)
    at map (/home/jr/uwazi/app/api/migrations/migrations/17-metadata-structured-object/index.js:50:13)
    at resolveProp (/home/jr/uwazi/app/api/migrations/migrations/17-metadata-structured-object/index.js:101:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:29017) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 59)
(node:29017) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^[OR^[[1;6Qntities.metadata -> 1000 / 1254


```

**Comment by vasyugan** [comment]
So this is the function where it hangs at: 

```
[function getContext(translation, contextId = '') {
  return (
    translation.contexts.find(ctx => ctx.id.toString() === contextId.toString()) || { values: {} }
  );
}
]
```

**Comment by vasyugan** [comment]
yarn run-production also fails therefore:

```
yarn run-production
yarn run v1.21.1
$ export NODE_ENV=production; node server.js
==> Connecting to mongodb://localhost/uwazi_development
==> Processing system keys...
(node:21847) DeprecationWarning: Mongoose: `findOneAndUpdate()` and `findOneAndDelete()` without the `useFindAndModify` option set to false are deprecated. See: https://mongoosejs.com/docs/deprecations.html#-findandmodify-
==> Your database needs to be migrated, please wait.
metadata-structured-object...
(node:21847) DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use Collection.countDocuments or Collection.estimatedDocumentCount instead
(node:21847) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
2020-02-21T12:48:13.649Z [localhost] 
uncaught exception or unhandled rejection, Node process finished !!
 TypeError: Cannot read property 'contexts' of undefined
    at getContext (/home/jr/uwazi/prod/app/api/migrations/migrations/17-metadata-structured-object/index.js:24:17)
    at Promise.all.value.map (/home/jr/uwazi/prod/app/api/migrations/migrations/17-metadata-structured-object/index.js:63:27)
    at Array.map (<anonymous>)
    at resolveProp (/home/jr/uwazi/prod/app/api/migrations/migrations/17-metadata-structured-object/index.js:50:11)
    at Object.keys.reduce (/home/jr/uwazi/prod/app/api/migrations/migrations/17-metadata-structured-object/index.js:101:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 
```

**Comment by txau** [comment]
@vasyugan is this still happening?

**Comment by vasyugan** [comment]
> @vasyugan is this still happening?

Indeed, it is. A while ago I sent a copy of our database to @konzz , he offered to look into it, because I am pretty lost. I don't know if he already found the time to do so.

**Comment by vasyugan** [comment]
Tried again with release version 1.6, still unchanged. So far, I haven't heard back from @konzz 
Maybe, could we have another look?

**Comment by vasyugan** [comment]
Same with master, just tried.

**Comment by vasyugan** [comment]
On the face of it, it seems to have something to do with translations. it references line 63 of app/api/migrations/migrations/17-metadata-structured-object/index.js which is part of a function thatgoes:

```
        if (prop.content && ['select', 'multiselect'].includes(prop.type)) {
          const dict = dictionariesByKey
            ? dictionariesByKey[prop.content]
            : await db.collection('dictionaries').findById(prop.content);
          if (dict) {
            const context = getContext(translation, prop.content);
            const flattenValues = dict.values.reduce(
              (result, dv) => (dv.values ? result.concat(dv.values) : result.concat([dv])),
              []
            );
            const dictElem = flattenValues.find(v => v.id === elem.value);

            if (dictElem && dictElem.label) {
              elem.label = translate(context, dictElem.label, dictElem.label);
            }
          }
```
But could you maybe assist me in narrowing it further down? @konzz

**Comment by fnocetti** [comment]
Hi @vasyugan, I will continue to follow up with your issue.
I'll keep you posted on my findings.

**Comment by fnocetti** [comment]
@vasyugan after looking at your DB, you have configured 4 languages but many entities/documents have translations for 2 extra languages that are not present in the DB.

To solve the problem you will need to:

1. Delete from the Mongo DB the entity records that correspond to those languages from the entities collection.
1. Run `yarn migrate` to continue the migration process
1. Run `yarn reindex` to update your search indexes

You should be able to get your instance running after following those steps.

You can check which are the extra languages I'm referring to by querying any entity by its sharedId in the MongoDB. For example:

1. Run `db.getCollection('entities').find({})`
1. Inspect the first result and keep its sharedId.
1. Run `db.getCollection('entities').find({sharedId:"YOUR-SHARED-ID-HERE"})`. It should return 6 results, each corresponding to a different translation of the entity/document. Check the `language` field and look for the 2 that are not configured in your Uwazi collection.

Then, to delete the translations for those languages you will need to run:
```
db.getCollection('entities').remove({ 'language' : {'$in': ['LANG1','LANG2']} });
```
where LANG1 and LANG2 are to be replaced with the language codes shown in the entity's language field for the unneeded translations.

> OF COURSE, THIS WILL ERASE DATA, SO I RECOMMEND SAVING A BACKUP FIRST

Also, it would be really useful for us if you have any clue on how you got to that DB state.

- Where those languages configured and deleted afterwards?
- If so, did you deleted them by directly interacting with MongoDB or through the Uwazi UI?
- Can you remember if this conflicting entities were created before or after those languages existed in your system?

**Comment by vasyugan** [comment]
Wow, thanks!! 

Indeed, Aymara (ay) and Quechua (qu) were the two culprits... Thanks so much for looking into this! I sincerely hope you didn't spend too much time on it.

@fnocetti 
> Also, it would be really useful for us if you have any clue on how you got to that DB state.
> 
>     * Were those languages configured and deleted afterwards?

I guess so, although I don't remember. Since the project is focused on indigenous peoples in South America, I may have added those two languages at some point, but soon realized that we won't be able to service them.
 
>     * If so, did you deleted them by directly interacting with MongoDB or through the Uwazi UI?

Certainly through Uwazi's web ui. I know very little about Mongo and won't thouch a DB directly unless that's absolutely necessary.

>     * Can you remember if this conflicting entities were created before or after those languages existed in your system?

No, unfortunately, since I don't remember at which point I added the languages, apart from that I must have done so, obviously.

**Comment by fnocetti** [comment]
I'm glad your issue is solved and greatly appreciate your input!
I'm closing this issue now.
