### ISSUE TITLE
Allow admins to import attachments (images and other files) during csv import

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#2782]
As an administrator of an Uwazi instance that would like to migrate thousands of entities that have files attached to them (mostly images), I want to be able to migrate these files and reflect their connection to the respective entity (without having to upload these attachments manually). 

Note from Rafa: we need to keep in mind that attachments could belong to one or more languages, so this should be reflected in the import which is going to be the only tricky part.

**Comment by RafaPolit** [comment]
This is being worked on.

The team has talked about allowing attachments to attach ONLY to all languages, and have decided on a procedure to unify DOCUMENTS and ATTACHMENTS so they are stored together with flags to differentiate them.

**Comment by daneryl** [comment]
PR is ready, small documentation on how to use on the PR #2889
