### ISSUE TITLE
Reindex is triggered when configuring a relationship field as not filter and it should NOT

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2783]
1. Configure a relationship from an entity as "use as filter" and save.
2. Set the same property as not "use as filter" and save.

This triggers a reindex that should not be happening.

**Comment by txau** [comment]
Related/dupp: https://github.com/huridocs/uwazi/issues/2403

**Comment by txau** [comment]
Related: https://github.com/huridocs/uwazi/issues/897

**Comment by RafaPolit** [comment]
First approach:
- [ ] Create a list of non-critical actions that will not require a reindex: ie: Assigning a new property as filter, reordering field order, select a property as priority sorting, etc.

Look into this and compile a list, then implement that if ONLY those changes have happened, there should not be a reindex of all those entities.

**Comment by txau** [comment]
Closing in favor of: https://github.com/huridocs/uwazi/issues/3611
