### ISSUE TITLE
Instead of having one default template, this instance has multiple default templates

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#2784]
Since a few weeks ago, an Uwazi instance now has more than one default template:

![image](https://user-images.githubusercontent.com/354426/75406008-5678de80-58dd-11ea-940d-1c018b4651bf.png)

**Comment by RafaPolit** [comment]
I have modified the database directly.  Lets keep an eye open as to how that could have happened.  I'm closing this for now.
