### ISSUE TITLE
Display a "show less" button at the end of a list of items after clicking on "show more" button

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#2785]
As a user, I need to click on "show more" in order to see the full list of options in a drop down property:

![image](https://user-images.githubusercontent.com/354426/75406207-e028ac00-58dd-11ea-95a1-9ee2108696b8.png)

...and now that I have selected an item from the list, I want to be able to click on something like a "show less" button because this is such a long list of items so it's easier for me to see all the properties on this form. 

![image](https://user-images.githubusercontent.com/354426/75406288-19f9b280-58de-11ea-9d80-f7cd4ab7d329.png)

**Comment by RafaPolit** [comment]
This has been implemented as part of #2828
