### ISSUE TITLE
Custom Public Form

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#2794]
Create a custom PublicForm that has a wizard system to be filled. It also should send an email with custom text (that will have part of the information) to the submitter and to an Uwazi admin of that instance that will be specified.

The form will have a  field that it's automatically filled with an autogenerated friendly ID.

IDs should be numbers in sequential order + the year like 107-2020 or 23-2020 or 1018-2020
The filter for this field should be a text input where users can type the exact ID: "107-2020"
The field should be disabled so users can't edit it.

@simonfossom  This will need some designs.

Ask for text and designs before starting.

**Comment by kjantin** [comment]
@konzz regarding your statement above
>IDs should be numbers in sequential order + the year like 107-2020 or 23-2020 or 1018-2020

Is this something that the partner specifically requested?

**Comment by konzz** [comment]
No, but if I remember correctly that's how they ID now their complaints.

**Comment by kjantin** [comment]
Hi @konzz - this feature is being requested by at least 6 different partner organisations. The more common feature is being tracked here - https://github.com/huridocs/uwazi/issues/1173. Do you think we would be able to implement this feature for all users? This has been discussed a few times also with @RafaPolit and he thought it shouldn't be too difficult.

**Comment by konzz** [comment]
Yes, the unique ID field can be implemented as a general feature for Uwazi or as a custom code inside this issue. I think there is an ongoing conversation about what will be, based on those requests

**Comment by simonfossom** [comment]
The difference is that this partner needs ID to be a metadata and others are looking for a way to get unique ID for entities to find them more easily. This two requests are not the same!

**Comment by txau** [comment]
> The difference is that this partner needs ID to be a metadata and others are looking for a way to get unique ID for entities to find them more easily. This two requests are not the same! Please correct me if I'm wrong.

That is true, but I wonder if we can merge both into a single one.

**Comment by simonfossom** [comment]
I guess it could be if they are ok to use autogenerated hash that they can find under any entity as ID of a case 🤔 
@MatelSow would that be something they would consider? 
I can't see why not.

**Comment by RafaPolit** [comment]
Since the 'unique ID' can take many, many forms and configurations (I want sequential numbers, no... I want alphanumeric random 8 characters, no... what is needed is a time-based value)... wouldn't it make sense to just code into the javascript of the page of the form this auto-generated value with whatever they want, and just be sent with the rest of the form?

That way we don't pollute the base code with this issue until it is formed in a way that works for most use cases.

**Comment by txau** [comment]
@RafaPolit yes if we are only solving the public form, the question is whether there is a broader need for an auto-generated unique id. In that case, shall we cover all those different formats, or propose a particular one and ask users to stick to that one?

**Comment by MatelSow** [comment]
For this particular partner, there is no particular format required. @konzz suggested a short, random, 5-digit alphanumeric code which they have accepted.

**Comment by simonfossom** [comment]
@konzz @txau if this is specific to one partner shouldn't it be in GitLab? 

---

> a short, random, 5-digit alphanumeric code which they have accepted.

@konzz @MatelSow where is this documented?

**Comment by nwyu** [comment]
This custom work has been completed for this client. Closing this issue.
