### ISSUE TITLE
Users see "Could not reach server, please try again later" message after log-in

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#2798]
There are a number of Uwazi instances for which when I log-in, I see a message for about 5 seconds that says "Could not reach server, please try again later", but then everything works fine. This has been happening for about 2-3 months. I don't think it's causing any problems, but it is confusing to see this message when there is actually nothing wrong.

**Comment by txau** [comment]
Apparently only happening in private instances, the message appears for a moment when redirecting from login to the default URL.

**Comment by elric-wamugu** [comment]
The issue is triggered by calling reloadHome() after resolveSuccessfulLogin and happens only in the Firefox browser. More context of the issue here https://medium.com/vinh-rocks/how-to-handle-networkerror-when-using-fetch-ff2663220435
