### ISSUE TITLE
Improve ES reindex settings

### ISSUE THREAD

**Issue by albert-a09** [huridocs/uwazi#2808]
In order to speed up ES reindex speed we should use 3 shards and 0 replicas.

Required settings: 
```
'index.number_of_replicas': 0,
'index.number_of_shards': 3,
```
after `'index.mapping.total_fields.limit': 2000`, in `database/elastic_mapping.js`

**Comment by RafaPolit** [comment]
But this needs to be configured as that four our own pipeline only!  We are maintaining at the same time an Open Source project as well as a psuedo-SaaS within ourselves.  We cannot just 'change' that for everyone if they are not using sharded ES servers.

**Comment by txau** [comment]
Will adding that config fail if the ES server has no replicas and shards?

**Comment by txau** [comment]
@albert-a09 where the number of shards 3 coming from? why that particular number?

**Comment by txau** [comment]
After running some tests locally:
- It doesn't have any negative impact on stand alone ES install.
- It does increase the indexing speed locally as well.

Allegedly the default value for number of shards is 5, but running some benchmarks on different numbers of shards I realized that for whatever reason we have a default of 1, thus we don't benefit from parallel computing the reindexes. Hence the increase in reindex performance locally is coming from number of shards = 3.

**Comment by txau** [comment]
> @txau i thought we want the ES config only for reindex time ? don't we have more replicas/shards than that ? also what happens when we want a different configuration and at the same time they want faster indexing speeds.

@daneryl regarding the amount of shards, I already asked @albert-a09 about that number. Regarding the replicas I thought we agreed not to have replicas? I'd like to know @albert-a09 option on that as well.

Implementing this only at re-index time should be easy since the code for re-indexing is isolated in database > reindex_elastic.js

**Comment by txau** [comment]
@daneryl I think on the short term we are going to be ok with 3 shards and 0 replicas. I rather see this PR through and discuss whether we want to have replicas or a different numbers of shards.

**Comment by albert-a09** [comment]
@txau we have 3 data server, so in case of 3 shard they will be used in parallel. Yes there is not so much performance difference between 2 and 3 shards but they are.

**Comment by daneryl** [comment]
@txau @albert-a09 @rafa merging this, if at some point we or someone need a different config  we can work on having this configured only on reindex and when finished set the original config back
