### ISSUE TITLE
Inherited properties not showing on several places

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2815]
On library and uploads, if I click on an entity with inherited property, the values are correctly populated on the side panel.

If I do the same on the relationships panel, the values are not showing on the side panel.

If I go into the Entity view, they are also not correctly populated.

**Comment by RafaPolit** [comment]
There are now a few key instances using iheritance.  Perhaps we need to move this into the sprint pipeline? @txau

**Comment by RafaPolit** [comment]
This is still happening on the cards and relationships side panel entity view.

**Comment by daneryl** [comment]
can not replicate, probably already fixed by #3602
