### ISSUE TITLE
Correct the title

### ISSUE THREAD

**Issue by simonfossom** [huridocs/uwazi#2818]
Change names of _**Relationship types**_ to _**Connections**_ or other way around - they cannot be different.

<img width="542" alt="Screenshot 2020-03-15 at 21 00 12" src="https://user-images.githubusercontent.com/8134850/76709619-675c8900-6700-11ea-94c0-788d6e865677.png">

**Comment by txau** [comment]
I used the same translation key as in the side panel menu, this way they are always in sync. Although this leaves an entry in translations for "Connections" that may not be used at all. I guess this is a different topic that needs to be addressed.
