### ISSUE TITLE
missing icon on connections

### ISSUE THREAD

**Issue by simonfossom** [huridocs/uwazi#2819]
This square icon is actually missing icon, right? 

![image](https://user-images.githubusercontent.com/8134850/76712365-7b13e980-6718-11ea-8bfd-e738c07fdb43.png)

**Comment by txau** [comment]
It is displayed like this to me. It may be related to https://github.com/huridocs/uwazi/issues/2242.
![Screenshot from 2020-03-15 22-26-55](https://user-images.githubusercontent.com/489831/76723205-1e123680-670c-11ea-8adf-250d21830913.png)

**Comment by simonfossom** [comment]
Yeah, it's the same. It means the icon is missing 🤔 
It should be an dropdown arrow! 
This should be easy to change.
