### ISSUE TITLE
ValidationError when saving templates in migrated instance

### ISSUE THREAD

**Issue by xileflix** [huridocs/uwazi#2825]
Over the past few weeks, we migrated our Uwazi instance from HURIDOCS' servers to our own, on data.guardint.org, through a dumping and restoration of all data and files.

Now we're having a bug when trying to add new fields to templates, or even saving templates as they are without changing or adding anything. It seems to be an issue with multi-select fields...

![Screenshot from 2020-02-18 18-57-54](https://user-images.githubusercontent.com/18326691/77051865-4334cc80-69cc-11ea-80ee-20277c103d2c.png)

Could that bug result from the migration from HURIDOCS' servers to data.guardint.org? Any clue on how to solve this?

**Comment by txau** [comment]
@xileflix first of all I would suggest to make sure you have the latest version (Master) and that you follow the upgrade instructions.

**Comment by RafaPolit** [comment]
Please ensure that you have the right versions of all the dependecies needed:
- mongodb
- elasticsearch

We recently upped the required versions of both MongoDB and Elastic, so please ensure that they meet the requirements.

Could you report which versions you have of all the packages suggested in the README installation instructions?  Thanks.

**Comment by xileflix** [comment]
I'll try the upgrades and checks asap and report back, thanks!

**Comment by RafaPolit** [comment]
@xileflix was this resolved by updating the package versions?

**Comment by txau** [comment]
Closing (stale).
