### ISSUE TITLE
Placeholder text in select-fields

### ISSUE THREAD

**Issue by simonfossom** [huridocs/uwazi#2830]
Placeholder text must be human-readable. In this example it should say _Select a country_. Because it would be cumbersome to write it for each select-placeholder usually we use just "_Select_". (Like it was before - other screenshots)

![image](https://user-images.githubusercontent.com/8134850/77303957-0fbbb000-6cf4-11ea-910d-28f26ffb9b91.png)

---

![image](https://user-images.githubusercontent.com/8134850/77304868-5fe74200-6cf5-11ea-8055-32159e7aebe6.png)

![image](https://user-images.githubusercontent.com/8134850/77304997-8f964a00-6cf5-11ea-863b-c8b7b33134f4.png)

**Comment by txau** [comment]
@simonfossom this could be as easy as changing the default select placeholder. But his was introduced by @rustedgrail in this commit: https://github.com/huridocs/uwazi/commit/a9a3d8baaf20f7a5afb154c9bb28fc15f86db9d6#diff-d3f08e14e3cc6319da67b96e923f1f4c so I'd like to know first if this is impacting somewhere else in the UI.

**Comment by simonfossom** [comment]
Honesty I don't know. But as far I understand uwazi it shouldn't. We always have a titles explaining what you are selecting from. 🤷‍♂

**Comment by txau** [comment]
> Honesty I don't know. But as far I understand uwazi it shouldn't. We always have a titles explaining what you are selecting from. man_shrugging

This is being used in the Topic Classification UI, so maybe ther eis a reason why it says "Select other [name]". Idk if this is trivial and we can just modify it, or the side effects on the topic classification are going to be too bad.

I hope either @rustedgrail or @gabriel-piles can answer this question.

**Comment by simonfossom** [comment]
It's Alberto's design. I found it:

![image](https://user-images.githubusercontent.com/8134850/78157641-7e111880-7440-11ea-807b-49755a95801a.png)

![image](https://user-images.githubusercontent.com/8134850/78157721-9bde7d80-7440-11ea-8a7a-5d60e2be8ed9.png)

By what I can find we can safely reverse it. There's a title above each select.

**Comment by simonfossom** [comment]
@daneryl @txau @RafaPolit 
Can someone write closing notes on this issue pls?

What changed? What can we expect to see now in uwazi?

**Comment by txau** [comment]
This was a pretty quick fix. Now instead of "Select another X" it will display just "Select...".
