### ISSUE TITLE
default filters render result in app crash

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazi#2831]
when property as default filter renders label on library/uploads throws a translation error and app crashes. tagging this as critical as we can not merge/deploy to master until this is fixed.

@gabriel-piles @txau @RafaPolit apart from the translation solution, maybe we should "relax" a little bit this error and throw it as a warning to prevent crashes but having some info on things that are not properly translated.

**Comment by RafaPolit** [comment]
Yes, we want a more 'relaxed' version that does not crash the app.  A warning of a wrongly translated label would be useful to detect where this is happening.

**Comment by daneryl** [comment]
@RafaPolit @txau changed it so that it logs a warning.
now the warning itself is generated because a property is being used as a default filter, when filters try to render they are assuming the context for translation should be the first template selected,  in this case no templates are selected  that means undefined context, what should i do about all this ?

- leave it as is with the warning ?
- do not try to translate if there is no context ?

in the case of having templates selected as filters, it does not give a warning because there is a context, but it is also wrong because code is translating based on the first template, when this can be multiple templates with the "same" property (this means they have the same name) but because they belong to different templates they can have different translations, i do not think this needs/can be solved here but its important to point out.

**Comment by txau** [comment]
@daneryl I think is the same as this one: https://github.com/huridocs/uwazi/issues/2820 .IMO we can close this issue here and solve the bug in another PR.

**Comment by daneryl** [comment]
@txau @RafaPolit yes, same issue in a different place, so close this with the warning ? PR is ready, review required.
