### ISSUE TITLE
Ability to sort alphabetically in charts

### ISSUE THREAD

**Issue by simonfossom** [huridocs/uwazi#2839]
The most obvious example where this is needed is years in charts (example below). This just **has to** be sorted alphabetically.

Also it is expected soon for some partners.
 
![image](https://user-images.githubusercontent.com/8134850/77558859-bf8f4a00-6ebb-11ea-9656-96d68835b2fb.png)

**Comment by txau** [comment]
Related: https://github.com/huridocs/uwazi/issues/2435 https://github.com/huridocs/uwazi/issues/2434

**Comment by txau** [comment]
The proposed solution is to be able to pass an ordering criteria parameter to the chart upon instantiation. This param should support:
- Ordering numerically by value (ascending or descending)
- Ordering alphabetically by label (ascending or descending)

**Comment by txau** [comment]
This one is also related: https://github.com/huridocs/uwazi/issues/1891 but I think we shouldn't address it right now, since it involves time based indexing in ES.

**Comment by RafaPolit** [comment]
This functionality will use the `sort` attribute of the BarChart component.  It should be a valid JSON, and accepts to keys: `by` and `order`.

```
<BarChart sort='{ "by": "result", "order": "desc" }' />
```
Possible values:
by: `result` | `label`
order: `asc` | `desc`

Default ordering is by `result` `desc`, exactly as it has been working up till now.  If you select `label` as the sorting by attribute, ordering defaults to `asc`.  Any of the four combinations is valid and has been implemented.
