### ISSUE TITLE
Condition downloading mongo

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2845]
If already downloaded, do not download: /database/download_mongo_prebuilt.js

**Comment by daneryl** [comment]
@txau mongodb-memory-server already does the download, the auto download we implemented was before they added it, we should be able to remove our post install on the package json and everything should work. do not know if you will stop experiencing the issue though but at least it will be faster ...

**Comment by txau** [comment]
Since this issue is onyl affecting me I'm closing this for now.
