### ISSUE TITLE
Unclear random error "Properties can't swap names" when renaming template fields

### ISSUE THREAD

**Issue by n-mouse** [huridocs/uwazi#2853]
The error "Properties can't swap names: ___________" appears  when users try to rename template fields (old properties are English, new are Cyrillic). It seems to happen in a random way, some properties are renamed successfully and others fail, in any case there is no actual swapping involved.

**Comment by RafaPolit** [comment]
Please, do not use Cyrillic for naming template properties.  We 'normalize' names and non-latin characters are transformed to underscores.  That is why you are reading the ________ "property name".  The conflict arises if two words have the same length in characters, as the system detect both names as the same property.

This is a known bug, but there is a workaround:  name the properties in English, as it was, and then translate those properties into Cyrillic in the translations section of settings.

For admins and end users, everything will appear in Cyrillic.  Internally, they will be used in English.

This would pose a problem also for URLs of queries and other unforeseen issues.  Sorry for the inconvenience with this area of support for non-english languages.

**Comment by txau** [comment]
Closing. Duplicate: https://github.com/huridocs/uwazi/issues/2358
