### ISSUE TITLE
ToC not visible from public library landing page and 3rd level subheadings not locating accurately

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#2854]
Hey guys,
I just noticed this while  working on the CHR Philippines instance and thought to highlight. 
See link to video below
https://www.loom.com/share/d22638f375f74886ad0d0a9f866d4d93

**Comment by RafaPolit** [comment]
Thanks for the detailed report.

I can confirm the bug on the ToC not being visible in library view.  It's being tracked in #2855 

The second part of the report is not limited to 3rd level subheadings, the scroll feature just takes you to the actual page of where the contents are, but it does not check if the actual bookmarked text is within view.

We could improve on that, but it's complicated to know that an element in the PDF has come into view.  That is why the 'absolute position' in PDFs approach is much better.

**Comment by HSips** [comment]
Many thanks @RafaPolit I hear you on the absolute position approach.
