### ISSUE TITLE
Validation error when adding multiple values to a select field in the Quicklabel window

### ISSUE THREAD

**Issue by gabriel-piles** [huridocs/uwazi#2863]
Validation error when adding multiple values to a select field in the Quicklabel window.
This error appears because when a thesaurus is used as a select in one template, in this window multiple values can be added.

To reproduce this, the e2e fixtures can be used in Uwazi. 

Go to the URL:
http://localhost:3000/es/library/?quickLabelThesaurus=5e3d1853deeb2652690a0c10&q=(allAggregations:!t,includeUnpublished:!t)

Edit an entity and add more than one color for the Costume field.

**Comment by fnocetti** [comment]
@gabriel-piles is this still happening?

**Comment by txau** [comment]
quicklabel is deprecated. Closing.
