### ISSUE TITLE
Allow displaying the SharedID in the metadata and cards

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2871]
As a first approach to the unique ID field, we could implement a new metadata property field similar to the preview field, which would be for 'display' purposes only.  You add the Unique ID field, and it displays in metadata and / or cards the shared ID of the entity.

It's 12 characters, so it's small enough to be useful (in contrast with the mongo ID!).

The one aspect that probably requires some work is to make the documents searchable by that value, as currently searching by shared ID does not return any values.

What do you think?

related to: #2792, #1173

**Comment by daneryl** [comment]
@RafaPolit sharedId is going to probably disappear at some point, maybe not the best one to make public on the cards ?

**Comment by RafaPolit** [comment]
While the concept of not having one entity per language is a path we aim to follow, that does not necessarily mean we need to stop generating the "smaller" identifier along with the mongoID.  

But I can absolutely see your point.  Still, what would you propose to those that want 'unique' fields to follow up on cases, for example.  We have several requests to expose something like an auto-generated value, an auto-increment one, or any other form of quickly disambiguate between several possible matching records.

One real use case is: follow up of cases.  Instead of saying: "my name is X and my case discusses Z" for the Uwazi admin to filter, yo call and say: "I'm calling about case z982bdss".  If you need to recite the mongoID, it's a nightmare.

The admins can enter a 'manual' text field that they generate, but a lot of users want a faster way instead of having to know beforehand which was the last number they used, or similar things.  This was an intent to simplify that, give them a unique ID that is autogenerated, that is more or less small (ie: not the mongoID!) and is already available... instead of developing a fully configurable auto-generated field.

Do you have other ideas as to how to accomplish this?  Thanks.

**Comment by RafaPolit** [comment]
Also, if we remove the sharedID once the unified entities make their way to the production code, are all our previous URLs, Menus, and elements in custom pages using the sharedID broken and obsolete?  I would think keeping the sharedID (with a different concept, no longer an ID shared by multiple entities, but a smaller identifier) could be useful?

**Comment by daneryl** [comment]
@RafaPolit yes i understand the cases and it makes sense, i think we should keep sharedID even when we get rid of it for backward compatibility, you are right.
Do not have good arguments against that except that its not intended for that use, i will prefer to develop it as a feature instead of reuse something that by luck is there, it does not have to be fully configurable but something more friendly maybe than the sharedId.

**Comment by txau** [comment]
> @RafaPolit yes i understand the cases and it makes sense, i think we should keep sharedID even when we get rid of it for backward compatibility, you are right.
> Do not have good arguments against that except that its not intended for that use, i will prefer to develop it as a feature instead of reuse something that by luck is there, it does not have to be fully configurable but something more friendly maybe than the sharedId.

Agreed. I think creating a unique autogenerated code field is more convenient that reusing shared ids. We don't need to cover every possible "code convention". We can start with one proposal and eventually evolve it if we find the need.

**Comment by RafaPolit** [comment]
Ok.  So I'll close this issue. We will create a new one once the characteristics of this functionality are correctly defined then.
