### ISSUE TITLE
Flow breech? 

### ISSUE THREAD

**Issue by mylaa** [huridocs/uwazi#2874]
On public libraries, I'm **NOT** logged in and it allows me to _''Select All'_' entities, and shows the bulk publishing and editing option. 

It allows to go through all the steps and when you hit "save" you are asked to log-in. 
Nevertheless, this is a major flow issue. It should not be accessible for **non-logged** users.

**Comment by RafaPolit** [comment]
Yes, the 'select all' should only be available to logged user, just like selecting cards on the library is only activated to logged in users.
