### ISSUE TITLE
"Any" aggregation can render negative values

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2878]
The "any" aggregation is computed by adding all the 'option values' and subtracting the 'missing' or 'no value'.

When there are more options than the aggregations loaded, this yields negative values.

![Example](https://user-images.githubusercontent.com/4309019/79505190-a3358780-7ff9-11ea-8d9a-d23bc420c3a6.jpg)

**Comment by konzz** [comment]
Close in favour of #3243
