### ISSUE TITLE
Undefined defaultDoc on viewer -> routeActions

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2901]
We are receiving several error notifications on different instances with this message:
```
TypeError: Cannot read property '_id' of undefined
    at requestViewerState ([...]/app/react/Viewer/actions/routeActions.js:41:77)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

This means that the Viewer's `requestViewerState` procedure is returning `undefined` on the `defaultDoc` key for the `getDocument` process near line 30.

This could be the result of navigating to the URL of an Entity without document, but given the amount of errors we are getting, this does not seem to be the case.  We should look for what it triggering this, but we should also probably tackle the scenario of what to do if this happens.  Theoretically it shouldn't happen as that route should only be called for entities which already have a main document.

**Comment by daneryl** [comment]
The only way to reproduce this is to manually set on the url "file=non existent" that ive found.

anyway we need to handle this scenario and respond a 404. but as we are not sure this is the case i have made a small PR #2904 on the error report for SSR to see in more detail what is causing this exactly.

with this we will know which request is causing this and will be able to debug, if its a file manualy set case then its a matter of 404 respond.

**Comment by txau** [comment]
Related: https://github.com/huridocs/uwazi/issues/2888

**Comment by RafaPolit** [comment]
Given the amount of errors we have been having, I really doubt that someone is just manually tampering with the filename on different instances... but it could be the case.

**Comment by RafaPolit** [comment]
PR #2904 is meant to provide feedback to actually find the source of this.

Just to clarify, this is happening in a considerable amount of instances, this is not specific to any data source.

**Comment by RafaPolit** [comment]
We need to find a way to return a 404 when a non existing file is requested.
