### ISSUE TITLE
Fix intermitent tests for CSV Export

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2903]
- [x] Use supertest to test res.download and not route return
- [x] Check validation (specially `search` which is currently an array)
- [x] Test properly the file unlink, this probably means mocking the file generation naming.  Please ensure that the name can not be duplicated if tests are run in paralell
- [x] Test for correct passing of the user to the search function (perhaps @daneryl can help set this up quicker)
- [x] test that the exporter got called correctly with the desired params, even if its reply is mocked.  A good approach is to tailor the reply according to the arguments passed, in that way you are testing, with the response, the arguments passed.
- [x] Look if there is merit to create a separate file for the `api/export/` route?

**Comment by cdsetadmin** [comment]
Good job, just passing through!

**Comment by fnocetti** [comment]
Leaving a bit of advance report here:

- Checked with @daneryl and the solution seems to be ok.
- Moved the routes and tests to separate files, although we agreed that in the future we will need to find a better place to put both import and export functionalities.
- Migrated all the involved JS code to TS.

As for the still in progress work, I am:

- [ ] Completing the test cases
- [ ] Adding at least one simple integration test to the route
- [ ] Double checking the correctness of the search parameters and it's validation

**Comment by fnocetti** [comment]
I decided not to move forward with the integration test implementation at this time as it was taking me too much time to integrate with the search api (including ES) and this fix is needed on the code base.
I also double checked the search parameters (allowed by the export route) and removed some that wasn't useful for the export.

**Comment by RafaPolit** [comment]
I think this is OK.  We don't really need the full integration test at this point.  For such tests that require heavy fixtures, the better approach is to use E2E for that.
