### ISSUE TITLE
Puppeter e2e testing scaffold 

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2905]
Have a couple of basic tests based on puppeteer passing in CI as a base for e2e revamping.

**Comment by txau** [comment]
Need to upgrade to node 10.20.

**Comment by RafaPolit** [comment]
- [ ] Research and try to implement the e2e tests using a different database

**Comment by txau** [comment]
Related: https://github.com/huridocs/uwazi/issues/2894
