### ISSUE TITLE
Allow email "from" to be configured so that not every instance sends an "Uwazi" mail

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2912]
Currently, every mail sent from our platform comes from "Uwazi".  While we are the platform, each mail should come from either the Collection name or a custom configured 'from' email configured as part of the collection.

**Comment by vasyugan** [comment]
I'd like to second this! Today, after I fixed the mail settings of our instance, I was quite surprised that the from: address was no-reply@uwazi.io, also, this address seems to be hardcoded in ten different files.
