### ISSUE TITLE
CSV Export crashing instances on staging server

### ISSUE THREAD

**Issue by fnocetti** [huridocs/uwazi#2914]
Trying to do an export on the staging server will crash the app with the following error:
`[{instance-name}] uncaughtException: ENOENT: no such file or directory, open '{uwazi-installation-dir}/temporal_files/158919140076346qt7mwsjaj.csv'
Error: ENOENT: no such file or directory, open '{uwazi-installation-dir}/temporal_files/158919140076346qt7mwsjaj.csv'`

Note strings between braces ({ }) are place holders for this issue.

@daneryl suggests it looks like it's probably related to the writing permissions in the temporal_files folder on the server, which sounds fair since at the end, the service tries to download a file that might have not been created if the permissions are wrong.

**Comment by daneryl** [comment]
@fnocetti not permission but the actual folder does not exists, is this included on the uwazi code base ? maybe its just a matter of the deploy pipeline, 

if we just include the creation of this folder on the deploy process like the uploaded_documents and log folder and it should work.

**Comment by fnocetti** [comment]
@daneryl oh, it is included and has a placeholder file just like the uploaded_documents folder. Maybe there's something with our deploy process that I don't know and requires a special treatment?

**Comment by daneryl** [comment]
@fnocetti yes aparently the needed folders on the deploy pipeline are created by an ansible script for each instance.

**Comment by fnocetti** [comment]
OK, if that can be done I think it is the solution.

- Using a folder outside of the uwazi installation was already discussed and discarded because we prefer to have the data contained within the same directory (which seems to be the reason why we have the uploaded_files folder within the installation folder)
- Sharing the uploaded_files folder for both purposes might work but I really think we should use separate folders because the contents are really different. Also having a dedicated folder for temporal files will be helpful for diagnosis and clean up since it is supposed to be normally empty if the system is working correctly.

**Comment by RafaPolit** [comment]
This is a problem with our server infrastructure, not with the code itself.  Closing this for now.
