### ISSUE TITLE
Fix "duplicated name" feedback style

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#292]
![screen shot 2016-08-14 at 22 36 03](https://cloud.githubusercontent.com/assets/489831/17651877/95ea210e-626f-11e6-9b4f-90b3ff003243.png)

**Comment by danicatalan** [comment]
![screenshot 2016-11-02 16 46 00](https://cloud.githubusercontent.com/assets/6364153/19935858/d4e49160-a11b-11e6-84f5-d628d5269ccb.png)

**Comment by danicatalan** [comment]
Updated:

![screenshot 2016-11-03 13 42 45](https://cloud.githubusercontent.com/assets/6364153/19966317/8278dba6-a1cb-11e6-98fd-f79507f7b609.png)
![screenshot 2016-11-03 13 28 55](https://cloud.githubusercontent.com/assets/6364153/19966318/827a0d82-a1cb-11e6-819b-547119391799.png)
