### ISSUE TITLE
Error validating template if relationship property is assigned "any entity"

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2929]
If I try to save a template with a relationship field assigned to "any entity or document" as "Entites" select, it will fail validation.

**Comment by mfacar** [comment]
It should only be a validation at the backend or should it behave like the field Relationship Type?

**Comment by mfacar** [comment]
It is possible to save if the relationship has not had a previous entity value, the error only occurs if the relationship had another entity before. 
In the first case the content property doesn't exist, in the second this one is an empty string, this is triggering a validation error of minimum length.

**Comment by mfacar** [comment]
@RafaPolit, If we unify the behavior and let as default value an empty string at adding a property of type relationship, and remove the min length validation in the template schema, all test passed and it prevents the validation error.
Could there be an affected behavior that needs to be considered?
