### ISSUE TITLE
X button to reset search

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazi#293]
<img width="537" alt="screen shot 2016-08-14 at 10 48 43 pm" src="https://cloud.githubusercontent.com/assets/1386423/17651943/666d025a-6271-11e6-8359-e37a60683a66.png">

@danicatalan we lost the X button to reset search, is this intentional ?

**Comment by danicatalan** [comment]
Fixed.

![screenshot 2016-08-15 20 48 29](https://cloud.githubusercontent.com/assets/6364153/17675340/a65cf1d2-6329-11e6-83ce-47fe89d46429.png)

**Comment by txau** [comment]
@danicatalan What do you think of using the same "reset" icon and position we are using for the date field? For the sake of uniformity of the UI.

**Comment by danicatalan** [comment]
@txau I think it's a better approach to get the close icon, because it's a design pattern.

We can keep both on the UI.

**Comment by txau** [comment]
Closed in #304
