### ISSUE TITLE
Order selection and deselection of filers / relationship fields may deselect all values

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2942]
if you select check boxes on filters and / or multiselect fields on 'reverse' order, that is, if you have 4 items, first select item 4, then 3, then 2, and then 1, if you uncheck item 4, all other selections are removed.

## Steps to reproduce

- Create a relationship field in any template pointing to a template of which you have a couple of entities that belong to the second template
- Enter "new entity"mode and select that template to start working
- Select (check) the last entity from the list of values in the relationship field
- Check a previous value
- UnCheck the last entity

Notice how all the checkboxes are cleared.

@konzz Do you think this is an easy fix?  Thanks.

**Comment by txau** [comment]
Related/dupp: https://github.com/huridocs/uwazi/issues/3215

**Comment by txau** [comment]
@RafaPolit @nwyu this has been reported already 4 times in issues in GitHub, I think we should move it to sprint.
