### ISSUE TITLE
Develop "import from" on entity creation / edit

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2946]
Instead of the "duplicate entity" procedure requested on #2793 , we are moving on with "import from".

This will allow to, while creating or editing an entity, import matching template properties from a different entity.

**Comment by txau** [comment]
@RafaPolit maybe just a typo but I guess the feature is called "copy from"? "import from" sounds like CSV stuff.

**Comment by konzz** [comment]
Dessings
https://www.figma.com/file/Zw9JkOl11WCgdFfIKugCGy/Uwazi-connections?node-id=406%3A0
