### ISSUE TITLE
Have a slightly different design for entity cards

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#295]

**Comment by danicatalan** [comment]
![screenshot 2016-08-21 14 03 25](https://cloud.githubusercontent.com/assets/6364153/17837033/14fbf534-67a8-11e6-9ce0-2a590a20e3ed.png)

**Comment by txau** [comment]
1. @danicatalan if we are going to use the bended corner as a way for differentiating documents from entities and other stuff:
- Make the bended corner more evident, add color maybe?
- Create an equivalent insignia in the same area of the card for entities.

2. I like the new approach to the tags (3rd design), although that needs some thinking.

3. I wouldn't use the doc/entity icon because users may want to add their own icons (ie country flags) etc.

4. I wouldn't have the "stacked" leafs design. Is sort of misleading. What does it actually mean? Also is going to complicate the symmetry of the grid etc.

So I guess the solution should be along the line of 1. Design variations in the top right corner, evident to make them clearly visible.

**Comment by danicatalan** [comment]
![screenshot 2016-08-22 17 01 05](https://cloud.githubusercontent.com/assets/6364153/17859662/cfd46480-688a-11e6-8a97-a908165646f6.png)

**Comment by danicatalan** [comment]
@konzz Differentiate between Entities `fa-bank` and Documents `fa-file-text-o`.

![screenshot 2016-08-22 17 42 59](https://cloud.githubusercontent.com/assets/6364153/17861060/e4023f68-688f-11e6-8825-f675f1b662b3.png)

**Comment by txau** [comment]
Fixed in #326
