### ISSUE TITLE
Activity log sanitization

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2953]
At the moment our logs just grow with no clean up strategy whatsoever.

**Comment by txau** [comment]
Also we are logging plenty of unneeded information.

**Comment by RafaPolit** [comment]
@txau and @mfacar to discuss how to accomplish this

**Comment by txau** [comment]
Related: https://github.com/huridocs/uwazi/issues/2532

**Comment by txau** [comment]
- Check existing activity logs for raw data that we don't want to log
- Add decorators for the raw entries that we want to keep
- Prevent unwanted raw data from being logged
- Create a migration to get rid of the already logged raw data
- Develop retain policy just for entities and document CRUD operations. ie. keep up to 100k before start purging. Other logs such as settings, pages, etc should be kept forever

**Comment by mfacar** [comment]
@txau @RafaPolit, What do you think about using Mongo TTL Indexes to expire the activity logs based on a retaining policy by action?
It seems that the same functionality is being used to delete session data. I think it is could be better than purge the documents from a cronjob.

**Comment by RafaPolit** [comment]
Sounds like an interesting option.  Using capped collections seems like another route: https://docs.mongodb.com/manual/core/capped-collections/

The question is: do we want to just delete them without any additional process of storing what is going to be deleted?  If the answer is yes, then this could work.

Still, if you make only a few changes every week, perhaps the capped collection would allow users with low rotation of actions to not lose data if it is not filling up too much space?  Let's discuss this during the sprint once you have all the information?

Thanks for researching this.

**Comment by mfacar** [comment]
Thanks @RafaPolit for sharing the capped collections, I've seen it, I think that given we want to keep certain kind of actions forever, the idea is to have different policies of retention by method/url instead of relying on the insertion order.
For example:
```
never expire: /api/settings, /api/pages, /api/entities, ...
expire after X months: /api/semantic-search/notify-updates, /api/documents, ...
expire after X days: /api/translations, ...
```
In that case, TTL Indexes provide us the required behavior.
The matter with this is that the background thread that reads the data-type values in the index and removes expired documents from the collection runs every 60 seconds by default. However, this lapse could be changed by 
`db.adminCommand({getParameter:1, ttlMonitorSleepSecs: 120});`

**Comment by txau** [comment]
@mfacar with TTL the problem I see if that we will be purging useful data even for small collections with low rotation. At the same time big collections with a lot of rotation could still grow too huge logs. In that sense, we get the worse of both worlds.

I'd like to know how the logs actually look like after removing all the noisy entries that add no value, particularly that how much that 450k entries log is shrinking before making further decisions?

**Comment by txau** [comment]
related: https://github.com/huridocs/uwazi/issues/3094

**Comment by mfacar** [comment]
> @mfacar with TTL the problem I see if that we will be purging useful data even for small collections with low rotation. At the same time big collections with a lot of rotation could still grow too huge logs. In that sense, we get the worse of both worlds.

It has total sense, there are totally different conditions across instances, maybe we can use a setting to determine the frequency of deletion.

> I'd like to know how the logs actually look like after removing all the noisy entries that add no value, particularly that how much that 450k entries log is shrinking before making further decisions?

In the case of this sample log, after delete noise entries the storage is reduced by less than 1% (pdfinfo&raw entries). If we delete the oldest entries in order to keep them under 100k (there were 80k the last deleted day), the collection is shrunk by 70%.

@txau please can you elaborate on what should be the criteria for purging in case that the collection reaches 100k entries? 
I think we still have to define either a lifetime per resource or global age in order to delete entries.

**Comment by txau** [comment]
@mfacar @RafaPolit probably we should avoid loosing the whole history of an entity in order to keep the activity log small. I'm wondering if instead of deleting, the retention policy could condense the relevant past information in a single entry. This way we could keep track of the last 3 (arbitrary number, maybe a config option?) changes in a fully detailed record and create a special record that contains a list of all the previous actions without the details for historical purposes.

Certain record types could be kept forever such as changes to settings and other important entries.

With this kind of solution we know the size of the log is proportional to the size of the collection, so the amount of entries (not counting settings and such) is 4*amount of records, that is, a maximum of 3 full records + 1 historical record per each record that eve existed in the collection.

The historical record could still grow too much and maybe at some point we need to add an extra strategy for cleansing this up, but I guess is worth leaving this tech debt for now.

> In the case of this sample log, after delete noise entries the storage is reduced by less than 1% (pdfinfo&raw entries). If we delete the oldest entries in order to keep them under 100k (there were 80k the last deleted day), the collection is shrunk by 70%.

I'm curious about this. I guess there are more records that should not be recorded as ie, the `/api/semantic-search/notify-updates` you just mentioned, I don't see the value in keeping that kind of record? Also please keep an eye on https://github.com/huridocs/uwazi/issues/3094.

**Comment by mfacar** [comment]
@txau @RafaPolit I like the idea. I think that the content of the special registry could be the beautified log that we show on the screen, without the body. What do you think about not keep this data as a list inside the activity log but inside a new historical activity log collection? With this approach, we could be made direct finds and apply future purge strategies easier.

**Comment by txau** [comment]
@mfacar keeping the historical log apart makes total sense. We need to figure out how we want to display it in the activity log though.

**Comment by mfacar** [comment]
Perhaps we could keep the same option at Settings although, with two sources, the content should be the same only that the historical data wouldn't have the body as part of the registry.

**Comment by RafaPolit** [comment]
- [ ] Together with the DB update, the log should write a line to a file system
- [ ] Implement a 1 year expiry on the Database (research how to implement that on existing collections, and how this will look in the multi-tenant scenario

**Comment by txau** [comment]
Also related: https://github.com/huridocs/uwazi/issues/2879
