### ISSUE TITLE
Have global loader a la GitHub

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#296]

**Comment by danicatalan** [comment]
Flash without spinner: http://github.hubspot.com/pace/docs/welcome/

![screenshot 2016-08-15 16 19 16](https://cloud.githubusercontent.com/assets/6364153/17667168/05f1c58a-6304-11e6-8f88-9669f9516f50.png)

**Comment by RafaPolit** [comment]
We certainly want this!

**Comment by danicatalan** [comment]
Up this issue. We need this soon because users doesn't know if the app is working when loading times are too long, specially on filters and search.

**Comment by txau** [comment]
@konzz this was in sprint or your new hobbie is finishing old issues?

**Comment by txau** [comment]
@danicatalan @konzz You guys arbitrarily decided to add this task to the sprint. If t takes more than 2-3 to complete I totally disagree with that decision. Remember that we have POs for a reason.
