### ISSUE TITLE
Research Uwazi Versioning

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2966]
We need:
- [ ] Automatic increase of minor version? upon: master merge? with each migration?
- [ ] Manual upgrade of major versions
- [ ] Keep better release notes so users know breaking changes, bug fixes, etc.
- [ ] Client version-checking of match between client and server to prevent corruption of data
- [ ] Create template for documenting in PR: breaking changes, bug fixes, new functionality, documentation?
- [ ] Explore option to have two dev branches? One with patches, the other with features so we can split them? Research this.
- [ ] Research existing templates for Git Workflow

Some related issues:
#2101 
#2041

**Comment by txau** [comment]
This has been addressed and we are using semver now.
