### ISSUE TITLE
You can assign the same property name pointing to different thesauri in different templates

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2968]
## To reproduce

- Have template A with property "country" pointing to thesauri "countries"
- Have template B with property "country" pointing to thesauri "cases"

This is a weird scenario: the property has a consistent type, but by pointing to different thesauri, the condition opens a whole can of worms.  Specially if the thesauri are nested and one of the properties is selected as "default filter".

This should not be allowed.  If the same name is used with different targets, this should prevent saving.

**Comment by txau** [comment]
@RafaPolit what is causing the buggy behavior? is it because of elastic mappings or something else?

**Comment by RafaPolit** [comment]
In this case, it is the fact that you could populate values from thesaurus A on one template and with values from thesaurus B on another one.

This poses and issue if they are marked as default filters or if you select both templates, as to where to get the namings from. 

Even more complicated, there is a special condition where, when faced with nested thesaurus values, our client "knows" how to render those values and their parents.   In this case, it is "trying" to render flat values but finding nested values assigned to the entities, so it is failing.

In this case, it is not a matter of elastic mapping, as the mapping actually matches.  It is more a problem of populating the labels of the values (now that they are not kept in memory).

Still, as already talked about, this produces a ambiguous term and it would be good for the admins to define and disambiguate those terms so that users are not presented with a same-name property that means (and points to) two different things.

**Comment by txau** [comment]
@RafaPolit but from the default/common filter perspective, we could disambiguate by using also the target thesaurus as criteria, isn't it? it doesn't really matter if there are two filters with the same name as long as it doesn't explode. It is up to admins to disambiguate these namings.

**Comment by fnocetti** [comment]
@simonfossom what do you think it would be a good validation failing message for this?

**Comment by simonfossom** [comment]
For validating if the same title is on two different select/multiselect I would go with:
> _**Please choose a different title.**
Entered title is already in use on another select or multiselect with a different thesaurus._

if we want to be more descriptive we might want to add:
> _Having the same title on different thesauri causes usability problems while filtering._

**Comment by RafaPolit** [comment]
- [ ] Thesauri properties with same name, same type but pointing to different thesauris
- [ ] Relationship properties with same name, same type but pointing to different relationship
