### ISSUE TITLE
Field name sanitization

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2972]
At the moment we are sanitizing in a very strict manner field names for mongodb storage and elastic mappings. We are replacing potential illegal characters by "_" chars, in some cases leading to names composed just by underscores which in turn generates naming conflicts.

Part of the solution is having a less strict sanitation, since actually both mongo, elastic and JS itself support a wider ranger of characters.

> If you try to create an index with a name whose length exceeds 255 characters (or ~100 UTF-8 encoded bytes) you'll get an error like this one

> InvalidIndexNameException[Invalid index name [...], index name is too long, (266 > 255)]

> As for the valid characters to use in an index, the best place to look for is in their test suite, but basically an index name

    must not contain the characters #, \, /, *, ?, ", <, >, |, ,
        Since ES 7.0 onwards, : is not allowed as well
    must not start with _, - or +
    must not be . or ..
    must be lowercase

From https://stackoverflow.com/questions/41585392/what-are-the-rules-for-index-names-in-elastic-search

**Comment by txau** [comment]
From Mongo documentation:
> according to the source below, you can use any UTF8 character in the field name -- the only exception is the '.' character which is not allowed in field names (because it's used to query sub-documents), and field names can't start with a '$' character..

**Comment by RafaPolit** [comment]
Approach to develop this:
- Develop a new sanitizer that only takes into account the fewer characters
- Develop a flag "Use legacy property name sanitizer" (find the correct wording!) that would be selected by default on old instances (migration?).  Newer instances should have this disabled by default.
- If users decide to 'uncheck' the legacy support, we run a script to replace names with label, warning that common filters, urls, pages, etc. can get broken

**Comment by RafaPolit** [comment]
After some conversation, clicking on the new option WILL migrate the templates to the new sanitizing scheme.
- [ ] Implement on save migration.

Messsage for UI:
- [ ] Support non-latin characters in property names
Checking this box enhances support for non-latin languages as default languages.  This will update all template properties automatically.  This process could take several minutes.  This process will likely change URLs to specific filters.   If you have menus or links using such URLs, they will probably stop working after the update.  Please ensure you correct them manually.  After selecting this option, you will not be able to revert back.  If you are not facing issues with your template property names, we recommend leaving this unchecked.
