### ISSUE TITLE
Numeric range filters fail when only 'from' digit is input

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2978]
If I create a numeric field and then add it as filter, apparently the ES search fails upon searching only the 'from' (while I am still writing, before entering the "to").  This only happens after the first time.  That is, you enter a From, it filters, you enter a To, it filters.  You then DELETE the To, and it fails... and then if fails whatever you do.

**Comment by txau** [comment]
@RafaPolit I think this is actually the same bug as #3004
