### ISSUE TITLE
Inputing a number in the search box yields a validation error

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2979]
If you just input a number in the search box, you get a validation error.  Entering "quotes" fixes the problem.  We need to ensure the search is a string or change a bit the validation.

**Comment by mfacar** [comment]
The change at the validation level is very straightforward if we added support for number type at the validation schema. 
Since there are other issues related to errors with searchterm like in #2665, do you think this issue could be closed with the simplest solution?
