### ISSUE TITLE
Error thrown in browser, instead of access to library

### ISSUE THREAD

**Issue by whyfrycek** [huridocs/uwazi#2986]
When opening the direct URL to an instance (library), an error thrown in the browser is:
`url: /api/search?order=desc&sort=creationDate
query: {
 "order": "desc",
 "sort": "creationDate"
}
Cannot read property 'toString' of undefined`

It is possible to log in by going straight to the login screen.

User checked in activity log and there were no template or thesaurus changes that could have caused this, since last entities were successfully added (ca. one week ago).

User also tried to access data through the API and only had access to one record (which is less than expected, given data entered).

**Comment by RafaPolit** [comment]
We have found the problem, still working on the solution.

Regarding the returned documents via API, all documents are unpulished and returning them via API would require logging in and sending the correct authorization token.

We can confirm there are 1610 documents in the database.

**Comment by RafaPolit** [comment]
This is a known problem when using non-latin characters, most of the discussion happened on #2358 .

This particular collection has used Russian template property names, and some of the names have the exact same character length, which is internally confusing the aggregations system.

We are working on a long-term solution in #2988, #2971, #2968.

The immediate solution (that will fix the problem for the time being) is follow this suggestion: https://github.com/huridocs/uwazi/issues/2358#issuecomment-501341313

To repeat what was written:
> We encourage users to set the property names in latin characters and then use translations to define the non-latin labels.

To fix:
- go to https://xxxx.uwazi.io/login (replace xxxx with instance name)
- after login, you will be presented with an error and an empty library, this is, for the moment, expected
- manually replace the browser URL to https://xxx.uwazi.io/settings
- go into templates > and then `edit` on the only template name
- replace all the non-latin character named properties with latin character names.  we suggest English as that makes easier to debug if we need to find a particular property later on
- once finished, save the template
- go into the library and check that the error has been fixed
- then go to settings > translations > (template name) > translate
- provide the Russian translations for the english-named labels

Now, if you go back into the library, you will correctly see the values but also see the correct Russian labels.

**Comment by txau** [comment]
sigh

**Comment by whyfrycek** [comment]
Solved the issue. Thanks for the detailed explanation @RafaPolit !
