### ISSUE TITLE
Set default starting geolocation coordinates

### ISSUE THREAD

**Issue by MatelSow** [huridocs/uwazi#2998]
**Use case**: I would like to be able to choose a default starting place on the map in entities with geolocation coordinates. Current default is Switzerland.
![1](https://user-images.githubusercontent.com/56391759/85297333-e7824f80-b4a2-11ea-9e81-a86eaee8059d.png)

**Comment by natasha-todi** [comment]
MFA for its Justice for Wage Theft instance has requested to be able to choose their default starting place as well. The geolocation field ( PFA screenshot below) is on their submission form for someone to report wage theft. At the moment the default starting place is Switzerland as well and MFA want Saudi Arabia, Qatar, Kuwait, Oman, Bahrain, and UAE to be the default starting place. 

![Screenshot 2020-07-02 15 30 27](https://user-images.githubusercontent.com/60774708/86345992-e9ee6180-bc79-11ea-9a6f-ca0e5f37d10e.png)
