### ISSUE TITLE
Ensure full backend entity metadata validation

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#3003]
Backend needs to ensure metadata consistency:

- [x] - should not allow incorrect foreign keys (either because they are deleted entries or because they belong to different templates or thesauris)

- [x] -  should not allow incorrect types
- [x] -  should not allow 'rogue' property names not found on the template
- [ ] -  check if ti merits to do this for batch processes as well.
   - [x] - saveMultiple on our entitiesModel (this calls directly model.save, not executing validation) i think we need to add validation but this will result in slower saves, and we do not really know how many entitites are we saving at a time using this function.
   - [ ] - updateMany using mongo query like { $set/$rename/$unset : {} }, i do not know how we can validate this properly as you can send things like {'metadata.name': 'name'}, maybe check how on how many cases we using this and change it so that it is always (if possible) an entity structure that we can validate using the current validator.

**Comment by daneryl** [comment]
here is a summary from the current tests of the current validations on entities

    validateEntity
      ✓ should allow ObjectId for _id fields (149ms)
      ✓ should allow removing the icon (9ms)
      ✓ should allow template to be missing (3ms)
      ✓ should fail if template does not exist (5ms)
      ✓ should fail if title is not a string (6ms)
      ✓ should fail if title exceeds the lucene term byte-length limit (8ms)
      ✓ should allow title to be missing (6ms)
      metadata
        ✓ should allow non-required properties to be missing (4ms)
        if no property is required
          ✓ should allow metadata object to be missing if there are not required properties (4ms)
          ✓ should allow metadata object to be empty (4ms)
        if property is required
          ✓ should fail if field does not exist (26ms)
        any property
          ✓ should fail if value is not an array (22ms)
        text property
          ✓ should fail if value is not a single string (7ms)
          ✓ should fail if value is a string that exceeds the lucene term byte-length limit (6ms)
        markdown property
          ✓ should fail if value is not a string (4ms)
          ✓ should fail if value is a string that exceeds the lucene term byte-length limit (8ms)
        media property
          ✓ should fail if value is not a string (5ms)
        image property
          ✓ should fail if value is not a string (4ms)
        numeric property
          ✓ should fail if value is not a number (4ms)
          ✓ should allow value to be empty string (5ms)
          ✓ should allow numbers passed as strings (3ms)
        date property
          ✓ should fail if value is not a number (7ms)
          ✓ should allow value to be null if property is not required (4ms)
        multidate property
          ✓ should fail if value is not an array of numbers (6ms)
          ✓ should allow null items (7ms)
        daterange property
          ✓ should fail if value is not an object (6ms)
          ✓ should allow either from or to to be null (8ms)
          ✓ should fail if from and to are not numbers (4ms)
          ✓ should fail if from is greater than to (4ms)
        multidaterange property
          ✓ should fail if value is not array of date ranges (15ms)
        select property
          ✓ should fail if value is not a non-empty string (5ms)
          ✓ should allow empty string if property is not required (6ms)
        multiselect property
          ✓ should fail if value is not an array of non-empty strings (6ms)
          ✓ should allow value to be an empty array (3ms)
        relationship property
          ✓ should fail if value is not an array of non-empty strings (5ms)
        link property
          ✓ should fail if value is not an object (9ms)
          ✓ should fail if label or url are not provided (7ms)
          ✓ should fail if label or url is not a string (5ms)
          ✓ should be ok if both are empty (4ms)
        geolocation property
          ✓ should fail if value is not an array of lat/lon object (3ms)
          ✓ should fail if lat or lon are not numbers (5ms)
          ✓ should fail if label is not a string (4ms)
          ✓ should not fail if label is not present (3ms)
          ✓ should fail if lat or lon is missing (7ms)
          ✓ should fail if lat is not within range -90 - 90 (6ms)
          ✓ should fail if lon is not within range -180 - 180 (5ms)

**Comment by txau** [comment]
@daneryl may be related to this topic. When an instance is in blank state and no thesauri exists, you can add a select property to a template with empty thesauri and it will let you save.

**Comment by daneryl** [comment]
- [ ] should not allow incorrect foreign keys (either because they are deleted entries or because they belong to different templates or thesauris)
- [ ] should not allow incorrect types
- [ ] should not allow 'rogue' property names not found on the template
- [ ] check if ti merits to do this for batch processes as well

**Comment by daneryl** [comment]
> @daneryl may be related to this topic. When an instance is in blank state and no thesauri exists, you can add a select property to a template with empty thesauri and it will let you save.

this is actually about template validation, should i include this on the PR, i have another PR https://github.com/huridocs/uwazi/pull/2989 where i have been doing some work on that, needs QA actually but that is not included, is just that i want to avoid conflicts.

**Comment by txau** [comment]
> > @daneryl may be related to this topic. When an instance is in blank state and no thesauri exists, you can add a select property to a template with empty thesauri and it will let you save.
> 
> this is actually about template validation, should i include this on the PR, i have another PR #2989 where i have been doing some work on that, needs QA actually but that is not included, is just that i want to avoid conflicts.

You are right, let's do it in another PR.

**Comment by daneryl** [comment]
im leaving updateMany queries out of this for now as there is not too many and they are a more controlled environment and only triggered on template changes, the update should be correct.
