### ISSUE TITLE
Numeric filter sends an empty value when cleared causing a query shard exception

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#3004]
1. Input a value in the field "From" and wait for automatic submission.
2. Input a value in the field "To" and wait.
3. Delete the value from the field "From".

![image](https://user-images.githubusercontent.com/489831/85423472-f8c76c80-b533-11ea-8f3f-a94ab568e090.png)

**Comment by RafaPolit** [comment]
This may be the cause of this other bug: #2978
