### ISSUE TITLE
Select multiple entities without being logged in

### ISSUE THREAD

**Issue by simonfossom** [huridocs/uwazi#3006]
We have "export CSV" and bookmarks are coming. It makes sense that not-logged-in user should be able to select multiple entities so he can use bulk actions, no?

**Comment by txau** [comment]
I think the "export CSV" works based on the filters/search, not in bulk selection? Can you confirm @fnocetti ?

**Comment by simonfossom** [comment]
Yes, it works well with filters/search, but admin can also select multiple entities and export them. 
Why the viewer shouldn't be able to do that?

**Comment by txau** [comment]
@simonfossom got it. I does make sense.

**Comment by txau** [comment]
> I think the "export CSV" works based on the filters/search, not in bulk selection? Can you confirm @fnocetti ?

I just double checked and actually this functionality is working. Users can bulk select a subset and only these records will be exported.

**Comment by nwyu** [comment]
This works, however it would be good to make the ability to select multiple entities more apparent to end users. This is achieved right now by holding the `cmd`  or `shift` button and clicking on multiple cards (in Library) or checkboxes (in Table View). There is a pro tip that is shown to logged in users, but this is not shown to the public. Closing this in favor of #5045.
