### ISSUE TITLE
Data lost - 0 records on 2 Databases

### ISSUE THREAD

**Issue by Ilyes-Chiha** [huridocs/uwazi#3035]
- Today we logged into 2 of our Uwazi databases
- We did not found any records on these two instances
- The templates still exist
- The data is critical and we are in urgent need of recovering it
- There is no deletion of data in the activity log
- I am at your disposal to help and communicate to you any useful information

**Comment by RafaPolit** [comment]
All the data was still present in the database, it was just not showing on the library.

A more technical explanation: we use MongoDB as our database for storing entities, we use ElasticSearch to query those entities.  The ElasticSearch index was not refreshed after a clean reindex we did yesterday and this showed up as if no data existed.  This was not the case.  The elastic index has been refreshed and now you can see all your files.

Hope this solves the issue.

**Comment by Ilyes-Chiha** [comment]
thank you Mr RafaPolit for your work .

**Comment by txau** [comment]
@Ilyes-Chiha since your data is back I'm closing the issue.
