### ISSUE TITLE
Data not found 

### ISSUE THREAD

**Issue by Ayesha707** [huridocs/uwazi#3036]
i have logged into our uwazi database but no data is been found. Over 500 plus records

**Comment by RafaPolit** [comment]
All the data was still present in the database, it was just not showing on the library.

A more technical explanation: we use MongoDB as our database for storing entities, we use ElasticSearch to query those entities.  The ElasticSearch index was not refreshed after a clean reindex we did yesterday and this showed up as if no data existed.  This was not the case.  The elastic index has been refreshed and now you can see all your files.

Hope this solves the issue.

**Comment by txau** [comment]
@Ayesha707 this is fixed now. Sorry for the inconvenience!

**Comment by Ayesha707** [comment]
Thank you all so much .
