### ISSUE TITLE
404 when documents in different languages have a different amount of pages (3 pts)

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#3039]
Documents vary in the amount of pages they have across translations. In Uwazi, you can switch from one language to another while being in the URL for a particular page, ie:
- en/entity/hcvrcury1oj?page=9

When switching to another language while in that URL, if the target document has less pages Uwazi will toss a 404.

I guess this can easily be detected and fixed.

**Comment by konzz** [comment]
Remove the page url parameter when changing languages.
