### ISSUE TITLE
And/Or toggle in filters appears to distort statistics displayed in library side panel

### ISSUE THREAD

**Issue by MatelSow** [huridocs/uwazi#3049]
Instance is multilingual - English/French

When filtering by properties with multi select fields, the and/or toggle appears to distort the statistics displayed in the side panel. Any ideas what could have caused this or how to resolve?

![1](https://user-images.githubusercontent.com/56391759/87314235-39a71580-c523-11ea-9c8c-cdbe81206127.png)

**Comment by txau** [comment]
@MatelSow what is the distortion? Do you mean those numbers are changing or that the UI is distorted?

**Comment by MatelSow** [comment]
@txau i am referring to the UI. The numbers are working correctly. Thanks

**Comment by txau** [comment]
@MatelSow there is clearly a problem with the CSS, that said, they've put a really long label "Filtres ET operateur" instead of just "and". I understand they want to clarify that functionality for the end users but I strongly suggest that they use a shorter label.
