### ISSUE TITLE
tableview

### ISSUE THREAD

**Issue by simonfossom** [huridocs/uwazi#3050]
[PRD link](https://docs.google.com/document/d/11FQk2z9ypfavW4Pk-ASxcCSMMPH0P5Cd4LDWDc9fbRc/)

[Design link](https://www.figma.com/file/xjsz7r65epN4B0b96zilac/UWAZI-redesigns?node-id=346%3A3734)

Let me know if something isn't clear in the doc comments

**Comment by simonfossom** [comment]
## User Stories
As an admin, I need to quickly sort and filter and skim through my collection to find relevant entities.
As a viewer, I want to quickly and easily find information in the collection.

## Behavior 
**Desktop**
Column width is determined by the longest title.
Default widest column is 332px (widest content 300px + 16px left and right margin) - if title is longer it is truncated. A column cannot be smaller than 50px in width.
The gap between columns 1px, gap between rows 2px.
The header row is always visible on vertical scrolling, a title column is always visible on horizontal scrolling.
Scrolling to the end of the table loads more or shows [load more] button.
Columns are resizable.

Actions
- Search	
- change view - cards, table, map
- column selector - add & remove columns in the table (default are metadata visible in card view)
row width selector (if text is longer it is truncated)
  - 1 line row: 30px
  - 2 line row: 44px (default)
  - 3 line row: 56px
- filters button opens side-pannel

Open an entity and select
- Click on a row opens entity in sidepanel
- Click on a checkbox selects the row (clicking a row to open it doesn't change selection)

**Mobile** shows only title column by default, but users can add any number of other columns (title column is horizontally scrollable on mobile)

**Comment by simonfossom** [comment]
Suggested component to explore: https://www.npmjs.com/package/react-table

**Comment by simonfossom** [comment]
@mfacar @fnocetti 

Update:
**Tableview displays columns of metadata:** text, numeric, select, multi-select, relationships (as link), Date, Date Range, Multi-date, Multi-date Range, Link, Geolocation (as coordinates; in future to display name of location)

**Tableview cannot display columns of metadata:** image, preview, media
These metadata cannot be selected from the column-selection button nor are they displayed by default.

- added **_Hide unselected_** checkbox under the search (see design)
- 'selected' sidepanel is removed (see design)

**Comment by fnocetti** [comment]
> * 'selected' sidepanel is removed (see design)

@simonfossom does this apply to the cards view too?

**Comment by simonfossom** [comment]
> Hide unselected checkbox

It is disabled if no rows are selected. When any number of rows are selected, checking 'hide unselected' hides rows that are not selected. 

> 'selected' sidepanel

No, just in tableview.
