### ISSUE TITLE
Support ICU analyzer

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#3059]
Elastic's ICU Analysis plugin (https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-icu.html) can fix a couple of pending issues: 
 - #1622 number sorting in strings
 - #2050 Turkish chars

>  including better analysis of Asian languages, Unicode normalization, Unicode-aware case folding, collation support, and transliteration

I added this as an optional param, so it is not mandatory to install and use the plugin, although I'd say is advisable. This should be reflected in our documentation (@nwyu ). In order to activate this option you need to:

1. Install the plugin:
```
sudo bin/elasticsearch-plugin install analysis-icu
```
2. Set an env var for Uwazi to know you want to use these functions:
```
export USE_ELASTIC_ICU=true
```

At the moment this is only being used for fixing title sorting issues but I suspect we could extend this to other properties used for sorting as well as multi-select filters.

**Comment by mfacar** [comment]
It's resolved with https://github.com/huridocs/uwazi/pull/3058
