### ISSUE TITLE
Date field value display format

### ISSUE THREAD

**Issue by elric-wamugu** [huridocs/uwazi#3060]
The date format in the collection's settings 
![Screenshot_2020-07-20 Settings • Human Rights Research](https://user-images.githubusercontent.com/2143671/87932719-4334fe00-ca8c-11ea-849b-a55c22a3831a.png)

controls the date format in edit view/mode only

![Screenshot_2020-07-20 A HRC RES 33 24 - resolution adopted by the Human Rights Council o](https://user-images.githubusercontent.com/2143671/87932844-7aa3aa80-ca8c-11ea-962b-a185b21ff5c9.png)

and never when viewing an entity normally
![Screenshot_2020-07-20 A HRC RES 33 24 - resolution adopted by the Human Rights Council o (1)](https://user-images.githubusercontent.com/2143671/87933043-d2daac80-ca8c-11ea-865e-bce1ec354eee.png)

How to replicate:
- Edit and save the date display format in the admin settings under collection
- Toggle between the view and edit of an entity with a date field. The settings applied above affects the date display format while in edit mode only.

**Comment by txau** [comment]
The date format is controlled by the locale, that configuration is only for inputs, so this is working as intended. We could improve the UX by specifying that this is not "DATE FORMAT" but "INPUT DATE FORMAT".
