### ISSUE TITLE
Add link to DOCUMENTATION on the Settings -> Collection page

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#3066]

**Comment by simonfossom** [comment]
This is the link that needs to be added: https://uwazi.readthedocs.io/en/initial-setup/admin-docs/managing-settings.html?highlight=PRIVATE%20INSTANCE#how-to-edit-your-site-settings

User can click on the link in the notice.

![collection](https://user-images.githubusercontent.com/8134850/88069915-5de1a280-cb72-11ea-8dca-feacce2e0137.png)

([Design link](https://www.figma.com/file/xjsz7r65epN4B0b96zilac/UWAZI-redesigns?node-id=466%3A22572))

**Comment by simonfossom** [comment]
A better way might be to put the documentation link into settings navigation instead of on one subpage
https://github.com/huridocs/uwazi/issues/3370

**Comment by nwyu** [comment]
The link to Uwazi documentation will reside on the Settings sidebar, as suggested in #3077. Closing this issue.
