### ISSUE TITLE
Add "remember me" for longer Uwazi sessions

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#3067]
While having sessions that expire sooner is a good security measure, in many cases users could benefit from a somewhat longer sessions. This could be achieved by a "Remember me" checkbox at the log-in moment that will set a longer expire time for that particular session, leaving at the discretion of the user if the session should be long or short.

What do you think @simonfossom ?

**Comment by simonfossom** [comment]
Yes! I agree completely. Without it session should end when user closes all tabs of an instance.
_Remember me_ session would be maybe for home computer - I don't know what would be good length. Two weeks? Month?

**Comment by txau** [comment]
Sessions already last 15 days. Closing for now.
