### ISSUE TITLE
Automatically focus on input on new item in thesauris

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#307]
It would greatly improve UX to have the focus set automatically on the input box when creating a dictionary.

![screen shot 2016-08-18 at 13 55 03](https://cloud.githubusercontent.com/assets/489831/17772886/9f2c867e-654b-11e6-9c43-6881d0ecae18.png)

**Comment by kjantin** [comment]
Currently, when I click on "add item" I see the "Item name" field:
![image](https://user-images.githubusercontent.com/354426/28718320-5db38fc6-7373-11e7-965c-51bf2a6a2fd3.png)

@txau are you suggesting that the cursor be placed in that new/empty "Item name" field?

**Comment by txau** [comment]
Yes.

**Comment by txau** [comment]
Related: https://github.com/huridocs/uwazi/issues/1442
