### ISSUE TITLE
Can not upload Pdf above 1 MB

### ISSUE THREAD

**Issue by chris260671** [huridocs/uwazi#3081]
Is there a limit with the upload size as I read in another closed issue there is not supposed to be one . Any Pdf above 1 MB does not upload and leaves me with the attached white page .  will paste the error code i see in the terminal window ... as well 
yarn run v1.22.4
$ export NODE_ENV=production; node server.js
==> Connecting to mongodb://localhost/uwazi_development
==> Processing system keys...
(node:28570) DeprecationWarning: Mongoose: `findOneAndUpdate()` and `findOneAndD                                                                                                 elete()` without the `useFindAndModify` option set to false are deprecated. See:                                                                                                  https://mongoosejs.com/docs/deprecations.html#-findandmodify-
==> 🌎 Listening on port 3000. Open up http://localhost:3000/ in your browser.
2020-07-26T15:19:13.610Z [localhost]
url: /api/entities
body: {
 "_id": "5f1d9d925e3c216f9adbde54",
 "language": "en",
 "metadata": {
  "comments": [
   {
    "value": ""
   }
  ],
  "multi_select": [],
  "date_range": [
   {
    "value": {
     "from": null,
     "to": null
    }
   }
  ],
  "rich_text": [
   {
    "value": ""
   }
  ],
  "multi_date_range": []
 },
 "sharedId": "kltpuu9bo8m",
 "template": "5f1d9bdd5e3c216f9adbdcb2",
 "title": "Oct 23 2017 Motion for Reconsideration Exhibits compressed"
}
TypeError: Promised type was not provided!
    at ensure (/root/uwazi/prod/app/shared/tsUtils.js:7:11)
    at validateDictionariesForeignIds (/root/uwazi/prod/app/shared/types/validat                                                                                                 eMetadataField.js:73:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-07-26T15:19:22.515Z [localhost]
url: /api/entities
body: {
 "_id": "5f1d9d925e3c216f9adbde54",
 "language": "en",
 "metadata": {
  "comments": [
   {
    "value": ""
   }
  ],
  "multi_select": [
   {
    "value": "kltpuu9bo8m"
   }
  ],
  "date_range": [
   {
    "value": {
     "from": null,
     "to": null
    }
   }
  ],
  "rich_text": [
   {
    "value": ""
   }
  ],
  "multi_date_range": []
 },
 "sharedId": "kltpuu9bo8m",
 "template": "5f1d9bdd5e3c216f9adbdcb2",
 "title": "Oct 23 2017 Motion for Reconsideration Exhibits compressed"
}
TypeError: Promised type was not provided!
    at ensure (/root/uwazi/prod/app/shared/tsUtils.js:7:11)
    at validateDictionariesForeignIds (/root/uwazi/prod/app/shared/types/validat                                                                                                 eMetadataField.js:73:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)

![Annotation 2020-07-26 163942](https://user-images.githubusercontent.com/68544954/88483289-be038a80-cf5e-11ea-9835-1e5558bfc403.png)

**Comment by konzz** [comment]
@chris260671 Hi! Uwazi itself does not have a restriction (just tested to upload a 3mb pdf), I assume you are self hosting, so maybe your server does have a limit and those errors are because Uwazi is not handling the error from the server properly.

Can you check if you have a limit in the server configuration?

**Comment by txau** [comment]
@chris260671 the error seems to be unrelated to the file size, but I suppose that if you are reporting it as something being triggered when you try to upload files bigger than 1MB its because that is the pattern you detected. 

Did you try with different files?

From the error, it seems to me that is rather related to a problem with the multi-selects.
```
TypeError: Promised type was not provided!
at ensure (/root/uwazi/prod/app/shared/tsUtils.js:7:11)
at validateDictionariesForeignIds (/root/uwazi/prod/app/shared/types/validat eMetadataField.js:73:25)
at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by chris260671** [comment]
@konzz I verified with the VPS server provider there is no limit on it .....  I have one idea and i will know in the next hour , because this one doc uploaded the other day fine and now suddenly it acts up at every doc that it is above 1 MB ... might be completled unrelated but the docs are at OneDrive , and Microsoft recently updated my surface x to Windows insider Build ... i just rolled back ... lets see ... I am doing as well a complete bare clean install on Ubuntu 16 on the server ....as I was out of luck to get Uwazi to run on Centos 7 or 8 ...   

@txau ... yes everything below 1 MB uploads fine ... what i have noticed happend with some documents it took the title and it looked like it uploaded but when you click on view and try to populate the doc ... its not there and you get the green upload file button . when i looked into uploded docs pdf folder it had however assigned a pdf number ... really bizzare ... will know more in an hour so ...  I am getting good in installing Uwazi ...LOL

**Comment by txau** [comment]
@chris260671 can you maybe share one of the documents that are failing if they are not private information? I'd lie to run my own tests locally.

**Comment by chris260671** [comment]
@txau if you can give me your email address ... I will sent it to you .... just got an error during stable version install at yarn install ... complaining about missing node-sass ...  ran yarn add node-sass and it created lock file and went on ... 

here from the error throw ... if you need the full code that ran let me know i keep the terminal window ..... 

   ^
../../nan/nan.h: In instantiation of ‘void Nan::imp::SetMethodAux(T, v8::Local<v8::String>, v8::Local<v8::FunctionTemplate>, ...) [with T = v8::Local<v8::Object>]’:
../../nan/nan.h:2353:20:   required from ‘void Nan::SetMethod(HandleType<T>, const char*, Nan::FunctionCallback) [with T = v8::Object; HandleType = v8::Local; Nan::FunctionCallback = void (*)(const Nan::FunctionCallbackInfo<v8::Value>&)]’
../src/binding.cpp:338:42:   required from here
../../nan/nan.h:2337:3: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>&, v8::Local<v8::Function>)’
   recv->Set(name, GetFunction(tpl).ToLocalChecked());
   ^
In file included from /root/.node-gyp/14.6.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:51,
                 from ../src/binding.cpp:1:
/root/.node-gyp/14.6.0/include/node/v8.h:3670:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^
/root/.node-gyp/14.6.0/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
/root/.node-gyp/14.6.0/include/node/v8.h:3673:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^
/root/.node-gyp/14.6.0/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
binding.target.mk:125: recipe for target 'Release/obj.target/binding/src/binding.o' failed
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/root/uwazi/node_modules/node-sass/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/uwazi/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 4.4.0-186-generic
gyp ERR! command "/root/.nvm/versions/node/v14.6.0/bin/node" "/root/uwazi/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /root/uwazi/node_modules/node-sass
gyp ERR! node -v v14.6.0
gyp ERR! node-gyp -v v3.6.2




root@localhost:~/uwazi# yarn add node-sass
yarn add v1.22.4
[1/4] Resolving packages...
warning node-sass > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > react-datepicker@0.46.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0".
warning " > react-datepicker@0.46.0" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0".
warning " > react-flags@0.1.12" has incorrect peer dependency "react@0.13 - 15.x".
warning " > react-router@3.0.5" has incorrect peer dependency "react@^0.14.0 || ^15.0.0".
warning "@types/react-dnd > react-dnd@10.0.2" has incorrect peer dependency "react-dom@>= 16.8".
warning " > eslint-config-airbnb@17.1.0" has incorrect peer dependency "eslint-plugin-import@^2.14.0".
warning "eslint-config-airbnb > eslint-config-airbnb-base@13.1.0" has incorrect peer dependency "eslint-plugin-import@^2.14.0".
warning " > jest-puppeteer@4.4.0" has incorrect peer dependency "puppeteer@>= 1.5.0 < 3".
[4/4] Building fresh packages...
success Saved lockfile.
warning "node-sass" is already in "devDependencies". Please remove existing entry first before adding it to "dependencies".
success Saved 3 new dependencies.
info Direct dependencies
└─ node-sass@4.14.1
info All dependencies
├─ node-gyp@3.8.0
├─ node-sass@4.14.1
└─ sass-graph@2.2.5
$ yarn run snyk-protect
yarn run v1.22.4
$ snyk protect
Successfully applied Snyk patches

Done in 213.20s.
Done in 242.35s.

**Comment by txau** [comment]
@chris260671 I think there is a mismatch between the README instructions for installing and the latest stable (sorry, our bad!) regarding the node version. I suggest that you rather go for the master version https://github.com/huridocs/uwazi/tree/master.

Here is my email: jaume@huridocs.org

**Comment by chris260671** [comment]
No worries Jaume as I said after 30 installs in 5 days I am getting good at it ...LOL ... now if you want to look at what happened on the server ,,,, when i tried to upload i got the same problem again ... it started uploading then went to the blank page .... when i go the console the title of the doc is there but as before no pdf and green button to upload .. if you want to see it ... just go to crimeright.co.uk  and log in with the default admin log in I have not changed the password .... I will send you an email with an ssh user log in so you can look at the server as well ... let me know when you are done ... no worries there is nothing on the server besides uwazi .... and its in root

**Comment by chris260671** [comment]
@txau have sent you email ... by the way I looked now at the link you sent me ... this is the master version i installed and follwed the same dependency instructions ... i only took what you suggested ... and i can not see a difference with this one https://github.com/huridocs/uwazi that i followed or have you just updated?

**Comment by txau** [comment]
@chris260671 just replied to the e-mail. There is nothing wrong with the file itself. The master version should be ok, I wasn't sure if you were trying to run the master one or the latest stable: https://github.com/huridocs/uwazi/releases/tag/v1.6

**Comment by chris260671** [comment]
@txau now i am confused .... should i pull git clone -b master --single-branch https://github.com/huridocs/uwazi.git   or  v.1.6 https://github.com/huridocs/uwazi/releases/tag/v1.6 ?

I assume the git pull with the master .... lol let me try ...

**Comment by txau** [comment]
Just:
```
git clone https://github.com/huridocs/uwazi
```

Also it is definitely odd that with node version 10.21 you are still getting the gyp error. Maybe it is because a newer version of node-sass is already installed and `yarn install` is not downgrading it. I would suggest to make sure you run:
```
> rm -fr ./node_modules
> nvm use 10.21
> yarn install
> yarn production-build
> yarn blank-state
> yarn run-production
```

**Comment by chris260671** [comment]
@txau Sorry it took me so long but i did install so often that Certbot refused to issue a certificate . LOL I forgot about their limit , luckily I have an unlimited cert with the server company but was a bit of a pain to change all the code .. oh well .

Anyway I can confirm that I was running a complete new install with a complete fresh server image and it is 10.21 I downloaded it manually no other node installed . 
I tried to upload the doc again and same issue ... I will upload another that is smaller than 1 mb and you will see it works fine ... something weird going on .. and it cant be server limit because i just uploaded uwazi of 2.6mb via ssh ... 
 I will reinstall you as a ssh user , with the same password ... this is now as well the password for uwazi itself on the webpage crimeright.co.uk  ... so admin and password you have for the server .
I let you have a look ... as I said i don't see where it goes wrong ....
I really follow the instructions to the T ....

**Comment by chris260671** [comment]
@txau Ok i uploaded the other doc ... just fine but it say conversion error ... but still displays it ... have not seen this one before ... :P anyway if you go to private docs you will see 2 docs the one that i send you in the mail ... which does not upload besides the title and the other one i just uploaded with the conversion error ....

**Comment by txau** [comment]
@chris260671 got it. The main problem was due to the proxy not allowing more than 1MB per client request. This seems odd to me since Uwazi uploads are handled with chunks set over web-sockets. So maybe the minimum chunk is bigger than 1MB? I hope @daneryl or @konzz can toss some light on this topic. 

Nevertheless I fixed it by adding this line to you /etc/nginx/nginx.conf and restarting the service:
```
client_max_body_size 100M;
```

The other problem you just reported was caused by poppler-utils not being installed in the system. Probably you were already tired and forgot to run `apt install poppler-utils`, needed for PDF to text conversion etc.

I also created an /etc/systemd/system/uwazi.service file for you. By the way I made sure that it is working with the production build and paths, so look for your logs and uploaded files in prod/ instead (just in case). 

Also you could use just the contents of the prod folder, you don't need anything contained in the parent folder but of course its easier to maintain if you need to upgrade so you just need to run git pull and rebuild.

I suppose once you get this running you'll setup some server hardening? ie. firewalling elastic, uwazi and mongo's ports so they are only accessible via localhost.

Please let me know if everything is running smoothly!

**Comment by chris260671** [comment]
@txau thanks for this .... well i did not even look at nginx to be honest .... i looked every where else , and i knew i had left poppler utils out as i thought ubuntu had this preinstalled to version 0.40 , but maybe i am wrong .

That was my next question with the service file .... lol .

However I can't test it all because for some reason it does not let me log in ... did you change the password by any chance ?

Best Chris

**Comment by txau** [comment]
@chris260671 yeah, I runned `yarn blank-state`. Sorry for not mentioning that =)
