### ISSUE TITLE
Explicit elastic mapping

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#3090]
@txau @daneryl Please write the process to accomplish this

**Comment by txau** [comment]
- Use field alias so we can better support property type changes without breaking Elastic
- The aliases point to the actual indexed field that can be sufixed by type (numeric, string, date, etc)
- Make sure that we fine tune the different indexing options so we don't any unneeded overhead
- Create an artifact that return the mappings when provided with an Uwazi template definition
- Upgrade the module to @elastic/elasticsearch
- Support Elastic 7.9.1
- See if we can recover anything from this PR https://github.com/huridocs/uwazi/pull/3069 and it's issues https://github.com/huridocs/uwazi/issues/3068 https://github.com/huridocs/uwazi/issues/3065
- If possible, remove the node CLI param for the header size bug

**Comment by txau** [comment]
`"doc_values": false`
> If you are sure that you don’t need to sort or aggregate on a field, or access the field value from a script, you can disable doc values in order to save disk space.

We should include this logic in the explicit mapping for fields that are not going to be searched, sorted and used as filter. Since this is an index param, it can be updated when the user marks "use as filter"
