### ISSUE TITLE
Allowing single map view on entity view to compare multiple geolocations

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#3098]
There should be an option (or default to this) to view a single map that shows multiple geolocation properties: both local and inherited.  Keep in mind  that the geolocation field is already prepared to have multiple geolocations itself.  There is no UI for this, but do not break that functionality.

**Comment by simonfossom** [comment]
Connected: https://github.com/huridocs/uwazi/issues/2990

**Comment by simonfossom** [comment]
Here's the [design proposal](https://www.figma.com/file/xjsz7r65epN4B0b96zilac/UWAZI-redesigns?node-id=541%3A23399)

Post comments here or on the design itself.

**Comment by txau** [comment]
> Here's the [design proposal](https://www.figma.com/file/xjsz7r65epN4B0b96zilac/UWAZI-redesigns?node-id=541%3A23399)
> 
> Post comments here or on the design itself.

I cannot access the sigma file, it looks like is not public/shared?

**Comment by simonfossom** [comment]
@txau should work now. pls check

**Comment by txau** [comment]
@simonfossom it works now, ty.

**Comment by txau** [comment]
@simonfossom I guess this proposal is actually doing more than requested:

1. I see you added some controls to add multiple values to a geolocation field. While this is possible and our data structure covers it, this is not really what is needed for this issue. We can discuss the support for multiple values on geolocation fields as a separate issue. So these controls should remain the same as the currently are:
![image](https://user-images.githubusercontent.com/489831/89912306-a576af80-dbaf-11ea-85c0-b212f4909320.png)
2. Mark where it is inherit from: they can be inherited from several templates and properties. I guess this should be rather expressed in each point in the map?
![image](https://user-images.githubusercontent.com/489831/89912705-19b15300-dbb0-11ea-8367-43d49c4e237f.png)

Just to recap what we discussed:
- In an entity you can have geolocation points coming from two different sources: entity's property and inherited properties.
- At the moment all of these are rendered as separate maps both for edition and viewing.
- We want to render them as a single map for viewing, but keep them separated for edition.
- Keep in mind that inherited geolocations are rendered on edit time as a multi-select, not a map. So users pick-up a title, not a point in the map.
- When a geolocation is inherited, we want to render it at view time with the color of the inherited template.
- The final result is that at view time, the user only sees a single map with all the dots. These dots need to be differentiable (on click/mouse over?).
- BTW I think we could make the dots a little bit bigger, they are difficult to spot sometimes.

**Comment by simonfossom** [comment]
Here's an idea: why not show all entity's geolocation data always in only one map? 🤔

**Comment by txau** [comment]
@simonfossom it is a good idea and it would be great to support multiple values and labels. Even location name to coordinates resolution and vice-versa. But that is a way bigger change. Maybe we can discuss it over a call to figure out if it is viable?

**Comment by simonfossom** [comment]
During the product call, we decided to go for editing:
- map per metadata with current editing
- adding show/hide map button on top
- adding a template tag of the linked geolocation

on viewing:
- one map without a title on top
- all locations displayed underneath as tags
- interactions are only on the map as it is now: tap(mobile) or hover showing tooltip

[Design link](https://www.figma.com/file/xjsz7r65epN4B0b96zilac/UWAZI-redesigns?node-id=541%3A23399)

**Comment by simonfossom** [comment]
@RafaPolit @txau can you pls check "view" part if it's ok?

**Comment by simonfossom** [comment]
On a call with Rafa we decided:

- coordinates and titles of linked entities appear as colored pills 
- color of a pill comes from it's template

In editing:
- map is above geolocation metadata as it is now
- 'show map' / 'hide map' button next to the title
- template pill for linked geolocation under the title 

In viewing:
- title of linked geolocation has in parenthesis name of the template
- pills of linked entities are in the color of their original template
- in map pins are in the color of an entity

For single geolocation
- map appears the same as it now: title, map, pills ()

For multiple geolocations one after another
- map is displayed first with all pins from all grouped metadata
- title with pills of each geolocation metadata goes one after another (see design link above)

While editing geolocation metadata there is a note saying:
_Grouping geolocation properties together will show them on the same map._

[Design link](https://www.figma.com/file/xjsz7r65epN4B0b96zilac/UWAZI-redesigns?node-id=541%3A23399)

**Comment by txau** [comment]
@simonfossom looks good to me. I have a concern though: currently users can arbitrarily set the order of appearance of the fields. When showing a single map, in which order is going to appear? Also, is this map condensing all the geolocation points so the original geolocation fields are not being shown?

Also a minor issue. I understand that in most cases when inhering a property from another template, as in this case template `person` is inheriting the property `location of attack` from the template `event`, we want to show the inherited value and its nice to have the title of the inherited template in parenthesis. I can see a usability issue when it comes to scrolling through the list of options trying to locate a particular option by alphabetical order.

**Comment by simonfossom** [comment]
- map order ->  Ah yes, I'll add that in the previous comment to have all in one place.
- condensing all the geolocation points -> if you mean coordinates, then no. Do you think they are needed? 
- minor issue -> if by inherited value you mean coordinates, I'm not sure how helpful that would be. Same as now, we use coordinates to render the map. Pills with titles of inherited properties are there as more of a 'legend' to the map.
- could you expand a bit more on the issue when scrolling the list to locate an option. Not sure what you mean.

**Comment by txau** [comment]
@simonfossom 

> condensing all the geolocation points -> if you mean coordinates, then no. Do you think they are needed?

I mean, when in view mode (not edit), will this map with all the points replace all existing geolocation fields? This is related to the order. Ie. in this screenshot:

![image](https://user-images.githubusercontent.com/489831/93670957-551b2900-fa5c-11ea-9602-3cc40c770b24.png)

All the geolocation fields will be placed together overwriting the user selected sorting of fields?

> could you expand a bit more on the issue when scrolling the list to locate an option. Not sure what you mean.

In this other screenshot, if the user had 100 options, they won't be listed by alphabetical order:

![image](https://user-images.githubusercontent.com/489831/93670990-872c8b00-fa5c-11ea-9e81-c0ba3e9f0de5.png)

**Comment by RafaPolit** [comment]
I proposed that we do it semi-automatic:
- The first map appears in the place of the first geolocation property in the metadata display
- If there are more geolocation properties ADJACENT to that property, they are combined
- If there are properties in between that are NOT geolocation, then they are displayed as normal in the order selected, and any other geolocation cluster of properties will render a new map whenever it appears.

In this way, we give some control on whether or not the geolocations are combined or not, but we don't burden the interface with groups or clusters.

**Comment by txau** [comment]
@RafaPolit sounds good. Let's make sure the grouping criteria is obvious for users so they actually take advantage of it. Maybe this should be an explicit option instead of "adjacency"? A check box or similar.

**Comment by simonfossom** [comment]
Thanks Rafa for replying.
@txau I wouldn't make it explicit. It's better to have a simplified display of information, so automatic is better in ux-sense in my opinion. I've put a note there so whenever the user adds location he'll see and he can act on it. If we make it a checkbox then the grouping needs additional action to happen, which is not desirable.
Also this is in between step to metadata grouping. We'll be working on this more later for sure.

**Comment by fnocetti** [comment]
I started working on this late last week. I already wrote an O(n) algorithm for grouping the adjacent geolocations at a presentation level which is optionally controlled by a flag prop, but haven't worked on the UI yet. It's the next step.
I'm planning to implement a new component for the grouped fields that uses the GeolocationViewer. The latest is already prepared to show multiple markers but doesn't support colors. So, the following is a non-extensive list of what's to do yet:

- [ ] Implement the GroupedGeolocationViewer.
- [ ] Implement the "Show map" button and the list view for hidden mode.
- [ ] Implement the color support for GeolocationViewer.
- [ ] Make the template color available to Geolocation and Inherited fields.

**Comment by RafaPolit** [comment]
Lets discuss this "flag" thing.  Both @simonfossom and I don't think that it was needed.

**Comment by fnocetti** [comment]
> Lets discuss this "flag" thing. Both @simonfossom and I don't think that it was needed.

@RafaPolit @simonfossom I'm sorry for the confusion. It's not a UI flag. I meant that I designed the code in a way that a flag on the component's props activates the grouping feature for reusability purposes, so only a techy thing.
On the other hand, when I said "haven't worked in the UI yet" I meant for the feature, not for the flag.
Again, I'm sorry, and I hope this clarifies.
