### ISSUE TITLE
Entities without document show map in sidebar but not in full-view

### ISSUE THREAD

**Issue by simonfossom** [huridocs/uwazi#3102]
![image](https://user-images.githubusercontent.com/8134850/89784352-ce983100-db18-11ea-86b0-4dd737d822db.png)
![image](https://user-images.githubusercontent.com/8134850/89784387-de177a00-db18-11ea-9266-617a0e3066e7.png)

**Comment by simonfossom** [comment]
I can see it now. 🤷‍♂️

**Comment by txau** [comment]
@simonfossom isn't this caused by the bug in inheritance? https://github.com/huridocs/uwazi/issues/2815 So if the property is not inherited you see it.

**Comment by simonfossom** [comment]
Now that I think about it - it is. Yes. Because I changed the geolocation to be inherited but then instance restarted and returned local property - so there was no more but. 

That explains it. 👍
