### ISSUE TITLE
Change helper text on table of contents TOC for ease of use

### ISSUE THREAD

**Issue by simonfossom** [huridocs/uwazi#3103]
https://www.figma.com/file/xjsz7r65epN4B0b96zilac/UWAZI-redesigns?node-id=546%3A26
(title of frame explains for which role is each text)

**Comment by txau** [comment]
I guess we have improved the problem =)

![image](https://user-images.githubusercontent.com/489831/113816746-74e11880-9732-11eb-92e2-d7083af367f2.png)
