### ISSUE TITLE
Adding item in table of contents TOC make document view crash and keep reloading

### ISSUE THREAD

**Issue by simonfossom** [huridocs/uwazi#3104]
A document was there and after adding a TOC item it just keeps loading back the doc.
![image](https://user-images.githubusercontent.com/8134850/89798743-da8dee00-db2c-11ea-9ec1-e194f14e7c10.png)

**Comment by legitmaxwu** [comment]
Hi, I would like to look into this. May I claim this issue?

Thanks!
Max

**Comment by RafaPolit** [comment]
@legitmaxwu sure! Please let us know how this goes.

**Comment by RafaPolit** [comment]
@legitmaxwu we are reassigning this to our devs, we need this with more urgency now.

Please let us know if you still have availability to work on other issues.  Thanks.
