### ISSUE TITLE
Copy-from UX glitches

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#3109]
- When using it in the side-panel, if you have scrolled down already, you get a blank side panel and you don't see the search box.
- It shows the preview which takes a lot of real state. Maybe this is good for easily identifying the source document to copy from but it takes a lot of real state with info that won't be copied.
- The button label says "copy highlighted". Since there are highlighted fields in both sides it can be misleading when a field is highlighted on the left side (target) but not present on the right side (source). If the point is to tell the user that the field will be overwritten with no values maybe we could use some other visual code.
- Some multi-select fields are overwritten with a blank value instead of no value selected:
![image](https://user-images.githubusercontent.com/489831/90279105-c2b4b380-de25-11ea-83be-db13056ab842.png)

**Comment by fnocetti** [comment]
> * When using it in the side-panel, if you have scrolled down already, you get a blank side panel and you don't see the search box.

I already have a CSS fix for this.

> * It shows the preview which takes a lot of real state. Maybe this is good for easily identifying the source document to copy from but it takes a lot of real state with info that won't be copied.

After discussing with @simonfossom this is more a bug than a glitch. The preview is not meant to be copied (nor its actually copied) and it's not only shown but also highlighted. We need to fix it.

> * The button label says "copy highlighted". Since there are highlighted fields in both sides it can be misleading when a field is highlighted on the left side (target) but not present on the right side (source). If the point is to tell the user that the field will be overwritten with no values maybe we could use some other visual code.

Agreed with Simon that this can be improved by adding the title to the section and using a more descriptive icon on the copy highlighted button.
Also, at some point it would be nice to have a color code signaling the pairs of fields to be copied. If I have time I'll give it a try, but a bit complex.

> * Some multi-select fields are overwritten with a blank value instead of no value selected:
>   ![image](https://user-images.githubusercontent.com/489831/90279105-c2b4b380-de25-11ea-83be-db13056ab842.png)

@txau I haven't been able to reproduce this yet. Would you be able to provide any insights?

- Which data set you tested this on?
- Where you copying from an entity of a different template?

**Comment by txau** [comment]
@simonfossom @fnocetti yet another glitch, when hitting "back to search" after selecting a document, it clears out the search. This is very annoying if you miss-clicked the wrong record or if you were just exploring the "copy from" record.

**Comment by txau** [comment]
@fnocetti regarding the bug, I haven't been able to reproduce it either, so probably is not that common? Sorry, my bad I didn't capture the exact steps when I reported.
