### ISSUE TITLE
Performance issues on VPS

### ISSUE THREAD

**Issue by sborrajo** [huridocs/uwazi#3121]
CPU Cores | 6
Total CPU Speed | 14.4Ghz
Memory | 6Gb
OS | Ubuntu 18.04 64bit
Uwazi v1.6

On our Uwazi instance uploads via CSV take a long time to complete, and create a CPU spike where Node and Elastich hog 100% of the CPU capacity. This reverts to normal after upload is complete.
However, after several entities have been created via uploads, the slowdown and CPU spike happens with almost any action taken in the Uwazi UI, making navigation and entity update very difficult.

**Comment by txau** [comment]
@sborrajo what version of mongo db are you using? there is a known issue with WiredTiger cache with Mongo 4.0.x.

**Comment by sborrajo** [comment]
Hi! Updating has solved some of the performance issues. Thanks!

**Comment by sborrajo** [comment]
>

**Comment by RafaPolit** [comment]
I am seeing this same performance problems on our own infrastructure with other collections.  Maybe this is worth investigating further?

**Comment by txau** [comment]
@RafaPolit is that related to the disk latency problem? if so I guess we can close this issue.

**Comment by RafaPolit** [comment]
Yes, some was latency, perhaps the batches on logs also.  This is, for the time being, fixed.
