### ISSUE TITLE
Thesauri don't display translations

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#3122]
In an Uwazi with two languages, create and translate a thesaurus (both thesaurus title and items).

It does not get translated in:
- settings > translations
- settings > translations > [that thesaurus]
- settings > thesauri
- settings > thesauri > [that thesaurus]
- Library filters
- Upload filters

It does get translated in 
- side panel entity view/edit
- entity card
- full entity view/edit

**Comment by RafaPolit** [comment]
For 'settings', we need to keep the original values, as they are not labels.   Still, there is alternatives to show the translations along with the original values. @simonfossom will work on this on #3129.

We actually need to fix:
- [ ] Library Filters for thesauri-based properties
- [ ] Upload Filters for thesauri-based properties
