### ISSUE TITLE
Look into request timeouts for long-processes

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#3130]
Some processes that are very long, time out without any feedback: template structure changes on large collections, for example.

Large uploads also, and these are more critical because they actually prevent the entity from being created.

**Comment by daneryl** [comment]
Check how many requests we have that trigger our 60 second timeouts before deciding how to proceed.

**Comment by RafaPolit** [comment]
This is being rolled out on a per-case basis.  Closing this for now.
