### ISSUE TITLE
CSV export fails on entities without template

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#3131]
When you upload a document, the entity gets created without a template.

This has been a source of problems before.  We should assign the default template to those entities.

If not, exporting to CSV when there are un-templated entities produces an error.

**Comment by txau** [comment]
@RafaPolit we added the default template approach precisely for this. I just run a test and uploading a document will assign the default template. Also, you cannot delete a template if it has documents assigned. How do you get to a state were they have no templates assigned?

**Comment by txau** [comment]
This scenario only happens if the user already had entities with no template assigned in uploads before we deployed the "default template" feature. The existing entities were not migrated to a particular template. We can ignore this.
