### ISSUE TITLE
CSS glitch on sidepanel for mobile

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#3133]
<img width="300" src="https://user-images.githubusercontent.com/489831/91228213-1dcb8d80-e6e5-11ea-8757-f62f3ed26e71.png" />

**Comment by txau** [comment]
@simonfossom a quick fix could be making the buttons smaller for  smaller screens.

**Comment by simonfossom** [comment]
Can't we make side panel full width?

**Comment by txau** [comment]
@simonfossom ok. let's do that.

**Comment by nwyu** [comment]
A continuation of the above report. Upon Edit of main document, buttons on mobile appear as such:
![image](https://user-images.githubusercontent.com/56067374/101431326-edf86c80-3906-11eb-85e2-649e6fcffaab.jpeg)

**Comment by txau** [comment]
Fixed
