### ISSUE TITLE
Elastic too_many_buckets_exception error

### ISSUE THREAD

**Issue by sborrajo** [huridocs/uwazi#3134]
CPU Cores | 6
Total CPU Speed | 14.4Ghz
Memory | 6Gb
OS | Ubuntu 18.04 64bit
Uwazi | v1.6
Mongo | 4.2.8 
Elastic | 7.6.2

The following API call:

`http://uwazihost/api/search?allAggregations=true&from=0&includeUnpublished=true&limit=1`

Returns this error:

`"[too_many_buckets_exception] Trying to create too many buckets. Must be less than or equal to: [10000] but was [11217]. This limit can be set by changing the [search.max_buckets] cluster level setting., with { max_buckets=10000 } (and) [too_many_buckets_exception] Trying to create too many buckets. Must be less than or equal to: [10000] but was [10997]. This limit can be set by changing the [search.max_buckets] cluster level setting., with { max_buckets=10000 } (and) [too_many_buckets_exception] Trying to create too many buckets. Must be less than or equal to: [10000] but was [11387]. This limit can be set by changing the [search.max_buckets] cluster level setting., with { max_buckets=10000 }"`

So far we seem to have solve the issue by increazing the Elastic _search.max_buckets_ parameter to 20000. Is this a recommended solution? I understand this could create issues in memory ussage.

Thanks!

**Comment by txau** [comment]
@sborrajo I guess your are dealing with a fairly big collection =)

From the error message I can see your search aggregations are attempting to create up to 11.387 buckets, so with 10.000 you were not that far from the default limit. Apparently this 10k value [was a breaking change introduced in Elastic 7.x ](https://www.elastic.co/guide/en/elasticsearch/reference/7.0/breaking-changes-7.0.html#search-max-buckets-cluster-setting) and also it seems to have been reverted to its previous default (65.535) in [Elastic 7.9](https://www.elastic.co/guide/en/elasticsearch/reference/7.9/search-aggregations-bucket.html).

I haven't followed the conversation but apparently this decision even [affected Kiabana's defaults](https://github.com/elastic/elasticsearch/issues/42001) and they decided to set the limit to 65.535.

While having too many buckets can eventually trigger an OOM issue, I think you are still within a safe range and increasing the max buckets to 20k should be ok!
