### ISSUE TITLE
Library issues

### ISSUE THREAD

**Issue by simonfossom** [huridocs/uwazi#3139]
- [ ] remove Restart button, there is [x] in search 
- [ ] remove Search button, please please remove that
~~"select-all" selects now all but only loaded/displayed entities. This is unexpected. Select all should select all even if they are not loaded.~~
- [ ] show "CSV Export" only when some (or all) entities are selected.

**Comment by RafaPolit** [comment]
> * "select-all" selects now all but only loaded/displayed entities. This is unexpected. Select all should select all even if they are not loaded.

Just to signal that this particular point is, by no means, an easy fix.

**Comment by simonfossom** [comment]
Ok, let's do the other ones. After thinking about it a bit, there's rarely use to "select all". I would put a JS-trigger on it just to see if anyone is trying to use it.

**Comment by simonfossom** [comment]
I've moved the select-all issue here: https://github.com/huridocs/uwazi/issues/3417

**Comment by nwyu** [comment]
Closing this issue in favor of #3186.
