### ISSUE TITLE
Migration required for "ghost" metadata

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#3141]
Previously, we did not sanitize the metadata.  Upon deleting a property, the metadata value for existing entities would remain as data of the entity.

Now, if you delete a property, entity's metadata gets sanitized and that property is removed (as should be).

Still, we never migrated the metadata to delete those ghost values.  The problem is that, for old collections that already have this ghost metadata, if you try to update the template, resaving the entities causes failed validations, because you are sending properties that are no longer supported by the template.

There is a "workaround" which is to recreate the template property, save the template, and now delete it once more.  Now, our sanitizing procedure works and deletes the entity's metadata key.

Still, this is very obscure and convoluted, not to mention really undecipherable for a non-tech user.

We need to migrate the entities to be sanitized and free of these ghost values.

**Comment by daneryl** [comment]
@RafaPolit im not able to replicate, i have tried setting a fake metadata to all entities and then saving the template, this results in a successful save.
i still made the migration that fixes "ghost" properties before trying to replicate https://github.com/huridocs/uwazi/pull/3145, but it does not seems a problem right now.

**Comment by daneryl** [comment]
i was not able to reproduce the issue but we know there is this ghost data and the migration fixes this data state, we continue with the PR.
