### ISSUE TITLE
Library sorting does not get updated in the URL

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#3158]
Replicate:

1. Go to library
2. Select some sorting criteria

The URL does not get updated with the criteria. Sometimes, the page reloads and the sorting gets reset back to relevance.

**Comment by RafaPolit** [comment]
Check if #3156 solves this also?

**Comment by fnocetti** [comment]
@mercy noted that the issue is only reproducible when a text search is in place (thats when the relevance criteria kicks in).
Anyways, this not solved by #3156 and actually looks like an independent issue.
