### ISSUE TITLE
issues with pdf uploads

### ISSUE THREAD

**Issue by hapee** [huridocs/uwazi#3161]
I am running Uwazi self hosted and after completion of the installation I tried to upload pdf documents and some work without a problem but some dont at all and I end up for example on a blank page with url ending on 
en/entity/bx1wh1igt7
firefox console says Uncaught TypeError: e is null
when I try to upload the document the timer goes to uploading 100% and than it stops and no document is uploaded.

Is there a file setting or an upload limit somewhere that could cause this?
Is there a way to see filesize in Uwazi at all?

Thanks in advance.

**Comment by RafaPolit** [comment]
Thanks for the report.

Have you any load balancer in place in front of the Uwazi server, or are you using the Uwazi server directly?

If you have put a load balancer like NGINX in front, those usually have relatively low file size defaults.  If not, Uwazi is using the default Express limits, which I think are about 100MB or so.

Are you confident this is a size limitation? Could it be that the PDFs themselves are formed different? If you suspect the later, can you share one of the 'failing' PDFs so we can test it on our infrastructure?

Just to note, we had a critical bug regrading uploads on 1.7.0 that was fixed on 1.7.1.  So, if you are running the older version, please update with the recent fix.  But this would have prevented all uploads, so this will probably not solve your issue.

**Comment by hapee** [comment]
Thanks Raphael,

I am using NGINX in fron of it I will check that settings but it might not be a files size issue indeed, can you check the attached pfd if it works on your environment?

I have installed 1.7.0 today on two different machine and both have the same issue so glad that is is consequent ;-)
[april_2015-mmr.pdf](https://github.com/huridocs/uwazi/files/5189919/april_2015-mmr.pdf)

**Comment by RafaPolit** [comment]
NGINX has a 1Mb file upload limit set by default.  It may very well be that this is causing the problems.

I have tried your file on our Demo instance and it works.  Here is what to expect with large / complex PDFs:
- Upload the PDF file, watch the Upload progress bar grow until 100%
- Once uploaded, watch the Processing bar progress... this PDF in particular took about 10 seconds to process on our servers

![Up-A1](https://user-images.githubusercontent.com/4309019/92517115-c8f73f00-f1db-11ea-8744-3c5fb5929b05.jpg)

- Once the "processing" is finished, click on the card to check that the file is actually registered as part of the "Documents" section:

![Up-A2](https://user-images.githubusercontent.com/4309019/92517184-e3c9b380-f1db-11ea-8a34-7f435bd1b78a.jpg)

- After that, click on the "view" button of the card or on the side panel.  IMPORTANT: The first time a document is accessed, the client processes that document and sends a report on the amount of characters per page to the server, which then stores that data and returns that to the client.  This can take a long time, especially if the client from which you are accessing the document is a slower machine or tablet.   That process can take a while, so be patient.  After that first load, subsequent loads will not do this extra procedure and load much faster.

Here is the result on our servers:
![Up-A3](https://user-images.githubusercontent.com/4309019/92517435-46bb4a80-f1dc-11ea-900c-fd92724f67d6.jpg)

Our servers are running 1.7.1.

Can you confirm you have Poppler Utils installed on your system?  Perhaps it is the client-side process which is prevented somehow? What OS / Browser are you using to access the file the first time?

**Comment by hapee** [comment]
thank Raphael,

that helped:
![image](https://user-images.githubusercontent.com/379964/92520025-42625200-f21b-11ea-8f3a-dfd22eca3235.png)

I will check the poppler utils and Firefox is my daily driver but I tested it with Chrome as well but it was nginx that I had to adept, thanks for pointing me there.

**Comment by RafaPolit** [comment]
Glad it helped and that you have it running correctly.
