### ISSUE TITLE
Selecting the target entity when adding relationships in the entity tree does not get updated

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#3191]
This is a minor issue but can be misleading for users under certain circumstances.

Steps to reproduce:

1. Go to the relationship tree of an entity.
2. Edit and search.
3. On another tab, go to uploads an create a new entity that could be used as target entity.
4. Go back to the first tab and try to add an entity.
5. The new entity should be listed in the potential targets but instead the search results are sort of "cached".

Possible solution: when users hit the "Add entities or documents" button the result list gets updated.

**Comment by daneryl** [comment]
Closing since there is no uploads anymore and now we have create entity from the tree view.
