### ISSUE TITLE
Table View improvements

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#3196]
Now that the MVP for table view is merged, we should keep on improving some details:

- [ ] Use translated property names (where to pick the translations from is tricky)

- [ ] Keep the column selector open for selecting more than one column at a time? (discuss)
- [ ] Show a "loading..." or spinner when the infinite scroll is loading to give feedback to the user when response is not immediate
- [ ] Maybe use a width 100% so when there are few columns they will still fill the available realstate? (discuss)
- [ ] Figure out a way to keep the footer visible (this probably involves isolating the 'load more' buttons into a reusable component and refactoring the library components)
- [ ] Solve initial column selector naming... it reads "hide columns", when you could also show more columns

**Comment by RafaPolit** [comment]
@fnocetti wrote:

Things that were not included in this MVP
- Implementation of the re-designs (layout and new toggle buttons)
    - New layout
    - New toggle buttons
    - Filters side panel hidden by default
- Specific behavior on rows selection and multi-selection
    - Multiple selected document list should not appear on side panel
    - Selecting entities with the checkbox should not open the side panel
    - Clicking on the row should not change selection status but open the side panel metadata view
- Column resizing (and re-ordering?)
- Filters and orders on table headers. Filters matching highlights on table cells values
- Complex types rendering: geolocation, image, media, nested (to be reviewed with Simon)
- “Hide unselected” and “select all” (title header) checkboxes
- Export CSV button on main view instead of side panel

**Comment by RafaPolit** [comment]
From partner impressions:
- Should we allow to default to table view instead of card view option? (settings config? user config?)
- Option to create a URL that defines the selected columns so that it can be shared via LINK
- Column ordering - separate from template property order - 
- Custom CSSs applied to rows depending on the values of certain properties (class escape rows?)
- If there is a single template selected, remove the template column?

**Comment by Predragh** [comment]
Hello, from the GIJTR/HRDI Iraq project's user experience, it would it be so much useful to have 'User' column in table view filter selection, next to the "Date added". This would help better project management,trust-building, and overview of work quality. 
Thank you for considering.

**Comment by txau** [comment]
Will break down to smaller issues.
