### ISSUE TITLE
Cannot save date properties when in AR version of Uwazi instance

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#3198]
When you are in the AR language of an Uwazi instance, try to create an entity, select a date in any date property -- the date you have entered disappears when you click "return" or simply click out of the property. The date is not saved. 

![Gif of issue](http://g.recordit.co/te5SZxiTsv.gif)

I have confirmed this same bug in two different Uwazi instances that use AR language.

**Comment by RafaPolit** [comment]
Confirmed bug.  Moved to priority Critical, looking into it.
