### ISSUE TITLE
Display of  name of template in arabic 

### ISSUE THREAD

**Issue by Ilyes-Chiha** [huridocs/uwazi#3199]
hello 
I have predecessily translate the name of templates into arbic and it displaed correctly (in arabic version ) but now it will display only in english ( latin lettres not in arabic letters) in arabe version of display. however i verified the translation and  it was correct. but the display in arbic version dont work the name of template  display only in  english in arabic version

**Comment by RafaPolit** [comment]
Thanks for the report.

Can you confirm in what place you are experiencing this issue?  Is it the template names on the cards within the library?  Is this on the entity or document view?  Or is this in the template editing within the settings?

The first cases should not happen, but inside settings it is intended.  Can you please confirm where are you experiencing this issue?

Thanks.

**Comment by daneryl** [comment]
closed due to inactivity
