### ISSUE TITLE
Design question

### ISSUE THREAD

**Issue by hapee** [huridocs/uwazi#3205]
not sure if the question belongs here but on a selfhosted Uwazi instance I am looking for some information on where to customize design a little, add a logo, make some links, I use this as an example:
https://cyrilla.org/library/
where and in which files can I change the header template.

Kind regards,
Hapee

**Comment by whyfrycek** [comment]
Hi @hapee - you can do that in the settings of your collection. Some of what you're asking about is covered here in the documentation: https://uwazi.readthedocs.io/en/latest/admin-docs/designing-your-website.html (links in the menu, visualisations)

For CSS, this seems to not be covered in the documentation just yet, but you can do so in the interface, by going to settings --> collection --> and scrolling to the bottom where you find a button "custom styles".

Hope this helps!

**Comment by hapee** [comment]
Thank @whyfrycek nice to be helped by you, this is what I was looking for thanks.
