### ISSUE TITLE
Add multi-select to filters with both documents and entities to select types

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#321]

**Comment by danicatalan** [comment]
![multiselect-flow](https://cloud.githubusercontent.com/assets/6364153/17939282/362545ce-6a2a-11e6-81ed-a2dc79d2a8ec.png)

**Comment by danicatalan** [comment]
Show less button:
![screenshot 2016-08-24 18 43 16](https://cloud.githubusercontent.com/assets/6364153/17939374/aceaf672-6a2a-11e6-98e1-bce8a2b80d3a.png)

**Comment by danicatalan** [comment]
Basic multi-select
![screenshot 2016-08-26 17 24 20](https://cloud.githubusercontent.com/assets/6364153/18010968/3d9e129c-6bb3-11e6-9bfc-278e6f6533db.png)

:hover and :checked options while creating the query
![screenshot 2016-08-26 17 24 30](https://cloud.githubusercontent.com/assets/6364153/18010969/3da0863a-6bb3-11e6-9e99-38ad0179e5f5.png)

Active items when the query is done
![screenshot 2016-08-26 17 26 15](https://cloud.githubusercontent.com/assets/6364153/18010972/3da3471c-6bb3-11e6-8cc5-42946ff8afe8.png)

Off/on property (for filters)
![screenshot 2016-08-26 17 32 45](https://cloud.githubusercontent.com/assets/6364153/18010970/3da2663a-6bb3-11e6-8863-31df0e9d2e7b.png)

![screenshot 2016-08-26 17 30 32](https://cloud.githubusercontent.com/assets/6364153/18010971/3da31e9a-6bb3-11e6-9737-3e0f9c1be9e3.png)
