### ISSUE TITLE
Geolocation field tossing a JS error

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#3210]
It doesn't crash the application or prevent's it from working.

1. Add a geolocation field to an existing template.
2. Go into entity view and hit edit.

![image](https://user-images.githubusercontent.com/489831/94273796-212f8000-ff02-11ea-9c44-29ba0c610060.png)

**Comment by fnocetti** [comment]
The TypeErrors were addressed in #3273 
The React warning is a no-op and really expensive to solve at this point so we are tracking it on a different tech debt issue #3281
