### ISSUE TITLE
Issue with selecting and deselecting filters and sub-filters 

### ISSUE THREAD

**Issue by natasha-todi** [huridocs/uwazi#3215]
When trying to deselect a filter on the sidebar, the system automatically deselects all the other filters that were selected as well. Please refer to the screen record to see an illustration of the issue.  

[Screen Recording 2020-09-26 at 16.30.46.mov.zip](https://github.com/huridocs/uwazi/files/5288520/Screen.Recording.2020-09-26.at.16.30.46.mov.zip)

**Comment by txau** [comment]
This or a similar bug has already been reported: https://github.com/huridocs/uwazi/issues/2942 Let's try to fix soon.
