### ISSUE TITLE
Error on file download when filename contains non basic ascii characters.

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazi#3219]
`
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Disposition"]
    at ServerResponse.setHeader (_http_outgoing.js:546:3)
    at /srv/data/uwazi/core-1601282998/app/api/files/routes.js:82:13
`

the case tested contains the `’` character.

**Comment by daneryl** [comment]
fixed by using accepted answer here https://stackoverflow.com/questions/23895924/expressjs-download-filename-utf-8

**Comment by txau** [comment]
@daneryl can we close the issue then?
