### ISSUE TITLE
Multi-select metadata building block

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#322]
- Create the field type based on our newly created multi-select filter
- Create the field
- This can replace our current filter for select
- Add to metadata view. 

@danicatalan we need to create a design for this. How are we going to represent the options in metadata? Some examples of where this is going to be used:
  - The judges signing a sentence
  - Tags assigned to an entity or doc
  - Mechanisms used in a court case

/cc @konzz

**Comment by danicatalan** [comment]
![screenshot 2016-08-26 19 06 26](https://cloud.githubusercontent.com/assets/6364153/18013824/43de0826-6bc0-11e6-921d-9b6fc9d18ea8.png)

@konzz check `322-multiselect-metadata-view` to get the css styles.

**Comment by danicatalan** [comment]
Close.
