### ISSUE TITLE
tableview: text cutoff when two or more lines

### ISSUE THREAD

**Issue by simonfossom** [huridocs/uwazi#3221]
<img width="352" alt="Screen Shot 2020-09-28 at 16 26 34" src="https://user-images.githubusercontent.com/8134850/94447413-041cda80-01aa-11eb-8984-dc2e04f552b1.png">

**Comment by fnocetti** [comment]
@simonfossom  This happens specifically for Markdown/Richtext fields.
The markdown renderer has its own styles. We need to work in a CSS reset for the fields or figure a better way to show the contents.

**Comment by txau** [comment]
@simonfossom so what is the bug? do we want cut-off or we don't want it?

**Comment by fnocetti** [comment]
> @simonfossom so what is the bug? do we want cut-off or we don't want it?

@txau 
I think he reported this like this was for text fields, but this actually happens to MD. Text fields should be fine. So I think we should move the conversation to #3222

**Comment by txau** [comment]
> > @simonfossom so what is the bug? do we want cut-off or we don't want it?
> 
> @txau
> I think he reported this like this was for text fields, but this actually happens to MD. Text fields should be fine. So I think we should move the conversation to #3222

Ok, got it. I think it makes sense to CSS-type the rows and columns depending on the kind of content they contain so the visuals can be properly adapted.

**Comment by simonfossom** [comment]
The issue is that if cut-off happens user can't read the text. That makes it not useful. So we can either display with better formating or not display the last row.

Another issue is if we want to display rich text fields we have to invite users to read the full thing.
The solution was to click the row to open in the sidebar - the same way as cards work.

**Comment by txau** [comment]
@simonfossom I thought the cut-off was intentional so users *hint* there is extra text?

**Comment by simonfossom** [comment]
By design, we said it would be just truncated and you can click the row to see all.
![image](https://user-images.githubusercontent.com/8134850/94559023-ebbbc700-0260-11eb-8597-60778f108c33.png)

If we can't do that, I would recommend a link that opens a row where there is a truncation:
![image](https://user-images.githubusercontent.com/8134850/94559192-27ef2780-0261-11eb-8de6-30883d717db9.png)

The best in my opinion is to enable click the row (anywhere) to open sidepanel. It would also be great if we could trigger popup over truncated cells to see full content just of that cell. That way user doesn't have to do anything. If he would hover over the cell for 2 sec the popup would appear with full text. So as he reads the full text appears. (Although with this we might be overdoing it.)

![image](https://user-images.githubusercontent.com/8134850/94559684-e6ab4780-0261-11eb-8299-3591ae1ee7a0.png)

I'd like to do some user interviews to see what would be expected behavior and does this break userflows  before we continue with it.

Will report back.

**Comment by txau** [comment]
> The best in my opinion is to enable click the row (anywhere) to open sidepanel. It would also be great if we could trigger popup over truncated cells to see full content just of that cell. That way user doesn't have to do anything. If he would hover over the cell for 2 sec the popup would appear with full text. So as he reads the full text appears. (Although with this we might be overdoing it.)

This sounds good to me.

**Comment by RafaPolit** [comment]
I agree on the click row.

I actually also think it's a good solution to have a 'half line' (perhaps with a gradient like in the cards) to hint there is more to the text you are reading.

If we show three lines "exactly", it could appear that that is the whole extent of the text.  This allows this notion of: there 'could' be more.  So I thought it was a happy coincidence that it happened like that without tinkering the CSS further.
