### ISSUE TITLE
Customised header for GUARDINT database

### ISSUE THREAD

**Issue by guardint** [huridocs/uwazi#3236]
Hey there, I am new to GitHub and I have no idea if this is the right way to get my problem solved.

We set up this UWAZI database (https://data.guardint.org/en/library/) for our project GUARDINT and we would like to integrate our design (Logo, colour…) in a customised header.

To do so at the UWAZI docs I am advised to create an issue here.

The attached PDF shows our aimed appearance and I also attached our logo.
[GUARDINT_Website_Database_V1.pdf](https://github.com/huridocs/uwazi/files/5329133/GUARDINT_Website_Database_V1.pdf)

![GUARDINT_Logo_one-line_RGB](https://user-images.githubusercontent.com/72407620/95113698-2206b400-0743-11eb-9e04-159015b45195.png)

Can somebody please help me with this?

**Comment by txau** [comment]
@guardint it is pretty easy to do it yourself, you can take a look to this section of the documentation with some sample code: https://uwazi.readthedocs.io/en/latest/admin-docs/designing-your-website.html#customise-the-header
