### ISSUE TITLE
Inherited field label not translated on sidepanel

### ISSUE THREAD

**Issue by fnocetti** [huridocs/uwazi#3237]
When inheriting a property from a relationship, the label is not being translated when shown in the sidepanel.
This is because the translateContext it is receiving is the one for the inherited property, but the label is defined in the inheriting tamplate (the label for the relationship field).
It is probably being overwritten in the `inherit` function of the `formater.js` file.

**Comment by konzz** [comment]
This looks to be fixed by the backend denormalization.
