### ISSUE TITLE
Provide support for custom "type icon" in entities and documents

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#324]

**Comment by danicatalan** [comment]
Step 1: Differentiate between Entities `fa-bank` and Documents `fa-file-text-o`.

![screenshot 2016-08-22 17 42 59](https://cloud.githubusercontent.com/assets/6364153/17861060/e4023f68-688f-11e6-8825-f675f1b662b3.png)

Step 2: Create an option on settings to let the user select icons for every entity/doc type.

**Comment by danicatalan** [comment]
Deprecated. We just delete those icons and now cards just have the label:

![image](https://cloud.githubusercontent.com/assets/6364153/20715084/4fde1a98-b64e-11e6-86de-959afbb2ff68.png)
