### ISSUE TITLE
Replace map dot with map-marker on main map

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#3241]

**Comment by RafaPolit** [comment]
This requires a Canvas object to be passed to the Supercluster library, so we will tackle this later.

**Comment by fnocetti** [comment]
> @RafaPolit the problem was with dot visibility and can be solved with bigger dots, no necessarily with markers.

I tried this and it improves the readability a lot. I'll include it on the PR for  #3240 and we can decide later if it would close this issue.
