### ISSUE TITLE
Import CSV slows down if creation of thesaurus values is needed [timebox 1 day]

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#3242]
Import CSV runs very fast when the row uses existing thesaurus values.

If the row needs to create one or more thesaurus values in different thesauri, it really slows down 10x or more.

Pre-computing the values to be added, adding them, and then moving on with the import could significantly improve import time.

This is probably also true for relationships.

**Comment by txau** [comment]
typeParsers are querying the database each time a row in the CSV is processed. There is no caching strategy. My initial hunch is that we need to abstract away an in memory copy for thesauri and related entities that contains its own strategy for handling new additions.

**Comment by LaszloKecskes** [comment]
The call eventually reaches the [/api/import](https://github.com/huridocs/uwazi/blob/a8d771cf70d7790852e8fd34f9b407539d2ffda4/app/api/files/routes.ts#L187) endpoint, where it calls [csvLoader load function](https://github.com/huridocs/uwazi/blob/a8d771cf70d7790852e8fd34f9b407539d2ffda4/app/api/csv/csvLoader.ts#L44). Then it goes to the file [importEntity](https://github.com/huridocs/uwazi/blob/d1d26da1d35630ee08fb28353e4684103fa9b78d/app/api/csv/importEntity.ts) via the importEntity and translateEntity functions.

In general, during the processes in that file there are various database calls that happen entity by entity. Specifically, while parsing the values, the [select typeparser](https://github.com/huridocs/uwazi/blob/d1d26da1d35630ee08fb28353e4684103fa9b78d/app/api/csv/typeParsers/select.ts) saves non-existing values in the thesaurus.

A generated import csv generated the following timings to see that the difference comes from the parser:
without thesaurus entries:
	Total time spent in importEntity and translateEntity: 34472.30907795951
	Time spent in select formatter: 26769.520630031824
	Entire api call time:: 34.514s
with existing thesaurus entries:
	Total time spent in importEntity and translateEntity: 11290.365173023194
	Time spent in select formatter: 968.8885739520192
	Entire api call time:: 11.335s
	
This example focused on the select fields, but other type parsers that use the thesauri (i.e. multiselect) are probably also affected, and need to be checked.

**Comment by LaszloKecskes** [comment]
With the pre-flight implementation, the new values look like this:
	without thesaurus entries:
		time spent in arrageThesauri: 350.931ms
		Total time spent in importEntity and translateEntity:11677ms
		Time spent in select formatter: 861ms
		Entire api call time:: 12066ms
	with existing thesaurust entries:
		time spent in arrageThesauri: 23.217ms
		Total time spent in importEntity and translateEntity:11373ms
		Time spent in select formatter: 1713ms
		Entire api call time:: 11440ms
So we have made the extra 26 seconds for the thesauri saving considerably shorter.

As a stress test, I have run an import file with 2 fields (1 select, 1 multiselect), 1000 new values each, with a total of 1M entities. The thesauri saving passed in 9 seconds, and I've let the counter run until 50K imported entities. With this, I think the informal requirement of a "couple of hundred thesauri values" and a "few hundred thousand entities" should be okay.
