### ISSUE TITLE
Rison decoding errors break the client app

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#3244]
Running searches containing certain characters break the app with a blank screen. Ie, searching for "title:contreras" tosses these errors:
```
rison parser error:  missing ',' vendor.bundle.js:1:300385
rison parser error:  missing ':' vendor.bundle.js:1:300385
rison parser error:  missing ',' vendor.bundle.js:1:300385
rison parser error:  missing ':'
```

**Comment by txau** [comment]
Related: https://github.com/huridocs/uwazi/issues/2665

**Comment by mfacar** [comment]
> Related: #2665

@txau #2665 is not directly related to this issue, I'm opening a new PR for this one and I'll comment over #2665 as a separate issue.
