### ISSUE TITLE
Partner request for connections to show up in both the entities' card view 

### ISSUE THREAD

**Issue by natasha-todi** [huridocs/uwazi#3255]
In Uwazi when we creates connections between two entities, the connection is visible in the card view only in the first entity (as seen in the attached video). In order for the relationship to show up in the second entity's card view as well, the partner created another relationship from the second entity to the first entity. This however shows up as a second relationship instead of a bi-directional relationship ( as seen in the attached video). 

The partner request is instead of creating two different relationship hubs to depict the same relationship, would it be possible to show the relationship in the card view for both entities that are connected in any given relationship? Their use case is that they want lawyers and researchers to be able to click on any entity and see all relationships and connections. At the moment, because it does not show up on the card view, their end user will have to click on the full view button and only then can  they see the connections symbol and see that a relationship exists. 

[TJWG_Issue.mp4.zip](https://github.com/huridocs/uwazi/files/5376651/TJWG_Issue.mp4.zip)

**Comment by txau** [comment]
@natasha-todi there is an easier way: they can add the type of relationship to the other case as well, so this screen from your video:

![relationship with no label](https://user-images.githubusercontent.com/489831/96058142-c5dd1780-0e47-11eb-959b-6229a2100b6c.png)

The "right side" of the relationship has no label, therefore it is not matching the config of the field that must have the relationship type "Related to". You can add the right side label so it looks like: 

![relationship same labelpng](https://user-images.githubusercontent.com/489831/96058838-93341e80-0e49-11eb-8897-d2d9fb017770.png)

This way they don't need to duplicate the connection, just add the same label to both sides. The only caveat in this scenario is that Uwazi will behave this way:

![image](https://user-images.githubusercontent.com/489831/96058955-da221400-0e49-11eb-8413-c9db10f2a158.png)

So as you can see `Case 2` appears as related to `Case 2` but I don't think this is a blocker for the users in any way.

**Comment by natasha-todi** [comment]
@txau Thank you for showing me this easier way! Just to follow up, is there a way to do this via csv import because the partner is bringing in at least 500 records and is importing the relationships as well.

**Comment by txau** [comment]
> @txau Thank you for showing me this easier way! Just to follow up, is there a way to do this via csv import because the partner is bringing in at least 500 records and is importing the relationships as well.

I'll check it out.
