### ISSUE TITLE
Information that has been entered within properties is not being saved leading to undercounting 

### ISSUE THREAD

**Issue by natasha-todi** [huridocs/uwazi#3264]
As seen in the screencast attached, for the example of the template Victim, entity E12: in the beginning there is no property Criminal Charge that is visible on the entity. When one clicks on edit, the information is already filled out as seen in the ticked criminal charges - _Refoulement of religious adherents and religious practices_ but has not been saved by the system. 

The partner has reported that they noticed this lead to serious undercounting in their database where within entities they realised, that the information they filled out and made sure to save exists, but has not actually been saved and thus is not counted by the filter on the side bar. 

[Screen Recording 2020-10-18 at 19.29.31.mov.zip](https://github.com/huridocs/uwazi/files/5401637/Screen.Recording.2020-10-18.at.19.29.31.mov.zip)

**Comment by natasha-todi** [comment]
@RafaPolit following our discussion in the coordination call yesterday, the partner said they brought in all their data manually and that too in September which is quite a while back. When they noticed the missing labels, they had already tried refreshing the browser or navigating to another tab in Uwazi (as you suggested yesterday), however that did not make the system index the new data. I think we might need to look into this further.

**Comment by natasha-todi** [comment]
Issue is still ongoing, may need to look into this once more. Thank you!@RafaPolit

**Comment by daneryl** [comment]
@natasha-todi i can not confirm this is happening anymore, pls keep us updated in case it is.
i think this should not be on the github issues as it is data/partner specific ?

**Comment by nwyu** [comment]
We were unable to recreate this problem. This issue will be closed for now. We can reopen it again if the partner reports that this is still happening.
