### ISSUE TITLE
CSV export is outputting dates in the wrong format.

### ISSUE THREAD

**Issue by fnocetti** [huridocs/uwazi#3272]
When the administrator selected a date format in the collection settings the CSV export is producing dates using for the day a format like "we/07/1993".
This is because the dates formats were updated to work with the DatePicker (which not longer uses moment.js internally), but now they're messing with the algorithms that use moment.js.

For reference, this is the implied commit: https://github.com/huridocs/uwazi/commit/1d9a0aafb6db8e8f5f52f14689746c5756535bc1

We need to find a way to make both libraries work.
Maybe migrating from moment.js to date-fns (the dependency the date picker has) is an option?
We also need to check if there are any other use cases broken because of the date format.

**Comment by txau** [comment]
@fnocetti I guess it makes sense that we migrate to date-fns. Moment.js is being discontinued anyway.

**Comment by RafaPolit** [comment]
For now, just parse the configuration string, and replace `yyyy` with `YYYY`, and there is probably also `dd` to `DD` or the other way around.  Please check the datepicker PRs.
