### ISSUE TITLE
Create user groups

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#3287]
# User Groups

## Backend

- [x] Create a new db collection `usergroups`
- [x] Initially, store users in usergroups as array of objects with `_id` (this will allow further denormalization if needed)
- [x] Routes (limited to admin) to CRUD usergroups

## Client

- [x] Split the user's settings into tabs: users and groups
- [x] Create basic CRUD for groups
- [x] Adding users requires users lookup, user disable for users already on list, users list should display users alphabetically, we should control the scroll and decide if it scrolls only for users of the sidepanel scrolls fully, leaving the title possibly hidden upon scroll.  It's not a huge deal, just see what makes more sense.

**Comment by RafaPolit** [comment]
@simonfossom Current design for the creation of `user groups` breaks the current pattern of uwazi settings.

## Create Flow

### Current flow:
- There is a center FAB to add a new element (`add thesaurus`, `add template`, `add user`, `add relation types`)
- This button is a pre-action that triggers the flow to add a new element
- Clicking brings you to a new page that configures the new element

### New Flow
- Side panel is always open, there is an `add group` button
- This button is a post-action once you have entered the form input fields
- Clicking it would actually 'save' or 'create' (or 'add) your new group

Since this is already an established pattern with our users, I feel OK with having the `add group` FAB actually open the side panel (instead of going into a new page), but having the same label as the other buttons but making it a `post action` instead of `pre action` seems really confusing for the end user.

@mfacar and I think we should keep the center fab on the list window, leave the `add group` label, and, upon click, open a side panel that has the form, with a `save` (for consistency) or `create` button in the side panel.

## Edit / Delte flow

### Current Flow
- The action buttons are already present on the list view for edit or delete
- Once you click edit, you go into an edit window, and you have a 'save' button to confirm changes or 'cancel' to go back, deleting requires to click the delete and confirm on the list view.  I should note that there is a second 'language' for this operations when editing and deleting entities, which more closely follow your current proposal.

### New Flow
- Clicking the row enters an 'edit' mode which allows editing or deleting the element, much more similar in flow to the entities flow.

We think that replicating the entities flow is a good improvement, also using the side panel instead of the new window is a huge improvement.  Still:
- There is no `save` button on the edit design flow.  Are you expecting name editing and user adding / deleting to have auto-save upon editing?  If so, we believe this is a heavy departure to the usual flow and we should not do it like that until there is system-wide auto save with undo features.  Right now, we would vote for a `save` button on the side panel to confirm and a cancel button to discard, closing the side panel on action, just like we have proposed on the create flow, and mimicking the edit entities flow.
- The Delete button on the side panel is actually a good improvement in our opinion

cc @txau

**Comment by simonfossom** [comment]
@RafaPolit 

Could you please comment in PRD. Thanks
