### ISSUE TITLE
Saving templates gives an illegal_argument_exception as reply

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#3291]
Any time you try to save a template, you get an `illegal_argument_exception` error as a reply.

Changes are, apparently, properly saved.  If you refresh the template data is in, but saving always throws a 400 illegal argument exception error.  No log is recorded on the notifications channel.

**Comment by txau** [comment]
@RafaPolit is that an Elastic exception? Does it happen with any template or just some?

**Comment by daneryl** [comment]
Closing, this issue is infrastructure related.

**Comment by txau** [comment]
@RafaPolit @daneryl I experienced this problem while developing locally, in my case a simple reindex fixed it.
