### ISSUE TITLE
Ensure `yarn emit-types` either on commit, push, or PR

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#3294]
Ensure that `emit-types` is somehow automated.  Right now, it is easily forgettable.

- It can be on preparing the PR (it should happen before the types check)
- It could be a commit hook (perhaps overkill)
- It could be a push hook

Define the best strategy and implement it.

**Comment by daneryl** [comment]
this was solved by adding a check on the PR check list.
