### ISSUE TITLE
Showing multiple entries in CSV as one single entry when uploaded to UWAZI

### ISSUE THREAD

**Issue by lalichaa** [huridocs/uwazi#3300]
I am stuck with this and can't seem to find out a solution. I am using Airtable to build my data and have some fields that have multiple entries (eg. field international crimes sometimes has both genocide + war crimes if the person committed those crimes). I have created thesauri using the same names for crimes. Upon uploading a CVS to my UWAZI instance, those multiple entries are shown as one single entry in my filters, divided with a comma, instead of being shown as multiple entries like they are in the Airtable (eg. international crimes filter has genocide,war crimes as one choice for a person, but it should be genocide + war crimes as two separate choices). I hope this makes sense and could be solved. Thank you!

**Comment by nwyu** [comment]
Hi @lalichaa! From the sounds of it, I think you could be working with Peter. 

To import a column with multiple values into a field with either a multi-select or select property in Uwazi, separate each option by a pipe symbol (e.g. Arbitrary arrest|Illegal search). Please let us know if this works for you!
