### ISSUE TITLE
Inconsistency SEARCH endpoint using API in GreenHost

### ISSUE THREAD

**Issue by gabriel-piles** [huridocs/uwazi#3301]
When the infrastructure was moved to Greenhost, accessing HURIDOCS using the API became inconsistent.

 I'm trying to get entities using the search endpoint with the following parameters:

{'_types': ["TEMPLATE_ID"],
                  'types': '[TEMPLATE_ID]',
                  'unpublished': 'true',
                  'limit': 1,
                  'order': 'desc',
                  'sort': 'creationDate'
                  }

Performing the request 10 times, the result looks like this:

[]
[]
[]
['se8gim501x']
['se8gim501x']
[]
['se8gim501x']
[]
[]
[]

Each time new logging (get connect_sid) is performed.

Worth mentioning that with the same 'connect_sid', the requests are consistent, they are always void or always one result.

**Comment by daneryl** [comment]
this is infrastructure related, closing.
