### ISSUE TITLE
Thesauri values not being displayed

### ISSUE THREAD

**Issue by mylaa** [huridocs/uwazi#3302]
Edited the ''Country'' thesauri list: 
![Screenshot 2020-11-02 at 15 18 49](https://user-images.githubusercontent.com/22371911/97878811-6758da00-1d1f-11eb-93ff-cd682c374cc1.png)

But it's not being updated/reflected when one needs edits entities: 
![Screenshot 2020-11-02 at 15 17 43](https://user-images.githubusercontent.com/22371911/97878995-b141c000-1d1f-11eb-83d5-7f06e84e2115.png)

Is this a bug?

**Comment by txau** [comment]
@mylaa thesauri do not support flags, so I suppose you have both a thesaurus with the countries and entities that you are using in a relationship field (which support flags). So I'm pretty confident you need to add another country entity for Burkina Faso.
