### ISSUE TITLE
object mapping for  [metadata.type_de_document] tried to parse field [type_de_document] as object, but found a concrete value

### ISSUE THREAD

**Issue by vincib** [huridocs/uwazi#3306]
Hi Everyone,

when upgrading from an older uwazi (about 6 month old, I'd say) to 1.10.1, I launches yarn reindex, but got this for a bunch of documents (most documents posted between July and October by the way :/ ) 

Is there a way I could find what's going on ? 

```

uwazi@members:/srv/uwazi/uwazi$ yarn reindex
yarn run v1.22.5
$ node run.js ./database/reindex_elastic.js
Deleting index uwazi_tepo... [done]
Creating index uwazi_tepo... [done]
Tweaking index settings for reindex performance... [done]
Starting reindex...
2020-11-03T15:30:19.362Z [uwazi_development] ERROR! Failed to index documents.
[
 {
  "index": {
   "_index": "uwazi_tepo",
   "_type": "_doc",
   "_id": "5f89bb392a2baf7756af89e5",
   "status": 400,
   "error": {
    "type": "mapper_parsing_exception",
    "reason": "object mapping for [metadata.type_de_document] tried to parse field [type_de_document] as object, but found a concrete value"
   }
  }
 },

```

**Comment by RafaPolit** [comment]
Thanks for the info.

If it is on old Uwazi, you will need to first ensure you have upgraded nodejs and upgraded and migrated Mongo and Elastic to the new required versions.

After that:
- yarn install
- yarn migrate 
And only then;
- yarn reindex


Did you follow all those guides and it gave you that error?

**Comment by vincib** [comment]
Hi Rafapolit, thanks for your help (by the way, its the data.technopolice.fr instance of La Quadrature du Net, indexing the technologies used by police in France and Europe...)

yes it was an old uwazi (but was upgraded today) and I did 

```
uwazi.git$ yarn install 
then "./install.sh ../uwazi/" (which seems to do migrate and reindex through JS scripts)
```
the end of install.sh triggered the error

If I do yarn migrate then yarn reindex, I have the same error at reindex step.

FYI, I just found this in the ES log while doing the reindex : 

```
[2020-11-03T23:57:38,306][INFO ][o.e.c.m.MetaDataMappingService] [members] [uwazi_tepo/TzTD2IAPR4WsUaNbt-gAwQ] update_mapping [_doc]
[2020-11-03T23:57:38,465][DEBUG][o.e.a.b.TransportShardBulkAction] [members] [uwazi_tepo][0] failed to execute bulk item (index) index {[uwazi_tepo][_doc][5f89bbc42a2baf7756af89f0], source[{"documents":[],"title":"2020.10.14 Echanges mails LFP TwoI","user":"5d0feeec7a263d3a72de7155","creationDate":1602862020141,"published":true,"template":"5d544e317a263d3a72deec87","language":"en","sharedId":"rws6kusvwwj","toc":[],"attachments":[],"__v":0,"uploaded":true,"file":{"originalname":"2020.10.14-Echanges_mails_LFP-TwoI.pdf","mimetype":"application/pdf","filename":"16028620207771dbzp7py59t.pdf","size":148249,"language":"fra","timestamp":1602862021026},"processed":true,"totalPages":2,"fullText":"entity","metadata":{"type_de_document_administratif":"i1aubuqgct","date":1602869623,"produit_par":["6w3pzbnbcfg"],"projet_s__li__s_":[],"document_s__li__s_":["rws6kusvwwj","m81ma7gzfui"],"origine_du_document":["fygijsdbjtk"],"sujet_s_":["innnjt9l72c"]}}]}
org.elasticsearch.index.mapper.MapperParsingException: object mapping for [metadata.type_de_document_administratif] tried to parse field [type_de_document_administratif] as object, but found a concrete value
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrNested(DocumentParser.java:377) ~[elasticsearch-7.6.2.jar:7.6.2]

```

**Comment by txau** [comment]
This clearly is a concrete value instead of an object: "type_de_document_administratif":"i1aubuqgct"

@vincib what type of field do you have configured for this property?

**Comment by vincib** [comment]
Here is the description of that field.

![tda](https://user-images.githubusercontent.com/358692/98097206-fcc5ac80-1e8c-11eb-9bd3-09fd88f50389.jpg)

For the record it looks like we have 

- good data for those fields, for files created before we upgraded to v1.6
- bad data for those fields for files created after we upgraded to v1.6 (on August 1st 2020 it seems)
- we upgraded to 1.10.1 two days ago, and had that error for a document uploaded when we where using v1.6, and it seems to crash the reindex process there.

**Comment by vincib** [comment]
ok, I'm using studio3 to explore our mongo database, and we had 2 entries with this value instead of [ "value" ]
I changed them by editing the document ... 
and now the reindex is crashing a bit further...  :) 

a document with "metadata":{"type_de_document":"049lns6mnr28" ... 
crashing on 
org.elasticsearch.index.mapper.MapperParsingException: object mapping for [metadata.type_de_document] tried to parse field [type_de_document] as object, but found a concrete value

then another with : "metadata": { "date":1601510400  
instead of "metadata": { "date": { "value": 1601510400 } 

... Is there a possibility that our mongodb was borked by the v1.6 upgrade? and do you have any idea how we could fix that?

**Comment by txau** [comment]
@vincib I guess a possible approach is to manually fix these malformed data as you are already doing. 

As to why this is happening, it is difficult to say. Data migrations stack one on the top of another so I don't see how it could have happened that some data wasn't migrated. I can imagine that some scenarios were not properly tested on our end since we tend to develop migrations as we go and normally all of our data is only 2 or 3 migrations behind, in your case probably 10 or 15 migrations were applied at once.

Maybe you can attempt to remigrate? On a backup of your db, you can delete entries in the "migrations" collection from migration 16 on (including 16) and run `yarn migrate` followed by `yarn reindex`. I tried removing also previous to 16 but apparently migration 15 wipes out all my relationships for whatever reason.

**Comment by txau** [comment]
Closing (stale)

**Comment by nono-lqdn** [comment]
Hello, I'd like to reopen this issue, as I've took on the work of @vincib at the organisation. I've updated Uwazi, which went well, until as said before, the end of the ./install.sh, when the reindex is going on. Please see the log below :

```
Starting reindex...
2021-12-01T12:41:10.042Z [uwazi_development] ERROR! Failed to index documents.
[
 {
  "index": {
   "_index": "uwazi_tepo",
   "_type": "_doc",
   "_id": "5f89bb392a2baf7756af89e5",
   "status": 400,
   "error": {
    "type": "mapper_parsing_exception",
    "reason": "object mapping for [metadata.type_de_document] tried to parse field [type_de_document] as object, but found a concrete value"
   }
  }
 },
 {
  "index": {
   "_index": "uwazi_tepo",
   "_type": "_doc",
   "_id": "5f89bb392a2baf7756af89e6",
   "status": 400,
   "error": {
    "type": "mapper_parsing_exception",
    "reason": "object mapping for [metadata.type_de_document] tried to parse field [type_de_document] as object, but found a concrete value"
   }
  }
 },
 {
  "index": {
   "_index": "uwazi_tepo",
   "_type": "_doc",
   "_id": "5f89bbc42a2baf7756af89f0",
   "status": 400,
   "error": {
    "type": "mapper_parsing_exception",
    "reason": "object mapping for [metadata.type_de_document_administratif] tried to parse field [null] as object, but found a concrete value"
   }
  }
 },
 {
  "index": {
   "_index": "uwazi_tepo",
   "_type": "_doc",
   "_id": "5f89bbc42a2baf7756af89f1",
   "status": 400,
   "error": {
    "type": "mapper_parsing_exception",
    "reason": "object mapping for [metadata.type_de_document_administratif] tried to parse field [null] as object, but found a concrete value"
   }
  }
 },
 {
  "index": {
   "_index": "uwazi_tepo",
   "_type": "_doc",
   "_id": "5f89bc5f2a2baf7756af8ce2",
   "status": 400,
   "error": {
    "type": "mapper_parsing_exception",
    "reason": "object mapping for [metadata.type_d_acteur] tried to parse field [type_d_acteur] as object, but found a concrete value"
   }
  }
 },
 {
  "index": {
   "_index": "uwazi_tepo",
   "_type": "_doc",
   "_id": "5f89bc5f2a2baf7756af8ce3",
   "status": 400,
   "error": {
    "type": "mapper_parsing_exception",
    "reason": "object mapping for [metadata.nom_complet] tried to parse field [nom_complet] as object, but found a concrete value"
   }
  }
 },
 {
  "index": {
   "_index": "uwazi_tepo",
   "_type": "_doc",
   "_id": "5f89bcef2a2baf7756af8ce9",
   "status": 400,
   "error": {
    "type": "mapper_parsing_exception",
    "reason": "object mapping for [metadata.application_s_] tried to parse field [null] as object, but found a concrete value"
   }
  }
 },
 {
  "index": {
   "_index": "uwazi_tepo",
   "_type": "_doc",
   "_id": "5f89bcef2a2baf7756af8cea",
   "status": 400,
   "error": {
    "type": "mapper_parsing_exception",
    "reason": "object mapping for [metadata.application_s_] tried to parse field [null] as object, but found a concrete value"
   }
  }
 },
 {
  "index": {
   "_index": "uwazi_tepo",
   "_type": "_doc",
   "_id": "5f9d38b67bd6493a840bf1e5",
   "status": 400,
   "error": {
    "type": "mapper_parsing_exception",
    "reason": "object mapping for [metadata.type_de_document_administratif] tried to parse field [type_de_document_administratif] as object, but found a concrete value"
   }
  }
 },
 {
  "index": {
   "_index": "uwazi_tepo",
   "_type": "_doc",
   "_id": "5f9d38b67bd6493a840bf1e6",
   "status": 400,
   "error": {
    "type": "mapper_parsing_exception",
    "reason": "object mapping for [metadata.type_de_document_administratif] tried to parse field [type_de_document_administratif] as object, but found a concrete value"
   }
  }
 }
]


Warning! Errors found during reindex.
Restoring index settings... [done]
Done, took 7.726 seconds
```

**Comment by txau** [comment]
@nono-lqdn I can't really explain what the cause is without having access to the data. Nevertheless, since it is only affecting 6 records and you have the ids right there, I suggest that you connect manually to the database and take a look to the values of these properties, if possible manually fix them.

You can also just delete these values from the DB and add them manually when the reindex has worked out.

**Comment by nono-lqdn** [comment]
>  I suggest that you connect manually to the database and take a look to the values of these properties, if possible manually fix them.

I could indeed. How should I proceed ?

**Comment by txau** [comment]
Roughly:

1. Connect to mongo
2. Run a query of the type `db.getCollection('entities').find({_id: ObjectId('id_goes_here')})`
3. Take a look to the failing properties in the metadata array (metadata.type_de_document, metadata.type_de_document_administratif, metadata.type_d_acteur) etc.
4. Inspect if the structure of the value makes sense. In Uwazi normally you'll find an array of objects, so if the value is coming from a thesauri it would look like `[{label:'Some label', value:'an ID for the thesauri item'}]`

If you have doubts maybe you can share the values here so we can take a look.

**Comment by nono-lqdn** [comment]
Hello,
I have 10 values that fail with the following IDs ;
- 5f9d38b67bd6493a840bf1e6
- 5f9d38b67bd6493a840bf1e5
- 5f89bcef2a2baf7756af8cea
- 5f89bcef2a2baf7756af8ce9
- 5f89bc5f2a2baf7756af8ce3
- 5f89bc5f2a2baf7756af8ce2
- 5f89bbc42a2baf7756af89f1
- 5f89bbc42a2baf7756af89f0
- 5f89bb392a2baf7756af89e6
- 5f89bb392a2baf7756af89e5
I've connected to the mongo DB, and chose to find the first one ; 
`> db.getCollection('entities').find({_id: ObjectId('5f9d38b67bd6493a840bf1e6')})`

It gives me the following ( truncated ) results, in the order listed above ;

>   "reason": "object mapping for [metadata.type_de_document] tried to parse field [type_de_document] as object, but found a concrete value"

```
"metadata" : { 
"type_de_document_administratif" : "adwntncbhed", 
"date" : { 
  "value" : 1598918400 
}, 
```
>     "reason": "object mapping for [metadata.type_de_document] tried to parse field [type_de_document] as object, but found a concrete value"

```
"metadata" : { "type_de_document" : "049lns6mnr28", "date" : { "value" : 1558632889 }, 
```
>     "reason": "object mapping for [metadata.type_de_document_administratif] tried to parse field [null] as object, but found a concrete value"

```
"metadata" : { "type_de_document_administratif" : [ "i1aubuqgct" ], "date" : { "value" : 1602869623 },
```
>     "reason": "object mapping for [metadata.type_de_document_administratif] tried to parse field [null] as object, but found a concrete value"
```
"metadata" : { "type_de_document_administratif" : [ "i1aubuqgct" ], "date" : { "value" : 1602869623 },
```
>     "reason": "object mapping for [metadata.type_d_acteur] tried to parse field [type_d_acteur] as object, but found a concrete value"
```
"metadata" : { "type_d_acteur" : "12fqcbhr5uac",  ...
```
>     "reason": "object mapping for [metadata.nom_complet] tried to parse field [nom_complet] as object, but found a concrete value"
```
"metadata" : { "nom_complet" : "XXX", 
```

>     "reason": "object mapping for [metadata.application_s_] tried to parse field [null] as object, but found a concrete value"
```
"metadata" : { "application_s_" : [ "innnjt9l72c" ], 
```
>     "reason": "object mapping for [metadata.application_s_] tried to parse field [null] as object, but found a concrete value"
```"metadata" : { "application_s_" : [ "innnjt9l72c" ], ```
>     "reason": "object mapping for [metadata.type_de_document_administratif] tried to parse field [type_de_document_administratif] as object, but found a concrete value"
```
 "metadata" : { "type_de_document_administratif" : "adwntncbhed", 
```
>     "reason": "object mapping for [metadata.type_de_document_administratif] tried to parse field [type_de_document_administratif] as object, but found a concrete value"
```
"metadata" : { "type_de_document_administratif" : "adwntncbhed",
```

It seems that the issue is coming from the detection of the type of the field, as explained in this issue : https://github.com/uken/fluent-plugin-elasticsearch/issues/452

> I'm seeing the same error message. From what I can tell, some elements of the log structure are variable (like the various status fields). For instance, responseObject.status can be either an object or a string. From what I understand ES will autodetect type based on what it receives first and then if any of the following documents do not match the schema, it rejects them with a 400.

I'm not fluent in MongoDB, but it seems that the issue is not database corruption, but from ElasticSearch itself, trying to read a field while assuming a wrong datatype ? If so, can I configure it in some way or another ?

**Comment by nono-lqdn** [comment]
I also saw this error I missed earlier, could it have anything to do with the present issue ? Should I open another ticket for it ?

```
2021-12-03T10:44:40.171Z [uwazi_development] uncaughtException: Cannot apply array updates to non-array element description: "Lorem Ipsum ( redacted for privacy ) ...."
MongoError: Cannot apply array updates to non-array element description: "Lorem Ipsum ( redacted for privacy ) ...."
    at Function.create (/srv/uwazi/uwazi/node_modules/mongoose/node_modules/mongodb/lib/core/error.js:57:12)
    at toError (/srv/uwazi/uwazi/node_modules/mongoose/node_modules/mongodb/lib/utils.js:130:22)
    at /srv/uwazi/uwazi/node_modules/mongoose/node_modules/mongodb/lib/operations/common_functions.js:384:39
    at handler (/srv/uwazi/uwazi/node_modules/mongoose/node_modules/mongodb/lib/core/sdam/topology.js:953:24)
    at /srv/uwazi/uwazi/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection_pool.js:350:13
    at handleOperationResult (/srv/uwazi/uwazi/node_modules/mongoose/node_modules/mongodb/lib/core/sdam/server.js:565:5)
    at MessageStream.messageHandler (/srv/uwazi/uwazi/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:281:5)
    at MessageStream.emit (events.js:314:20)
    at processIncomingData (/srv/uwazi/uwazi/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/srv/uwazi/uwazi/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (_stream_writable.js:352:12)
    at MessageStream.Writable.write (_stream_writable.js:303:10)
    at Socket.ondata (_stream_readable.js:713:22)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
[Tenant error] Error: Accessing nonexistent async context
```

**Comment by nono-lqdn** [comment]
> You can also just delete these values from the DB and add them manually when the reindex has worked out.

I could also do this, as it seems easier.

Could you tell me how to delete the values from the DB ? As to adding them back, I can simply re-upload them as done the first time, right ?

Would this work :

`db.test_users.deleteOne( {"_id": ObjectId("5f9d38b67bd6493a840bf1e6")});`

And then, I would re-upload the pdf documents by hand ?

**Comment by txau** [comment]
@nono-lqdn by deleting I meant deleting the failing value, not the whole document. So ie here:
```
"metadata" : { 
"type_de_document_administratif" : "adwntncbhed", 
"date" : { 
  "value" : 1598918400 
}, 
```

The date field is correctly formatted but the type_de_document is not (for whatever reason, a failing data migration or maybe a bug on our end). So if you run this type of query:
```
db.getCollection('entities').updateOne(
    { _id: ObjectId("id_goes_here") }, { $set: {
        'metadata.type_de_document_administratif': []
      } }
);
```
You'll delete the value. Then use Uwazi's UI to enter the value and it will take care of proper formatting.

After fixing them all, run `yarn reindex`

**Comment by RafaPolit** [comment]
Please, feel free to re-open this issue if you need further assistance.

**Comment by nono-lqdn** [comment]
Sorry for the time it takes between updates.

I managed to fix the database by running the commands you told me about, but I now have a new error, which seems to be linked to an incorrect type. I might need to re-run some modifications on objects where I set `metadata.<key>: {}`

The full error log ; 

```
$ yarn migrate
yarn run v1.22.17
$ node --max-http-header-size 20000 scripts/run.js ../app/api/migrations/migrate
default_null_inheritedValue_to_empty_array...
2021-12-16T17:14:53.051Z [uwazi_development] uncaughtException: Cannot apply array updates to non-array element description: {}
MongoError: Cannot apply array updates to non-array element description: {}
    at Function.create (/srv/uwazi.git/node_modules/mongoose/node_modules/mongodb/lib/core/error.js:57:12)
    at toError (/srv/uwazi.git/node_modules/mongoose/node_modules/mongodb/lib/utils.js:130:22)
    at /srv/uwazi.git/node_modules/mongoose/node_modules/mongodb/lib/operations/common_functions.js:384:39
    at handler (/srv/uwazi.git/node_modules/mongoose/node_modules/mongodb/lib/core/sdam/topology.js:953:24)
    at /srv/uwazi.git/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection_pool.js:350:13
    at handleOperationResult (/srv/uwazi.git/node_modules/mongoose/node_modules/mongodb/lib/core/sdam/server.js:565:5)
    at MessageStream.messageHandler (/srv/uwazi.git/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:281:5)
    at MessageStream.emit (events.js:314:20)
    at processIncomingData (/srv/uwazi.git/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/srv/uwazi.git/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (_stream_writable.js:352:12)
    at MessageStream.Writable.write (_stream_writable.js:303:10)
    at Socket.ondata (_stream_readable.js:713:22)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
[Tenant error] Error: Accessing nonexistent async context
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by nono-lqdn** [comment]
> replace any description value of the type "{}" to [{value: 'whatever was there'}].

Could you indicate a simple way to do so if you know who to, please ? :) Thanks
