### ISSUE TITLE
Apparently user deletions are not being logged in the activity log

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#3310]
Research if user deletions is not getting logged in the activity log.

**Comment by grafitto** [comment]
I think I found something. in the `activitylogMiddleware`, for an activity to be logged, the endpoint should not exist in the `IGNORED_ENDPOINTS` array, and also the method should not exist in the `ignoredMethods`. However,  when deleting a user (DELETE /api/users), the method `DELETE` does not exist in the `ignoredMethods` but `/api/users` exists in the `IGNORED_ENDPOINTS`... therefore `!IGNORED_ENDPOINTS.includes(baseurl)` returns `false`

### Proposed solution
```js
function mustBeLogged(baseurl, method, body) {
  const isLoggedRequest =
    baseurl.includes('/api/') &&
    ((!ignoredMethods.includes(method) && !IGNORED_ENDPOINTS.includes(baseurl)) ||
      (baseurl === '/api/users' && method === 'DELETE')); //Add this condition
  const validBody = !BODY_REQUIRED_ENDPOINTS.includes(baseurl) || JSON.stringify(body) !== '{}';
  return isLoggedRequest && validBody;
}
```
