### ISSUE TITLE
Mislabelled items on UI 

### ISSUE THREAD

**Issue by mylaa** [huridocs/uwazi#3312]
- Mislabelled items on the login page (UI).
- Functions work. 
- Occurs on Chrome and Firefox, on 1 instance only. 
- It's a minor issue. 
- Instance URL will be shared privately. 

![Screenshot 2020-11-10 at 10 28 37](https://user-images.githubusercontent.com/22371911/98656029-7acbfc80-2340-11eb-8d04-dc0858bb82f9.png)

**Comment by kjantin** [comment]
I have run into this same problem. Go to the "Translations" section, and "System" and search for these terms and see what is listed in there - the terms may have changed there for some strange reason.

**Comment by nwyu** [comment]
Resolved. Closing this issue.
