### ISSUE TITLE
Exploring solutions for bar chart visualisation

### ISSUE THREAD

**Issue by natasha-todi** [huridocs/uwazi#3318]
Partner has requested for a bar chart for their landing page to render from the template Victim which has a From-To Date Field and captures time of abduction/arrest/disappearance. The time frame is 1945- present and will be ongoing, hence is far too many bars to show in one single graph. Possible solutions are: 

1. Show the information by decade- How would we set this up since their current entities capture the information year wise? - Add a new field with a drop down for decades and do bulk editing to get this information?

2. OR show the ten highest number of victims by year

@RafaPolit @nwyu

**Comment by nwyu** [comment]
This is no longer needed at this time.
