### ISSUE TITLE
Intermediate step: replace PDF highlighting system

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#3336]

**Comment by gabriel-piles** [comment]
1. When a TOC entry is clicked, 
 * No highlight is visible (probably intended)
 * The scroll goes to a different place each time it is clicked (see gif)

![output](https://user-images.githubusercontent.com/22240564/102494536-1570d700-4075-11eb-9559-bbb0db867246.gif)

2. When a text reference takes two pages and it is clicked to show it in the document, it goes to the second page.

**Comment by gabriel-piles** [comment]
@konzz 

The menu to create connections and the table of contents is displayed when users are not logged in!

![Screenshot 2021-01-19 at 11 58 52](https://user-images.githubusercontent.com/22240564/105026531-ec19e100-5a4e-11eb-93e1-dd71496951c0.png)

**Comment by RafaPolit** [comment]
To Do:
- Refine migration to work with edge cases
