### ISSUE TITLE
Import from CSV not working with requiered fields

### ISSUE THREAD

**Issue by sborrajo** [huridocs/uwazi#3337]
- Uwazi 1.14.0
- Node 14.6.0
- Elastic 7.9.3
- Mongo 4.2.9

Importing from CSV files only works if fields are not mandatory. When fields are mandatory the CSV uploads, but no entities are created. Uwazi's log shows:
CREATE USER Imported entities from file
Query | {}
Body | {}

**Comment by RafaPolit** [comment]
Thanks for the report.

Just to be sure: are the mandatory fields included in the CSV? Or are you expecting the CSV import to by-pass the mandatory fields?

**Comment by sborrajo** [comment]
The CSV has the same field structure as the target template. Mandatory fields are not empty or ommited.

**Comment by sborrajo** [comment]
Once the template was erased and recreated, the issue stopped.
