### ISSUE TITLE
Bulk delete leaves indexed entities when they are used in relationships

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#3354]
When bulk deleting a bunch of entities Uwazi is leaving a ghost entry in the ES index despite being deleted in the database. While this is easily fixed with a reindex, it is misleading for users.

Steps
1. In a blank uwazi create template A and template B. Also create a relationship type.
2. In uploads create entity A-1, entity A-2 and entity B-1 (for templates A and B).
3. Edit entity's B-1 relationships and add A-1 and A-2 all in the same hub. Save.
4. Go back to uploads, select all and bulk delete and refresh. One of the A entities will still be in the list.

**Comment by fnocetti** [comment]
This is not longer reproducible.
