### ISSUE TITLE
Cannot access the public library of an instance

### ISSUE THREAD

**Issue by agsabbagh** [huridocs/uwazi#3356]
the public library link  /library/?q=(order:desc,sort:creationDate,treatAs:number) is no longer working, and getting the following result, 
![image](https://user-images.githubusercontent.com/66379177/101238882-5d4a4280-36f4-11eb-844e-9a78a60a1384.png)

any suggestions for a solution?

**Comment by nwyu** [comment]
The public library link on this instance has been fixed.
