### ISSUE TITLE
Error when trying to add a new property on a template with a blank uwazi

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazi#3357]
to replicate.
- setup a blank state uwazi.
- go to settings -> template
- edit Document template
- add Text property
- save

**Comment by grafitto** [comment]
Also Image property behaves the same way.

**Comment by txau** [comment]
I reverted to commit c3f689488232c9e04133b5b030d83ee625c591f9 and the bug is not present. I guess this was introduced with https://github.com/huridocs/uwazi/pull/3284 (cc @konzz )
