### ISSUE TITLE
Orphan inherit property causes app to crash.

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazi#3358]
To replicate:
- Create 3 templates, A, B and C with the following properties.
    - A Text property.
    - B Relationship property to A, inherits Text property.
    - C Relationship property to B, inherits Relationship property.
- Delete Template A.
- B Relationship property gets deleted automatically (this is correct, the related template does not exist anymore)
- C Relationship property still exists and inherits from an nonexistent B relationship property.
- Go to library.
- app crashes.

on this scenario you still can by hand navigate to /settings/templates and delete manually the C Relationship property, this is only if you do not want to maintain the connections between C and B.
it is not possible to send a "blank" inherit property, i think this is desirable to be able to reset the connection inherit property ?

any suggestions on how to solve this ?  what other scenarios we do not know that are similar to this ?
the most obvious solution i guess is dealing with this kind of cascade deletion of properties by automatically reset the inherit property of Template C ?

related #3356

**Comment by txau** [comment]
@daneryl I think cascading the deletion makes sense, but I have some concerns. Does this mean that we are allowing for end-less jumps of inheritance? So in the scenario that you described, if you had a Template D inheriting from C that would still happen?

If that is the case, does that mean as well that our relationships model is cascading updates to these properties? What are the performance implications of that?

**Comment by daneryl** [comment]
@txau i have tested the scenario.
we are not following this kind of relationships endlessly, this means that an inherit property pointing to a relationship will only show the first jump:

template B shows template A text
template C shows a link to template A
template D shows a link to template B

when template A gets deleted, Template D is actually inheriting from an existent property from template C, when this gets fixed (i did it manually by removing the orphan inherit property from C and resaving C) template D relationship property works well and points to B.

**Comment by txau** [comment]
Double checked and the bug is not present anymore, at least as it is described in the issue. Closing for now.
