### ISSUE TITLE
Links in emails use incorrect host if Uwazi is behind a reverse proxy

### ISSUE THREAD

**Issue by duncanka** [huridocs/uwazi#3364]
The recommended way to set up Uwazi to use HTTPS is to put it behind a reverse proxy. However, once it's behind a reverse proxy, the domain and port [inserted](https://github.com/huridocs/uwazi/blob/b4ab90a2034bbc705e4af681888b90b8b660975b/app/api/users/routes.js#L9) into email links are incorrect: they refer to whatever local domain and port the reverse proxy forwards to, rather than the domain and port visible to the external world.

Some possibilities to fix this:

- Adding a string option that just tells Uwazi directly what its externally visible host is.
- Adding a boolean option for whether to fetch the host information from reverse proxy forwarding headers (`X-Forwarded-Host`).

It looks like the `express` module actually supports this last possibility already, but it requires some configuration.

**Comment by daneryl** [comment]
@duncanka im not able to replicate this locally, we also have a reverse proxy on our production environment and working well,
can you maybe share you reverse proxy config to be able to debug this ?

**Comment by duncanka** [comment]
After inspecting the reverse proxy config, I determined that I needed to set the `Host` flag in Nginx:
```
proxy_set_header Host $host;
```
So this issue is now resolved for me. But it might be worth adding a note to the [documentation](https://uwazi.readthedocs.io/en/latest/sysadmin-docs/install.html) that recommends using a reverse proxy to caution that emails will only work properly if the proxy sets the `Host` header.
