### ISSUE TITLE
Cannot edit template, error is "validation failed: .properties[1] should not have additional properties"

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#3375]
I'm trying to edit the "online resource" template in https://doc-resources.uwazi.io. I tried to add a relationship property, but when I try to save the template I get this error message:

![image](https://user-images.githubusercontent.com/354426/102275161-006c3a80-3ef3-11eb-8c57-0d7d9d2b5184.png)

**Comment by kjantin** [comment]
This seems to only be an issue when I try to add a property of type "relationship". :(

**Comment by kjantin** [comment]
Ran into this problem again when trying to add a multi select to the same template:

![image](https://user-images.githubusercontent.com/354426/102277276-0879a980-3ef6-11eb-9aa6-ab2d7c656da5.png)

**Comment by nwyu** [comment]
@kjantin Can you confirm if this has been resolved or whether this is still an open issue? Thanks!

**Comment by kjantin** [comment]
resolved! :)
