### ISSUE TITLE
The ''delete property'' feature is failing

### ISSUE THREAD

**Issue by mylaa** [huridocs/uwazi#3377]
Delete property feature is failing, and throws an error message.
- Select a template 
- Delete any property 
- The property first disappears 
- Click ''Save'' 
- You get an error message
- Refresh the browser, the deleted property reappears
- Seems to be specific to this instance only

![Screenshot 2020-12-16 at 10 00 47](https://user-images.githubusercontent.com/22371911/102327217-b41e0a80-3f85-11eb-899b-fbcebe9d7926.png)

**Comment by konzz** [comment]
Cant replicate probably fixed by #3361

**Comment by tatjana-g** [comment]
Adding to this: After having tried to modify the template (without success), an entry of type 'RAW' is added to the activity log.

This is its description:

" POST: /api/templates/check_mapping
Query | {}
-- | --
Body | {"_id":"5a71e0906d3c7b421ddeb07a","name":"Resolution","commonProperties":[{"_id":"5a71e0906d3c7b421ddeb07c","label":"Title","name":"title","isCommonProperty":true,"type":"text","prioritySorting":true},{"_id":"5a71e0906d3c7b421ddeb07b","label":"Date added","name":"creationDate","isCommonProperty":true,"type":"date","prioritySorting":false}],"properties":[{"nestedProperties":[],"_id":"5a71ef5a3f3f4e437f6f0929","label":"Topic","type":"multiselect","content":"5a71eb3c3f3f4e437f6f0923","showInCard":true,"filter":true,"required":false,"name":"topic","id":"a5b69e63-1626-4ebb-ac2f-d7eb37be14a3","localID":"ytzquaj64e"},{"nestedProperties":[],"_id":"5abb6546810e0f6bcc104eb5","filter":true,"label":"sponsors","type":"relationship","content":"5abb60a1810e0f6bcc104e70","relationType":"5abb64f6810e0f6bcc104ea5","showInCard":false,"name":"sponsors","id":"41bc0e99-def7-431d-9266-72fc6fd55921","inherit":true,"inheritProperty":"5fd332dbffc2523a6083ddce","localID":"52lnu5mvcj"},{"nestedProperties":[],"_id":"5abb6560810e0f6bcc104eb7","id":"c50ac711-ffbf-41b8-8ff2-2f3b664abac0","name":"cosponsors","showInCard":false,"relationType":"5abb650f810e0f6bcc104ea8","content":"5abb60a1810e0f6bcc104e70","type":"relationship","label":"cosponsors","filter":true,"localID":"ak6qyhbv62"},{"nestedProperties":[],"_id":"5fc7b899280a26525d54001f","label":"groupsponsors","type":"relationship","inherit":false,"content":"5fc4f44b45db62177a6dfee5","relationType":"5fc52178e2aa6e1ade17b80d","name":"groupsponsors","id":"a67b4d1e-17fa-4ffe-bd15-f857ac1bf549","showInCard":false,"required":false,"filter":true,"localID":"lp4462ihmc"},{"nestedProperties":[],"_id":"5fc7bd76fb92f21a9dd3f9ee","label":"groupcosponsors","type":"relationship","inherit":false,"content":"5fc4f44b45db62177a6dfee5","relationType":"5fc52185646e4b1a599e3a28","name":"groupcosponsors","id":"e4cec933-6c3b-4520-8614-ab0175bc2eaf","filter":true,"showInCard":false,"localID":"e13lux1k635"},{"nestedProperties":[],"_id":"5abb65a1810e0f6bcc104ebd","label":"favor","type":"relationship","relationType":"5abb651c810e0f6bcc104eab","content":"5abb60a1810e0f6bcc104e70","name":"favor","id":"7b97494d-b384-4b7c-9ad8-0f6e66f53f12","filter":true,"localID":"rby0wnupx4"},{"nestedProperties":[],"_id":"5abb65a1810e0f6bcc104ebc","label":"abstained","type":"relationship","content":"5abb60a1810e0f6bcc104e70","relationType":"5abb6524810e0f6bcc104eae","name":"abstained","id":"60ab67c9-fe3d-47b3-9a4e-475b89c50b29","localID":"3utenpjy72f"},{"nestedProperties":[],"_id":"5abb65a1810e0f6bcc104ebb","label":"against","type":"relationship","content":"5abb60a1810e0f6bcc104e70","relationType":"5abb652b810e0f6bcc104eb1","name":"against","id":"4c8b56c1-c8ee-4893-9393-bb5606af646a","filter":true,"localID":"fsrlpqhonj"},{"nestedProperties":[],"_id":"5fbfbc15f6c98a4641892f41","label":"link","type":"link","name":"link","id":"71e1ee64-469a-4154-baa0-17966a083d41","localID":"odx8n1zkkkq"},{"nestedProperties":[],"_id":"5fc9018edf65c9521bc000e6","label":"date","type":"date","name":"date","id":"f2ad9566-dd5d-45cf-a483-acd1db662531","filter":true,"localID":"v0fe45aksu"},{"nestedProperties":[],"_id":"5fc919c79a4c2a529a820b04","label":"topics","type":"multiselect","content":"5fc0bd24f6c98a4641894364","name":"topics","id":"166296ae-d148-4525-9f1e-0247a25bd256","showInCard":true,"filter":true,"localID":"c9tsnuam7fr"},{"nestedProperties":[],"_id":"5fc91a90df65c9521bc0037d","label":"vote_type","type":"select","content":"5fbfb4bd9ae2bf23fee21f87","name":"vote_type","id":"c92e3130-e0e6-467f-829e-61e4e972d50b","showInCard":true,"filter":false,"localID":"b7sy06e12wi"},{"nestedProperties":[],"_id":"5fcfae3ef179a93a156aace1","label":"regular","type":"select","content":"5fcfae02a1b6de3a3a07fb11","name":"regular","id":"a458bd62-b449-4181-88ff-5d40d4b5d475","localID":"lokwp66nnni"},{"nestedProperties":[],"_id":"5fcfae3ef179a93a156aace2","label":"special","type":"select","content":"5fcfad9fffc2523a6082ac80","name":"special","id":"856b9a56-a7f2-4429-9eb0-66d819f44f9c","localID":"q80ddghiswo"},{"nestedProperties":[],"_id":"5fd0bc820dda5f3a8587e7da","label":"no_amds","type":"numeric","name":"no_amds","id":"e8d68828-d37b-4349-8c47-05d786833b55","localID":"86h4v4ep0z5"},{"nestedProperties":[],"_id":"5fd22df14ba0bd7f3454f9f7","label":"agenda_item","type":"select","content":"5fbfb46f26cd22033b8fea35","name":"agenda_item","id":"809ace64-c2c2-4ce3-87c2-9b532f558af5","localID":"a4h2pv4hn"}],"__v":0,"default":true,"color":"#3F51B5"} "


![image](https://user-images.githubusercontent.com/76156426/102509827-478b3480-4087-11eb-8a83-cbce3648e199.png)
