### ISSUE TITLE
Bulk relationship save grows exponentially

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#3378]
When saving relationships in bulk, the amount of time needed to process the request grows exponentially as we add more relationships to the bulk. This is probably due to a blocking process.

**Comment by txau** [comment]
https://github.com/huridocs/uwazi/issues/2276

**Comment by elreplicante** [comment]
@txau is still this problem happening or can the issue be closed?

**Comment by txau** [comment]
@elreplicante I guess we can close for now but we should write some stress tests to make sure we have this scenario under control.

**Comment by txau** [comment]
A further research revealed issues in relationships.bulk:
```
const saves = await Promise.all(bulkData.save.map(reference => this.save(reference, language)));
```
This promise all will trigger the whole process for each entity in the hub.

Later on:
```
if (updateEntities) {
      const touchedHubs = Array.from(new Set(relationships.map(r => r.hub)));
      for (let i = 0; i < touchedHubs.length; i += 1) {
        // eslint-disable-next-line no-await-in-loop
        await this.updateEntitiesMetadataByHub(touchedHubs[i], language);
      }
    }
    return result;
```
Despite declaring a "Set" to process hubs only once, since this is isolated as part of the previous promise.all, it will always contain 1 hub that gets processed multiple times (once per entity in the hub).

Then on
```
async updateEntitiesMetadataByHub(hubId, language) {
    const pepe = Math.random();
    const hub = await this.getHub(hubId);
    const entitiesIds = hub.map(r => r.entity);
    const res = entities.updateMetdataFromRelationships(entitiesIds, language);
    return res;
  },
```
The call to getHub is somewhat expensive (50ms) and get repeated over and over again per each entity in the hub. It grows as there are more entities in the hub.

As a result a call to relationships.bulk with around 10 entities in the hub, even if these entities have no relationships or inheritance can take up to 3 or 4 seconds.

**Comment by txau** [comment]
Related/same: https://github.com/huridocs/uwazi/issues/3994

**Comment by LaszloKecskes** [comment]
Note: the exact same thing happens one line later in the deletions. The implementation is slightly different, but the effect is the same; processing all entities in the hubs for each entity. We will fix that as well.
