### ISSUE TITLE
Links to entities should open side panel instead of navigating to entity

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#3380]
Currently when clicking on any text link pointing to an entity we are directly navigating to that entity. This has proven to be less desirable than opening the entity on the side panel and then, let the user decide whether they want to actually navigate to that entity.

**Comment by konzz** [comment]
I'm not sure this is still happening. Right now when you click in any part of the relationship it opens on the side panel, and only if you click in the view button it navigates. This behaviour is the same as in the library.

<img width="478" alt="Screenshot 2021-05-13 at 10 02 17" src="https://user-images.githubusercontent.com/948117/118097303-cc7a4000-b3d2-11eb-90ba-91c6e22a8ccf.png">

**Comment by txau** [comment]
I mean these links

![image](https://user-images.githubusercontent.com/489831/118139607-c2e9db80-b3c4-11eb-8661-dd019a029ea9.png)

**Comment by txau** [comment]
Related/same: https://github.com/huridocs/uwazi/issues/4242
