### ISSUE TITLE
Activate permissions

### ISSUE THREAD

**Issue by fnocetti** [huridocs/uwazi#3383]
Obvious places where permissions should have effect are:
- [x] Search
   - [x] Elastic search by permissions
- [x] Permissions on entities CRUD (mongo + UI)
   - [x] Create entities
   - [x] Delete entities 
   - [x] Inherited properties
   - [x] Validation of relationships metadata
   - [x] Multiple edition of entities
   - [x] View entities connections
- [x] Add unit tests to cover the permissions scenarios
- [x] Add e2e tests to cover the permissions scenarios
- ~~[ ] Create index in mongo for permissions property~~  //should be implemented until have public feature 
- [x] Fix lose of context error 
- [x] Generate a list of all endpoints/routes on the app and check their access-levels needs.
- [x] Show/hide action buttons based on permissions
- [x] Add table and cards indicators as per design.
- [x] Allow no logged user create entities from public form

**Comment by RafaPolit** [comment]
Check the multitenant implementation as an example of how to pass variables to the entire application.

**Comment by RafaPolit** [comment]
Gross estimate: 40pts

**Comment by mfacar** [comment]
List of affected endpoints:

**method** | **endpoint** | **bypass**
-- | -- | --
delete | /api/documents |  
post | /api/entities | unrestricted
get | /api/entities |  
delete | /api/entities |  
post | /api/entities/multipleupdate |  
post | /api/files |  
get | /api/references/by_document/ | unrestricted
post | /api/relationships/bulk |  
get | /api/thesauris | unrestricted
get | /api/references/by_document/ | unrestricted

**Comment by nwyu** [comment]
The feature has been merged into the parent branch access-levels.
