### ISSUE TITLE
Remove uploads section

### ISSUE THREAD

**Issue by fnocetti** [huridocs/uwazi#3384]
- [x] Design public permissions
- [ ] Remove uploads section
- [x] Add indicators on cards and table as per designs

**Comment by nwyu** [comment]
Relates to #3492.

**Comment by fnocetti** [comment]
@nwyu @konzz here is a brief definition of the "Remove uploads sections" that can be used as description for the singular issue/story. Hope this clarifies a bit. cc @RafaPolit 

There are currently two sections in Uwazi to see either published or not published entities. They are called "Public documents" (formerly "Library") and "Private documents" (formerly "Uploads").
With the implementation of the user access levels, or entity sharing, now private/public is not the only criteria to discern the visibility of an entity. For that reason we want to get rid of the private documents section in pro of a unified documents view (another way to think about this is "merging" the views).
Currently, the Public Documents view allows the user to include unpublished documents as a filter. This is a good approximation of what we intend to do.
As a side effect, the buttons on the top right corner of the screen for Public and Private documents are meant to disappear, leaving only the Settings/Log in button.
Also, currently the private documents view is the place where users are able to upload documents, create entities or import csv files. This actions need to be moved to the unified view.
Still there might be diverging thoughts in the team on how to approach this and what's the intended outcome, so we need to review this.

**Comment by simonfossom** [comment]
There relevant screen:
![Collection view](https://user-images.githubusercontent.com/8134850/114054515-395c6080-9890-11eb-8253-8c1f6741d4a3.png)

([Link to the screen in design of Access Levels](https://www.figma.com/file/2AT2ilGWBTe0pWy4j66yxW/Uwazi-Access-Levels?node-id=790%3A1821))

**Comment by nwyu** [comment]
This is being closed in favor of #3704 and #3705.
