### ISSUE TITLE
something causes elastic error on search.

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazi#3394]
we need to debug what is causing a state where elasticsearch responds with ```search_phase_execution_exception```

**Comment by daneryl** [comment]
to replicate:

- yarn blank-state
- add text property to default template
- create an entity with a value on the created entity
- update the default template and change the name of the property
- an error appears and from that point on the search also throws an error

still do not know the cause.

**Comment by daneryl** [comment]
here is what causes the bug, this is the template save flow endpoint:
https://github.com/huridocs/uwazi/blob/c73ad7e010c61ae140b1a7b7ea7f26f512affc1c/app/api/templates/routes.js#L14-L42

- line 19 saves the template
     - property name change modifies all the template entities.
     - this produces a reindex which generates a dynamic mapping.
- line 35 updates the mapping, which produces the following error because the mapping already exists with another type.
```
"root_cause": [
              {
                "type": "illegal_argument_exception",
                "reason": "Mapper for [metadata.wtfs.value] conflicts with existing mapping:\n[mapper [metadata.wtfs.value] has different [index] values, mapper [metadata.wtfs.value] has different [index_options] values, mapper [metadata.wtfs.value] has different [store_term_vector] values, mapper [metadata.wtfs.value] has different [store_term_vector_offsets] values, mapper [metadata.wtfs.value] has different [store_term_vector_positions] values, mapper [metadata.wtfs.value] has different [analyzer]]"
              }
            ],
```

the main reason this is like in my opinion is because its not properly tested, tests are mocking the call to updateMapping on line 35, also the tests do not take into account a template update for this, only creation. a proper test would have found this bug during development probably.

On a side note, ```tenants.current()``` its supposed to be low level api only to use in certain I/O abstractions, for the elasticsearch one im working on a refactor that will encapsulate this here #3391

**Comment by fnocetti** [comment]
After debugging this and talking with Joan, it looks like we probably need to update the mapping before the reindex. Assigning to Konz for further review.
