### ISSUE TITLE
Long titles get two lines on header

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#341]
![screenshot 2016-08-23 16 11 04](https://cloud.githubusercontent.com/assets/6364153/17895115/4b4c92ce-694c-11e6-979d-ef552661d7b3.png)

@txau This is solved in #180. We need to deploy the last changes in their environment.

These are some tests on our dev environment:

![screenshot 2016-08-23 16 08 53](https://cloud.githubusercontent.com/assets/6364153/17895113/4b273eb6-694c-11e6-87c2-dc2586b08363.png)
![screenshot 2016-08-23 16 10 54](https://cloud.githubusercontent.com/assets/6364153/17895114/4b4415f4-694c-11e6-9cf4-c7a4fcc5da52.png)

**Comment by txau** [comment]
@danicatalan cool! We could actually improve this a little bit by having a solution for mobile. Now is blank:

![screen shot 2016-08-23 at 16 18 12](https://cloud.githubusercontent.com/assets/489831/17895404/4ca238ee-694d-11e6-8107-f1318f380c16.png)

What about a smaller font version in two lines?

**Comment by danicatalan** [comment]
This need a little bit of work, because I need to create some rules for buttons and objects to keep the collection title at the proper size and get the two lines, but it could be a good idea.

Do you want me to perform it or maybe we can set this on `next`?

**Comment by txau** [comment]
@danicatalan also this:

![screen shot 2016-08-23 at 16 44 30](https://cloud.githubusercontent.com/assets/489831/17896441/f4ea5150-6950-11e6-91b5-c7b5a5529da5.png)

Yeah, since the main problem is solved, this can wait.

**Comment by danicatalan** [comment]
We should use this approach for that case: http://stackoverflow.com/questions/15292708/text-overflow-css-truncation

**Comment by danicatalan** [comment]
This is fixed on #396:

![screenshot 2016-09-08 16 58 29](https://cloud.githubusercontent.com/assets/6364153/18354867/771d24de-75e7-11e6-9277-68cd7846f12b.png)
![screenshot 2016-09-08 17 12 31](https://cloud.githubusercontent.com/assets/6364153/18354866/77179e06-75e7-11e6-88da-238c75421b54.png)
