### ISSUE TITLE
"RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by mylaa** [huridocs/uwazi#3439]
This is not a bug, but the https://right-docs.uwazi.io/en/ instance is super slow to load.

Jaume mentioned that something is wrong with the instance since it is giving this kind of error: "RangeError: Maximum call stack size exceeded".

**Comment by daneryl** [comment]
@mylaa @txau did not replicate the error described here.
i have created another issue probably related that describes why the performance is bad and possible solutions -> #3444

**Comment by mylaa** [comment]
Thanks @daneryl, closing this issue and will follow the developments at #3444
