### ISSUE TITLE
Property displayed twice 

### ISSUE THREAD

**Issue by mylaa** [huridocs/uwazi#3442]
Sometimes, when in the Map view one of the properties, called ''main sponsor'', is being displayed twice.

Go to: https://right-docs.uwazi.io/en/

1. Select the following filters: Amendment, and Regular Session 30 - September 2015
2. You'll have 10 entities.
3. Click on the entity ''A/HRC/30/L.38: Amendment to draft resolution A/HRC/30/L.25''
4. Property Main Sponsor is displayed twice. 
5. In the same search, select the entity: A/HRC/30/L.39: Amendment to draft resolution A/HRC/30/L.25
6. Another example: A/HRC/30/L.40: Amendment to draft resolution A/HRC/30/L.25
7. Also: A/HRC/30/L.41: Amendment to draft resolution A/HRC/30/L.25
8. A/HRC/30/L.42: Amendment to draft resolution A/HRC/30/L.25
9. A/HRC/30/L.35: Amendment to draft resolution A/HRC/30/L.11/Rev.1
10. A/HRC/30/L.36: Amendment to draft resolution A/HRC/30/L.11/Rev.1

The issue is not consistent. However, 7 out of 10 entities in this search have the issue of displaying the ''main sponsor'' property twice.

**Comment by txau** [comment]
Fixed in another PR.
