### ISSUE TITLE
very slow instances with high numbers of inherited geolocation markers.

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazi#3444]
this method is the main bottleneck combined with multiple calls.
https://github.com/huridocs/uwazi/blob/ddf7db71ee062f4f86126ad3d45b2495ae9d3c15/app/react/Map/helper.js#L135-L143

the dataset used to test is around 1500 entities with multiple inherited geolocation markers, the final collection is around 66k markers.
the getMarkers function takes around 0.5 to 1 seconds to complete, but even worse, the function is being called multiple times when performing an action on the app, for instance performing a sort, calls this function 7 times, for a total of almost 5 to 7 seconds where the browser is frozen.

all this is happening on library view, which  again, should not be needed at all (just to show the +99 badge on the top right), but this is a different issue, when you navigate to the map this will still happen, and will also include the rendering of the markers which will make the whole thing slower, in my machine the app crashes.

this is a suggested list of changes to improve this:

1.  (#3466) make the getMarkers function faster, probably there is other reasons why is slow but these are the obvious ones.
       - there is abusive and repeated usage of .toJS inside
       - there is repeated calls to .find also
2. (#3466) the multiple calls seems to be because of not needed re-renders, ideally the function gets called only once.

## TODO
- this case is weird, from the 66k final markers only 249 are unique. maybe we should think about making some kind of clustering on server-side to improve performance of data transmitted and rendering speed.

- After another look we found that the actual request for the markers its also very slow, around 10 seconds on my machine !

**Comment by txau** [comment]
@daneryl regarding point 3, it makes sense to do better handling of geopoint clustering. Elastic supports that kind of query: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-geohashgrid-aggregation.html

But it also means that we probably need to synchronize zoom level in client side to the precision of the query.

**Comment by txau** [comment]
Related: https://github.com/huridocs/uwazi/issues/2402

**Comment by RafaPolit** [comment]
Estimate for points 1 and 2: 8pts

**Comment by mylaa** [comment]
@daneryl I know the root cause of this slow performance is the inherited geolocation. We are considering to completely remove it from this instance, because the map view is not a mandatory thing, nor it is super helpful for this project. 
Removing the inherited geolocations may improve the performance of this instance. 
I'll update you when it's done. 
Of course, this does not mean that the issue will not recur in other similar use cases.

**Comment by daneryl** [comment]
All missing issues are being tracked on their own issue.
