### ISSUE TITLE
toc auto generated integration

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazi#3447]
~~receives tenant and task (toc generation)
calls external toc generation external service (http)
blocks specified task until its finished, the same task for the same tenant can not be run at the same time. (task should be blocked in a shared resource to support uwazi multiprocess architectures)
on toc generated, it does save the toc on the file and sets a "Machine Generated" flag
reindex related file entity with the machine generated flag to be able to aggregate and filter
add number of page on the toc UI
do not change size of the toc sidepanel (will be a separate development)
do not implement the next/prev UI to see a selection of entities (will be a separate development)~~

**Comment by daneryl** [comment]
change of scope to simplify.
we decided that the endpoint to trigger jobs its not the best solution and we do not want to spend too much time on the "cronjob" side of things yet, we are going to use the same approach we are using now, this will basically work like the vault and sync jobs, it works on a single process setup, for our production infrastructure it will work exactly the same, an uwazi instance for each specific tenant that runs "jobs"

**Comment by RafaPolit** [comment]
Gross estimate 40pts
