### ISSUE TITLE
Unable to change property name and type

### ISSUE THREAD

**Issue by mylaa** [huridocs/uwazi#3449]
On the https://right-docs.uwazi.io/ instance

- login, select the template ''Resolution''
- edit the Label of any property
- click save
- the system thrown an error _''An error has occurred''_ 
- similarly, select any property
- change its type, i.e. mark or unmark as ''use as filter'', ''show in the cards''
- click save
- the system thrown an error _''An error has occurred''_

**Comment by konzz** [comment]
Fixed by #3454
