### ISSUE TITLE
New user can't login

### ISSUE THREAD

**Issue by tlacoyodefrijol** [huridocs/uwazi#3450]
I'm trying to create a new user in a self hosted Uwazi instance. When the user is created created I get a message that says created successfully (see attachment)
![Screenshot 2021-01-26 at 14 22 46](https://user-images.githubusercontent.com/5587545/105900762-1f75e600-5fe2-11eb-9cc6-56afe9be3c7b.png)
Trying to log in, I get a Login failed message
![Screenshot 2021-01-26 at 14 24 44](https://user-images.githubusercontent.com/5587545/105900964-5cda7380-5fe2-11eb-915e-5cacd907625f.png)
Eventually, account is locked but I don't get an email to unlock
![Screenshot 2021-01-26 at 14 25 02](https://user-images.githubusercontent.com/5587545/105901036-6bc12600-5fe2-11eb-8d54-7e7201a127d6.png)
 Activity log shows the user is created, password is hashed. Working accounts had unhased passwords when user was created. 
![Screenshot 2021-01-26 at 14 27 53](https://user-images.githubusercontent.com/5587545/105901283-c2c6fb00-5fe2-11eb-9a3f-58f307e10a44.png)

**Comment by txau** [comment]
@tlacoyodefrijol if you are not receiving the e-mail probably the sendmail is miss configured. 

Which version of Uwazi are you using? There was a similar bug that got patched in 1.20: https://github.com/huridocs/uwazi/issues/3209

**Comment by tlacoyodefrijol** [comment]
Thanks @txau! I can't remember which version it is, but definitely not 1.20. I guess we'll have to update and see how it goes.

**Comment by txau** [comment]
@tlacoyodefrijol np! let me know if you need further support.
