### ISSUE TITLE
Malformed query triggers a 500 for the load more button

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#3460]
Sending an arbitrary malformed query string triggers and error in the load more button component, probably due to lack of validation before destructuring the param.

ie: server.com/library/?q=something

```
2021-02-05T14:43:44.614Z [server] 
url: /en/library/?q=something
query: {
 "q": "something"
}
TypeError: Cannot create property 'from' on string 'something'
    at DocumentsList.loadMoreButton (/opt/uwazi/cores/core-1.22.0/app/react/Layout/DocumentsList.js:58:5)
    at /opt/uwazi/cores/core-1.22.0/app/react/Layout/DocumentsList.js:179:18
    at DocumentsList.render (/opt/uwazi/cores/core-1.22.0/app/react/Layout/DocumentsList.js:172:7)
```

**Comment by MeerHamza1421** [comment]
can you explain this issue a bit more

**Comment by txau** [comment]
I haven't looked into the code but from this error message `TypeError: Cannot create property 'from' on string 'something'` I imagine the "load more" button, which controls the pagination of results expect the GET param "from" to exist in the query string.

The code for this button should be resilient to the absence of these params. Also to these params not being numeric or being in wrong ranges.

**Comment by daneryl** [comment]
important to clean because the errors are being logged in the error log.

**Comment by fnocetti** [comment]
This is returning a 400 right now. Is it good enough for it not to be shown in the logs? Do we want to go a step further and implement proper validations so only rison queries are allowed in the q param? @txau @daneryl

**Comment by txau** [comment]
@fnocetti a 400 is ok, I don't think we need logging for it. I do think though that we should implement validation for the query strings at some point. These params are commonly being used and abused for attempts of injection by hackers/scanners, etc. It is not big deal but they can generate quite some unneeded server load.

Closing for now
