### ISSUE TITLE
Request from partner to be able to remove CSV export button if needed 

### ISSUE THREAD

**Issue by natasha-todi** [huridocs/uwazi#3462]
As discussed in the coordination call some possible action items are: 

- Having a captcha on the csv export function to prevent our servers from crashing. 
- The csv export option could be a feature toggled from admin's settings. 
- Only allow logged in users to export csv files

**Comment by txau** [comment]
I think all these options should be implemented.
- Logged out user always are required to fill in a captcha for CSV export.
- Admins can totally disable CSV export for logged out users via settings.

**Comment by nwyu** [comment]
Related issue: [Add captcha to CSV export #3453](https://github.com/huridocs/uwazi/issues/3453)

**Comment by txau** [comment]
@RafaPolit Quick and dirty: let's add a CSS class to the CSV export button so they can easily hide it via CSS.

**Comment by nwyu** [comment]
Fixed in #3582.
