### ISSUE TITLE
Lock entity/doc type after creation

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#347]
Changing the type of an entity or document after saving it may cascade into unforeseen errors. Ie. An entity is being used as a foreign key in a property in a document, based in a dictionary, thus changing the property type is changing the dictionary it belongs to.

In order to avoid these and other complications, we should lock the type after first save.

**Comment by RafaPolit** [comment]
Not a wanted behavior, but we need to address the cascade effect it will produce.
