### ISSUE TITLE
Button overlaping on content in settings menu (mobile)

### ISSUE THREAD

**Issue by Zasa-san** [huridocs/uwazi#3470]
The issue shown in the image seems to happen only in the thesauri page. This happened in Firefox and Chrome. 

![image](https://user-images.githubusercontent.com/71732018/107558420-81754480-6bb9-11eb-80b6-a17f44fa48d6.png)

**Comment by nwyu** [comment]
With the new action buttons coming into Uwazi (#4852) that will replace the floating action buttons, this will no longer be a problem.

![new-action-button](https://user-images.githubusercontent.com/56067374/187232187-6b041308-be69-4db6-9697-55caedb55d6f.png)
