### ISSUE TITLE
Server crash on null value (8 pts)

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#3472]
Sending a "null" value as a relationship value causes a server crash:
```
TypeError: value.map is not a function
    at validateRelationshipForeignIds (/home/txau/work/uwazi/app/shared/types/validateMetadataField.ts:99:28)
    at validateMetadataField (/home/txau/work/uwazi/app/shared/types/validateMetadataField.ts:144:13)
```
The code expects `[{value: 'something'}] but just `null`was sent.
We should make sure that the schema is validated before any other validation.

**Comment by daneryl** [comment]
the error was produced when sending a string as a metadata property not a null, value, #3718 fixes this and other potential similar errors by always validating the entity schema first, and if its valid then validating the data.
