### ISSUE TITLE
Certain entities cannot be edited

### ISSUE THREAD

**Issue by tatjana-g** [huridocs/uwazi#3474]
In one of the instances, some country entities cannot be edited.

1. Filter for 'Countries'
2. Select 'Uruguay': A generic error message will show ("An error has occured")
3. Click 'Edit': The same error message shows and editing is not possible

This error occurs only for some of the countries. It has not been observed with any other document type. 
All countries have geolocations and most are connected with other entities via relationships.

**Comment by daneryl** [comment]
probably this is due to vast amount of relationships in the entities, this triggers the JS error 
```
RangeError: Maximum call stack size exceeded
    at new RelationshipCollection (/opt/uwazi/cores/core-1.32.0/app/api/relationships/relationshipsHelpers.js:116:1)
    at /opt/uwazi/cores/core-1.32.0/app/api/relationships/relationships.js:185:39
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
original error: {}
```
