### ISSUE TITLE
Translation blocked data import?

### ISSUE THREAD

**Issue by tlacoyodefrijol** [huridocs/uwazi#3475]
We are uploading data to our self-hosted Uwazi instance. Just updated to 1.23.0
Steps taken were:
- We uploaded four out of the 5 templates. 
- As the fourth was indexing, we added some translations to Spanish
- We then tried to upload the final CSV for the main template, to build relationships. 
- Uwazi shows as uploading, gets to 100% but nothing happens. 

Tried reindexing and restarting Elastic. Nothing changes. Log shows upload happened. 
Could it be possible the translation broke something that doesn't allow the final template to register the upload?

**Comment by daneryl** [comment]
@tlacoyodefrijol what is the status on this? did you manage to solve it ? sorry for the super late reply. please reopen if you still need support.
