### ISSUE TITLE
Node process crashing when server started

### ISSUE THREAD

**Issue by tlacoyodefrijol** [huridocs/uwazi#3481]
Just did a fresh reinstall of self hosted Uwazi. All from scratch, just imported nginx configs. No errors during install. I started the server and got this error. 

root@uwazi:~/uwazi# node server.js
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
==> Connecting to mongodb://localhost/
==> 🌎 Listening on port 3000. Open up http://localhost:3000/ in your browser.
2021-02-23T14:47:15.855Z [localhost] 
uncaught exception or unhandled rejection, Node process finished !!
 Error: Error: ENOENT: no such file or directory, open '/root/uwazi/app/react/../../dist/webpack-assets.json'
webpack-assets.json do not exists or is malformed !,
                          you probably need to build webpack with the production configuration
    at ReadFileContext.callback (/root/uwazi/app/react/ServerRouter.js:306:11)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:264:13)
    at FSReqCallback.callbackTrampoline (internal/async_hooks.js:129:14)
original error: {}

**Comment by RafaPolit** [comment]
Thanks for the report.

It looks like you are missing the webpack build process.  Did you run the `./install.sh` as described on point 6 of the README?

**Comment by tlacoyodefrijol** [comment]
I did. Just reran the script, just in case. Same error as before.

**Comment by tlacoyodefrijol** [comment]
Getting a different error emulating everything in a local instance. This happens even before being able to run the node server. 

(base) ➜  uwazi yarn blank-state
yarn run v1.22.10
$ ./database/blank_state.sh


Deleting uwazi_development database on 127.0.0.1
./database/blank_state.sh: line 12: mongo: command not found
./database/blank_state.sh: line 13: mongorestore: command not found
$ node --max-http-header-size 20000 run.js ./app/api/migrations/migrate
Sanitizing connections...
2021-02-23T17:03:02.868Z [uwazi_development] uncaughtException: Cannot destructure property 'languages' of 'settings' as it is null.
TypeError: Cannot destructure property 'languages' of 'settings' as it is null.
    at Object.up (/Users/oscar.montiel/Documents/uwazi/app/api/migrations/migrations/6-connections_sanitizing/index.js:14:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /Users/oscar.montiel/Documents/uwazi/app/api/migrations/migrate.ts:26:5
    at run (/Users/oscar.montiel/Documents/uwazi/app/api/migrations/migrate.ts:25:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
$ node --max-http-header-size 20000 run.js ./database/reindex_elastic.js
Deleting index uwazi_development... [done]
Creating index uwazi_development...
 - Base properties mapping
 - Custom templates mapping
 [done]
Tweaking index settings for reindex performance... [done]
Starting reindex...
Indexing documents and entities... - 0 indexed
Restoring index settings... [done]
Done, took 1.793 seconds
✨  Done in 10.36s.

**Comment by RafaPolit** [comment]
`mongo command not found` suggests that you don't have mongoDB installed.  Or at least the executable binaries.  Please, ensure that you have all the required dependencies and at the required versions that are listed in the README.
