### ISSUE TITLE
Remove "no-type" option from uploads

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#3483]
Since we introduced the default template there is no possibility of not having a type, so this feature is obsolete.
![image](https://user-images.githubusercontent.com/489831/109014072-6a365c80-7679-11eb-99ce-2fd34478a42c.png)

**Comment by Aishu21** [comment]
Can I work on this issue ?

**Comment by txau** [comment]
@Aishu21 absolutely =)

**Comment by Aishu21** [comment]
Hi,

I am not able to build code in windows.
Facing many installation problems.
You can assign it to someone else.
Apologies for the same.

**Comment by txau** [comment]
@Aishu21 that is ok, thanks for giving it a try. Just in case you want to try something else, when developing on windows, our team uses linux virtual machines.

**Comment by daneryl** [comment]
This is already fixed since now uploads are integrated into library.
