### ISSUE TITLE
Issue in naming entites and categories

### ISSUE THREAD

**Issue by N07070** [huridocs/uwazi#3484]
Hello,

While using Uwazi, we have seen issues with naming of entities that don't update after being renamed.

For example, in the back-end, we can class project per application or goal, or by priority 

![image](https://user-images.githubusercontent.com/2259999/109310975-7d962300-7845-11eb-8ad0-cae4a14903a5.png)

In the front-end, we can see that each is called Domaines. It was the name of the fields originally, but has been changed since then.

![image](https://user-images.githubusercontent.com/2259999/109311111-ab7b6780-7845-11eb-94a9-2e841602ac13.png)

How could be resolve theses issues ?

**Comment by konzz** [comment]
Hi, do you have more than one language in your Uwazi ? is this happening in the default language also?

**Comment by daneryl** [comment]
@N07070 property names do not sync with translations, if you want to display a different label you can translate it using the translations UI settings -> translations -> {{template to translate}}.
reopen if this is still an issue.
