### ISSUE TITLE
Translations of nested thesauri are not translated in filters agregations (4pts)

### ISSUE THREAD

**Issue by MatelSow** [huridocs/uwazi#3487]
Instances where all translations have been provided in the settings are displaying 'original' language of data entry in the nested thesauri and not the current UI language. This is only happening in the side panel aggregation and not on the full entity view.

Only the group name of the dictionary is shown in the current language.
<img width="387" alt="Screenshot 2021-03-02 at 19 26 26" src="https://user-images.githubusercontent.com/948117/109696493-67fa6380-7b8d-11eb-9179-ed79ad20134f.png">

**Comment by MatelSow** [comment]
Thanks @konzz - do you have an idea of the timeline for completion? The partner is asking. Thank you!

**Comment by konzz** [comment]
@MatelSow it will probably go in to next sprint.
