### ISSUE TITLE
Connected text in OCRed documents becomes opaque

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#349]
OCRed documents have a background image and a layer of invisible text on the top of it. This layer allows for text selection, copy, paste, etc.

Our current CSS style for highlighted text has no transparency thus the text is no longer readable.

![screen shot 2016-08-25 at 17 06 54](https://cloud.githubusercontent.com/assets/489831/17985858/1ccd9542-6b18-11e6-88b3-eb406e975ffd.png)

**Comment by YolandaCHR** [comment]
@txau Thanks for pointing this bug out - I was wondering about the 0% transparency

**Comment by danicatalan** [comment]
Fixed. I just changed opacity 100% with opacity 80% and looks great on both image and text selection.

![screenshot 2016-08-29 17 33 16](https://cloud.githubusercontent.com/assets/6364153/18057247/6a33d522-6e0f-11e6-999d-6612170f7bf0.png)

**Comment by txau** [comment]
@danicatalan I this could do for now. Although the underlying text is not that sharply visible... what about a 70%?

**Comment by danicatalan** [comment]
There is not a big improvement here. This will always depend on the original font color. The higher the contrast between font and background, the better it will be.

![screenshot 2016-08-29 18 40 21](https://cloud.githubusercontent.com/assets/6364153/18059204/2d45c0fe-6e18-11e6-8a8f-72e4ead7e026.png)

**Comment by txau** [comment]
@danicatalan ok.

I hope @YolandaCHR likes it =)

**Comment by txau** [comment]
Fixed in #372
