### ISSUE TITLE
Filter agregate entities I have explicit permissions to see and edit (17pts)

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#3491]
Create filters to filter entities that I have explicit permissions to see and edit.

- React component for the filters, probably outside of the component that generates the filters based on a template
- Search endpoint been able to understand the filter and generate the appropriate aggregations based on the user or the groups the user belongs to. (ask Joan about recently developed similar feature)

Allow users to isolate entities they have been shared with / created by them from either public entities (for collaborators) or all entities (for admins and entities)

Designs:
https://www.figma.com/file/2AT2ilGWBTe0pWy4j66yxW/Uwazi-Access-Levels?node-id=509%3A6
<img width="244" alt="Screenshot 2021-03-02 at 18 08 40" src="https://user-images.githubusercontent.com/948117/109686243-637c7d80-7b82-11eb-80cc-6b53a1338c49.png">

**Comment by konzz** [comment]
@daneryl this issues should be close right?

**Comment by Zasa-san** [comment]
The feature has been merged into the parent branch access-levels.
