### ISSUE TITLE
Image and Media Field revamp (30pts)

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#3494]
The Image and Media field should use the new modal implemented for attachments (aka Supporting files).
When opening the modal you should have a list of the attachments of the entity that can go in to that field, selecting and accepting would update the field with the attachment information:
`{value: ['idOfTheFile']}`
 
<img width="266" alt="Screenshot 2021-03-03 at 11 25 52" src="https://user-images.githubusercontent.com/948117/109791945-4a6fdd00-7c13-11eb-93c8-ba61092fba12.png">

This list of supporting files should only show attachments that can be in the image or media field respectively.
 
This task will involve:
- Update the image / media fields to have a button as in the designs and open a modal with the attachments.
- Update the metadata fomater to render the image based in the File _id and confirming the url with the attachments that are in the enitity.
- Update CSV import to create entities with the file _id in the image fields instead of the url
- Update Vault sync to create entities with the file _id in the image fields instead of the url
- Create a migration for all existing image / media fields. The migration should take in to account when the url of the image points to an image in of the entity, or an external image, if its an external image, an "external attachment" should be created and asociated with the field. If its internal image the Attachment should already exists and only needs to be associated via _id. 

Designs:
https://www.figma.com/file/xjsz7r65epN4B0b96zilac/0-uwazi-redesigns?node-id=1335%3A6

**Comment by txau** [comment]
@konzz this issue is related to uploading attachments: https://github.com/huridocs/uwazi/issues/2550
