### ISSUE TITLE
Error when starting server from system service

### ISSUE THREAD

**Issue by tlacoyodefrijol** [huridocs/uwazi#3495]
Uwazi was installed correctly and running fine when executing the server.js from production folder. But when running the service we get the following error. 

`url: /api/search?order=desc&sort=creationDate
query: {
 "order": "desc",
 "sort": "creationDate"
}
getaddrinfo ENOTFOUND elasticsearch`

**Comment by txau** [comment]
Looks like you are trying to connect to elasticsearch on the address "elasticsearch", so either properly define that address on your hosts file, or explicitly pass the env var to Uwazi before launching as in: `$ export ELASTICSEARCH_URL=http://localhost:9200`

Check https://github.com/huridocs/uwazi/wiki/Install-Uwazi-on-your-server for more info.
