### ISSUE TITLE
Denormalize inherited values instead of “UI automagic” (20pts)

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#3497]
Right now the UI uses the relationships of an entity to show inherited values. Because of that, the inherited values are only properly shown in the side panel. We want the data to be denormalised, store in the database, indexed and shown correctly in all the app.

- The [denormalise](https://github.com/huridocs/uwazi/blob/37d91765babc2e6b685a584d39f10e578777c2e7/app/api/entities/entities.js#L22) function should get the inherited values and store them in a `.inherited` key in the property.

When denormalizing you are going to find:
 1. A concrete value (ie. a date, number or text), the value gets denormalized
 2.  A thesauri key, both the key and the value needs to get denormalized (the value for representation, the key for aggregations), although maybe these aggregations can be based on the values, but still you need a way to cascade update when there are changes in the inherited values.
 3.  An inherited property (that is, trying to inherit an already inherited property). We want to avoid this scenario for now. This can lead to circular references or combinations that cycle through massive datasets.

- The [formater](https://github.com/huridocs/uwazi/blob/development/app/react/Metadata/helpers/formater.js) should know how to handle properties with inherited values, and remove any code related to the previous implementation.

- Update the metadata property [schema](https://github.com/huridocs/uwazi/blob/37d91765babc2e6b685a584d39f10e578777c2e7/app/shared/types/commonSchemas.ts#L93)
- Create a migration to denormalize the existing data
- Remove any code related to the previous implementation
- Review that when changing the template, the metadata inherited should be properly updated

**Comment by txau** [comment]
@konz aggregation filters and multi-select fields in forms also need to know about this. I think denormalizing also allows us to get rid of translations for these scenarios.

When denormalizing you are going to find:
- A concrete value (ie. a date, number or text), the value gets denormalized
- A thesauri key, both the key and the value needs to get denormalized (the value for representation, the key for aggregations)
- A select/multi-select value. Works as in thesauri, both the key and the value need to be denormalized.
- An inherited property (that is trying to inherit and already inherited property). We want to avoid this scenario for now. This can lead to circular references or combinations that cycle through massive datasets.

I think we are already denormalizing geolocations? If so we probably need to unify the code to avoid special cases etc.

This is going to need a data migration along with the properties schema.

Also idk if this has an impact in the data paths for elastic for common filters?

**Comment by txau** [comment]
Related: https://github.com/huridocs/uwazi/issues/2735
