### ISSUE TITLE
Formatter (formater) is using UTC dates when it shouldn't (7 pts)

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#3509]
Our date system has two different types of dates:
- timestamps representing actual dates
- timestamps representing times

For both, we store the UTC time for those values.  This is correct.

For display purposes, these need to be separated:
- If you input that an act happen on August 23, 1946, then it should show to everyone as that date, so it needs to be kept as a UTC and its value shown in UTC everywhere.
- If you want to know when a particular user edited an entity or created a file, then that time should get transformed into your local time, so you know that this was created 2 minutes ago and not, for example, sometime into the future if you are in the Americas and someone created an entity in Europe two minutes ago.

The formatter is doing the wrong thing with Creation Date and Modification Date.

When this is fixed, the tests on [TableRow.tsx](https://github.com/huridocs/uwazi/blob/development/app/react/Library/components/TableRow.tsx) will start failing again and should be updated.  Probably other places are affected as well.

**Comment by nwyu** [comment]
Related: https://github.com/huridocs/uwazi/issues/3451

**Comment by RafaPolit** [comment]
To check: apparently the formatter (formater.js) is not addressing AT ALL the common properties: title, creationDate, editDate.  They are coming RAW from the entity and not being formatted at all (or included the custom title lable, etc.).  So this issue may actually need to actually do that together with changing the way dates are processed.
