### ISSUE TITLE
Error when importing from CSV 

### ISSUE THREAD

**Issue by tlacoyodefrijol** [huridocs/uwazi#3517]
We're performing an upload from CSV. The ID of the entity is a number. When one user tried to upload Uwazi threw the following error. 

```
The import process threw an error:
 validation failed
should be number: .metadata['identificador']
```
Then another user tried uploading the exact same file and it worked.

**Comment by RafaPolit** [comment]
Is this a self-hosted UWAZI?  What version are you running?

The `identificador` property is, as I take it, configured as a number.  Any string that if fed to that value will yield an error.  Was the same CSV tried twice?  Or was it different CSVs generated from the same 'source' (for example, an EXCEL file exported).  When working with CSVs, please ensure they are coded with UTF-8 to avoid issues (especially if non-basic characters like accents or ñs are being used).

If it was the same exact CSV without any re-saves, perhaps they were uploaded from different systems?  Linux machines tend to infer the UTF-8 by default, while Windows machines use to require it to be explicitly selected.

If you believe it really was the exact same file, can you please provide either here or internally a copy of the file so we can look into it?

Thanks for the report.

**Comment by tlacoyodefrijol** [comment]
It's a self-hosted version running v 1.24

Identificador is a number indeed. It's the exact same file, encoded as UTF-8 and downloaded from a shared Google Drive folder right after the first error and uploaded directly to the instance from a different folder. I'll check if we can share the file internally. Thanks for the reply!

**Comment by daneryl** [comment]
Closing (stale).
