### ISSUE TITLE
replace icon (already in Uwazi)

### ISSUE THREAD

**Issue by simonfossom** [huridocs/uwazi#3528]
We have copy-from icon. It appears in two places:
1. FAB when clicking "Edit" on entity 
![image](https://user-images.githubusercontent.com/8134850/111350817-d0177200-8682-11eb-902c-69510b22befe.png)
2. when you search and click entity which you want to copy 
<img width="259" alt="Screen Shot 2021-03-07 at 08 57 20" src="https://user-images.githubusercontent.com/8134850/111350861-d86fad00-8682-11eb-9461-d2bc578afef9.png">
We need to replace the 1st icon with the 2nd

**Comment by konzz** [comment]
Hi @simonfossom cant find that icon in fontawesome, can you tell me wich icon is? if it is custom made, can you share it here?

**Comment by simonfossom** [comment]
It already is in Uwazi as a path:
![image](https://user-images.githubusercontent.com/8134850/111620523-200f4980-87e7-11eb-803c-24638f2f9e88.png)

you can find it in icons under **copy-from** like in the icons dropdown:
![image](https://user-images.githubusercontent.com/8134850/111620630-446b2600-87e7-11eb-8ba5-76a95a9771ee.png)
