### ISSUE TITLE
multi-date ranges - "remove" buttons are messed up

### ISSUE THREAD

**Issue by simonfossom** [huridocs/uwazi#3529]
<img width="371" alt="Screen Shot 2021-03-07 at 08 47 41" src="https://user-images.githubusercontent.com/8134850/111351156-2b496480-8683-11eb-8306-f33e1ef5f893.png">

**Comment by nwyu** [comment]
This looks fine now.

![multi-date range field](https://user-images.githubusercontent.com/56067374/187061024-65760062-b0a5-446f-86c9-d7885fb4bb5a.png)
