### ISSUE TITLE
Relocate item type tag

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#353]
@danicatalan 

- We have never used the action bar for anything but opening the document
- This way all tags are aligned creating better horizontal readablity

![screen shot 2016-08-26 at 00 34 19](https://cloud.githubusercontent.com/assets/489831/17988192/e5313848-6b24-11e6-80c5-5bac71b1b3df.png)

**Comment by danicatalan** [comment]
I think this is a great idea! Also we can remove the border to the action bar and stack all the possible buttons to the right (in library, uploads and sidebar).

![screenshot 2016-08-27 16 08 16](https://cloud.githubusercontent.com/assets/6364153/18027917/828b4344-6c70-11e6-8b49-a25819a7656b.png)

**Comment by txau** [comment]
@danicatalan go for it. 

Make sure the type tag has an alternate (ie, …) for long tag names.

**Comment by txau** [comment]
Closed in #379
