### ISSUE TITLE
Issue when uploading large files into supporting files 

### ISSUE THREAD

**Issue by natasha-todi** [huridocs/uwazi#3536]
When trying to upload this mov. file of size 1.25 GB into supporting files, even though it seems that the video has been uploaded, the user cannot click on the close button. Upon refreshing, the video has not been uploaded. (User had successfully uploaded a similar sized file just before) 

![Screenshot 2021-03-17 at 4 14 09 PM](https://user-images.githubusercontent.com/60774708/111455370-d159a500-873d-11eb-9a78-b57fc6e4734d.png)

**Comment by konzz** [comment]
We would need the specific file to debug this if it is working ok in other scenarios

**Comment by nwyu** [comment]
It is confirmed that we currently have a 500MB limit.
