### ISSUE TITLE
Metadata aggregations counts are ignoring the permissions restrictions. (6pts)

### ISSUE THREAD

**Issue by fnocetti** [huridocs/uwazi#3540]
When a collaborator user is presented with the library/uploads, the filters side panel is showing the counts as if permissions didn't exist. That is: if 2 entities exists for a particular aggregation and the user only has permissions to see 1, the aggregation count is still showing 2.
The fix for this issue implies, instead of manually pushing the permission filters to the query, setting the permissions filter by using the `addFilter` method in the query builder (because that method also works with the aggregations).

**Comment by nwyu** [comment]
The feature has been merged into the parent branch access-levels.
