### ISSUE TITLE
Issue when syncing with a submission form that is in more than one language. 

### ISSUE THREAD

**Issue by natasha-todi** [huridocs/uwazi#3552]
Syncing is set up between two Uwazi instances one public and one private (all changes made in the private instance), in order to have responses of the submission form on the public instance drop into the private instance. 
 On the submission form, the user cannot see the translated version of first question (also known as Title) and the question does not show up in the translations settings on the public instance at all.

**Comment by konzz** [comment]
Close in favour of #3553
