### ISSUE TITLE
Sync process does not sync the translation of the "Title" label in templates (13pts)

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#3553]
How to reproduce:
 - Have a sync setup with a "private" and "public" instances.
 - Have more than one language
 - Modify label for Title in a template
<img width="885" alt="Screenshot 2021-03-23 at 12 06 27" src="https://user-images.githubusercontent.com/948117/112137215-46126080-8bd0-11eb-8b92-3bd8a473a06d.png">

 - Translate that in other languages
 - Go to the "public" instance and see that the key to translate the "Title" label does not exists.

**Comment by RafaPolit** [comment]
The PR already has the bug fix.  

To Do:
- [ ] Migration moving the updatelogs of all `translations` to current timestamp to force re-sync of the missing translations.
