### ISSUE TITLE
Missplaced "add supporting file" button

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#3556]
![image](https://user-images.githubusercontent.com/489831/112172379-4869c000-8bba-11eb-87cd-56fd535a281f.png)

**Comment by simonfossom** [comment]
No, it's by design. We should at some point move "upload documents" button to the right of the "Primary Documents" title for consistency. 

![screen01](https://user-images.githubusercontent.com/8134850/112181587-dc5c7b80-8bfc-11eb-98b5-3fbb67aa0a03.png)

**Comment by nwyu** [comment]
Closing this issue in favor of #3557.

**Comment by txau** [comment]
@simonfossom having it on top makes sense, but having the button 700px away from the title not so much. Maybe the rightful place is besides the title?

**Comment by simonfossom** [comment]
Yes, we've addressed it here: #3569
