### ISSUE TITLE
Move the "Upload new file" button inline and to the right of the main "Documents" header

### ISSUE THREAD

**Issue by nwyu** [huridocs/uwazi#3557]
- [ ] Rename "Documents" to "Primary Documents".
- [ ] Rename "Upload new file" to "Upload PDF".
- [ ] Move green upload button inline and to the right of this header (so that it is consistent with the "Add supporting files" button in the area below it).

The info icon and tooltip can be added at a future time.

**Comment by simonfossom** [comment]
![image](https://user-images.githubusercontent.com/8134850/112201742-d83a5900-8c10-11eb-8166-9df0ac74dd1f.png)

Design: https://www.figma.com/file/xjsz7r65epN4B0b96zilac/0-uwazi-redesigns?node-id=2308%3A0
