### ISSUE TITLE
Better handle multiple file attachments on public forms (13pts)

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#3576]
Handling multiple attachments in the public form is not intuitive, and some mobile OSs do not allow multi-selection.

We need to improve this flow.

(Salva suggested looking into the Airtable implementation as reference)

Add e2e for the public form

**Comment by simonfossom** [comment]
Update to how upload section on public form should look like and behave:

![image](https://user-images.githubusercontent.com/8134850/113742630-151f4900-9703-11eb-836d-dc36d41d224d.png)

([Link to design](https://www.figma.com/file/xjsz7r65epN4B0b96zilac/0-uwazi-redesigns?node-id=2416%3A0))
