### ISSUE TITLE
Ensure that the client /api route respects the current domain and not be forced to localhost

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#3585]
Current client's `/api` page shows the swagger HTML for the API definitions.  You can execute queries to the API within that page.  The problem is that this is limited to `localhost`, making it unusable for any collection that is not local.

We could look into fixing that, the problem is that the swagger definitions are so outdated (#3531) that I'm not sure what the value of this change would be without actually updating the swagger files.

This comes from a self-hosted user reported in #3455

**Comment by RafaPolit** [comment]
Also, logging in is not working, so you cannot try any of the authorized endpoints.  Really not sure it's worth the time investing on this at this point.

**Comment by daneryl** [comment]
closing in favor of https://github.com/huridocs/uwazi/issues/3784
