### ISSUE TITLE
Public permission not shows the first time you open the share modal on a public entity

### ISSUE THREAD

**Issue by fnocetti** [huridocs/uwazi#3590]
For some reason, on already existing DBs the share modal won't show a public permission the first time you try to share a published entity.
This may cause users to accidentally publish entities when trying to share.

**Comment by fnocetti** [comment]
This issue showed not to be reproducible locally. Furthermore, it is not reproducible anymore in the original instance. We're keeping it open until releasing for further testing.

**Comment by daneryl** [comment]
probably fixed by other PR, not replicable
