### ISSUE TITLE
UI and interaction issues

### ISSUE THREAD

**Issue by simonfossom** [huridocs/uwazi#3593]
### differences from design 
- [ ] colors are not as in design:
  - settings: hover on row #F4F6FB
  - settings: hover on row #E5EEFE
  - settings: password+2FA #B5EAB4
  - settings: password #EEEEEE
- [ ] title of share dialog is 'bold' -> 500, it should be 'regular' -> 400
- [ ] option in share dialog needs 8px padding on all sides (and for text to stay centered vertically)
- [ ] user/group/pubic icon should be filled white not trasparent
- [ ] on the first row of dropdown there should be helper text "Press enter to add" 
- [ ] tooltip on 'restricted' icon is misaligned 
![image](https://user-images.githubusercontent.com/8134850/114382684-eedb2c80-9b8c-11eb-9e74-ded2d687d30e.png)
- [ ] tabs are small. they should have 16px left and right padding and 8px up and down padding. text in tabs should be aligned
![image](https://user-images.githubusercontent.com/8134850/114384249-c2281480-9b8e-11eb-889d-1c8f662ea28a.png)
- [ ] header in settings/users should have same padding as cells
![image](https://user-images.githubusercontent.com/8134850/114384526-1b904380-9b8f-11eb-91c0-4ff425b59cd7.png)
- [ ] settings/users add and edit field-titles should be Roboto Slab
![image](https://user-images.githubusercontent.com/8134850/114386214-395ea800-9b91-11eb-83f9-add53eefde38.png)
- [ ] settings/users add and edit fields should have 8px padding on all sides
![image](https://user-images.githubusercontent.com/8134850/114386490-922e4080-9b91-11eb-8272-fdfcaf6b8bef.png)
- [ ] settings/users add and edit FABs fill color and hover behavior is not as of other FABs (we have this buttons implemented right already)
![image](https://user-images.githubusercontent.com/8134850/114386000-f7cdfd00-9b90-11eb-9190-a22980ac151f.png)

### interactions that should be different 
- [ ] if I am admin or editor I should be editor on all entities and "can edit" cannot be removed from me
- [ ] when user is creating or editing a user or a group, other user or group cannot be selected. User **has to** discard changes or save before continuing to other task.

**Comment by fnocetti** [comment]
@simonfossom could you please mark this issues as critical and non-critical? Critical meaning: "we need this before going live"
Thanks!!

**Comment by simonfossom** [comment]
Idk... I'm not setting priorities.
imo none of these are critical. Last two lines, interactions, are important though.
