### ISSUE TITLE
text change on tooltips in Settings/Collection

### ISSUE THREAD

**Issue by simonfossom** [huridocs/uwazi#3605]
Replacing text in some of the tooltips in Settings/Collection:

See design link: https://www.figma.com/file/xjsz7r65epN4B0b96zilac/0-uwazi-redesigns?node-id=2546%3A0

**Comment by RafaPolit** [comment]
I believe the English should be reviewed?  Things like: "When coming to your database..." could be much better expressed.

Also, I believe it is a mistake addressing the user by "you".  Instead we should aim to either mention the "collection" or the "end users" or whoever is the target of the phrase.

**Comment by simonfossom** [comment]
@RafaPolit please make suggestions in Figma with comments where you think text should be changed and how. It's the speak-bubble icon on the top left of the nav. 

About addressing users with "you"... I don't know. It's not "collection that preforms action of changing favicon. "End users" sounds strange to me. Like we're trying to distance ourself from them. idk... "You" is a person reading the tooltip and performing an action. If they have to reload a page, how would that be expressed? Person doing the action has to do it, no? 🤔 
Maybe Lauren would be helpful here if she has time.

**Comment by RafaPolit** [comment]
Yeah, I agree it's difficult.  But, for example, phrases like: "Allows administrators and editors to share entities publicly", is a very good description... saying "Allows you to..." is much less precise.  So, I wanted to find those type of wordings to replace the word "you" which seems very ambiguous when you are "you" the admin, "you" the editor, "you" the user.

**Comment by RafaPolit** [comment]
For example: "When coming to your database, if you wish the user..."

This is a clear example of confusing the admin.  What is "coming"?, what is even "database"?.

So, something like: "Configure this value if you want visitors and users to be directed to a landing page other than library".  It's, for me, a lot simpler and to the point and while it uses minor technical terms like "landing page", I believe users will be able to find what that is much better than trying to understand what is "coming to your database".  

Yes, I agree that the native English speakers should give us a hand here.

**Comment by llfinch** [comment]
Hi all, I'd be happy to take a look at the text! I'll do so later today and drop some suggestions, if any, here.

**Comment by llfinch** [comment]
Hi all, 

I went through and made some suggested edits to the tool tips below. Feel free to take what you need and toss the rest if it doesn't work! I think using "you" as a form of address is perfectly natural - the English passive isn't great (unlike other languages, like Spanish, that do passive and no-specified-subject really well and naturally) and to me it's clear who the "you" is: the person reading the tool tip who has the pwoer to act on it. 

There's one bit that is confusing to me. I tried to find clarification in the documentation but wasn't able to. In the tool tip about non-Latin languages support, it says: "After selecting this option, you will not be able to revert back to using legacy property naming. If you are not facing issues with your template property names, we recommend leaving this unchecked." It's not immediately obvious to me what we mean by legacy property naming. Does this have to do with the URLs changing (which is mentioned right before this bit)?

Thanks! 

--

A favicon is a small icon that represents your collection in browser tabs and bookmarks. The default favicon is the Uwazi logo. To use your own:
1. Upload your icon in Custom Uploads.
2. Copy its URL.
3. Choose "Custom Icon" and paste the URL in the indicated field.
4. Reload the page to see your favicon in action.

--

The landing page is the first page that visitors see when they come to your collection. The default landing page is your collection's library. You can set a different landing page by adding its relative URL here.
For example: 

A page: /page/dicxg0oagy3xgr7ixef80k9
A filtered view in Uwazi: /library/?searchTerm=test
An entity: /entity/9htbkgpkyy7j5rk9
A document: /document/4y9i99fadjp833di

Important: You must use relative URLs. These start with a forward slash and do not include the domain name. For example: In the address https://yoursite.com/landingpage, the relative URL is /landingpage

-----

This option allows administrators and editors of your collection to publicly share select entities, meaning visitors to your collection will be able to see these entities without logging in. 

---

If you have a contact form, this is the email address that will receive the form's submissions. Click here to learn how to add and confirgure a contact form on a webpage. 

----

This is the email address that will appear as the sender when an email is sent from your Uwazi collection to registered users. The default address is no-reply@uwazi.io. You can set a custom one by including your desired email address here.

---

If you have configured a public form and would like a different Uwazi collection to receive the submissions, enter its URL here.

----

This option enhances support for non-Latin languages as default languages of your collection. 
Selecting this option will update all template properties automatically. The process could take several minutes.
Selecting this option will likely change the URLs of library filters. As a consequence, if you have menus or links using such URLs, they will probably stop working. You will need to update them manually. 
After selecting this option, you will not be able to revert back to using legacy property naming. 
If you are not facing issues with your template property names, we recommend leaving this unchecked.

**Comment by RafaPolit** [comment]
To implement this:
- First create a migration that will do the following:
    - Replace values on NON-ENGLISH languages that still match the original (previous) value (this is, avoid those that have already been translated)
    - Replace values in ENGLISH with the new values, no matter what they have, even if they have been translated
- Update the "default translation" repo as well with these values
- Replace the HTML of the code with the new values
- Ensure that they are included in "smaller" semantic keys and not full-text keys

**Comment by mfacar** [comment]
#5159 includes a small parser in the `Translate` component which at the moment supports line breaks and italic text (wrapped between asterisks (`*italic*`).  
Some of the changes in tooltips couldn't be applied because are not applicable, for example: "allow public sharing" which currently is not an option in collection settings.
