### ISSUE TITLE
Open document icon needs to be more obvious

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#362]
![screen shot 2016-08-26 at 18 27 49](https://cloud.githubusercontent.com/assets/489831/18012668/dc035346-6bba-11e6-9136-93942420cd66.png)

I think this guy needs to more visible. Even @konzz missed it and he knows the interface by heart.

**Comment by danicatalan** [comment]
I added a border to the icon - now is like the other buttons in the overall application.

I also included the open button inside the sidepanel-footer. Maybe it's a little bit redundant on desktop, but works great on mobile and also it's good to educate the users that this icon is our "universal open document icon".

I've made two variations: one with this icon and another with an arrow variation, just for simplification purposes. I think both work very well, so It would be great to hear your opinion about the two alternatives.

![screenshot 2016-08-27 16 02 54](https://cloud.githubusercontent.com/assets/6364153/18027901/0f1d50dc-6c70-11e6-9aae-69af1c53a9b9.png)

![screenshot 2016-08-27 15 56 57](https://cloud.githubusercontent.com/assets/6364153/18027870/297bbafa-6c6f-11e6-91a7-2c23a2d90d09.png)

**Comment by txau** [comment]
@danicatalan I like the first icon better.

I'm not that convinced about the highlight card, all blue?

**Comment by danicatalan** [comment]
I think this is the best approach we can get for now.

![screenshot 2016-08-29 16 49 05](https://cloud.githubusercontent.com/assets/6364153/18055533/8874d222-6e08-11e6-92a7-5e4747838463.png)

**Comment by txau** [comment]
Closed in #379
