### ISSUE TITLE
upgrade to 1.18 breaks cross-references

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#3626]
I today tried to upgrade  from 1.17 to the present version, which failed. So I opted to do a piecemeal upgrade instead, my Uwazi is now at version 1.20.0 and I see that the upgrade step from 1.17 to 1.18 has broken the handling of cross references.

e.g https://fpic.enip.eu/en/entity/ft228hi5pr5?ref=5c925ef073bb98001d833805 get me to an all-white screen while 
the plain address of the document https://fpic.enip.eu/en/entity/ft228hi5pr5  works.
I am submitting this after noticing that the issue persists through version 1.20. Apologies if this is something that has already been fixed in subsequent releases.

**Comment by RafaPolit** [comment]
This was a known issue and fixed in 1.27 (https://github.com/huridocs/uwazi/tree/1.27.0) on PR #3572 .  Please update to the latest stable release (currently 1.28).

**Comment by vasyugan** [comment]
> This was a known issue and fixed in 1.27 (https://github.com/huridocs/uwazi/tree/1.27.0) on PR #3572 . Please update to the latest stable release (currently 1.28).

Yes, that was the first thing I tried, but that broke other stuff, that is, the yarn migrate &&  yarn reindex failed once  again. Will have another look at this tomorrow or so.

**Comment by RafaPolit** [comment]
In theory, you shouldn't need to move one version at a time.  You could put 1.28 on top of 1.17 and migrations should happen correctly.  Please, let us know of any findings / errors.

Thanks for the report.

**Comment by vasyugan** [comment]
ok, closing this one, opening a separate issue.
