### ISSUE TITLE
Upgrade  from 1.17 to 1.28: yarn reindex: "Uncaught Reindex error."

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#3627]
Unfortunately, not a lot of info. I just did the upgrade from uwazi 1.17 to 1.28. While running yarn migrate && yarn reindex I see the following:

```
yarn run v1.22.4
$ node run.js ./app/api/migrations/migrate
Done in 3.43s.
running yarn migrate
yarn run v1.22.4
$ node run.js ./database/reindex_elastic.js
Deleting index uwazi_development...2021-04-27T11:14:29.117Z [uwazi_development] Uncaught Reindex error.
Cannot read property 'error' of undefined
Will exit with (1)

Restoring index settings... [done]
2021-04-27T11:14:29.134Z [uwazi_development] uncaughtException: request to http://elasticsearch:9200/uwazi_development/_settings failed, reason: connect ECONNREFUSED 192.168.144.3:9200
FetchError: request to http://elasticsearch:9200/uwazi_development/_settings failed, reason: connect ECONNREFUSED 192.168.144.3:9200
    at ClientRequest.<anonymous> (/home/node/uwazi/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:314:20)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.4

```

**Comment by txau** [comment]
It seems like Elastic search is down or not reachable in that IP or port:

reason: connect ECONNREFUSED 192.168.144.3:9200

**Comment by vasyugan** [comment]
> It seems like Elastic search is down or not reachable in that IP or port:
> 
> reason: connect ECONNREFUSED 192.168.144.3:9200

Yes, but that's _after_ running yarn migrate. So something crashes elastic during the migration and redindex process.

**Comment by vasyugan** [comment]
somehow it works now... Not really sure what is different this time. Sorry for having bothered you.

**Comment by RafaPolit** [comment]
It could be a memory hogging scenario during the migration.  It would be interesting to follow up a bit on this.

The good thing is that Elastic is used only for search, no critical data is stored there.  As long as the Mongo server was up and running, there should not be an issue.  You should go for a reindex to ensure that Elastisearch reflects the final state of the DB.

**Comment by txau** [comment]
> somehow it works now... Not really sure what is different this time. Sorry for having bothered you.

Great =)
