### ISSUE TITLE
Filter and Aggregate by Inherited metadata (30pts)

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#3636]
Expected features:
- Filter by inherited metadata instead of the title of the inherited entity
- Show appropriate aggregations for each value.
- Inherited filters should match with common filters.

Implementation decisions
- ~Template properties will have type (text, relationship...) and filterType (relationships will use inherited type)~
- ~The inheritedValue will be moved from inheritedValue to value~
- ~The value will be moved to ref {value: label:} or ref / refLabel~
- ~The label should be replaced with the inherited property label~
- Do not allow inheriting from inherited

Tips
- Make sure copy from copies everything and not just the value
- check permissions ??
- Check if inherited properties are exported with the correct value and just report it but do not develop

Example of inherited values

```
{
  sharedId: 456,
  title: 'Konz the famous magician',
  template: A,
  metadata: {
    favourite-colors: [{value: 28s7d3, label: 'green'}, {value: 234js9d3, label: 'blue'}],
  },
}

{
  sharedId: 859,
  title: 'Rafa the copy cat',
  template: B,
  metadata: {
    inherited-color: [{value: [28s7d3, 234js9d3], label: ['green', 'blue'], ref: {value: '456', label: 'Konz the famous magician'}}],
  },
}
```

**Comment by daneryl** [comment]
> Make sure copy from copies everything and not just the value

copy from does not copy everything, only the value actually, but  this is correct, as the new values are  "readOnly" and generated from the server based on the value, when saving the entity everything works properly. what is a bit weird is that in the copy-from UI you see the original values in the form and the inherited in the copy panel
![copy-from](https://user-images.githubusercontent.com/1386423/117941578-89549a00-b30a-11eb-8d5e-d0ec266118c0.png)


> Check if inherited properties are exported with the correct value and just report it but do not develop

export csv for inherited properites is exporting only the original label/title

**Comment by konzz** [comment]
Yes I think that "Make sure copy from copies everything and not just the value" was for the previous aproach
