### ISSUE TITLE
System Language Translations Import (13pts)

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#3643]
- Add CSV import to update translations
- Look at thesauri CSV import to follow similar approach
- Change "System" label in the translation form to User Interface
- The Translation form will remain in the translations section (for now)

CSV should expected to be something like
```
key, english, spanish
hello, hello, hola
bye, good bye, adios
```
We already have a [CSV loader](https://github.com/huridocs/uwazi/blob/development/app/api/csv/csvLoader.ts) look at it for more specifics.

![translations](https://user-images.githubusercontent.com/8134850/116520002-72598500-a8d2-11eb-809f-4888b0b41ac7.png)

Long discussion issue: #2487

**Comment by grafitto** [comment]
> * Look at thesauri CSV import to follow similar approach

Do we also add a FAB for the import or is there another approach, I am asking this because I understand we are working towards removing FABs entirely from Uwazi and adding one now would be doing the opposite @konz @RafaPolit

**Comment by nwyu** [comment]
@grafitto, it is true that we're trying to be fab-free, but for now let's use the button for import since there is not an alternative design, and it continues to follow the import thesauri action.
