### ISSUE TITLE
Public form should render a simple textarea instead of a markdown field (2pts)

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#3656]
When rendering a template that has a "Rich Text" field in the public form.

<img width="724" alt="Screenshot 2021-05-11 at 14 53 38" src="https://user-images.githubusercontent.com/948117/117818255-b7819d80-b268-11eb-9287-71d8bfad0d6a.png">

Tips:
@mfacar develop something similar for the  Not-so-UniquiteID-maybe? field  [this is the code](https://github.com/huridocs/uwazi/blob/f4a8c0f6635726193d3bc69897d55fc1c7a24017/app/react/Metadata/components/MetadataFormFields.js#L198-L201)

**Comment by RafaPolit** [comment]
Check if not rendering the "edit | preview | help" can be accomplished simply. Fallback to the CSS hiding approach only if needed.
