### ISSUE TITLE
Relationships multiinheritance 🚀 (20 pts)

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#3667]
Tasks:
- Allow multiple inheritance via different fields
- On edit we will group all relationships that are the same in only one relationship field
- The API should validate that we are sending the same values or return an error
- Remove template validation that prevents multiple relationship fields with the same configuration

WARNING ⚠️ 
We have two proceses that are affected by this:
- Generate relationships based on the metadata
- Modify metadata based on relationships

**Comment by RafaPolit** [comment]
![Uploading multi-inheritance-sidepanel-edit-A01.png…]()
