### ISSUE TITLE
Move the check for X-Requested-With into another middleware (5 pts)

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#3669]
maybe we should move the check for X-Requested-With into another middleware that is not present in the tests to avoid this pollution everywhere ? i think that check does not belong into the auth middleware anyways, its a diferent thing. tech debt ?

_Originally posted by @daneryl in https://github.com/huridocs/uwazi/pull/3617#discussion_r631627341_

**Comment by daneryl** [comment]
On top of it I think we should have a custom return error when the flag is not present in the request, right now returns "Unauthorized" which is confusing when testing the API

**Comment by konzz** [comment]
In the [AuthMiddleware](https://github.com/huridocs/uwazi/blob/cedae1cf2109054bc2b6fa5e2cafc6f6118ffcba/app/api/auth/authMiddleware.ts#L16) we check if the request was made with "XMLHttpRequest"
`req.get('X-Requested-With') === 'XMLHttpRequest'`

This check does not belong to this  middleware.
- Create a new middleware to do this check
- This middleware should return a proper error. (Right now you get "Unauthorized"
- Update tests? TBD
