### ISSUE TITLE
Fix performance issues with denormalize in backend. (13pts)

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#3671]
Hello developer, our organization has been fixing some performance issues related to the function getByDocument(), this function is also used in the [process of denormalise inherited properties in the backend](https://github.com/huridocs/uwazi/blob/75fad04668851a6789906499e0c7651f1cb88871/app/api/entities/entities.js#L394).

The mission, if you decide to accept it, would be to find an alternative to get all relationships each time an entity is been denormalised.

Good Luck.
Hot fix

**Comment by fnocetti** [comment]
We decided that this issue still needs to be worked but we are estimating a new story to work it with another approach, because the one taken didn't lead to the results we expected.
