### ISSUE TITLE
To be able to add unique ID as the title of an entity (13 pts)

### ISSUE THREAD

**Issue by natasha-todi** [huridocs/uwazi#3672]
Partners who work in the violations stream and follow the "who did what to whom" events based methodology often have their templates organised by the Victim, Perpetrator, Event and Location structure. In the case of the Victim or the Perpetrator templates, most partners working in sensitive contexts redact names and all other identifying information. Accordingly instead of the name of the Victim or the Perpetrator they would benefit from being able to use the unique id as the title. 

As the unique id feature currently exists, our violations stream partners would still need to think of and create titles for the entities (unrelated to the sensitive information they have redacted) and to simultaneously add the unique ID property to that template.  

_As a human rights defender working in a sensitive context, I want to be able to assign unique ids as titles instead of the names of the victims and perpetrators in order to be able to easily reference specific entities either in the database or any of the reports produced around the documentation work._

**Comment by simonfossom** [comment]
@txau @nwyu 
This is connected to unlocking titles and other system metadata. we should discuss this on product call

**Comment by natasha-todi** [comment]
As discussed in today's Monday coordination call, some possibilities are : 

- To be able to auto-generate unique IDs as titles 
- Or allowing users to choose which property should be presented as a template's title property

**Comment by txau** [comment]
@simonfossom indeed. I'm inclined towards de idea of selecting a property as title. Or even a combination of several properties.

**Comment by konzz** [comment]
- Hide title in public form
- CSV import should add generated ids to entities without titles.
- Check CSV import still prevents empty titles when no autogenerating.
