### ISSUE TITLE
"x hidden" relationships does not take into account not-yet-loaded hubs

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#3699]
Currently, the relationships tree view has, beneath the search box, the amount of relationships you have, the ones that are "hidden" to you (with a mention that you don't have permissions!).

Yet, this value is not taking into account the fact that we load only the first 10 hubs.  So, this value says something like: "1023 hidden because you don't have permissions, request your organization for access".  But, if you load more hubs, now you have "983 hidden".  And so forth.

So, they were not hidden due to lack of permissions, they were just not yet loaded.

This is very missleading.
cc. @mfacar @fnocetti

**Comment by txau** [comment]
![image](https://user-images.githubusercontent.com/489831/120012691-12233500-bf9d-11eb-9262-909793610cf7.png)

**Comment by daneryl** [comment]
@fnocetti does https://github.com/huridocs/uwazi/pull/3871 fixed this ?

**Comment by fnocetti** [comment]
> @fnocetti does #3871 fix this ?

Correct, closing now.
