### ISSUE TITLE
Relationships aggregations on side panel only reflect loaded hubs (timeboxed 1 day)

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#3700]
Si panel relationship aggregations are no longer aggregating all the hubs for a particular entity, they are only aggregating the relationships that originally loaded.  As you load more aggregations, the values change.

As in library, aggregations need to show the total amount, regardless of how many items you have loaded in the central panel.

**Comment by simonfossom** [comment]
@RafaPolit I guess this is the same bug?


https://user-images.githubusercontent.com/8134850/122282997-5c3c6e00-ceec-11eb-8a30-2b1bad0a9ef6.mov

**Comment by konzz** [comment]
Related #3699 ?

**Comment by RafaPolit** [comment]
The screen capture on post #2 is not at all the same issue.

**Comment by fnocetti** [comment]
Investigation concluded
