### ISSUE TITLE
Fix performance issues with denormalize inherited values in backend. Round 2 (30 pts)

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#3702]
When we save an entity we trigger a  "denormalize Inherited metadata" process, it process all the entities related to the entity saved and updates the denormalization, so if the entiy has modified any property thats been inherited, its updated everywhere.

We already tried a first refactor but did not achieve a good performance so we discarded the changes.

The idea will be to start by defining scenarios and create new tests for this, since one of the bigger problems in the first attempt was not having reliable tests.

It's not safe to go alone! Take this.  🗡️

**Comment by fnocetti** [comment]
Hot fix merged to dev
