### ISSUE TITLE
Administrator permission filters (20 pts)

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#3703]
As admins we want to filter entities by "EXPLICIT" access levels that groups or users have on those entities.

<img width="404" alt="Screenshot 2021-05-31 at 17 07 43" src="https://user-images.githubusercontent.com/948117/120212866-d4d7d500-c232-11eb-9b2f-774e6560a41b.png">

**Comment by RafaPolit** [comment]
The "Public" and "Restricted" should not appear here on this admin-exclusive, but replace the "include unpublished" on the general filters when you are logged in.

We still need to discuss what would happen if we uncheck both options.

**Comment by fnocetti** [comment]
> The "Public" and "Restricted" should not appear here on this admin-exclusive, but replace the "include unpublished" on the general filters when you are logged in.
> 
> We still need to discuss what would happen if we uncheck both options.

This is addressed in #3817
