### ISSUE TITLE
Bring uploads functionality to the library (30 pts)

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#3704]
We are in the process of removing the uploads section, for this the first step is bringing the uploads functionality to the library:

- Create new entity
- Upload PDF
- Import CSV
- Remove link to uploads
- Change the filter "Include unpublished documents" to (TBD) filters for Public and Restricted.

⚠️  Many e2e depend on going to uploads to create entities, and will break by these changes.

![Collection view](https://user-images.githubusercontent.com/8134850/114064678-29e21500-989a-11eb-964a-8534e79fe4fd.png)

([Link to the screen in design of Access Levels](https://www.figma.com/file/2AT2ilGWBTe0pWy4j66yxW/Uwazi-Access-Levels?node-id=790%3A1821))

**Comment by RafaPolit** [comment]
Please, coordinate the Wiki update to show these changes.

**Comment by nwyu** [comment]
For users with a login, there will be a filter up top in order to distinguish the Published/Public entities and the Unpublished/Restricted entities. This will replace what is currently the "Include unpublished documents" filter.

**Comment by fnocetti** [comment]
Regarding the Published/Unpublished filters, @Zasa-san and I think that the best option is to have to check boxes with the following semantic:

- **Both unchecked:** show everything.
- **Published checked:** show only published.
- **Unpublished checked:** show only unpublished.
- **Both checked:** show everything.

Also, can you confirm the labels for those check boxes?

cc: @nwyu @RafaPolit @txau
