### ISSUE TITLE
Show metadata in cards

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#371]
- [x] Admin can configure which properties will be shown in cards
- [x] Display properties in cards with no size restrictions

**Comment by RafaPolit** [comment]
@danicatalan ,

There is a
```
width: auto - 100px;
```
Property set for dd which is accepted by any browser.  This is affecting the styling of the metadata in cards.

**Comment by RafaPolit** [comment]
ToDo:

- [ ] Discuss implementation apprach
- [ ] Refactor / create independent Component in Doc.js

**Comment by txau** [comment]
Closed in #400
