### ISSUE TITLE
Settings-->Available languages exclamation mark tooltip typo and inconsistency

### ISSUE THREAD

**Issue by llfinch** [huridocs/uwazi#3710]
Current text reads: “Some adavanced search features may not be available for this language.” with a typo in "advanced". It should be corrected to: “Some advanced search features may not be available for this language.”

Furthermore, the exclamation mark tooltip warning that “some advanced search features may not be available” should only be for languages without an [Elastic Search language analyzer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-lang-analyzer.html), right? However, the following languages which indeed have Elastic Search support still show the exclamation mark and tooltip: Bengali, Chinese Japanese Korean (CJK), Estonian, Indonesian

![imagen](https://user-images.githubusercontent.com/56080527/120318364-0e1a4e80-c2e0-11eb-81bb-0fa78b041282.png)

**Comment by konzz** [comment]
If our list of supported languages is outdated we should review it, check which version of elastic-search supports those languages, and check our version.

**Comment by mfacar** [comment]
This warning was removed as it was asked in #4872
