### ISSUE TITLE
Clicking "settings" in footer takes you to a mostly blank screen (1 pts)

### ISSUE THREAD

**Issue by llfinch** [huridocs/uwazi#3712]
In the footer navigation is an item called "Settings". When you click on it, you're taken to /en/settings which is essentially a blank page. This is unexpected and as a user makes me wonder if the request timed out. 

It might be better that clicking the footer nav item "Settings" behaves exactly like clicking the top righthand corner cog icon: it takes you to Settings-->Account.

![uwazi footer nav](https://user-images.githubusercontent.com/56080527/120321569-c39ad100-c2e3-11eb-89b1-98d10b1a7680.jpg)
![footer navigation settings result](https://user-images.githubusercontent.com/56080527/120321578-c5fd2b00-c2e3-11eb-9084-03888e5fd594.jpg)

**Comment by Ashish-15s** [comment]
I am a beginner in open source . So, Can anyone help me to find the specific path for this issue ?
