### ISSUE TITLE
Template label falling off the side of card (3 points)

### ISSUE THREAD

**Issue by llfinch** [huridocs/uwazi#3713]
While browsing this collection using my laptop + external monitor: https://nkfootprints.info/library/?q=(searchTerm:%27%27) I noticed that the cards aren't properly responding to different browser widths. When I view the library on my wider external monitor, the template label extends so far that the "view" button falls off the side of the card:

![footprints wide screen](https://user-images.githubusercontent.com/56080527/120322099-52a7e900-c2e4-11eb-981c-4ea878907743.jpg)

But when I view the library on my more narrow laptop screen, the label fits itself just fine in the card:

![footprints smaller screen](https://user-images.githubusercontent.com/56080527/120322110-58053380-c2e4-11eb-8693-0f1d824ae40c.jpg)

**Comment by fnocetti** [comment]
Solution:
- Truncate the message, use elipsis (...)
