### ISSUE TITLE
Settings-->Collection-->Private instance tooltip typo

### ISSUE THREAD

**Issue by llfinch** [huridocs/uwazi#3714]
The current text of the tooltip reads: “Private Instance: Check to make this instance private (only logged users access the data)”

This needs to be corrected to say "logged-in users" to avoid confusion, as "logged" by itself simply means "recorded" or "surveilled" (and since we actually have an Activity Log, could be confusing too). It could also read better to say:

"Check to make this instance private (only logged-in users **can** access the data)"

![private instance tooltip](https://user-images.githubusercontent.com/56080527/120323426-c1d20d00-c2e5-11eb-9f71-e691fb1ffbd8.jpg)

A smaller additional edit could be made to "Private instance" by putting "instance" in lowercase, instead of the current capitalized style. This would make it consistent with most of the other Collection settings options that surround it, in which only the first word is captalized:

![collection setting titles](https://user-images.githubusercontent.com/56080527/120323549-e29a6280-c2e5-11eb-8537-d61e586dd683.jpg)

**Comment by RafaPolit** [comment]
Thanks for this report.  Indeed, this should be a very quick fix.
