### ISSUE TITLE
Default entity sorting option language could be improved (1 pts)

### ISSUE THREAD

**Issue by llfinch** [huridocs/uwazi#3715]
“Recently” and especially “Least recently” sound a bit awkward because “recently” isn’t a comparative (it’s just an adverb) unlike "Least recently", and “least recently” is a rather clunky superlative on its own.

We could simply replace them with “Newest” and “Oldest” which are cleaner and fairly common superlatives in this context?

![default date sorting language](https://user-images.githubusercontent.com/56080527/120324067-7a984c00-c2e6-11eb-8c5c-a8ce8f8470e9.jpg)

**Comment by grafitto** [comment]
This might need a migration on translations, basically to replace `Least recently` with `Oldest` and `Recently` with `Newest`. Correct? @konzz @RafaPolit @fnocetti
