### ISSUE TITLE
Requested feature 

### ISSUE THREAD

**Issue by agsabbagh** [huridocs/uwazi#3721]
adding social media sharing buttons with counters i.e. Facebook and twitter, to entities, to allow people from sharing their relatives profile on social media.
![image](https://user-images.githubusercontent.com/66379177/120594004-f0b4c400-c448-11eb-880c-efe83a38eebf.png)

**Comment by txau** [comment]
Hello @agsabbagh unfortunately we do not plan to add sharing to social media support directly in Uwazi on the short term.
