### ISSUE TITLE
Korean letters rendering issue (1/2 day timeboxed)

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#3723]
We have some example PDF in Korean that when uploaded to Uwazi render everything (other languages, images) but not the Korean texts.

Please ask PMs ( @nwyu ) for an example PDF.

**Comment by LaszloKecskes** [comment]
After (roughly) the allotted half day timebox:

1, I have tried to create a pdf with some random korean text copy-pasted from wikipedia (using ubuntu default LibreOffice Draw). It renders.
2, I have loaded in one of the faulty pdfs. It reproduces the error.
3, I have opened and re-exported the faulty pdf using Draw, without any other change. It fixes the issue.

The difference I could find between the two is that the Draw exported working pdfs use pdf1.5, while the faulty one uses pdf1.3.

On an another track, the non working examples give the following warning: "Warning: Error during font loading: The CMap "baseUrl" parameter must be specified, ensure that the "cMapUrl" and "cMapPacked" API parameters are provided."
This warning is not present on the working examples.

Researching this, the following threads seemed relevant.
- https://github.com/FranckFreiburger/vue-pdf/issues/190
- https://blog.csdn.net/m0_37903882/article/details/113320701
- https://stackoverflow.com/questions/32764773/what-is-a-pdf-bcmap-file
- https://www.telerik.com/forums/where-to-set-cmap

According to the stackoverflow thread:
"Include the files and set the PDFJS options correctly if there is a possibility that you need to display pdfs with East Asian texts that were created by legacy pdf creation tools. Don't include the files if you are certain you won't need to display such files."

Based on the warning message and the difference in the pdf versions, my current best guess is that this is the case.
