### ISSUE TITLE
Table view: endless scroll + select all dont play well together

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#3732]
Since our table view is based on endless scroll, trying to perform a simple bulk operation on several entities results in needing to scroll to the limit several times before hitting the select all button in order to do the bulk operation.

**Comment by fnocetti** [comment]
Isn't that the same for the cards but by clicking a button?
Also this makes me wonder (again :D ) if we need to rethink the select all button semantics. Should it select every result shown or every result in the search?

**Comment by txau** [comment]
@fnocetti agree. There are these three ingredients we need to balance out:
- Select all meaning all visible or all affected by filters? If we convert it to "all affected by filters" then the problem is solved.
- The load more/trigger the scrolling is down the list, while the select button is at the top. When you know what data you want to select and what you want to do about it, it is annoying having to jump between the beginning and the end of the list.

> Isn't that the same for the cards but by clicking a button?

Yes, but at least you have the option to get 300 in a go, which in most cases is enough to get all the data. Is way less time.

**Comment by txau** [comment]
- Remove endless scroll
- "Select all" will have an interaction option to also select non visible items.

**Comment by nwyu** [comment]
Closing in favor of #4996 and #4997.
