### ISSUE TITLE
Close filter button in table view above other button (3 pts)

### ISSUE THREAD

**Issue by gabriel-piles** [huridocs/uwazi#3743]
The close filters button (a simple cross) in table view appears above other button.

It happens in Chrome and Firefox on linux Pop!_OS 20.10.

![Screenshot from 2021-06-15 14-59-36](https://user-images.githubusercontent.com/22240564/122057935-69256880-cdeb-11eb-96f8-6fdc37d4b794.png)

**Comment by RafaPolit** [comment]
Removed "on linux" from the title, it is not OS dependent.
