### ISSUE TITLE
Error reported as localhost (5 pts)

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#3755]
The tenant needs to be displayed in the error for proper debugging:
```
2021-06-19T20:16:14.337Z [localhost] 
import.csv file not found
```

**Comment by txau** [comment]
`2021-06-29T01:08:44.995Z [localhost] There's a connection to entity: ftwked8gct on hub: 5f28024899525cd2e451c76b, but no entity data.`

**Comment by daneryl** [comment]
after taking a look i think the best solution should be to avoid ```shouldBeMultiTenantContext``` 
https://github.com/huridocs/uwazi/blob/9c2ea55b19aaea6daa04b5366799282e2216a23a/app/api/log/infoFormat.ts#L8-L11

we can do the following 
- assume always multitenant.
- try catch on the tenants.current()
- if there is an error then add that info in the object returned

this ensures we always will have all the info we need, without having to know from the outside if we should be in a multitenant context or not.

@konzz @txau
