### ISSUE TITLE
Plain Text / OCR on pdf files 

### ISSUE THREAD

**Issue by mirzip** [huridocs/uwazi#3758]
Hello, 
I'm a new UWAZI user. When using the "plain text" function to analyze documents, some pdf files are readable and others are not, which leads to differences in the level of search results. 
I'm trying to figure out  what system UWAZI currently uses for this function so I can determine in advance which files should be uploaded to UWAZI as they are, and which ones should be processed via an OCR tool beforehand.
Any help would be greatly appreciated.

**Comment by txau** [comment]
@mirzip currently Uwazi doesn't integrate any OCR solution, although we plan to do it soon. Uwazi extract the PDF text content and uses a full text server for indexing/searching (ElasticSearch). So as far as the PDF has any text content, it will be indexed, which is not the case of the non-OCRed files.

Any OCR before uploading to Uwazi will work.
