### ISSUE TITLE
Add Cancel button when editing entity?

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#376]
If I click on an entity and edit the metadata, the 'closing' X on the panel is more or less auto-explanatory.

But when I click on the 'extrenal link' button on an entity I see the metadata on the left side of the screen and the connections on the right side.

If I edit from there the metadata, I can 'save' or 'delete', but there is no way to 'cancel' any changes I have made.  This seems very un-intuitive to me.

Is this an intended behavior?

**Comment by danicatalan** [comment]
I added a simple cancel button when the users is editing the content. I need some dev help to close the edit form. @RafaPolit can you check it out? It's on `376-entity-cancel-edit`

![screenshot 2016-09-14 23 00 01](https://cloud.githubusercontent.com/assets/6364153/18529833/0a1cb5ce-7acf-11e6-8121-31ffe8f30fc7.png)

**Comment by txau** [comment]
Related to https://github.com/huridocs/uwazi/issues/359
