### ISSUE TITLE
New PR checklist

### ISSUE THREAD

**Issue by Zasa-san** [huridocs/uwazi#3771]
Review and suggest a new checklist for PRs. Create a poll to vote witch items should be included in the new list, and suggest new items aswell.

**Comment by LaszloKecskes** [comment]
@Zasa-san Is something going on with this? If not, can you close it? Thank you!

**Comment by Zasa-san** [comment]
> @Zasa-san Is something going on with this? If not, can you close it? Thank you!

We are not working on this at all. I'll close it.
