### ISSUE TITLE
Library display options are hidden behind filters window

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#3775]
When I go to the Impact Iran library https://impactiran.uwazi.io/library and click on "select filters", there's no way for me to then hide the filters so I could change the view from table to cards or a map. 
![2021-06-23_11-23-52 (1)](https://user-images.githubusercontent.com/354426/123134134-19abf180-d416-11eb-8266-347a59aa32f3.gif)

**Comment by nwyu** [comment]
Same problem reported at #3743.

**Comment by nwyu** [comment]
This is fixed in #3789. Currently in staging; will be included in the next deployment to production.
