### ISSUE TITLE
Not setting the inherited property crashes Uwazi

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#3783]
Replicate:

On a relationship property in settings > templates, check the "inherit property" box but do not select any property and save. When you try to access the library the app crashes.

This should have validation on client side and server side.

Also, this code in `search.js` probably could be more fail safe:
```
  if (inheritedProperty.type === 'geolocation') {
          geolocationProperties.push(`${prop.name}`);
        }
```

**Comment by konzz** [comment]
This may be fixed by #3747
