### ISSUE TITLE
create basic api documentation 

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazi#3785]
based on https://docs.google.com/document/d/1sqF7nqyYm4VhtrFVDR67H1O_MVA-o4gxvWPNhX4PE2U

**Comment by andreasnef** [comment]
Hi @daneryl 

Looking at this issue and also https://github.com/huridocs/uwazi/issues/3784, I am wondering if you have a timeline for this, or if there is another location where we could find an up-to-date api documentation for reference? I'm mostly curious if for example updates of entities are possible?

Kind regards, Andreas

**Comment by daneryl** [comment]
Hello @andreasnef there is no timeline yet for this, i think we will try to progressively create it.
Updates on entities are possible using the same endpoint mentioned on the document **POST** ``/api/entities``, let me know if i can help with that, or need help with anything.

**Comment by daneryl** [comment]
this is being worked on with a different approach #5448, #5277
