### ISSUE TITLE
Add option or botton to download PDF printable version of an entity

### ISSUE THREAD

**Issue by marina-ga** [huridocs/uwazi#3794]
Partner suggestion/request for future development. 
As an HR org, a partner wants to collect complaints directly through Uwazi and print the entity with the info gathered for the victim. So,  they can share a copy of their complaint manually signed. Victims need to present the printed complaints to other institutions. 
Currently, the partner first fills a paper form and after that enters the data into Uwazi. Having a printable version would save a lot of time.

**Comment by txau** [comment]
@marina-ga I'd go for CSS for printing and then they can print to PDF.

**Comment by marina-ga** [comment]
Thanks @txau! 

So, which is the correct path to achieve this goal?
Are these the right links to address this? 
https://uwazi.readthedocs.io/en/latest/admin-docs/designing-your-website.html?highlight=Css
https://uwazi.readthedocs.io/en/latest/admin-docs/analysing-and-visualising-your-collection.html?highlight=print
