### ISSUE TITLE
TOC selection rectangles fail to index due to type mismatch

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#3797]
ElasticSearch has given an error indexing a TOC's selection rectangles because it cannot change long to float.

We should cast the correct type to avoid this issues.

Also note that this error is reporting as 'localhost', so it doesn't have the context in the process, we should address that as well.

```
2021-07-07T11:58:52.946Z [localhost] ERROR! Failed to index documents.
[
 {
  "index": {
   "_index": "xxxx",
   "_type": "_doc",
   "_id": "6xxxxxxxxxxxxxxxxxxxxx3",
   "status": 400,
   "error": {
    "type": "illegal_argument_exception",
    "reason": "mapper [documents.toc.selectionRectangles.height] cannot be changed from type [long] to [float]"
   }
  }
 }
]
```

**Comment by konzz** [comment]
Closed in favour of #3755  and #3807
