### ISSUE TITLE
Request for a more detailed/comprehensive template conflict reindex message (1 pts)

### ISSUE THREAD

**Issue by natasha-todi** [huridocs/uwazi#3798]
Feedback from several partners is that if this type of message (attached below) shows up while making changes to the template, most users would not be sure of the implications of a reindex and/or template conflict or what it will do to their collection. 

<img width="669" alt="Screenshot 2021-07-08 at 11 16 35 AM" src="https://user-images.githubusercontent.com/60774708/124890375-9d103a00-dff5-11eb-9ed6-6cd9842a9b76.png">

**Comment by RafaPolit** [comment]
I agree.

**Comment by txau** [comment]
Moreover, the red coloring and warning style looks may discourage from running the reindex.

**Comment by natasha-todi** [comment]
Is there any way we can change or improve the message here soon? Multiple partners have reached out in the last few months mentioning that they stop making the changes they were going to due to not fully understanding what clicking save on this message will do.

**Comment by txau** [comment]
To be fixed along with: https://github.com/huridocs/uwazi/issues/4061

**Comment by konzz** [comment]
@nwyu We need the new copy of this message

**Comment by konzz** [comment]
Check that this text is translatable

**Comment by nwyu** [comment]
The new text:

> A reindex of your collection is necessary. The reason may vary -- from certain changes made to a template's property to new fields that need to be populated across entities. This process will not negatively affect the data in your collection. It can last a few minutes and some parts of your collection might take some time to reappear in the Library, but this is temporary. Do you want to continue?

**Comment by nwyu** [comment]
Replace the button text from "Accept" to "Confirm" and change the color to green.
