### ISSUE TITLE
Information Extraction Dashboard (7 pts)

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#3799]
For the feature extraction we need a dashboard to access each property that can be extracted. This section will be behind a feature toggle / configuration that for the MVP will be done manually in the DB and won't have a configuration panel. This configuration should include the template and which properties are being extracted.

This panel will only represent the metadata extraction configuration, buttons wont do anything for now, and will be implemented in consecutive issues.

Link to the [designs](https://www.figma.com/file/h3mhxBGiRctmF72HLf0qld/UWAZI---ML---information-extraction?node-id=1270%3A2824)

Next screenshot is just for estimation purposes and quick reference, for actual size of the elements, refer to the original designs in the link above
<img width="906" alt="Screenshot 2021-07-08 at 11 37 14" src="https://user-images.githubusercontent.com/948117/124901810-a2b05480-dfe2-11eb-8182-960143637eed.png">

**Comment by RafaPolit** [comment]
Do not include the buttons for this first iteration.
