### ISSUE TITLE
search input + enter always produces an error.....

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazi#380]

**Comment by txau** [comment]
@daneryl  This is not happening in dev server. Only in :4000. Maybe this needs some db views or elastic config to be deployed as well?

**Comment by daneryl** [comment]
The error was produces by the new multiselect stored on elastic as [value, value] and trying to do a search using a string.
Fixed by not using metadata fields to search, only the fullText of the document and the title, we need to solve this but its not that bad, as you can search by any metadata using filters, so close this for now ?

**Comment by txau** [comment]
Yes. I'm going to open another card for the backlog so we don't forget.
