### ISSUE TITLE
Mark Document Properties (17 pts)

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#3801]
⚠️ Depends on #3818 (done)

When editing an entity that has a document, we want to add the "mark" function, so users can select an area of a document to copy the contents and assign them to a property. This will also store the selected areas.

- This feature will support text, rich text and numeric properties and dates
- If the extracted value is not valid for the field (i.e a date) the field will be left blank.
- Only one selection per property.
- You should be able to remove a selection.
- Store the selection rectangles in the file along with the property  they represent
- This feature should only be active with the "Main" file

For a possible technical solution see this [repo](https://github.com/allenai/pawls) and the [demo](https://pawls.apps.allenai.org/)

Link to the [designs](https://www.figma.com/file/h3mhxBGiRctmF72HLf0qld/UWAZI---ML---information-extraction?node-id=1270%3A2824)

<img width="872" alt="Screenshot 2021-07-08 at 12 40 53" src="https://user-images.githubusercontent.com/948117/124909209-7a2c5880-dfea-11eb-8159-8ca36ba91bb6.png">

**Comment by Zasa-san** [comment]
- Alongside the selection and the property they represent, a timestamp with the timezone should also be stored in the file.
- If the property gets deleted from the template, it should also be deleted from the file.
