### ISSUE TITLE
Align active/inactive toggle for filters

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#381]
If a property is larger than the sidepanel, the string collapses with (...), but the multiselect width remains larger than the sidepanel.

![align](https://cloud.githubusercontent.com/assets/6364153/18089276/6532610a-6ebf-11e6-894b-6201b81195d5.png)

**Comment by txau** [comment]
@danicatalan it should not be dependent on the width of the text. Can you fix this?

**Comment by txau** [comment]
Closed in #403
