### ISSUE TITLE
Area Selection (20 pts)

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#3818]
See react-pdf-renderer [#5](https://github.com/huridocs/react-pdf-renderer/issues/5)

**Comment by gabriel-piles** [comment]
The area selection is not going to be implemented, instead the text selection is going to be improved.

Improvements:
- Update react-text-selection-handler library in Uwazi, use it from npm and adapt the usage to the new version
- Update pdfjs-dist to version  2.3.200 (newer versions make Uwazi crash)
- Use textLayerMode : 2 in pdfjs to improve PDF selection
