### ISSUE TITLE
Include number of hidden properties

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#382]
We moved the **Show all** button above the multiselect, but I think the user needs more feedback to visually see that there are more items hidden.

I think it would be great if we add a note with remaining properties, like:

![screenshot 2016-08-30 14 36 43](https://cloud.githubusercontent.com/assets/6364153/18089316/a16134b2-6ebf-11e6-9c9f-c966e4a7f0f1.png)

**Comment by txau** [comment]
More improvements:
- Position the "Show more" button to right side of the list.
- Change it for "N more..."
- Only displayed below when the list is collapsed, but both up and down when is uncollapsed.

**Comment by danicatalan** [comment]
- [ ] Search box aligned to left.
- [ ] Show more/show less only below the item list.
- [ ] Increase facet browsing label width.
- [ ] Fix Datepicker filter.
