### ISSUE TITLE
Tool tip for "no pages enabled for entity view" cut off

### ISSUE THREAD

**Issue by llfinch** [huridocs/uwazi#3823]
When editing the metadata of a template, there is text just under the template name (when applicable) that reads: "There are no pages enabled for entity view" followed by an icon indicating a tool tip. Unfortunately, when you hover for the tool tip, you are only able to see half of it (and it crucially cuts off just at the "moment of truth" where it's about to give you the meat of the advice) because it seems to fall behind the first property tile (in this case, Title). 

![imagen](https://user-images.githubusercontent.com/56080527/126485865-cad4a005-5b5d-480f-805f-96b93c91e480.png)

For what it's worth, I'm using Firefox and the issue remains no matter if I use my small laptop screen or my external wider monitor.

**Comment by llfinch** [comment]
As a follow-up, there's also a problem with the tool tip's location when you toggle on entity view, in that it becomes hidden behind the first property tile and also the toggle switch: 

![imagen](https://user-images.githubusercontent.com/56080527/126486387-c286ca77-816b-4d13-bfff-a9a48403157f.png)

**Comment by grafitto** [comment]
This issue has been fixed by https://github.com/huridocs/uwazi/pull/3870 

Closing
