### ISSUE TITLE
Migration to add missing system keys (5 pts)

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#3836]
- There are many system keys that are missing. Link to the [key terms to add](https://docs.google.com/spreadsheets/d/1hmavcpjurCJLAfzOrVuohciA2Ix8HwABPjlgKMI7lvM/edit?usp=sharing).
 - This will enable us to pass the csv file to translate these terms quickly, rather than rely singly on the "live translation" button so that we can translate this text.
- Update blank-state

**Comment by LaszloKecskes** [comment]
As discussed: as part of the QA, it is necessary to look for feedback from the product team about the actual system keys we want to input, and modify the system_keys.csv accordingly.
