### ISSUE TITLE
Satellite view for maps. (8 pts)

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#3838]
Usecases:
👩‍💻 **Investigator** - As a human rights investigator conducting research on penal facilities, I want to be able to display the location of each penal facility on a satellite map in Uwazi in order to enable my team to explore the terrain, buildings and any surrounding structures to further complement and strengthen my investigation. 

👨‍💻 **End User** - As an end user viewing a database on  penal facilities, I want to be able to see each penal facility’s geolocation on a satellite map that is dynamic because I can then co-relate information around conditions in the facility and the different places mentioned in interviews and drawings such as interrogation rooms, sleeping quarters, kitchen areas etc to the actual satellite image. 

<img width="662" alt="Screenshot 2021-07-27 at 10 21 33" src="https://user-images.githubusercontent.com/948117/127121448-bfaf0416-e92e-4a47-8261-49f906c39eeb.png">
(just a random image of somewhere in the world)

👨‍🔧 Technical details:
Uwazi maps have a street style view, that is defined by the [app/react/Map/style.json](https://github.com/huridocs/uwazi/blob/development/app/react/Map/style.json) file. We want to add a button to switch between street and satelite view that updates the map style.
For the button implementation you may use react-map-gl [MapControll](https://visgl.github.io/react-map-gl/docs/api-reference/map-controller), for the style check with @RafaPolit

⚠️ 
- We may need to update react-map-gl to use a new style.
- If we update, our previous style may not be compatible and we will need to define a new one.

**Comment by txau** [comment]
For this particular use case, wouldn't it be enough to use different map services and take a screenshot of the satellite view of the area? Keep in mind that each service may have a different satellite tile collection with better resolution, more up-to-date tiles, etc. Maybe GMaps or other paid services have better satellite tiles than OSM.

**Comment by natasha-todi** [comment]
@txau in this particular use case, the purpose of proposing satellite view is to allow the investigator as well as the end user to interact with the actual map and zoom in to examine particular parts of the prison facility like where interviewees have mentioned they were interrogated, or the sleeping quarters etc or zoom out to see the surrounding topography and buildings to gain more insight on the facility itself. In this use case, the partner is also going to supplement each prison facility entity with conditions in the facility as well blueprint drawings of the inside to label the different sections.
