### ISSUE TITLE
UI terms "public entities" and "private entities" missing from Translations-->User Interface list

### ISSUE THREAD

**Issue by llfinch** [huridocs/uwazi#3841]
It seems that sometime recently, the terms for the two sides of an Uwazi library were renamed from "Public documents" and "Private documents" to "Public entities" and "Private entities". 

![imagen](https://user-images.githubusercontent.com/56080527/127160620-07e7f3ce-8e89-40a3-8117-bb66b16e3a89.png)

But it seems that this change wasn't also made in the list of UI terms in Settings-->Translations-->User Interface. "Public entities" and "Private entities" do not appear, meaning I as a user have no way to translate them there. (I can still translate them "live" however by toggling on the translation icon in the menu.) 

However, "Public documents" and "Private documents" are still in the list of Settings-->Translations-->User Interface.

![imagen](https://user-images.githubusercontent.com/56080527/127161761-243a4e6e-fde7-4f8a-b9da-ddf2d7bbfeff.png)

**Comment by nwyu** [comment]
Related to #3836.

**Comment by RafaPolit** [comment]
These two are being removed, as the former "uploads" section is being merged into the library.
