### ISSUE TITLE
Topic classification suggestions not showing in UWAZI

### ISSUE THREAD

**Issue by gabriel-piles** [huridocs/uwazi#3846]
For the instances with topic classification activated, when there is suggestions in the entities collection like

    "suggestedMetadata": {
        "issues": [{
            "value": "3d7eb25c-ff23-4835-bbdf-6bebdd115e63",
            "label": "International instruments",
            "suggestion_confidence": 0.91,
            "suggestion_model": "1575275219"
        }],

, those suggestions should be displayed in UWAZI in the thesauris settings

![Screenshot from 2021-08-02 12-37-26](https://user-images.githubusercontent.com/22240564/127848848-49146609-71e2-4f8b-868b-cd50524cc3c2.png)

but it is not the case.

**Comment by LaszloKecskes** [comment]
It looks like that the topicClassification feature toggle in settings also impacts elasticsearch indexing for this part. That is:

- 'yarn reindex' without the feature toggle results in no values (i.e. the behavior described in the issue)
- 'yarn reindex' with the feature toggle results in properly found values

**Comment by LaszloKecskes** [comment]
As discussed, the solution will be to make the indexing also be dependent on the 'enable classification' bool on the dictionaries: i.e. if there is at least one enabled, include this feature in the indexing. Manually triggering a re-indexing will still be necessary.
