### ISSUE TITLE
README instructions are pointing to generic links

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#3872]
A recent edit to the REAMDE.MD file replaced the download instructions for Elasticsearch with a generic download link, which does not coincide with version requested as soon as new versions are released.

We should replace with the specific version download link instead of the generic one that points the the newest version.

This should be the link for Elastic 7.10: https://www.elastic.co/downloads/past-releases/elasticsearch-7-10-0

**Comment by RhnSharma** [comment]
I would like to take this one.
