### ISSUE TITLE
Some migrated translation labels are not translatable at UI

### ISSUE THREAD

**Issue by mfacar** [huridocs/uwazi#3874]
With  #3836 we added some keys into the system context translations, however, the following keys from the imported ones are not being translated at the UI.

|key | location|
|--- | ---|
|Add   people or groups | Share entities popup|
|Administrators and Editors | Share entities popup|
|HELP | TEXT on rich text field|
|PREVIEW | TEXT on rich text field|
|EDIT | TEXT on rich text field|
|Search (not main search but on   Copy From screen) | Not using the 'Search' translated term|
|Action | TEXT on Tools > Activity Log|
|Time | TEXT on Tools > Activity Log|
|Find | TEXT on Tools > Activity Log|
|Description | TEXT on Tools > Activity Log|
|Uwazi UI | BUTTON on Settings > Translations|
|Select... | TEXT|
|You should activate this feature for enhanced account security | TEXT on Settings > Account|
|This option will show a   notification about the use of cookies in your instance. | TEXT on Settings > Collection|
|Month, Day, Year 09-18-2020 | TEXT on Settings > Collection|
|landing page description | |

Additionally, the following keys are shown as a unique label in the UI, but at code level are composed of several html elements.

|key | 
|---|
|ProTip!   Use cmd or shift  + click to select multiple files.|
|Copy properties to this entity   from:|
|Enable this page to be used as   an entity view page:|
|Browse your PDFs to upload or   drop your files here.|
|ProTip! For better   performance, upload your documents in batches of 50 or less.|

**Comment by daneryl** [comment]
@konzz bump!

**Comment by konzz** [comment]
Probably most or all of the cases reported here were fixed in the PR that added the automated check, since I fixed arround 200+ labels. Still some texts that are contained in a variable may not be translatable with the inline tool or may not be in the context. Probably we want to close this issue and find a different approach to those edge cases.
