### ISSUE TITLE
Metadata keys 'clean' their label with underscore when special characters are used which loses semantics

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#388]
When I select as the label for a field a name with a special character like: "País", the key for the metadata property is registered as "pa_s" (replacing the acuted i with an underscore), which is very hard to read or understand (as well as throw eslinting errors that 'camel case has not been observed' for naming conventions).

Perhaps for 'obvious' foreign characters like: á, ñ, ü, ê, etc, the basic guarism could be used?

**Comment by txau** [comment]
We definitely need safe name generation for the DB.

**Comment by RafaPolit** [comment]
Maybe work on #751 addressed this already? @daneryl

**Comment by kjantin** [comment]
According to @daneryl this is not yet fixed, but it's low priority.

**Comment by txau** [comment]
@RafaPolit I've been running some tests:
1. I removed the sanitize function (replacement with underscores) before saving to db.
2. I created entities, thesauri, thesauri values, properties and property values with unsafe chars (ie: ëntíty "something |\ ', 'Testing öîùá Çá'.
3. I tested that searching, filtering, creating entities, etc worked.

I think our stack (including database, elasticsearch, react, etc) supports this and is automatically sanitizing dangerous chars such as " ' \. So, why replacing with _ when its semantically easier for anyone to have the actual field name as the user entered it?

**Comment by daneryl** [comment]
@txau i think we should test more edge cases but if it works, yeah why not.

**Comment by RafaPolit** [comment]
One important thing is that, with that approach: Pais, país, and pais would be considered 3 different metadata names for filtering and other grouping concepts.  So we need some sort of sanitizing.

**Comment by txau** [comment]
After some debate, this is not having any negative impact in the project. It is true that there is a slight loose in semantics, but it doesn't really affect users or developers. Not fixing.
