### ISSUE TITLE
Terribly slow instance

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#3886]
On ihrda.uwazi.io try to text search for "African Charter" and open the document "African Charter on Humans and People's Rights". The whole process is extremely slow.

This instance is known to have hundreds of text references for some documents.

**Comment by LaszloKecskes** [comment]
One possible issue for the search is that it sends two requests to the search api (`app/api/search/search.js`, set through the file `app/api/search/deprecatedRoutes.js`), one without geolocation, one with.
Example calls:
Without geolocation:
```
{
  allAggregations: false,
  filters: {},
  from: 0,
  includeUnpublished: false,
  limit: 30,
  order: 'asc',
  searchTerm: 'African',
  sort: '_score',
  unpublished: false,
  aggregateGeneratedToc: true,
  include: [ 'permissions' ]
}
```
With geolocation:
```
{
  allAggregations: false,
  filters: {},
  from: 0,
  includeUnpublished: false,
  limit: 30,
  order: 'asc',
  searchTerm: 'African',
  sort: '_score',
  unpublished: false,
  aggregateGeneratedToc: true,
  geolocation: true,
  include: [ 'permissions' ]
}
```
The second call takes 10-15 times more time than the first, and returns no results with geolocation.

**Comment by LaszloKecskes** [comment]
On opening the document, the core issue is that the document in question has 6000+ text references. If entities might have this (or even larger amount) of references/relationships, that is going to strain the browser even if everything is optimal. We might need a workaround for these cases in the long term.

Specifically in this case we found three bottlenecks:
1, Immutable -> toJS for large amount of references, when dispatching library.sidepanel.references/SET to the store might take single digit seconds ([here](https://github.com/huridocs/uwazi/blob/cedae1cf2109054bc2b6fa5e2cafc6f6118ffcba/app/react/BasicReducer/reducer.js#L21)).
2, During rendering the sidepanel after the click, it arranges the references and reaches a [parseReferences](https://github.com/huridocs/uwazi/blob/cedae1cf2109054bc2b6fa5e2cafc6f6118ffcba/app/react/Viewer/selectors.js#L13) function, which is takes somewhere between 30-60 seconds. The current algorithm might have O(n^2) running time worst case, scales badly.
3, When actually rendering the references, react tries to render all 6000+ nodes, it goes slowly, and in my case can actually cause the browser break, depending on available memory.

**Comment by txau** [comment]
@LaszloKecskes in this particular instance the library is also super slow, but the text references are not being loaded in the library. Do you have any idea how the vast amount of text references is related with the slowness of library?

**Comment by LaszloKecskes** [comment]
Split into #3897 and #3898.

**Comment by LaszloKecskes** [comment]
Closing, since it was split up.
