### ISSUE TITLE
validation errors on saving autogenerated TOC

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazi#3887]
> I went through the process of reviewing the TOC and trying to mark it as reviewed and got two errors:
> 
> * After adding one element to the TOC, I tried to add another element and got the infamous error "blablabla selection rectangles is empty"
> * After finishing and saving the TOC, trying to mark as reviewed gave the validation error.

**Comment by txau** [comment]
This may have been fixed along with some other selection rectangles fixes. It is difficult to tell since there are no specific entities reported. Closing for now.
