### ISSUE TITLE
Problems with TOC (and probably other text references/selections) changing PDF rendering in view

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#389]
There are certain types of PDFs that, if you add a TOC and save the TOC, this procedure changes the view of the document:
Selecting TEXT:
![screenshot from 2016-08-31 17-41-00](https://cloud.githubusercontent.com/assets/4309019/18148885/265ea216-6fa2-11e6-88b1-7e01be560638.png)
After hitting Save:
![screenshot from 2016-08-31 17-41-08](https://cloud.githubusercontent.com/assets/4309019/18148898/35b4ac24-6fa2-11e6-9d34-1a9b4432e121.png)

This is the PDF for testing:
[98065.pdf](https://github.com/huridocs/uwazi/files/448412/98065.pdf)

**Comment by daneryl** [comment]
fixed by #392
