### ISSUE TITLE
Slow text search ( 5 pts)

### ISSUE THREAD

**Issue by LaszloKecskes** [huridocs/uwazi#3897]
Split from #3886.

On ihrda.uwazi.io, the text search for "African Charter" is slow.
One possible issue is that it sends two requests to the search api (`app/api/search/search.js`, set through the file `app/api/search/deprecatedRoutes.js`), one without geolocation, one with.
Example calls:
Without geolocation:
```
{
  allAggregations: false,
  filters: {},
  from: 0,
  includeUnpublished: false,
  limit: 30,
  order: 'asc',
  searchTerm: 'African',
  sort: '_score',
  unpublished: false,
  aggregateGeneratedToc: true,
  include: [ 'permissions' ]
}
```
With geolocation:
```
{
  allAggregations: false,
  filters: {},
  from: 0,
  includeUnpublished: false,
  limit: 30,
  order: 'asc',
  searchTerm: 'African',
  sort: '_score',
  unpublished: false,
  aggregateGeneratedToc: true,
  geolocation: true,
  include: [ 'permissions' ]
}
```
The second call takes 10-15 times more time than the first, and returns no results with geolocation.

**Comment by konzz** [comment]
There are three problems:
1. The geolocation query is slow.
2. The geolocation query is not always needed
3. When needed we don't need all the data in the library just the number.

Posible solutions:
- Investigate further on why the query is low and fix it.
- Do a different endpoint for the library that only returns the number.
- Remove the query when not needed ( no geolocation in the templates )
- Remove the number from the library.

**Comment by daneryl** [comment]
Apart from this one we want to actually debug the query and make it fast for instances that actually need it. https://github.com/huridocs/uwazi/issues/3934
