### ISSUE TITLE
Missing property creationDate on templates.

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#3900]
[Added support for date modified field on cards #3346](https://github.com/huridocs/uwazi/pull/3346) introduced the common property "editDate". This property was added to every entity with a migration, and new templates have it, but it was not added to existing templates.

Tasks:
- Migration to add editDate to all existing templates without it.

**Comment by daneryl** [comment]
the previous issue did not introduce "creationDate", it introduced "editDate", @konzz how important this is in your opinion ?

**Comment by fnocetti** [comment]
@konzz we think you meant editDate here. Can you check and take care of @daneryl 's comment? Thanks
