### ISSUE TITLE
Date fields CSSs glitch

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#3903]
@daneryl edited:
![css_glitch](https://user-images.githubusercontent.com/1386423/132547850-4691fb6a-a998-4ded-b506-4ce76c0474f3.jpg)

**Comment by daneryl** [comment]
![css_glitch](https://user-images.githubusercontent.com/1386423/132547784-050e9cc7-3ed1-4028-9173-c2bc101d2943.jpg)
