### ISSUE TITLE
Migration to delete orphaned connections (5 points)

### ISSUE THREAD

**Issue by mfacar** [huridocs/uwazi#3906]
Dependant of #3905 

Create a migration to remove inconsistent connections coming from errors at entity deletion. 

Related with #3755

**Comment by daneryl** [comment]
We are not going to wait on #3905, lets do the migration to clean up the error log.

**Comment by konzz** [comment]
- Delete orphan entities
- Check remaining connections in the hub
- If only 1 connection remain in the hub, delete that connection too
