### ISSUE TITLE
Geolocation search query is very slow [timeboxed 1 day]

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazi#3934]
Debug geolocation bottleneck, that apparently happens also when the number of geolocation points is 0.

**Comment by konzz** [comment]
Coming from #3897

**Comment by Zasa-san** [comment]
Testing locally with a database that has one or more geolocation properties on 3 templates:
- queries with more geolocation results take more time than queries with less geolocation results.
- the culprit could be  https://github.com/huridocs/uwazi/blob/421a01d699f057d3c8e647838dab2f4f8b3c9c14/app/api/search/search.js#L150
- forcing non-geolocation queries to have the same 9999 limit made them equally slow.
