### ISSUE TITLE
Upgrade to Typescript 4.x

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#3941]
We are currently using the latest 3.x version of typescript, yet 4.x should not be too much effort.

I did a quick try and there are more or less ~50 type errors.  Most of which are the typing of the `err` argument received by the `catch(err)`.  This will require some research, as Typescript does not support annotations in the catch variable. There are some suggested patterns around this, but it was not straightforward.

**Comment by fnocetti** [comment]
We are currently in version 5.x
Closing
