### ISSUE TITLE
Improve CSS for printing (5 pts)

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#3944]
On pages and entity metadata, the result of control+P could be improved in our default CSSs.

**Comment by konzz** [comment]
Requirements detected but may not be all:
- Hide all menu elements
- Hide footer
- Hide FABs
- Upload attachment form
<img width="442" alt="Screenshot 2021-11-16 at 09 29 19" src="https://user-images.githubusercontent.com/948117/141949663-c5c1cb64-ab11-4e7e-a7d9-418753d2c12b.png">
<img width="443" alt="Screenshot 2021-11-16 at 09 31 42" src="https://user-images.githubusercontent.com/948117/141949639-bf6d06d8-4376-4b57-a150-cafcd4b9892c.png">
