### ISSUE TITLE
Pages

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#395]
- [x] Have a section in admin where users can configure pages.
- [x] Pages have: title and markdown text.
- [x] Pages show the static URL link.

**Comment by danicatalan** [comment]
Pages admin:
![screenshot 2016-09-06 17 48 19](https://cloud.githubusercontent.com/assets/6364153/18282453/761eb214-7461-11e6-9ca3-673bdc808504.png)

Blank state:
![screenshot 2016-09-06 18 40 15](https://cloud.githubusercontent.com/assets/6364153/18282452/76150b38-7461-11e6-8dee-4a8e6e4e02c7.png)

If users save the page, an info-box appears with the static URL:
![screenshot 2016-09-06 18 36 33](https://cloud.githubusercontent.com/assets/6364153/18282454/762304ae-7461-11e6-9fa4-c2d57307067e.png)

Users can change from Edit to Preview mode inside the editor:
![screenshot 2016-09-06 18 34 32](https://cloud.githubusercontent.com/assets/6364153/18282451/7613451e-7461-11e6-8698-75665f3490a7.png)

**Comment by txau** [comment]
@danicatalan I guess we need to create also the design of the page as displayed publicly =)

**Comment by RafaPolit** [comment]
Functionality to create, edit and delete pages is finished.  Still need to go through the 'page view' routes and components, and test some of the implementation.

**Comment by RafaPolit** [comment]
This is done from the DEV perspective.
Pages displayed publicly have been inserted inside a basic container, no formatting.
Passing on to UX to @danicatalan .
