### ISSUE TITLE
Add language entity validation may result in inconsistent data.

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#3955]
When we add a new language to Uwazi, we make a copy of all the entities, and save them with the new language, in this process we validate the entities, an scenario may happen that you have added a required property in a template after already having some entities, making the validation to fail, and that entity, and all subsequent entities (valid or not) to not be copied to the new language.

<img width="873" alt="Screenshot 2021-10-06 at 15 55 49" src="https://user-images.githubusercontent.com/948117/136217167-9336f614-6e6b-4225-b629-7f6b82c04255.png">

**Comment by RafaPolit** [comment]
The options on how to tackle this will be discussed in the tech call.

**Comment by RafaPolit** [comment]
The process should be as follows:
- language creation should not use the entities model, it should duplicate entities with the `db.collection` methods as is done with the sync.  This avoids any checks that we don't need to happen ONLY on language creation
- create a script that assesses the extent of this bug in our collections: how many instances have irregularities in different languages
- create a migration that sanitizes this scenario: fetch ALL shared IDs in the collection, and, for those that don't have one entity per language, duplicate the existing one into the other languages.  Do NOT assume that any language is the master language.  The missing entity could be in any language, including the default language.

**Comment by RafaPolit** [comment]
Created individual issues for each part. Closing this.
