### ISSUE TITLE
Navigation menu

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#396]
- [ ] User can configure navigation menus from settings.
- [ ] Menus have a URL and a title.
- [ ] Menus can be ordered to control appearance.

**Comment by danicatalan** [comment]
First iteration with positioned elements on mobile and desk. We need to improve the styling.

![screenshot 2016-09-08 16 55 09](https://cloud.githubusercontent.com/assets/6364153/18354247/228603a2-75e5-11e6-94ff-fac65a5180af.png)
![screenshot 2016-09-08 16 55 15](https://cloud.githubusercontent.com/assets/6364153/18354245/227dbeb8-75e5-11e6-870f-101c6eeb4de4.png)
![screenshot 2016-09-08 16 55 26](https://cloud.githubusercontent.com/assets/6364153/18354246/227e92e8-75e5-11e6-84f6-13bdf544af2a.png)
![screenshot 2016-09-08 16 55 36](https://cloud.githubusercontent.com/assets/6364153/18354248/228c1af8-75e5-11e6-80cc-451e18fdcd05.png)

**Comment by danicatalan** [comment]
Functional menu with tab styles (related to #354).

![screenshot 2016-09-09 20 30 29](https://cloud.githubusercontent.com/assets/6364153/18398287/6995383e-76cc-11e6-8cb1-2cf18ce242cc.png)
![screenshot 2016-09-09 20 31 06](https://cloud.githubusercontent.com/assets/6364153/18398286/6988af38-76cc-11e6-954f-e435ef54461c.png)
