### ISSUE TITLE
Library: Load More loads next 12 and then no more cards are able to be loaded

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#398]
When I go to the library I read:
12 of 49 documents

If I scroll down and select 'load more' the next 12 documents are loaded at which point the top count gets replaced with "24 documents" and I cannot load any more documents.

**Comment by txau** [comment]
The list also breaks when you sort the list (A-Z, Recent). This bug was probably introduced with the faceted browsing.

**Comment by daneryl** [comment]
fixed by #412
