### ISSUE TITLE
Reindex triggered when changing image fit/fill (3 pts)

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#3980]
This is one of the cases when reindex is not supposed to be triggered. Review also other image params.

**Comment by Zasa-san** [comment]
This seems to be covered by #3769, when it implements:
https://github.com/huridocs/uwazi/blob/421a01d699f057d3c8e647838dab2f4f8b3c9c14/app/api/templates/reindex.js#L3
Here it covers actions related to property's styles. 

Changing any option of an image properties does not trigger reindexes by `reindexEntitiesByTemplate`

**Comment by txau** [comment]
@Zasa-san you are right. I've been tracking the execution and the problem is not the reindex but updating all entities with relationships. It seems to me that we optimized the reindex to be triggered only when needed, but we are lacking a similar approach for the entities stored in mongo. 

So at the end of the day, changing an image fit/fill that is supposed to only affect the template re-saves all entities without any change in them =(

I'm going to close for now since this is going to be addressed in the data layer redesign.
