### ISSUE TITLE
Request from partner to be able to order templates alphabetically (3 pts)

### ISSUE THREAD

**Issue by hyebin-bina** [huridocs/uwazi#3997]
Partner asked if it is possible to organize their templates alphabetically as they do with the thesauri list.

**Comment by konzz** [comment]
Sort templates alphabetically in Settings > Templates like Settings > Thesauris

**Comment by konzz** [comment]
yes that's the idea

**Comment by RafaPolit** [comment]
This needs to be sorted based on TRANSLATED values, so there is an added layer of complexity as to how to achieve this.
