### ISSUE TITLE
Test code review: replace switch statements with object literals

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#4]
@daneryl @konzz 

Testing how we can use issues for code review. So far I'm not happy with the inline comments (blame). Github's interface for this sucks big time. Comments get lost, there is no way of tracking what conversations are active etc. The official suggestion is to use pull requests, which I think is a total overkill unless you are conducting a full code review.

Code style suggestion, replace switch statements with object literals: https://toddmotto.com/deprecating-the-switch-statement-for-object-literals.

https://github.com/huridocs/UwaziDocs/blob/9fcc2009263a36f4885b0e0bcc7bd70dfef2c973/app/react/Templates/components/FilterSuggestions.js
```
getTypeIcon(type) {
    let icon;
    switch (type) {
    case 'checkbox':
      icon = 'fa fa-check-square-o';
      break;
    case 'select':
      icon = 'fa fa-sort';
      break;
    case 'list':
      icon = 'fa fa-list';
      break;
    case 'date':
      icon = 'fa fa-calendar';
      break;
    default:
      icon = 'fa fa-font';
    }

    return icon;
  }
```

**Comment by konzz** [comment]
Fixed with #81
