### ISSUE TITLE
Have search in the uploads section same as in the library

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#40]

**Comment by RafaPolit** [comment]
- Uploads should not be 'uploads', but a 'my unpublished documents', 'private data', 'staging area'
- Documents in uploads can be 'shared' with others (for viewing and/or editing?)
- Uploads box is not ideal
- "+" (new entity) button is not ideal, and not intuitive at all

**Comment by danicatalan** [comment]
Move this issue to the **Bulk upload** milestone.

I'm going to write the user story to focus this tag:

_"As a user, I want to search and filter my documents on **Uploads**  the same way I do in **Library**"_

- [ ] Bring the search and filters to the Uploads section.
- [ ] Bring the Sort-by functionality to Uploads section.

All the other notes inside this issue must be discussed in other treads to focus our development on concrete things.

**Comment by txau** [comment]
@danicatalan @kjantin @RafaPolit the problem with having full search and filter as in library is that most of the documents you have in you inbox don't even have metadata. What about a smaller brother of the full feature?

- Full text search
- Filter by template type
- Ordering (title and date added)

**Comment by konzz** [comment]
To be done in #887
