### ISSUE TITLE
Maps - Zoom In and Out buttons (3 pts)

### ISSUE THREAD

**Issue by salvalacruz** [huridocs/uwazi#4004]
Maps do not display the **+** (Zoom In) and **-** (Zoom out) buttons, neither on the overview map or on when creating or editing entities (with geolocation properties).

**Comment by nwyu** [comment]
@salvalacruz Could you add `showControls="true"` to your map component code and confirm whether it adds the zoom buttons to your map?

**Comment by salvalacruz** [comment]
I mean, the zoom in and out buttons does not apear in:
- Map views, in the main screen.
- Creating or editing entities, with geolocation property.
- Submission forms.

**Comment by daneryl** [comment]
On the main library map there are zoom buttons and work properly.
You can still zoom in with double click and Zoom out with control+double click on the other maps.
On the short term we could add this description to the help hover the map has on the bottom left, although this option is a little bit obscure its better to have the buttons back.

**Comment by daneryl** [comment]
Confirm that the library has some zoom default buttons, just enable them for the views that are missing them.

**Comment by salvalacruz** [comment]
Hello, sorry, I've just realized that Zoom In and Out buttons are available in maps when you enter to an entity view, but NOT in the main screen, when you filter the Collection and use map view:

![image](https://user-images.githubusercontent.com/73410334/154344620-accde735-e467-4dc0-abcd-0b1a58788264.png)

**Comment by txau** [comment]
@salvalacruz in the main screen zoom +/- is mapped to Uwazi's magnifying glass buttons instead of the buttons you see in the entity view. We may need to address this UI inconsistency but the buttons are there.

**Comment by salvalacruz** [comment]
It's true @txau , sorry, it's just a different look and I did not realize.
