### ISSUE TITLE
Custom entity pages should start with sidepanel closed (3 pts)

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#4013]
When entering a entity view page that has been configured with custom page, the side panel should be closed by default.
Update the button's icon that opens the side panel as well.

**Comment by juanmnl** [comment]
[This "columns" icon was chosen](https://fontawesome.com/v5.15/icons/columns?style=solid) to replace the chart icon on custom entity pages.

ie.
![action](https://user-images.githubusercontent.com/699945/143038692-897f0cfd-651e-4abf-a0c6-a2ac12580270.png)
