### ISSUE TITLE
Fix the delete button on custom uploads

### ISSUE THREAD

**Issue by grafitto** [huridocs/uwazi#4022]
Fix the delete button on the custom uploads. 
![image](https://user-images.githubusercontent.com/8601175/141481269-10391a12-4e4d-436c-b0b2-ed69aacc8256.png)

**Comment by salvalacruz** [comment]
Hi, right now, in any instance I try, the URL of the files in Custom Uploads can not be red properly: 

![image](https://user-images.githubusercontent.com/73410334/152372705-a9b21233-bd2c-401b-9f1d-e22ad42625cd.png)
