### ISSUE TITLE
Decide what to do with Attachments and File in Copy From flow

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#4024]
With the addition of "attachments" (and eventually File section) to the EDIT form, the Copy From flow needs to address this new possibility: do we copy the attachments and file? Do we provide options to decide to copy or not? Do we intentionally PREVENT the copying of files?

The decision also extends to Image properties: if you copy-from an image property, that value is pointing to an attachment on "the other" entity.  Should that also copy the attachment? Should that point to the "other entity's attachment"? Should it not get copied at all?

**Comment by RafaPolit** [comment]
cc @nwyu @txau @juanmnl

**Comment by txau** [comment]
Difficult to decide without knowing how this is affecting users. I suggest we go for the cheapest approach for now and address it later if it doesn't result.

**Comment by Zasa-san** [comment]
For now it's been decided that files (supporting files, and media and image fields) will be ignored by copy from until we have a good solution that avoids file duplication and entities breaking due to one entity depending on the supporting files of another.
