### ISSUE TITLE
Inconsistent misalignment of template aggregate in filters sidebar 

### ISSUE THREAD

**Issue by llfinch** [huridocs/uwazi#4027]
The total count of the first primary filter in the Library's filters sidebar seems to be experiencing some misalignment, but inconsistently so: at 80% zoom and 100% zoom on my browser (Firefox from my 14-inch laptop), it's misaligned: indented way to the left. But at 90% and 110% zoom, the alignment becomes correct. 
<img width="367" alt="80 percent" src="https://user-images.githubusercontent.com/56080527/141780040-458dda75-5f56-47f0-9783-b453b71d58d6.png">
<img width="384" alt="90 percent" src="https://user-images.githubusercontent.com/56080527/141780044-bf62c5c9-5241-4512-9a70-f1b20971d860.png">
<img width="370" alt="100 percent" src="https://user-images.githubusercontent.com/56080527/141780047-57ae515c-1790-4ad3-af3b-7a9008882414.png">
<img width="383" alt="110 percent" src="https://user-images.githubusercontent.com/56080527/141780049-88182122-3c9c-4994-94a5-2963f01fd3a9.png">

**Comment by RafaPolit** [comment]
I cannot replicate this on Chrome.  Resizing the zoom is done by the browser.  If things are working correctly at 100%, I'm not sure we can do a lot here.

**Comment by txau** [comment]
I managed to replicate on Firefox playing with different view port sizes and zoom levels. It is difficult to trigger it and it doesn't have a big impact. It is a CSS issue caused by the recently added toggle for "Featured/all" eventually colliding with the next element of the ul > li.
