### ISSUE TITLE
HandleError request ID can fail due to no async context

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#4032]
Function `handleError` in `handleError` could fail in request id due to async context failing, in which case it's only throwing only the missing context without the original error.

cc @daneryl to please further explain this

**Comment by daneryl** [comment]
@RafaPolit i think the info you gave is enough, but maybe we can extend this to any possible error that handleError can throw a part of the error being handled with the same strategy that we already implemented for the error reporing.

https://github.com/huridocs/uwazi/blob/109cd29aae9732f05ade623a7dd0e068784754cd/app/api/log/infoFormat.ts#L6-L18

which basically reports the error being handled and the potential error in the implementation itself.

**Comment by daneryl** [comment]
> but maybe we can extend this to any possible error that handleError

This is not needed, this kind of errors happen very rarely and they should be tested, the request context should be the focus here.
