### ISSUE TITLE
Yarn hot cannot find module rsmq

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#4038]
```
[nodemon] starting `node --max-http-header-size 20000 ./server.js`
[11:47:07 PM] Starting compilation in watch mode...

internal/modules/cjs/loader.js:1083
  throw err;
  ^

Error: Cannot find module 'rsmq'
Require stack:
```

**Comment by RafaPolit** [comment]
Maybe an obvious question, did you try `yarn install`?  Maybe something got corrupted in the node_modules? Remove them and yarn install again?

**Comment by txau** [comment]
@RafaPolit I did, but apparently something went wrong during yarn install. It is working now.
