### ISSUE TITLE
Issue when switching the map style while editing a geolocation property (3 pts)

### ISSUE THREAD

**Issue by natasha-todi** [huridocs/uwazi#4043]
When creating/editing a geolocation property within any given template in Uwazi, **the pin moves on its own accord to another location** when a user clicks on switch map style. Refer to this [video](https://drive.google.com/file/d/1hvTqH0Q_Yejzm6yFXms2eduvQuSTa2bW/view?usp=sharing) for reference.

**Comment by RafaPolit** [comment]
It looks like the button to change the map style is not cancelling the bubble-up of events of map-click.  We should look into this.
