### ISSUE TITLE
API allows to save relationships with non-existent relationship id

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#4044]
Via API call, one can create relationships where the relationship id doesn't exist. This scenario is mainly plausible when directly manipulation the API rather than via the UI, still a race condition could allow users to also trigger this behavior via the UI.

**Comment by LaszloKecskes** [comment]
Will be solved in relationships v2.

**Comment by txau** [comment]
@LaszloKecskes I we can close it then
