### ISSUE TITLE
Creating an Entity with Multiselect when entity is not first in the list is broken!

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#405]
Reproduction instructions:
- Create an entity template that has a multiselect
- Create another entity template that has a name that precedes the previous entity template
- Go to uploads and create an entity
- Change type to the multiselect-containing entity

There is an error:

```
warning.js:36 Warning: Failed propType: Invalid prop `value` of type `string` supplied to `MultiSelect`, expected `array`. Check the render method of `Control`.
```

And if you try to multiselect the options it does not work.  You need to save the entity and go back in order for the multiselect to work correctly.

**Comment by konzz** [comment]
Cant reproduce, probably already fixed
