### ISSUE TITLE
In attachments and other file uploads get mime types from client (5 pts)

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#4050]
Right now we are performing a server side request to get mime types of attachments. We need to change this to be based on client side so we don't allow arbitrary URL requests from Uwazi.

**Comment by txau** [comment]
If we trust the mime-type coming from the client, we also need to consider any potential security implications. Ie. can a force mime-type inject code to be executed somewhere?

**Comment by konzz** [comment]
A different solution is needed, CORS does not allow this.
