### ISSUE TITLE
Step by Step on Installing Uwazi

### ISSUE THREAD

**Issue by blesskn** [huridocs/uwazi#4055]
Good day. Can you kindly assist on the step by steps after installing all the dependencies. What is the next step? What are the steps to install Uwazi on my computer. I look forward to hearing from you.

**Comment by txau** [comment]
Hello @blesskn 

After installing all dependencies here: https://github.com/huridocs/uwazi#dependencies, you need to follow these instructions https://github.com/huridocs/uwazi#production so you end up connecting to  http://localhost:3000 and login with the credentials "admin" / "change this password now".

Those are step by step instructions for installing and running Uwazi.

Unless you have a specific question or error, I don't know how I can help you.

**Comment by blesskn** [comment]
Thank you for your response. Is it ok if I send you my domain cpanel details then you install Uwazi into the system so I can create my dayabase online in my domain server.

**Comment by txau** [comment]
Dear @blesskn I'm sorry but we can't assume that kind of task and responsibility. If you want to hire professional services please get in touch with our support team at support@uwazi.io.

As mentioned before, if you are not going to be able to maintain the server yourself including periodical updates, server hardening, backups, etc, I suggest you ask for a paid instance at support@uwazi.io. We offer affordable prices and spare you the trouble of maintaining a service.

**Comment by blesskn** [comment]
Thank you. I'm kindly asking for Uwazi to be installed direct into my domain cpanel then I work from there. My server is capable of everything. I just want to reach to the Uwazi platform then I can do my work online without working on localhost.

**Comment by blesskn** [comment]
Good day. I have sent emails to support but i'm not getting any response. Can you kindly quote me for 2 months to host Uwazi on your servers so that I can work online. Kindly assist.
