### ISSUE TITLE
CSV import composite issue (5 pts)

### ISSUE THREAD

**Issue by LaszloKecskes** [huridocs/uwazi#4059]
This is a composite issue that describes multiple bugs with the csv import process, which we decided to keep together since they involve the same part of the code.
The csv import is a two steps process. First, a pre-flight (csvLoader - arrangeThesauri) collects the new values from the select and multiselect fields, then the main loop after performs the actual entity import one-by-one.

Bug 1: Column Name Sanitization

In the pre-flight step, the function assumes that the csv column names are already safe property names (lowercase, underscore instead of spaces). This is not the case; the file could contain the raw label, or even different capitalization (Example Select Value, instead of example_select_value). This results in the new values not loaded in the thesauri, then the entity import fails at the first new value.
Solution: The pre-flight needs to sanitize the column names before matching to properties. The sanitization needs to be consistent with what already happens in properties, preferably through the same function.
With this bug, ping me (@LaszloKecskes ) for help about the pre-flight, if needed.

Steps to reproduce:

- create a thesauri
- create a select or a multiselect property with a label that will be different from the safe name
- try to import an entity with a new value, where the column uses the label

<del>Bug 2: Triplicate Imports</del>

<del>While testing the previous bug, for some people the entity import resulted in triplicate imports (i.e. the same set of entities imported three times).</del>
<del>I have not been able to reproduce the problem. @nwyu  reported this, and could supply more information.</del>

<del>Bug 3: #3764 - CSV import of nested thesaurus values fails</del>

<del>If you CSV import an entity with a select or multiselect with the value of a nested thesaurus item, the value appears on cards (denormalized?) but when you edit the entity, it doesn't show on the selectors.</del>

**Comment by nwyu** [comment]
Bug 2 is not currently reproducible. Unsure but it may have been due to poor/unstable connectivity from my side. Either way, bug 2 qis no longer occurring.
