### ISSUE TITLE
Log activity

### ISSUE THREAD

**Issue by salvalacruz** [huridocs/uwazi#4060]
I suggest to add these registers as actions in the log activity, for security reasons:

- Action "LOGIN", when a user enters to the instance.

- Action "LOGOUT" when a user exit.

- Action "EXPORT CSV" when a user saves filtered information to a CSV file (if it's posible, registering which information has exported).

**Comment by txau** [comment]
Not for the export csv thing and the other functionality is duplicated in #4185
