### ISSUE TITLE
Changing property type displays an error and dosesn't work

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#4061]
On a template with a text property named "A", without any entities in the database. Delete the property "A" and create a new one of the type numeric also named "A" and try to save. Gives an error.

If you first delete the property, then save, then create the new property, it works.

**Comment by txau** [comment]
![image](https://user-images.githubusercontent.com/489831/167449171-21a91277-b9af-4dbe-9ded-41c803151e7f.png)

**Comment by RafaPolit** [comment]
Frontend has been taken into a new issue.
