### ISSUE TITLE
Translating thesauri values does not change denormalized labels in entities (13 pts)

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#4062]
On a Uwazi with 2 or more languages.

1. Create a thesaurus
2. Add that thesaurus as the list for a multi-select property
3. Create an entity (thesaurus values and labels get denormalized)
4. Change the translation for one thesaurus item 
5. The entity still reflects the previous value both in the database and the UI

**Comment by txau** [comment]
Confirmed:
- On entity creation the translations are properly denormalized
- On thesaurus translations the label are not denormalized (not involving inheritance)
- If another entity is inheriting this thesaurus value, the label is not being denormalized either

**Comment by RafaPolit** [comment]
This requires a migration of existing data.
