### ISSUE TITLE
Testing Factory wrongly implements Thesaurus values

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#4066]
Currently, our test Factory system, when receiving a single value for `thesauri`, it is assigning that value to the `id` AND `label`.  This is prone to error when designing things, because you could use ID when you meant to use the LABEL (for example, for sorting) and not notice the problem.

This is a simple fix, but it breaks a lot of expects right now.

**Comment by txau** [comment]
@daneryl check if this was fixed during a mob programming session.

**Comment by daneryl** [comment]
this was solved by allowing to pass a tuple like value 

```
      values: values.map(value =>
        typeof value === 'string'
          ? { _id: idMapper(value), id: value, label: value }
          : { _id: idMapper(value[0]), id: value[0], label: value[1] }
      ),

```
