### ISSUE TITLE
Add link issue

### ISSUE THREAD

**Issue by AhmadQadi1** [huridocs/uwazi#4069]
Many users have problems in adding the links to the allocated field for links. When they fill in all fields and try to submit the link field reddens and the submission doesn't work.
![signal-2021-11-26-200742_001](https://user-images.githubusercontent.com/95572565/144746803-7cbf7718-218e-4059-bcc3-ca6a20a0f659.jpeg)

**Comment by txau** [comment]
@AhmadQadi1 a hunch: for some reason you are not seeing the "label" part of the link field (see the screenshot). I tried several resolutions to test if this was a mobile issue, and in every case the "label" input was always visible. So I wonder if the label field was hidden via CSS, in which case users can't add a label and the field won't validate. 

![image](https://user-images.githubusercontent.com/489831/144943626-a6f4caa6-c65e-49ba-a391-475be1763f1f.png)

PS. There is a related issue to not force labels in links: https://github.com/huridocs/uwazi/issues/3977

**Comment by AhmadQadi1** [comment]
> @AhmadQadi1 a hunch: for some reason you are not seeing the "label" part of the link field (see the screenshot). I tried several resolutions to test if this was a mobile issue, and in every case the "label" input was always visible. So I wonder if the label field was hidden via CSS, in which case users can't add a label and the field won't validate.
> 
> ![image](https://user-images.githubusercontent.com/489831/144943626-a6f4caa6-c65e-49ba-a391-475be1763f1f.png)
> 
> PS. There is a related issue to not force labels in links: #3977

Thank you for the clarification, it is really the case! Then what is the solution?

Thank you

**Comment by txau** [comment]
@AhmadQadi1 wait for https://github.com/huridocs/uwazi/issues/3977 to be fixed or you can go for a temporal patch with page's JS. If this is a public intake form, you can try to inject a default value to the hidden label field from JS. You can add the JS in the "Page Javascript" section.
