### ISSUE TITLE
Image and media happy paths

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#4071]
After #3494 and #3899 our image and media fields have improved the UX but they are far for complete. These 3 happy paths need to be fixed:

A. Display the recently uploaded content in the content selector
1. While in edit/creation mode for an entity add a new media in supporting files
2. Click the "Select supporting file" button
3. The newly created media does not appear in the available files.

B. Upload the supporting file in the dialog
1. While in edit/creation mode for an entity click on the "Select supporting files"
2. There is no option for uploading new content. There is an option for "Add from URL" but not for uploading.

C. Add directly to field
1. While in edit/creation mode for an entity there should be a button "Add file" that directly uploads the content and sets it as field value.

**Comment by konzz** [comment]
Point A requires some analysis to see how we can display the file thumbnail, it is not clear that we will have access or that we might need to use local storage.

**Comment by Zasa-san** [comment]
Point C is not going to be implemented, since it's redundant to have that many buttons to upload or select files.

Point B: will change the modal tab 'Add from URL' to 'Add new file', and in that tab we will have the form to add from URL and the button to add and select a new file.

**Comment by juanmnl** [comment]
After a quick chat with @mfacar and @txau, we decided to go with a "single screen modal" as the tabbed navigation didn't make a lot of sense. We're just adding the import options as a sub-header of the modal, with the files container underneath.

IE. (follow these patterns but with the currently available styles)

<img width="839" alt="supporting files - empty" src="https://user-images.githubusercontent.com/699945/160627816-52e18fee-5915-46f2-8269-037fd5c453ca.png">

<img width="839" alt="supporting files - content" src="https://user-images.githubusercontent.com/699945/160627826-f71ebc25-973a-4795-a29a-6a5ac2963b34.png">
