### ISSUE TITLE
Using filter first-day-last-month and last-day-last-month gives search_phase_execution_exception error 

### ISSUE THREAD

**Issue by daitj** [huridocs/uwazi#4079]
After some recent updates, I cannot say exactly which version as I was not aware of this error, I am getting. 

```
url: /api/search?filters=%7B%22initial_date%22%3A%7B%22from%22%3A%22first-day-last-month%22%2C%22to%22%3A%22last-day-last-month%22%7D%7D&limit=0&order=desc&sort=creationDate&types=%5B%226cb66d666eaf666bc6666bd3%22%5D&allAggregations=true&geolocation=true&include=%5B%22permissions%22%5D
query: {
 "filters": {
  "initial_date": {
   "from": "first-day-last-month",
   "to": "last-day-last-month"
  }
 },
 "limit": 0,
 "order": "desc",
 "sort": "creationDate",
 "types": [
  "6cb66d666eaf666bc6666bd3"
 ],
 "allAggregations": true,
 "geolocation": true,
 "include": [
  "permissions"
 ]
}
search_phase_execution_exception
```

The `inital_date` is a type date field.

It was used in a `<Database/>` tag, if I replace `initial_date.from` and `inital_date.to` with proper timestamp, it works normally.

**Comment by RafaPolit** [comment]
We need to look why this could have stopped working.

**Comment by RafaPolit** [comment]
@daitj The fix for this bug has been merged into the dev branch, and will probably be included in the upcoming release candidate, and one week afterwards the fix will be merged into the master branch after the testing phase.

Thanks for the report.
