### ISSUE TITLE
Issue when creating grouped primary filters 

### ISSUE THREAD

**Issue by natasha-todi** [huridocs/uwazi#4083]
Error message reported on separate instances when trying to create a new group in the filters settings. 
![Screenshot 2021-12-14 at 2 11 44 PM](https://user-images.githubusercontent.com/60774708/145961504-441badb0-694b-433e-a30f-cdf7b70a5b72.png)
![Screenshot 2021-12-14 at 2 12 24 PM](https://user-images.githubusercontent.com/60774708/145961522-b93aa961-cdd6-4f06-9fd9-e1fcdd444de6.png)

**Comment by txau** [comment]
@natasha-todi this is known bug that is going to be fixed soon: https://github.com/huridocs/uwazi/issues/3983
