### ISSUE TITLE
Enclosing the field name betwen [] chars causes some search problems  (5 pts)

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#4090]
A user reported a search error. I haven't been able to replicate the error but this path causes the search not to work for properties enclosed in []:

(on firefox)
1. Rename a template property from "something" to "[something]". Make sure it is used as filter.
2. Go to library
3. Reload (important)
4. Try to filter by that field
5. Nothing happens, no request is sent to the server or anything

**Comment by RafaPolit** [comment]
Check if other edge-characters also trigger this issue. `(`, `>`, `<`, `?`, `\`, `|`, `%`.  The problem here only happens when they are actually ENCLOSED in the square brackets, so try enclosing in different characters.

**Comment by Zasa-san** [comment]
- Opening, closing, or enclosing template property names in `[ ]` will make it stop searching.
- Opening, closing, or enclosing template property names in `%` makes the client crash.

**Comment by Zasa-san** [comment]
I've also discovered that trying to save an entity with properties named with `[ ]` throws a 422 (Unprocessable Entity)`. @konzz @RafaPolit
