### ISSUE TITLE
OCR Tooltip texts

### ISSUE THREAD

**Issue by Zasa-san** [huridocs/uwazi#4091]
The tooltip for PDF that cannot be OCR because of an error in the service says `The OCR engine couldn’t read the document. Try uploading the document in a different format.`
Format can only be PDF, so "another format" is misleading.

**Comment by txau** [comment]
What do you think of `The OCR engine couldn't read the document due to a malformed format.`

**Comment by Zasa-san** [comment]
That's more precise, It's ok as long we don't need to tell users what to do about it.

**Comment by Zasa-san** [comment]
@RafaPolit going with @txau 's suggestion for now.
