### ISSUE TITLE
Multiselect filters that have groups should use the parent in the URL instead of the children (8 pts)

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#4094]
When you have a thesauri with groups, and you click the parent, that action puts all the children in the url as filters, but if then you use that URL in a page, and also add more values to that group, you will expect that when you visit that url the ne sub values are also been filtered by.

Example:
- You have library filters like this:
<img width="396" alt="Screenshot 2021-12-17 at 15 55 54" src="https://user-images.githubusercontent.com/948117/146564031-3080f889-762e-4ca2-94ed-5a03884818ea.png">

- You use the url to create a link pointing to Cool People
- Someone adds new cool people, let's add Santi and Joan
- And then when you visit again that filter you get this:

<img width="396" alt="Screenshot 2021-12-17 at 15 57 08" src="https://user-images.githubusercontent.com/948117/146564302-a0aa51eb-f57b-42b2-8dd8-c7b51926b809.png">

**Comment by txau** [comment]
A positive side effect is shorter URLs.

**Comment by juanmnl** [comment]
This is the agreed pattern to solve this.

We'll add a new state to the filter group parent checkbox which consists on a "full select" that locks out partial selection of the children. 

*Any child added later to that group will be automatically selected by default when this mode is active.

![2022-01-11 12 08 29](https://user-images.githubusercontent.com/699945/149799278-29c03e94-fa53-415a-be02-263af09e0cd8.gif)


Checkbox States breakdown:

<img width="1422" alt="Screen Shot 2022-01-11 at 11 54 37" src="https://user-images.githubusercontent.com/699945/149798775-a72d9094-ee43-4a9d-812f-90ed68af301b.png">
