### ISSUE TITLE
Update Babel and Webpack

### ISSUE THREAD

**Issue by LaszloKecskes** [huridocs/uwazi#4096]
Currently, on the github repository we have several warnings about packages by dependabot. A large portion of those are part of the internal dependency chains of babel and webpack. In order to resolve the issues, we need to update. 
Before attempting the fix for the issue, some further discussion will be necessary about how to handle the changes; the initial view was that it would involve rewriting our babel and webpack configs, scripts, etc. from scratch, rather than attempting to update incrementally.

**Comment by konzz** [comment]
@joan after a brief discussion please confirm priority high of this issue in the next tech call
