### ISSUE TITLE
Update Jest

### ISSUE THREAD

**Issue by LaszloKecskes** [huridocs/uwazi#4097]
Currently, on the github repository we have several warnings about packages by dependabot. Some of these are part of the internal dependency chain of jest. To resolve some of the issues, we need to update jest. 

Note: jest is only a dev dependency.

During an initial short trial, after updating to the now current jest version (27.4.5), an immediate issue is that the default test runner of jest had been changed. It is possible to manually set it in the jest configs (see: https://stackoverflow.com/questions/68853359/jasmine-is-not-defined ). After that, in the unit tests only 29(/3971) failed tests remain, most likely due to the same reason ("ReferenceError: setImmediate is not defined").
Note that there are multiple jest configs and test suites (unit tests, nightmare e2e suites, puppeteer e2e tests) to configure and debug after the update.

**Comment by Zasa-san** [comment]
When upgrading jest, please the try to remove `jest-environment-jsdom-sixteen` dependency. This was installed a as standalone, required by React Testing Library in `app/react/Viewer/components/specs/OCRStatus.spec.tsx`.
I think newer versions of Jest already have this included, and should not be needed as a standalone.
