### ISSUE TITLE
[HELP] reading the returned entity as markdown

### ISSUE THREAD

**Issue by justinbalaguer** [huridocs/uwazi#4106]
when you add an entity it automatically supports markdown (e.g adding a description in the text area field), is there a component or a way (javascript) to read the text field as markdown / styled in html?

**Comment by fnocetti** [comment]
Hello @justinbalaguer, can you please elaborate the use case a bit more? What do you want to achieve?

**Comment by justinbalaguer** [comment]
when you add an entity it is supported here, but how can I have that markdown support when I put it on an entity page or use javascript to get that description data
![image](https://user-images.githubusercontent.com/26339491/147108397-8c11691e-5484-42cb-a124-3e4ac6fd8f0a.png)

**Comment by RafaPolit** [comment]
For entity pages, we provide a component named `<EntityData>` which renders every property using the same functionality you get on the side panel or on the entity view page.

For that, please use the documentation found here:
https://uwazi.readthedocs.io/en/latest/admin-docs/creating-entity-pages.html

As for rendering with Javascript, there are probably a few JS libraries that will transform markdown to html.  We use `markdown-it` and `markdown-it-container` internally to produce the results you get on Uwazi, but implementing those will be up to the site admin.

If this is for display INSIDE Uwazi Entity Pages, I believe the `<EntityData>` component will probably give you most of what you need.

If something is not clear, or if I misread what is the expected result, don't hesitate to elaborate further.

**Comment by justinbalaguer** [comment]
ohh I see thank you so much. I will close this now.
