### ISSUE TITLE
Blank charts

### ISSUE THREAD

**Issue by AhmadQadi1** [huridocs/uwazi#4108]
![blank charts](https://user-images.githubusercontent.com/95572565/147090775-0151d782-0e67-4124-b098-ff706390810b.png)

The second quarter of "the Breakdown by quarter (2021)" chart in the English version of the website suddenly changed to blank. Please find below a screenshot showing the chart.

**Comment by nwyu** [comment]
@AhmadQadi1 This appears to be fixed. I just resaved the page with the same javascript..

![7amleh-counters](https://user-images.githubusercontent.com/56067374/147199300-228e107b-df98-4692-8196-c5d676fcba01.png)
