### ISSUE TITLE
Code for Home Page

### ISSUE THREAD

**Issue by blesskn** [huridocs/uwazi#4109]
Good day. Can you kindly send me a basic css code to insert on the home page. The one that includes a full width image which will be a 1/3 of the screen, with text for about us at the bottom of the image.

Best regards

**Comment by MatelSow** [comment]
Hello, please see below the steps to achieve this on the homepage. Let me also direct you to our Uwazi documentation available here for more information. Best

**The following steps need to be completed using an administrator account.**


1. Go to the uploads section under the category tool within your Account Settings menu
2. Upload the picture you would like to us as a banner on the page
3. Copy the URL generated after uploading the picture
4. Go to the Global CSS section under the category tool within your Account Settings menu
5. Copy and paste the code below


```
.home-hero {
  background: #f4f7f9;
  background-image: url(/assets/1641834415441ihi6jqwiml.jpg);
  background-size: cover;
  background-position: center;
  padding: 48px 16px;
  margin: -15px -15px 0 !important;
  max-width: calc(100% + 30px) !important;
  text-align: center;
}
```

**Note**: please insert the url generated after uploading the picture in the brackets aafteter url in the code   background-image: url(/assets/1641834415441ihi6jqwiml.jpg)

1. Go to the Pages section within your Account Settings menu
2. Create a new page by clicking on Add page
3. Copy and paste the code below


```
<Dataset />

<section class="home-hero" id="home-hero">
  <style type="text/css">
    #home-hero {
      background-position: center;
      height: 30vh;
      padding-top:1px;
      display: flex;
      flex-flow: column;
      justify-content: center;
    }
</section>
 
 
# <div style="text-align: center"> About Us </div>
```
   

<div style="text-align: justify"> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum>. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum </div>

**Comment by blesskn** [comment]
Thank you so much
