### ISSUE TITLE
Migrate corrupted data due to language creation bug (8 pts)

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#4115]
⚠️ DEPENDS ON #4133

- [ ] Check this if #4133 is already merged

create a migration that sanitizes this scenario: fetch ALL shared IDs in the collection, and, for those that don't have one entity per language, duplicate the existing one into the other languages. Do NOT assume that any language is the master language. The missing entity could be in any language, including the default language.

Split from #3955

**Comment by konzz** [comment]
Laszlo has written a script to check whenever an instance needs to be migrated and also returns the list of entities affected.
