### ISSUE TITLE
"An unexpected error" message appearing always on the website

### ISSUE THREAD

**Issue by AhmadQadi1** [huridocs/uwazi#4116]
The message of "an expected error" always appears on the website though everything works properly. Users think their submission didn't work. Attached is a screenshot of the message.
![signal-2022-01-04-221654](https://user-images.githubusercontent.com/95572565/148180452-84c4407d-43d1-440d-aa17-2088e1020192.jpeg)

**Comment by RafaPolit** [comment]
We can't seem to replicate the issue.

This suggests that there is an error in the client-side javascript.  Please, contact your Project Manager in HURIDOCS so we can locate the issue.
