### ISSUE TITLE
Possible issue with translation of thesauri in different languages from within Uwazi 

### ISSUE THREAD

**Issue by natasha-todi** [huridocs/uwazi#4121]
As seen in this [video](https://drive.google.com/file/d/1uQik_EAMmVX9xGxTX_eiQeV_Yu1yEZhd/view?usp=sharing), even though the thesauri "Language_Test" has been edited and 'translated' via the translations section in Uwazi, when the user toggles to Setting >Thesauri> Language Test, they can only see one option in all the language interfaces. If the user tries to edit the thesauri from the Thesauri section by changing the UI and entering the information, the latest change becomes the common thesauri for all languages. To note: this change also reflects in the dropdown for data entry when this thesauri is used in a template as a single select or a multi-select whereby the last change seems to override all previous edits across languages. Is this expected?

**Comment by RafaPolit** [comment]
This is a UX issue, and a known issue.  The best way to think about this is as follows:
- Non-settings related items (entities and pages) are translated changing the UI language
- Settings related items (thesauri, templates and templates properties) are translated via the translations, and changing the languages does not show changes in translations.

It's not ideal, but it prevents changing values in different languages thinking "Hey! I'm editing this value", when in fact you are just changing it's translation.  We should improve on this, but, as is, is "expected".

cc @juanmnl
