### ISSUE TITLE
Add reindex flag to migrations (5 pts)

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#4122]
We want to avoid human errors when deploying so if a deploy needs a reindex it should be marked in a migration.

Possible options:
- The migration has a flag to say reindex or not.
- The migration has a flag but can be changed on the fly when an instance does not need to be migrated
- The migration returns some information including if it requires a migration or not.

⚠️ Beware of making this backwards compatible with previous migrations (it should not throw errors if flag is not defined)

**Comment by txau** [comment]
Also if several migrations are executed in sequence, the flag should be carried to the last one so we don't run futile reindexes?
