### ISSUE TITLE
Show connections in entities and documents when used as (multi)select value

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#414]

**Comment by RafaPolit** [comment]
To discuss:
If I create an entity B which references entity A:
- If entity B is not yet published (entity A is), when I go to entity A -> should B be listed as a reference? Always? Only if logged in?

**Comment by txau** [comment]
@RafaPolit regarding the first issue. We are going to encounter that same situation often, when we have a public information connected to a private information.

In my opinion, it should only be displayed if you have authorisation (in this case, if you are logged in ).

**Comment by RafaPolit** [comment]
### To implement
- [ ] Hide un-published references
