### ISSUE TITLE
Social Media Sharing Buttons & Entity Hit Counts

### ISSUE THREAD

**Issue by blesskn** [huridocs/uwazi#4156]
Good day

Is there a way of adding social media sharing buttons i.e. Facebook and Twitter, to entities, to allow people to directly share on social media platforms?.

Another question is, is there a way of adding hits counts showing how many people viewed your page, viewed an entity, show number of downloads made from an entity?.

Thank you in advance.

**Comment by nwyu** [comment]
Hi @blesskn. Thanks for your suggestions! We do not currently have either feature within Uwazi. You can, however, monitor your collection's web traffic if you wish . You can learn how to configure this here: [https://uwazi.readthedocs.io/en/latest/admin-docs/managing-settings.html#how-to-track-your-collections-web-analytics](https://uwazi.readthedocs.io/en/latest/admin-docs/managing-settings.html#how-to-track-your-collections-web-analytics).

**Comment by blesskn** [comment]
Thank you very much for the response. Can you kindly advice on the invoice for the small package I requested sometime ago, I have not yet received the payment details. Is it ok to add more entities and files whilst I wait for the invoice.

Best regards

**Comment by nwyu** [comment]
Please do, @blesskn! Feel free to continue adding into your Uwazi. My colleague will be in touch soon with your invoice. All best!

**Comment by blesskn** [comment]
Thank you very much.
