### ISSUE TITLE
Google Fonts is not loading

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#416]
![screenshot 2016-09-12 19 52 11](https://cloud.githubusercontent.com/assets/6364153/18446457/b146e3f0-7922-11e6-8f74-27468d543597.png)

![screenshot 2016-09-12 19 53 07](https://cloud.githubusercontent.com/assets/6364153/18446434/9a115e18-7922-11e6-8ce9-2a51465c4967.png)

**Comment by RafaPolit** [comment]
Reinstated to Root.js
