### ISSUE TITLE
Display of values from nested thesaurus when selected using a Multi-select property (3 pts)

### ISSUE THREAD

**Issue by Chamrid** [huridocs/uwazi#4161]
When a template has a multi-select property and an option in a nested thesaurus is selected, the value of the option does not display when the view is on table view it rather shows "Object Object".

See below a screenshot :

<img width="1437" alt="Capture d’écran 2022-01-21 à 11 55 49" src="https://user-images.githubusercontent.com/82155887/150537090-0dbdeb17-cbf3-4c8c-acfb-132c054810ac.png">

**Comment by konzz** [comment]
@kevin take a look at this issue reported by Jaume and see if you can fix both things https://github.com/huridocs/uwazi/issues/4226
