### ISSUE TITLE
Cannot bulk edit on entities that are using multi-inheritance 

### ISSUE THREAD

**Issue by natasha-todi** [huridocs/uwazi#4192]
As seen in the [video](https://drive.google.com/file/d/17wysGaUh9RNB2TcIiRWQbpbSWYTcGS3O/view?usp=sharing), when trying to bulk edit entities within the template Act of Violation which has multi inheritance set up, there seems to be an error. This was also replicated in other partner instances. 
<img width="645" alt="Screenshot 2022-01-27 at 5 39 25 PM" src="https://user-images.githubusercontent.com/60774708/151356168-a5fb0cd4-e422-458b-99ca-f272267a833c.png">

**Comment by natasha-todi** [comment]
This is also happening on entities that have only single inheritance set up: 
<img width="1104" alt="Screenshot 2022-01-28 at 7 33 50 PM" src="https://user-images.githubusercontent.com/60774708/151560359-8ffa9b84-2781-48dc-9a2f-0b4fa888002a.png">

**Comment by konzz** [comment]
Hi @natasha-todi  this issue is already been fixed, thanks for reporting it. I'm closing this one if you want to follow it there is a draft pull request: [here](https://github.com/huridocs/uwazi/pull/4219)
