### ISSUE TITLE
There is window size where there is neither menu links nor 'mobile' menu.

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#420]
There is an intermediate size of window where there is no way to access navigation links, as they are already hidden from view, but there is still no 'three-lined-menu'.

![screenshot from 2016-09-14 15-42-29](https://cloud.githubusercontent.com/assets/4309019/18529298/1a5a0fc8-7a92-11e6-927e-02ff8b38adba.png)

![screenshot from 2016-09-14 15-42-32](https://cloud.githubusercontent.com/assets/4309019/18529304/1e3f7dc6-7a92-11e6-8b60-30ad63c37298.png)

![screenshot from 2016-09-14 15-42-36](https://cloud.githubusercontent.com/assets/4309019/18529309/2531ee0c-7a92-11e6-9bb2-573cc006cdc2.png)

**Comment by danicatalan** [comment]
This happens in `396-menu` (it's still not merged).

I'm fixing it on that branch, I'll ping you when it's ready.

**Comment by RafaPolit** [comment]
Working OK in 396.
