### ISSUE TITLE
Separate library and viewer

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#422]
I think it would be interesting to check in the future if we can separate the viewer (for documents and entities) from the library, settings...

It's good for UX because helps the user to focus on just document/entity related content, and changing the header or background color it's a technique widespread used.

![screenshot 2016-09-15 16 55 49](https://cloud.githubusercontent.com/assets/6364153/18554702/567b8648-7b65-11e6-97c3-e1b53c158727.png)

**Comment by txau** [comment]
@danicatalan I think is a good idea. Although we may want to add a breadcrumb or something so users don't loose awareness of where they are at.
