### ISSUE TITLE
Metadata properties are created with id, _id and LocalID in templates (13 pts)

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#4223]
Replicate:
- blank-state
- edit the default template "Document" and add some properties

In the database these properties have id, _id and LocalId. They should only have _id.

**Comment by konzz** [comment]
- id should be removed and changed to use _id
- _id is the one we want to use and persist
- LocalID should not reach the backend and only be used for drag and drop in the client.

**Comment by RafaPolit** [comment]
- Remove LocalID and id from the backend validation
- Remove all uses of id
- LocalID should me still used in client and then sanitized before sending to backend
- Migration to remove id and localID from the databases
