### ISSUE TITLE
Inherited properties are not displayed in table view

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#4226]
dixit

**Comment by salvalacruz** [comment]
Hi, I've tried with a staging instance, it looks still need to be checked:

![image](https://user-images.githubusercontent.com/73410334/153267733-f1a8172b-0039-4f92-abab-b8fe1f82ee98.png)

In the table view, “Código País” is empty, but “Loc País” works well (both inherited properties).

**Comment by Zasa-san** [comment]
Thanks @salvalacruz for reporting!

Looking into it, the following type of inherited properties fail to appear on table view:
- Text
- Numeric
- Link

Additionally, inheriting a link makes the application crash when selecting the entity that is inheriting that link.

To reproduce this issues:
- Create a template A with a text, numeric and link property.
- Create a template B that inherits any of those properties.
- Go to table view: text and numeric do not appear for the entity that is inheriting.
- Selecting the entity from template B while it's inheriting a link makes the app crash.
