### ISSUE TITLE
Search is not computing the correct aggregations per template (5 pts)

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#4227]
When filtering by template search should be displaying the amount of entities for other templates. This filters is a special case and does not work as the rest of the aggregations. Instead it gives 0 for other templates:

![image](https://user-images.githubusercontent.com/489831/152102736-6ade79b2-3ad0-4917-bae1-9b1a8a415f3c.png)

**Comment by RafaPolit** [comment]
This is behaving like and AND and it should be behaving like an OR.
