### ISSUE TITLE
Aggregate multi-inheritance values on entity data (8 pts)

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#4232]
When using pages for templates, inherited fields come as separate arrays hence there is no way they can be used to display tabular data based on their common source entity. A work around for this problem exists via JS but it will fail on the server side rendering.

It would be great to have retrieve multi-inherited values as an aggregate for easy of use for tabular data and keeping server side rendering.

**Comment by konzz** [comment]
- ~This extra information should not be always returned, only when requested~
- ~Client should request this whenever is going to show an entity in page view.~

Client will post process this in the client.

The data should come in a format like:

For an entity with 3 relationship properties inheriting from 2 different entities:
```
relationships_data: {
       template_relationship_type: [
              {
                     age: [23], country: ['es'], colors: ['blue', 'red']
              },
              {
                     age: [], country: ['es'], colors: ['green']
              }
       ]
}
```

**Comment by txau** [comment]
@konzz will this structure work with the repeat tag?

**Comment by konzz** [comment]
I dont know, would need to test

**Comment by txau** [comment]
@konzz alternatively, this can be addressed in the context of the upcoming template/form groups (https://github.com/huridocs/uwazi-design/issues/12)
