### ISSUE TITLE
use elasticsearch to improve performance on a highly used mongodb query

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazi#4276]
On initial load 200 entities of each template are preloaded into client alongside with thesauri to prefill the selects/multiselects when the property is a relationship, this is a slow query to perform in specific scenarios, delaying the initial load of the application, moving this query to elasticsearch can reduce the initial load times and remove load from mongodb.

https://github.com/huridocs/uwazi/blob/a8ca492835b53fe57894cb3cab60ffffa4b93632/app/api/thesauri/thesauri.js#L148-L161

**Comment by LaszloKecskes** [comment]
As discussed with @daneryl, instead of moving to elastic, we extend the entity index over the templates into a composite over template-language-published to better support the query from mongo.
