### ISSUE TITLE
Demo instance: Document 'type' change

### ISSUE THREAD

**Issue by YolandaCHR** [huridocs/uwazi#429]
When working on metadata, the different categories in 'Document' are automatically labeled 'Type'.
Is there a way to be able to edit that instance's name from 'Type' to something else?

**Comment by txau** [comment]
@YolandaCHR do you mean the label "Type" that appears in the side panel when you select a document from the list?

If so, I have the same feeling about it. Title and type of document are a special case of metadata that is always present. What do you think of this solution?

![screen shot 2016-09-20 at 10 02 20](https://cloud.githubusercontent.com/assets/489831/18662172/76497c52-7f19-11e6-8e02-1831bb2b9c2f.png)

So its displayed in the same way it is displayed in the rest of the system. The "type" label will simply disappear.

/cc @danicatalan

**Comment by YolandaCHR** [comment]
@txau 
This might be a good idea - it also breaks the monotony of text only and creates a visual link to the cards.
Just in case 'Type' does not really fit in with the user's syntax - so I like it!
