### ISSUE TITLE
Demo instance: Rich text format

### ISSUE THREAD

**Issue by YolandaCHR** [huridocs/uwazi#430]
Is there a way for the 'Rich text Format' property to be 'rich' enough so that italics and links can be added?
Just wondering!
Thanks for all the hard work :)

**Comment by RafaPolit** [comment]
@YolandaCHR , thanks for all the feedback.

On the rich text editor, on the top right side, you will find three tabs: Edit, Peview, and Help.

If you click on the Help button, you will be redirected to a page explaining how to format text in order for it to have italics, bold, links, images, quoted text, etc.

The input format is called 'mark down'.  You can input the rich text and check how it is looking with the preview button.

Hope this helps,
best regards,
Rafa.

**Comment by YolandaCHR** [comment]
Sorry @RafaPolit - I missed that feature!
Thanks very much

**Comment by txau** [comment]
@YolandaCHR on a side note, this is only the first iteration of that metadata type. In the future we plan to add assistants to ease the process of linking documents etc.

I think this field could serve better your needs for the "Commentaries" of your project? Note that it can be used as a metadata of entities (although probably you need a better rendering for the entity view).

**Comment by YolandaCHR** [comment]
Thanks @txau - sounds great!
