### ISSUE TITLE
Timelines

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#431]

**Comment by danicatalan** [comment]
This is the timeline design for individual items. It will render on metadata panel and entity viewer.

![screenshot 2016-09-20 17 22 19](https://cloud.githubusercontent.com/assets/6364153/18676717/d8fb89ac-7f56-11e6-8c3a-2375d948749b.png)

We need to discuss where we catch data and how inject it on the app.

**Comment by danicatalan** [comment]
We need to check this, because empty years are not rendering on the timeline:

![screenshot 2016-10-17 19 22 31](https://cloud.githubusercontent.com/assets/6364153/19447757/435c8118-949f-11e6-9143-8638daa3a8f2.png)

**Comment by txau** [comment]
We also said that we were going to add the fast tool tip instead of the browser's default slow tool tip.
