### ISSUE TITLE
Account settings - rol and groups

### ISSUE THREAD

**Issue by salvalacruz** [huridocs/uwazi#4316]
Just a suggestion, for the **/settings/account** screen:

Would it be appropriate if the user can view on this screen information about what **role** their account has and what **user groups** they are included in?

**Comment by juanmnl** [comment]
We are going with a quick solution for this, reusing the pills we have in the `USERS page > USERS table` for showing your ROLE and GROUPS. (Also adding username to the mix)

When a user doesn't have any groups, the whole row should be hidden.

<img width="720" alt="Screen Shot 2022-03-18 at 10 40 08" src="https://user-images.githubusercontent.com/699945/159034775-6f0e5446-c60e-44e7-9e7e-b490a4e0de07.png">
