### ISSUE TITLE
User workflow to add properties to information extraction (8 pts)

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#4320]
Right now the config for IX is inserted manually in the DB, we want our users to be able to configure this via the UI
Designs:
https://www.figma.com/proto/VbnNs1Iy8qbOet3oLwMgfe/Information-Extraction?page-id=1%3A9&node-id=18%3A3050&viewport=281%2C48%2C0.29&scaling=min-zoom&starting-point-node-id=6%3A3363

**Comment by juanmnl** [comment]
**Basic user flow:**
```mermaid
  flowchart TD;
      IE[Main IE dashboard] --> |Modal| Add[Add property/properties];
      Add --> Templates[Template list w/ supported properties];
      IE[Main IE dashboard] --> |Modal| Update[Update property];
      IE[Main IE dashboard] --> Select[Select single or multiple properties] --> |Modal| Update;
      Select[Select single or multiple properties] --> Remove;
      IE[Main IE dashboard] --> Review[Review property];
      Review --> |Go back| IE;
      Review[Review property] --> Suggestion[Select single or multiple suggestions] --> Accept[Accept all];
      Review[Review property] --> ApplySuggestion[Apply suggestion];
      Review[Review property] --> Document[Entity/Document detail];
      Document --> |Go back| Review;
```

**Notes:**
- Use available styles
- Warning dialog when existing w/o saving
- Both **main IE dashboard & Review property** should be the **same table component**
- Limit cells to 2 lines w/ ellipsis
  - Show full content on hover
- Sticky table header and footer
- Nice to have: **Search component** on every screen & modal (add if time allows)
- [Table library to review](https://github.com/githubocto/flat-ui#readme)

**Comment by juanmnl** [comment]
**Main IE Dashboard**

List of user-selected _(supported)_ properties to be extracted from documents.

Basic IxD:
- Add/Edit/Remove property
- Single & multiple selection
  - Contextual Actions
- Navigate to property review

---

<img width="1440" alt="Main IE Dashboard" src="https://user-images.githubusercontent.com/699945/155155804-4ae0d45c-f127-41c1-a957-e395e2b2dbf1.png">

**Comment by juanmnl** [comment]
**Main IE Dashboard + Add property MODAL**

List of available templates with supported properties.

Basic IxD:
- Select/Unselect template property
- Select property from all templates
- Select multiple properties
  - Adds row/property
- Add/remove template for existing property (update)
- Search behaves as a filter
  - Uncollapses matching templates
  
---

<img width="1440" alt="Main IE dashboard with modal" src="https://user-images.githubusercontent.com/699945/155155934-4d8b1026-fdb8-4d16-ae10-bba725d9fc66.png">

---

<img width="1411" alt="Screen Shot 2022-02-22 at 09 59 55" src="https://user-images.githubusercontent.com/699945/155159241-fa0a8427-84da-4b14-841a-0625cad4b278.png">
