### ISSUE TITLE
Workflow to open PDF when reviewing suggestions (20 pts)

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#4322]
Information extraction basic flows:

Main dashboard:
- Checkbox select w/ contextual actions
- Add property modal
- Property detail navigation
 
Property Dashboard:
- Back navigation
  - checkbox selection (w/ possible contextual actions if needed)
  - apply change on the fly (arrow button)
  - detail navigation:
  - slide detail + close
  - full page detail
    - back navigation

Designs

https://www.figma.com/proto/VbnNs1Iy8qbOet3oLwMgfe/Information-Extraction?page-id=1%3A9&node-id=6%3A3363&viewport=281%2C48%2C0.29&scaling=min-zoom&starting-point-node-id=6%3A3363

**Comment by juanmnl** [comment]
**Basic user flow:**
```mermaid
  graph TD;
      Main IE dashboard --> Add property;
      Main IE dashboard --> Review property dashboard;
      Main IE dashboard --> Select single/multiple properties --> Remove;
      Add property --> Select supported property from template(s);
      Add property --> Update selected property;
      Review property dashboard --> Back navigation;
      Review property dashboard --> Select multiple suggestions --> Accept all;
      Review property dashboard --> Accept suggestion;
      Review property dashboard --> Document detail navigation;
      Document detail navigation --> Back navigation;
```

**Comment by juanmnl** [comment]
**Main IE Dashboard**

List of user-selected _(supported)_ properties to be extracted from documents.

Basic IxD:
- Add/Edit/Remove property
- Single & multiple selection
  - Contextual Actions
- Navigate to property review

---

<img width="1440" alt="Main IE Dashboard" src="https://user-images.githubusercontent.com/699945/155155804-4ae0d45c-f127-41c1-a957-e395e2b2dbf1.png">

**Comment by juanmnl** [comment]
Main IE Dashboard + Add property MODAL

List of available templates with supported properties.

Basic IxD:
- Select/Unselect template property
- Select property from all templates
- Select multiple properties
  - Adds row/property
- Add/remove template for existing property (update)
- Search behaves as a filter
  - Uncollapses matching templates
  
---

<img width="1440" alt="Main IE dashboard with modal" src="https://user-images.githubusercontent.com/699945/155155934-4d8b1026-fdb8-4d16-ae10-bba725d9fc66.png">

**Comment by juanmnl** [comment]
**Review property**

List of suggestions for available matches.

Basic IxD:

- Apply suggestion (arrow button)
  - Suggestion is always to the left of the current value column (See title and date examples)
- Single or multiple selection to batch accept suggestions
- Navigate to document/entity**

---

<img width="1440" alt="Review property" src="https://user-images.githubusercontent.com/699945/155157861-0db87bad-0123-4513-b669-db811e8b83ee.png">

---

** we need to chose the quickest between two options (see next comment):
1. Full master/detail navigation
2. Document/entity slider

**Comment by juanmnl** [comment]
**Detail navigation**

1. Master/detail navigation:

User navigates to the entity detail when clicking **context**

<img width="1440" alt="Entity detail" src="https://user-images.githubusercontent.com/699945/155158108-cd8557c2-4886-44a7-9701-27987955e8e2.png">

---

2. Document/entity slider

The document slides from the right with the single property input when clicking **context**

<img width="1440" alt="Entity slider" src="https://user-images.githubusercontent.com/699945/155158600-b276362f-f8a8-4a71-bab8-59d1c958341f.png">
