### ISSUE TITLE
Better deal with non-standard document formats

### ISSUE THREAD

**Issue by whyfrycek** [huridocs/uwazi#433]
Just opened a pretty wide pdf on my demo server that also includes images: https://friedhelm.uwazi.io/document/4db5883ef6e4fc7cdbcdf8f71502f5aa

It makes me scroll quite a bit, which is not great on a computer and even more complicated on mobile. Not sure, if there is a great solution, but maybe zoom could actually help?

**Comment by txau** [comment]
These kind of documents are always being to be hard to deal with, not to speak about mobile.

I've been running some tests and a zoom feature greatly mitigates the pain.

**Comment by kjantin** [comment]
@whyfrycek 's link is now broken, but I think this issue is related to #1143

**Comment by nwyu** [comment]
Closing this issue after discussion with programs team. This was seen as an uncommon format and very low priority.
