### ISSUE TITLE
Improve performance for entity save

### ISSUE THREAD

**Issue by elreplicante** [huridocs/uwazi#4356]
We have a N+1 queries problem on POST /api/entities.

Sentry screenshot:

<img width="1451" alt="Screenshot 2022-03-01 at 10 55 50" src="https://user-images.githubusercontent.com/1397196/156147053-220899e2-aa7a-44e2-ae1b-d067156580cb.png">

**Comment by LaszloKecskes** [comment]
Solved through the related prs.
