### ISSUE TITLE
Public form infinite redirection (5 pts)

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#4358]
Under certain conditions the URL in "settings > collection > public endpoints > public form submit url" can cause an infinite redirection.

**Comment by Zasa-san** [comment]
After trying several configuration options we have not been able to reproduce this issue. We might need an example of an instance where this happened to better understand how this issue occurs. 
cc: @mfacar

**Comment by txau** [comment]
Maybe @daneryl can toss some light, I diagnosed the bug with him.

**Comment by daneryl** [comment]
Maybe this was badly diagnosed, im not able to replicate, lets revisit if this happens again.
