### ISSUE TITLE
Import CSV thesauri duplicates values when importing multiple times.

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazi#4369]
- create a blank thesauri
- import a CSV to fill it
- go back to thesaurus list and edit the same thesauri
- import again the same file
- values get duplicated

I am not sure this needs to be fixed ? but we already having problems with some partners probably because the lack of feedback, they end up with multiple duplication of the same value and this can lead to assign different internal ids when relating this values to an entity.

- should we not allow duplicates on thesauri values, what is the use case to allow this ?
- should we provide feedback to the user that the values are going to be duplicated ?
- maybe on the particular case of importing, do not allow duplication at all ?

**Comment by txau** [comment]
Thesauri creation via UI also allows for duplicate values. This is wrong and should be addressed as well. This issue could be solved if CSV import of thesauri uses the same validation as in thesauri's model.
