### ISSUE TITLE
Save button for paragraph to paragraph connection is not where expected

### ISSUE THREAD

**Issue by whyfrycek** [huridocs/uwazi#437]
1) I am creating a paragraph to paragraph connection
2) All interactions are in the panel on the right
3) Only the save button for the connection is above the document, which confuses me

**Comment by RafaPolit** [comment]
Completely agree on this one!

**Comment by danicatalan** [comment]
Related to #631.

We are going to upgrade as soon as possible our interactions buttons. Now, they will be over the text: also this save button.

I move this into sprint, waiting for solve the other issue and close this one.

**Comment by danicatalan** [comment]
We have move all our text interaction above the document on #631. Now, this button will be rendered when the user selects the target text.

![screenshot 2016-12-19 17 49 31](https://cloud.githubusercontent.com/assets/6364153/21321085/9b9be4d6-c613-11e6-939e-3a6bfa4a96e4.png)

@whyfrycek thanks for your feedback. Please keep in touch with @txau to check if you have the last version deployed to your instance. We would like to get your feedback :)
