### ISSUE TITLE
Fold options into a drop down menu in "order by" metadata properties in library

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#442]

**Comment by danicatalan** [comment]
All the code to complete this is on `dropdown-sort-by`.

I created the styles for a Dropdown component:

![screenshot 2016-09-27 15 48 57](https://cloud.githubusercontent.com/assets/6364153/18876456/1867bc96-84ca-11e6-9b06-4de440b17493.png)

![screenshot 2016-09-27 15 49 07](https://cloud.githubusercontent.com/assets/6364153/18876455/1863b5c4-84ca-11e6-94fd-b1b3697408cf.png)

But the interaction it's not define. @RafaPolit let me know when you get this and we can work together to finish the component.

**Comment by txau** [comment]
@RafaPolit its buggy =D
