### ISSUE TITLE
External URLs don't work on the Menu

### ISSUE THREAD

**Issue by UjoNyawara** [huridocs/uwazi#447]
These are useful for linking back to the Organization's website and other pages. When clicked nothing happens.

![issue-01](https://cloud.githubusercontent.com/assets/1784894/18781307/cecd81bc-8189-11e6-908a-8e3288708ec8.jpg)

**Comment by RafaPolit** [comment]
This is coming really soon. We need to address different URL sources and detect the current deployment domain in order to sort local from external sources.

**Comment by RafaPolit** [comment]
Do we really want external URLs on the Menus though? Perhaps these are better located inside pages?

At any rate, external URLs should probably open in a new tab, or be tagged clearly as 'leaving Uwazi', so this requires some further discussion.

**Comment by kjantin** [comment]
@danicatalan can you update the help text to clarify that you can't put an external URL into these menu items? We still need to discuss this as a team whether we want to allow external URLs (and how), but in the meantime some documentation will be helpful to the user Thanks!
