### ISSUE TITLE
I deleted default document type and metadata, and now can't see any option in the Upload section

### ISSUE THREAD

**Issue by UjoNyawara** [huridocs/uwazi#448]
I'm working on the collection for PALU - https://palu.uwazi.io, I decided to deleted all default content ie. the  first document, test dictionary, default document type, everything. I then created my own new ones. But now, when I upload a brand new document and try to edit the properties, nothing shows up. See https://palu.uwazi.io/uploads and screenshot attached.

![issue-02](https://cloud.githubusercontent.com/assets/1784894/18781853/4217f448-818c-11e6-941e-09bbce6bdf15.jpg)

**Comment by UjoNyawara** [comment]
Also, just to confirm, I do have a document type called Treaties which does have Properties. I even logged in and out but nothing.

![issue-02b](https://cloud.githubusercontent.com/assets/1784894/18781926/94160f32-818c-11e6-84f5-93f68ac21dc8.jpg)

**Comment by txau** [comment]
@RafaPolit I've just checked this. Its tossing this JS error:

MetadataForm.js:66 Uncaught TypeError: Cannot read property 'toString' of undefined

**Comment by RafaPolit** [comment]
This is a known bug.  Its the 'When adding a multiselect field to the template, I need to change the default property, and then select it again in order for the template to work'.

I have fixed the instance by reasigning all the multiselects.  At some point we need to puase a bit the new functionality rush and address this technical debt issues.

Best regards,
Rafa.

Closing in favor of #477
