### ISSUE TITLE
When selecting a paragraph connection, last existing connection is always rendered green

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#455]
Way to reproduce:
- Create a paragraph connection from document A to B
- Go to document A and select to create a second connection to document B
- Select a portion of text not belonging to the first connection

Result:
- The first connection is rendered green as if you have selected the same text as connection

Expected result:
- No previous connection is rendered green unless the same text was clicked.

**Comment by RafaPolit** [comment]
This is still an issue.

**Comment by kjantin** [comment]
Still an issue but will probably be addressed with the connections improvements.
