### ISSUE TITLE
Gradient behind buttons shows grey banding on mobile devices.

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#458]
The gradient behind the buttons of the side panel on mobile devices does not work like its desktop-size solution.

![img_1442](https://cloud.githubusercontent.com/assets/4309019/18854144/050b6fc8-840f-11e6-9d99-f9ea3df8224d.PNG)

**Comment by txau** [comment]
@danicatalan this may be related to https://github.com/huridocs/uwazi/issues/378

**Comment by danicatalan** [comment]
Fixed in #578.

I will close this when the other issue is merged.
