### ISSUE TITLE
Download original file

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#47]

**Comment by txau** [comment]
@danicatalan this would be easily solved with the action bar we've discussed today.

**Comment by danicatalan** [comment]
@txau yes, but we still need in inside the floating button to able to download the document from the viewer.

**Comment by danicatalan** [comment]
Updated here, take a look to this video: https://github.com/huridocs/uwazi-assets/blob/master/10_float_button/10_float_button.mov

**Comment by konzz** [comment]
Solved with #214

**Comment by txau** [comment]
Actually not working.

**Comment by daneryl** [comment]
solved d42a157a0bbeac8ed93239bb3016482e5fef6df0

**Comment by txau** [comment]
LGTM
