### ISSUE TITLE
Cannot save metadata on document in DRA instance

### ISSUE THREAD

**Issue by whyfrycek** [huridocs/uwazi#473]
1) We uploaded documents to https://dra.uwazi.io/
2) We created a metadata scheme and dictionaries
3) We added metadata to one of the uploaded documents and clicked the save button
4) Unexpectedly, nothing happened (and we could thus not publish the document)

**Comment by txau** [comment]
@RafaPolit can you check it out? The console tosses the following error:

Uncaught TypeError: val.trim is not a function

**Comment by RafaPolit** [comment]
The multiselect field is somewhat new, and adding the 'required' property to the template definition is what broke the form validation.

Already fixed in DEV environment, will merge into the different instances as soon as another bug is fixed.

**Comment by RafaPolit** [comment]
This has been fixed for all instances.  Some old configurations may need manual updating, but new configurations should not present this issue any more.
