### ISSUE TITLE
Uploads

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#475]
Trying to start the upload of docs. half done. When accessing the page, I get this msg... that this script https://humphrey.uwazi.io/bundle.js:3456 is unresponsive. Dunno if this is relevant.. sorry if not..

**Comment by txau** [comment]
Thanks for reporting @HSips.

This is already reported and fixed in https://github.com/huridocs/uwazi/issues/474

We're deploying the fix to production soon.
