### ISSUE TITLE
sidepanel-body padding-bottom is not working as expected in FF

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#494]
The sidepanel-body padding-bottom which would allow clearance for the scrollbar to show the last connection as well as make room for the panel action buttons is not working in FF.

The result is that you cannot see correctly the last connection.

To test this you need to be logged in and an entity needs to have enough connections to overflow beyond the action buttons.

**Comment by danicatalan** [comment]
Duplicated #378
