### ISSUE TITLE
Antigua country flag is broken

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#499]
![screen shot 2016-10-20 at 14 46 30](https://cloud.githubusercontent.com/assets/489831/19560274/11870a6e-96d4-11e6-8eb9-7731b0d34aea.png)

**Comment by RafaPolit** [comment]
This is an issue with the react-flags component.  I checked.

The 'vendor' flag is there, but the code is not implemented on the component.  Best case scenario, I'll make a pull request of their repo and add those missing flags.  Worst case, we make a fork of the repo and maintain it ourselves.

I'll start with the pull request and see how it goes.

**Comment by txau** [comment]
This is not urgent, lets leave it in the backlog for now.

**Comment by RafaPolit** [comment]
The pull request has been accepted and added to v0.1.12 of the remote respository:
https://github.com/wiredmax/react-flags/pull/5#event-832427856

Closing.
