### ISSUE TITLE
Property names in search by url may change

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#502]
When using a url for rebuilding the search filters, some field names may have changed in metadata, thus the search would fail.

**Comment by RafaPolit** [comment]
The solution for this is not as straightforward as would have been expected, there are a lot of scenarios where we cannot 'reconstruct' the original search, even if storing the property name changes.

We need to have a brainstorming about this, it has already started with the development of #751
@txau @daneryl @konzz @kjantin @danicatalan

**Comment by txau** [comment]
@RafaPolit on a previous discussion with @daneryl and @konzz we decided that these names are never going to change. The drawback of this approach is that the matching between the property label and the database name may be out of sync and confusing after several label changes.

Still, the solution is pretty straight forward and solves the problem for most scenarios.

What do you think @RafaPolit?

**Comment by kjantin** [comment]
Closing and working on #503 to improve these URLs
