### ISSUE TITLE
Faster pop-ups

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#504]
Instead of default browser tooltip, we should use a library with faster tooltips.

**Comment by danicatalan** [comment]
@txau I didnt remember but we already developed a little tooltip - you can check it making hover on "Powered by Uwazi" on the footer.

**Comment by danicatalan** [comment]
@txau do you know if we are still using default tooltips somewhere or can we close this issue?

**Comment by txau** [comment]
@danicatalan I guess we can close =)
