### ISSUE TITLE
Refresh metadata configuration forms CSS

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#512]

**Comment by danicatalan** [comment]
Review property editor for docs and entities:

- Every property label in one line width full width field.
- Move thesauris in a second level with more space.
- Use as filter: remove grey box and get all coincidences at full width.
- Show in cards, sortable and required maybe in one line each.
- Causa > articulos violados: full rebump.

**Comment by danicatalan** [comment]
![screenshot 2016-10-28 19 27 53](https://cloud.githubusercontent.com/assets/6364153/19815776/af5380c6-9d44-11e6-9ef9-5f2f09434a87.png)

![screenshot 2016-10-28 19 28 08](https://cloud.githubusercontent.com/assets/6364153/19815775/af51b110-9d44-11e6-9204-5442b13d8850.png)
