### ISSUE TITLE
Couple of glitches in timeline rendering

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#533]
![screen shot 2016-10-25 at 00 50 32](https://cloud.githubusercontent.com/assets/489831/19666821/19416e3a-9a4d-11e6-989c-3ffddabe9f5b.png)

- [ ] Properly display de process tag.
- [ ] Can we make it full width?

**Comment by danicatalan** [comment]
Fixed in https://github.com/huridocs/uwazi/commit/c03d35cff9246a6850ae105b2fa656b9ecb29b13
