### ISSUE TITLE
Fix mandatos for judges in CEJIL

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#551]

**Comment by RafaPolit** [comment]
This has been implemented on the CEJIL migration repository.

This requires a working CEJIL CouchDB database, but does not depend on MySQL being installed on the system (the migration data is encapsulated on a JS file).

## Executing the migration

The migration project needs to reside besides the uwazi root folder, not inside (just like for the regular migration to work).  Then execute:
```Batch
$ node updateMandates.js
```
The feedback should show the migrated template and 136 judges updated.
