### ISSUE TITLE
Document totals don't show up anymore

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#557]
![screen shot 2016-10-27 at 20 18 44](https://cloud.githubusercontent.com/assets/489831/19779714/a6d6423e-9c82-11e6-81aa-0f7a721d5c1d.png)

**Comment by danicatalan** [comment]
Is not working on Document types. In their properties, the element `multiselectItem-results` it's rendering properly.

![screenshot 2016-10-28 09 50 21](https://cloud.githubusercontent.com/assets/6364153/19798892/f7d31e20-9cf3-11e6-915a-ad58d4ac2ae7.png)
