### ISSUE TITLE
Check metadata titles on cards

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#580]
We need to improve the metadata titles on cards. Now there's a lot of redundancy and space wasted with them.

![screenshot 2016-11-03 17 17 03](https://cloud.githubusercontent.com/assets/6364153/19974639/680889ba-a1e9-11e6-86b7-b6a77441bc36.png)

**Comment by danicatalan** [comment]
![gfks6caxi6](https://cloud.githubusercontent.com/assets/6364153/20484941/d187c9e6-aff9-11e6-948b-c93b663a5e17.gif)

**Comment by txau** [comment]
@danicatalan awesome. How does it work in mobile?

**Comment by danicatalan** [comment]
Without hided information - title above the metadata info:

![screenshot 2016-11-21 17 58 41](https://cloud.githubusercontent.com/assets/6364153/20492208/2f6024ea-b014-11e6-8c81-c76511db9de5.png)
