### ISSUE TITLE
Improve dropdown on SortBy component

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#591]
Dropdown interaction is very difficult because some design problems:

- [x] Direction arrow is the same as the dropdown arrow, so the user tends to click that arrow if he wants to expand de dropdown options, not to change the direction order.
- [x] Dropdown options renders buggy: moving all the labels, spaces and icons inside the contextual box. We need to check the contextual box CSS in order to improve the interaction when opening the dropdown.
- [x] When the user clicks inside an option on the dropdown, the direction order changes to the oposite. Remove that behaviour: all direction changes must be on the arrow.

**Comment by RafaPolit** [comment]
Resolved as part of #590
