### ISSUE TITLE
Couple of UI glitches

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#593]
- [x] White label on a document type.

![screen shot 2016-11-11 at 18 51 16](https://cloud.githubusercontent.com/assets/489831/20224669/e45c194e-a83f-11e6-8bd0-e8209aaeb847.png)

- - - - - -

- [x] Break line on sidepanel footer.

![screen shot 2016-11-11 at 18 51 19](https://cloud.githubusercontent.com/assets/489831/20224670/e45d21cc-a83f-11e6-86a8-61c989b21cf5.png)

**Comment by danicatalan** [comment]
The first issue was because I changed the default label style (**.item-type-0**) from primary colour to empty colour.

We need to discuss if we keep 0 as empty item (and start counting from 1), or if we keep counting from 0 and create a new **.item-type-empty**.

**Comment by danicatalan** [comment]
Discussed this with @daneryl and we have created a new class called **.item-type-empty**
