### ISSUE TITLE
Some UI glitches strikes back

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#601]
- [x] Item type label limit.

![screen shot 2016-11-15 at 12 16 55](https://cloud.githubusercontent.com/assets/489831/20303898/e1b35da6-ab2d-11e6-89d7-21d11793f84a.png)
- - - - -
- [x] Multiselect counter color.

![screen shot 2016-11-15 at 12 17 10](https://cloud.githubusercontent.com/assets/489831/20303900/e1b48208-ab2d-11e6-917a-d429e3dcf5c8.png)
- - - - -
- [ ] Sort by doesn't show Property name on sidepanel.

![screen shot 2016-11-15 at 12 19 08](https://cloud.githubusercontent.com/assets/489831/20303899/e1b4650c-ab2d-11e6-9930-7343a14481d5.png)

**Comment by danicatalan** [comment]
@RafaPolit I fixed the first issue on this commit: https://github.com/huridocs/uwazi/commit/46bdc72c080a0684f4ec1f0d69e3799a23587f8c

All wrappers must have the **item-label-group** class to limit the label width. Please check my commit to review if we need to add that class in other places.

![screenshot 2016-11-15 12 33 24](https://cloud.githubusercontent.com/assets/6364153/20304312/bda65c2c-ab2f-11e6-8ab1-89d792489447.png)

**Comment by danicatalan** [comment]
@txau for the second issue, I think the most reasonable approach y to change all results to grey and just use primary colours on hover (border) or selected filter (background).

![screenshot 2016-11-15 12 46 09](https://cloud.githubusercontent.com/assets/6364153/20304662/bdf4a22c-ab31-11e6-9120-d11e9d1782f9.png)
![screenshot 2016-11-15 12 45 09](https://cloud.githubusercontent.com/assets/6364153/20304663/bdf4d300-ab31-11e6-9961-5d4123ed0ad0.png)

This works pretty well on every color scheme and also we don't need custom code for every instance.

**Comment by txau** [comment]
@danicatalan agree

**Comment by danicatalan** [comment]
@RafaPolit for the last issue, I checked and any option has a **.is-active** class, so the selected option doesn't not appear:

![screenshot 2016-11-15 12 52 09](https://cloud.githubusercontent.com/assets/6364153/20304777/63fd23f6-ab32-11e6-9cf7-b79bb75cb4af.png)

I don't know how to pass that argument into the **Sort-By** component. This is the code on _DocumentList.js_ for the library:

`<SortButtons sortCallback={this.props.searchDocuments}/>`

And this is from _EntitiViewer.js_ for entities:

`<SortButtons stateProperty="entityView.sort" />`

**Comment by danicatalan** [comment]
@konzz I've been talking with @RafaPolit and we saw that entity reference sorting is broken by the addition of **.raw** to every property. This should be configurable on the instance of component.
