### ISSUE TITLE
Sort by doesn't show Property name on sidepanel

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#630]
- [ ] Sort by doesn't show Property name on sidepanel.

![screen shot 2016-11-15 at 12 19 08](https://cloud.githubusercontent.com/assets/489831/20303899/e1b4650c-ab2d-11e6-9930-7343a14481d5.png)

**Comment by danicatalan** [comment]
Extracted from #601.

**Comment by txau** [comment]
@konzz I think this has been fixed in https://github.com/huridocs/uwazi/pull/624 ?
