### ISSUE TITLE
Improve text actions menu

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#631]
- [x] They appear in the document mid-screen.
- [x] All three are shown at the same time (not green "+" button).
- [x] Remove label and replace with a tooltip (the good one).
- [x] Check position when sidepanel is opened.
- [x] Float Save button on the mid-screen when user is creating a reference.
- [ ] Keep view sidepanel button when text is selected.
- - - - -
- [ ] Nice to have: Add keyboard shortcut, explain shortcut in tooltip.

**Comment by danicatalan** [comment]
- [ ] Check position when sidepanel is opened.
- [ ] Float Save button on the mid-screen when user is creating a reference.
