### ISSUE TITLE
Side panel default behaviour is open

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#634]
- [ ] In library shows filters by default.
- [ ] In library metadata shows on the top of filters.
- [ ] In document its always open.
- [ ] In mobile, we have floating button and side panel can be hidden.
- [ ] On first load, document shows table of content by default (if not empty), otherwise metadata.

**Comment by danicatalan** [comment]
A first approach to solve this issue on library:

![screenshot 2016-12-19 18 19 00](https://cloud.githubusercontent.com/assets/6364153/21322043/a98c2228-c617-11e6-9a82-2b267bb9a49e.png)

**Comment by txau** [comment]
Canceled in favor of other solution
