### ISSUE TITLE
Display all tabs in library's side panel

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#635]
- [ ] table of contents
- [ ] connections
- [ ] metadata
- [ ] text references
- [ ] attachments

- Keep in mind that you can't create TOCs or text references from library.
- Disable click on TOC or text reference. You need to open the document first.

**Comment by kjantin** [comment]
Before this issue was addressed, what was the behavior? Was it only the "information" tab that was displayed when you were in the library? Is this about what tabs are displayed on the right sidebar after you click on a card in the library? Thanks for clarifying!

**Comment by konzz** [comment]
Exactly, only "information" tab was shown when you click on a card in the library, now we load all the tabs available for that card, for example, documents will have "table of contents" tab where the entities wont.
