### ISSUE TITLE
Support OCR

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#64]
Add OCR capabilities to uploads section

**Comment by kjantin** [comment]
Hey @txau, people are still requesting this - can I re-open it so that others can follow along with the progress?

**Comment by RafaPolit** [comment]
We have talked over this and we have signaled out two stages for this development's MVP:

### Stage 1
- Single button on the Document Viewer (for each PDF that could be accessed) that triggers the external service for OCRing.
- It replies immediately with a "OCR in progress"
- The "task manager" will eventually callback with some sort of socket interaction with the client when finished

### Stage 2
- Create a window that lists the Files in the collection and, ideally, knows which PDFs fail to pass an "already OCRd" check
- That window should allow to Filter a bit to get to a desired group of files
- It should have a button to OCR a particular file

**Comment by txau** [comment]
Defined and under development in #4058
