### ISSUE TITLE
Can't publish uploaded documents

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#641]

**Comment by RafaPolit** [comment]
@txau I have run some tests and I am 99% sure that this is working correctly when the App stack is working as expected.

If logstash is not running though, the sync with Elasticsearch is lost and newly published documents, changes made to existing documents and document deletion is not reflected in the library.

The case of the publishing is particularly difficult, as the entity has no way of being accessed other than the library, where it will NEVER show up.  Its in the DB, but elastic ignores it completely.

This will require a logstash restart, but, the worst part, is that the elastic index needs to be reindexed, and the several attempts of creating documents will probably show duplicated documents.
