### ISSUE TITLE
Change "source document" to a more meaningful label

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#649]
I like the label "The document you are reading". We should also remove the bounding box. Is not a doc type tag, is other kind of info.

![screen shot 2016-11-22 at 00 41 12](https://cloud.githubusercontent.com/assets/489831/20505324/6d774e4c-b04c-11e6-9a48-539eae767862.png)

**Comment by danicatalan** [comment]
I've tried with "You are reading this document", I don't know why but I think it sounds more confident.

![image](https://cloud.githubusercontent.com/assets/6364153/20625000/95ede720-b310-11e6-9c96-1a269f70d1a8.png)
