### ISSUE TITLE
Give some love to the metadata form in Uploads

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#655]
- [x] Form header height.
- [ ] Multi-date fields (custom code for CEJIL).

![screen shot 2016-11-22 at 01 10 05](https://cloud.githubusercontent.com/assets/489831/20505920/8bf46aea-b050-11e6-9375-53819c0b1be6.png)

**Comment by danicatalan** [comment]
I mainly replaced the red button to delete dates with the one integrated inside the date. On date ranges, this icon is on the right side, outside the inputs.

I also changed the add button location and color to one more intuitive and with explicit labels.

![image](https://cloud.githubusercontent.com/assets/6364153/20666057/a44a12d6-b562-11e6-9a2b-eb211d04e0ef.png)

![image](https://cloud.githubusercontent.com/assets/6364153/20666012/5c67b61c-b562-11e6-8b61-48f27889db06.png)
