### ISSUE TITLE
Replace floating menu with our new menu design in Uploads

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#656]
- Watch out icon colours too. They should be blue for action, green for additions, red for deletions.

![screen shot 2016-11-22 at 01 10 20](https://cloud.githubusercontent.com/assets/489831/20505966/d47a758e-b050-11e6-8a4b-8c929670b47d.png)

**Comment by danicatalan** [comment]
I've switched from the floating button component to the sidepanel menu component.

![screenshot 2016-11-22 19 11 43](https://cloud.githubusercontent.com/assets/6364153/20535996/89d7c5c6-b0e7-11e6-98c3-cbe29ded6a7c.png)

@RafaPolit all the functionality was on **UploadsMenu.js | 46**.

**Comment by danicatalan** [comment]
We need to deploy this issue before #631 cause floating button is shared in both issues.
