### ISSUE TITLE
Validate home page

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#662]
Users configuring a non-existent home page break their apps.

- Clarify how this field should be used in settings.
- Call it landing page?

**Comment by danicatalan** [comment]
I think the best approach here is to join **Account** and **Collection** in just one section and use the collection URL as a base for the homepage input. Also we remember the user is doing Uwazi configuration repeating "you Uwazi collection" on little descriptions below the inputs. I think it's a straightforward path for the user and the configuration form keeps more consistent and less fragmented and this helps to understand what you're configuring.

![image](https://cloud.githubusercontent.com/assets/6364153/21811725/06fb5556-d751-11e6-914f-c751c1ecccc6.png)

**Comment by txau** [comment]
@danicatalan I think we shouldn't merge them. At some point users other than administrators will have accounts as well but they won't have permissions to modify the collection settings.

How about:

- We add the prefix "http://..." as shown in the design.
- We further clarify how to use this field with even more complete explanation in the hints.

**Comment by danicatalan** [comment]
@txau that's right, but we need to be very meticulous splitting this section in two - one for admin configuration and other for user configuration (admin will have both).

However this will not affect the current problem. I think the easiest way to fix this is with an alert below the input, like in "Menu" section. This attach is a quick approach with the idea:

![home-settings](https://cloud.githubusercontent.com/assets/6364153/22023518/c2441026-dcc6-11e6-88b3-ff05035dcd25.png)

If we think this is the best way to solve this problem, I think the design challenge is to improve this alert (in both "Collection" and "Menu" section), with better text explanation and styles.

**Comment by konzz** [comment]
Change the label "HOME PAGE" to "LANDING PAGE"

**Comment by konzz** [comment]
@txau copy for the explaining text?

**Comment by txau** [comment]
"The landing page is the first thing users will see when visiting your Uwazi instance. You can use any URL from your Uwazi instance as a landing page, examples:

- A pages: /page/dicxg0oagy3xgr7ixef80k9
- Library results: /library/?searchTerm=&filters=%7B%7D&order=desc&sort=metadata...
- An entities: /entity/9htbkgpkyy7j5rk9
- A document: /document/4y9i99fadjp833di

Always use URLs relative to your site, starting with / and skipping the https://yoursite.com/."

**Comment by konzz** [comment]
@danicatalan the progress for this is in the branch 662-collection-improvements it needs some styling

**Comment by danicatalan** [comment]
@konzz branch updated with those styles.
