### ISSUE TITLE
The tooltip showing up without overing the text feels unnatural

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#665]
Can we make it happen only when overing the text?

![screen shot 2016-11-23 at 17 57 02](https://cloud.githubusercontent.com/assets/489831/20571103/7ab37706-b1a6-11e6-8373-7360439a46f7.png)

**Comment by danicatalan** [comment]
I fixed this in https://github.com/huridocs/uwazi/issues/638 because I felt the same and it was a quick CSS change.

Edit PR to reference this issue.
