### ISSUE TITLE
Add tooltips (with translations) to each of these buttons

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#666]
![screen shot 2016-11-23 at 18 03 20](https://cloud.githubusercontent.com/assets/489831/20571304/32a29d88-b1a7-11e6-9a76-8888c273c3a8.png)

**Comment by danicatalan** [comment]
![74romt8mw0](https://cloud.githubusercontent.com/assets/6364153/20632402/82ee018c-b33d-11e6-839e-4cd112548fb7.gif)

**Comment by danicatalan** [comment]
Pending translations.
