### ISSUE TITLE
When navigating to a text reference in a document from another document it should scroll down to the reference

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazi#687]

**Comment by vasyugan** [comment]
I was't aware of this bug report, sorry for the duplication in #2237  . But I would have questions why this is "low priority". My understanding is that the ability to have cross references is one of the core features of Uwazi. 
This is one of the things I am really struggling with at the moment, trying to use Uwazi to build up a collection of quotes from various documents about the same subject. Very often, when reading the quote one will want  to quickly check out the context, and at this moment this takes the step of finding it in PDF documents which in our case are often over a hundred pages.

**Comment by RafaPolit** [comment]
- [ ] The Text reference should also be a URL

**Comment by vasyugan** [comment]
Why has this been closed? Last I checked, clicking a reference still doesn't take one to the referenced paragraph but only to the beginning of the document.

**Comment by txau** [comment]
@vasyugan while double checking this functionality I realized we have a bug. I'm opening a new issue (https://github.com/huridocs/uwazi/issues/3016) and keep track of this requirement on that other issue as well.
