### ISSUE TITLE
Improve sorting

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#706]
- [x] The sorting menu will only provide properties from entity/doc type from the list (sortable properties available).
- [x] When a property is selected for sorting, the property will always appear in the card.
- [x] If the card has the property with empty value, users will get a hint in the card.
- [x] If the card has not the property selected for sorting, it will give a feedback message in the style "This item has no X property".
- [x] Change "Upload date" to "Date added" in cards.
- [x] Change "Recent" to "Date added: Recent" and "Date added: Latest" in sort menu.
- [x] Change "A-Z" to "Title: A-Z" and "Title: Z-A" in sort menu.
- [x] Remove direction arrow from sort menu.
- [x] When an item has empty property or has no property, they always appear at the end, regardless of direction of the sorting.
- [x] FIX: Keep selected property first when dropdown is displayed.

**Comment by danicatalan** [comment]
![image](https://cloud.githubusercontent.com/assets/6364153/21357521/b358efd4-c6d5-11e6-8346-f246295782f6.png)

**Comment by danicatalan** [comment]
![image](https://cloud.githubusercontent.com/assets/6364153/21357690/7232e9fa-c6d6-11e6-843f-de10ad1a888e.png)

**Comment by RafaPolit** [comment]
Important:

- [x] pages should have their own sorting criteria passed to the Docs, not using the global search sorting params.

**Comment by RafaPolit** [comment]
All described functionality is now implemented.

Some issues that arose during development have been implemented as well, there is one missing:
- [ ] Configure document-type filter selector to also 'reset' the sort property to 'default' if the clicked template does not have the sortable property.

Current implementation makes the sorting buttons dissappear when no valid property found.  I am not developing a 'case' for that scenario as it would be imposible to achieve once the above functionality is implemented.

**Comment by RafaPolit** [comment]
@konzz As discussed in the sprint planning meeting, elastic search is ordering as expected when the document is missing the property.  It is, however, not working as expected when the document has the property but the content is empty.

Can we pair-program this? Thanks.

**Comment by txau** [comment]
- [ ] Add an X for closing the modal
- [ ] In order to disambiguate the ordering criteria in cards, its rendered with the same color as the sort text.
- [ ] Will try to keep current sorting criteria, either coming from user selection or priority sorting. If its not possible, will use priority sorting.

**Comment by danicatalan** [comment]
This kind of button don't usually have a closing button. They can be closed if the users clicks out the box.

![image](https://cloud.githubusercontent.com/assets/6364153/22114059/83485fe6-de68-11e6-8404-c9d61a19b91a.png)

@txau If clicking out the box is complex to develop, this is the way we need to implement with a closing button:

![image](https://cloud.githubusercontent.com/assets/6364153/22114017/641483ca-de68-11e6-863f-48a48eedc98c.png)

**Comment by RafaPolit** [comment]
That is exactly what @txau was referring to.  That is the X! We also need to make it so that it closes when you click outside, but that will take a little longer I think.

**Comment by RafaPolit** [comment]
- [ ] Fix in-line checkbox CSSs for new FORM
- [ ] Define final text for tooltip in template creation
