### ISSUE TITLE
Open sidepanel by default on Document Viewer

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#713]
- [x] If a user opens the document viewer in desktop, the sidepanel is opened by default.
- [ ] The first tab shown is the TOC.
- [ ] Keep the floating button on mobile.

@txau review this if you think we need to add something more.

**Comment by RafaPolit** [comment]
I don't hink having the TOC as first tab is a good idea.  Every document has info, not every document has a TOC.

Mobile specifics will be dealt on a second iteration of this functionality, as several side panels are not working on mobile for the time being.
