### ISSUE TITLE
Nested thesauri

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#720]
Some users have request the possibility of having nested dictionaries.

**Comment by danicatalan** [comment]
We need this for Region / Cities in zorla, right? @daneryl

**Comment by kjantin** [comment]
Estimate: 2 weeks (user design, development, testing, feedback)
Decision: We'll address this feature request when it is required from a partner.

**Comment by danicatalan** [comment]
Minority Forum also needs this feature for their thesauri.

**Comment by txau** [comment]
There are a series of thesauri related issues that we could address during this development:

https://github.com/huridocs/uwazi/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+dictionary
