### ISSUE TITLE
Filter's reset button should also reset search

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#723]
![image](https://cloud.githubusercontent.com/assets/489831/21769879/235e9a8a-d681-11e6-848c-0b892f85fddc.png)

**Comment by kjantin** [comment]
Can you explain what the original issue was?

**Comment by konzz** [comment]
@kjantin the filters form in the library section has a reset button that resets all the selected filters, but the search box at the top of the form was not reset by this button.
