### ISSUE TITLE
Floating action button in library, uploads and viewer should be almost the same

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#73]
Library:
- View metadata
- Edit metadata
- Delete document
- View document

Viewer:
- View metadata
- Edit metadata
- Delete document
- View relations

Uploads:
- Delete document
- View document
- Publish document
- Save metadata

**Comment by danicatalan** [comment]
@daneryl take a look at https://github.com/huridocs/uwazi/issues/10

This is the issue I talked to you other day related with the menu. I think it's a good idea to schedule a call both of us to review both issues together, let's talk about it on the sprint.

**Comment by konzz** [comment]
Solved with #213
