### ISSUE TITLE
Add some margin to bottom left panel

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#732]
Some info displays too close to the margin and its sort of hidden to users. Adding some margin may mitigate this effect:

![image](https://cloud.githubusercontent.com/assets/489831/21992887/35af534a-dbe6-11e6-8f0c-2e5c149a39e4.png)

**Comment by danicatalan** [comment]
There was a tricky CSS to add a padding if the sidepanel has a footer. I removed this so know the sidepanel always have the same padding. The code is much more clean and it solves the issue.
