### ISSUE TITLE
Clarify search box

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#733]
Maybe add a magnifying glass or some other visual hint?

![image](https://cloud.githubusercontent.com/assets/489831/21992928/6a9bb418-dbe6-11e6-85d8-c1bec7863352.png)

**Comment by danicatalan** [comment]
@txau agree with that. I think we also need to do some quick fixes into the suggester:

- [ ] Text alignment
- [ ] Blank spaces
- [ ] Box shadow
- [ ] See all documents button

![image](https://cloud.githubusercontent.com/assets/6364153/21997024/493d1748-dc2d-11e6-8665-53d1e96903c1.png)

What do you think?

**Comment by txau** [comment]
Ok. Go for it.

Please take into consideration that text in bold is supposed to represent the matching text. Maybe we could use a more explicit highlight?

**Comment by txau** [comment]
@danicatalan related to the conversation we had earlier. Search boxes should be consistent in every view.

**Comment by danicatalan** [comment]
We've perform visual improvements on the overall searchbox and search suggestions:

![image](https://cloud.githubusercontent.com/assets/6364153/22393062/254f4414-e501-11e6-9b85-c95860455fca.png)
![image](https://cloud.githubusercontent.com/assets/6364153/22393066/304c541a-e501-11e6-8dde-46fb50412691.png)

Other improvements we're made on interaction: placeholder and reset button appearance has been improved, making the searchbox more usable.
