### ISSUE TITLE
Cannot (easily) delete "Multi Select" default text when editing Multi Select field

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#761]
When I try to add a Multi-select field to my document type: HURIDOCS Manuals, I can't seem to delete the "Multi Select" text that is in the Label field by default. I can’t highlight without moving the entire box, and I can’t move my cursor by clicking my mouse (which is really weird). I can only move the cursor by using the arrows on my keyboard. 
﻿﻿
![image](https://cloud.githubusercontent.com/assets/354426/22441081/e1739e20-e703-11e6-83b5-8c2f0f2dd700.png)

What would be ideal is if that text disappears when I put my cursor in there.

**Comment by RafaPolit** [comment]
This is a known issue. It's an annoying behaviour. Dragging should be disabled inside the input so you can select text, be it fully or partially.

Deleting the text could be an option only if the default text is present, but not if the name has already been customized.

This needs fixing.

**Comment by danicatalan** [comment]
This is happening on Firefox. Chrome works fine.

**Comment by txau** [comment]
Fixed
