### ISSUE TITLE
Dictionary stuck on "Testing dictionary" options on a new multi-select field that should be referencing another dictionary

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#762]
I created a new dictionary called "Language". I added a few languages as items within this dictionary. I assigned this dictionary to a multi-select field called "Language". But when I try to select a language for my document, I only see the list of items from the "Testing dictionary" - it's like it's stuck there. I double checked that I had the right dictionary there, and I do. 
![image](https://cloud.githubusercontent.com/assets/354426/22441574/f67c409a-e705-11e6-8b18-946960acd0dc.png)

**Comment by RafaPolit** [comment]
Actually, this goes a bit deeper: the property's thesaurus is not changing.  If you change it to the test dictionary and refresh the page, it shows the same language thesaurus as selected. This is wrong.

We just updated the form library, a deploy could fix this issue. Will look into it further.

Thanks for the report,
Rafa.

**Comment by RafaPolit** [comment]
@kjantin can you please confirm that this is fixed in your instance with the new version?

Thanks.
