### ISSUE TITLE
Unable to change document type during editing (in uploads as well as in library)

### ISSUE THREAD

**Issue by UjoNyawara** [huridocs/uwazi#763]
When editing a document, if I change document type, the info tab freezes and goes blank. I'm unable to do anything beyond this point. Humphrey and I are working on the PALU/ Humphrey's Instance in preparation for a PIL training and are unable to work on the documents.

![freezing-error](https://cloud.githubusercontent.com/assets/1784894/22473342/a43dc0c6-e7e9-11e6-9ab5-7adc328071d5.jpg)

**Comment by txau** [comment]
Hey @UjoNyawara ! thanks for reporting.

@RafaPolit @daneryl give some priority to this please.

**Comment by konzz** [comment]
@UjoNyawara @txau the instance has been redeployed and now is working fine, apparently we didn't detect this bug, but it was fixed with the recent changes to the form library.

**Comment by HSips** [comment]
Thanks guys. I am now able to edit on both PALU and Humphrey instances.
