### ISSUE TITLE
Text selection doesn't keep highlight

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#764]
When the user is creating a text connection, the visual selection of the text is lost if the user clicks outside any element.

![pe7g1hljca](https://cloud.githubusercontent.com/assets/6364153/22478692/4b7cbb0c-e7eb-11e6-9b98-1f3f945cd594.gif)

You can see in the avobe screenshot that "**Superman**" was selected but if the user occasionally clicks outside any input, the text highlight disappears. Users think they lost the selected text and they start again the process.

**Comment by txau** [comment]
This on is tricky because at the same time users expect to clear the selection when they click outside of the selection.

**Comment by konzz** [comment]
@danicatalan @txau Should we close this one, or we intend to change this behaviour?

**Comment by danicatalan** [comment]
They expect the selection to be cleared if they are not creating one piece of information related with that text. In my opinion, text should keep it, because if not you are loosing the context while creating the connection.

**Comment by danicatalan** [comment]
Not to implement now, closing this.
