### ISSUE TITLE
Update connections search box

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#765]
Update the styles on the Connection searchbox with the new created for the library.

**Old styles**

![image](https://cloud.githubusercontent.com/assets/6364153/22478941/40d6fcde-e7ec-11e6-82a1-b05acbc15dd8.png)

**New styles**

![image](https://cloud.githubusercontent.com/assets/6364153/22478948/4afef2ac-e7ec-11e6-844b-7fb5fccd2425.png)

**Comment by txau** [comment]
I think we need to improve the overall interaction there.

**Comment by danicatalan** [comment]
We will review this while improving the overall connections.
