### ISSUE TITLE
Buggy behaviours on sidepanel

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#768]
When the user is navigating between documents, if he tries to edit one in the Library and doesn’t save that document, the “edit” state is saved.

This means if he enters the document, come back to the library and open the sidepanel of another document, the state saved it’s loaded, creating a buggy behaviour on the sidepanel.

![ugoewr0xwp](https://cloud.githubusercontent.com/assets/6364153/22479764/4a981cdc-e7ef-11e6-8e35-8f8361fc3e42.gif)

**Comment by txau** [comment]
This is not causing data consistency errors. I guess we can close for now.
