### ISSUE TITLE
Improve table CSS

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#773]
As you can see, there is a misalignment.

![image](https://cloud.githubusercontent.com/assets/489831/22513563/9aeaa684-e86a-11e6-81c8-aa2eb08cfcc0.png)

**Comment by konzz** [comment]
@txau this is fixed in the improvements to the violated articles field, once it gets deployed to cejil it will be fixed

**Comment by danicatalan** [comment]
Thanks @konzz.

I'm gonna merge a PR with a little improvement on the table CSS (a property to display all the columns with same width). Aside from that, we can close this issue now or when it's deployed to Cejil.

**Comment by danicatalan** [comment]
Fixed in Cejil, I'm closing it.
