### ISSUE TITLE
Double click on a card to open it?

### ISSUE THREAD

**Issue by whyfrycek** [huridocs/uwazi#776]
When working with Uwazi collections, because of the look and feel of the cards, it is not always obvious to me how to open it (the small document button may not be enough). One thing I have tried is opening them on double click. Not sure, but maybe that would help? Possibly, the solution is different altogether, however.

**Comment by txau** [comment]
@danicatalan we could add double click, still I think our current approach is better than just opening the document on click.

**Comment by danicatalan** [comment]
We talked about this idea on #638 and I'm convinced it will work pretty well.

I've checked this behaviour and Google Drive does this way. Combined with the **Open** button on the sidepanel, I think this would be a killer feature.

**Comment by danicatalan** [comment]
Closing in favor of #756.
