### ISSUE TITLE
Find a solution for bi-directional connections and their labeling

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#777]
@kjantin Has brought back the notion of having better labels regarding the "directionality" of the connections:  a judge 'signed' a document, but a document 'was signed by' a judge.

She has mentioned how Drupal solves this by creating 'per connection' labels.  We could actually use a per-template label when that connection is created.

We should begin discussing this and evolve the solution for when it gets implemented.

**Comment by txau** [comment]
Duplicated. https://github.com/huridocs/uwazi/issues/983
