### ISSUE TITLE
UX for showing references

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#78]
- [x] Add title and close icon
- [x] On displaying references panel, always show all references
- [x] Focus visually the reference that you are hovering or selecting. (highlight or something in the right panel too)
- [x] References are not highlighted in text when they are not select/hover (so no introducing noise into the text)
- [x] On hover on the text, we highlight when there is a reference
- [x] On click on the highighted text, we show the reference(s) on the right panel
- [x] On click on the markers, it will highlight the referenced text
- [x] On lick on the marker, it will show the reference(s) in the right panel
- [x] Remove icons from the reference cards
- [x] Switch relation type to just the label of the relation. So instead of "This oducment is based on...blabla" we will have just "Based on".
- [x] On click on the reference in the side bar, in will always scroll to that reference in the text.
- [x] On click on the reference text in the document, it will always scroll to that reference card on the side bar.
- [x] When the user clicks on a relationship inside the document, make scroll to this card if it's not focused on the sidebar.
- [x] If its a reference to a paragraph, we scroll directly to that paragraph
- [x] Use the same design as uploads/library for reference cards. Including the open document icon.
- [x] Remove "Comment" and "Bookmark" actions from the action button on text selection
- [ ] On text selection, change "Floating action" button color, so its more explicit. (Add animation?)

**Comment by danicatalan** [comment]
@txau the last point don't belong to this story - it's for this one: https://github.com/huridocs/uwazi/issues/79

Otherwise I've checked all other insights and they're complete. I'm gonna record the video and upload it to assets. I will notice you when this is done.

**Comment by danicatalan** [comment]
@txau the last point don't belong to this story - it's for this one: https://github.com/huridocs/uwazi/issues/79

Otherwise I've checked all other insights and they're complete. I uploaded the video on the assets repo: https://github.com/huridocs/uwazi-assets/tree/master/78_showing_references
