### ISSUE TITLE
Be able to open the side panel with the metadata when a card is displayed in a page

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#786]

**Comment by danicatalan** [comment]
Added an image with the proposed functionality:

![screen shot 2017-02-08 at 14 54 54](https://cloud.githubusercontent.com/assets/6364153/22740083/b49717d0-ee0e-11e6-9a2e-9032aaf22f46.png)

I think this is one of the most important features in our app: the possibility to view document's metadata without enter on the document.

@txau the CSS code is already used on library, so we can start developing the functionality if we don't see any other UX implications.
