### ISSUE TITLE
Filtered properties must appear on cards

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#787]
As a user, I need to filter cards by properties (for example, _Countries_), but I can't distinguish which cards belong to each value used to filter:

![image](https://cloud.githubusercontent.com/assets/6364153/22658782/8fa3c26c-ec9b-11e6-9bab-f0ca1811b57f.png)

Maybe a solution is to display those properties in the cards, as we do with Sorting.

![image](https://cloud.githubusercontent.com/assets/6364153/22658830/bea98f10-ec9b-11e6-9fb1-2bc856d4b0d0.png)

**Comment by txau** [comment]
@danicatalan what about having a switch in the filters so the properties are displayed in cards? That way users can select which info they want to see. This was discussed in the past.

/cc @kjantin

**Comment by danicatalan** [comment]
@txau yeah, we talked about this and I think it's an interesting idea we can develop in the future. However sorted and filtered properties must appear always on cards to do not lose the context.

**Comment by txau** [comment]
"However sorted and filtered properties must appear always on cards to do not lose the context."

They must? Not so sure. Think about the implications.

**Comment by danicatalan** [comment]
Maybe we can allow users to hide those properties with the new feature, but the default behavior I suggest is _user clicks on property (to sort or to filter) and this property appears in cards_.

I'm thinking on this example:

- I click on filter by **Country > Ecuador**, and **Country > Perú**.
- I don't see which cards belong to each country.
- I need to active "Country" properties on cards (I also need to know that this feature is available somewhere).

It would be better if those properties are shown by default if I use them. Maybe it would be some cases when the user wants to hide a filtered property, we can let the user hide them.

That way we give them flexibility to customize how they read the data available.

**Comment by konzz** [comment]
@simonfossom Closing this for now
