### ISSUE TITLE
Arabic text not adding

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#789]
I am adding up AU documents which are available in En, Fr, Por and Arabic. I have created a field for 'Full document title' to add the long formal title of the each document. However, the Arabic text is not showing. Not urgent, but something to come round to in time.
See below.
![arabic text not adding](https://cloud.githubusercontent.com/assets/22650647/22671508/aba3f7f4-ecdf-11e6-9f65-84b9e02fa9bf.png)

**Comment by kjantin** [comment]
Is it possible to translate the interface into Arabic as right-to-left configuration?

**Comment by txau** [comment]
@kjantin it is, but this task is big. I think we should delay it until we have a very good reason to implement it.

**Comment by kjantin** [comment]
Moved this issue to #933
