### ISSUE TITLE
Improve the UX for referencing

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#79]
- Add the 3rd step in "reference to a paragraph" case. Showing the (3) step. allows you to go back.
- Push "relationship type" at the top of the sidebar.
- Change radiobutton to select.

**Comment by danicatalan** [comment]
@konzz here is the video about this story, let me know if you have any doubt about it! ;)

https://github.com/huridocs/uwazi-assets/tree/master/79_create_relationship

**Comment by txau** [comment]
Inherited from #78:
- [ ] Switch relation type to just the label of the relation. So instead of "This oducment is based on...blabla" we will have just "Based on".
- [ ]  If its a reference to a paragraph, we scroll directly to that paragraph
- [ ] Remove  the left margin for the "referenced text" snippet inside the card.
- [ ] Unhighlight on closing side panel.
- [ ] When clicking on open document, we open the referred document.
