### ISSUE TITLE
Default properties uneditable

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#790]
There are 2 default properties: 'Title' and 'Date added'.
So I was thinking the 'Date added' is rather confusing when it appears in the Library as for most docs, when it was added to Uwazi is unhelpful data, as opposed to say, 'Date issued' or 'date adopted' (for treaties for instance.
SO I wanted to edit 'Date added' to something else but can't.
How would you advice? See below
![default properties uneditable](https://cloud.githubusercontent.com/assets/22650647/22671844/79245d8a-ece1-11e6-9ce0-1a8bb855ee9b.png)

**Comment by danicatalan** [comment]
_Date added_ a default property that reflects just that: when the document was added to the system.

If you want to use custom dates (like 'Date issued') you can drag a new **Date** property from the right panel. This will allow you to go to a document and select a custom date for the new property - so now, you will have custom dates added to your documents.

Moreover I recommend you to activate two options inside the new property: with **Use as filter** option you will be able to search and filter documents on the library by the date they were issued. And if you check the **Priority sorting** option, all your documents will be ordered chronologically in the library (and not by date added to the system).

**Comment by HSips** [comment]
Cool! Will countercheck those options.
Thanks
warmest

---
Consultant
HURIDOCS, Nairobi

HURIDOCS Secretariat
Rue de Varembé 3
1202 Geneva, Switzerland
http://www.huridocs.org

Humphrey Sipalla http://ssrn.com/author=2593184

**Comment by HSips** [comment]
Hey Dani, 
So I already have the 'Date issued' added. But the 'Date added' still shows on the library, which is the problem because it is confusing. Its confusing because, to the reader looking at the library, there is no indication of what date means what. See below.
![date added-humphrey instance](https://cloud.githubusercontent.com/assets/22650647/22719539/fc178034-edb6-11e6-883d-179523a02bc5.png)

What we need is to be able to edit the 'Date added' so that it doesn't **show to the user**. I have checked on the Pretoria instance and the 'Date added' also shows. 
![pretoria instance-date added problem](https://cloud.githubusercontent.com/assets/22650647/22719632/720f5cee-edb7-11e6-83ea-64bf5a10feff.png)

**Comment by txau** [comment]
@HSips @RafaPolit at the beginning "date added" would only show up if no other property was marked for showing in cards. Obviously this has been overwritten. I think:

- This option should be configurable, as Humphrey is pointing out.
- We shouldn't show this option as default.

**Comment by RafaPolit** [comment]
@txau , that is still true.  This was overridden by the requirement: 'the sorting property shows in card, even if not configured as such'.  So this is true for whatever property you select as the sorting order.  If you select "Title" as opposed to "date added", the date added will disappear from the card.

So what is the desired behavior here? Change the default sorting order? Don't show the date in the card even if selected as sorting?

**Comment by kjantin** [comment]
This has been addressed in #1004
