### ISSUE TITLE
User password recovery process overhauling

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#792]
- The question mark after 'failing' the password is not intuitive. There should be a permanent option to recover password
- When recovering the password, the field asking for email should not be pre-filled with the user name already entered in the field before

**Comment by RafaPolit** [comment]
@danicatalan : 

More use cases that don't seem intuitive:
- Once you have clicked on the 'recover password button', either get back to the regular login, or at least allow the login button to reset the look of the page.

As it is right now,  you can not return to the login form from the reset password form.

**Comment by danicatalan** [comment]
I changed the question mark with a permanent "Forgot password" link. Also updated the logo, I know some of you wanted this so hard :)

![screen shot 2017-05-17 at 17 02 35](https://cloud.githubusercontent.com/assets/6364153/26160959/ddd1a4d8-3b22-11e7-8985-2a8fb37babad.png)
![screen shot 2017-05-17 at 17 03 55](https://cloud.githubusercontent.com/assets/6364153/26160960/ddf90708-3b22-11e7-8016-a7da87baa0aa.png)

The behaviour remains the same, we need to discuss some things:

- Clicking on "Forgot password" reduces the form but keeps the same inputs. Do we want this behavior? We are changing the labels (from User to Email) but the input doesn't change. This is the reason why appears pre-filled with username.
- If we keep the same input, we need to solve how a user comes back to the login. Some solutions:
-- Login button comes back to the previous state (now keeps the recovery password state).
-- When clicking on recovery password button, user is redirected to the previous state. We show the alert on the login page with user + password form.

**Comment by danicatalan** [comment]
I created a PR to merge the new button position for recover password and the updated logo. We will discuss the user flow in a new issue.
