### ISSUE TITLE
Selected property does not display in library card or side panel

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#795]
I have a dictionary called "Language" that I use for a property called "Language". This property is included on the document template "HURIDOCS Manuals" and I have checked the "Show in cards" option. On the document, I have selected "French", but I do not see "French" in the card, nor on the side panel:
![image](https://cloud.githubusercontent.com/assets/354426/22709899/6f9a654e-ed49-11e6-81ce-9e7ab90a8506.png)
(note: you see 2 commas because the 3 items that were there before have been deleted since the new deployment)

I only see "French" in the side panel when I view the document 
![image](https://cloud.githubusercontent.com/assets/354426/22709969/a8356ce6-ed49-11e6-9670-774cc1c406f3.png)

**Comment by RafaPolit** [comment]
This appears to be a bug when previous data exists on the templates and you select a new thesauri / entity as a select or multiselect.

The document gets saved with the ID for the language, but also 'keeps' the previous values, which make no sense given the new thesauri.

We'll look into it.

A quick and dirty fix is to delete the property, save the document, and then creating a new one.  That should fix it, but if you could leave your instance with this data for further debugging it would be useful.

Rafa.

**Comment by kjantin** [comment]
This is being addressed in #798. Will close.
