### ISSUE TITLE
Clicking on the 'view' button of a library card does not cancel the cards click event and is also acting as 'select item'

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#799]
When clicking on the 'view' button of a library card, the click is not canceling the card's 'click' behavior.

This produces the following unexpected behaviors:
- the side panel is showing the item's info when you return to the library
- there are several extra requests made to show the item info in the library, when you are already making those requests on the entity or document viewer.

The event bubble should be stopped to prevent this unwanted overhead.

**Comment by txau** [comment]
@konzz check out for this same behaviour in uploads where you also have more buttons in the cards.

**Comment by RafaPolit** [comment]
This was solved when removing the click event from every Doc and into the isolated library DocumentList component.
