### ISSUE TITLE
Simplify and streamline interface translation using Transifex

### ISSUE THREAD

**Issue by whyfrycek** [huridocs/uwazi#800]
Hello team,

I was wondering, if we can simplify the translation process by using a service like Transifex. Through the OTF, we would probably have access to it for free. That way, we could work with partner organisations, volunteers and professional translators in a streamlined way.

If you agree, @kjantin could handle the sign up there and @txau could look with the team on how to practically implement.

Links: https://www.transifex.com/otf/public/
https://www.opentech.fund/lab/localization-lab

**Comment by kjantin** [comment]
Will research this, but will consider waiting to implement until 1.0 release, because this instance will be more stable and the text won't change so dramatically

**Comment by whyfrycek** [comment]
Another option could be a hosted version of this: http://docs.translatehouse.org/projects/pootle/en/latest/index.html

This is what Jitsi Meet uses. Benefit: free and open source. Would have to think about possible drawbacks - people need to create accounts on yet another service, overhead of management, prettyness of interface, etc.

**Comment by mayeulk** [comment]
Hi, I second the original suggestion, although I suggest Weblate, which can be self-hosted.
I've read:
https://uwazi.readthedocs.io/en/latest/admin-docs/translating-your-collection.html#how-to-translate-the-uwazi-interface
But it shows how to translate your instance.
I found this https://github.com/huridocs/uwazi/issues/3344
but found no link of a common translation platform.
I speak 7 languages and found some untranslated strings here and there... and a few incorrect translations. How can I contribute to translations?
Thank you.
Mayeul Kauffmann
