### ISSUE TITLE
Select and edit multiple files at once

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#806]
_"As a user, I want to select multiple files on the Library and edit their metadata at once. I also want to delete all the documents at the same time."_

- - - -

We have different scenarios here:

- [x] All the files selected are the same document type.
- [x] Different document types on the same selection.

I'm going with the **cmd + click** approach for this story. We will discuss other ways to select documents in a future issue.

**Comment by danicatalan** [comment]
These are the wireframes I explained yesterday with a new level on fidelity - I hope you catch the concept better with this animations.

First of all, this is how we currently edit a single file:

![single-file-full-size](https://cloud.githubusercontent.com/assets/6364153/22936324/71153d18-f2d5-11e6-82a8-4165db1285ef.gif)

Now, how this process will work on multiple files:

![multiple-files-full-size](https://cloud.githubusercontent.com/assets/6364153/22936344/836ebe12-f2d5-11e6-8404-2eed09040aa6.gif)

As you can see, when multiple files are selected, the properties are shared so any change in one property will affect the rest. As first approach for our implementation, I suggest just be able to change:

- The document type when all the selected files are the same document.
- All empty properties (you can see in the animation that _Title_ can't be edited).
- Delete all selected documents (to solve #788).

**Comment by kjantin** [comment]
I understand and it makes sense. Looks good!

**Comment by danicatalan** [comment]
Thank you @kjantin!

I'm going to attach the view when multiple files are selected but they don't have the same doc type and after that, move it to **dev**. Ping me if you have more doubts when developing this!

**Comment by danicatalan** [comment]
Disable edit button when multiple document types are selected:

![animation](https://cloud.githubusercontent.com/assets/6364153/23069667/97a9552c-f528-11e6-8efa-b91a498adc91.gif)

**Comment by txau** [comment]
@danicatalan is not clear to me how do you select multiple files. Is it based in pressing the shift key? Or do we have a button to toggle "Multiple selection"?.

If its the first option, we definitely need to add a tooltip on multiple file selection (how to use shift and/or command/control as any other file system).

Still, how will this work in mobile with no shift/control? Maybe we should go for the "Multiple file selection" toggle right away?

**Comment by HSips** [comment]
Thanks for this!
Will be working on humphrey instance tomorrow and will give feedback!

**Comment by danicatalan** [comment]
@txau in this first stage, I suggested to use a simple combo key (cmd + click on Mac, ctrl + click on Windows and Linux) similar as usual OS selection because is not intrusive with the UI. That way we don't need to think on toggles or other selection systems right now and we can focus on develop the multiple edit feature.

After that, we can test the feature and think with more feedback which is the better way to do multiple selections and communicate to the user.

**Comment by konzz** [comment]
@danicatalan what about mobile devices?

**Comment by danicatalan** [comment]
@konzz we have thought about it (long press click or multi selection toggle) but is something I prefer to develop later because right now all our instance admins work on their documents on desktop, so mobile really don't add as much value as having the functionality working on desktop and being tested by the users.

**Comment by txau** [comment]
@danicatalan Ok for now about the mobile devices. Still, I think we need to add a visible hint "Hold shift/control and click on the cards for multiple selection".
