### ISSUE TITLE
Upload and edit multiple files at once

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#807]
_"As a user, I want to upload multiple files on My files and edit their metadata at once while I'm uploading them."_

- - - - -

This is related to #806.

Will be expanded with more information as the other issue evolves.

**Comment by danicatalan** [comment]
Add animation following the same patron than multiple item selection (806 issue).

![multiple-uploads](https://cloud.githubusercontent.com/assets/6364153/22983551/ba6ae486-f3a2-11e6-8614-6fbf324a92c0.gif)

**Comment by kjantin** [comment]
Yea, this makes sense. It's hard to imagine another way to do it, so if there are pros/cons to this approach versus another one, that would be helpful. But otherwise I think this process makes sense. Thanks for the nice animation!

**Comment by danicatalan** [comment]
This is just a little improvement on the upload section, but pretty useful for our users. There is other way to do it (fill the metadata first, then, upload the docs) but I think it has some cons:

- It's less intuitive because you don't have the documents on the screen.
- It's less intuitive because it's different from the proposed solution on #806. Keeping the same behavior for similar things it's good for UX consistency.
- It's harder to develop for our dev team (we have a lot of things done with this approach).
- It's more scalable: imagine a future where you upload all the documents and click on a "Wizard" button that process the files and matches the metadata with machine learning.

**Comment by kjantin** [comment]
So if I have 250 documents that I want to upload and all should have the metadata "green", I would first be inclined to select the metadata "green" and then perform the upload - but, as long as I can upload all 250 documents and have them accessible as a group (by being able to select "last upload" or something like that) so I don't have to search around for all of them, then this would work fine.  
And yea I like Wizards!

**Comment by txau** [comment]
@kristin I think we need basic ordering in the uploads with at leat two options: title and date added. That way its easy to select the last uploads and perform metadata edition.

@danicatalan overall I find the solution in the animation to be good enough. We can improve when we receive some feedback.

**Comment by danicatalan** [comment]
Move into sprint + dev with the current scope. We will add the sorting functionality on #40.

**Comment by konzz** [comment]
- [ ] Make warning signs orange
- [ ] Update warning copy to "Warning: you are editing multiple files. Fields marked with a <> will be updated with the same value."
- [ ] Allow users to select multiple entities with shift key
- [ ] Move template label to the right in the list of selected documents
- [ ] Fix bug: Select multiple entities, edit, and then select one, the form appears empty
- [ ] Fix bug: After loading the form with some values, they appear in other documents without that value
- [ ] Automatically select all documents after an upload
