### ISSUE TITLE
When adding headings to ToC they appear in all CAPS but should appear in titlecase

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#813]
Good people!!
I met 2 pilots this week and have a number of comments/issues from them. I will put them as separate issues. Hope not a problem :)
1. Table of Contents
1.1 when adding headings to ToC, once you save they appear in all CAPS. Should appear in titlecase
1.2 It does not seem possible to have various levels of headings in ToC. Most documents will have about 4 levels. Can this feature be added (or is it I who doesn't know how to do it :) )

**Comment by danicatalan** [comment]
Absolutely not @HSips! You're feedback it's much appreciated 👍 

1.1. Yeah, they appears in all CAPS because of the font styles. I think we need to improve those styles soon, so please share with us how are you using it and we can see together a better way to render the TOC items.

1.2. You can do it if edit the Table of Content and press the arrows next the titles:
![toc-indent](https://cloud.githubusercontent.com/assets/6364153/23015609/c606889a-f433-11e6-9236-236ae5e5bc11.gif)

**Comment by txau** [comment]
@danicatalan maybe the all-caps option as default is no the best one. What f we modify the default style to not force all caps? If they still want caps they can always type in caps.

@HSips I think your second question is answered by @danicatalan ?

**Comment by danicatalan** [comment]
@txau yes, we are going to better font sizes and not caps by default :+1:

**Comment by danicatalan** [comment]
I've been working a with the TOC style issue. This is how it's rendered now:

![screen shot 2017-02-17 at 16 42 20](https://cloud.githubusercontent.com/assets/6364153/23072128/e56a1258-f530-11e6-8b0e-f3617a0cc344.png)

This is the new proposal, with the next changes:
- [ ] Bigger and bolder fonts.
- [ ] Remove all-caps and italics.
- [ ] Larger indentation to differentiate levels easily.

![screen shot 2017-02-17 at 16 46 03](https://cloud.githubusercontent.com/assets/6364153/23072084/c3f5d986-f530-11e6-974a-cbf5e1c1e2fb.png)

What do you think about it? @HSips @txau

**Comment by txau** [comment]
@danicatalan looks great although I think you should test the design against other TOCs, particularly against one with long titles.

**Comment by HSips** [comment]
I love the second option in screenshot. Let me use it a bit as I find screenshots for the other issue (on spellcheck on properties) and will come back with feedback.
Cool! Will also inform PILnet peoples this is sorted.

**Comment by HSips** [comment]
@txau yes, let me try on long titles in those AU documents and give feedback.

**Comment by HSips** [comment]
I have tried a bit. Seems ok on the first option rendering, though I guess @danicatalan will change to the second. Will keep using and alert if any comment is necessary. Thanks!

**Comment by danicatalan** [comment]
@HSips this change is not implemented yet, it is in design step, and I don't know if you are able to get this new design into your instance to test it before we accept the changes and merge them to all the instances.

I've tried with long texts and renders great. Also you can check some widow words (for example, on "This is the place where they talk about Modern Age") but the TOC readability is still perfect.

![image](https://cloud.githubusercontent.com/assets/6364153/23124651/6706abd4-f76e-11e6-9277-6c5db4af54a1.png)

I think the problem with long texts it's when you edit the TOC:

![image](https://cloud.githubusercontent.com/assets/6364153/23124737/c662c040-f76e-11e6-9527-53e4c66f6f43.png)

We can create a new task to solve this problem, but I think is not critical and we can merge this issue as it is to improve a lot the TOC readability.

**Comment by HSips** [comment]
Thanks too here. Yes, I noticed when I logged in after sending the response
that the second option was not implemented yet. Happy that it works well
with long titles in your testing.
No urgency on implementation. I guess we should not disrupt too much your
normal work priorities. For now, users can continue with their data
organisation work while you implement.
On a separate point. What are 'widow words'?


---
Consultant
HURIDOCS, Nairobi

HURIDOCS Secretariat
Rue de Varembé 3
1202 Geneva, Switzerland
http://www.huridocs.org

Humphrey Sipalla http://ssrn.com/author=2593184

**Comment by danicatalan** [comment]
In Graphic Design, a widow is when a word remains alone in a paragraph. We try to avoid widows with manual breaks to improve readability:

[widow](https://5thcolor.files.wordpress.com/2011/12/widows.jpg)

Widows are usual in Web Design, because the cost of automatically process all the text to avoid a widow is too big, so we try to improve readability with other techniques, like font sizes and margins.

**Comment by txau** [comment]
@danicatalan I think this is good enough for now? Shall we go ahead and merge?

**Comment by HSips** [comment]
Thanks Dani! I am learning!


---
Consultant
HURIDOCS, Nairobi

HURIDOCS Secretariat
Rue de Varembé 3
1202 Geneva, Switzerland
http://www.huridocs.org

Humphrey Sipalla http://ssrn.com/author=2593184

**Comment by danicatalan** [comment]
Merged into development.

@HSips these will be into your instance soon, thanks for your feedback and hope you find it a good improve ;)

**Comment by HSips** [comment]
Thanks Dani. I loved the screenshot already!
Followed the link on widows. I was taught to call them 'hanging lines'.

---
Consultant
HURIDOCS, Nairobi

HURIDOCS Secretariat
Rue de Varembé 3
1202 Geneva, Switzerland
http://www.huridocs.org

Humphrey Sipalla http://ssrn.com/author=2593184
