### ISSUE TITLE
Would like to see total # of pages in PDF, and the page where one is within the PDF

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#814]
When visualising a PDF doc alongside the right hand properties column, it would be great if it would show no. of pages of the PDF, and where one is on along this. Helps when working on a 100 page document.

**Comment by kjantin** [comment]
This will be a great feature, but it is not urgent at this time.

**Comment by HSips** [comment]
Well... I am not sure. I hope the issues raised are not a bother. Is it ok
to raise them?

---
Consultant
HURIDOCS, Nairobi

HURIDOCS Secretariat
Rue de Varembé 3
1202 Geneva, Switzerland
http://www.huridocs.org

Humphrey Sipalla http://ssrn.com/author=2593184

**Comment by txau** [comment]
@HSips totally ok! Please keep the good feedback coming! =)
