### ISSUE TITLE
Spellcheck on properties

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#816]
Spellcheck, as far as I can tell, only works on the default properties/dictionaries, but not on the ones a user selects. Can this be generalised?

**Comment by danicatalan** [comment]
@HSips can you give us more information about this issue, like screenshots and specific use cases?

**Comment by HSips** [comment]
Here's a screenshot.
So the default properties have a spellcheck, but not ones the user selects.
![spellcheck on properties](https://cloud.githubusercontent.com/assets/22650647/23106463/f0e1ae28-f6fe-11e6-8f9e-0ee068f436c1.png)

**Comment by danicatalan** [comment]
@HSips we didn't develop native spellcheck in our system, but seems like some feature in those fields can be blocking your browser to spellcheck the property name.

We are going to test and check if there's a solution to this issue.

**Comment by HSips** [comment]
@danicatalan Thanks.

---
Consultant
HURIDOCS, Nairobi

HURIDOCS Secretariat
Rue de Varembé 3
1202 Geneva, Switzerland
http://www.huridocs.org

Humphrey Sipalla http://ssrn.com/author=2593184

**Comment by kjantin** [comment]
This is not an urgent issue right now, we'll check this when we have time.

**Comment by txau** [comment]
I guess we are not adding spellchecking anytime soon. Closing.
