### ISSUE TITLE
Custom pictures for entities or documents when viewing cards in library

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#817]
As at now, the Library has one visual, a thumbnail type. Is it possible to add a thumbnail pic of a report cover/icon of some kind? If yes, which property type can one add to the document to facilitate this?

**Comment by danicatalan** [comment]
@HSips we've been discussing this some time ago and decide to not support this feature right now. We will return to this at some point, but not sure how are going to achieve this: custom pictures for entities or documents automatic cover for documents...

**Comment by danicatalan** [comment]
I let this opened to share your comment on our Backlog reviews.

**Comment by txau** [comment]
@HSips @danicatalan I think we should implement this feature but it should be automatic, taking the first page of the document as the thumbnail.

This is just cosmetics, it doesn't really add that much value, but many users are going to appreciate the visual boost.

**Comment by HSips** [comment]
@danicatalan @txau agree. This is not an urgent feature. Just raised it as was raised in the meets. I guess we best discuss library visualisation when we have good number of pilots at that stage and can properly compare needs across wider range of users.

**Comment by danicatalan** [comment]
This has been requested by a new project. They want to select a picture to be rendered on cards to display the cases in a more visual way.

Still not urgent feature.

**Comment by danicatalan** [comment]
Thumbnails were designed for AOT, take UI as reference: http://aot.netlify.com/learning

**Comment by txau** [comment]
@HSips this is fixed and will be available after the next deployment.
