### ISSUE TITLE
Link paragraph to entities

### ISSUE THREAD

**Issue by whyfrycek** [huridocs/uwazi#818]
Use case: I have uploaded testimonies in which witnesses describe events and persons. These documents mention for example a particular person "bad person A" in a paragraph. 

I have previously created "bad person A" as an entity.

Now, I would like to link that paragraph with an entity.

**Comment by kjantin** [comment]
Assigned to @RafaPolit in the last call

**Comment by RafaPolit** [comment]
This is already possible, the only problem resides on the wording of the connection: currently it reads "connect to a Document", when, in fact, entities can get selected.

Change the wordings to reflect all options.

**Comment by whyfrycek** [comment]
Yes, just tested, that works. 

However, when starting from an entity, I can only link to other entities or documents, not paragraphs within them. Not sure, if this is a priority, as the most likely user story is starting withing a document, marking a paragraph and linking to an entity, but still.

**Comment by txau** [comment]
@whyfrycek I'd definitely say is not a priority right now. Its a nice to have.
