### ISSUE TITLE
When creating a connection, either relabel "Select Document" or add "Select entity"

### ISSUE THREAD

**Issue by whyfrycek** [huridocs/uwazi#819]
When I open an entity, I want to link it to another entity. I can do that, but the box to search and choose from is called "search documents". This was confusing, as I was not sure whether I can create a link to another entity.

Ideas for solutions:
1) Rename to just "Select"
2) Have separate boxes for entities or documents
3) Have a drop down in search that would allow me to only search for a particular document type/entity (or have this as a separate box

Something like 3) may be helpful eventually, as that would allow me to quickly only go through a list of persons, for example.

![many reports from the internet - chromium_062](https://cloud.githubusercontent.com/assets/7205036/23017729/c4a4c72a-f43b-11e6-835f-3af720ba95c9.png)

**Comment by kjantin** [comment]
Decision: rename to "Select document or entity". Moving to sprint

**Comment by danicatalan** [comment]
Fixed with the proposed renaming:

![image](https://cloud.githubusercontent.com/assets/6364153/23260672/36f90efc-f9d3-11e6-8b68-05adfe633be6.png)

We are studying if we merge or not entities and documents, so maybe we will need to come back here.
