### ISSUE TITLE
Keep the latest upload batch active

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#822]
_"As a user, I want to keep the latest upload batch active, so that way I can easily select all the documents  I uploaded together."_

- - - - - 

I think it's a great idea and we can develop the feature to a more complex system (something like "Upload historic") so you can view and select different batches. We can keep the historic for entities created together.

This was proposed by @kjantin on #807. @RafaPolit also knows some things about how this works on photography software.

**Comment by danicatalan** [comment]
This is related to use filters on Uploads (#40).

**Comment by txau** [comment]
@danicatalan a quick note here. Do we still have the upload progress bar?

If so, we could display it on the right panel as well. Maybe also have some visual feedback for the bulk upload (Uploading 23 of 40 items...).

**Comment by danicatalan** [comment]
When uploading multiple files, keep them selected.

**Comment by konzz** [comment]
To be implemnted in #828
