### ISSUE TITLE
Build out API so that third parties can use it

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#832]
How can someone use the existing Uwazi API? Have instructions been documented?

**Comment by kjantin** [comment]
API has not been developed to be used by third parties at this time. This will be developed after stable release. Changing the title of this issue.

**Comment by RafaPolit** [comment]
API is now accessible from within a working installation of Uwazi on the **/api** route:
http://localhost:3000/api

**Comment by kjantin** [comment]
https://japiqay.uwazi.io/api/
