### ISSUE TITLE
Show metadata on cards inside Uploads

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#837]
_"As a user, I would like to see the metadata rendered in cards inside the Uploads Section, as are displayed on Library."_

- - - - -

- [ ] Render the item-metadata inside cards - like in Library.

**Comment by txau** [comment]
@danicatalan This goes along the line of revamping "Uploads" to "My files". But we need a broader discussion on how this is going to work.

**Comment by danicatalan** [comment]
This will be fixed on #887.
