### ISSUE TITLE
How can one Uwazi collection share documents with another collection?

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#839]
Use case: There is a network of organizations, each organization produces and curates their own documents, but they also want to contribute a few of those documents to a shared Uwazi instance that represents the entire network. What is the best way to have this document live in both places? Ideas:
1. find a way to sync the data between different instances (an API?), or 
2. layered Uwazi instances, where the individual orgs have their own collections within the larger network collection

**Comment by kjantin** [comment]
We are leaning towards option 1, where only changes (aka deltas) are sent from the 'slave' instances to the 'master' instance. ﻿

![image](https://user-images.githubusercontent.com/354426/48016785-843f8000-e0fa-11e8-854c-05b4af504e7e.png)

estimate: 20 days of development

**Comment by txau** [comment]
Solved in https://github.com/huridocs/uwazi/issues/2110
