### ISSUE TITLE
Improve drag and drop box on My files

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#841]
_"When uploading documents into **My Files**,
I want to drag and drop the files in a bigger area than the current box
to make easier the process of uploading the docs."_

- - - - -

Some users reported than the box on Upload is not enough representative - they use to drop the files on the document list (not the box). To improve this feature, we need to:

- [x] Move the upload box inside the item list ([preview](https://cloud.githubusercontent.com/assets/6364153/23364279/c1b4754e-fcfe-11e6-9d5c-7d00fce30628.png)).
- [ ] Let the user drag and drop above the document list.

**Comment by danicatalan** [comment]
I've achieved to move the box inside the list without problems, it was just a HTML div with some static content.

I quickly checked a prototype moving the Dropzone component from UploadBox.js to UploadList.js. It works properly with the imports and the mapDispatchToProps moved to UploadList.js too, but I need a developer to do it the right way, check all the states and maybe remove the UploadBox component because we will not use it anymore.

![animation](https://cloud.githubusercontent.com/assets/6364153/23399981/9ebb2840-fda2-11e6-926c-857fb5fb1ed0.gif)

**Comment by kjantin** [comment]
I'm taking this out of the milestone related to applying metadata to multiple files at once only because it isn't a requirement.

**Comment by daneryl** [comment]
Review Pro tip on the new designs

**Comment by txau** [comment]
I honestly think we can live without this =)
