### ISSUE TITLE
Allow users to select from existing HURIDOCS micro-thesauri for Uwazi "dictionaries"

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#843]
How can we integrate HURIDOCS' existing micro-thesauri into Uwazi to make it easier for users to create Uwazi "dictionaries"? These are the ones that currently exist:

    Huridocs Index Terms
    Violations Typology
    Rights Typology
    Types of Acts
    Methods of Violence
    International Instruments
    Counting Units
    Civil Status
    Education
    Occupations (ILO Categories)
    Physical Descriptors
    Religions
    Ethnic Groups
    Languages
    Geographical Terms
    Types of Source Material
    Types of Locations
    Degrees of Involvement
    Source Connection to Information
    Types of Intervention
    Types of Relationships
    Types of Chain of Events
    Relevant Characteristics
    Types of Perpetrators
    Status as Victim
    Status as Perpetrator
    Types of Responses
    Attribution
    Types of Detention
    Whereabouts and Outside Contact During Detention
    Legal Counsel
    Types of Courts
    Types of Language Used in Court
    Autopsy Results
    Death Certificate
    Statements Signed
    Medical Attention
    Intent
    Sex
    Types of Addresses
    Violation Status
    Reliability
    Monitoring Status
    Impact on the Situation
    Intervention Status
    Priority
    Compensation
    Types of Dates
    Sexual Orientation

All available in Google spreadsheets, and in multiple languages: https://www.huridocs.org/resource/micro-thesauri/

**Comment by whyfrycek** [comment]
This is a great question! For us and our partners, this is obviously very useful.

While at it, I would wonder, if it could be an import of terms from a spreadsheet/csv? This way, we might cover other use cases. It would particularly be interesting to see in what format Dublin core is available (http://dublincore.org/)

What also would be very interesting, but possibly go to far here, is the ability to "share" and make available these and other lists. This would make it much easier to benefit of others' work in customising and "hacking" methodologies.

**Comment by whyfrycek** [comment]
Likewise for http://schema.org/docs/schemas.html

**Comment by txau** [comment]
@kjantin as @whyfrycek pointed out, the way to go is providing support for importing thesauri instead of polluting the application with dozens of thesauri. A simple CSV import/export should do.

**Comment by kjantin** [comment]
Closing this issue because I created a feature request to allow users to import data from CSV: https://github.com/huridocs/uwazi/issues/926

**Comment by kjantin** [comment]
Reopening this issue per @txau. Is the goal of this issue to **allow users to import lists of items for dictionaries via CSV**?

**Comment by daneryl** [comment]
i think we can close this ?, functionality added by #2423 and #2463

**Comment by txau** [comment]
@kjantin as per the above mentioned issues, existing micro-thesauri could be imported (in multiple languages) as CSVs.
