### ISSUE TITLE
Handle indexing errors

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#845]
If an errors happens during a new entity / document indexation, the document wont show up anywhere until a manual re-indexation is done. We need to handle this errors for a re-try.

**Comment by txau** [comment]
@konzz has this been fixed with the latest fixed in ES indexing?

**Comment by txau** [comment]
@konzz comment or close please

**Comment by konzz** [comment]
No, its not fix, it can still happen.

**Comment by txau** [comment]
Related to this:
```
2020-03-18T20:53:20.565Z [bluebird] ERROR Failed to index document 5e728a4050c71b7beb100bf9: {
 "type": "illegal_argument_exception",
 "reason": "Document contains at least one immense term in field=\"metadata.kidnapp_details.value.raw\" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[50, 50, 32, -48, -72, -47, -114, -48, -67, -47, -113, 44, 32, -48, -78, 32, -48, -78, -48, -66, -47, -127, -48, -70, -47, -128, -48, -75, -47, -127]...', original message: bytes can be at most 32766 in length; got 58894",
```

**Comment by txau** [comment]
@RafaPolit I guess while closing the other issues this issue is now obsolete?

**Comment by RafaPolit** [comment]
No, actually it isn't.

Because if an index failed, it is now reporting to client, yes, but it is still leaving the 'ghost' on the database.  So this needs to be done ON TOP of the other issues.

**Comment by txau** [comment]
After considering several options, we concluded that a good-enough solution will be catching indexing errors and setting a flag somewhere in Uwazi (database?). If that flag is present and an indexing problem happened, privileged users will at least know that some data may be out of sync.

**Comment by txau** [comment]
Further discussion concluded that there is not need for transactional integrity for Mongo + Elastic combined operations. While Mongo has to keep data integrity and apply transactions when needed, it may happen that Elastic can fail to index something and gets out of sync, and this is acceptable as far as the problem gets fixed and a reindex is run. In every case, that indexing error should be logged and reported and it is indicative of a bug.
