### ISSUE TITLE
When new items are added to a dictionary, they are not displayed when editing a document

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#849]
I have a dictionary called "Tags". I am using this dictionary to call items for a property called "Tags" on my document template "Huridocs manuals". When I add new items to the dictionary:
![image](https://cloud.githubusercontent.com/assets/354426/23705687/0c03dec4-03d9-11e7-948b-fc1f70f72eb0.png)
...the new items are not displayed when I edit a document - I only see the old items:
![image](https://cloud.githubusercontent.com/assets/354426/23705727/2f248d4a-03d9-11e7-909c-785e625906b9.png)
https://kristin.uwazi.io

**Comment by konzz** [comment]
Already fixed
