### ISSUE TITLE
New approach to "connections": implement "relationship" field

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#853]
A field that appears in metadata a allows users to connect to docs/entities.

**Comment by txau** [comment]
Since its a connection type, we don't need to delete the referred entity, so no cascade deletion.

**Comment by danicatalan** [comment]
This is a must in our app to keep following our connections philosophy.

I'm removing "new" tag and I'm tempted to put the "next" tag because I think this field type will improve a lot the UX and connections will be more useful if we can render them on metadata and cards.

**Comment by danicatalan** [comment]
@txau are we still in for relationships as metadata or should we close this issue until next iterations?

**Comment by txau** [comment]
We are. Do not close this please.

**Comment by txau** [comment]
Duplicate: https://github.com/huridocs/uwazi/issues/1430
