### ISSUE TITLE
When adding TOC items in the default language, they need to appear also in other languages when in fallback mode

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#855]
1. I open a document in Spanish, being the default (fallback language).
2. I add items to the TOC.
3. I navigate to english. The fallback document is displayed (in spanish) since there is no english doc, but the TOC is not being displayed.

**Comment by danicatalan** [comment]
This is affecting now some users, we need to review it soon if it's a straightforward fix.

**Comment by txau** [comment]
This is not working at the moment. Is this properly tested?

**Comment by konzz** [comment]
Did not have integration tests and broke due to some changes, this #1357 is the  PR with the fix and added integration tests
