### ISSUE TITLE
Allow for attachment file title edition

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#859]

**Comment by whyfrycek** [comment]
wondering whether it is desirable at all to offer changing file titles based on metadata?

**Comment by txau** [comment]
@whyfrycek good idea but we have other priorities right now. Sorry =/

**Comment by RafaPolit** [comment]
@whyfrycek Do you mean allowing title suggestions?  Or be able to just pick some of the metadata as name?

**Comment by RafaPolit** [comment]
The current filename for the main document's PDF is derived from the document's Title. Editing the document's title (in the Info tab) successfully updates the main PDF filename.  There is currently no way of separating the document's Title to the PDFs filename.

Work done to explain this in #889

Let me know if I can close this issue for now.

**Comment by danicatalan** [comment]
To allow renaming filenames on attachment, we need to implement the next changes on the interface:

- [ ] Remove "Replace" and "Delete" buttons on every card. Place "Edit" button instead.
![1- attachements](https://cloud.githubusercontent.com/assets/6364153/24868512/8aae1ec8-1e10-11e7-9f22-08f66a42f95b.png)

- [ ] When editing a source file, we place the "Replace" button below the text area with the filename. Remember that this filename won't be connected to the Document title.
![2 - attachements edit source file](https://cloud.githubusercontent.com/assets/6364153/24868511/8aa75336-1e10-11e7-8f40-06b09bebc93a.png)

- [ ] When editing another file, we don't have any replace button. We keep the "Delete" button below the text area with the filename, as in the source file.
![3 - attachements edit extra file](https://cloud.githubusercontent.com/assets/6364153/24868513/8aaebacc-1e10-11e7-8835-6ca2cd2ba120.png)

**Comment by txau** [comment]
@danicatalan how is this going to look like when someone hits reupload? where is the progress bar going to be an what feedback is the user going to receive?

**Comment by danicatalan** [comment]
@txau we don't have that functionality right now, the browser just wait all the process and refresh the new document.

If we want to improve the experience on attachments, we need to create a new issue to keep this one clean with the main story.

**Comment by txau** [comment]
@danicatalan ok, nevermind then. Lets keep it simple for now?

**Comment by danicatalan** [comment]
@txau yes, this feature is adding little value to the app (but is necessary for some of our users).

The proposed doesn't add much complexity to development because I kept all the features (replace document and delete document) as they are right now.
