### ISSUE TITLE
Show full text search snippets on cards

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#861]

**Comment by danicatalan** [comment]
![screen shot 2017-04-11 at 12 48 45](https://cloud.githubusercontent.com/assets/6364153/24905738/3c5078d4-1eb5-11e7-9902-575cbee786d8.png)

I used the same highlight as in search for UI consistency, I can change both highlights if needed but we need to have a call to check some issues:

- Get snippets from the search engine. It's difficult to take decissions (like how many lines are rendered) if I don't have real data.
- How to sort documents (it keeps the default sorting and sometimes is confusing, because a relevance rating is expected).
- Are we searching on Rich texts? A document can have a description and a source text.
- Do we want to highlight the title too?

**Comment by danicatalan** [comment]
This is an evolution of the previous concept adding some interesting features. First of all, we will render the first snippet of text in 2 lines with the keyword highlighted and also a little **+X results** that will help users understand the magnitude of the keyword inside the document.

![search-snippet](https://cloud.githubusercontent.com/assets/6364153/25745467/4a11cb88-319f-11e7-9abc-a1dade943e23.png)

If the user clicks on the card **while performing a search**, all the snippets will appear on the sidepanel. That way a user can review all the snippets without opening the document. Also is very useful if you want to compare over the documents quickly, because you can click on differents cards and see the snippets without loosing your context.

![search-snippet-active](https://cloud.githubusercontent.com/assets/6364153/25745466/4a11500e-319f-11e7-915c-c27888f8f80e.png)

The user can refine the search on the search box inside the sidepanel, but won't affect the global search on the library, just the sidepanel. Clicking on the item, the document opens and the user goes automatically to the page.

Also related to 927, we will keep this sidepanel inside the document so the user won't lose the results and will be able to continue researching inside the doc.

![search-snippet-document](https://cloud.githubusercontent.com/assets/6364153/25745468/4a13edfa-319f-11e7-9cad-41807cb10fef.png)

**Comment by txau** [comment]
This is pretty neat. I like it.
