### ISSUE TITLE
When updating a multiselect value in library the changes are not reflected immediatly 

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#865]
1. Select a library card with a multiselect field.
2. Edit the values (add or delete).
3. Hit save.

You won't see the values updated in the metadata side panel unless you reselect the card.

**Comment by RafaPolit** [comment]
This happens at least with RichText also, perhaps with all the input types.

**Comment by danicatalan** [comment]
Closing this in favour of #1084 because is happening with all properties - not just multiselect.
