### ISSUE TITLE
Improvements on new Entity Connections

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#870]
There are some improvements that remain to be implemented on the Entity Connections interaction:
- [ ] When you delete the last connection of a sub-item which was selected, reset the filters so that that particular template ID is not selected.  If only that particular field was selected, completely reset the fiilters.
- [ ] Make sorting properties update when groupings templates or groups are selected (the sorting options should only include properties relevant to the selected templates, but also if the selected sorting is not a valid option, there should be an update of the sorting criteria as well)

**Comment by txau** [comment]
@RafaPolit how is this being affected by the new relationships?

**Comment by kjantin** [comment]
hey @RafaPolit, do you have an estimate on how long it would take to develop the second feature: 

> Make sorting properties update when groupings templates or groups are selected

SMEX could use something like this for the CYRILLA project.
