### ISSUE TITLE
Implement new Connections UX in the Document Viewer

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#871]
The new Connections implemented on the Entity Viewer should be ported into the Document Viewer.

The current limitation is that the server service that fetches and groups the connections brings ALL the connections, INCLUDED the text connections.  It groups them properly.  We should filter out the non-relevant connections, which are only Text references that belong to this document's text.  Its important to keep in mind that text connections from another document that point out to text of this document should also be filtered out, but those that are text connections pointing to this 'entire' document should be kept!

There are three options to achieve this:
- Filter them in client (probably the worst option and it will involve heavy parsing of the groupings)
- Filter out in server all the text connections that are not relevant without any option to send all the connections.  This could lead to re-implementing further down the road if for any reason we want all the connections.
- Filter out in server with a flag to exclude the current text connections.  This could be a bit more complicated.

Lets talk about this?

**Comment by txau** [comment]
Duplicate: https://github.com/huridocs/uwazi/issues/1430
