### ISSUE TITLE
Include date format help text for user when adding a date using the calendar property

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#872]
If I want to enter the date 13 March 1986, the system requires me to scroll through years of calendar months to find the right date. The user should be able to choose whether they want to type in the date (provide the format in help text) or use a calendar to select the date.

**Comment by txau** [comment]
@kjantin this is already supported. Users can type in the date.

**Comment by kjantin** [comment]
Oops - I realize now that my browser window was too small to access the field to enter a date. Once I made the browser window bigger, I was able to put my cursor into the field. Sorry for the confusion! I still think it would be really helpful to the user to include the date format in help text.

**Comment by danicatalan** [comment]
This can be solved with a simple placeholder as @RafaPolit suggested yesterday:

![image](https://cloud.githubusercontent.com/assets/6364153/26346359/3d0f6016-3fa6-11e7-8517-e86e6af8659a.png)

Is not very helpful with this ugly format (you still need to remember how to write Jan, Feb, Mar...) but it would work great when the input date format is with slash.

![image](https://cloud.githubusercontent.com/assets/6364153/26346497/b04a6f44-3fa6-11e7-8e3b-0697f5105134.png)

What do you think?
