### ISSUE TITLE
Unable to delete demo document "Our Story UwaziDocs"

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#873]
When a new Uwazi instance is created, it comes with a document as a demo called "Our Story UwaziDocs". When I try to delete it, it goes away for about a second, then it comes back. https://hr-reports.uwazi.io/ 
![image](https://cloud.githubusercontent.com/assets/354426/24100490/dd665508-0d4a-11e7-8332-0c5e4275f461.png)

**Comment by kjantin** [comment]
I can delete this now. The latest deployment must have fixed what was going on here!

**Comment by kjantin** [comment]
Ah yes, my good friend the "Our Story Uwazidocs" document is back. :) 
https://hr-reports.uwazi.io/
![image](https://cloud.githubusercontent.com/assets/354426/24169402/e2fe82ba-0e53-11e7-8448-09fa6e6379d7.png)
Again, I can't seem to delete it.

**Comment by txau** [comment]
I confirm the bug. I've observed 2 different behaviours in my instance:

- When trying to delete a document, the document is not deleted.
- When trying to delete an entity, it briefly disappears from the list, the reappears. Reloading effectively removes the deleted entity.

**Comment by RafaPolit** [comment]
Cannot reproduce the first problem.  Deleting either a Document or Entity is correctly deleting the entries in the database.

I confirm the second problem is Elasticsearch replying the results before the entry in elasticsearch is deleted.

**Comment by daneryl** [comment]
"Our story" doc had no real pdf uploaded, (and the server trys to delete it but do not exists so it throws an error) this is a bug on the deployment, looking into that tight now, made a PR to be able to properly delete docs with unexistent pdf. https://github.com/huridocs/uwazi/pull/902
