### ISSUE TITLE
Issues/Errors when attempting to run test_api.sh

### ISSUE THREAD

**Issue by KKNomad** [huridocs/uwazi#874]
Hi,

When I try running the test_api.sh, i get the following errors;

*                    Failures                    *
**************************************************

1) translations process System context should add keys that do not exist into all languages
  - Failed: TypeError: newKeys.includes is not a function
      at /~/~/uwazi/app/api/i18n/translations.js:113:72
      at Array.filter (native)
      at /~/~/uwazi/app/api/i18n/translations.js:113:52
      at Array.forEach (native)
      at /~/~/uwazi/app/api/i18n/translations.js:111:17
      at process._tickCallback (node.js:438:9)

2) translations process System context should delete the keys that are missing
  - Failed: TypeError: newKeys.includes is not a function
      at /~/~/uwazi/app/api/i18n/translations.js:113:72
      at Array.filter (native)
      at /~/~/uwazi/app/api/i18n/translations.js:113:52
      at Array.forEach (native)
      at /~/~/uwazi/app/api/i18n/translations.js:111:17
      at process._tickCallback (node.js:438:9)

3) translations updateContext() should add a context with his values
  - Failed: TypeError: deletedProperties.includes is not a function
      at /~/~/uwazi/app/api/i18n/translations.js:138:72
      at Array.filter (native)
      at /~/~/uwazi/app/api/i18n/translations.js:138:41
      at Array.map (native)
      at /~/~/uwazi/app/api/i18n/translations.js:130:39
      at process._tickCallback (node.js:438:9)

4) references routes GET search should return references limited by the entity they belong to and selected filter
  - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

Anyone who can assist? Thanks

**Comment by konzz** [comment]
Hi @KKNomad, have you done an "npm install" or preferable a "yarn install" before running the tests? The project is in ES6 and you may be missing babel, a dependency for transpiling.

Install [Yarn](https://yarnpkg.com/lang/en/docs/install/) and then run yarn install and try to run the tests again, thanks!

I close the issue if you have any more troubles feel free to reopen it.

**Comment by KKNomad** [comment]
Hi konzz,

Noted. Finally got it to work. Thanks
