### ISSUE TITLE
Mixup the order in which Uwazi selects colors to use for templates

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#877]
Currently, when you create a new template, Uwazi assigned a similar color to the name of the template in the cards:
![image](https://cloud.githubusercontent.com/assets/354426/24106803/6d312050-0d5f-11e7-97ed-9a615ffc642e.png)
It would be better to mixup the order of the colors that the system selects so the colors stand out more if you only have a few templates.

**Comment by danicatalan** [comment]
@kjantin this is not really an UX issue. The real issue that someday we will solve is how a user can select a custom color for every document type.

This is related to how the code is assigning those values. This is our current color palette:

![screen shot 2017-04-10 at 18 13 13](https://cloud.githubusercontent.com/assets/6364153/24871307/742d3720-1e19-11e7-89eb-cb8bfc200523.png)

And colors are assigned this way:

```
The first Doc type has value 0, so gets the c-type-0
The second Doc type has value 1, so gets the c-type-1
...
```

If we want to mixup colors, we need to randomize the assigned colors to each document type.

**Comment by danicatalan** [comment]
Close in favor of #1338
