### ISSUE TITLE
Allow for more ways to find documents/entities when creating connections

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#878]
Currently, when you select a document/entity for a connection, it only searches for text in the title of the document/entity:
![image](https://cloud.githubusercontent.com/assets/354426/24107193/7fd61476-0d60-11e7-9102-0b783e3280f3.png)
It would be helpful to allow for more kinds of search, such as filtering by the document template, full text search, properties, etc.

**Comment by txau** [comment]
@kjantin actually I think this is a broader task related to improving the search box function, not only for connection target look-up but also in library and uploads.

Some ideas:

- Not only titles and text content is searched but also other properties including the template type.
- Highlight the matching text.
- Search both as a group of terms (ie. "My search string") and separate words (ie. "My" "search" "string") while giving priority to the group.
- Add some special commands, ie. if you have a document type named "Report", be able to run a "report: search string" that will search only within reports.

**Comment by txau** [comment]
Duplicate: https://github.com/huridocs/uwazi/issues/1430
