### ISSUE TITLE
Support for embedding YouTube videos in the RichText metadata property

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#879]
A user should be able to embed a video (not just the link, but on-uwazi embed display) from YouTube.

- [x] How to select the video? ID? Link? (Ux)
- [x] Decide best way to display and decide upon the video's size: on cards, on entities, on pages, o document metadata, etc. (Ux)

**Comment by kjantin** [comment]
what is the format that the user will use to embed a video in the rich text field?

**Comment by txau** [comment]
@kjantin I think: {youtube}(URL)

/cc @RafaPolit

**Comment by RafaPolit** [comment]
Yes, that's it. It can be almost any link to the video, but let's instruct users yo navigate to the video, click on share, and then use that URL.
