### ISSUE TITLE
Support for embedding Images

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#881]
Displaying images on the RichText property is already supported, but we need to find the best approach to upload those files.

Perhaps a new metadata property?
Perhaps a full entity type that is just an image?
Perhaps the 'attachments' section can flag the type of attachment as image?
Perhaps there can be an 'attachment' metadata property that can work as a 'general field'.  You upload a doc, an image, a sound file, and the system knows how to interpret it?
There is an image/media library where you can choose from?

**Comment by RafaPolit** [comment]
We have discussed this and voted in favor of an 'Attachment field type' on the templates configuration options.  That would allow for any type of document to be attached as a metadata property.  Those files can be downloaded for any type.   If we detect a valid HTML image file (jpg, png or gif), the property will display the image instead of the file.

It would be useful if @txau and @kjantin gave feedback regarding this solution.

**Comment by RafaPolit** [comment]
Waiting for feedback from Matchbox to better understand the requirement.

**Comment by kjantin** [comment]
This feature is no longer a priority and has been removed from the milestone related to supporting non-PDF file types

**Comment by danicatalan** [comment]
This has been requested by a new project:

- Have a property that supports upload and render multiple images. Users can click on each image to expand it.
- Select one image as a custom picture (related to #817).

Still not a priority but I think is worth mention this information here.
