### ISSUE TITLE
Styles not loaded properly on Entity viewer

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#883]
In Entity viewer, the styles are not loaded properly, maybe because a class name change on a parent element.

Is not just the titles, also the links, the lists...

![image](https://cloud.githubusercontent.com/assets/6364153/24141799/e405dbec-0e24-11e7-850c-fdff913cd4b9.png)

These are the default styles for metadata. They are loading properly on sidepanel:
![screen shot 2017-03-21 at 10 55 48](https://cloud.githubusercontent.com/assets/6364153/24141847/06910cea-0e25-11e7-8757-c42760d7c981.png)

**Comment by RafaPolit** [comment]
If I remember correctly you removed the 'aside' and nested the viewer inside another container for it to show either metadata or the connections.  That could have messed with the CSS selectors.

**Comment by danicatalan** [comment]
@RafaPolit thanks for the info. I removed the aside parent and specify both .sidepanel and .entity-viewer as parents for those styles.
