### ISSUE TITLE
Unify Library and Uploads sections

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#887]
We want almost the same functionality for the Library and Uploads, but showing published or unpublished documents respectively. To avoid duplication of code, both sections need to use the same code as much as possible.

- [ ] Add a "New Entity" button to the top of the uploads section
- [ ] Add "No Template Selected" to the list of types in the filters panel
- [ ] Do not use the filters config in the uploads section.

**Comment by txau** [comment]
@konzz Is this a duplicate? #862

**Comment by danicatalan** [comment]
- [ ] Move "No template" to the top of filters.
- [ ] Rename "No template" with "No type" on filters.
- [ ] Rename "Metadata required" to "No type" on cards.

cc @konzz
