### ISSUE TITLE
Check if re-uploading a document deletes TOC entries, and add TOC to the alert warning

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#889]
Check if re-uploading a document deletes TOC entries, and add TOC to the alert warning

**Comment by RafaPolit** [comment]
TOC is not being deleted.

**Comment by txau** [comment]
@RafaPolit I think TOC and text references should be deleted. Connections should be kept.

**Comment by RafaPolit** [comment]
That is the exact behavior that has been merged and the current warning updating to explain that.
