### ISSUE TITLE
Add a help text to the filters section

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#890]
Users have no clue what this section is for. It could be easily fixed adding a help text.

![screen shot 2017-03-23 at 10 08 12](https://cloud.githubusercontent.com/assets/489831/24240101/bcfcf05c-0fb0-11e7-854f-1e0df6f31e6c.png)

**Comment by danicatalan** [comment]
![image](https://user-images.githubusercontent.com/6364153/31344784-f6489d92-ad13-11e7-8780-bd7d3dcd84e1.png)

The code is available in `890-filters`.

What do you think about the copy?
