### ISSUE TITLE
Add user feedback when large database changes would take more than a fraction of a second

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#897]
When changing a template property name, or other processes that would take longer than a fraction of a second, give some feedback like: 'working...', a cog, a progress line, etc.

**Comment by txau** [comment]
@RafaPolit is this fixed with the load bar?

**Comment by txau** [comment]
Moreover, our load balancer is capping the connection timeout to 30 seconds, so we probably need to use socke.io or similar to keep the connection alive and let user know.

**Comment by txau** [comment]
This has a progress bar now.
