### ISSUE TITLE
Global 404 for non-existing instances

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#910]
@RafaPolit commented that non-existing instances (like https://abetterrafa.uwazi.io) are pointing to africog.

We need to redirect all those requests to a new page with information about the redirection (the instance doesn't exists) an some useful links to allow user navigate and find more info.

This will not solve our 404 for not founded pages on individual instances.

Notify Albert when this is ready.

**Comment by kjantin** [comment]
To implement when the new website is ready so we can make a really useful 404 page.

**Comment by danicatalan** [comment]
Don't confuse our internal 404 with this global 404. This is common on SASS:

![image](https://user-images.githubusercontent.com/6364153/27288182-43dbeef8-5506-11e7-9b71-c0f1bebec85f.png)

**Comment by daneryl** [comment]
this is fixed on the web server, changed 404 for [444 No Response](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes), all not existing servers will just respond this on http and https connections. no 404 needed for this, only for the internal app not found requests.

**Comment by danicatalan** [comment]
Great, thanks @daneryl!
