### ISSUE TITLE
Cannot access 'drag and drop' box when browser window is made smaller

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#922]
When I make my browser window smaller (but not super small) on Firefox, the main navigation buttons cover up the 'drag and drop' box in the upload section:
![image](https://cloud.githubusercontent.com/assets/354426/25051498/f59b6ff8-211a-11e7-9e02-9c44aea1d104.png)

(also, the EN box seems a bit shorter than the ES box)

**Comment by danicatalan** [comment]
We need to improve the nav menu in general. What do you think @kjantin?

**Comment by kjantin** [comment]
I don't know. I suppose everything could always been improved.

**Comment by kjantin** [comment]
Drag and drop improvements in progress here #555

**Comment by danicatalan** [comment]
Closing in favour of #1070
