### ISSUE TITLE
Search box inside documents

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#927]
- [ ] Be able to search words inside a document.
- [ ] List all the results on a ¿sidepanel?. If a user clicks on a results, it will scroll to the page where the result is (like relationships).

- [ ] Related with #861: If a user search on Library and clicks on the card, we will show all the results too.

**Comment by danicatalan** [comment]
This is the first concept about how to search inside a document. Right now the sidepanel looks poor just with the search box, but it would be awesome if we use this space to suggest keywords inside the document (¿more relevant words with Machine Learning?), so it won't be just a search tab - but a discover tab.

![search-document](https://cloud.githubusercontent.com/assets/6364153/25745793/ee86f2c8-31a0-11e7-889a-b923faada66a.png)

![search-snippet-document](https://cloud.githubusercontent.com/assets/6364153/25745794/ee89b076-31a0-11e7-990c-962f157c268d.png)

**Comment by txau** [comment]
I think this is ok, but I would reorder the buttons so that button that also exist in entity view always appear in the same position. We could even some visual separation between transversal buttons (appear both in entity and document view) and specific buttons for documents.
