### ISSUE TITLE
Rename documents / entities types inside admin

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#928]
**EDIT: Rename it as "types"**

- - - - -

There are a lot of confusion inside settings because of terminology. We will add the word **templates** after Documents and Entities: "Document templates" and "Entity templates" to make clear that admins are managing templates, not document / entities.

The changes will affect:
- [x] Left navigation panel
- [x] Titles in every section
- [x] Buttons to create new templates

![screen shot 2017-04-21 at 12 43 51](https://cloud.githubusercontent.com/assets/6364153/25274440/56d20ab4-2690-11e7-8a6c-728c95a42c7c.png)
![screen shot 2017-04-21 at 12 44 22](https://cloud.githubusercontent.com/assets/6364153/25274439/56ccf128-2690-11e7-9efa-3afecb601dfc.png)
![screen shot 2017-04-21 at 12 44 52](https://cloud.githubusercontent.com/assets/6364153/25274438/56a7333e-2690-11e7-85b9-7978c362a0bb.png)

**Comment by kjantin** [comment]
Or use "type" instead of "template"?
