### ISSUE TITLE
Unable to add metadata to uploaded document

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#929]
I uploaded a PDF and when I click on the card, I only see the option to "Save" in the right sidebar. When I click on "Save" it doesn't do anything. So I am unable to publish new documents. 
![image](https://cloud.githubusercontent.com/assets/354426/25292246/4eff9802-26a3-11e7-9e57-10140e6775cb.png)

**Comment by kjantin** [comment]
I came across this problem in this demo: https://hr-reports.uwazi.io/en/uploads

**Comment by daneryl** [comment]
fixed 60d49b1c8c707ac1b4bd8f9b0eab72a6a9317871
