### ISSUE TITLE
Labels with colors for Document types

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#93]

**Comment by danicatalan** [comment]
I updated the cards with the labels with colors:

![colors](https://cloud.githubusercontent.com/assets/6364153/16587747/5aebc82c-42cc-11e6-9838-a11f612af29e.png)

...but now they are all with default color (`.item-type-0`) that gets the `$c-primary` color as label background.

I have created a color palette with all the possible colours, and we need to discuss how to implement this in the react component and how the admin can select the color for every doc type.

![colors-palette](https://cloud.githubusercontent.com/assets/6364153/16587746/5ac5edfa-42cc-11e6-854f-63808350e3d6.png)

**Comment by txau** [comment]
@daneryl @konzz color is assigned to document types based on order of appearance. doc type 1 -> color 1, doc type 2 -> color 2 and so on so forth.
