### ISSUE TITLE
No clues to tell user that there are references attached to certain text in a document

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#930]
When I open a PDF in Uwazi that has references, I do not see any highlighted text that tells me that 'this paragraph has a reference'. I thought that feature existed before - maybe it it went away?

**Comment by danicatalan** [comment]
I will review the highlight opacity. Thanks @kjantin.

**Comment by kjantin** [comment]
That would be great @danicatalan, but it's more than just making the highlighting more clear. It's that when you look at the document and you are on the references tab, it would be helpful to know what text has a reference. For example: https://hr-reports.uwazi.io/en/document/41u2dwixsu2elim6q07qw4gqfr. The phrase "Universal Declaration of Human Rights" has a doc referenced to it, but I would never know that just looking at the PDF. Can we have that text highlighted so the user knows to click on it? Can the highlighting be different from the highlighting that comes when you click on the reference card in the right sidebar?

**Comment by danicatalan** [comment]
Is actually working:

![highlight](https://cloud.githubusercontent.com/assets/6364153/25344431/5ff41dec-2912-11e7-8ac0-56acaa9563ab.png)

But because an issue with PDF.js the opacity is to much subtle, so it seems there's no highlight on that text.

**Comment by danicatalan** [comment]
@kjantin I fixed the opacity issue with PDF.js and this is the difference between the old highlight and the new one:

![image](https://cloud.githubusercontent.com/assets/6364153/26144980/0e3f3ef6-3aeb-11e7-9d05-07561a5e0277.png)

![image](https://cloud.githubusercontent.com/assets/6364153/26145010/3074ca54-3aeb-11e7-8ba0-e21273c2ee33.png)
