### ISSUE TITLE
Add help text to upload a bunch of documents and not freeze the browser

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#934]
When a user uploads a lot of documents, the browser usually freezes.

We need to add a help text to let user is better to upload little bunch of documents to not freeze it.

**Comment by danicatalan** [comment]
We can start using the ProTip help (like the GitHub) to show contextual help that looks well without much effort. Also we can use this in other contexts (for example, on how multiselect something or in settings).

![screen shot 2017-04-27 at 13 41 11](https://cloud.githubusercontent.com/assets/6364153/25481825/4995e546-2b4f-11e7-854d-49f63d489db0.png)

**Comment by konzz** [comment]
Discussed in sprint planing, we think that the message doesn't tell the user about the possible "freezze" of the browser, and is a bit missleading.

Replace text with: For better performance, upload your documents in batches of 50 or less.

**Comment by danicatalan** [comment]
@konzz done! ;)
