### ISSUE TITLE
Make icon/flag optional

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#939]
Many users had indicated the icon/flag property is very annoying because it's something that appears by default in ALL the documents and entities forms but actually the use cases are very reduced.

We need to think how an admin can configure this on Settings to let them decide where they want to use it.

**Comment by bertver** [comment]
this is annoying for both clients and ourselves when doing configs - would like to suggest to upgrade priority level.

**Comment by txau** [comment]
@daneryl I added some CSS to your PR here: https://github.com/huridocs/uwazi/pull/1960

I noticed there is a glitch: once an entity had an icon and has been removed, the icon field appears as shown by default:

1. Edit an entity that has no icon set.
2. Note that the icon selector is hidden.
3. Show the selector and add an icon.
4. Save.
5. Edit that same entity.
6. Hit the "remove icon" button.
7. Save.
8. Edit that same entity again.
9. Note that the field is shown as default.

**Comment by txau** [comment]
@daneryl I guess my CSS/layout changes broke the unit tests.

**Comment by txau** [comment]
Fixed
