### ISSUE TITLE
Document connections show 'uploading' on already published documents

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#943]
Document connections show 'uploading' on already published documents
![screenshot from 2017-04-28 10-06-41](https://cloud.githubusercontent.com/assets/4309019/25534731/65d8bd7c-2bfa-11e7-818d-8f28c79364e2.png)

**Comment by konzz** [comment]
@danicatalan after investigating, looks like this is happening after you moved the <UploadEntityStatus> component into the <Item> component, not sure if it was strictly necessary for the CSS, can you review it please, and see if this can go back to the <Doc> component.

**Comment by danicatalan** [comment]
@konzz sure, assign to myself and I will check how to fix it.
