### ISSUE TITLE
Default instance should be English only

### ISSUE THREAD

**Issue by whyfrycek** [huridocs/uwazi#956]
*Current behaviour:*

When creating a new instance, it is both in English and Spanish.

*Expected behaviour:*

An instance only comes with one language as default. This would be English

*Browny points:*

Documentation for devevelopers to select languages on set up

Add language management to interface

**Comment by daneryl** [comment]
Blank state should have only english, and admin user should have a default admin role.

**Comment by txau** [comment]
Already fixed.
