### ISSUE TITLE
Add the "pages" and "menu" features to user documentation

### ISSUE THREAD

**Issue by whyfrycek** [huridocs/uwazi#957]
The "pages" and "menu" feature are currently not documented - both would be helpful, since one user just had a question about them.

**Comment by kjantin** [comment]
These are documented here:
https://github.com/huridocs/uwazi/wiki/Create-pages 
https://github.com/huridocs/uwazi/wiki/Configure-navigation-menu-links
These pages are found under the 'Manage user settings' section. Is there more info I should include?

**Comment by whyfrycek** [comment]
Oops! Totally overlooked them. They are perfectly fine - I think what maybe we can improve is that they are under user settings, which makes sense from the application logic, but was not how I was looking at it as a "user". Maybe we can find a better label or split the actual user settings and the parts that are actually about content creation?

**Comment by RafaPolit** [comment]
I agree these are not 'user settings'.

Our Settings section includes both actual user settings like recovery mail and password and the entire site configuration.

I agree that they should be separated in the user guide.

**Comment by kjantin** [comment]
I think it would make sense to change the user guide if we change the layout for how people manage the user settings and site configurations. Currently, it's all under _Settings_ in Uwazi, so I have updated the user guide to read "Manage settings" instead of "Manage user settings".

**Comment by whyfrycek** [comment]
Thanks, that should help! I think I simply overlooked it as a subheading, despite the labelling being perfectly clear.

My point was that I didn't suspect pages in particular under settings. It's good to for now mirror the interface, but that is expecting the user to know that that is the place they need to look for. Let's think about that for future iterations of the guide.
