### ISSUE TITLE
Prevent sending entire entities when saving metadata to prevent possible data loss.

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#959]
The current metadata save is sending the entire entity as loaded in client and replacing the entire contents of the entity with the sent data.

If two people are working on the same entity and one is working on attachments, for instance, then saving the metadata from the other computer will override the entire entity, loosing wanted changes.

The metadata save should only send metadata.

**Comment by txau** [comment]
I'd say we need conflict detection, probably optimistic offline lock: https://martinfowler.com/eaaCatalog/optimisticOfflineLock.html
