### ISSUE TITLE
Implement user roles

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#963]
Previous issue #953 

Any user will be able to:
- View all the documents, entities, properties, connections, etc in Uwazi (but cannot edit, create, or delete anything)
- User the search and filter functionalities

**Editor** will be able to:
- Do all the things that a User can do
- Upload documents and create entities
- Delete documents and entities
- Organize the collection (as defined in the user guide), including: apply properties, create connections and references, create a table of contents
- Add/edit translations

**Administrator** will be able to:
- Do all the things that an Editor can do
- Manage settings (as defined in the user guide)
- Configure the information architecture (as defined in the user guide), including: create document and entity types/templates, create dictionaries, name connections
- Configure filters
- Add and delete users

ToDo:
- [x] Users have a property "role" that can be "admin" or "editor"
- [x] API needsAuthorization middleware should be a function that receives a list of roles like: `needsAuthorization(["admin", "editor"]);`
- [x] Client NeedsAuthorization receives a roles prop: `<NeedsAuthorization roles={["admin", "editor"]}>`
- [x] Server side rendering should properly redirect to library loged users that are not authorized for that route
- [x] Create migration to add role admin to all current users

**Comment by tuxpiper** [comment]
May I ask about adding entries to dictionaries? Who would be able to do that?

imho, in many cases there would be value in Editors being able to do that.

**Comment by kjantin** [comment]
@tuxpiper our team could see both sides of this:
1. You might have a very specific data model with specific dictionaries that you wouldn't want edited by anyone but the administrators, especially if you plan to have many editors adding and editing information in the system, or
2. There is more flexibility in your approach and it would be easier to allow your Editors to add/edit dictionaries so they wouldn't have to go through an Admin each time they wanted to add a new term. 
We were leaning towards the first option, but if you think the second makes more sense for Japiqay, then we could implement that.

**Comment by tuxpiper** [comment]
Thank you @kjantin ! For Japiqay, it will all depend on what ends up being in a dictionary :) Let's tackle this detail as part of the modelling discussion.
