### ISSUE TITLE
Reorder tabs on sidepanel

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#964]
Related to #927.

This is sidepanel tabs on Entities:

![image](https://cloud.githubusercontent.com/assets/6364153/25809118/60eabcb0-340c-11e7-8e88-6e94d60944fc.png)

And this is sidepanel tabs on Documents:
![image](https://cloud.githubusercontent.com/assets/6364153/25809132/691d8ade-340c-11e7-80a1-4c2784197d63.png)

We need to reorder those tabs to be more consistent in both viewers (some icons are used in both while others are specific for documents) and also think about some kind of visual separation between them.

**Comment by danicatalan** [comment]
What do you think about this tabs order?

![tabs-order](https://cloud.githubusercontent.com/assets/6364153/26112496/5908c4c2-3a58-11e7-9a8e-3bc31696eb96.png)

I don't feel very comfortable moving the references away from connections, but it makes sense to maintain the common tabs always together. Any new idea on how to rearrange them?

**Comment by txau** [comment]
@danicatalan what do you understand by "common tabs"? The way I see it, text references and table of contents are common tabs in the sense they are text tools.

**Comment by danicatalan** [comment]
@txau I understand by common tabs this two groups:

- Text tools: Table of Content, Text references.
- Info tools: Metadata, Connections, Attachments.

This is how I split the tabs on the design and for me is the best option. I had doubts because references and connections seems related too, but as I can see you have the same way to see the groups.
