### ISSUE TITLE
Implement full text search

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#965]
Implement #861 + #927 

# Document viewer

We will add a new tab on Documents called **Search**. This tab looks poor just with the search box, but it would be awesome if we use this space to suggest keywords inside the document (¿more relevant words with Machine Learning?), so it won't be just a search tab - but a discover tab. 

![search-document](https://cloud.githubusercontent.com/assets/6364153/25745793/ee86f2c8-31a0-11e7-889a-b923faada66a.png)

When a user performs a search, all the words are highlighted on the document and appears on the sidepanel. Clicking on the sidepanel item scrolls automatically to the related paragraph (like relationships).

![search-snippet-document](https://cloud.githubusercontent.com/assets/6364153/25745794/ee89b076-31a0-11e7-990c-962f157c268d.png)

# Library

When a user uses the searchbox on Library, we will render the first snippet of text in 2 lines with the keyword highlighted and also a little **+X results** that will help users understand the magnitude of the keyword inside the document.

![search-snippet](https://cloud.githubusercontent.com/assets/6364153/25745467/4a11cb88-319f-11e7-9abc-a1dade943e23.png)

If the user clicks on the card **while performing a search**, all the snippets will appear on the sidepanel. That way a user can review all the snippets without opening the document. Also is very useful if you want to compare over the documents quickly, because you can click on differents cards and see the snippets without loosing your context.

![search-snippet-active](https://cloud.githubusercontent.com/assets/6364153/25745466/4a11500e-319f-11e7-915c-c27888f8f80e.png)

The user can refine the search on the search box inside the sidepanel, but won't affect the global search on the library, just the sidepanel. Clicking on the item, the document opens and the user goes automatically to the page.

We will keep this sidepanel inside the document so the user won't lose the results and will be able to continue researching inside the doc.

**Comment by kjantin** [comment]
This looks great, @danicatalan !

**Comment by txau** [comment]
@danicatalan I would place the page number under the snippet and make the snippet wider.

**Comment by danicatalan** [comment]
This is implemented on `965_full_text`, but after talking with @daneryl, we decided to spend some time to make another iteration and review the changes on the branch to improve some UX issues.

I self-assign this to review it this week.

**Comment by danicatalan** [comment]
These are the changes for the implementation of full text search on our app:

![screen shot 2017-06-20 at 11 53 26](https://user-images.githubusercontent.com/6364153/27327515-1ea9014e-55af-11e7-959c-a159e2abaf4d.png)

- [ ] Move search box above the document list.
- [ ] Align document counter and sort by below the search box.
- [ ] Make Search icon inside the box clickable. It will trigger the search.
- [ ] Hide suggestions. We will improve the results in other issue.
- [ ] Make page link inline with snippet text.
- [ ] Add page link functionality (#1021).

**Comment by danicatalan** [comment]
@daneryl we need to discuss when are we going to implement the new suggestions. Is not a priority, but maybe you want to review how the suggestions are hide right now and modify them (by CSS, not by JS).

Also we will need to review a lot of E2E, we can do that after completing the above list of tasks (please edit the list if you find more tasks to do).

**Comment by danicatalan** [comment]
Elasticsearch is currently configured by UI, not by document. We have to know each document's language to perform good searches.

We had implemented a **automatic language detection** library that assign languages while documents are uploading. This will allow Elasticsearch to use stopwords locally for each document (in both document viewer and library), regardless the UI language.
