### ISSUE TITLE
Cards: improve border rendering on the “View document” icon (add dark grey border)

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#97]
![screen shot 2016-06-01 at 14 53 27](https://cloud.githubusercontent.com/assets/489831/15710076/afc6aa30-2808-11e6-93bc-e2d8698f548b.png)

**Comment by danicatalan** [comment]
This was solved when rounded border was removed.

![card](https://cloud.githubusercontent.com/assets/6364153/16387102/b940deb0-3c93-11e6-9e32-13bb254963b3.png)
