### ISSUE TITLE
Add ability to track website stats: number of visitors, what they visit, etc

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#971]
_As a user, I want to know how many people are coming to visit my Uwazi instance, what they are viewing, and how they are using the site. _

**Comment by txau** [comment]
What kind of support for analytics? I guess we should bet for an minimum viable feature with Piwik (https://piwik.org/).

Alternatively we could go for Google Analytics first, but you know... google... -_-

**Comment by kjantin** [comment]
Request from Japiqay:

> Here are some examples of information we would like to present in a public front page:
> * Aggregates and numbers about content in the platform
> * Most used tags, most relevant document, most viewed
> * Information about politically exposed persons (view per politician, for example)
> * Rich tag overviews (when showing all docs in a category, presenting visual aggregates on top of the page with information about that category)

**Comment by danicatalan** [comment]
@kjantin We should differentiate between public stats and administrative stats. In this case, tracking user behaviours (number of visitors, what they visit) should be administrative stats rendered on an external dashboard (Google Analytics, Piwik) or an internal dashboard (custom tracking).

Google Analytics seems a straight forward solution to that. I would chose this tool for a quick implementation and let them see how many users are visiting their collections and which kind of content their are consuming.

In the future it will be a good idea to track this internally on a dashboard inside Settings and remove GA dependency.

**Comment by kjantin** [comment]
The team decided to explore Google Analytics as a short term solution for this.

**Comment by danicatalan** [comment]
Can we review this issue?

I added the Analytics Tracking ID to Settings and Google Tag Assistant (a Chrome extension to detect Google services on a website) detects the Analytics Tracking ID but there's an alert with the non-standard implementation.

![image](https://user-images.githubusercontent.com/6364153/29307425-19d83f80-81a2-11e7-8a60-b8fc827e56ba.png)

Also Google Analytics is not receiving traffic from _cejil.uwazi.io_.

![image](https://user-images.githubusercontent.com/6364153/29307488-678e14ca-81a2-11e7-8833-d2f9ee10cb9e.png)

**Comment by konzz** [comment]
@danicatalan can you share the link to that "Non-standard implementation" an screenshot is not very useful here.

**Comment by danicatalan** [comment]
@konzz sure!

https://support.google.com/tagassistant/answer/3207128?ref_topic=2947092#nonstandard

**Comment by danicatalan** [comment]
Now it's working propertly, I'm closing this issue.

![image](https://user-images.githubusercontent.com/6364153/29361885-cac6c284-8289-11e7-9e8f-04fe258ce287.png)
