### ISSUE TITLE
Visualisation of the countries that are connected to our cases

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#976]
~~"As an administrator of our Uwazi instance, I'd like to be able to create a geographical map of all the countries that are included as properties (or entities) in our collection, allowing visitors/users to click on the country and be brought to a filtered collection based on that country."~~

~~Example: the map on the Inter American Caselaw Analyser http://cejil.cla.huritech.org/en/~~

_"Understanding that a geographic map is difficult to render and use on mobile phones, and that these kinds of maps can distort the data that it is meant to represent (because of sizes of countries, etc), I would like an accurate and usable visualisation of the countries that are connected to our cases in Uwazi. Something like the list on the left side of http://caselaw.ihrda.org/country/"_

**Comment by kjantin** [comment]
Maps, as a tool for visualising data in your Uwazi collection, has some problems. Let's take a map to represent countries, for example:
- If your collection only includes certain countries, what can be inferred by excluding some countries? How would that render in a map? Would it tell the user that there are no cases or decisions related to that country? Or just not in your collection?
- From a usability perspective, some countries may be so small in relation to other countries on the map that users won't even see that it's there for them to click on. This is relevant for Latin America and the Pacific Islands, just to name a few examples. 

If the map is only meant to provide something visually pleasing and engaging for users, we'd like to explore developing something that is more helpful. 

We will be exploring helpful data visualisations and dashboards for Uwazi within [this Milestone](https://github.com/huridocs/uwazi/milestone/4). One idea to tackle this request for a map is to instead display a list of countries (so each country is represented equally) with some data represented in numbers and bars next to each country. See http://caselaw.ihrda.org/country/ (the left side of this page).

**Comment by kjantin** [comment]
I have updated the title and description of this issue to more accurately represent the user's request.

**Comment by txau** [comment]
Addressed in the geolocation feature.
