### ISSUE TITLE
Add ability to hide "Date added" field from cards

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#978]
_"As an Uwazi administrator, the "Date added" field is not important for our documents and add unnecessary data to the cards. However, I cannot delete this field because it is a default field (it exists for every template I create) and it is locked. Can this be unlocked to allow admins to delete this field?"_
![image](https://cloud.githubusercontent.com/assets/354426/25957494/74b0bd58-363c-11e7-8593-deac184f9d76.png)

**Comment by konzz** [comment]
That property may be very useful for other purposes like database migrations, and we shouldn't remove it, the idea of that field, is to tell the users that the property exists and they don't need to create it in case they want it. But I understand that they property always appears in the cards and can be frustrating, the option to hide it in the cards, or don't show it by default would be possible.

**Comment by kjantin** [comment]
Thanks for explaining this @konzz ! I just updated the issue to reflect this change. cc @danicatalan

**Comment by RafaPolit** [comment]
This is actually the configured behavior.  The date-added field will only show if selected as a sorting option on the library.  This can be overridden by configuring the sorting priorities correctly.

There is a bug that is preventing proper configuration of sorting priorities and it is being resolved in #999

**Comment by RafaPolit** [comment]
Rather than have the option to hide the date added (because when intentionally selecting date added as sorting order we want it there), we are going to configure a default sorting property for the collection so anyone can have whatever filterable property they want as option for default sorting.

This is described in #1004
