### ISSUE TITLE
Allow admins to create two labels for relationships 

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#983]
It would be helpful to be able to reflect relationships between documents/entities that are more complex than can be captured in one label. Often, a relationship description that makes sense in one direction (e.g. Kristin is the mother of Nolan) doesn't make sense if you switch around the subject/object (e.g. Nolan is the mother of Kristin - nope). Can we allow users to capture these more complex relationships?

Here's how CiviCRM tackles this issue ([found in their guide](https://docs.civicrm.org/user/en/4.7/organising-your-data/relationships/)):

> Enter descriptive labels for the relationship type you are creating in the Relationship Label-A to B and Relationship Label-B to A fields. The Relationship Label-A to B field describes the relationship between Contact A and Contact B; the Relationship Label-B to A field describes the relationship between Contact B and Contact A.
> - Some relationships can be described by the same label in both directions; in these cases you can enter the Relationship Label once in the Relationship Label-A to B field. For example, when describing the relationship between two domestic partners named Sylvia and Audre, you can say that Sylvia is the "Partner of" Audre and Audre is the "Partner of" Sylvia. Therefore you would enter the "Partner of" label only in Relationship Label-A to B field, leaving the Relationship Label-B to A field blank.
> - In other situations one Relationship Label cannot be applied in both directions; in these cases you need to enter different Relationship Labels in each of the Relationship Label fields. For example, you can say that Kiyoshi is the "Grandparent of" Yuki but you cannot say that Yuki is the "Grandparent of" Kiyoshi. Therefore you would enter the "Grandparent of" label in the Relationship Label-A to B field and either "Grandchild of" or "Grandparent is" in the Relationship Label-B to A field.

An example closer to our use-case would be:
Document A = a court decision
Entity B = a judge
Relationship Label A to B = a court decision "was decided by" a judge
Relationship Label B to A = a judge "made the decision on" a court decision

**Comment by kjantin** [comment]
It would also be nice to be able to add a description of the relationship/connection.

**Comment by txau** [comment]
@kjantin both supported in the new relationships.
