### ISSUE TITLE
Add thesauri save button at bottom of page

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#992]
The list of thesuari for themes/topics of OAU/AU documents has become rather long, made me wonder whether it would be possible to add a 'save' button at the bottom of the page or list of thesauri so the content manager need not scroll back up to save everytime...

**Comment by danicatalan** [comment]
This is the design to allow users saving in long lists of items without scrolling up. It's just implemented in Dictionaries but I will think about applying the same concept to other sections inside settings.

![image](https://cloud.githubusercontent.com/assets/6364153/26593424/4bc19020-4564-11e7-9514-2cadee31e2b1.png)

I also cleaned some CSS related to panel headers and panel footers, and changed all the buttons that doesn't save into primary color (blue).

**Comment by RafaPolit** [comment]
Maybe the round green save button that is always at the bottom of the side panel is a nice and consistent way of having the save button always visible?

**Comment by danicatalan** [comment]
@RafaPolit I like the idea, we must review all the Settings UI to correctly implement this through all the sections but it can work:
![floating-button](https://cloud.githubusercontent.com/assets/6364153/26620223/33c4f240-45e2-11e7-82f9-c05c144b3eae.png)

**Comment by danicatalan** [comment]
Added this new design in whole Settings. @RafaPolit can we review the PR together?

**Comment by txau** [comment]
@danicatalan are those floating buttons? Or now we only have the save buttons at the end?

**Comment by danicatalan** [comment]
@txau they are the same buttons you can find on sidepanel or entities, so every action (like save) will be always on the same place on documents and settings.

![screen shot 2017-06-07 at 18 40 50](https://user-images.githubusercontent.com/6364153/26890157-e247484e-4bb0-11e7-88d3-97ca402d5dad.png)

![screen shot 2017-06-07 at 18 42 31](https://user-images.githubusercontent.com/6364153/26890223-191e1708-4bb1-11e7-9ace-970623efd8f6.png)

**Comment by RafaPolit** [comment]
Yes @txau , they are floating buttons. The idea was to have them always available to prevent the user needing to scroll or either up or down to find the buttons.

**Comment by txau** [comment]
@RafaPolit good. ty.
