### ISSUE TITLE
Add help text to user interface that will explain which permissions are assigned to each role

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#997]
Add help text to user interface that will explain which permissions are assigned to each role as described in #953

**Comment by kjantin** [comment]
More information on these roles:
* A _visitor_ (no account needed) is able to view, search and filter all the documents and entities in Uwazi, as well as their properties, connections, etc.
* An _editor_ is able to do all the things that a _visitor_ can do and additionally: upload documents and create entities, delete documents and entities, organise the collection by applying properties, creating connections and references, creating a table of contents, and add/edit translations.
* An _administrator_ is able to do all the things that an _editor_ can do and additionally: manage site settings and configuration, add/delete users and assign roles, configure filters, and configure the information architecture by creating document and entity types, creating dictionaries and naming connections. 
  
Well, here's some draft text @danicatalan, but I think what would be idea would be a table of permissions on the left, roles on the top, and then an "x" in the box to show which permission goes with which role. Can we do that?

**Comment by danicatalan** [comment]
@kjantin I was thinking in something more simple like this:

![image](https://cloud.githubusercontent.com/assets/6364153/26142326/569f3f26-3ae0-11e7-94c5-9ca1ef25a1fa.png)

The table is ok when the user roles are complex but right now, with just to profiles and no option to edit the permissions, I will keep this as simple as possible.

**Comment by kjantin** [comment]
yes, great! do you think it would be helpful to include any info on what _visitors_ are able to do? maybe that's just too much info and it's already obvious...

**Comment by danicatalan** [comment]
@kjantin I think it's too obvious...

**Comment by kjantin** [comment]
Ok. Let's def go with your design. It's really good.
